rook/rook

build/release/Makefile
=> build: remove extraheader from git config

.github/workflows/canary-integration-test.yml, tests/scripts/github-action-helper.sh
"metadataDevice" field in host-based cluster is not tested yet.
**Checklist:**
- [o] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [o] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [o] Unit tests have been …
=> test: add canary integration test for osd with metadata device

Documentation/Upgrade/health-verification.md
* Make "Status Output" command directly usable on a copy-and-paste basis
* Link to 'Rook toolbox' which can be helpful if somebody does not have a toolbox running
No existing issue known.
**Checklist:**
(x) Link does not function: https://rook.io/docs/rook/latest/development-flow.html
=> Improve Upgrade Health verification page

ROADMAP.md
Add planned features to the list for 1.10 planning.
**Checklist:**
=> docs: Update the roadmap for 1.10

.github/workflows/commitlint.yml, .mergify.yml
=> ci: update doc link in ci

deploy/examples/create-external-cluster-resources.py
external-script: remove signature import
remove signature import as it is not required.
external-script: clean import section
import all the libraries at top
Resolves #
**Checklist:**
=> external-script: remove signature import

pkg/operator/ceph/csi/controller.go
If some clusters don't have their monitors up and running, we don't have
a clusterInfo (internal detail struct). We don't want to block the csi
controller reconcile if all the clusters are not ready. So let's proceed
with the elements that are ready and reconcile again to see if others
have made progress.
Resolves #
**Checklist:**
=> csi: do not block the reconcile if all clusters are not ready

.docs/macros/includes/main.py, tests/scripts/pythonwebserver/server.py
formatting other python files using black
Resolves #
**Checklist:**
=> ci: use python formatting tool black

.github/workflows/canary-integration-test.yml, Documentation/CRDs/ceph-cluster-crd.md, deploy/examples/create-external-cluster-resources.py, deploy/examples/import-external-cluster.sh
For using restricted auth users we need to update the
restricted users in the Storage class, so updating
it is in the JSON output for the external cluster
Resolves #
**Checklist:**
=> csi: make storage class updated with csi-users in external cluster

deploy/examples/create-external-cluster-resources-tests.py, deploy/examples/create-external-cluster-resources.py
`black` is python formatter tool which
automatically formats python files without
manual changing. just run `black <python-file>`
and done.
(cherry picked from commit 00f21c08666d18cbb6e3210be39f4ef49e71ea67)
Resolves #
**Checklist:**
=> external: format python files using tool black

Documentation/CRDs/ceph-cluster-crd.md
Some optional Flags are already added
for external script but not documented,
So to expose the functionality to users
adding them to the doc list
Resolves #
**Checklist:**
=> doc: update ceph external cluster flags

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox.yaml
The patch release is updated in the docs and examples to v1.9.6
**Checklist:**
=> build: Update release version to v1.9.6

.github/workflows/linters.yaml, deploy/examples/create-external-cluster-resources.py
ci: add check for unused or dead code in py file
adding multiple linters like black for python
which will help us with better quality of python code.
Also, in the future, we'll aim to get errors for warnings also but
there are a lot of warnings and it is difficult to fix at once.
core: fix lint issue in python files
Closes: https://github.com/rook/rook/issues/10374
Resolves #
**Checklist:**
=> ci: add check for unused or dead code in py file

.github/workflows/docs-check.yml, Makefile, build/release/Makefile, build/release/requirements_docs.txt, mkdocs.yml
* ci: add docs-check flow - Checks for broken docs links
* docs: use exclude plugin to ignore the readme.md file
* build: add separate docs build and preview targets
**Checklist:**
=> build: add separate docs build and preview targets

Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph-cluster/templates/cephobjectstore.yaml, tests/integration/ceph_upgrade_test.go
Signed-off-by: Markus Schmidleitner <markus.schmidleitner@ocilion.com>
Use correct namespace for provisioner in cephobjectstore template
Resolves #10153
**Checklist:**
=> helm: use correct namespace for provisioner in cephobjectstore template

.github/workflows/daily-nightly-jobs.yml
ci: skip daily nightly job on fork
Resolves #
**Checklist:**
=> ci: skip daily nightly job on fork

.github/workflows/synk.yaml
ci: skip snyk ci from running on fork repo
Resolves #
**Checklist:**
=> ci: skip snyk ci from running on fork repo

design/ceph/object/ceph-sse-s3.md
The design doc for adding support in RGW for handling s3 requests with
sse:s3.
Resolves #
**Checklist:**
=> docs: design doc for supporting aws sse:s3 in RGW

deploy/charts/library/templates/_cluster-role.tpl, deploy/examples/common.yaml
Reduce the RBAC scope to the minimum necessary
permissions for rook to operator
Resolves #
**Checklist:**
=> core: remove all wildcard permissions in rbac definations

pkg/operator/ceph/pool/controller.go, pkg/operator/ceph/pool/controller_test.go
Signed-off-by: shalev.p <shalev.p@taboola.com>
Changed configureRBDStats behavior , remove dot postfix
Resolves #10574
**Checklist:**
=> Fix EnableRBDStats mgr

.github/workflows/rgw-multisite-test/action.yml, Documentation/CRDs/Cluster/ceph-cluster-crd.md, Documentation/Upgrade/ceph-upgrade.md, deploy/charts/rook-ceph-cluster/values.yaml, deploy/examples/cluster-external-management.yaml, deploy/examples/cluster-multus-test.yaml, deploy/examples/cluster-on-local-pvc.yaml, deploy/examples/cluster-on-pvc.yaml, deploy/examples/cluster-stretched-aws.yaml, deploy/examples/cluster-stretched.yaml, deploy/examples/cluster-test.yaml, deploy/examples/cluster.yaml, deploy/examples/images.txt, design/ceph/ceph-cluster-cleanup.md, images/ceph/Makefile, tests/framework/installer/ceph_installer.go
With the release of ceph v16.2.10 we update the operator base image and the default example install to configure v16.2.10.
**Checklist:**
=> build: Update examples to ceph v16.2.10

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox.yaml
For the patch release the operator version and example manifests are updated to v1.9.8
**Checklist:**
=> build: Update release version to v1.9.8

Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md, deploy/examples/filesystem.yaml
Signed-off-by: Gaurav Sitlani <gauravsitlani@riseup.net>
Resolves #
**Checklist:**
=> docs: CephFS mirroring updates around Peer Tokens

deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml, deploy/examples/monitoring/localrules.yaml
docs: Fix multiple spelling errors, improve wording
Upstream changes are in https://github.com/ceph/ceph/pull/47284
Signed-off-by: Anthony D'Atri <anthonyeleven@users.noreply.github.com>
Resolves #
**Checklist:**
=> Improve descriptions in localrules.yaml

deploy/examples/monitoring/localrules.yaml
Aligns the indentation of the rule definition for the pool rules array uniformly.
Resolves #10653
**Checklist:**
=> Correct indentation level for pool rules

.github/workflows/build.yml, .github/workflows/codegen.yml, .github/workflows/codespell.yaml, .github/workflows/crds-gen.yml, .github/workflows/golangci-lint.yaml, .github/workflows/helm-lint.yaml, .github/workflows/linters.yaml, .github/workflows/mod-check.yml, .github/workflows/push-build.yaml, .github/workflows/rbac-gen.yaml, .github/workflows/shellcheck.yaml, .github/workflows/stale.yaml, .github/workflows/synk.yaml, .github/workflows/unit-test.yml
Restrict the GitHub token permissions only to the required ones;
this way, even if the attackers will succeed in compromising your workflow,
they won’t be able to do much.
Included permissions for the action.
https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
Replaces #10438
**Checklist:**
=> ci: set permissions for github actions

deploy/examples/common-second-cluster.yaml
Added missing RoleBindings in examples or deploying CephClusters in multiple namespaces.
**Checklist:**
=> [MASTER] Bugfix RBAC second cluster

deploy/examples/nfs.yaml, design/ceph/ceph-nfs-ganesha.md
=> docs: SSSD-NFS design

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox.yaml
For the patch release update the examples and docs to v1.9.9
**Checklist:**
=> build: Update the release version to v1.9.9

.github/workflows/rgw-multisite-test/action.yml, Documentation/CRDs/Object-Storage/ceph-object-multisite-crd.md, PendingReleaseNotes.md, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, deploy/examples/object-multisite-test.yaml, deploy/examples/object-multisite.yaml, design/ceph/object/zone.md, pkg/apis/ceph.rook.io/v1/types.go, pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go, pkg/operator/ceph/object/controller.go, pkg/operator/ceph/object/controller_test.go, pkg/operator/ceph/object/objectstore.go, pkg/operator/ceph/object/objectstore_test.go, pkg/operator/ceph/object/spec.go, pkg/operator/ceph/object/zone/controller.go
User can define his desired endpoint list in Zone CR so that it will
overwrite the default service name for rgw.
Resolves #6432
**Checklist:**
=> rgw: add custom endpoint list option for zone

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
With the beta release of v1.10 the release version in the examples and docs is updated.
The upgrade guide is updated for v1.10, but not tested yet.
**Checklist:**
=> build: Update release version to v1.10.0-beta.0

tests/scripts/github-action-helper.sh
=> ci: fix multus depment cr link

Documentation/CRDs/ceph-client-crd.md, deploy/examples/sqlitevfs-client.yaml
I've added documentation that specifies how to use the `CephClient` CRD, along with how to use it specifically with the [Ceph SQLite VFS](https://docs.ceph.com/en/latest/rados/api/libcephsqlite/)
Resolves #10689 
**Checklist:**
- [-] Unit tests have been added, if necessary.
- [-] Integration tests have been added, if necessary.
=> docs: add examples for CephClient CRD use & libcephsqlite

pkg/operator/ceph/controller/spec.go
we need use `!=` for string comparision in bash instead of
`-ne`. Also, need to correct periodicity if condition to
make it work as expected.
Resolves #
**Checklist:**
=> core: fix logrotate bash check and periodicity logic

Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
Most of the users starts with single site, provide the steps to convert
existing cephobjectstore into multisite configurations.
Resolves #10416
**Checklist:**
=> docs: add steps to convert existing cephobjectstore into multisite

tests/framework/installer/ceph_manifests.go, tests/framework/installer/ceph_manifests_previous.go, tests/integration/ceph_upgrade_test.go
With the pending release of 1.10, the upgrade tests in master should be testing the upgrade from 1.9 to the master branch.
**Checklist:**
=> build: Test upgrade from 1.9 to master

.github/workflows/build.yml, .github/workflows/canary-integration-test.yml, .github/workflows/canary-test-config/action.yaml, .github/workflows/codegen.yml, .github/workflows/codespell.yaml, .github/workflows/commitlint.yml, .github/workflows/crds-gen.yml, .github/workflows/create-tag.yaml, .github/workflows/daily-nightly-jobs.yml, .github/workflows/docs-check.yml, .github/workflows/golangci-lint.yaml, .github/workflows/integration-test-config-latest-k8s/action.yaml, .github/workflows/integration-test-config-older-k8s/action.yaml, .github/workflows/integration-test-config/action.yaml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, .github/workflows/mod-check.yml, .github/workflows/push-build.yaml, .github/workflows/rbac-gen.yaml, .github/workflows/stale.yaml, .github/workflows/unit-test.yml, .vscode/settings.json, tests/scripts/create-bluestore-partitions.sh
Resolves #10698 
**Checklist:**
=> ci: ubuntu 18.04 is deprecated upgrade to ubuntu 20.04

pkg/operator/ceph/cluster/crash/crash.go
v1beta1 cron jobs have not been created by rook since k8s 1.21 and now are fully removed from K8s in 1.25. As long as we still support older than 1.21 we still need to attempt to delete the v1beta1 cron jobs in case they had been created before an upgrade. If the deletion fails, now we just log a debug statement since it is a normal condition, and continue with the v1 cron job creation.
**Checklist:**
=> core: Only log errors with v1beta1 cron job deletion

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox.yaml
Update the docs and manifests to release version v1.9.10
**Checklist:**
=> build: Update release version to 1.9.10

Documentation/Contributing/documentation.md
Improve the documentation around documentation building (e.g., mention targets for previewing docs).
**Checklist:**
=> docs: improve documentation about documentation building

pkg/daemon/ceph/osd/daemon.go, pkg/daemon/ceph/osd/daemon_test.go
Old lsblk can't detect bluestore signature.
So read the head of device and verify signature
as a workaround.
Resolves #10665
**Checklist:**
=> osd: fix osd detection logic for old lsblk

.github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, .mergify.yml, Documentation/Getting-Started/Prerequisites/prerequisites.md, Documentation/Getting-Started/quickstart.md, Documentation/Helm-Charts/ceph-cluster-chart.md, Documentation/Helm-Charts/operator-chart.md, pkg/operator/ceph/csi/csi.go, pkg/operator/ceph/csi/spec.go, tests/framework/installer/ceph_helm_installer.go, tests/framework/installer/ceph_manifests.go, tests/integration/ceph_base_block_test.go, tests/integration/ceph_base_file_test.go
Rook policy defined in #10809 is to support the most recent seven K8s releases, so we update the min version to 1.19 for Rook v1.10.
Resolves #10809
**Checklist:**
=> build: Update min version to k8s 1.19

pkg/operator/ceph/csi/cluster_config.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
remove duplicate word in comments
Resolves #
**Checklist:**
=> csi: remove duplicate word in comments

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the minor release update the docs and examples to v1.10.0.
**Checklist:**
=> build: Update the release version to v1.10.0

Documentation/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-storage.md
Step by step guide to share a PVC across namespaces.
Resolves #10370
=> doc: add documentation for sharing a CephFS PVC across namespaces

.github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml
I missed to remove older config for release
tests yaml.
Resolves #
**Checklist:**
=> ci: fix release tests configuration

tests/framework/installer/ceph_installer.go
The helm integration test was immediately removing both the cluster and the operator charts, without waiting for any resource deletion between the deletions. This causes intermittent failures in the test since the cluster CR and mon secret and configmap to never be deleted because the operator will be stopped before their finalizers can be removed. Now we wait for their finalizers to be removed before removing the operator chart.
**Checklist:**
=> test: Wait for resource deletion during helm uninstall

pkg/daemon/ceph/osd/daemon.go, pkg/daemon/ceph/osd/volume.go, pkg/operator/ceph/cluster/osd/provision_spec.go, pkg/operator/ceph/cluster/osd/spec.go
Simplify osd management code.
Resolves #
**Checklist:**
=> osd: refactor code

.github/workflows/build.yml, .github/workflows/codegen.yml, .github/workflows/crds-gen.yml, .github/workflows/rbac-gen.yaml, .github/workflows/unit-test.yml
Resolves #10896
**Checklist:**
=> ci: no need to copy working dir to GOPATH

design/ceph/ceph-nfs-ganesha.md
=> docs: add kerberos to nfs-ganesha design

pkg/operator/ceph/csi/predicate.go, pkg/operator/ceph/csi/predicate_test.go
findCSIChange will work only for single line values/configuration in the configmap. If the value is multiline, the regex will not
be able to indentify the change because of it no configurations will be applied to the csi driver. Removing this check so that if there is any update on the configmap, we will reconcile the csi driver.
Note:- This might look heavy, but updating the config map is not a frequent event.
Resolves #
**Checklist:**
=> csi: remove findCSIChange from predicate

.github/workflows/build.yml, .github/workflows/canary-integration-test.yml, .github/workflows/codegen.yml, .github/workflows/codespell.yaml, .github/workflows/commitlint.yml, .github/workflows/crds-gen.yml, .github/workflows/create-tag.yaml, .github/workflows/daily-nightly-jobs.yml, .github/workflows/golangci-lint.yaml, .github/workflows/integration-test-config-latest-k8s/action.yaml, .github/workflows/integration-test-config-older-k8s/action.yaml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-setup/action.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, .github/workflows/mod-check.yml, .github/workflows/push-build.yaml, .github/workflows/rbac-gen.yaml, .github/workflows/stale.yaml, .github/workflows/unit-test.yml, tests/scripts/create-bluestore-partitions.sh
Look at individual commit
Resolves #
**Checklist:**
=> ci: ubuntu 18.04 is deprecated upgrade to ubuntu 22.04

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the documentation and manifests to v1.10.1
**Checklist:**
=> build: Update the release version to v1.10.1

deploy/examples/create-external-cluster-resources.py
remove duplicate import urllib.parse which is handled below
with try and except no need to import separately. Also, change
the way to get the python version.
Resolves #
**Checklist:**
=> external: fix import errors for python2

go.mod, go.sum
Updating go-ceph module into latest version v0.17
Resolves #
**Checklist:**
=> build: update goceph module to v0.17

Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
Resolves #10958 
**Checklist:**
=> docs: clarify Object Pool CRD is same as Block Pool CRD

pkg/daemon/ceph/client/status.go, pkg/daemon/ceph/client/status_test.go, pkg/daemon/discover/discover.go, tests/framework/clients/cluster.go, tests/framework/utils/k8s_helper.go, tests/integration/ceph_base_deploy_test.go
1. Eliminate possible memory leaks of timer.
2. Eliminate duplicated events between udev events and kernel events.
3. Empty struct have the lowest size.
1. Eliminate possible memory leaks of timer.
2. Eliminate duplicated events between udev events and kernel events.
```
🍺 /root/go/src/rook/rook ☞ git:(notes) ✗ udevadm monitor
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent
KERNEL[2934697.068804] change   /devices/virtual/block/dm-3 (block)
UDEV  [2934697.073716] change   /devices/virtual/block/dm-3 (block)
KERNEL[2934701.359157] change   /devices/pci0000:00/0000:00:0b.0/virtio2/block/vdb (block)
UDEV  [2934701.392697] …
```
=> osd: optimize device probe

.github/workflows/canary-integration-test.yml, pkg/daemon/ceph/client/command.go, pkg/operator/ceph/client/controller.go, pkg/operator/ceph/cluster/cleanup.go, pkg/operator/ceph/cluster/cluster.go, pkg/operator/ceph/cluster/cluster_external.go, pkg/operator/ceph/cluster/controller.go, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/rbd/controller.go, pkg/operator/ceph/cluster/version.go, pkg/operator/ceph/controller/cluster_info.go, pkg/operator/ceph/controller/cluster_info_test.go, pkg/operator/ceph/csi/controller.go, pkg/operator/ceph/file/controller.go, pkg/operator/ceph/file/mirror/controller.go, pkg/operator/ceph/file/subvolumegroup/controller.go, pkg/operator/ceph/nfs/controller.go, pkg/operator/ceph/object/bucket/controller.go, pkg/operator/ceph/object/controller.go, pkg/operator/ceph/object/notification/controller.go, pkg/operator/ceph/object/realm/controller.go, pkg/operator/ceph/object/topic/controller.go, pkg/operator/ceph/object/user/controller.go, pkg/operator/ceph/object/zone/controller.go, pkg/operator/ceph/object/zonegroup/controller.go, pkg/operator/ceph/pool/controller.go, pkg/operator/ceph/pool/radosnamespace/controller.go, tests/scripts/github-action-helper.sh
Closes: https://github.com/rook/rook/issues/10812
Resolves #
**Checklist:**
=> nfs: fix nfs if multus is enabled

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox.yaml
For the patch release update the example manifests and docs to v1.9.11
**Checklist:**
=> build: Update the release version to 1.9.11

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the example manifests and docs to v1.10.2
**Checklist:**
=> build: Update the release version to 1.10.2

Documentation/Getting-Started/.pages, Documentation/Getting-Started/ceph-teardown.md, Documentation/Storage-Configuration/ceph-teardown.md
The cleanup guide is difficult to find under the storage configuration section with so many other topics. We also will show the cleanup guide from the getting started section to make it more discoverable.
Resolves #10953
**Checklist:**
=> docs: Symlink cleanup page to the Getting Started doc folder

Documentation/Storage-Configuration/Advanced/ceph-osd-mgmt.md
updated troubleshoot doc using common issues to reference krew plugin and added krew section for osd pugre.
Resolves #
**Checklist:**
=> docs: update troubleshoot docs and add krew uses

.github/workflows/canary-integration-test.yml, .github/workflows/canary-test-config/action.yaml, tests/scripts/deploy-validate-vault.sh
updating canary k8s version to 1.25.0 
Resolves #10530 
**Checklist:**
=> ci: update canary k8s version to 1.25.0

Documentation/Contributing/development-environment.md
Fixing the following broken note box in docs:
See here https://rook.io/docs/rook/v1.9/Contributing/development-environment/#install-helm
Resolves #
**Checklist:**
=> docs: fix notes in docs

.github/workflows/daily-nightly-jobs.yml, tests/framework/installer/ceph_installer.go, tests/integration/ceph_mgr_test.go
The ceph master images were recently renamed to main so we need to pick up the new tag.
**Checklist:**
=> ci: Ceph master images renamed to main

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox.yaml
Update the release version to v1.9.12
**Checklist:**
=> build: Update the release version to v1.9.12

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release we update the docs and example manifests to v1.10.3
**Checklist:**
=> build: Update the release version to v1.10.3

Documentation/Getting-Started/.pages, Documentation/Getting-Started/release-cycle.md
The release schedule and maintenance approach has been left as undefined until now to give flexibility to the maintainers to release as needed. But the community is asking for clarity around the planned release schedule so it is time to document the procedures.
**Checklist:**
=> docs: Document expectations for releases

deploy/examples/monitoring/rbac.yaml
Reduce the RBAC scope to the minimum necessary
permissions for rook to operator
Resolves #
**Checklist:**
=> core: remove wildcard permission in rbac

pkg/operator/ceph/pool/controller.go, pkg/operator/ceph/pool/controller_test.go
Signed-off-by: Avan Thakkar <athakkar@redhat.com>
Rook currently knows rbd pools only if they defined through `CephBlockPool`, so it overrides the config 
`mgr/prometheus/rbd_stats_pools` which may have already been set for pools external to Rook. Check config  before running set command and if there some existing pools append them to `enableStatsForCephBlockPools`.
Resolves #11056
**Checklist:**
=> operator: Don't remove existing pools for mgr/prometheus/rbd_stats_pools

.github/workflows/daily-nightly-jobs.yml
installing yq in daily nightly job and remove once the job is done
Resolves #10180 
**Checklist:**
=> ci: install yq in daily nightly job

.github/workflows/daily-nightly-jobs.yml
ci: the daily job is failing due to k8s communication
installing minikube and kubectl to see if that
works.
Resolves #10180 
**Checklist:**
=>  ci: clean daily arm job yaml and install minikube and kubectl

tests/framework/clients/nfs.go, tests/framework/installer/ceph_manifests.go, tests/framework/installer/ceph_manifests_previous.go, tests/integration/ceph_base_file_test.go, tests/integration/ceph_base_nfs_test.go
- ci: add nfs sna & restore e2e testcase
- ci: add nfs clone e2e testcase
Resolves #10895 
**Checklist:**
=> csi: Add nfs snap & clone ci

pkg/operator/ceph/object/admin.go
The `periodWillChange()` implementation to detect map keys to ignore. Previously, we relied on the `GoString()` method to output the same format always to determine the current path to the map[string]interface{} node, but that may change depending on the underlying implementation of go-cmp.
Instead, parse the go-cmp `Path` step by step and construct a JSON path to the node in a stable format.
Resolves #
**Checklist:**
=> object: fix logic for rgw period commit detection

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the examples and docs to v1.10.4
**Checklist:**
=> build: Update release version to v1.10.4

deploy/charts/rook-ceph-cluster/values.yaml
Adding `enableRBDStats: true` example in helm charts values.yaml
Resolves #
**Checklist:**
=> docs: adding enableRBDStats example in helm chart deployment

Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md
Fixes numbering in docs notes
Resolves #
**Checklist:**
=> docs: fix typo in numbering

Documentation/CRDs/Cluster/ceph-cluster-crd.md, Documentation/CRDs/Cluster/external-cluster.md, Documentation/CRDs/Cluster/host-cluster.md, Documentation/CRDs/Cluster/pvc-cluster.md, Documentation/CRDs/Cluster/stretch-cluster.md, Documentation/Upgrade/ceph-upgrade.md, deploy/charts/rook-ceph-cluster/values.yaml, deploy/examples/cluster-external-management.yaml, deploy/examples/cluster-on-local-pvc.yaml, deploy/examples/cluster-on-pvc.yaml, deploy/examples/cluster-stretched-aws.yaml, deploy/examples/cluster-stretched.yaml, deploy/examples/cluster.yaml, deploy/examples/images.txt, deploy/examples/toolbox.yaml, deploy/olm/assemble/metadata-common.yaml, design/ceph/ceph-cluster-cleanup.md, design/ceph/ceph-nfs-ganesha.md, images/ceph/Makefile, pkg/operator/ceph/nfs/security_test.go, pkg/operator/ceph/object/spec_test.go
core: upgrade ceph to latest release v17.2.5
Resolves #
**Checklist:**
=> core: upgrade ceph to latest release v17.2.5

.github/dependabot.yml
Dependabot workflow automation for updating dependency
Resolves #11215
**Checklist:**
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
=> bot: dependabot workflow automation for updating dependency

Documentation/Troubleshooting/performance-profiling.md
Added steps to collect live coredump and perf data for troubleshooting purposes.
Resolves #11151
**Checklist:**
=> docs: added steps to collect coredump and perf troubleshooting info

ROADMAP.md
The roadmap is updated with planned features for the v1.11 release targeted for January.
**Checklist:**
=> docs: Update roadmap for the v1.11 release

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox.yaml
For the patch release the examples and docs are updated to v1.9.13
**Checklist:**
=> build: Update release version to v1.9.13

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release the examples and docs are updated to v1.10.5
**Checklist:**
=> build: Update the release version to v1.10.5

deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go
=> object: mark endpoint as a optional field

Documentation/Storage-Configuration/Block-Storage-RBD/rbd-mirroring.md
the pool mentioned in docs didn't have hypen
doc ref: https://rook.io/docs/rook/v1.9/Storage-Configuration/Block-Storage-RBD/rbd-mirroring/#create-rbd-pools
[root@centos-4gb-hel1-1 rook]# kubectl get cephblockpool.ceph.rook.io/mirroredpool Error from server (NotFound): cephblockpools.ceph.rook.io "mirroredpool" not found
Signed-off-by: Deepika Upadhyay <deepika@koor.tech>
Resolves #
**Checklist:**
=> docs: update rbd-mirror doc

pkg/operator/ceph/cluster/crash/reconcile.go
Fixes #11321
I'm not sure what `request.Namespace` is, but it's probably wrong to use that within the loop over different namespaces. There's another occurence of `request.Namespace` in: https://github.com/rook/rook/blob/42dd82b6fda877b973821062ffb1451804f3218d/pkg/operator/ceph/cluster/crash/reconcile.go#L101
Not sure if that should be changed to something else, too.
**Checklist:**
=> crash: Fix a bug where crash collectors in wrong namespaces were deleted

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release the docs and examples are updated to v1.10.6
**Checklist:**
=> build: Set the release version to v1.10.6

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release the examples and docs are updated to v1.10.7
**Checklist:**
=> build: Update the release version to v1.10.7

Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-notifications.md
fix nodes in docs Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-notifications.md
**Checklist:**
=> docs: Fix notes in CephBucketTopic docs

Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
updated the outdated registry URL for the CSI sidecar images in the custom-images
Resolves #11463
**Checklist:**
[skip ci]
=> doc: update csi registry in custom-images

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the examples and docs to v1.10.8
**Checklist:**
=> build: Update the release version to v1.10.8

pkg/operator/ceph/cluster/cluster.go
closes: https://github.com/rook/rook/issues/11470
Resolves #
**Checklist:**
=> external: Dont call telemetry if the cluster is external

design/ceph/ceph-mon-pv.md
see more: https://github.com/rook/rook/issues/10470
Signed-off-by: Deepika Upadhyay <deepika@koor.tech>
Resolves #
**Checklist:**
=> docs: add a design doc proposal for mon zonal availability support

Documentation/Helm-Charts/operator-chart.md, Documentation/Storage-Configuration/Ceph-CSI/custom-images.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/spec.go
update all the kubernetes sidecars to the latest release.
Resolves #11507
**Checklist:**
=> csi: update sidecars to latest release

deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml, deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml, deploy/charts/rook-ceph-cluster/values.yaml
Resolves #11516
**Checklist:**
=> helm: storageclass secrets namespace made the same as the release namespace

Documentation/Helm-Charts/operator-chart.md, deploy/charts/rook-ceph/templates/configmap.yaml, deploy/charts/rook-ceph/templates/deployment.yaml, deploy/charts/rook-ceph/values.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/controller.go, pkg/operator/ceph/webhook.go, tests/framework/installer/ceph_settings.go
sadly, we need to disable webhook by default until we find solution to https://github.com/rook/rook/issues/10719
Resolves #
**Checklist:**
=> webhook: disable webhook by default

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the examples and docs to v1.10.9
**Checklist:**
=> build: Update the release version to v1.10.9

design/ceph/resource-constraints.md
Fix incorrect CRD name in documentation
Resolves #
**Checklist:**
=> docs: fix incorrect CRD name in documentation

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release the examples and docs are updated to version v1.10.10
**Checklist:**
=> build: Update release version to v1.10.10

build/release/README.md
Thanks to @travisn for providing his release procedure notes!
I think the whole document might need some more cleaning up as it initially spoke about using GitHub Actions to create the release branch/ tag.
**Checklist:**
=> docs: add release instructions

.github/workflows/rgw-multisite-test/action.yml, tests/scripts/github-action-helper.sh
=> test: add multisite bidirectional replication coverage

deploy/examples/create-external-cluster-resources.py
=> external: dont do rgw validation if python version < 3

pkg/operator/ceph/webhook-config.go
=> operator: fix webhook logging during deletion

Documentation/Getting-Started/.pages, Documentation/Getting-Started/glossary.md
Resolves #11367
**Checklist:**
=> docs: add glossary page

pkg/operator/ceph/object/notification/provisioner.go
rgw: handle insecure flag skip for object bucket notification in the tls config
Resolves #11629
**Checklist:**
=> rgw: handle insecure flag skip for object bucket notification in the tls config

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the docs and example manifests to v1.10.11
**Checklist:**
=> build: Update the release version to v1.10.11

deploy/examples/filesystem.yaml
Add comment regarding mds daemon placement to example file.
Resolves #11658
=> Add comment regarding placement restrictions.

pkg/operator/ceph/cluster/cluster.go
Set the rbd map default option to ms_mode=prefer_crc when v2 ports are used and encryption is disabled. If we dont pass/set the ms_mode in the map options, the kernel client will assume it's using v1 ports, and the map operation will fail.
This check is for a use-case where encryption is disabled, but v2 ports are used.
Using older kernels with v2 ports with/without rbd map options is not possible. The mapping will fail.
Resolves #
**Checklist:**
=> core: set rbd default map options

.mergify.yml
Add the mergify settings so backports can be automated to the release-1.11 branch and automatically merged after the CI is green.
**Checklist:**
=> ci: Update mergify for the 1.11 branch

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the new 1.11 branch set the beta release version to v1.11.0-beta.0.
**Checklist:**
=> build: Set the release version for the v1.11.0-beta.0

go.mod, go.sum
update https://github.com/advisories/GHSA-vvpx-j8f3-3w6h and upgrade thought about dependencies
Resolves #
**Checklist:**
=> build: update package dependencies

Documentation/Upgrade/ceph-upgrade.md, Documentation/Upgrade/rook-upgrade.md
Resolves #11725 
**Checklist:**
=> docs: update docs to prepare for v1.11 release

deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml, deploy/examples/monitoring/localrules.yaml
Update rook prometheus localrules files to align with ceph/ceph prometheus alerts
Resolves #
**Checklist:**
=> monitoring: align with ceph/ceph prometheus alerts

pkg/operator/ceph/object/user/controller.go, pkg/operator/ceph/object/user/controller_test.go
Removing user caps will be skipped as the UserCaps is empty, which will cause updating user caps to not take effect.
Resolves #11715 
**Checklist:**
=> object: update os user caps

Documentation/Upgrade/rook-upgrade.md
=> doc: add helm supported version note to upgrade doc

.github/workflows/build.yml, .github/workflows/canary-integration-test.yml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/push-build.yaml, .github/workflows/tmate_debug/action.yml
this will help deduplicate tmate debug code throughout.
Resolves #
**Checklist:**
=> ci: use composite action for tmate session debugging

build/makelib/common.mk
There are a couple minor changes needed to allow building Rook on Apple silicon.
Resolves #
**Checklist:**
=> build: allow building on Mac with Apple silicon

PendingReleaseNotes.md
=> docs: update k8s version to 1.26.1 in release notes

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the examples and docs to v1.10.12.
**Checklist:**
=> build: Set the release version to v1.10.12

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the new minor rook release we set the examples and documentation to v1.11.0.
**Checklist:**
=> build: Set the release version to v1.11.0

.github/workflows/canary-integration-test.yml, .github/workflows/canary-test-config/action.yaml, tests/scripts/github-action-helper.sh
=> ci: Fix the multus integration test

deploy/examples/cluster.yaml
=> manifest: fix whitespace issues

PendingReleaseNotes.md
For the feature work that will happen in the v1.12 timeframe, we reset the pending release notes in
the master branch.
**Checklist:**
=> docs: Reset the pending release notes for v1.12

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release the examples and docs are updated to v1.11.1
**Checklist:**
=> build: Update release version to v1.11.1

deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go
Add fsid to the  additionalPrinterColumns on the crd types
[11862](https://github.com/rook/rook/issues/11862)
**Checklist:**
=> core: add fsid to the additionalPrinterColumns on cephcluster custom resource

build/csv/csv-gen.sh
ci: temporarily skipping another platform to fix the build
temporarily skipping other platforms to fix the build since we are working on bigger changes to remove csv generation.
Resolves #https://github.com/rook/rook/issues/11746
**Checklist:**
=> ci: temporarily skipping other platform to fix build

pkg/operator/ceph/cluster/nodedaemon/exporter.go
Remove the `ceph-conf-dir` volume and volume mount from exporter as it's no more required to spin up exporter daemon
Resolves #11910
**Checklist:**
=> core: remove ceph-conf-dir volume mount from exporter

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the docs and examples to v1.11.2
**Checklist:**
=> build: Update release version to v1.11.2

design/ceph/object/store.md
The PR #11091 add support for LDAP integration with RGW, this contains breif overview of design specific details.
**Checklist:**
=> docs: design doc for LDAP intergration with RGW

go.mod, go.sum
=> build: update vault to 1.13.1

Documentation/Contributing/development-flow.md
Testing changes and debugging issues in Ceph manager modules
**Checklist:**
=> docs: debug and test ceph manager modules

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the docs and examples to v1.10.13.
**Checklist:**
=> build: Update the release version to v1.10.13

Documentation/Troubleshooting/disaster-recovery.md
add recovering steps when rook crs and ceph daemons are all deleted.
here is the context: https://github.com/rook/rook/discussions/11821
Resolves #
**Checklist:**
=> docs: an update to disaster recovery with new scenario

Documentation/Storage-Configuration/Advanced/ceph-osd-mgmt.md
=> docs: update krew link osd removal docs

.github/workflows/canary-test-config/action.yaml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml
Resolves #12114 
**Checklist:**
=> ci: update k8s to v1.27.1 in ci

.github/workflows/canary-integration-test.yml, .github/workflows/rgw-multisite-test/action.yml, cmd/rook/ceph/osd.go, pkg/clusterd/disk.go, pkg/clusterd/disk_test.go, pkg/daemon/ceph/osd/daemon.go
Allow use the filter when it is scanning the devices
Resolves #10340
**Checklist:**
=> osd: allow scanning devices with filter

OWNERS.md
Since Cassandra is no longer supported and Yannis is no longer active on the project, move him to Emeritus maintainer.
**Checklist:**
=> docs: Move yannis to emeritus maintainer

Documentation/Getting-Started/Prerequisites/prerequisites.md, Documentation/Getting-Started/example-configurations.md, Documentation/Getting-Started/quickstart.md, Documentation/Getting-Started/release-cycle.md, Documentation/Getting-Started/storage-architecture.md, Documentation/README.md, GOVERNANCE.md, INSTALL.md
- Update the getting started guide, prereqs, architecture, and other basic docs with more concise wording and removed some obsolete information. Some links are removed so they don't distract the user from reading the critical information that we are conveying in the rook docs.
These updates are a result of a good conversation at Cephalocon with @zdover23 (Ceph docs lead) on what we can do to clarify and improve Rook documentation. More updates to come...
**Checklist:**
=> docs: Update core getting started docs for clarity

.github/workflows/canary-integration-test.yml
till we didn't resolve the multi-cluster-mirroring ci issue lets keep it disable
Resolves #
**Checklist:**
=> ci: disable multi-cluster-mirroring

.github/workflows/docs-check.yml, Documentation/CRDs/.pages, Documentation/CRDs/specification.md, Documentation/gen-crd-api-reference-docs/template/members.tpl, Documentation/gen-crd-api-reference-docs/template/pkg.tpl, Documentation/gen-crd-api-reference-docs/template/placeholder.go, Documentation/gen-crd-api-reference-docs/template/type.tpl, Makefile, build/crds/generate-crd-docs.sh, crd-docs-config.json, pkg/apis/ceph.rook.io/v1/types.go
=> docs: add support for autogenerated docs for CRDs

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release the docs and examples are updated to v1.11.5
**Checklist:**
=> build: Update patch version to v1.11.5

Documentation/CRDs/specification.md
update generation of documents for CRDs automatically
Resolves #
**Checklist:**
=> docs: update documentation for CRDs

README.md
=> docs: fix slack image in rook readme

pkg/operator/ceph/config/monstore.go
if the configuration is already set in the ceph database, using `ceph config assimilate-conf` will add the key and value if its missing but it won't update the value if the key is already present. To fix this problem we can remove the key and add all the configurations once again.
Resolves #
**Checklist:**
=> ceph: unset all the encryption configuration before setting

cmd/rook/rook/rook.go
Name was accidentally modified in PR #12069.
Resolves #
**Checklist:**
=> operator: fix package logger name for rookcli

deploy/examples/create-external-cluster-resources.py
1) The check validate_rgw_multisite was always checking for realm updated it to check the specific config
2) External: fixed validate_rgw_endpoint pool validation
The function pool_exists seems to only accept a string, but not a List, as it is given in validate_rgw_endpoint.
The change iterates calling pool_exists one by one over the list of pools given in validate_rgw_endpoint. This change made it possible to us to connect our RGW to OCP via Rook.
3) external: added missing realm, zonegroup and zone while interacting with users
Resolves # https://github.com/rook/rook/issues/12153
**Checklist:**
=> external: fix rgw multisite config check

cmd/rook/userfacing/multus/validation/validation.go
Even though this is validated in the validation process, validating in
the cli gives better user feedback and doesn't spam the user with
suggestions for the failure that aren't relevant.
Resolves #
**Checklist:**
=> operator: validate multus validation networks in cli

ROADMAP.md
Update the roadmap for the 1.12 release in the July timeframe.
Maintainers, please suggest features that are in the works for the near term so we can add them to this list for 1.12.
**Checklist:**
=> docs: Update the roadmap for v1.12

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the docs and example manifests to v1.11.6
**Checklist:**
=> build: Update release version to v1.11.6

Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
The StorageConfiguration docs for external needs to update with Rook design
Resolves #
**Checklist:**
=> docs: update the documentation for external rgw servers

Documentation/CRDs/Object-Storage/ceph-object-store-user-crd.md, Documentation/Contributing/development-flow.md, pkg/operator/ceph/cluster/cluster_external.go
The dev guide had some outdated info that is now updated, as well as some rewording for consistency and improved writing.
**Checklist:**
=> docs: Dev guide review updates

Documentation/Storage-Configuration/NFS/nfs-advanced.md, pkg/operator/ceph/nfs/config.go
wihtout RGW section, nfs daemon could not setup correctly with rgw export for rados authentication. Eventually it ends up in crash loop. change to use double quotes for string as designated in ganesha documentation.
Resolves #11592 
**Checklist:**
=> nfs: adding RGW section in ganesha.conf

.github/workflows/build.yml, .github/workflows/canary-integration-test.yml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/push-build.yaml
Currently tmate was not accessible and showing access denied,
Update limit-access-to-actor to true, which register tmate with a public ssh key
https://github.com/mxschmitt/action-tmate#use-registered-public-ssh-keys
Resolves #
**Checklist:**
=> ci: update tmate to run successfully with public ssh

Documentation/CRDs/Object-Storage/ceph-object-store-crd.md, Documentation/CRDs/specification.md, Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, deploy/examples/create-external-cluster-resources-tests.py, deploy/examples/create-external-cluster-resources.py, deploy/examples/object-external.yaml, pkg/apis/ceph.rook.io/v1/types.go
donot change rgw fqdn to ip if provided,
As now the bucket class supports the
entry of fqdn
Resolves #
**Checklist:**
=> external: fqdn should be persisted

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the docs and examples to v1.11.7
**Checklist:**
=> build: Update release version to v1.11.7

.github/workflows/daily-nightly-jobs.yml
add docker to the pipeline to allow minikube able to use docker driver
Resolves https://github.com/rook/rook/issues/12306
**Checklist:**
=> ci: fix minikube execution

Documentation/CRDs/Cluster/external-cluster.md, deploy/charts/rook-ceph-cluster/values-external.yaml
1) removed the supported version column
2) updated the doc with support for v2 port an helm installation
3) Add support for rgw objectuser creation
Resolves # https://github.com/rook/rook/issues/12205
https://github.com/rook/rook/issues/12046
**Checklist:**
=> doc: update external cluster docs

Documentation/Storage-Configuration/ceph-teardown.md
Current cluster teardown document assumes that there is only one Rook/Ceph cluster. If not, the instruction written in this document might delete the data of other clusters.
Resolves #
**Checklist:**
=> docs: prevent to delete other clusters data on cluster deletion

Documentation/Upgrade/ceph-upgrade.md, Documentation/Upgrade/rook-upgrade.md
With the upcoming v1.12 release in a few weeks, the upgrade guide (rook-upgrade.md and ceph-upgrade.md) need to be updated to support the new version.
Resolves #12361 
**Checklist:**
=> docs: Update the upgrade guide for the v1.12 release

Documentation/CRDs/specification.md, Documentation/gen-crd-api-reference-docs/template/pkg.tpl, build/crds/generate-crd-docs.sh
=> docs: remove the line generated by gen-crd-api-reference-docs

design/ceph/object/ceph-cosi-driver.md
The first draft for the design doc for ceph cosi driver with Rook
Resolves #7843
**Checklist:**
=> docs: add design doc for Ceph COSI driver

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the docs and example manifests to v1.11.8
**Checklist:**
=> build: Update release version to v1.11.8

pkg/operator/ceph/object/user/controller.go
There is no reference for ssl in cephobjectstore Secret, so users won't have much idea why tls secret need to used. Hence give reference object stores tls secret ref in the Secret.
Resolves #
**Checklist:**
=> object : add ssl ref in cephobjectstore user secret

deploy/examples/import-external-cluster.sh
import script may be need a re-run if other
resources need to be configured
for ex: if rbd is configured and later on point
someone want to also configure rgw, it will have
a choice
Resolves # Closes: https://github.com/rook/rook/issues/12412
**Checklist:**
=> external: make import script idempotent

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
=> build: Update release version to v1.11.9

Documentation/Helm-Charts/operator-chart.md, Documentation/Storage-Configuration/Ceph-CSI/custom-images.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/spec.go
update csi sidecars' image version
Resolves #12442 
**Checklist:**
=> csi: update csi sidecars' image version

Documentation/CRDs/Cluster/external-cluster.md, deploy/examples/create-external-cluster-resources-tests.py, deploy/examples/create-external-cluster-resources.py
updated some function which were strictly used for IPV4
Resolves # https://github.com/rook/rook/issues/11602
**Checklist:**
=> external: add support for IPV6 ceph daemons

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the new 1.12 branch set the beta release version to v1.12.0-beta.0.
**Checklist:**
=> build: Set the release version for the v1.12 beta

.github/workflows/build.yml, .github/workflows/canary-integration-test.yml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/push-build.yaml, .github/workflows/tmate_debug/action.yml
we need make `limit-access-to-actor: false` and also
in the right place where tmate `uses` is called for
composite yaml.
Resolves #11985 
**Checklist:**
=> ci: fix tmate access issue

.github/workflows/daily-nightly-jobs.yml, deploy/examples/cluster-test.yaml, pkg/operator/ceph/cluster/version_test.go, pkg/operator/ceph/version/version.go, pkg/operator/ceph/version/version_test.go, tests/framework/installer/ceph_installer.go, tests/integration/ceph_upgrade_test.go
Update test files to support the next version of ceph, ceph reef v18
Resolves #12367
**Checklist:**
=> test: add support Ceph Reef v18 with updated integration tests

.github/workflows/canary-integration-test.yml, deploy/examples/create-external-cluster-resources.py
Set the csi subvolume to pin type distributed and pin setting 1
So to statically balance the PVs across all MDS ranks
Resolves #
**Checklist:**
=> external: pin the default csi subvolume

.vscode/extensions.json, .vscode/settings.json
Closes: https://github.com/rook/rook/issues/11926
Resolves #
**Checklist:**
=> external: make black as default python formatter

tests/framework/installer/ceph_installer.go
update ceph to reef as default version
Resolves #
**Checklist:**
=> test: update reef as default version

.github/workflows/update_dependabot_bundler_pr.yml
the runner update_dependatbot_bundler was never running successfully
https://github.com/rook/rook/actions/workflows/update_dependabot_bundler_pr.yml we need a small change to add the breaking change from the action provider
see https://github.com/actions/github-script/issues/242
Resolves #12352
**Checklist:**
=> ci: update the update_dependabot_bundler action

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the docs and example manifests to v1.11.10
**Checklist:**
=> build: Update release version to v1.11.10

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the minor release update the docs and example manifests to v1.12.0. Enjoy!
**Checklist:**
=> build: Update the release version to v1.12.0

pkg/operator/ceph/object/objectstore.go
Gateways that do not run the sync threads should not be accessible from one of the Zone endpoint. If this is the case, the synchronization might stop working.
When the CephObjectStore has the option
`spec.gateway.disableMultisiteSyncTraffic` set to `true`, we must ensure that the objectstore endpoint is not present in the Zone endpoint.
Resolves #12533
**I tried to add some unit tests, but struggled to add one. There is currently no tests that verify that the ObjectStore endpoint is added to or removed from the Zone endpoints.**
However, I manually tested the following scenarios:
1. Creating a new Zone and a new CephObjectStore A without sync: endpoints are empty
2. Adding a new ObjectStore B with sync: endpoint contain B's endpoint 
3. Enabling the sync on A: endpoints contain A and B's …
=> object: do not add objectstore endpoint to zone when sync is disabled

tests/framework/clients/filesystem.go, tests/scripts/collect-logs.sh
added kube-system namespace also to collect
logs from to debug the smoke suite issue
Resolves #
**Checklist:**
=> test: collect kube-system logs for debugging

pkg/operator/ceph/nfs/security.go
This will enable us to use GSSAPI in sssd for authentication when connecting to the remote LDAP server.
We can setup CephNFS to authenticate incoming NFS connections using Kerberos. For this we mount the user provided  krb5.conf and the krb5 keytab file in the nfs-ganesha container. When setting up Kerberos, we also have to setup sssd  to map the kerberos principal to a uid/gid. This is usually a LDAP server.
At the moment, if the LDAP server doesn't allow anonymous binds to lookup user data, we need to provide a bind user and password for sssd to authenticate with the LDAP server. 
With this change, we mount the user provided krb5.conf and the keytab files also within the sssd container of the pod. This allows the sssd server to authenticate with the LDAP …
=> nfs: mount krb5.conf and krb5.keytab in the sssd container

pkg/operator/ceph/cluster/cluster_external.go
Currently, if we	use the	msgr2 port,   
cs-cluster-config-json looks like 
"monitors":["192.59.109.11:3300","192.59.109.13:6789","192.59.109.12:6789"]
The first monitor is passed by the python script and the rest are
Discovered by rook operator, so	if the first mon is using the v2 port
let's update the	other mons also	by setting up the RequireMsgr2 flag
Resolves #
**Checklist:**
=> external: set RequireMsgr2 if v2 port is configured

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, tests/framework/installer/ceph_manifests_previous.go
For the patch release update the examples and docs to v1.12.1. 
Also the upgrade test will be from v1.11.10 to master.
**Checklist:**
=> build: Update release version to v1.12.1

PendingReleaseNotes.md
The 1.13 pending release notes are now reset.
**Checklist:**
=> docs: Reset the pending release notes for v1.13

.github/workflows/canary-integration-test.yml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, tests/scripts/github-action-helper.sh, tests/scripts/validate_cluster.sh
ci: add github action to free space in runner
adding github action to free space in runner
which will help us avoiding mon low space error
core: update ceph version to reef
cluster.yaml require some changes to upgrade to ceph reef
and also require to update link to point quay.
Also, update images.txt and toolbox with latest version.
ci: same ceph version in toolbox and cluster-test
Let's use same ceph version(latest Reef) in both
cluster-test and toolbox.yaml so that we don't need
to pull image twice. Alos, github action helper script
was calling `deploy_manifest_with_local_build` which
is required for operator.yaml and not for toolbox.yaml.
multus: use right interface in ci validation
runner version `2.306` had the interface `net`
but somehow version …
=> ci:  fix all the canary test

.github/workflows/integration-tests-on-release.yaml
I missed adding the action which free some disk space which may help with low resource issues.
Resolves #
**Checklist:**
=> ci: add free disk action to release/master ci

tests/integration/ceph_base_object_test.go, tests/integration/ceph_bucket_notification_test.go, tests/integration/ceph_object_test.go
Current reason for failure
clients: "cephbuckettopic" "my-topic" exist, but ARN was not set
Added some more re-try as it might take some more time to update the ARN in status
Resolves #
**Checklist:**
=> ci: fix testobjectsuite ci

.github/workflows/build.yml, .github/workflows/canary-integration-test.yml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/push-build.yaml, .github/workflows/tmate_debug/action.yml, tests/scripts/github-action-helper.sh, tests/scripts/validate_cluster.sh
Please look at individual commits
Resolves #12671 #12583
**Checklist:**
=> ci: fix all the canary test (backport)

Documentation/Getting-Started/ceph-openshift.md, deploy/charts/rook-ceph-cluster/templates/securityContextConstraints.yaml, deploy/charts/rook-ceph/templates/deployment.yaml, deploy/charts/rook-ceph/templates/securityContextConstraints.yaml
The sccs were missing in the helm installation,
added it
Resolves # Closes: https://github.com/rook/rook/issues/12280
**Checklist:**
=> helm: install rook in openshift cluster

deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml
The CRDs were not generated for the latest since #12384 was merged without rebasing, and other updates with a newer dependency required the newer descriptions. This fixes the CI for the make-crds action.
**Checklist:**
=> build: Update crds gen for new descriptions

Documentation/Contributing/rook-test-framework.md
Rename and move tests/README.md to  Documentation/Contributing/rook-test-framework.md in order to make it as part of the contributing section
Resolves #11574
**Checklist:**
=> docs: move how to run tests instructions to contributing

.github/workflows/build.yml, .github/workflows/canary-integration-test.yml, .github/workflows/canary-test-config/action.yaml, .github/workflows/codegen.yml, .github/workflows/crds-gen.yml, .github/workflows/daily-nightly-jobs.yml, .github/workflows/docs-check.yml, .github/workflows/golangci-lint.yaml, .github/workflows/integration-test-config-latest-k8s/action.yaml, .github/workflows/mod-check.yml, .github/workflows/multus.yaml, .github/workflows/push-build.yaml, .github/workflows/rbac-gen.yaml, .github/workflows/unit-test.yml, build/makelib/golang.mk
=> build: update go version to 1.21 from 1.20

Documentation/CRDs/ceph-client-crd.md
=> docs: correct some libcephsqlite statements

design/ceph/osd-migration.md
Resolves #12813
**Checklist:**
=> cleanup of the OSD migration design document

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release update the examples and documents to v1.12.3.
**Checklist:**
=> build: Update release version to v1.12.3

ROADMAP.md
The roadmap doc is updated with some high level features that are targeted for the 1.13 release.
**Checklist:**
=> docs: Update roadmap for 1.13

ROADMAP.md
COSI is not yet ready for declaring stable while the K8s feature is still in alpha state, despite how stable Rook's implementation may be.
Also a few other minor updates missed in #12874. 
**Checklist:**
=> docs: Fine tune roadmap for 1.13

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml
For the patch release, update the docs and examples to v1.11.11
**Checklist:**
=> build: Update the release version to v1.11.11

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.12.4.
**Checklist:**
=> build: Update the release version to v1.12.4

cmd/rook/ceph/osd.go, pkg/daemon/ceph/osd/daemon.go, pkg/daemon/ceph/osd/remove.go, pkg/daemon/ceph/osd/volume_test.go, pkg/operator/ceph/cluster/mon/health_test.go, pkg/operator/ceph/cluster/nodedaemon/exporter.go, pkg/operator/ceph/cluster/nodedaemon/pruner.go, pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/osd/osd_test.go, pkg/operator/ceph/cluster/watcher.go, pkg/operator/ceph/controller/network.go, pkg/operator/ceph/csi/cluster_config.go, pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/csi/spec_test.go, pkg/operator/ceph/csi/util_test.go, pkg/operator/ceph/file/dependent.go, pkg/operator/ceph/object/bucket/provisioner.go, pkg/operator/ceph/object/bucket/util.go, pkg/operator/ceph/object/dependents_test.go, pkg/operator/ceph/object/user/controller.go, pkg/operator/ceph/object/zone/dependents_test.go, pkg/operator/k8sutil/configmap.go, pkg/operator/k8sutil/prometheus.go, pkg/operator/k8sutil/service.go
=> core: import packages only once

Documentation/Storage-Configuration/ceph-teardown.md
The teardown guide is updated with the guidelines to use third person wording and be more concise. Also, remove the list of CRDs from the example that easily becomes outdated as the list changes from release to release.
**Checklist:**
=> docs: Review the teardown guide for updated guidelines

.github/workflows/canary-test-config/action.yaml, .github/workflows/integration-test-config-latest-k8s/action.yaml, tests/scripts/github-action-helper.sh
The issues are fixed from the clean disk action
repo and we shouldn't require any workaround. Also, I'm not using git revert to revert the commit is earlier clean disk action was mentioned in every CI which was duplicate and now we have placed the action to composite yaml
Resolves #
**Checklist:**
=> ci: remove workaround for clean disk action

.github/workflows/canary-integration-test.yml, Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md, Documentation/Storage-Configuration/ceph-teardown.md, cmd/rook/rook/rook.go, deploy/examples/create-external-cluster-resources.py, pkg/daemon/multus/validation.go, pkg/operator/ceph/object/admin.go, tests/framework/clients/block.go
closes: https://github.com/rook/rook/issues/12987
Resolves #
**Checklist:**
=> docs: fixing some spelling issues

Documentation/Contributing/development-environment.md
Adding some detailed instructions on how to use the local built Rook image on minikube cluster
Resolves #
**Checklist:**
=> docs: improving minikube setup documentation

pkg/operator/ceph/cluster/mgr/mgr.go, pkg/operator/ceph/cluster/nodedaemon/exporter.go
Several messages were showing up in the operator log more often than necessary, so let's change them to debug level.
**Checklist:**
=> exporter: Change verbose info to debug logs

Documentation/Contributing/development-environment.md
=> docs: fixing typos

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and docs to v1.12.5.
**Checklist:**
=> build: Update the release version to v1.12.5

Documentation/Storage-Configuration/Object-Storage-RGW/cosi.md
Fixed a wording problem and moved the app pod to the default namespace where the secret was created and also removed the init container from the sample as the busybox doesn't have setup-aws-credentials CLI pre-installed.
Resolves #
**Checklist:**
=> cosi: fix problem in cosi document

Documentation/Storage-Configuration/Monitoring/ceph-dashboard.md
https://github.com/rook/rook/pull/11845 added dynamic label `mgr_role`. The example yaml files are updated but this doc is missed.
I think it would be better to refer to `deploy/examples` but I find all other places are not doing that. So keep it inlined to be consistent.
Resolves #
**Checklist:**
=> doc: fix document about viewing dashboard outside of cluster

Documentation/Upgrade/ceph-upgrade.md
Closes: https://github.com/rook/rook/issues/13010
Resolves #
**Checklist:**
=> docs: adding specific instructions to upgrade Rook toolbox

.snyk
Update the snyk ignores related to Vault MPL-2.0 licenses.
Resolves #
**Checklist:**
=> security: update snyk ignores for MPL-2.0

Documentation/Troubleshooting/kubectl-plugin.md
=> docs: fix install command

deploy/examples/create-external-cluster-resources-tests.py, deploy/examples/create-external-cluster-resources.py
if the monitoring endpoint is not present
we were not returning any error, but the
field is the mandatory output, so a return error i not found
**Checklist:**
=> external: fix monitoring endpoint check

deploy/examples/common-second-cluster.yaml
fix rook-ceph-mgr-system role and namespace
Resolves #
**Checklist:**
=> manifests: fix rook-ceph-mgr-system role and namespace

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and docs to v1.12.7
**Checklist:**
=> build: Update release version to v1.12.7

Documentation/Contributing/development-environment.md, tests/scripts/create-dev-cluster.sh
Adding a script for devs to simplify the test cluster creation. By now it just create the one-node cluster without 
enabling any kind of service but more parameterized functionality can be added later for the different supported
modules (rgw, nfs, etc).
Resolves #
**Checklist:**
=> test: adding a script to simplify test cluster creation

deploy/examples/cluster-on-pvc-minikube.yaml
adding an example for a cluster where local pvc are used
for mon store and for OSD creation
Resolves #
**Checklist:**
=> test: adding an example for cluster on local pvc creation

.github/workflows/helm-lint.yaml
The helm linter was failing with v2.4.0. Now we update the version of the action to the latest and greatest.
**Checklist:**
=> ci: Update helm linter to v2.6.0

pkg/apis/go.mod, pkg/apis/go.sum
The merge of the go modules in the apis subdirectory missed some changes from another merge around the same time, so this will add the missing updates and fix the CI.
**Checklist:**
=> build: Update go modules from merge conflict

build/release/Makefile
This fixes the docs deploy issues caused by the mike 2.0.0 release that removed/renamed some flags, see
https://github.com/jimporter/mike/releases/tag/v2.0.0
Resolves #13149
**Checklist:**
=> ci: fix mike deploy flags

tests/scripts/create-dev-cluster.sh
Adding a new '-m' option for activating monitoring during cluster setup. With this option turned on, the script will handle the installation of the monitoring stack and configure the dashboard to connect to the newly installed Prometheus server automatically.
Resolves #
**Checklist:**
=> test: adding support for monitoring in dev-create-cluster script

tests/scripts/create-dev-cluster.sh
Let's use the minikube profiles feature to set up a unique profile exclusively for the Rook cluster. By doing this, we make sure that we don't run into any issues with other minikube profiles that users might already have in their local setup.
Resolves #
**Checklist:**
=> test: using minikube profiles for rook cluster creation

pkg/daemon/ceph/client/pool.go, pkg/daemon/ceph/client/pool_test.go
This commits add check to update the deviceClass on existing pool.
Resolves #12714 #12263 
**Checklist:**
=> pool: allow updating deviceClass on existing pool

deploy/examples/monitoring/csi-metrics-service-monitor.yaml, deploy/examples/monitoring/exporter-service-monitor.yaml, deploy/examples/monitoring/externalrules.yaml, deploy/examples/monitoring/prometheus-service.yaml, deploy/examples/monitoring/prometheus.yaml, deploy/examples/monitoring/rbac.yaml, deploy/examples/monitoring/service-monitor.yaml
including the namespace tag in the monitoring manifests to streamline the automated process of modifying them through scripting
Resolves #
**Checklist:**
=> manifest: adding the namespace tag to the monitoring manifests

.github/workflows/daily-nightly-jobs.yml
Add tmate debugging to daily/nightly jobs to help debugging.
Resolves #
**Checklist:**
=> test: add tmate to daily/nightly jobs

pkg/operator/ceph/cluster/mgr/mgr.go, pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/mon/mon_test.go, pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/rbd/mirror.go, pkg/operator/ceph/controller/spec.go, pkg/operator/ceph/file/mds/mds.go, pkg/operator/ceph/object/rgw.go
During certain maintenance tasks the admin will own running
operations on the ceph mgr, rgw, mds and rbd-mirror daemons
and the operator should not interfere with those operations.
Resolves #12785 
**Checklist:**
=> core: operator to skip reconcile of mgr, rgw, mds and rbd-mirror 

tests/scripts/create-dev-cluster.sh
Adding support to specify operator and cluster namespaces as new command-line arguments for the `create-dev-cluster` script. This PR adds new arguments:
-  `-c`  to specify the cluster namespace
-  `-o` to specify the operator namespace
In addition, the script will automatically update the namespace in the corresponding YAML files. Operator namespace is create automatically if it doesn't exist.
**Testing:** 
**1- Create a cluster**
```
./tests/scripts/create-dev-cluster.sh -m -r -f -p minikube -c rook-cluster-ns -o rook-operator-ns
Using '/home/<user>/workspaces/src/github.com/rook/rook/tests/scripts/../../deploy/examples/' as examples directory..
Using rook-cluster-ns as cluster namespace..
Using rook-operator-ns as operator namespace..
Updating namespace on common.yaml
Updating …
```
=> test: adding support to specify the operator and cluster namepaces

deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go
webhook: add validating admission policy
this commit adds validating admission policy
for cephcluster cr according to webhook rules.
Not all the webhook can be moved to validating
admission policy for example checking multus
selector validation.
**Note: Not all the Webhooks can be moved to CEL for example validating network for multus selector. And, will push changes in different commits based on local testing**
Resolves #12938
**Checklist:**
=> webhook: add validating admission policy

.github/workflows/canary-integration-test.yml, Documentation/CRDs/Cluster/external-cluster.md, deploy/examples/create-external-cluster-resources.py, deploy/examples/import-external-cluster.sh
change the json output of storageclass to also inclusde rados namespace, and also added the changes in the csi secret
**Checklist:**
=> external: add support for rados namespace for external cluster

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the new pre-release beta the docs and manifests are updated to the v1.13.0-beta.0 tag.
**Checklist:**
=> build: Update the release version to v1.13.0-beta.0

.mergify.yml
Add mergify rules for opening backport PRs to the 1.13 branch and also for auto-merging backports after the CI passes.
**Checklist:**
=> ci: Mergify rules for release-1.13

deploy/charts/rook-ceph-cluster/templates/cephobjectstore-ingress.yaml
fix a regression introduced in #13288
**Checklist:**
=> helm: fix namespace for objstore ingress

Documentation/CRDs/Cluster/ceph-cluster-crd.md
- describe pgHealthCheckTimeout pgHealthyRegex in the CephCluster CRD document.
- Use more appropriate words in the table of supported configurations for OSD creation.
**Checklist:**
=> doc: add the description of some fields and update the table of supported configurations for OSD creation

tests/scripts/create-dev-cluster.sh
=> Adding new option -i to specify the cluster spec file + some code refactoring

cmd/rook/ceph/osd.go, pkg/daemon/ceph/osd/remove.go
This reverts commit 927af7c7f765c141b6c7c54a70414539d8f8fa9f.
**Checklist:**
=> Revert "osd: add callback function in osd removal"

.github/workflows/golangci-lint.yaml
updating go version from `1.21.4` to `1.21.5`
Resolves #
**Checklist:**
=> ci: update go version in govulncheck

Documentation/CRDs/Shared-Filesystem/ceph-fs-subvolumegroup-crd.md
add the name and pinning spec in the docs
Closes: https://github.com/rook/rook/issues/13329
Resolves #  https://github.com/rook/rook/issues/13329
**Checklist:**
=> docs: document the subvolumegroup pinning

tests/framework/clients/filesystem.go
The filesystem is not being deleted because of the existing svg.
Add a cliet call to delete the deafult csi svg, for helm test
**Checklist:**
=> ci: delete svg in helm test

deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go, pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
added the cel rules at sunvolumgroup and rados
namesapce spec
closes: #13315
Resolves # #13315
**Checklist:**
=> build: add cel rule to make resource immutable

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and docs to v1.12.10
**Checklist:**
=> build: Update the release version to v1.12.10

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the new minor release update the examples and docs to v1.13.0.
**Checklist:**
=> build: Update the release version to v1.13.0

.github/workflows/canary-integration-test.yml, .github/workflows/canary-test-config/action.yaml, .github/workflows/collect-logs/action.yaml, .github/workflows/integration-test-config-latest-k8s/action.yaml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, tests/scripts/collect-logs.sh
ci: add 'rook-ceph-seconday' ns to collect logs.
In canary test `multi-cluster-mirroring` we also need to collect
logs of `rook-ceph-secondary` namespace to debug the ci.
ci: remove unwanted inputs from composite action
we are passing inputs to composite action, like
`github_token` which is not being used anymore. Its'
better to clean those lines.
**Checklist:**
=> ci: add 'rook-ceph-seconday' ns to collect logs.

Documentation/CRDs/Cluster/ceph-cluster-crd.md
This commit documents the newly added `spec.csi`
section containing CSI driver related options.
Resolves #13356 
**Checklist:**
=> doc: document `spec.csi` section in cephcluster crd

.github/workflows/canary-test-config/action.yaml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, .mergify.yml
=> ci: upgrade kubernetes version to latest version

deploy/charts/rook-ceph/templates/deployment.yaml
Fix duplicate tolerations in operator helm chart.
Resolves https://github.com/rook/rook/issues/13416
**Checklist:**
=> helm: Fix duplicate tolerations

pkg/operator/ceph/cluster/watcher.go, pkg/operator/ceph/cluster/watcher_test.go, pkg/operator/ceph/csi/secrets.go, pkg/operator/ceph/csi/secrets_test.go
This commit implements network fencing for cephFS.
Closes: #13201 
Checklist:
=> csi: implement network fencing for cephFS

.github/dependabot.yml
This reverts commit 39659140f2221ae36920ade38442d276bf00933a.
**Checklist:**
=> Revert "bot: add directory /pkg/apis to update go pkg"

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and manifests to v1.13.1
**Checklist:**
=> build: Update release version to v1.13.1

CODE-OWNERS, OWNERS.md
=> doc: add subhamkrai name to 'approvers' list

CODE-OWNERS
added parth arora(parth-gr) to the reviewers list in the code-owners file :) .
Resolves #
**Checklist:**
=> doc: Proposal to add parth-gr to the reviewers

design/ceph/object/store.md
Support DNS subdomain style for RGW buckets. Design doc for #4780 
Resolves #
**Checklist:**
=> doc: design specification for virtual host style for RGW buckets

Documentation/CRDs/Cluster/ceph-cluster-crd.md, Documentation/CRDs/Cluster/host-cluster.md, Documentation/CRDs/Cluster/pvc-cluster.md, Documentation/CRDs/Cluster/stretch-cluster.md, Documentation/Upgrade/ceph-upgrade.md, deploy/charts/rook-ceph-cluster/values.yaml, deploy/examples/cluster.yaml, design/ceph/ceph-cluster-cleanup.md, pkg/operator/ceph/cluster/osd/deviceset_test.go, tests/manifests/test-cluster-on-pvc-encrypted.yaml
Since v18.2.1 is the default recommendation for the ceph version, update all the docs and examples to that version. This is a follow-up from #13428.
Resolves #13498 
**Checklist:**
=> helm: Update cluster chart and all examples to ceph v18.2.1

.github/workflows/canary-integration-test.yml, tests/scripts/csiaddons.sh
Resolves #13438 
**Checklist:**
=> ci: add validation for csi-addons sidecar

CODE-OWNERS, OWNERS.md
=> doc: add sp98 to approvers list

.github/PULL_REQUEST_TEMPLATE.md
=> doc: Comment out the resolved issue by default in the PR template

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and docs to v1.13.2
**Checklist:**
=> build: Update the release version to v1.13.2

Documentation/Helm-Charts/operator-chart.md, Documentation/Storage-Configuration/Ceph-CSI/custom-images.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/spec.go
updating csi provisioner to 3.6.3 as we have a bug in 3.6.2
Resolves #13475
**Checklist:**
=> csi: update csi provisioner to 3.6.3

Documentation/Helm-Charts/operator-chart.md, deploy/charts/rook-ceph/templates/configmap.yaml, deploy/charts/rook-ceph/values.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/csi.go, pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml, pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml, pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
This commit adds the flexibility to configure leader election flags per the user requirement and keeps the existing values as the default ones.
**Checklist:**
=> csi: make leader election flags configurable

pkg/operator/ceph/cluster/osd/osd.go
If migration of the OSDs is enabled, operator should wait for the pgs to be clean after the all the OSDs have reconciled. This will help add the exponential backoff for the operator restarts when OSD migration is needed but PGs are still rebalancing the data after last OSD migration.
Also, if the migration is pending at the end of the OSD reconcile, then trigger the reconcile again.
Resolves #13525
**Checklist:**
=> osd: fix operator reconcile during OSD migration

tests/scripts/create-dev-cluster.sh
So far all the arguments were being handled as separate getopts flags introducing a lot of boilerplate code for every new flag. The new approach improves the arguments handling by using env variables.
This is a followup PR to address the improvements proposed on https://github.com/rook/rook/pull/13298#pullrequestreview-1768437705
Resolves #
**Checklist:**
=> dev: improving the handling of arguments within the script

build/release/Makefile
=> build: fix bad quotation in make help

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.12.11
**Checklist:**
=> build: Update the release version to v1.12.11

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and docs to v1.13.3
**Checklist:**
=> build: Update the release version to v1.13.3

pkg/operator/ceph/controller/predicate.go
The changes made to cosi driver are reflected. Add the cosidriver crd to predicate workflow.
Fixes: #12545
**Checklist:**
=> object: watch updates for cosidriver crd

deploy/examples/cluster-on-pvc-minikube.yaml
Resulting cluster:
```
bash-4.4$ ceph -s
cluster:
id:     32160b9f-3beb-4d44-8527-e1ef04ecedd2
health: HEALTH_OK
services:
mon: 1 daemons, quorum a (age 6m)
mgr: a(active, since 3m)
osd: 3 osds: 3 up (since 4m), 3 in (since 5m)
data:
pools:   1 pools, 32 pgs
objects: 2 objects, 449 KiB
usage:   80 MiB used, 60 GiB / 60 GiB avail
pgs:     32 active+clean
```
**Checklist:**
=> test: updating spec by an extra disk and the .mgr pool configuration

Documentation/Getting-Started/Prerequisites/prerequisites.md, Documentation/Getting-Started/quickstart.md
we need to clarify what all version we do support
Resolves # https://github.com/rook/rook/issues/13632
**Checklist:**
=> docs: clarify the k8s versioning in the doc

Documentation/Getting-Started/Prerequisites/prerequisites.md, Documentation/Getting-Started/quickstart.md
we need to clarify what all version we do support
Resolves # https://github.com/rook/rook/issues/13632
**Checklist:**
=> docs: clarify the k8s versioning in the doc in 1.12

pkg/operator/ceph/cluster/mgr/dashboard.go
previous code was calling the following command to create the dashboard user:
> ceph dashboard ac-user-create <username> -i <password-file>
this works the first time when the user doesn't exist, however subsequent calls for example when the password has changed or when the secret was deleted from k8s, will not take place as this command will succeeded because the user already exists but the password is not updated in this case. The fix consists in adding an explicit call to the command:
> ceph dashboard ac-user-set-password <username> -i <password-file>
which ensures the password is updated correctly in the access control db
Fixes: https://github.com/rook/rook/issues/13594
**Checklist:**
=> mgr: use the ac-user-set-password cmd to update the password

pkg/operator/ceph/cluster/nodedaemon/reconcile.go
The exporter service and service monitor should not be deleted if an individual daemon is being removed from a node. As long as the exporter is enabled with v18 and newer, the exporter service and service monitor should exist. Clusters were seeing their metrics stop collection when the exporter service and service monitor would disappear, especially when multiple clusters are configured.
Resolves #13642
**Checklist:**
=> exporter: Don't delete exporter service on daemon deletion

deploy/examples/create-external-cluster-resources.py, tests/scripts/pythonwebserver/server.py
currently there is a new release of black
formatter so updating it with new release
**Checklist:**
=> ci: reformat the python scripts

.github/workflows/golangci-lint.yaml
This is needed because not all contributors may be using gomft to format source code, and this could result in inconsistent usage over time.
**Checklist:**
=> ci: check for gofmt usage in golangci-lint

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and docs to v1.13.4.
**Checklist:**
=> build: Update the release version to v1.13.4

Documentation/Helm-Charts/operator-chart.md, Documentation/Storage-Configuration/Ceph-CSI/custom-images.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/csi/util_test.go, pkg/operator/ceph/csi/version_test.go
Updating the cephcsi image to 3.10.2 which is the latest released one.
Release note https://github.com/ceph/ceph-csi/releases/tag/v3.10.2
**Checklist:**
=> csi: update cephcsi image to 3.10.2

.github/workflows/canary-integration-test.yml, .github/workflows/daily-nightly-jobs.yml
Run the canary test suites with nightly CI so that we can detect
incoming issues with Ceph devel versions.
**Checklist:**
=> CI: run canary tests nightly

.github/workflows/canary-test-config/action.yaml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, Documentation/Getting-Started/Prerequisites/prerequisites.md, Documentation/Getting-Started/quickstart.md, PendingReleaseNotes.md, tests/scripts/github-action-helper.sh
upgrading minimum kubernetes supported version to v1.24.17 and also upgrading other kubernetes version to their latest respective version.
**Checklist:**
=> ci: upgrade min k8s supported version to 1.24.17

ROADMAP.md
Looking forward to the 1.14 release in April, update the roadmap of planned feature work. The features are not limited to this list, it is just for context on what is currently planned.
**Checklist:**
=> docs: Update roadmap for the 1.14 release

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and docs to v1.13.5.
**Checklist:**
=> build: Update the release version to v1.13.5

Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, tests/framework/installer/ceph_installer.go, tests/scripts/auto-grow-storage.sh, tests/scripts/create-dev-cluster.sh, tests/scripts/github-action-helper.sh
Uplift Prometheus operator version to v0.71.1
Resolves #13459 
**Checklist:**
=> Bump Prometheus operator version to v0.71.1

PendingReleaseNotes.md
doc: PendingReleaseNotes for update netNamespaceFilePath PR (https://github.com/rook/rook/pull/13613)
**Checklist:**
=> doc: PendingReleaseNotes for update netNamespaceFilePath PR

Documentation/README.md
Fixing the broken links in the docs.
=> doc: fix broken links

pkg/operator/ceph/csi/cluster_config.go, pkg/operator/ceph/csi/cluster_config_test.go
During cluster creation, csi config map was first filled with mon ips and without CSIDriverOptions.
This commit makes sure CSIDriverOptions are added at the begining when the entry is first created.
Updates:
- #13835
```
[User@localhost ~]:rook$ k get cm rook-ceph-csi-config -o yaml -w
apiVersion: v1
data:
csi-cluster-config-json: '[]'
kind: ConfigMap
metadata:
creationTimestamp: "2024-02-29T13:43:36Z"
name: rook-ceph-csi-config
ownerReferences:
- apiVersion: apps/v1
blockOwnerDeletion: false
controller: true
kind: Deployment
name: rook-ceph-operator
uid: 17c87c42-f130-481e-996d-a9750b5b21df
resourceVersion: "10112"
uid: 7e37de42-06fb-403b-b4a9-f0a8bfc2bb3e
---
apiVersion: v1
data:
csi-cluster-config-json: '[{"clusterID":"rook-ceph","monitors":["192.168.39.252:6789"]," …
```
=> csi: update CSIDriverOption params during saving cluster config

Documentation/Storage-Configuration/Advanced/key-management-system.md
Users on Microsoft Azure can make use of the Azure key vault service rather than replying on any third party service for KMS.
**Checklist:**
=> doc: add support for using azure kms

Documentation/CRDs/Cluster/external-cluster.md
differentiate betwwen two different ways
of s3 storage consumption
**Checklist:**
=> doc: update objectuser example in the external install

.github/workflows/canary-test-config/action.yaml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, Documentation/Getting-Started/Prerequisites/prerequisites.md, Documentation/Getting-Started/quickstart.md, PendingReleaseNotes.md
upgrading minimum kubernetes supported version to v1.25.16
**Checklist:**
=> ci: upgrade min k8s supported version to 1.25 combiner

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and example manifests to v1.13.6.
**Checklist:**
=> build: Update the release version to v1.13.6

Documentation/CRDs/Cluster/external-cluster.md
Updating the installation step of external cluster
to make it more user friendly
part-of: https://github.com/rook/rook/discussions/13831
**Checklist:**
=> external: restructure the external install steps

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the example manifests and docs to v1.13.7
**Checklist:**
=> build: Update release version to v1.13.7

.github/workflows/canary-integration-test.yml, Documentation/CRDs/Cluster/.pages, Documentation/CRDs/Cluster/ceph-cluster-crd.md, Documentation/CRDs/Cluster/external-cluster.md, Documentation/CRDs/Cluster/external-cluster/.pages, Documentation/CRDs/Cluster/external-cluster/external-cluster.md, Documentation/CRDs/Cluster/external-cluster/topology-for-external-mode.md, Documentation/Getting-Started/glossary.md, ROADMAP.md, deploy/examples/create-external-cluster-resources.py, deploy/examples/import-external-cluster.sh
with topologyconstrain pool we can enable any
replica pool usage and also can store data at any
topology
**Checklist:**
=> external: add topologyconstraintpool support for rbd storageclass

Documentation/Helm-Charts/operator-chart.md, deploy/charts/rook-ceph/templates/configmap.yaml, deploy/charts/rook-ceph/values.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/controller.go
added a new flag ROOK_CSI_DISABLE_DRIVER
to disable csi controller.
Signed-off-by: parth-gr <partharora1010@gmail.com>
**Checklist:**
=> csi: add a new flag to disable csi driver

pkg/operator/ceph/cluster/mgr/drain.go, pkg/operator/ceph/cluster/mgr/drain_test.go, pkg/operator/ceph/cluster/mgr/mgr_test.go, pkg/operator/ceph/cluster/mon/drain.go, pkg/operator/ceph/cluster/mon/drain_test.go, pkg/operator/ceph/disruption/clusterdisruption/add.go, pkg/operator/ceph/disruption/clusterdisruption/osd.go, pkg/operator/ceph/disruption/clusterdisruption/osd_test.go, pkg/operator/ceph/disruption/clusterdisruption/pools.go, pkg/operator/ceph/disruption/clusterdisruption/static_pdb.go, pkg/operator/k8sutil/k8sutil.go
This commit remove PdbV1Beta1 as k8s 1.25 doesnt support it.
Resolves #13941 
**Checklist:**
=> operator: remove PdbV1Beta1 support as k8s 1.25 doesnt support it

.github/workflows/build.yml, Makefile, build/makelib/golang.mk, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml
Few day's back go 1.22 is release. Let's add that
as valid version to build on.
https://tip.golang.org/doc/go1.22
**Checklist:**
=> build: add support for go 1.22

deploy/examples/create-external-cluster-resources.py
v2 port can be avalaible without v1,
so fixing the current check
**Checklist:**
=> external: fix v2 port check in external script

Documentation/Contributing/rook-test-framework.md, Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the new release branch update the examples and docs to v1.14.0-beta.0.
**Checklist:**
=> build: Update the release version to v1.14.0-beta.0

.github/workflows/canary-integration-test.yml, .mergify.yml
The test names must match exactly for the mergify auto merge to complete successfully. Update two of the test names to match the latest CI.
**Checklist:**
=> ci: Fix mergify auto merge test names

pkg/operator/ceph/pool/controller.go
Pool name either come from CephBlockPool name or form the CephBlockPool Spec. Use the correct name when trying to disable mirroring.
**Checklist:**
=> core: use correct pool name to disable mirroring

Documentation/CRDs/Cluster/ceph-cluster-crd.md
=> docs: fix network configuration bullets

Documentation/CRDs/Cluster/network-providers.md, Documentation/Helm-Charts/operator-chart.md, Documentation/Upgrade/rook-upgrade.md, PendingReleaseNotes.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml
Update pending release notes, upgrade docs, and supplementary documentation relevant for upgrades for the upcoming Rook v1.14 release.
**Checklist:**
=> doc: update release notes and upgrade docs for v1.14

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and docs to v1.13.8
**Checklist:**
=> build: Update release version to v1.13.8

PendingReleaseNotes.md
Since v1.14 is released, we reset the pending release notes for the v1.15 release.
**Checklist:**
=> doc: Reset pending release notes

.github/workflows/codespell.yaml, Documentation/Contributing/development-flow.md, design/ceph/osd-migration.md
add misspell linter to check all source codes
**Checklist:**
=> ci: add misspell linter

Documentation/CRDs/Cluster/network-providers.md
Most bullets and numbering in the network providers doc (sub-doc of CephCluster CR) wasn't rendering properly on the web. Fix by making sure there is a blank line before each numbered/bulleted section. And make sure nested numberings are indented 4 spaces.
**Checklist:**
=> doc: fix network provider bullets and numbering

pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/osd/osd_test.go
If device set names are duplicated, the OSDs will be very confused when multiple OSDs attempt to be configured with the same device set names. Updating the device set names does not help get out of the error situation since the OSDs will also be confused about which device set they belong to. The reconcile must fail completely if the device set names are duplicated to avoid this error scenario.
**Checklist:**
=> osd: Prevent osd reconcile when device set names duplicated

pkg/operator/ceph/cluster/osd/spec.go, pkg/operator/ceph/disruption/clusterdisruption/osd.go
core: fix typos in reconcile cluster disruption
**Checklist:**
=> core: fix typos in reconcile cluster disruption

pkg/apis/ceph.rook.io/v1/resources.go, pkg/client/informers/externalversions/factory.go, pkg/daemon/ceph/osd/kms/kmip.go, pkg/daemon/util/cmdreporter_test.go, pkg/operator/ceph/predicate.go
=> core: fix function names in comment

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and docs to v1.14.1.
**Checklist:**
=> build: Update the release version to v1.14.1

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and manifests to v1.14.2
**Checklist:**
=> build: Update the release version to v1.14.2

Documentation/CRDs/Cluster/external-cluster/external-cluster.md
fixing the list numbers in external document
closes: https://github.com/rook/rook/issues/13968
**Checklist:**
=> doc: fix external cluster document

Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot.md, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-clone.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md
Closes: #14059 
**Checklist:**
=> csi: remove out-dated prerequisites

Documentation/CRDs/Cluster/network-providers.md, Documentation/Storage-Configuration/NFS/nfs.md, cmd/rook/util/cmdreporter.go, pkg/daemon/util/cmdreporter.go, pkg/operator/ceph/cluster/osd/key_rotation.go, pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/osd/topology/topology.go, pkg/operator/ceph/cluster/watcher.go
=> docs: delete duplicate words and revise the names of some methods

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.14.3
**Checklist:**
=> build: update release version to v1.14.3

.github/workflows/build.yml, .github/workflows/canary-integration-test.yml, .github/workflows/codegen.yml, .github/workflows/codespell.yaml, .github/workflows/commitlint.yml, .github/workflows/crds-gen.yml, .github/workflows/create-tag.yaml, .github/workflows/daily-nightly-jobs.yml, .github/workflows/docs-check.yml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, .github/workflows/mod-check.yml, .github/workflows/push-build.yaml, .github/workflows/rbac-gen.yaml, .github/workflows/stale.yaml, .github/workflows/unit-test.yml
updating ubuntu image to 22.04 from 20.04 which is used in ci test
**Checklist:**
=> ci: update ubuntu image to 22.04

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.13.9
**Checklist:**
=> build: Update the release version to v1.13.9

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and manifests to v1.14.4
**Checklist:**
=> build: Update the release version to v1.14.4

pkg/operator/ceph/cluster/mon/spec.go, pkg/operator/ceph/cluster/mon/spec_test.go
When IPv6-only network mode is enabled and when mons are configured to listen only on msgrV2 port, Rook has to add the port to the mon --public-bind-addr in order to force mons to stop listening on the msgrV1 port. This can cause problems for IPv6 clusters where adding ':<port>' to the end of an IP addr looks like a valid IPv6 address.
In IPv6 mode, Rook needs to set this to `[<ip>]:<port>` with the brackets to be a non-ambiguous IPv6 address.
In IPv4 mode, Rook needs to keep its existing behavior. IPv4 mode should also continue to be the defualt assumption if the network config isn't specified.
If `dualStack: true` is specified, Rook is informed that the environment is dual stack, but Rook doesn't know which IP family to expect from the pod IP. In this scenario, it is safest for Rook not …
=> mon: fix bind addr when IPv6 and msgr2 are enabled

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and documentation to v1.14.5
**Checklist:**
=> build: Set the release version to v1.14.5

pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
`make codegen` resulted in a diff, so that needed to be committed.
**Checklist:**
=> build: add result of codegen

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and documentation
to v1.14.6
**Checklist:**
=> build: set release version to v1.14.6

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and documentation to v1.14.7
**Checklist:**
=> build: set release version to v1.14.7

pkg/operator/ceph/cluster/watcher.go
skip creating networkFence when 'ROOK_CSI_DISABLE_DRIVER' is set to 'false'.
Resolves #14223 
**Checklist:**
=> csi: skip creating networkFence when csi disabled

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md, tests/scripts/csiaddons.sh
updating csi-addons repo link to pull the yamls for installation
Resolves #14394
**Checklist:**
=> csi: update csi-addons repo link

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the manifests and docs to v1.13.10
**Checklist:**
=> build: Update the release version to v1.13.10

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the manifests and docs to v1.14.8
**Checklist:**
=> build: Update the release version to v1.14.8

deploy/examples/create-external-cluster-resources.py
Priority: command-line-args > config.ini file values > default values Currently default was having more priority so fixed it
**Checklist:**
=> external: config file should have more priority then defaults

README.md
This PR simply updates the main README.md to specify the new frequency for the community meeting. We will be meeting once a month now on the 2nd Tues of each month.
**Checklist:**
=> docs: update README with new community meeting frequency

.github/workflows/daily-nightly-jobs.yml, PendingReleaseNotes.md, deploy/examples/cluster-test.yaml, pkg/operator/ceph/cluster/version_test.go, pkg/operator/ceph/version/version.go, pkg/operator/ceph/version/version_test.go, tests/framework/installer/ceph_installer.go, tests/integration/ceph_upgrade_test.go
With the release of the first squid RC, we add squid to the supported versions and add tests to run
Rook against the squid release.
**Checklist:**
=> core: Add support for Ceph Squid

pkg/operator/ceph/csi/spec.go
The templateParam needs to be updated with the right values before we render the template.
**Checklist:**
=> csi: fix template render in logRotation

design/ceph/object/store.md
Update the vhost-style S3 bucket access design doc to reflect recent user feedback and configuration issues. The primary goal is to add a field to disambiguate for users and Rook which endpoint should be used for CephObjectStoreUsers, OBCs, and COSI buckets.
**Checklist:**
=> doc: update vhost-style S3 bucket design

pkg/operator/ceph/cluster/controller.go, pkg/operator/ceph/cluster/predicate.go, pkg/operator/ceph/cluster/watcher.go, pkg/operator/ceph/cluster/watcher_test.go, pkg/operator/ceph/cr_manager.go
Revert "csi: remove cephFs networkFence code temporarily"
mds: block of active mds ip only
currently, it was blocking both the mds ip
instead its should block ip of of mds which is in
the same node which is down.
**Checklist:**
=> mds: block of active mds ip only

Documentation/CRDs/specification.md, pkg/apis/ceph.rook.io/v1/types.go, pkg/operator/ceph/object/policy.go, pkg/util/sys/device.go
fix some comments
**Checklist:**
=> core: Fix some misspelled comments

cmd/rook/ceph/mgr.go, pkg/operator/ceph/cluster/mgr/mgr.go, pkg/operator/ceph/cluster/mgr/mgr_test.go
Closes #14477 
**Description:**  `watch-active` mgr sidecar container was using hardcoded `CephCluster.spec` to update mgr pod labels. This hardcoded spec was constructed from [sidecar cmd args](https://github.com/rook/rook/blob/master/cmd/rook/ceph/mgr.go#L54-L60)  `CephCluster.spec.monitoring.enabled` to also update mgs's `SerivceMonitor` but was missing `CephCluster.spec.labels.monitoring` and probably some other params.
**Solution:** Lookup `CephCluster.spec` from k8s cluster before handling active monitor updats.
=> mgr: lookup cluster crd on active mgr watch

tests/framework/utils/helm_helper.go
The helm upgrade tests have been failing frequently, but not always, on the oldest version of K8s that is tested in the CI for the past few months. Add a retry to attempt to get the CI passing more consistently.
Resolves #13884 
**Checklist:**
=> tests: Retry helm upgrade during upgrade tests

Documentation/CRDs/Cluster/external-cluster/external-cluster.md
curently if user want to utilise the new flags with upgrade user dont have the ability for it
Add the steps so user can make use of it
closes: https://github.com/rook/rook/issues/14368
**Checklist:**
=> doc: add upgrade steps for external cluster

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the manifests and docs to v1.14.9
**Checklist:**
=> build: Update the release version to v1.14.9

Documentation/Troubleshooting/ceph-common-issues.md
Create new topic in the the troubleshooting guide to explain how to fix a new rook-ceph deployment that could remain in an unhealthy state or fails to config because of the LimitNOFILE value specified in the containerd.service configuration. See https://github.com/rook/rook/issues/14470 .
**Checklist:**
=> docs: add troubleshooting topic for containerd LimitNOFILE issue

.mergify.yml
With the creation of the 1.15 branch, add the branch to the mergify rules. Also remove the 1.10 backport rules since no longer needed.
**Checklist:**
=> ci: Add 1.15 branch to mergify rules

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the new 1.15 branch and first test release, update the docs and manifests to v1.15.0-beta.0
**Checklist:**
=> build: Set the release version to v1.15.0-beta.0

Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md, design/ceph/object/store.md, pkg/operator/ceph/object/admin.go, pkg/operator/ceph/object/admin_test.go
RGW can only serve a single certificate. This limitation means that the prior behavior of using the default service for admin ops when TLS is enabled may mean it requires additional complex certificate management to make sure the object store uses a certificate valid for Rook internal admin ops and user connections.
This is needlessly complex for users. Instead, change Rook's behavior and documentation to clarify that it will use the same endpoint intended for S3 client applications. This means that users have a more straightforward path to enabling both Rook and consuming applications.
More info: https://github.com/rook/rook/issues/14530
Resolves #14530 
**Checklist:**
=> object: use advertise endpoint for admin ops

design/ceph/object/store.md
Design doc for #14441
**Checklist:**
=> target placement design doc

deploy/examples/csi/rbd/raw-block-pod.yaml, deploy/examples/csi/rbd/raw-block-pvc.yaml
This commit adds example yamls for block
volume mode.
Resolves #14483 
**Checklist:**
=> csi: add pvc & pod yamls for block volume mode

Documentation/Helm-Charts/operator-chart.md, PendingReleaseNotes.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/sqlitevfs-client.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml, tests/integration/ceph_upgrade_test.go
Adds a registry name to rook images
Resolves: #14545
**Checklist:**
=> manifest: add registry name to docker images

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the manifests and docs to v1.14.10
**Checklist:**
=> build: Update the release version to v1.14.10

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml, tests/framework/installer/settings.go, tests/integration/ceph_upgrade_test.go, tests/scripts/github-action-helper.sh
For the minor release update the documentation and manifests to v1.15.0
**Checklist:**
=> build: Update the release version to v1.15.0

Documentation/CRDs/Cluster/ceph-cluster-crd.md
Lists all possible values for priority class options at https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/priorityclasses.go exhaustively
**Checklist:**
=> docs: exhaustively list all priority class options

Documentation/Helm-Charts/operator-chart.md, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md, Documentation/Storage-Configuration/Ceph-CSI/custom-images.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, go.mod, go.sum, pkg/operator/ceph/csi/spec.go, tests/scripts/csiaddons.sh
updating csi-addons to latest v0.9.1 release.
**Checklist:**
=> csi: update csi-addons to v0.9.1

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and manifests to v1.15.1
**Checklist:**
=> build: Update release version to v1.15.1

pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/mon/mon_test.go
When removing a mon from quorum, there is a race condition that can result in mon quorum going being lost at least temporarily. The mon pod was being deleted first, and then the mon removed from quorum. If any other mon went down between the time the pod of the bad mon was deleted and when the mon was removed from quorum, there may not be sufficient quorum to complete the action of removing the mon from quorum and the operator would be stuck.
For example, there could be 4 mons temporarily due to timing of upgrading K8s nodes where mons may be taken down for some number of minutes. Say a new mon is started while the down mon also comes back up. Now the operator sees it can remove the 4th mon from quorum, so it starts to remove it. Now say another mon goes down on another node that is being …
=> mon: Remove extra mon from quorum before taking down pod

Documentation/Helm-Charts/operator-chart.md, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md, Documentation/Storage-Configuration/Ceph-CSI/custom-images.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/csi/util_test.go
we have 3.12.2 as the new cephcsi release updating the rook to use the same.
**Checklist:**
=> csi: update to new cephcsi release

.github/workflows/docs-check.yml, Makefile
**Description of Changes:** 
This makes the naming of CI-related make targets more systematic and consistent.
It is based on PR #14672 and continues the pattern started in that PR. 
**Checklist:**
=> CI:  rename  target check-helm-docs  to check.helm-docs

Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
Add missing csi addon's feature in the Rook document
**Checklist:**
=> doc: add the pv encryption key rotation job

.github/workflows/codespell.yaml, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, deploy/examples/monitoring/grafana/Ceph Cluster Dashboard.json, deploy/examples/monitoring/grafana/Ceph OSD Single Dashboard.json, deploy/examples/monitoring/grafana/Ceph Pools Dashboard.json, deploy/examples/monitoring/grafana/README.md
Add the Ceph Grafana dashboards that are hosted via my account on grafana.com to the docs. This would allows users to download them not just via grafana.com but also via GitHub. Additionally if the dashboards are changed we can go through the normal Rook PR flow and I'll upload the updated dashboards afterwards. 
**Checklist:**
=> docs: add grafana dashboards files to docs

Documentation/Storage-Configuration/Ceph-CSI/.pages, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot.md, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-group-snapshot.md, deploy/examples/csi/cephfs/groupsnapshot.yaml, deploy/examples/csi/cephfs/groupsnapshotclass.yaml, deploy/examples/csi/cephfs/pvc.yaml
This PR adds the sample YAMLs and documentation
for the VolumeGroupSnapshot feature.
**Checklist:**
=> docs: Add documentation for VolumeGroupSnapshot

.github/workflows/canary-test-config/action.yaml, tests/scripts/github-action-helper.sh
=> ci: fix ci permission issue with minikube start

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and example manifests to v1.14.11
**Checklist:**
=> build: Update release version to v1.14.11

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.15.2
**Checklist:**
=> build: Update release version to v1.15.2

Documentation/CRDs/Cluster/external-cluster/.pages, Documentation/CRDs/Cluster/external-cluster/advance-external.md, Documentation/CRDs/Cluster/external-cluster/consumer-import.md, Documentation/CRDs/Cluster/external-cluster/external-cluster.md, Documentation/CRDs/Cluster/external-cluster/provider-export.md, Documentation/CRDs/Cluster/external-cluster/upgrade-external.md
step1 to improve the external docs
and make it more clear to end user
**Checklist:**
=> docs: update external docs with a better structure

go.mod, pkg/apis/go.mod
this commits update the toolchain version to go v1.22.7
**Checklist:**
=> build: update toolchain to latest version

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and manifests to v1.15.3
**Checklist:**
=> build: Set the release version to v1.15.3

tests/scripts/github-action-helper.sh
This removes the execution of `sudo lsblk` three times for every single invocation of the script.  Usage of the BLOCK var is replaced with functions which memoize the result of probing for block devices.
This probably saves a fraction of a second per canary job.  The main benefit is that it allows many of the `github-action-helper.sh` functions to be run for development cycles without `sudo` being invoked.  Another benefit the removal of tight coupling of functions through global vars.
**Checklist:**
=> test: do not always run `sudo lsblk` in github-action-helper.sh

.github/workflows/canary-test-config/action.yaml, .github/workflows/integration-test-config-latest-k8s/action.yaml
This step consumes several minutes per job.
**Checklist:**
=> test: rm canary/integration "Free Disk Space" step

design/ceph/osd-migration.md
Existing OSD migration process is limited to updating the OSD backend store. This doc proposes a more generic API for the OSD migration that will help with other scenarios as well.
**Checklist:**
=> doc: osd migration design

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md, Documentation/Troubleshooting/ceph-csi-common-issues.md, pkg/operator/ceph/cluster/watcher.go
Disabling the RBD and CephFS fencing in Rook for now as it's having bugs where Rook is blocklisting the wrong IP address due to timing issues.
Resolves #14832
**Checklist:**
=> csi: disable fencing in Rook

Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-group-snapshot.md, deploy/examples/csi/cephfs/pvc.yaml, deploy/examples/csi/rbd/groupsnapshot.yaml, deploy/examples/csi/rbd/groupsnapshotclass.yaml, deploy/examples/csi/rbd/pvc.yaml
This PR adds the sample YAMLs and documentation
for the RBD VolumeGroupSnapshot feature.
=> docs: Add documentation for RBD VolumeGroupSnapshot

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.15.4
**Checklist:**
=> build: Set the release version to v1.15.4

.github/workflows/build.yml
=> ci: macos-12 will EOL soon, let's use latest tag

.github/workflows/canary-integration-test.yml, deploy/examples/object-separate-pools-test.yaml, deploy/examples/two-object-one-zone-test.yaml, tests/scripts/collect-logs.sh, tests/scripts/github-action-helper.sh
=> test: add two-object-one-zone canary test

pkg/operator/ceph/object/bucket/provisioner.go, pkg/operator/ceph/object/bucket/provisioner_test.go, pkg/operator/ceph/object/bucket/util.go
Previously, up to 3 calls to SetUserQuota() could be made.  This has been consolidated into a single call.  Additionally, the `addtionalConfigSpec` struct is introduced to centralize handling of `.spec.additionalConfig` keys and as foundational work to support new keys in the future.
Related to #14764  & #14815
**Checklist:**
=> object: set obc user quota(s) in one SetUserQuota() call

deploy/examples/operator.yaml
add missing `v` in the cephcsi image version.
Resolves #14822
**Checklist:**
=> csi: fix typo in image version

pkg/operator/ceph/object/json_helpers.go, pkg/operator/ceph/object/json_helpers_test.go, pkg/operator/ceph/object/objectstore.go, pkg/operator/ceph/object/shared_pools.go, pkg/operator/ceph/object/shared_pools_test.go
=> rgw: support new zone pools

.github/workflows/canary-integration-test.yml, Documentation/Storage-Configuration/Advanced/key-management-system.md, pkg/daemon/ceph/osd/kms/kms.go, pkg/operator/ceph/cluster/osd/key_rotation.go, tests/scripts/deploy-validate-vault.sh
Rook already has Key rotation algorithm implemented for default type https://github.com/rook/rook/pull/11749 (encryption keys are stored in a K8s Secret).
This PR adds key rotation support for vault KMS using the same algorithm.
**Checklist:**
=> kms: key rotation support for vault kms

Documentation/CRDs/Cluster/external-cluster/advance-external.md, Documentation/CRDs/Cluster/external-cluster/external-cluster.md, Documentation/CRDs/Cluster/external-cluster/upgrade-external.md
some of the links have the full path
which is not working in the doc server,
but works locally
**Checklist:**
=> docs: fix external doc broken links

Makefile
**Description of changes:** 
As suggested by @BlaineEXE in  a review comment ( https://github.com/rook/rook/pull/14700#discussion_r1815351982),
the goal  of this PR is to make all generating make targets more systematic.
Concretely, the following targets are added, as aliases of corresponding existing targets:
* `gen.codegen`
*  `gen.rbac`
* `gen.docs`
* `gen.crds`
* `gen.crd-docs`
All generating targets are run by a new target `generate`.
<!-- Uncomment this section with the issue number if an issue is being resolved
**Checklist:**
=> Make generating make targets more  systematic

deploy/charts/rook-ceph/templates/role.yaml, deploy/examples/common.yaml
csiaddons required new RBAC in the next release to create/update the csiaddonsnode object based on the owner deployment/daemonset names of the pods its running with.
**Checklist:**
=> csi: add new RBAC required for csiaddons

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/multus-validation.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.14.12
**Checklist:**
=> build: Update the release version to v1.14.12

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.15.5
**Checklist:**
=> build: Update the release version to v1.15.5

Documentation/CRDs/specification.md, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go, pkg/operator/ceph/pool/controller.go, pkg/operator/ceph/pool/status.go
Adding pool ID of the cephBlockPool in the CR status
Testing: 
```
kubectl get cephblockpools.ceph.rook.io  -n rook-ceph builtin-mgr -o yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
creationTimestamp: "2024-11-07T05:58:41Z"
finalizers:
- cephblockpool.ceph.rook.io
generation: 2
name: builtin-mgr
resourceVersion: "3083"
uid: 690f018e-6a66-4523-a981-ae3366860abd
spec:
status:
info:
failureDomain: host
type: Replicated
observedGeneration: 2
phase: Ready
poolID: 1
```
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
creationTimestamp: "2024-11-07T06:09:25Z"
finalizers:
- cephblockpool.ceph.rook.io
generation: 2
name: replicapool
resourceVersion: "3506"
uid: e76578df-d005-4e5d-9abc-237f3b849d98
spec:
status:
info: …
```
=> core: add pool IDs to cephBlockPool CR status

deploy/charts/rook-ceph/templates/role.yaml, deploy/examples/common.yaml
we need to have access to finalizers when we set the blockOwnerDeletion if an ownerReference refers to a resource
we can't set finalizers on, This adds the extra required permission
**Checklist:**
=> csi: add required finalizers for openshift

Documentation/CRDs/Cluster/external-cluster/provider-export.md
update the incstruction for where to run python script
**Checklist:**
=> external: fix external cluster docs

pkg/operator/ceph/cluster/osd/topology/topology.go
When node topology labels with duplicate values are detected, rook silently discards all but one label. This adds a warning informing administrators of this, allowing for easier identification of labeling issues. Without this, there is no indication of why labels are ignored, which makes tracking down CRUSH map issues difficult.
**Checklist:**
=> rook: add warning when duplicate node topology values are detected

pkg/operator/ceph/csi/ceph_connection.go, pkg/operator/ceph/csi/ceph_connection_test.go, pkg/operator/ceph/csi/config.go, pkg/operator/ceph/csi/config_test.go, pkg/operator/ceph/csi/operator_config.go, pkg/operator/ceph/csi/operator_config_test.go, pkg/operator/ceph/csi/operator_driver.go
this commit fix the code error faced during e2e testing in different PR. This PR is just subset of PR #14766. We don't want to include CI changes in this PR yet.
**Checklist:**
=> csi: fix new csi-operator related changes

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.15.6
**Checklist:**
=> build: Update release version to v1.15.6

pkg/operator/ceph/object/zone/controller.go, pkg/operator/ceph/object/zone/controller_test.go
Closes #15034
What was done: zone creation logic was moved to a separate function `createZoneIfNotExists`. Now when zone exists controller retuns from this function and continues with pools configuration instead of returning from reconcile loop.
=> rgw: fix shared pools for zone

Documentation/Helm-Charts/operator-chart.md, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md, Documentation/Storage-Configuration/Ceph-CSI/custom-images.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/csi/util_test.go
cephcsi fixed a bug related to data loss and its fixed in 3.12.3 release, This commit updates the cephcsi to 3.12.3 release.
**Checklist:**
=> csi: update to latest cephcsi release

Documentation/Upgrade/ceph-upgrade.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/filesystem-ec.yaml, deploy/examples/filesystem.yaml, deploy/examples/object-a.yaml, deploy/examples/object-b.yaml, deploy/examples/object-openshift.yaml, deploy/examples/object.yaml
Update upgrade guides, docs, and exmaple manifests for the Rook v1.16 release.
**Checklist:**
=> docs: update guides and examples for v1.16 release

CODE-OWNERS
=> ci: Add Artem to the reviewers list

Documentation/Helm-Charts/operator-chart.md, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md, Documentation/Storage-Configuration/Ceph-CSI/custom-images.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/csi/util_test.go
cephcsi [3.13.0](https://github.com/ceph/ceph-csi/releases/tag/v3.13.0) is released today and update the Rook to use the latest image
**Checklist:**
=> csi: update cephcsi to latest release

Documentation/Upgrade/ceph-upgrade.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/filesystem-ec.yaml, deploy/examples/filesystem.yaml, deploy/examples/object-a.yaml, deploy/examples/object-b.yaml, deploy/examples/object-openshift.yaml, deploy/examples/object.yaml
Update upgrade guides, docs, and exmaple manifests for the Rook v1.16 release.
Supersedes #15120 
**Checklist:**
=> docs: update guides and examples for v1.16 release (backport #15105)

.github/workflows/canary-test-config/action.yaml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-keystone-auth-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, .mergify.yml, Documentation/Getting-Started/Prerequisites/prerequisites.md, Documentation/Getting-Started/quickstart.md, PendingReleaseNotes.md, tests/scripts/github-action-helper.sh
With the release of K8s 1.32, we update the CI and docs to support this new release, to maintain the most recent six releases of K8s.
**Checklist:**
=> build: Add support for K8s 1.32

PendingReleaseNotes.md, pkg/operator/ceph/object/bucket/provisioner.go, pkg/operator/ceph/object/bucket/provisioner_test.go, pkg/operator/ceph/object/bucket/util.go, pkg/operator/ceph/object/notification/provisioner.go, pkg/operator/ceph/object/s3-handlers.go, pkg/operator/ceph/object/s3-handlers_test.go, tests/framework/clients/bucket.go, tests/integration/ceph_bucket_notification_test.go, tests/integration/ceph_object_test.go
Alternative PR to  #14889
Related to #14815
**Checklist:**
=> object: add bucketPolicy to obc

design/ceph/object/store.md
Add a design for CephObjectStore to allow users to pass through Ceph configs (e.g., `rgw_enable_apis`, `debug_rgw`) to the object store. This design will help users set configs that they want for their environments that aren't covered under Rook's umbrella of managed configs. This will benefit users by allowing them to make use of rare RGW features that Rook devs don't have ability to prioritize, as well as newly-released RGW features that Rook devs haven't had time to plan API interfaces for. This frees up Rook developers to focus effort on implementing APIs that have integration benefits with Kubernetes or other resources and less effort on simple configs.
Resolves #14753
**Checklist:**
=> doc: design ceph config passthru for object store

Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md, deploy/charts/rook-ceph-cluster/values.yaml, deploy/examples/object-ec.yaml, deploy/examples/object-multisite-pull-realm.yaml, deploy/examples/object-multisite.yaml, deploy/examples/object-openshift.yaml, deploy/examples/object.yaml
Closes #14770
sets bulk=true for rgw osd data pool by default
=> rgw: bulk data pool by default

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.15.7
**Checklist:**
=> build: Update the patch version to v1.15.7

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the minor release update the docs and examples to v1.16.0.
**Checklist:**
=> build: Update release version to v1.16.0

tests/scripts/github-action-helper.sh
Many of the canary tests have been failing much more frequently in the past week or two in the daily CI. The test is typically timing out pulling the image from `quay.ceph.io` since it does not have as high bandwidth for the images. A check is added to the test to wait specifically for the first mon so it waits sufficiently for the image pull before checking for other ceph daemons.
**Checklist:**
=> tests: Canary tests to wait for first mon to start

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.16.1.
**Checklist:**
=> build: Set release version to v1.16.1

ADOPTERS.md
Hi, we utilize Rook-Ceph in our product Alauda Container Platform(ACP).
We are very happy to be a adopter of Rook, and I'd like to share this information to you.
Thanks
=> doc: add adopter

Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md
Related to #15138
**Checklist:**
=> doc: add basic obc bucketPolicy description

PendingReleaseNotes.md
For the upcoming 4.17 release, we reset the pending release notes so we can add new features to the list.
**Checklist:**
=> docs: Reset pending release notes

ROADMAP.md
For the upcoming 1.17 release, update the high level features that are targeted.
This is not intended to be a complete list, as the full features are intended to be tracked in the [project board](https://github.com/orgs/rook/projects/7/views/1).
**Checklist:**
=> docs: Update roadmap for release 1.17

pkg/operator/ceph/config/monstore.go
=> operator: omit values from mon db config logs

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and manifests to v1.15.8
**Checklist:**
=> build: Set release version to v1.15.8

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.16.2
**Checklist:**
=> build: Set release version to v1.16.2

pkg/operator/ceph/object/objectstore.go, tests/scripts/multus/host-cfg-ds.yaml
=> ci: codespell: s/re-using/reusing/

Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md, pkg/operator/ceph/object/bucket/provisioner.go, pkg/operator/ceph/object/bucket/provisioner_test.go, pkg/operator/ceph/object/bucket/util.go, tests/integration/ceph_object_test.go
Related to #14815
**Checklist:**
=> object: add bucketLifecycle to obc

pkg/operator/ceph/config/monstore.go
Follow up to [discussion](https://github.com/rook/rook/pull/15270#discussion_r1916880157) in #15270
=> operator: log mon db config values with trace lvl

ADOPTERS.md
Add Thalassa Cloud to the list of adopter of Rook Ceph
**Checklist:**
=> docs: add Thalassa Cloud to Adopters

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
=> build: Updates spf13 pflag from 1.0.5 to 1.0.6

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.16.3
**Checklist:**
=> build: Update the release version to v1.16.3

Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md, pkg/operator/ceph/object/bucket/provisioner.go, pkg/operator/ceph/object/bucket/provisioner_test.go, pkg/operator/ceph/object/bucket/rgw-handlers.go, pkg/operator/ceph/object/bucket/rgw-handlers_test.go, pkg/operator/ceph/object/bucket/util.go, tests/integration/ceph_object_test.go, tests/integration/object/bucketowner/bucketowner.go
Related to #14815
**Checklist:**
=> object: add obc bucketOwner

Documentation/CRDs/Cluster/ceph-cluster-crd.md, Documentation/CRDs/Cluster/host-cluster.md, Documentation/CRDs/Cluster/pvc-cluster.md, Documentation/CRDs/Cluster/stretch-cluster.md, Documentation/Upgrade/ceph-upgrade.md, deploy/charts/rook-ceph-cluster/values.yaml, deploy/examples/cluster-external-management.yaml, deploy/examples/cluster-on-local-pvc.yaml, deploy/examples/cluster-on-pvc.yaml, deploy/examples/cluster-stretched-aws.yaml, deploy/examples/cluster-stretched.yaml, deploy/examples/cluster.yaml, deploy/examples/images.txt, design/ceph/ceph-cluster-cleanup.md, tests/manifests/test-cluster-on-pvc-encrypted.yaml
with ceph release v19.2.1 updating it to be dafult version in rook.
**Checklist:**
=> manifest: Update default ceph version to v19.2.1

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and manifests to v1.16.4
**Checklist:**
=> build: Update release version to v1.16.4

Documentation/Getting-Started/Prerequisites/authenticated-registry.md
=> doc: Authenticated Container Registry | Typo for imagePullSecrets

.github/workflows/canary-integration-test.yml, tests/scripts/github-action-helper.sh
=> ci: Increase rgw multisite test timeout for s3 client call

Documentation/Contributing/development-flow.md
**Description of changes:** 
The development  guide mentioned that commit messages should be lengthy which has a negative connotation of meaning long-winded.
This change rewords the corresponding part to sound   more positive.
**Checklist:**
=> docs: slight rewording in development guide

.github/workflows/push-build.yaml
Publishing packages to ghcr requires the packages write permission
**Checklist:**
=> ci: Add packages write permission for ghcr

pkg/operator/ceph/controller/predicate.go
=> fix: typo in log statement

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and manifests to v1.15.9.
**Checklist:**
=> build: Set release version to v1.15.9

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and manifests to v1.16.5.
**Checklist:**
=> build: Set release version to v1.16.5

pkg/daemon/ceph/client/command.go
dont overwrite err incase of stderr
**Checklist:**
=> core: dont overwrite err incase of stderr

tests/framework/installer/ceph_installer.go, tests/framework/installer/ceph_manifests.go, tests/framework/installer/ceph_manifests_previous.go, tests/framework/installer/ceph_settings.go, tests/framework/utils/k8s_helper.go, tests/integration/ceph_upgrade_test.go
=> ci: Install csi-op in integration tests

pkg/operator/ceph/file/subvolumegroup/controller_test.go, pkg/operator/ceph/pool/radosnamespace/controller_test.go
let's just add csi-op unit tests in rns and svg
we'll add more code in future.
**Checklist:**
=> csi: add csi-op api in unit tests

pkg/operator/ceph/object/user/controller.go
`objectuser.reconcile()` has a number of error triggered return statements which do not update the CR's status to reflect a reconcile failure.
`objectuser.updateStatus()` appears to have handling for when the CR has been deleted, so it should be safe to call any time `objectuser.reconcile` returns an error.
**Checklist:**
=> object: all CephObjectStoreUser reconcile errors set .status.phase

pkg/operator/ceph/controller/predicate.go, pkg/operator/ceph/controller/predicate_test.go
This label is not currently in use by rook.
**Checklist:**
=> core: rm controller-runtime predicate support for ceph_version label

.github/workflows/build.yml, .github/workflows/helm-lint.yaml, Makefile, build/crds/build-crds.sh, build/makelib/golang.mk, build/makelib/helm.mk, build/rbac/keep-added.sh, build/rbac/keep-rbac-yaml.sh, build/release/Makefile
Resolves #15218
**Checklist:**
=> ci: publish helm charts to oci repos

Documentation/Storage-Configuration/ceph-teardown.md
Resolves #15545 
**Checklist:**
=> docs: update commands for zapping devices

pkg/operator/ceph/object/topic/controller.go
topic.reconcile() had a number of error triggered return statements which did not update the CR's status to reflect a reconcile failure.
**Checklist:**
=> object: all CephBucketTopic reconcile errors set .status.phase

build/release/Makefile
Fixes build related issue caused by #15542 
- [job](https://github.com/rook/rook/actions/runs/14044447157/job/39321910039)
**Checklist:**
=> ci: fix version of chart not existing

build/release/Makefile
=> ci: fix push version mismatch

.github/workflows/build.yml, .github/workflows/helm-lint.yaml, Makefile, build/crds/build-crds.sh, build/makelib/golang.mk, build/makelib/helm.mk, build/rbac/keep-added.sh, build/rbac/keep-rbac-yaml.sh, build/release/Makefile
Publish the helm charts to the OCI registries docker, quay, and ghcr. Backport of three PRs: #15542, #15580, #15585
**Checklist:**
=> ci: Publish helm charts to the OCI registries docker, quay, and ghcr (backport #15542)

.vscode/settings.json
Enable gofumpt formatter in the recommended vscode settings.
**Checklist:**
=> build: add enable gofumpt in suggested vscode conf

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and docs to v1.16.6
**Checklist:**
=> build: Update release version to v1.16.6

.mergify.yml
For the new 1.17 branch, configure mergify to open backport PRs and automatically merge to the 1.17 branch.
**Checklist:**
=> ci: Add 1.17 branch to mergify backports

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the 1.17 initial beta release update the docs and examples to v1.17.0-beta.0
**Checklist:**
=> build: Set the release version for the v1.17.0-beta.0 release

.github/workflows/canary-integration-test.yml, deploy/examples/create-external-cluster-resources.py, images/ceph/Makefile
With the stable release of v19.2.0, we update the Rook operator base image to use this version to ensure
compatibility of ceph commands, in particular for
radosgw-admin.
**Checklist:**
=> build: Update base operator image to squid

pkg/daemon/ceph/cleanup/subvolumegroups.go
=> fix call errors.Wrapf with a nil value error after check another err

pkg/operator/ceph/csi/csi.go, pkg/operator/ceph/csi/csidriver.go, pkg/operator/ceph/csi/spec.go
EnableCSIDriverSeLinuxMount is always set to true , This commit remove the extra variable as its a introduced where we supported older kubernetes version.
**Checklist:**
=> csi: remove dummy code in csi driver creation

Documentation/Upgrade/rook-upgrade.md, PendingReleaseNotes.md
Update pending release notes and upgrade docs for v1.17.
**Checklist:**
=> doc: update release notes and upgrade docs

Makefile
This adds a few improvements to the Makefile:
* a target 'checkmake' is added to lint the Makefile for syntactic correctness.
* a few checkmake errors are fixed.
* * 'make help' output is improved.
**Checklist:**
=> some Makefile improvements

pkg/operator/ceph/pool/controller.go, pkg/operator/ceph/pool/status.go
In some cases, for example, kube-api flaps, CephBlockPool's status could be failed to update. In that case, rook-operator does not tries to update status again. This fix requests for requeue if pool's status update is failed.
Resolves #10356
**Checklist:**
=> pool: retry status update on fail

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Updated oauth package to address - https://access.redhat.com/security/cve/cve-2025-22868
**Checklist:**
=> update oauth package Fix CVE 2025 22868

Documentation/Helm-Charts/operator-chart.md, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md, Documentation/Storage-Configuration/Ceph-CSI/custom-images.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/csi/util_test.go
This commit updates cephcsi version to 3.14.0
in rook.
**Checklist:**
=> csi: update cephcsi to v3.14.0

Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
Resolves #15694 
**Checklist:**
=> docs: fix typos in CephObjectStoreUser.spec.keys example

Documentation/Upgrade/rook-upgrade.md, PendingReleaseNotes.md
Related to #15554 
Resolves #15711
**Checklist:**
=> doc: add CephBucketTopic kafka mechanism field to upgrade docs

pkg/operator/ceph/cluster/mon/service.go
In case of multicluster service, we need to always delete the mon-canary pods even if there is any failure while exporting the service, else multiple mon canary pods will get created.
Resolves #15717
**Checklist:**
=> mon: always delete mon canary pods

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.16.7
**Checklist:**
=> build: Update release version to 1.16.7

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml, tests/framework/installer/ceph_manifests_previous.go
For the minor release update the examples and docs to v1.17.0
**Checklist:**
=> build: Update release version to v1.17.0

build/release/README.md
**Description of changes:** 
Reading the release process documentation, I found the description of steps in one place to not quite match the intended effect of the actual command steps due to a slight imprecision in used terminology.
This change improves and clarifies the corresponding wording to hopefully prevent others from facing the same confusion.
**Checklist:**
=> docs: slightly improve wording in release guide

Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md
This PR corrects the indentation of the dashboard block and adds the missing enabled: true field in the YAML example.
Fixes: #15768 
**Checklist:**
=> doc: fix indentation and add enabled: true in dashboard config example

Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, tests/framework/installer/ceph_installer.go, tests/scripts/auto-grow-storage.sh, tests/scripts/create-dev-cluster.sh, tests/scripts/github-action-helper.sh
This PR updates the Prometheus Operator URL references from version v0.71.1 to the latest release v0.81.0 in documentation and integration test scripts.
This ensures we are aligned with the latest features and improvements from the Prometheus Operator project.
**Checklist:**
Fixes: #15701
=> test: update Prometheus Operator to v0.82.0

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and docs to v1.17.1
**Checklist:**
=> build: Update release version to v1.17.1

pkg/daemon/ceph/osd/remove.go
ceph-volume raw list will return the main disk instead of the mpath setup. `ceph-volume lvm zap` on the main disks fails. This PR uses `lsblk /mnt/<diskreference> ` to fetch the actual mapath disk and use it for cleaning
Testing: 
Before the fix: Notice that `ceph-volume raw list` returns OSD info with device name as `/dev/sdb`. And running `ceph-volume lvm zap` on the parent disk causes failure. 
```
[santosh@hetzner-dominguez ~]$ oc logs rook-ceph-osd-prepare-a349f13b45cd5b2d3f756a6f216d59c2-vfc6q
Defaulted container "provision" out of: provision, copy-bins (init), blkdevmapper (init)
2025/04/21 14:14:18 maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
2025-04-21 14:14:18.766927 I | cephcmd: desired devices to configure osds: [{Name:/mnt/ocs-deviceset-odf-disks-0-data-0jtnxv …
```
=> osd: fix osd disk cleanup for mpath setups

.github/workflows/checkmake.yaml
**Description of changes:** 
This adds 
linting of   the Makefile in the CI
in order to prevent PRs from introducing errors in the Makefile
**Checklist:**
=> ci: add a checkmake workflow

pkg/operator/ceph/object/user/controller.go
When multiple `CephObjectStoreUser` CRs are present, the operator logs a high volume of `CephObjectStore "foo" found` messages during reconcile.
**Checklist:**
=> object: change `CephObjectStore "foo" found` log level to debug

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the examples and docs
to v1.17.2
**Checklist:**
=> build: Prepare the v1.17.2 release

pkg/operator/ceph/file/subvolumegroup/controller.go, pkg/operator/ceph/pool/radosnamespace/controller.go
there can be a scenario where a new svg cr is created with
the same svg.filesystem and svg.spec.name, in that case we want to delete
the old svg CR without checking dependent child resources.
All the SVG:
```
kubectl  get cephfilesystemsubvolumegroups.ceph.rook.io  -o custom-columns=CRD-NAME:.metadata.name,SPEC-NAME:.spec.name
CRD-NAME   SPEC-NAME
group-a    csi
group-b    <none>
myfs-csi   csi
```
rook-operator logs, when I added code locally to print list of SVG 
```
2025-05-15 10:50:31.253259 I | ceph-fs-subvolumegroup-controller: 
2025-05-15 10:50:31.253275 I | ceph-fs-subvolumegroup-controller: 
2025-05-15 10:50:31.253278 I | ceph-fs-subvolumegroup-controller: group-a
2025-05-15 10:50:31.253280 I | ceph-fs-subvolumegroup-controller: myfs-csi
2025-05-15 10:50:31.253282 I | …
```
=> core: delete old svg/rns cr with same svg/rns  name

deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go
This commit Assigns short names to all Rook CRDs to improve kubectl usability.
Addresses https://github.com/rook/rook/issues/15863
**Checklist:**
=> core: add short names to rook CRDs

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.17.3
**Checklist:**
=> build: Update the release version to v1.17.3

design/ceph/ceph-managed-disruptionbudgets.md
doc: improve ceph-managed-disruptionbudgets.md
**Checklist:**
=> doc: improve ceph-managed-disruptionbudgets.md

.github/workflows/build.yml, .github/workflows/helm-lint.yaml, build/makelib/helm.mk, tests/scripts/helm.sh
**Description of Changes:** 
This updates the helm version used to the latest 
**Checklist:**
=> ci: use latest helm version 

Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
The documentaiton around object store certificates does not specify how to deal with internally issued certs being used on the RGW. From my testing it is possible to get the rook operator to validate the RGW certs if the entire certificate chain is put into the `cert` field of the `sslCertificateRef` secret.
Additionally, the docs are linking to a broken civetweb link but rook is now using the beast frontend, so I fixed that link to point towards the beast frontend documentation instead.
There was also some confusion around the `caBundleRef` and how that is used so I made the docs more explicit that the `caBundleRef` is used by the RGW to connect to external services such as LGW and mulitsite RGW.
Resolves: #14393
**Checklist:**
=> doc: improve documentation around object store certificates

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.16.8
**Checklist:**
=> build: update release version to 1.16.8

pkg/daemon/ceph/osd/volume.go, pkg/daemon/ceph/osd/volume_test.go
During the OSD preparation step, if the encrypted OSD disk belongs to a different cluster, then clean the disk if `wipeDeviceFromOtherClusters` is set to true.
(This is a follow-up PR of #15796 for encrypted OSDs) 
Testing:
```
kubectl logs rook-ceph-osd-prepare-set1-data-08hwft-wt2l8  -n rook-ceph
Defaulted container "provision" out of: provision, copy-bins (init), blkdevmapper (init)
2025/06/10 07:24:58 maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined
2025-06-10 07:24:58.955730 I | cephcmd: desired devices to configure osds: [{Name:/mnt/set1-data-08hwft OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: InitialWeight: IsFilter:false IsDevicePathFilter:false}]
2025-06-10 07:24:58.958713 I | rookcmd: starting Rook v1.17.0-alpha.0.266.g748e3cd11-dirty with arguments …
```
=> osd: wipe encryted osd disk from other cluster

Documentation/Helm-Charts/operator-chart.md, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md, Documentation/Storage-Configuration/Ceph-CSI/custom-images.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/csi/util_test.go
Updating the cephcsi version to v3.14.1 release.
**Checklist:**
=> csi: update csi version to 3.14.1

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.17.6
**Checklist:**
=> build: Update release version to v1.17.6

.github/workflows/canary-integration-test.yml
Resolves comment: https://github.com/rook/rook/pull/15666#pullrequestreview-3003761181
**Checklist:**
=> ci: refactor cluster teardown logic

pkg/operator/ceph/object/admin.go, pkg/util/exec/exec_pod.go
Closes #16101 
**Problem:** 
```shell
radosgw-admin zone/zonegroup set --infile=<path to json file>
```
The command above accepts file which works fine when operator executes command on the same host. For Multus clusters, operator executes commands in remote `cmd-proxy` container. In this case execution will fail if the file will not be presented inside remote container.
**Solution:** 
- Check if cluster is using Multus network and command contains `--infile` arg 
- copy the file to remote container before executing command
=> multus: support copy file to cmd-proxy container for rgw zone set

Documentation/Helm-Charts/operator-chart.md, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md, Documentation/Storage-Configuration/Ceph-CSI/custom-images.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/csi/util_test.go
Updating the ceph-csi image to 3.14.2 release.
Resolves #16156 
**Checklist:**
=> csi: update ceph-csi to 3.14.2

deploy/charts/rook-ceph/values.yaml
Nothing big, just correcting the commented example resource limits/requests.
=> correct example resources

tests/integration/object/bucketowner/bucketowner.go, tests/integration/object/user/userkeys/userkeys.go, tests/integration/object/util/admin/admin.go, tests/integration/object/util/s3/s3.go, tests/integration/object/util/sns/sns.go
=> test: factor out util/admin package for setup of ceph admin client

tests/framework/installer/ceph_installer.go, tests/framework/installer/ceph_manifests.go, tests/framework/installer/ceph_manifests_previous.go, tests/integration/ceph_upgrade_test.go
For the integration tests, now we start upgrading from v1.17.x to the master branch, to test that the upgrades are stable to what will become the 1.18 release.
**Checklist:**
=> tests: Upgrade from 1.17 to master

pkg/daemon/ceph/cleanup/hostpath.go
delete csi-related directories from /var/lib/rook that match the suffix `.csi.ceph.com`.
these folders were used in earlier versions when rook managed cephcsi directly. in later versions, logs and data are redirected to /var/lib/cephcsi, but legacy paths may still exist and require cleanup during uninstall.
this change improves cleanup completeness for odf 4.18 and earlier.
[](https://issues.redhat.com/browse/DFBUGS-2585 )
example of directories removed:
- `/var/lib/rook/openshift-storage.cephfs.csi.ceph.com`
- `/var/lib/rook/openshift-storage.rbd.csi.ceph.com`
**Tested locally:**
```
1.Create cephcluster CR on minkube
2.Check /var/lib/rook/ dir content:
$ minikube ssh
$ ls /var/lib/rook/
exporter  mon-a  rook-ceph
3.Add manually some "CSI" folders to /var/lib/rook/
minikube ssh
$ cd …
```
=> core: cleanup csi-related folders from /var/lib/rook during uninstall

deploy/examples/csi-operator.yaml
this yaml contains all the rbac, crds and csi-operator deployment all-in-one.
**Checklist:**
=> csi: update csi-operator yaml to version v0.4.0

pkg/operator/ceph/cluster/rbd/config.go
Resolves #16255
**Checklist:**
=> operator: Removed legacy secret deletion code in rbd

pkg/daemon/discover/discover.go
This PR deletes the logs stored in /var/log/ceph on the discover daemon nodes. This file contains the logs from runs of `ceph-volume`. Further discussion on this log file is present in the linked issue.
Resolves #16253
**Checklist:**
=> operator: delete ceph-volume logs to reduce discover daemon log size

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.16.9
**Checklist:**
=> build: Update release version to v1.16.9

Documentation/Helm-Charts/operator-chart.md, Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md, Documentation/Storage-Configuration/Ceph-CSI/custom-images.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/csi/util_test.go
We have new release for Ceph-CSI v3.15.0 -
https://github.com/ceph/ceph-csi/releases/tag/v3.15.0
**Checklist:**
=> csi: update ceph-csi to v3.15.0

design/ceph/cephx-keyring-rotation.md
Add a design doc to addres RFE #15904.
This design outlines important UX and implementation details for achieving automated/assisted workflows for rotating CephX authentication keys for Ceph daemons and other clients.
**Checklist:**
=> doc: add design for cephx key rotation

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.17.8
**Checklist:**
=> Release 1.17 prepare v1.17.8

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the minor release update the examples and docs to v1.18.0
**Checklist:**
=> build: update release version to v1.18.0

ADOPTERS.md
=> docs: add Sophotech to adopters list

pkg/operator/ceph/csi/secrets.go, pkg/operator/ceph/csi/secrets_test.go
Fix an issue where keepPriorKeyCountMax would be counted differently when rotation was currently in progress, versus when rotation was not in progress.
I found this issue when I was testing CSI key behavior that happens on CephCluster re-reconcile and what happens when just the `keepPriorKeyCountMax` value is changed. I was seeing that when `keepPriorKeyCount: 1` was set, Rook would sometimes delete all extra keys and keep only the active keys.
The logic as written and unit tested previously assumed the user input (prior count) was a count of total keys that should be active instead of a count of only the old/prior keys that should remain in addition to the latest active key. This resulted in off-by-one logic.
From my testing, I think this resolves the last of the off-by-one issues. …
=> csi: fix prior cephx key deletion logic

Documentation/Getting-Started/quickstart.md, Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md, Documentation/Upgrade/rook-upgrade.md, deploy/charts/rook-ceph/values.yaml, deploy/examples/direct-mount.yaml, deploy/examples/images.txt, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox-operator-image.yaml
For the patch release update the docs and examples to v1.18.2
**Checklist:**
=> build: Set release version to v1.18.2

Documentation/CRDs/Object-Storage/ceph-object-realm-crd.md, Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md, Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
=> docs: add cephobjectrealm.spec.defaultrealm field to examples

Documentation/CRDs/specification.md, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go
=> core: fix ObjectZoneSpec.ZoneGroup and ObjectZoneGroupSpec.Realm field descriptions

.github/workflows/daily-nightly-jobs.yml, pkg/operator/ceph/cluster/version_test.go, pkg/operator/ceph/version/version.go, pkg/operator/ceph/version/version_test.go, tests/integration/ceph_upgrade_test.go
we are now adding tentacle to the supported versions and add the upgrade test from squid to tentacle.
**Checklist:**
=> core: add support for ceph tentacle

.github/workflows/codespell.yaml, CODE-OWNERS, OWNERS.md
=> doc: add parth arora to the maintainers list

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
with latest design for networkFence, no need for
csi-addons to be installed as the implementation
is moved to csi-drivers.
Resolves #16513
**Checklist:**
=> csi: csi-addon no longer needed for network fence

pkg/operator/ceph/csi/operator_driver.go, pkg/operator/ceph/csi/operator_driver_test.go
The csi volumes and volume mount settings are now converted to the csi operator driver CR, for example to allow nix os mounts to be applied to the csi node plugins.
Resolves #16370
**Checklist:**
=> csi: Convert csi operator volume settings
