rook/rook

- demo/vagrant/cloud-config.yml.in
> Remove old quay keys

- pkg/util/sys/device.go
- pkg/util/sys/device_test.go
Addresses https://github.com/rook/rook/issues/168
> Look for devices using a cleaned mount point

- pkg/api/image.go
- pkg/api/routes.go
- pkg/cephmgr/ceph.go
- pkg/cephmgr/cephleader.go
- pkg/cephmgr/cephleader_test.go
- pkg/cephmgr/mds/agent.go
- pkg/cephmgr/mds/agent_test.go
- pkg/cephmgr/mds/filesystem.go
- pkg/cephmgr/mds/leader.go
- pkg/cephmgr/mds/leader_test.go
- pkg/cephmgr/mds/log.go
- pkg/cephmgr/mon/agent.go
- pkg/cephmgr/mon/config.go
- pkg/cephmgr/mon/conn_test.go
- pkg/cephmgr/mon/leader_test.go
- pkg/cephmgr/osd/agent.go
- pkg/cephmgr/osd/config.go
- pkg/cephmgr/osd/device.go
- pkg/cephmgr/test/info.go
Fixes https://github.com/rook/rook/issues/163.
> Add or remove a single file system in the storage cluster

- cmd/rook/main.go
- cmd/rook/node/list.go
- cmd/rook/node/list_test.go
- cmd/rook/object/connection.go
- cmd/rook/object/connection_test.go
- cmd/rook/object/create.go
- cmd/rook/object/create_test.go
- cmd/rook/object/object.go
- pkg/api/client.go
- pkg/api/object.go
- pkg/api/object_test.go
- pkg/api/routes.go
- pkg/cephmgr/rgw/agent.go
- pkg/cephmgr/rgw/leader.go
- pkg/cephmgr/rgw/leader_test.go
- pkg/cephmgr/rgw/user.go
- pkg/cephmgr/rgw/user_test.go
- pkg/model/object.go
- pkg/rook/client/client.go
- pkg/rook/client/client_test.go
- pkg/rook/client/object.go
- pkg/rook/test/mockclient.go
> rook tool support for object store creation and client connections

- README.md
- demo/kubernetes/README.md
- demo/kubernetes/rook-client/Dockerfile
- demo/kubernetes/rook-client/rook-client.yml
- demo/kubernetes/rook.yml
Significant updates to the k8s demo flow, please review those carefully and speak up if the flow doesn't make sense or could be improved.  I think reading markdown diffs is difficult, so best way to review the readme will probably be to read it directly at https://github.com/jbw976/rook/blob/master/demo/kubernetes/README.md
> kubernetes pod spec and documentation for running a rook-client pod

- demo/kubernetes/README.md
> docs: Add troubleshooting section for kubernetes rookd readme

- pkg/etcdmgr/bootstrap/discovery.go
> Handle a nil response from etcd discovery service more gracefully

- pkg/cephmgr/leader.go
- pkg/cephmgr/leader_test.go
In the first orchestration, all of the nodes should be refreshed for OSDs. Fixes #322
> Refresh all OSDs on the first refresh

- cmd/rookd/main.go
- demo/vagrant/util.rb
- pkg/api/handlers_test.go
- pkg/cephmgr/cephmgr.go
- pkg/cephmgr/leader_test.go
- pkg/cephmgr/osd/agent.go
- pkg/cephmgr/osd/agent_test.go
- pkg/cephmgr/osd/device.go
- pkg/cephmgr/osd/device_test.go
- pkg/cephmgr/osd/partition/scheme.go
- pkg/cephmgr/osd/partition/scheme_test.go
- pkg/clusterd/inventory/disk.go
- pkg/clusterd/inventory/disk_test.go
- pkg/clusterd/inventory/hardware.go
- pkg/clusterd/inventory/node_test.go
- pkg/util/sys/device.go
- pkg/util/sys/device_test.go
>  Allow OSD bluestore partitions to be separated to a dedicated high performance metadata device (e.g., NVMe/SSD)

- cmd/rookd/main.go
- demo/vagrant/Vagrantfile
- pkg/cephmgr/mon/config.go
- pkg/cephmgr/mon/config_test.go
- pkg/cephmgr/osd/device.go
- pkg/clusterd/clusterservice.go
- pkg/clusterd/join.go
- pkg/clusterd/network.go
- pkg/clusterd/network_test.go
> allow public/cluster network config information to be specified to rookd

- pkg/operator/mon/mon.go
- pkg/operator/mon/pod.go
- pkg/operator/osd/osd.go
- pkg/operator/rgw/rgw.go
Rather than passing the secrets in plain text to the pods, the keyrings are stored in k8s secrets. #357
> store mon and rgw secrets

- cmd/rook/object/connection_test.go
- cmd/rook/object/user.go
- pkg/api/object.go
- pkg/rook/client/client.go
- pkg/rook/client/client_test.go
- pkg/rook/client/object.go
- pkg/rook/test/mockclient.go
> cli and api: Fix issues wtih erroring on user create even when it is a success.

- toolbox/Dockerfile
- toolbox/README.md
- toolbox/entrypoint.sh
Any feedback is welcome, especially if the fundamental approach could be improved.
Addresses #343
> Rook toolbox container build and readme instructions

- pkg/api/filesystem_test.go
- pkg/api/object.go
- pkg/api/object_test.go
- pkg/model/object.go
> api: Add sorting of object buckets. Also a fix for something missed in another commit.

- build/release/common.sh
- build/release/containers.sh
- cmd/rook-operator/Dockerfile
> build and publish rook-operator container also

- pkg/api/object_test.go
> api: Fix the second part of the bucket ordering issue

- pkg/operator/cluster.go
- pkg/operator/operator.go
Multiple instances of rook can be supported. The only restriction is that storage devices cannot be used by multiple instances or else they will stomp on each other. Thus, the operator for now will only allow one instance to start with all devices. All others will start as directories.
In the future we could allow the devices to be partitioned by instance.
Fixes #444.
> Allow multiple instances of rook

- demo/kubernetes/rook-client/Dockerfile
- demo/standalone/README.md
- toolbox/Dockerfile
rook-client and toolbox containers have been verified with v0.3.0 release and pushed to quay.io
Addresses #449
> Update readme's and rook-client/toolbox Dockerfile to v0.3.0

- Jenkinsfile
- Makefile
- build/run
- external/CMakeLists.txt
- external/Makefile
- external/ceph-submodule-check
- glide.lock
working on a more permanent fix for this, but for now I'm disabling this check.
> build: speedup jenkins build

- Makefile
- build/makelib/golang.mk
This is to add a new jenkins job to check syntax and style. This would be set to no voting for now until we fix all the errors.
> Adding lint check for syntax and style.

- pkg/operator/cluster.go
- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
- pkg/operator/mon/pod.go
- pkg/operator/mon/pod_test.go
- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
Documentation is also added for TPR settings. Fixes #485
> Allow specifying a host path for the data-dir

- Documentation/k8s-monitoring.md
- Documentation/kubernetes.md
- demo/kubernetes/monitoring/prometheus-service.yaml
- demo/kubernetes/monitoring/prometheus.yaml
- demo/kubernetes/monitoring/service-monitor.yaml
> Guide for setting up monitoring with Prometheus in a Rook cluster

- build/makelib/release.mk
- build/release/release.sh
> build: release script arg fixes

- Documentation/k8s-pre-reqs.md
Adding documentation to setup minikube for rook.
> Adding steps to setup minikube for rook

- build/release/containers.sh
Fixes a security issue in alpine:3.4
> Base rook image off alpine 3.5 image

- cmd/rookd/osd.go
- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
> Store data devices in env var to avoid escaping issues

- cmd/rookd/api.go
- pkg/api/k8s/cluster_handler.go
- pkg/api/k8s/node.go
- pkg/operator/api/api.go
- pkg/operator/api/api_test.go
- pkg/operator/cluster.go
- pkg/operator/cluster/cluster.go
- pkg/operator/cluster/cluster_test.go
- pkg/operator/cluster_test.go
- pkg/operator/k8sutil/k8sutil.go
- pkg/operator/mds/mds.go
- pkg/operator/mds/mds_test.go
- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
- pkg/operator/mon/pod.go
- pkg/operator/mon/pod_test.go
- pkg/operator/operator.go
- pkg/operator/operator_test.go
- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
- pkg/operator/pool.go
- pkg/operator/rgw/rgw.go
- pkg/operator/rgw/rgw_test.go
- pkg/operator/tpr.go
Most of the lines changed are for a refactor of the context. For the change specific to the retry, see the first commit. Fixes #559
> Retry initializing a cluster instead of giving up

- Documentation/README.md
- Documentation/advanced-configuration.md
- README.md
Some of the sections can be removed/shortened later once rook-operator gets functionality added in #471 and #571.
Fixes #558
> Docs: Add Advanced Configuration

- Documentation/advanced-configuration.md
- Documentation/k8s-block.md
- Documentation/kubernetes.md
- Documentation/pool-tpr.md
- demo/kubernetes/rook-cluster.yaml
- demo/kubernetes/rook-pool.yaml
- demo/kubernetes/rook-storageclass.yaml
- pkg/operator/cluster.go
- pkg/operator/pool.go
- pkg/operator/tpr.go
> Rename rookpool and rookcluster to pool and cluster

- build/release/containers.sh
> Remove the rook client from the rook container

- pkg/cephmgr/osd/crushmap.go
- pkg/cephmgr/osd/crushmap_test.go
- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
> Set hostname of osd container to the host's name

- Documentation/k8s-monitoring.md
- demo/kubernetes/monitoring/prometheus.yaml
> Update monitoring walkthrough to use RBAC

- build/release/containers.sh
> Publish the client and toolbox containers

- pkg/operator/tracker.go
> Ensure the cluster channel is closed once

- pkg/operator/pool.go
> Reset the pool tpr watch index on failure

- build/release/release.sh
> build: write version file during promotion too

- Documentation/client.md
- Documentation/k8s-filesystem.md
- Documentation/kubernetes.md
- build/release/containers.sh
- cmd/rook/block/list_test.go
- cmd/rook/block/map.go
- cmd/rook/block/map_test.go
- cmd/rook/block/unmap_test.go
- demo/kubernetes/rook-client.yml
- e2e/framework/manager/rook_test_infra.go
- pkg/util/exec/exec.go
- pkg/util/exec/test/mockexec.go
- pkg/util/sys/device.go
- pkg/util/sys/device_test.go
- pkg/util/sys/kmod.go
- pkg/util/sys/parse.go
- pkg/util/sys/parse_test.go
The Rook client does not require a full distro. It's just a simple rest client tool. The only complication was removing the dependency on bash with pipeline commands. Fixes #654
> Rook client container based on Alpine

- e2e/framework/manager/rook_test_infra.go
Found a bug in in our rook_infra set up. we are using master-latest for rook-cluster, also we might run into cases where we just end up using rookd:master-latest when images are not found instead of aborting the test.
> making sure rook version tags can be found and replaced.

- Documentation/k8s-pre-reqs.md
- Documentation/kubernetes.md
- README.md
- demo/kubernetes/1.5/kube-registry.yaml
- demo/kubernetes/1.5/mysql.yaml
- demo/kubernetes/1.5/rgw-external.yaml
- demo/kubernetes/1.5/rook-client.yml
- demo/kubernetes/1.5/rook-cluster.yaml
- demo/kubernetes/1.5/rook-operator.yaml
- demo/kubernetes/1.5/rook-pool.yaml
- demo/kubernetes/1.5/rook-storageclass.yaml
- demo/kubernetes/1.5/rook-tools.yml
- demo/kubernetes/1.5/wordpress.yaml
- pkg/operator/api/api.go
Rook can run on Kubernetes 1.5 by using the yaml files in the 1.5 folder.
> Support Kubernetes 1.5

- cmd/rook/object/bucket.go
- cmd/rook/object/create.go
- cmd/rook/object/user.go
- pkg/api/object.go
- pkg/api/object_test.go
- pkg/api/routes.go
- pkg/cephmgr/rgw/bucket.go
- pkg/model/object.go
- pkg/rook/client/client.go
- pkg/rook/client/object.go
- pkg/rook/test/mockclient.go
cli: Added a few more bucket ops to the cli
> api: Added more bucket ops to the api

- demo/kubernetes/rook-client.yml
- demo/kubernetes/rook-cluster.yaml
- demo/kubernetes/rook-operator.yaml
- demo/standalone/Vagrantfile
- toolbox/rook-tools.yml
> use v0.4 image tags

- demo/helm/rook-operator/.helmignore
- demo/helm/rook-operator/Chart.yaml
- demo/helm/rook-operator/README.md
- demo/helm/rook-operator/templates/NOTES.txt
- demo/helm/rook-operator/templates/_helpers.tpl
- demo/helm/rook-operator/templates/clusterrole.yaml
- demo/helm/rook-operator/templates/clusterrolebinding.yaml
- demo/helm/rook-operator/templates/deployment.yaml
- demo/helm/rook-operator/templates/serviceaccount.yaml
- demo/helm/rook-operator/values.yaml
This chart launches the Rook operator with options to disable RBAC.
Inspired by the [Prometheus Operator](https://github.com/coreos/prometheus-operator/tree/master/helm/prometheus-operator)
More work to be done with a Cluster chart.
> Initial work on Rook operator Helm Chart

- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
> An unschedulable node will not be scheduled for mons

- glide.lock
- glide.yaml
resolve conflict between client-go dependencies and external-provisioner
Addresses #689
> fix vendor dependencies

- build/release/release.sh
the version file is missing from master release on S3. this fixes that.
> build: publish version file earlier

- PendingReleaseNotes.md
> docs: Draft of v0.5 release notes

- demo/kubernetes/rook-operator.yaml
> operator: consistent app label

- pkg/ceph/osd/daemon.go
- pkg/ceph/osd/daemon_test.go
- pkg/ceph/osd/device.go
- pkg/ceph/osd/device_test.go
> osd: include metadata devices when launching OSD daemon in Kubernetes

- e2e/README.md
- e2e/framework/clients/rest_client.go
- e2e/framework/objects/environment_manifest.go
- e2e/framework/utils/mysql_helper.go
- e2e/scripts/k8sBlockLongHaul.sh
- e2e/tests/baseSetup.go
- e2e/tests/block/create_block_test.go
- e2e/tests/block/k8s/longhaul/basicBlockonghaul_test.go
- e2e/tests/cleanup_test_infra_test.go
> adding long haul test for block .

- Jenkinsfile
> build: fix aws credentials

- glide.lock
- glide.yaml
- pkg/operator/api/api.go
- pkg/operator/api/api_test.go
- pkg/operator/cluster/cluster.go
- pkg/operator/cluster/pool.go
- pkg/operator/cluster/pool_test.go
- pkg/operator/k8sutil/placement.go
- pkg/operator/k8sutil/placement_test.go
- pkg/operator/k8sutil/pod.go
- pkg/operator/kit/client.go
- pkg/operator/kit/resource.go
- pkg/operator/kit/watcher.go
- pkg/operator/mds/mds.go
- pkg/operator/mds/mds_test.go
- pkg/operator/mgr/mgr.go
- pkg/operator/mgr/mgr_test.go
- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
- pkg/operator/mon/spec.go
- pkg/operator/mon/spec_test.go
- pkg/operator/operator.go
- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
- pkg/operator/provisioner.go
- pkg/operator/rgw/rgw.go
- pkg/operator/rgw/rgw_test.go
- pkg/operator/test/client.go
This is needed to make it compatible with k8s 1.8
Fixes https://github.com/rook/rook/issues/784
> Incorporating new Kubernetes API changes

- images/rook/Makefile
> ceph: use libc allocator on non intel platforms

- Jenkinsfile
- tests/scripts/dind-cluster.sh
- tests/scripts/kubeadm-dind.sh
- tests/scripts/makeTestImages.sh
- tests/scripts/minikube.sh
- tests/smoke/block_storage_smoke_test.go
Support running multiple k8s versions
> adding support for running tests on multiple  k8s versions

- tests/README.md
- tests/block/create_block_test.go
- tests/block/k8s/create_block_test.go
- tests/block/k8s/integration/k8sBlockStorageIntegration_test.go
- tests/block/k8s/longhaul/basicBlockonghaul_test.go
- tests/framework/clients/k8s_file_system.go
- tests/framework/clients/rest_client.go
- tests/framework/clients/test_client.go
- tests/framework/installer/install_helper.go
- tests/framework/utils/exec_utils.go
- tests/framework/utils/k8s_helper.go
- tests/framework/utils/k8s_helper_test.go
- tests/scripts/kubeadm-dind.sh
- tests/scripts/minikube.sh
- tests/smoke/block_test.go
- tests/smoke/file_test.go
- tests/smoke/object_test.go
- tests/smoke/smoke_test.go
- tests/smoke/test_helper.go
This integrates new logging and a k8s api client, which formed the basis for writing tests for #806.
> tests: k8s api client and more test logging

- cmd/rook/main.go
- cmd/rook/osd.go
- pkg/ceph/cephmgr.go
- pkg/ceph/leader_test.go
- pkg/ceph/osd/agent.go
- pkg/ceph/osd/agent_test.go
- pkg/ceph/osd/daemon.go
- pkg/ceph/osd/daemon_test.go
- pkg/operator/api/api.go
- pkg/operator/api/api_test.go
- pkg/operator/mds/mds.go
- pkg/operator/mds/mds_test.go
- pkg/operator/mgr/mgr.go
- pkg/operator/mgr/mgr_test.go
- pkg/operator/mon/spec.go
- pkg/operator/mon/spec_test.go
- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
- pkg/operator/rgw/rgw.go
- pkg/operator/rgw/rgw_test.go
Separating out this commit from #806
> services: start daemons with tini at pid 1

- demo/kubernetes/rook-storageclass.yaml
- pkg/operator/provisioner/provisioner.go
Fixes: https://github.com/rook/rook/issues/742
> Adding support for FSType in Rook volume provisioner

- Documentation/advanced-configuration.md
Fixes #801 
Rendered markdown can be previewed here: https://github.com/jbw976/rook/blob/docs-log-collect/Documentation/advanced-configuration.md#log-collection
> docs: add section on collecting all Rook logs

- build/release/Jenkinsfile.promote
- build/release/Jenkinsfile.tag
- build/release/Makefile
add two new jenkins files to tag a release and promote it.
fixes #725 and #548
> wip: build: add support for tagging a release and promoting it from jenkins

- tests/framework/utils/k8s_helper.go
- tests/framework/utils/k8s_helper_test.go
The kube context wasn't being loaded correctly when a certificate was in use
> tests: improve the kube context detection

- tests/scripts/kubeadm-dind.sh
- tests/scripts/minikube.sh
Some simple helpers to update rook and wordpress images in the minikube and kubeadm env
> tests: dev helpers to work with test env

- Documentation/README.md
- Documentation/advanced-configuration.md
- Documentation/client.md
- Documentation/cluster-tpr.md
- Documentation/development-flow.md
- Documentation/k8s-block.md
- Documentation/k8s-filesystem.md
- Documentation/k8s-monitoring.md
- Documentation/k8s-object.md
- Documentation/k8s-pre-reqs.md
- Documentation/kubernetes.md
- Documentation/pool-tpr.md
- Documentation/standalone.md
- Documentation/toolbox.md
- README.md
To avoid complicated PRs just get these changes into master asap.
> add front matter and a fix broken links on docs

- pkg/operator/mon/mon.go
Since the bind_addr change, the startup time of monitors forming quorum is much longer. By starting one monitor at a time, the time is much shorter (~20 seconds instead of a 1-2 minutes)
> operator: start one mon at a time

- Documentation/cluster-crd.md
- cluster/examples/kubernetes/rook-cluster.yaml
- pkg/operator/cluster/controller.go
- pkg/operator/cluster/types.go
- pkg/operator/mgr/mgr.go
- pkg/operator/mgr/mgr_test.go
Placement policy needs to be applied to the mgr daemon. Fixes #890
> mgr: apply placement policy to mgr daemon

- pkg/api/handlers_test.go
- pkg/api/pool.go
- pkg/ceph/client/pool.go
- pkg/ceph/mds/filesystem.go
> ceph: set application tag when creating pool

- build/release/Makefile
(cherry picked from commit ab5d89fff7a2c40aed45f6d0ab6e2fc44249f02d)
> build: fix chart merging

- build/release/Makefile
(cherry picked from commit 2568e8b679c51ab5c1dea49608bb4217f4cb5f52)
> build: fix helm pre-req

- pkg/ceph/collectors/health.go
- pkg/ceph/collectors/health_test.go
- pkg/ceph/collectors/osd.go
Ported from https://github.com/digitalocean/ceph_exporter/pull/66
> metrics: Include number of slow requests

- tests/framework/utils/k8s_helper.go
- tests/smoke/smoke_test.go
> gather rook operator and api logs on test failures.

- design/local-node-agent.md
Rendered markdown can be viewed here for easy reading: https://github.com/jbw976/rook/blob/agent-design/design/local-node-agent.md
> design: proposal for Rook local node agent

- Documentation/advanced-configuration.md
Signed-off-by: Hans van den Bogert <hansbogert@gmail.com>
> doc: refer to CustomResourceDefinition and not TPR

- design/upgrade.md
Easy to read rendered markdown: https://github.com/jbw976/rook/blob/upgrade-design/design/upgrade.md
> design: proposal for automated Rook cluster upgrades

- pkg/ceph/client/pool.go
- pkg/operator/pool/controller.go
- tests/smoke/pool_test.go
Fixes #989
***
This is a quick try to implement pool size changes by K8s CRD updates.
I haven't tested it yet, but will do so when I have the time.
/cc @ftab
> Added ability to update pool size by changing pool crd

- Jenkinsfile
- tests/integration/pool_test.go
Also global parameter issue with new PRs
> move pool resize test from smoke package to integration package.

- tests/scripts/kubeadm.sh
> Adding support for multi node k8s install via kubeadm

- tests/framework/utils/k8s_helper.go
- tests/framework/utils/mysql_helper.go
- tests/longhaul/block_test.go
> fix block longhaul test

- tests/pipeline/Jenkinsfile.k8sSetup
- tests/pipeline/Jenkinsfile.longhaul
- tests/pipeline/Jenkinsfile.regression
- complete regression
- longhaul testing
[skip ci]
fix #695
> create new jenkins pipeline

- design/data-model.md
- design/object-store.md
Also includes an overall Rook data model for reference
[skip ci]
> Design for the object store CRD

- design/filesystem.md
> docs: shared filesystem CRD design

- tests/pipeline/Jenkinsfile.k8sSetup
- tests/pipeline/Jenkinsfile.regression
> fix version wget on PR

- tests/pipeline/Jenkinsfile.k8sSetup
- use test scripts from scm checkout (instead of doing wget on files)
- copy rook test images to all nodes. 
[skip ci]
> update release k8s set up pipeline

- Documentation/kubernetes.md
- cmd/rook/osd.go
- pkg/ceph/cephmgr.go
- pkg/ceph/client/auth.go
- pkg/ceph/client/mon.go
- pkg/ceph/leader_test.go
- pkg/ceph/osd/agent.go
- pkg/ceph/osd/agent_test.go
- pkg/ceph/osd/config.go
- pkg/ceph/osd/daemon.go
- pkg/ceph/osd/daemon_test.go
- pkg/ceph/osd/device.go
- pkg/ceph/osd/device_test.go
- pkg/ceph/osd/filesystem.go
- pkg/ceph/osd/filesystem_test.go
- pkg/ceph/osd/scheme.go
- pkg/ceph/osd/scheme_test.go
- pkg/operator/api/api.go
- pkg/operator/k8sutil/kvstore.go
- pkg/operator/k8sutil/kvstore_test.go
- pkg/operator/k8sutil/rbac.go
- pkg/operator/osd/osd.go
- pkg/util/kvstore/kvstore.go
- pkg/util/kvstore/mockkvstore.go
- tests/framework/installer/install_helper.go
- tests/framework/utils/k8s_helper.go
- tests/integration/helm_test.go
- tests/integration/multi_cluster_deploy_test.go
> osd: Allow OSDs to recover from losing all their metadata and config

- Jenkinsfile
- tests/scripts/kubeadm-install.sh
- tests/scripts/kubeadm.sh
fix #1032 
[skip ci]- just added comment to kubeadm script.
> adding k8s 1.8 to ci pipeline

- PendingReleaseNotes.md
> Update pending release notes for OSD metadata recovery

- cmd/rookflex/cmd/init.go
- pkg/agent/flexvolume/controller_test.go
- pkg/agent/flexvolume/manager/ceph/manager.go
- pkg/agent/flexvolume/manager/ceph/manager_test.go
- pkg/agent/flexvolume/types.go
- pkg/operator/agent/agent.go
- pkg/operator/agent/agent_test.go
- tests/scripts/kubeadm-install.sh
- tests/scripts/kubeadm.sh
- tests/scripts/minikube.sh
Fixes https://github.com/rook/rook/issues/1062
> Executing modprobe in agent pod

- cmd/rookctl/block/list.go
- cmd/rookctl/block/map.go
- cmd/rookctl/block/unmap.go
- pkg/agent/flexvolume/manager/ceph/manager.go
- pkg/ceph/util/util.go
- pkg/ceph/util/util_test.go
- pkg/util/sys/device.go
- pkg/util/sys/device_test.go
Fixes https://github.com/rook/rook/issues/1056
> Moving FindRBDMappedFile to ceph/utils.go

- tests/scripts/kubeadm.sh
fixes https://github.com/rook/rook/issues/1057
> Overriding service via drop-in file instead of sed

- pkg/api/daemon.go
Fixes #990.
This adds a go routine to watch for changes to the configmap and on changes trigger an update to the Ceph config.
There may be race conditions because the config isn't being updated, but this would only happen when the cluster is "damaged" ~= the content of the configmap with the mons changes.
> Rook API service: Keep up with mon changes

- Documentation/upgrade.md
> TPR migration guidelines

- tests/framework/utils/k8s_helper.go
- tests/integration/base_block_test.go
- tests/integration/block_createBlock_k8s_test.go
- tests/longhaul/block_test.go
> adding clean up check to wait until pvc is deleted

- cmd/rookflex/cmd/unmount.go
- pkg/agent/flexvolume/controller.go
- pkg/agent/flexvolume/controller_test.go
Fixes https://github.com/rook/rook/issues/1082
> Allow attach request to proceed when VolumeAttachment is already created for the same pod

- pkg/ceph/osd/agent_test.go
- tests/integration/base_block_test.go
> tests: stabilize check for deleted pool

- tests/framework/installer/install_data.go
- tests/framework/installer/install_helper.go
- tests/integration/base_deploy_test.go
- tests/integration/base_file_test.go
- tests/integration/helm_test.go
- tests/integration/mon_test.go
- tests/integration/multi_cluster_deploy_test.go
- tests/integration/smoke_test.go
- tests/longhaul/block_test.go
> Test suites setup independent namespaces

- Documentation/cluster-crd.md
- Documentation/kubernetes.md
- PendingReleaseNotes.md
- cluster/charts/rook/templates/clusterrole.yaml
- cluster/examples/kubernetes/rook-cluster.yaml
- cluster/examples/kubernetes/rook-operator.yaml
- cmd/rook/osd.go
- pkg/ceph/osd/agent.go
- pkg/ceph/osd/device.go
- pkg/ceph/osd/filesystem.go
- pkg/ceph/osd/scheme.go
- pkg/operator/api/api.go
- pkg/operator/api/api_test.go
- pkg/operator/k8sutil/rbac.go
- pkg/operator/osd/osd.go
- pkg/operator/osd/storage_test.go
- tests/framework/clients/cluster.go
- tests/framework/clients/rest_client.go
- tests/framework/installer/install_data.go
- tests/framework/installer/install_helper.go
- tests/framework/utils/k8s_helper.go
- tests/integration/base_deploy_test.go
- tests/integration/block_createBlock_api_test.go
- tests/integration/block_createBlock_k8s_test.go
- tests/integration/helm_test.go
- tests/integration/multi_cluster_deploy_test.go
- tests/integration/smoke_test.go
- tests/longhaul/block_test.go
> enable bluestore on directories, make bluestore the default OSD backend, test bluestore in integration tests

- tests/framework/installer/install_data.go
- tests/framework/installer/install_helper.go
- tests/framework/objects/environment_manifest.go
- tests/framework/utils/k8s_helper.go
- tests/longhaul/base_block_test.go
- tests/longhaul/block_test.go
- tests/longhaul/block_with_fencing_test.go
- tests/pipeline/Jenkinsfile.longhaul
- tests/pipeline/Jenkinsfile.regression
- mount block volume once
- mount and unmount volumes per test
- run block test with fencing.
> adding new scenarios for block longhaul test

- Documentation/kubernetes.md
Cleanup instructions need to remove all CRDs and TPRs
[skip ci]
> Cleanup all TPRs with cluster removal

- Documentation/advanced-configuration.md
This adds a section about "Phantom OSD Removal" to the "Advanced Cluster Configuration" page.
Fixes #1071 
[skip ci]
/cc @jpds
> Added "Phantom OSD Removal" doc section

- Jenkinsfile
- build/makelib/common.mk
- build/makelib/golang.mk
- images/cross/Dockerfile
> build: upgrade golang to 1.9.1 and fix build issue

- tests/scripts/minikube.sh
> scripts: set default minikube test env to 1.8.0

- Documentation/k8s-pre-reqs.md
> Adding documentation to configure flexvolume in coreos

- tests/framework/installer/test_data.go
- tests/integration/base_block_test.go
- tests/integration/block_createBlock_k8s_test.go
- tests/longhaul/base_block_test.go
- tests/longhaul/block_with_fencing_test.go
> move block test data into common package.

- Jenkinsfile
> wip:fix host name for test log files.

- cmd/rook/main.go
- cmd/rook/mgr.go
- cmd/rook/osd.go
- cmd/rook/rgw.go
- pkg/ceph/mds/daemon.go
- pkg/ceph/mgr/daemon.go
- pkg/ceph/mon/daemon.go
- pkg/ceph/osd/agent.go
- pkg/ceph/osd/agent_test.go
- pkg/ceph/osd/daemon_test.go
- pkg/ceph/osd/filesystem.go
- pkg/ceph/rgw/daemon.go
- pkg/clusterd/context.go
The proc manager has much less footprint since standalone was removed
> Refactor proc manager for only the osd daemon

- Documentation/common-problems.md
[skip ci] OK, here it is. I should have had this done last week, but better late than never, right?  :-)
> First pass at a common problems page

- tests/scripts/minikube.sh
Convenience improvement,  local minikube context will restart Rook pods upon images update.
[skip ci]
> Restart pods for minikube kubectl context

- Documentation/k8s-filesystem.md
- cmd/rookflex/cmd/mount.go
- cmd/rookflex/cmd/root.go
- cmd/rookflex/cmd/unmount.go
- pkg/agent/flexvolume/controller.go
- pkg/agent/flexvolume/controller_test.go
- pkg/agent/flexvolume/types.go
- pkg/operator/mds/mds.go
- tests/integration/base_file_test.go
fixes https://github.com/rook/rook/issues/1008
> Adding support to mount cephfs in rook flexvolume

- pkg/ceph/client/osd.go
- pkg/ceph/osd/daemon.go
- pkg/ceph/osd/health.go
- pkg/ceph/osd/health_test.go
- pkg/util/proc/monitoredproc.go
- pkg/util/proc/procmanager.go
> OSD processes additional monitoring

- tests/pipeline/Jenkinsfile.k8sSetup
- tests/pipeline/Jenkinsfile.longhaul
- tests/pipeline/Jenkinsfile.regression
- tests/scripts/kubeadm.sh
- update default values for load test.
[skip ci]
fix #1160
> kubeadm join update for 1.8

- Documentation/filesystem-crd.md
- Documentation/k8s-block.md
- Documentation/k8s-filesystem.md
- Documentation/k8s-object.md
- Documentation/object-store-crd.md
- Documentation/pool-crd.md
- cluster/examples/kubernetes/1.5/rook-storageclass.yaml
- cluster/examples/kubernetes/rook-filesystem.yaml
- cluster/examples/kubernetes/rook-object.yaml
- cluster/examples/kubernetes/rook-pool.yaml
- cluster/examples/kubernetes/rook-storageclass.yaml
- design/filesystem.md
> set erasureCoded/replicated settings that fit the smallest cluster

- Documentation/client.md
> Replace AWS_ENDPOINT with AWS_HOST to satisfy AWS Signature V4

- pkg/operator/agent/agent.go
Fixes https://github.com/rook/rook/issues/1168
> Removing toleration effect so that rook-agents respect taints on nodes

- Documentation/kubernetes.md
- cluster/charts/rook/templates/deployment.yaml
- cluster/examples/kubernetes/rook-operator.yaml
- pkg/operator/agent/agent.go
- pkg/operator/agent/agent_test.go
- pkg/operator/k8sutil/k8sutil.go
- pkg/operator/k8sutil/rbac.go
- pkg/operator/k8sutil/rbac_test.go
- tests/framework/installer/install_data.go
- tests/framework/installer/install_helper.go
- tests/integration/multi_cluster_deploy_test.go
fixes https://github.com/rook/rook/issues/1041
> Create RBAC roles and service account for agents

- Documentation/kubernetes.md
- cmd/rook/operator.go
- pkg/agent/agent.go
- pkg/agent/cluster/controller.go
- pkg/agent/cluster/controller_test.go
- pkg/agent/flexvolume/controller.go
- pkg/agent/flexvolume/controller_test.go
- pkg/agent/flexvolume/crd/controller_crd.go
- pkg/agent/flexvolume/crd/controller_tpr.go
- pkg/agent/flexvolume/crd/fake.go
- pkg/agent/flexvolume/crd/types.go
- pkg/agent/flexvolume/fake.go
- pkg/agent/flexvolume/manager/ceph/manager.go
- pkg/agent/flexvolume/manager/ceph/manager_test.go
- pkg/agent/flexvolume/manager/fake.go
- pkg/agent/flexvolume/server.go
- pkg/agent/flexvolume/types.go
- pkg/ceph/client/image.go
- pkg/operator/agent/agent.go
- pkg/operator/agent/agent_test.go
- pkg/operator/cluster/controller.go
- pkg/operator/cluster/controller_test.go
- pkg/operator/cluster/register.go
- pkg/operator/operator.go
- pkg/operator/operator_test.go
@kokhang unit test coverage is still coming, but I wanted to get a quick up front glance from you to make sure this wasn't going in a wrong direction.  Thanks!
> clean up outstanding rbd devices during cluster deletion

- tests/framework/utils/k8s_helper.go
- tests/integration/base_block_test.go
Fixes https://github.com/rook/rook/issues/1175
> Check volumeattachment crd in integration tests

- Documentation/cluster-crd.md
- Documentation/kubernetes.md
- design/mon-health.md
A design doc for healthy mon quorum and failover. [skip ci]
> Design for mon failover

- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
operator: for generating osd pod spec, don't mount /dev if it does not need to, and don't run with privileged if it does not need to
When no devices are specified, no need to mount /dev, and don't need to run with privileged.  This allows emptyDir to run in a more restricted environment with least privilege needed.
fixes: #1186, fixes: #400.
> make osd runs with least privilege possible

- images/toolbox/toolbox.sh
> Generate toolbox config for mons with double digit names

- Documentation/k8s-filesystem.md
- PendingReleaseNotes.md
- Added agents updates
- Added flexvolume updates
- Added new filesystem updates
- Added flexvolume known issues
- Added workaround docs for consuming filesystem in old kernels
[skip ci]
> Update pending release notes

- Documentation/cluster-crd.md
- Documentation/helm-operator.md
- Documentation/kubernetes.md
- Documentation/toolbox.md
- cluster/examples/kubernetes/rook-cluster.yaml
- cluster/examples/kubernetes/rook-operator.yaml
- cluster/examples/kubernetes/rook-tools.yaml
> docs: update docs and yaml to v0.6.0

- design/resource-constraints.md
[skip ci]
This adds a design for resource constraints for rook.
Please let me know any feedback, I'll be glad to incorporate it into the design!
/cc @phsiao
> Added resource constraints design

- design/dynamic-provision-filesystem.md
> Design doc for dynamic provisioning filesystem

- cluster/examples/kubernetes/kube-registry.yaml
> Updating kube-registry example

- Documentation/cluster-crd.md
- Documentation/filesystem-crd.md
- Documentation/object-store-crd.md
- cluster/examples/kubernetes/rook-cluster.yaml
- cluster/examples/kubernetes/rook-filesystem.yaml
- cluster/examples/kubernetes/rook-object.yaml
- pkg/operator/api/api.go
- pkg/operator/api/api_test.go
- pkg/operator/cluster/controller.go
- pkg/operator/cluster/types.go
- pkg/operator/k8sutil/resources.go
- pkg/operator/k8sutil/resources_test.go
- pkg/operator/mds/mds.go
- pkg/operator/mds/mds_test.go
- pkg/operator/mds/types.go
- pkg/operator/mgr/mgr.go
- pkg/operator/mgr/mgr_test.go
- pkg/operator/mon/health_test.go
- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
- pkg/operator/mon/spec.go
- pkg/operator/mon/spec_test.go
- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
- pkg/operator/osd/spec.go
- pkg/operator/osd/spec_test.go
- pkg/operator/rgw/rgw.go
- pkg/operator/rgw/rgw_test.go
- pkg/operator/rgw/types.go
This is the "first" part of the resource constraints design implementation, user defined requests/limits for rook.
***
Currently untested and still WIP as I'm not done completely yet, but I'd like  want to get any feedback in as early as possible on the current changes.
**ToDo**:
> Added v1.ResourceRequirements to Cluster Spec

- Jenkinsfile
> send build notifications to slack

- tests/framework/clients/object.go
- tests/framework/contracts/operations.go
- tests/framework/objects/environment_manifest.go
- tests/framework/utils/s3_operations.go
- tests/integration/base_object_test.go
- tests/longhaul/base_block_test.go
- tests/longhaul/base_object_test.go
- tests/longhaul/block_test.go
- tests/longhaul/object_test.go
- tests/pipeline/Jenkinsfile.longhaul
> adding long haul test for object store.

- images/rook/Dockerfile.base
- pkg/operator/agent/agent.go
- pkg/operator/agent/agent_test.go
Fixes https://github.com/rook/rook/issues/1239
> Use modprobe and modinfo from the container

- build/makelib/common.mk
- images/image.mk
> use BSD / GNU agnotic sed params

- pkg/operator/k8sutil/rbac.go
> Fix argument parameter match

- pkg/ceph/osd/device.go
> Set bluestoreDirBlockSizeRatio to 1.0

- pkg/operator/agent/agent.go
- pkg/operator/agent/types.go
- tests/framework/clients/rest_client.go
- tests/integration/smoke_test.go
- tests/scripts/kubeadm.sh
> Get flexvolume plugin dir for all k8s versions

- images/toolbox/toolbox.sh
Fixes #1267
***
This adds the fallback for the toolbox to the DNS service name when the service env vars are not set which most likely means that the `hostNetwork: true` is used.
> toolbox: Fallback to rook-api dns name when service env vars are not set

- Documentation/client.md
(cherry picked from commit 825cc5b4706c09bf57dad1cc56ebd231acc8cee4)
[skip ci]
> Backport to 0.6.1: add replica count param to client walkthrough

- pkg/ceph/rgw/objectstore.go
- pkg/ceph/rgw/objectstore_test.go
(cherry picked from commit e7bd52a19935ea76f190c2a2e5e35eab03768e12)
> Backport to 0.6.1: skip deleting root pool when there are multiple object stores

- Documentation/cluster-crd.md
- cluster/examples/kubernetes/rook-cluster.yaml
- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
- pkg/operator/osd/spec.go
- pkg/operator/osd/spec_test.go
- pkg/operator/osd/storage.go
- pkg/operator/osd/storage_test.go
See https://github.com/rook/rook/issues/1256.
> Add cluster wide directories path

- MAINTAINERS
> update maintainer email

- pkg/agent/flexvolume/controller.go
- pkg/agent/flexvolume/controller_test.go
There is a case where a pod is trying to request a volume
attachment after the previous attachment failed. However even though this is
the same pod as the original attachment request, its UID could be different. This is normally caused when
the user manually deletes the pod and recreate it again. The name will be the same but the ID will be different
fixes https://github.com/rook/rook/issues/1214
> Ensuring volume lock is released when the same pod is requesting it

- Documentation/cluster-crd.md
- Documentation/helm-operator.md
- Documentation/kubernetes.md
- Documentation/toolbox.md
- cluster/examples/kubernetes/rook-cluster.yaml
- cluster/examples/kubernetes/rook-operator.yaml
- cluster/examples/kubernetes/rook-tools.yaml
> docs: update docs/yaml to v0.6.1

- cluster/charts/rook/templates/deployment.yaml
- cluster/examples/kubernetes/rook-operator.yaml
- pkg/operator/k8sutil/rbac.go
- pkg/operator/k8sutil/rbac_test.go
Fixes https://github.com/rook/rook/issues/1221
> Not create rbac roles on k8s cluster that have rbac disabled.

- cluster/charts/rook/templates/deployment.yaml
- cluster/charts/rook/values.yaml.tmpl
- cluster/examples/kubernetes/rook-operator.yaml
- pkg/operator/agent/agent.go
- pkg/operator/agent/agent_test.go
Fixes https://github.com/rook/rook/issues/1295
> Add toleration for agent daemonset

- Documentation/cluster-crd.md
- Documentation/helm-operator.md
- Documentation/kubernetes.md
- Documentation/toolbox.md
- cluster/examples/kubernetes/rook-cluster.yaml
- cluster/examples/kubernetes/rook-operator.yaml
- cluster/examples/kubernetes/rook-tools.yaml
> docs: update docs/yaml to v0.6.2

- Jenkinsfile
- tests/scripts/kubeadm-install.sh
- tests/scripts/kubeadm.sh
running integratin test on earliest and latest versions for k8s 1.6,1.7 and 1.8
fix #1227
> update ci env

- design/cluster-update.md
Fixes #1247 
Note that there are a couple TODO's called out, feedback welcome.
[skip ci]
> design: proposal for supporting Cluster CRD updates

- Documentation/development-flow.md
> docs: steps for backporting fixes to release branches

- pkg/operator/cluster/osd/osd.go
- pkg/operator/cluster/osd/osd_test.go
Fixes #1293
***
/cc @dgonzalezruiz
> op/osd: Replace directories usages with selection.directories

- pkg/daemon/ceph/client/erasure-code-profile.go
- pkg/daemon/ceph/rgw/objectstore.go
- pkg/daemon/ceph/rgw/objectstore_test.go
Fixes https://github.com/rook/rook/issues/1332
> Deleting erasure code profile when deleting object store

- images/ceph/build-ceph.sh
> Add condition for nproc when one CPU is available for Ceph build

- Jenkinsfile
- tests/framework/installer/test_data.go
- tests/framework/utils/k8s_helper.go
- tests/integration/base_block_test.go
- tests/integration/block_createBlock_k8s_test.go
- tests/integration/block_mount_unmount_test.go
- tests/integration/helm_test.go
- tests/integration/multi_cluster_deploy_test.go
- tests/longhaul/block_with_fencing_test.go
- tests creating pvcs with various AccessModes
- Mounting and unmounting PVCs with various AccessModes
- Scaling up PVCs via stateful sets
fix # 1217
> adding additional tests for block storage

- Jenkinsfile
- tests/integration/smoke_test.go
- add k8s 1.9 to CI pipeline
Resolves #1323
> Add k8s 1.9 to build pipeline

- tests/scripts/minikube.sh
- Bump default version to current stable version of 1.9.1
- Expose memory as env variable
[skip ci]
> Use kubeadm bootstrapper for minikube

- Documentation/common-problems.md
A common issue reported by users is that only a single mon starts instead of three. This adds a new section for troubleshooting the issue with the single mon.
[skip ci]
> Troubleshooting doc for single mon pod health

- README.md
> Add FOSSA status badge

- images/base/Dockerfile
- images/base/Makefile
Closes: https://github.com/rook/rook/issues/1314
> Images: Upgrade tini

- README.md
https://www.cncf.io/blog/2018/01/29/cncf-host-rook-project-cloud-native-storage-capabilities/
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
> Add CNCF project reference

- Documentation/k8s-pre-reqs.md
Signed-off-by: 陈宏 <chenhong@ghostcloud.cn>
privilege misspelled
[skip ci]
> priviledge should be a privilege

- CONTRIBUTING.md
> update dco info in contributing.md

- pkg/operator/provisioner/controller/controller.go
Signed-off-by: Omri Shiv <omri.shiv@teradata.com>
Fixing typo in controller.go
Resolves #
Checklist:
> Fixing typo

- pkg/operator/file/ceph/mds.go
...of things that appear to be unused.
> Couple of miscellaneous cleanups

- MAINTAINERS
Description of your changes:  Update the email addresses in the maintainers list
[skip ci]
> update email in maintainers list

- Documentation/common-problems.md
Undrained nodes will hang forever on `reboot` since RBD wasn't unmounted, at least this needs to be documented.
[skip ci]
> Document problem with node reboot without drain

- Documentation/development-environment.md
- Documentation/development-flow.md
- tests/scripts/multi-node/build-rook.sh
- tests/scripts/multi-node/config.rb
- tests/scripts/multi-node/rpm-system-prerequisites.sh
This commit adds instructions to develop on a multi-node deployment,
which is somehow similar to a production setup.
It also proposes a development workflow approach to write/build/test/ship
code to Rook.
Resolves #
Checklist:
[skip ci]
> doc: add doc for multi-node setup and dev workflow

- PendingReleaseNotes.md
Description of your changes:  Clear the pending release notes now that v0.7.0 has been released.
Checklist:
[skip ci]
> docs: clear pending release notes

- Documentation/helm-operator.md
- Documentation/toolbox.md
- cluster/examples/kubernetes/rook-operator.yaml
- cluster/examples/kubernetes/rook-tools.yaml
Description of your changes:  Update the tags in our example yaml and docs to point to v0.7.0 image.  This is only for the release-0.7 branch.
Checklist:
[skip ci]
> docs: update docs/yaml to v0.7.0 tags

- Documentation/upgrade.md
The upgrade docs now support the upgrade from v0.6.2 to v0.7. There have been changes to the api and osd pod specs that needed to be added to the upgrade. 
Resolves #1446
[skip ci]
> Support upgrade from 0.6.2 to 0.7.0

- Documentation/upgrade.md
Signed-off-by: Travis Nielsen <travisn@live.com>
(cherry picked from commit 19cec0ec46713cf8529e079085135c7df7ff5a6b)
[skip ci]
> backport: support upgrade from 0.6.2 to 0.7.0

- README.md
Details about the community meeting along with helpful links
[skip ci]
> updated readme with community meeting info

- build/makelib/helm.mk
- build/release/Makefile
Backport changes to 0.7 release
Resolves #1517
Checklist:
> build: use new S3 buckets

- MAINTAINERS
> Update the maintainers email

- ROADMAP.md
Description of your changes:  Update the Rook Roadmap as per community discussion
Checklist:
[skip ci]
> Update Rook roadmap

- Documentation/development-environment.md
- tests/scripts/multi-node/build-rook.sh
Fix some small bugs/clarify the recently-added multi-node development support workflow
Resolves #1520
Checklist:
[skip ci]
> Improvements to multi-node development 

- Documentation/helm-operator.md
- Documentation/toolbox.md
- Documentation/upgrade.md
- cluster/examples/kubernetes/rook-operator.yaml
- cluster/examples/kubernetes/rook-tools.yaml
Description of your changes:  Update the docs and yaml references to v0.7.1, the latest minor version
Checklist:
[skip ci]
> docs: update docs/yaml to use v0.7.1

- pkg/operator/cluster/controller.go
The stopCh value was only present in struct cluster, whose instance was
local to the onAdd function; save it to ClusterController.
Second, it was not initialized.
Third, ClusterController's "devicesInUse" needs to be set false on
cluster delete.
With this fix, Ceph clusters can be deleted and recreated without
restarting the Rook operator.
Signed-off-by: Dan Mick <dan.mick@redhat.com>
Resolves #
Checklist:
> Properly terminate controller threads on cluster delete

- cluster/charts/rook/templates/wait-on-resources-job.yaml
Description of your changes: Backport https://github.com/rook/rook/commit/bdf42283eb331eb97df11ad76b1d55468e2da4ad to 0.7 release branch
Resolves #1567
> Check for supporting API instead of specific K8S version

- README.md
Description of your changes: Update community meeting schedule to every other Tuesday
[skip ci]
> docs: Update community meeting schedule to every other Tuesday

- Documentation/development-environment.md
Signed-off-by: Dan Mick <dan.mick@redhat.com>
Resolves #
Checklist:
[skip ci]
> Add note about how to enable access to Dashboard

- Documentation/development-flow.md
Description of your changes: This addition to the contribution flow clarifies about when design documents should be used, why they should be used, as well as the process around authoring one.
[skip ci]
> docs: update contribution flow to clarify design document process

- images/cross/Dockerfile
Update golang to 1.10.1
none.
Checklist:
> build: upgrade to golang 1.10.1

- design/multiple-storage-types-support.md
Description of your changes:  Design document for Rook support of multiple storage types
Resolves #1375 
Checklist:
[skip ci]
> design: multiple storage types support

- design/dedicated-osd-pod.md
Design proposal to fix https://github.com/rook/rook/issues/1341
Resolves #1341 
Checklist:
[skip ci]
> design: one dedicated pod per osd

- Documentation/pool-crd.md
Documentation for erasure coding to help answer common questions about how to make decisions on data and coding chunks.
Checklist:
[skip ci]
> docs: erasure coding chunks explained

- Documentation/helm-operator.md
Signed-off-by: Brett Jacobson <brett.jacobson42@gmail.com>
Update the helm operator docs to specify rook-system as the namespace.
Resolves #1608 
Checklist:
[x] Documentation has been updated, if necessary.
[ ] Pending release notes updated with breaking and/or notable changes, if necessary.
[skip ci]
> updated doc to specify namespace on helm install

- Documentation/helm-operator.md
- cluster/charts/rook/values.yaml.tmpl
Resolves #1648
Checklist:
- [x ] Documentation has been updated, if necessary.
[skip ci]
> Update rook helm charts documentation

- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
- pkg/daemon/ceph/rgw/objectstore.go
Signed-off-by: Tony Allen <tony@upbound.io>
This patch enables EC overwrite for all created EC pools. Since EC overwrite is unnecessary for object stores, the feature is disabled for the data pools backing object storage. 
Resolves #1129 
Checklist:
> Enable EC overwrite for RBD and filesystem.

- Documentation/container-linux.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/coreos/ceph-after-reboot-script.yaml
- cluster/examples/coreos/ceph-before-reboot-script.yaml
- cluster/examples/coreos/rbac.yaml
Signed-off-by: hacor <hacornelis@gmail.com>
This page should be the final version of PR #1492 
[skip ci]
> Added ceph-reboot-script using the Container Linux Update Operator

- Documentation/monitoring.md
Added links to my Grafana Ceph dashboards to the documentation.
Checklist:
[skip ci]
> docs: Added links to my Grafana Ceph dashboards

- README.md
Add docker pull badge to README
Checklist:
[skip ci]
> add docker pull badge to readme

- Documentation/k8s-pre-reqs.md
> Fix link to kubeadm install page

- Documentation/common-issues.md
* Adds common issue section for `modprobe exec format error`, see #1542.
* Adds common issue section for multiple filesystem mount issues with old kernel
Resolves #1542
Checklist:
[skip ci]
> Add two common issues to the docs

- Documentation/development-environment.md
options collide with jekyll markup
Signed-off-by: Yehuda Sadeh <yehuda@redhat.com>
[skip ci]
> docs: escape docker options

- .github/PULL_REQUEST_TEMPLATE.md
Add a checklist item to PRs to request that upgrade from the previous release is tested and documented when necessary.
[skip ci]
> Upgrade should be tested and documented if necessary

- Documentation/quickstart.md
This adds the Slack inviter link to the quickstart guide.
Closes #1709.
Checklist:
[skip ci]
> Add Slack inviter link to quickstart

- pkg/operator/ceph/cluster/mon/util.go
- pkg/util/sys/device.go
- pkg/util/sys/device_test.go
- pkg/util/sys/parse.go
- pkg/util/sys/parse_test.go
- tests/framework/utils/helm_helper.go
Signed-off-by: Aayush Sarva <checkaayush@gmail.com>
Description of your changes: Replaced custom Awk function with `strings.Fields` and removed related tests along with some obsolete functions. 
Resolves #1700 
Checklist:
> Replace custom Awk and remove related tests

- Gopkg.lock
Description of your changes: Update the Gopkg.lock file for new k8s.io/api/apps/v1beta2 import.  Full analysis and details can be found in https://github.com/rook/rook/issues/1808#issuecomment-399698086.
Resolves #1808 
Checklist:
> build: update Gopkg.lock for new k8s.io/api/apps/v1beta2 import

- Documentation/block.md
supersedes #1619 
Resolves #
Checklist:
[skip ci]
> add clusterNamespace and associated comment to explain its necessity

- Gopkg.lock
Of all the items in the checklist for #1698, running `make vendor` was missed, resulting in a dirty master build.
**Checklist:**
> Update the go dependencies

- pkg/operator/ceph/cluster/osd/remove.go
This checks if the initial PG count is zero and if so skips the loop which would normally timeout due to the initial and current PG count not decreasing.
I haven't tested the fix but as far as I understand the logic this should work.
Maybe @dimm0 can try to reproduce as he first mentioned it.
Resolves #1708.
Checklist:
> osd: skip wait loop when initial PGs is 0

- build/release/README.md
**Description of your changes:** This change documents a set of release criteria and checklist by which a new release is approved.
Resolves #1846 
**Checklist:**
[skip ci]
> Define release criteria and checklist

- Documentation/README.md
- Documentation/advanced-configuration.md
- Documentation/block.md
- Documentation/ceph-cluster-crd.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-teardown.md
- Documentation/cockroachdb.md
- Documentation/common-issues.md
- Documentation/crds.md
- Documentation/development-flow.md
- Documentation/direct-tools.md
- Documentation/disaster-recovery.md
- Documentation/filesystem.md
- Documentation/helm-operator.md
- Documentation/k8s-pre-reqs.md
- Documentation/minio-object-store.md
- Documentation/object.md
- Documentation/quickstart-toc.md
- Documentation/storage.md
- Documentation/tectonic.md
- Documentation/toolbox.md
- Documentation/upgrade.md
- A number of small updates to the docs discovered while testing for the 0.8 release. 
- Moved quickstart guides for each storage provider under the Quickstart TOC
- Added troubleshooting topic for OSD creation
- Helm chart mentions the beta release, pending the 0.8 release
Resolves #1877
**Checklist:**
[skip ci]
> Doc clarifications for the 0.8 release

- cluster/examples/kubernetes/ceph/cluster.yaml
Fix a typo in the example documentation for setting up a cluster
None
**Checklist:**
[skip ci]
> Fix typo in Cluster Example

- Documentation/helm-operator.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml.tmpl
Add tolerations for the operator pods to allow them to be scheduled on nodes with taints set.
Resolves #1893 
**Checklist:**
> Add tolerations to Helm chart

- Documentation/upgrade.md
- PendingReleaseNotes.md
**Description of your changes:** clear pending release notes and update upgrade guide to 0.8
**Checklist:**
[skip ci]
> docs: clear pending release notes and update upgrade guide to 0.8

- build/codegen/codegen.sh
It must be a tab and not spaces.. which I accidentally broke some time ago.
**Checklist:**
[skip ci]
> Fix codegen script replace

- pkg/operator/ceph/cluster/osd/pod.go
Backport of PR #1926.
Resolves #1920.
**Checklist:**
> operator/osd: Use UpdateStrategy Recreate

- ADOPTERS.md
**Description of your changes:** Added a list of Rook adopters to keep track of production users of Rook.  This list will be used in the proposal to the CNCF to graduate Rook to the incubating stage.
**Checklist:**
[skip ci]
> Added list of Rook adopters

- Documentation/flexvolume.md
- Documentation/helm-operator.md
- cluster/charts/rook-ceph/values.yaml.tmpl
Improve flexvolume docs with better structure
Added OpenShift and Atomic flexvolume info
Relates #1790.
**Checklist:**
[skip ci]
> Improve flexvolume docs with better structure

- Documentation/flexvolume.md
- Documentation/helm-operator.md
- cluster/charts/rook-ceph/values.yaml.tmpl
See #1958
Relates #1958
**Checklist:**
[skip ci]
> Backport: #1958 "Improve flexvolume docs with better structure"

- Documentation/helm-operator.md
- Documentation/toolbox.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
**Description of your changes:** . Updates the doc and examples to use the v0.8.1 tag.
**Checklist:**
[skip ci]
> docs: update docs and examples for v0.8.1

- ROADMAP.md
**Description of your changes:** This PR updates the Rook roadmap for v0.9 and future milestones
**Checklist:**
[skip ci]
> update roadmap for v0.9+

- Documentation/direct-tools.md
- Documentation/toolbox.md
- cluster/examples/kubernetes/ceph/toolbox.yaml
Signed-off-by: Bogdan Luca <luca.bogdan@gmail.com>
Resolves #2021 
**Checklist:**
[skip ci]
> [docs] Set "hostNetwork: true" for toolbox

- Documentation/common-issues.md
This PR is a follow-up of the PR #1947, we need to update the common issue to include this new reason for the Agent deployment to fail.
Update the `common-issues.md` document to match the code change accordingly.
Resolves #
**Checklist:**
[skip ci]
> Update the common-issue documentation

- Documentation/ceph-quickstart.md
- Documentation/helm-operator.md
- Documentation/k8s-pre-reqs.md
- Documentation/upgrade.md
- Jenkinsfile
- PendingReleaseNotes.md
- tests/README.md
- tests/scripts/kubeadm-install.sh
- tests/scripts/kubeadm.sh
- tests/scripts/minikube.sh
Update k8s minimum supported version from 1.7 to 1.8. As a result, we drop the integration tests for k8s version 1.7 for upcoming 0.9 release.
Resolves #2040 
**Checklist:**
[skip ci]
> Update K8s minimum version supported by Rook from 1.7 to 1.8

- ADOPTERS.md
"On-premises" is what was meant.
Fix a typo: "on-premise" -> "on-premises"
Resolves NA
**Checklist:**
- [ NA] Documentation has been updated, if necessary.
- [ NA] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ NA] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ NA] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ NA ] `make vendor` does not cause changes.
- [ NA ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)
[skip ci]
> Fix typo in adopters.md

- build/makelib/golang.mk
- images/cross/Dockerfile
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/provisioner/controller/controller.go
- pkg/operator/ceph/provisioner/controller/controller_test.go
- pkg/operator/ceph/provisioner/provisioner_test.go
- pkg/operator/cockroachdb/controller.go
- pkg/util/proc/monitoredproc.go
Changes to support golang 1.11
Resolves # NA
> golang 1.11 support

- pkg/operator/ceph/cluster/osd/status.go
backporting 9ec37d5c00e8733a8e13da59068f5a812476a758
Resolves #
**Checklist:**
> Backport: Reset resource version if watch channel closed

- Documentation/helm-operator.md
- Documentation/toolbox.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
Updates the doc and examples to use the v0.8.2 tag.
**Checklist:**
[skip ci]
> Update docs and examples for v0.8.2

- design/ceph-csi-driver.md
Ceph CSI driver support rook
Resolves #
**Checklist:**
@travisn @BlaineEXE @ganeshmaharaj @gman0 @mkimuram
[skip ci]
> add ceph csi driver proposal

- Documentation/cockroachdb-cluster-crd.md
> docs: fix typo

- design/dynamic-provision-filesystem.md
Fixes invalid claim name
Resolves #
**Checklist:**
[skip ci]
> Fix invalid claim name

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/discover/discover.go
- pkg/operator/k8sutil/node.go
- tests/framework/installer/ceph_installer.go
- tests/framework/utils/k8s_helper.go
Resolves #2148 
**Checklist:**
Skipping the CI after too many random CI failures...
[skip ci]
> ceph: Update operator to use node hostname rather than name-name.

- README.md
Update README to reflect CNCF incubator status.
Resolves #2178 
**Checklist:**
[skip ci]
> update CNCF level in README

- Jenkinsfile
- tests/scripts/kubeadm.sh
Made sure all integration tests works on k8s 1.12
(Ran tests with kubeadm on ubuntu)
Resolves #2168 
**Checklist:**
[skip ci]
> Add Kubernetes 1.12 to Jenkins tests

- images/ceph/Dockerfile
- images/cockroachdb/Dockerfile
- images/cross/Dockerfile
- images/minio/Dockerfile
- images/nfs/Dockerfile
use "COPY" instead of "ADD" in Dockerfile to adopt docker best practice
Resolves #2155 
**Checklist:**
> use "COPY" instead of "ADD" in Dockerfile

- pkg/daemon/ceph/agent/agent.go
- pkg/daemon/ceph/agent/flexvolume/server.go
Due to a timing issue loading flex drivers since 1.11 (see https://github.com/kubernetes/kubernetes/issues/60694), the workaround is to periodically touch the flex drivers to make sure they're loaded. #2089 helped with this issue, but was not sufficient. This fix should help us last until we transition to csi.
Resolves #1501
**Checklist:**
added skip ci to merge after a simple update to the PR and a random failure hit...
[skip ci]
> Periodically refresh the flex drivers

- pkg/operator/nfs/controller.go
- pkg/operator/nfs/controller_test.go
adding validation of NFSServerSpec in accordance
with issues #2036 and #2037
Signed-off-by: tsullens <tsullens@mix.wvu.edu>
Added validation functions for the `exports.server.accessMode` and `exports.server.squash` NFS CRD Parameters as outlined [here](https://github.com/rook/rook/blob/master/design/nfs.md#nfs-crd).
Resolves #2036, #2037 
**Checklist:**
[skip ci]
> nfs: update operator for spec validation

- Documentation/development-flow.md
This PR adds source code layout to the development-flow doc.
Resolves #
**Checklist:**
[skip ci]
> Added source code layout to development-flow doc

- design/object-store.md
Signed-off-by: Enming.Zhang <zvampirem77@gmail.com>
Fix a minor typo in design/object-store.md
**Checklist:**
[skip ci]
> doc: fix a minor typo in design/object-store.md

- pkg/daemon/ceph/client/status.go
- pkg/daemon/ceph/client/status_test.go
The Ceph cluster should be considered clean for orchestration if the PGs are in the following states:
- `active+clean`
- `active+clean+scrubbing`
- `active+clean+scrubbing+deep`
Resolves #2240
**Checklist:**
> Cluster is clean if PGs are scrubbing

- Documentation/advanced-configuration.md
With this documentation enhancement, it is possible to apply a custom config override like [this](https://github.com/rook/rook/issues/1523#issuecomment-379799224) to allow a dedicated network for the OSDs to use for communication
Signed-off-by: Jeff Billimek <jeff@billimek.com>
**Description of your changes:** This is a documentation PR, instructing how to apply a custom config override like [this](https://github.com/rook/rook/issues/1523#issuecomment-379799224) to allow a dedicated network for the OSDs to use for communication.
Resolves #1523
**Checklist:**
[skip ci]
> Allow OSDs to use a dedicated network

- cmd/rook/ceph/osd.go
> Ceph osd: terminate fatal on pod init failures

- tests/integration/upgrade_test.go
The upgrade from 0.8 requires a new privilege to read pod logs, which was required for detecting the version of the ceph container when the version was decoupled. The upgrade test has actually been broken since then, although not reported in the integration tests. In addition to adding this new privilege to the integration test, the integration test now actually verifies the pods are started instead of just timing out. 
@BlaineEXE this is also a step we will need in the upgrade guide. Either we need to instruct them to add the `pod/log` privilege to the `rook-ceph-cluster-mgmt` ClusterRole as seen [here](https://github.com/rook/rook/commit/b2a0dc77fa63610881f84c4b9b5a7d9f4ed3f817#diff-86424e092115d22f58b9822e799d …
> Upgrade adds log access to cluster role

- README.md
Update the rook slackin link to `slack.rook.io`
Resolves #
**Checklist:**
[skip ci]
> update slackin link

- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/mon/mon.go
In order to have Ceph updates working for Rook release v0.9, apply a
simple, temporary solution to update the mons without extraneous mon
updates.
Temp solution for #2331 
**Checklist:**
> Ceph mon: temp change to support #2331 in v0.9

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/util.go
- pkg/operator/ceph/file/spec.go
- pkg/operator/ceph/object/spec.go
* mon: get port from endpoint
* mgr: use Recreate update strategy
Resolves #2345
**Checklist:**
// flaky build
[skip ci]
> Fix issues with mons and mgr when using hostnetwork

- Documentation/ceph-quickstart.md
As discussed on Slack w/ @galexrt .
Resolves #
**Checklist:**
[skip ci]
> ceph quickstart cluster.yaml fixed

- Documentation/ceph-quickstart.md
Signed-off-by: Olaf Klischat <o.klischat@syseleven.de>
Backport of https://github.com/rook/rook/pull/2362 to release-0.9
Resolves #
**Checklist:**
[skip ci]
> backport: ceph quickstart cluster.yaml fixed

- Documentation/ceph-upgrade.md
Signed-off-by: Jessynt <xr5299@gmail.com>
add missed namespace
**Checklist:**
> doc: add missed namespace

- Documentation/README.md
- Documentation/edgefs-cluster-crd.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-quickstart.md
- Documentation/edgefs-storage.md
- README.md
Signed-off-by: Dmitry Yusupov <dmitry@nexenta.com>
Resolves #2351 
**Checklist:**
[skip ci]
> EdgeFS documentation needs more love

- tests/scripts/helm.sh
Signed-off-by: Farhaan Bukhsh <farhaan.bukhsh@gmail.com>
[skip ci]
> Fix the typo in helm.sh

- Documentation/k8s-pre-reqs.md
Change links from relative to absolute so they work from both GitHub and rook.io. See example broken links at :
https://rook.io/docs/rook/v0.9/k8s-pre-reqs.html
> Fix links so they work from rook.io

- pkg/operator/edgefs/cluster/target/config/config.go
- pkg/operator/edgefs/cluster/target/configmap.go
- pkg/operator/edgefs/cluster/target/target.go
(cherry picked from commit 4f0f902daffb74f596f8996c1db3524924a04a13)
Resolves #
**Checklist:**
> Backport: Wrong condition in devices discovery

- Documentation/helm-operator.md
**Description of your changes:** Backport of #2418 (https://github.com/rook/rook/commit/30f5283a72811cfa7eda8e486a7b658e454af567)
Resolves #2340 for 0.9
**Checklist:**
[skip ci]
> docs: add stable channel to rook ceph helm chart docs

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/helm-operator.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
Update the release version in the sample manifests to `v0.9.1`. To be merged immediately before release.
**Checklist:**
[skip ci]
> Set the image tag to v0.9.1

- Documentation/ceph-monitoring.md
- Documentation/common-issues.md
- Documentation/quickstart-toc.md
- README.md
Fix a set of old links to slacking.
Resolves #
**Checklist:**
[skip ci]
> fix slack links

- Documentation/ceph-monitoring.md
- Documentation/common-issues.md
- Documentation/quickstart-toc.md
- README.md
Backport of slack link fix.
Resolves #
**Checklist:**
[skip ci]
> backport: fix slack links

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-upgrade.md
Added missing mon section (and also added dashboard and/or network sections) to the documented examples.
Resolves #2405.
**Checklist:**
[skip ci]
> Added missing mon section to documented examples

- Documentation/cassandra-cluster-crd.md
- Documentation/cassandra.md
Minor changes in docs.
Resolves #2452 
**Checklist:**
[skip ci]
> cassandra: minor documentation fixes

- PendingReleaseNotes.md
- pkg/operator/minio/controller.go
- pkg/operator/minio/controller_test.go
- pkg/operator/minio/operator.go
* Renamed MinioController to Controller as the package is named minio
* Update Minio Object Store objects if they already exist.
* Added readiness and liveness probes to Minio StatefulSet.
Resolves #
**Checklist:**
> Improve Minio operator

- pkg/daemon/ceph/agent/flexvolume/controller.go
Currently the "secretKey" to be used for mounting was not correctly set in the flexvolume code, this corrects this bug and correctly assigns it.
**Checklist:**
> Correctly set secretkey from mountSecretKey param

- pkg/operator/k8sutil/deployment.go
- pkg/operator/k8sutil/pod.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v0.9.go
- tests/framework/installer/installer.go
- tests/integration/base_deploy_test.go
- tests/integration/upgrade_test.go
The upgrade test should test the most recent release to the master build. This will ensure that the last release can be upgraded to the new release when the time comes to release. The current master tests become the v0.9 tests as the v0.8 tests are no longer necessary. 
**Checklist:**
> Upgrade test is from v0.9 to master

- Documentation/README.md
Resolves #
**Checklist:**
[skip ci]
> Update ceph status to Stable

- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/operator.yaml
- cmd/rookflex/cmd/init.go
- pkg/operator/ceph/agent/agent.go
- pkg/operator/ceph/agent/agent_test.go
This is a backport for allowing disabling of recursive fsgroup
Resolves: #2254
**Checklist:**
// random failure
[skip ci]
> Backport: Allow disabling fsgroup

- pkg/util/exec/exec.go
The io.MultiReader(r1, r2) reads r1 until EOF before moving on to r2.
When used for stdout/stderr stderr will not be written to the log until
stdout reaches EOF. This patch reads stderr in a go routine so that the
two streams can be interleaved properly.
Fixes: #2479
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
(cherry picked from commit fbb56c41ed2c89e5fdc7178ea55e7c27ae1daff2)
> Backport: interleave stdout/stderr logging

- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/mon/spec_test.go
Given that we have mon_host and mon_initial_members sections in our
ceph.conf, building a monitor map is not needed. During the monitor mkfs
a monmap will get generated on the fly based on the section mentioned
above.
One benefit from that commit is a potential speed improvement as we have
removed the container that was generating the map from the monitor
initialization sequence.
Resolves: https://github.com/rook/rook/issues/2576
> mon: do not generate nor inject a monmap

- pkg/operator/edgefs/cluster/target/layout.go
Signed-off-by: Anton Skriptsov <anton.skriptsov@nexenta.com>
Disks selection logic has been fixed
Resolves #2563
**Checklist:**
> EdgeFS dynamic HDD/SSD detection logic fix

- ROADMAP.md
Since the release of 0.9, this is a draft of what we hope to deliver in the next release and beyond. Issues without an owner are at risk of being moved to a future milestone. Given that we have discussed a quarterly time-based release starting at the end of March, if a feature doesn't make it in that timeframe, by default it would move to the next release.
More details are needed in the future roadmap beyond 1.0. That section is a very rough draft.
[skip ci]
**Checklist:**
> Update the roadmap for the 1.0 milestone

- pkg/operator/ceph/cluster/osd/spec.go
The default test cluster.yaml specifies a directory which is the same as the dataDirHostPath. This fails when creating the osd provisioning pod spec when the volume mount gets added twice, once for the dataDirHostPath and then again for the directory-based osd.
Resolves #2619 
**Checklist:**
> Avoid a duplicate volume for the default test directory

- README.md
Signed-off-by: hchiramm <hchiramm@redhat.com>
Resolves #
**Checklist:**
[skip ci]
> Markdown linter corrections.

- Documentation/ceph-csi-drivers.md
- cluster/examples/kubernetes/ceph/operator-with-csi.yaml
Follow up changes to CSI operator
Resolves #
**Checklist:**
[skip ci]
> add endpoints to rook ceph csi operator

- build/release/Makefile
> docs: Update the build process to use the new docs build process

- images/cross/Dockerfile
Signed-off-by: Michael Goff <thephred@gmail.com>
> build: Update node to 10.x in cross container

- Documentation/cassandra-operator-upgrade.md
- pkg/operator/cassandra/constants/constants.go
Fixes wrong mount point for PersistentVolume used by Cassandra. Code changes are very minor.
Resolves #2443
> cassandra: fix wrong mount point

- build/release/Makefile
- images/cross/Dockerfile
From https://github.com/rook/rook/pull/2497 and https://github.com/rook/rook/pull/2653
> Backport docs build process

- cmd/rook/cassandra/cassandra.go
- cmd/rook/ceph/agent.go
- cmd/rook/ceph/ceph.go
- cmd/rook/ceph/config.go
- cmd/rook/ceph/mds.go
- cmd/rook/ceph/nfs.go
- cmd/rook/ceph/operator.go
- cmd/rook/ceph/osd.go
- cmd/rook/ceph/rgw.go
- cmd/rook/cockroachdb/cockroachdb.go
- cmd/rook/discover.go
- cmd/rook/edgefs/edgefs.go
- cmd/rook/main.go
- cmd/rook/minio/minio.go
- cmd/rook/nfs/nfs.go
- cmd/rook/rook/rook.go
Signed-off-by: darshanime <deathbullet@gmail.com>
now it looks like:
```
Usage:
rook [command]
Available Commands:
cassandra   Main command for cassandra controller pod.
cockroachdb Main command for cockroachdb operator and daemons.
discover    Discover devices
edgefs      Main command for edgefs operator and daemons.
help        Help about any command
minio       Main command for Minio operator and daemons.
nfs         Main command for NFS operator and daemons.
version     Print the version number of rook
Flags:
-h, --help                           help for rook
--log-flush-frequency duration   Maximum number of seconds between log flushes (default 5s)
--log-level string               logging level for logging/tracing output (valid values: …
```
> unhide cobra commands

- Documentation/development-flow.md
Add more details on building and setting up a dev environment to help onboarding of new contributors.
**Checklist:**
[skip ci]
> Docs: Consistent dev environment

- design/ceph-nfs-ganesha.md
"replacment" to "replacement" in line 137.
[skip ci]
> Fix typo in doc

- Documentation/edgefs-iscsi-crd.md
- Documentation/edgefs-isgw-crd.md
- Documentation/edgefs-nfs-crd.md
- Documentation/edgefs-s3-crd.md
- Documentation/edgefs-s3x-crd.md
- cluster/examples/kubernetes/edgefs/cluster.yaml
- cluster/examples/kubernetes/edgefs/s3.yaml
- pkg/apis/edgefs.rook.io/v1alpha1/types.go
- pkg/operator/edgefs/cluster/target/config/config.go
- pkg/operator/edgefs/cluster/target/pod.go
- pkg/operator/edgefs/cluster/target/pod_test.go
- pkg/operator/edgefs/s3/s3.go
Provided a way to configure s3type.
Resolves #2510, #2681 
**Checklist:**
> EdgeFS: support for S3 buckets as DNS subdomain style

- Documentation/edgefs-vdev-management.md
**Description of your changes: Added a document about raw disks management in the EdgeFS**
Resolves #2573 
[skip ci]
> Edgefs VDEV management document

- tests/framework/clients/read_write.go
- tests/framework/installer/nfs_installer.go
- tests/framework/installer/nfs_manifests.go
- tests/integration/nfs_test.go
Signed-off-by: zhangyue <zy675793960@yeah.net>
As the title described, add nfs with multi export integration test.
Resolves #2038
> test: add nfs with multi export integration test

- Documentation/ceph-object.md
"retreived" to "retrieved" in line 142.
[skip ci]
> Fix misspell in doc

- Documentation/helm-operator.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml.tmpl
(cherry picked from commit dcc5d2b5ea494f9bec6596a2cc1aa44af5c29b48)
Backport of #2737.
@travisn do you think this is worth a release notes entry?
Resolves #2737.
**Checklist:**
> Added ROOK_HOSTPATH_REQUIRES_PRIVILEGED as value to Helm Chart

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
For the v0.9.3 release, the image tags need to be updated.
**Checklist:**
[skip ci]
> Set the rook image version to v0.9.3 in the example yamls

- Documentation/ceph-dashboard.md
Signed-off-by: Ryo Nakao <nakabonne@gmail.com>
This is a small fix just adding '-https'
[skip ci]
> Fix service name in doc

- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
Use the `rook/ceph` images, as they include the required tools and the `ceph-toolbox` images are no longer built for releases.
N/A
**Checklist:**
> update image for coreos reboot daemonsets

- Documentation/flexvolume.md
Sorted the flexvolume platform specific paths alphabetically.
Added some spacing around code blocks to prevent issues with certain
Markdown renderers.
Resolves #
**Checklist:**
[skip ci]
> docs: sorted flexvolume platform paths alphabetical

- Documentation/advanced-configuration.md
Signed-off-by: Enrique Medina Montenegro <enrique@medinamontenegro.es>
Resolves #
**Checklist:**
[skip ci]
> Add section to Change Failure Domain

- tests/README.md
Signed-off-by: Ryo Nakao <nakabonne@gmail.com>
We need wget when running [`tests/scripts/helm.sh`](https://github.com/rook/rook/blob/master/tests/scripts/helm.sh), so I guess specifying is more kind since it’s not pre-installed in MacOS.
[skip ci]
> Add wget to required tool list

- pkg/operator/ceph/file/mds/config.go
> Ceph file/mds: fix typo: mgr -> mds

- tests/integration/base_deploy_test.go
- tests/integration/cassandra_test.go
- tests/integration/cockroachdb_test.go
- tests/integration/multi_cluster_test.go
- tests/integration/nfs_test.go
Signed-off-by: zhangyue <zy675793960@yeah.net>
add ci logs when build is successful
Resolves #2790 
**Checklist:**
> test: add ci logs when build is successful

- pkg/daemon/ceph/client/filesystem.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/mds/mds.go
From ceph mimic (13.x) onwards, `mds deactivate` command is
deprecated. To scale down the number of active MDSes of a filesystem,
it's sufficient to set the desired number of active MDSes using
'max_mds' setting, and is no longer required to individually
deactivate the unwanted MDSes.
Resolves: #2725
Signed-off-by: Ramana Raja <rraja@redhat.com>
> ceph filesystem: don't use `mds deactivate` mimic onwards

- Documentation/ceph-csi-drivers.md
updated ceph-csi-drivers.md document to test cephfs csi driver.
Resolves #
**Checklist:**
[skip ci]
> Add cephfs csi doc

- Documentation/ceph-cluster-crd.md
- pkg/operator/ceph/cluster/cluster.go
Resolves #2461 
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>
> Allow Ceph detect version Job to accept placement

- pkg/daemon/ceph/client/command.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/orchestrator.go
Some of the dashboard operations need retries for when the manager hasn't fully started up.
> retry dashboard operations

- pkg/operator/ceph/cluster/rbd/config.go
- pkg/operator/ceph/cluster/rbd/mirror.go
Resolves #
**Checklist:**
[skip ci]
> Ceph rbd-mirror: use updateAndWait for daemons

- Gopkg.lock
- pkg/operator/edgefs/cluster/utils.go
Remove glog import from edgefs rook operator
Resolves #2807
**Checklist:**
> Edgefs,Issue 2807: Remove glog from edgefs rook operator

- Documentation/development-environment.md
- tests/scripts/k8s-vagrant-multi-node.sh
This adds a basic wrapper script around k8s-vagrant-multi-node project.
Resolves #1540
**Checklist:**
[skip ci]
> tests/scripts: Added basic k8s-vagrant-multi-node wrapper script

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Sets `bug` or `feature` label depending on the issue template chosen.
**Checklist:**
[skip ci]
> Set bug or feature label depending on issue template

- design/ceph-nfs-ganesha.md
Signed-off-by: Ker Liu kerliu818@gmail.com
fix a typo in design/ceph-nfs-ganesha.md
Resolves #
**Checklist:**
[skip ci]
> doc: Fix typo in doc

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster.yaml
> ceph: add docs for encrypted devices

- tests/framework/installer/edgefs_installer.go
- tests/framework/installer/edgefs_manifest.go
- tests/integration/edgefs_test.go
Simple integration tests for Edgefs cluster has been added
Resolves #2791
**Checklist:**
> Edgefs: Integration tests for EdgeFS

- Documentation/ceph-csi-drivers.md
- cluster/examples/kubernetes/ceph/csi/example/cephfs/pod.yaml
- cluster/examples/kubernetes/ceph/csi/example/cephfs/pvc.yaml
- cluster/examples/kubernetes/ceph/csi/example/cephfs/secret.yaml
- cluster/examples/kubernetes/ceph/csi/example/rbd/pod.yaml
- cluster/examples/kubernetes/ceph/csi/example/rbd/pvc-restore.yaml
- cluster/examples/kubernetes/ceph/csi/example/rbd/pvc.yaml
- cluster/examples/kubernetes/ceph/csi/example/rbd/secret.yaml
- cluster/examples/kubernetes/ceph/csi/example/rbd/snapshot.yaml
The current document is too old and it has a reference to the master branch(earlier master branch referred to csi-v0.3.0).
This PR updated the snapshot document wrt to the changes required for csi-v1.0.0
Resolves #
**Checklist:**
[skip ci]
> update ceph-csi rbd snapshot document

- Documentation/ceph-csi-drivers.md
Remove manual namespace creation from the doc because it will be created as part of common.yaml deployment.
**Checklist:**
[skip ci]
> remove manual namespace creation from doc

- pkg/operator/ceph/cluster/cluster.go
Fixes #2858 
Resolves #2858 
**Checklist:**
// for known CI issue
[skip ci]
> prevent multiple orchestrations at the same time

- Documentation/ceph-cluster-crd.md
> ceph: add link to ceph docs on encryption details

- cluster/examples/kubernetes/ceph/operator-openshift.yaml
set correct flexvolume dir for openshift4
Resolves #
**Checklist:**
// no need for builds on this yaml change
[skip ci]
> set correct flexvolume dir for openshift4

- Documentation/ceph-examples.md
Adding some more context and details to the ceph examples
I have tried to improve the ceph examples documentation. Added more context around the keywords (explanations and links to relevant documentation of the ceph project for example). 
Resolves #
As discussed with @travisn on Slack, I am submitting this documentation update.
**Checklist:**
- [X ] Documentation has been updated, if necessary.
[skip ci]
> Improving ceph-examples-md 

- pkg/operator/ceph/cluster/osd/spec.go
As per https://github.com/ceph/ceph/pull/26856 Ceph tunes the value of
osd-memory-target when running the OSD process so there is no need to
enforce it.
We also set a safety factor to that value which has been calculated by
the Ceph eng/perf team. Without this factor, the OSD will get OOM killed
since it is consuming memory for other purposes too.
[skip ci]
> ceph: osd, do not auto tune osd-memory-target

- Documentation/ceph-monitoring.md
- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-rules.yaml
- cluster/examples/kubernetes/ceph/monitoring/prometheus.yaml
Added prometheusRule file to enable prometheus based alerting for ceph storage.
Related to #2821 
**Checklist:**
[skip ci]
> Prometheus Rule for Ceph

- tests/framework/installer/ceph_manifests.go
I modified but missed saving this change intended to go into PR #3009.
[skip ci]
> ceph integration test: rm replicasets permission

- Documentation/ceph-cluster-crd.md
- Documentation/helm-operator.md
- cluster/charts/rook-ceph/values.yaml.tmpl
- design/mon-health.md
- pkg/operator/ceph/cluster/mon/health.go
design docs: update ROOK_MON_HEALTHCHECK_INTERVAL
Resolves #
**Checklist:**
[skip ci]
> docs: update ROOK_MON_HEALTHCHECK_INTERVAL

- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml.tmpl
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/daemon/discover/discover.go
- pkg/operator/ceph/cluster/controller.go
> Hotplug ignore rbd

- Documentation/ceph-examples.md
- cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml
Resolves #
**Checklist:**
[skip ci]
> csi with openshift support

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Fixes #3046 
Signed-off-by: Steven Rathbauer <steven@rathpc.com>
**Description of your changes:** This corrects the wrong slack links as well as the broken links in the template files.
Resolves #3046 
**Checklist:**
[skip ci]
> Correcting broken/wrong links in templates

- Documentation/edgefs-isgw-crd.md
- pkg/apis/edgefs.rook.io/v1beta1/types.go
- pkg/operator/edgefs/isgw/isgw.go
Resolves #3069 
**Checklist:**
Ci failures look like Ceph CI issues and not something related to EdgeFS, adding [skip ci]
> address regression in ISGW dynamicFetch configuring

- Documentation/ceph-cluster-crd.md
**Description of your changes:** Minor improvements to the ceph cluster CRD documentation.
Resolves # n/a
**Checklist:**
[skip ci]
> Minor documentation improvements

- pkg/operator/ceph/cluster/osd/osd.go
The list of nodes to be queried for configuring OSDs should include all of the K8s nodes before the placement or other filters are applied. The operator was sometimes missing configuring OSDs on nodes if the discover pod hadn't finished running on a node. Now the osd prepare job will be triggered on a node even if the discover pod hasn't yet run there.
Resolves #2977 
**Checklist:**
[skip ci]
> Query the latest list of nodes for osd orchestration

- Documentation/README.md
- Documentation/cassandra-operator-upgrade.md
- Documentation/ceph-advanced-configuration.md
- Documentation/ceph-cluster-crd.md
- Documentation/ceph-common-issues.md
- Documentation/ceph-csi-drivers.md
- Documentation/ceph-toolbox.md
- Documentation/development-environment.md
- Documentation/development-flow.md
- Documentation/flexvolume.md
- Documentation/helm-operator.md
- Documentation/k8s-pre-reqs.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
This updates the documentation and examples to use the v1.0.0 or
release-v1.0 branch wherever applicable.
Resolves #
**Checklist:**
[skip ci]
> Update documentation and examples to v1.0.0

- cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml
Added separator in YAML to enable creation of multiple SCC need by rook-ceph and rook-ceph-csi
Resolves #3096 
[skip ci]
> Added separator to enable creation of multiple SCC

- PendingReleaseNotes.md
The pending release notes for the next release need to start empty. Time to start on the 1.1 features!
**Checklist:**
[skip ci]
> Clear the pending release notes for the next release

- pkg/daemon/ceph/client/auth.go
- pkg/daemon/ceph/client/command.go
- pkg/daemon/ceph/client/crush.go
- pkg/daemon/ceph/client/erasure-code-profile.go
- pkg/daemon/ceph/client/filesystem.go
- pkg/daemon/ceph/client/image.go
- pkg/daemon/ceph/client/mgr.go
- pkg/daemon/ceph/client/mon.go
- pkg/daemon/ceph/client/osd.go
- pkg/daemon/ceph/client/pg.go
- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/status.go
- pkg/daemon/ceph/client/usage.go
- pkg/daemon/ceph/osd/device.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/dashboard_test.go
- pkg/operator/ceph/cluster/mgr/orchestrator.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/util/exec/exec.go
- pkg/util/exec/test/mockexec.go
This PR
1) adds a timeout-variant of running commands while collecting output from a file
2) refactors the ceph commands to reduce the number of interfaces
3) fixes #2734 by using the timeout variant
Resolves #2784
[skip ci]
> ceph: generate self-signed cert via a command that can timeout

- Documentation/ceph-upgrade.md
The default mon port has changed from 6790 to 6789. With the msgr2 work in nautilus, the mons need to be listening on the default ports. These instructions will direct users to failover the mons to the new default port.
We may want to look at automating this failover process, although that may be more risky than having the admin carefully do it as described here.
Resolves #3104 
**Checklist:**
[skip ci]
> Ceph: Upgrade guide for failing over mons to new default port

- cluster/examples/kubernetes/ceph/storageclass.yaml
This PR removes an incorrect space to validate the yaml file
[skip ci]
> Validate yaml by removing incorrect space

- Documentation/edgefs-cluster-crd.md
- pkg/operator/edgefs/s3/s3.go
- pkg/operator/edgefs/s3x/s3x.go
- pkg/operator/edgefs/swift/swift.go
S3 proxy container has added to S3X pod
Resolves #3169
**Checklist:**
// Known CI issues
[skip ci]
> Edgefs: Add s3 proxy container to S3X pod

- Documentation/ceph-teardown.md
Backport #3170 doc change.
Resolves #
**Checklist:**
[skip ci]
> Backport #3170

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
Update the documentation and examples to v1.0.1 for the release.
**Checklist:**
[skip ci]
> Update documentation and examples to v1.0.1

- Documentation/edgefs-csi.md
- cluster/examples/kubernetes/edgefs/cluster.yaml
- pkg/operator/edgefs/cluster/target/pod.go
Backport of 3182 to release-1.0
Resolves #3182
**Checklist:**
[skip ci]
> Edgefs:3181 prevents multiple targets deployment on the same node

- cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml
(cherry picked from commit 32057646ccb284be2e02cb72bead036e964cb66a)
Resolves #3096 
[skip ci]
> [backport] Added separator to enable creation of multiple SCC

- .gitignore
- Makefile
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/olm/ceph/README.md
- cluster/olm/ceph/assemble/metadata-common.yaml
- cluster/olm/ceph/assemble/metadata-k8s.yaml
- cluster/olm/ceph/assemble/metadata-openshift.yaml
- cluster/olm/ceph/assemble/rook-ceph.package.yaml
- cluster/olm/ceph/generate-rook-csv.sh
[skip ci]
Resolves #
**Checklist:**
> deployment: OLM integration

- Documentation/development-environment.md
> doc: add link to vagrant+libvirt setup

- pkg/operator/ceph/cluster/mgr/spec.go
Signed-off-by: Christian Hüning <christian.huening@figo.io>
Added Liveness Probe to Ceph Mgr
Resolves #2270 
**Checklist:**
[skip ci]
> added Liveness Probe to Ceph Mgr

- Documentation/ceph-common-issues.md
- Documentation/ceph-quickstart.md
Since the default OSD is no longer created under dataDirHostPath, the most common issue in the 1.0 release is that users don't have OSDs created in the cluster. Now the quickstart doc will guide users to create a test cluster to get them going with a filestore OSD in a directory, with clear guidance that devices should be available for production clusters.
Resolves #3242 #3243 
**Checklist:**
[skip ci]
> Ceph Quickstart Doc to specify test configuration for OSDs

- Documentation/ceph-common-issues.md
- Documentation/ceph-quickstart.md
(cherry picked from commit 346f2c9fd4912e5ce749ad9d91be825768b7e19d)
Since the default OSD is no longer created under dataDirHostPath, the most common issue in the 1.0 release is that users don't have OSD created in the cluster. Now the quickstart doc will guide users to create a test cluster to get them going with a filestore OSD in a directory, with clear guidance that this is not expected in production
Resolves #3242 #3243
**Checklist:**
[skip ci]
> Backport: Ceph quickstart uses the test configuration instead of devices

- cluster/examples/kubernetes/ceph/csi/example/rbd/storageclass.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-attacher.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
Remove various excess white space from ceph csi template files & example files.
**Checklist:**
[skip ci]
> Whitespace cleanups in ceph csi yaml files

- pkg/daemon/ceph/client/pg.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/remove.go
Updated the struct `PGDumpBrief` to handle json unmarshal for changed output of `ceph pg dump pgs_brief` command
Resolves #3178 
**Checklist:**
[skip ci]
> fixed ceph pg dump pgs_brief json deserialization

- pkg/daemon/ceph/client/pg.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/remove.go
Updated the struct PGDumpBrief to handle json unmarshal for changed output of ceph pg dump pgs_brief command backported into release 1.0
Resolves #3178 
**Checklist:**
[skip ci]
> Backport: Ceph pg dump pgs_brief json deserialization

- Documentation/ceph-cluster-crd.md
- pkg/operator/ceph/cluster/rbd/mirror.go
- pkg/operator/ceph/spec/spec.go
> Doc resource limit

- pkg/daemon/discover/discover.go
- pkg/daemon/discover/discover_test.go
the only exception to a naive device list comparison had been to ignore
drive UUID information which was unreliable when a device wasn't
formatted / partitioned. however various users have reported different
type of false positives that resulted in orchestration being run
continuously due to the wrong observation that devices were changing.
this patch fixes the cases we have observed and attempts to be slightly
more conservative in the calculation.
1. the devlinks is ignored. when a device is setup for lvm, for example,
the devlinks will be updated with different paths that point to the
device in addition to its standard paths addressable by pci address.
2. in the lvm case, the "model" field and "filesystem" field may also
change.
3. we ignore devices with devlinks that contain "usb" to …
> discover: handle false-positives observed by users

- pkg/operator/ceph/cluster/controller.go
Sometime the kube engine needs a bit of time to return the logs of a
given job and fails to read the stream.
Retrying up to 6 seconds to detect the Ceph version seems reasonnable to
overcome this issue.
Fixes: https://github.com/rook/rook/issues/3227
Resolves #
**Checklist:**
> ceph: retry on detecting ceph version

- pkg/operator/ceph/cluster/cluster.go
the resource struct has non-exportable fields which panics when
compared without setting a cmp.Option that allows for it
In particular, it deals with the case where we get:
```
E0511 17:34:40.863208       8 runtime.go:67] Observed a panic: cannot handle unexported field: {v1.ClusterSpec}.Resources["mgr"].Limits["cpu"].i
consider using AllowUnexported or cmpopts.IgnoreUnexported
```
Signed-off-by: David Luu <david@davidluu.info>
Resolves #3166 
**Checklist:**
[skip ci]
> ceph: added comparer for resource quantity when checking cluster changes

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
Set the version to v1.0.2 in deployment manifests and documentation for the release.
**Checklist:**
[skip ci]
> Set the image version to v1.0.2 in deployment manifests and docs

- Documentation/flexvolume.md
Very small PR that adds the location for AKS
[skip ci]
> Include AKS in the oddity list

- Documentation/ceph-dashboard.md
* Provided steps to enable Object Gateway mgmt. from toolbox CLI.
Signed-off-by: alfonsomthd <almartin@redhat.com>
**Checklist:**
[skip ci]
> ceph: updated doc. for enabling dashboard object gateway mgmt.

- pkg/daemon/ceph/client/osd.go
- pkg/operator/ceph/cluster/osd/health.go
- pkg/operator/ceph/cluster/osd/health_test.go
If for any reason an osd is marked out and ceph migrates its data and we determine it is safe-to-destroy, then rook would remove the K8s artifacts for those OSDs.
Resolves #2741
[Addendum: Resolves #3292]
**Checklist:**
[skip ci]
> Clean up the OSD after the OSD is marked "out"

- CODE-OWNERS
- CONTRIBUTING.md
- GOVERNANCE.md
- OWNERS.md
**Description of your changes:** This PR describes the new process for change approval to increase the code velocity of contributors to the Rook project.  New roles for approvers and reviewers are defined and the process to approve and merge changes is described in detail.
**Checklist:**
[skip ci]
> governance: new change approval process to include approvers/reviewers

- pkg/operator/minio/controller.go
Signed-off-by: xiaorui.zou <xiaorui.zou@gmail.com>
fix https://github.com/rook/rook/issues/3141  throw validate func err msg
[skip ci]
> Minio: throw validatefunc err msg

- Documentation/edgefs-upgrade.md
- cluster/examples/kubernetes/edgefs/cluster.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- pkg/apis/edgefs.rook.io/v1beta1/types.go
- pkg/apis/edgefs.rook.io/v1beta1/utils.go
- pkg/apis/edgefs.rook.io/v1beta1/zz_generated.deepcopy.go
- pkg/operator/edgefs/cluster/cluster.go
- pkg/operator/edgefs/cluster/configmap.go
- pkg/operator/edgefs/cluster/controller.go
- pkg/operator/edgefs/cluster/mgr/mgr.go
- pkg/operator/edgefs/cluster/mgr/mgr_test.go
- pkg/operator/edgefs/cluster/target/layout.go
- pkg/operator/edgefs/cluster/target/pod.go
- pkg/operator/edgefs/cluster/target/target.go
- pkg/operator/edgefs/cluster/utils.go
- pkg/operator/edgefs/iscsi/controller.go
- pkg/operator/edgefs/iscsi/iscsi.go
- pkg/operator/edgefs/isgw/controller.go
- pkg/operator/edgefs/isgw/isgw.go
- pkg/operator/edgefs/nfs/controller.go
- pkg/operator/edgefs/nfs/nfs.go
- pkg/operator/edgefs/s3/controller.go
- pkg/operator/edgefs/s3/s3.go
- pkg/operator/edgefs/s3x/controller.go
- pkg/operator/edgefs/s3x/s3x.go
- pkg/operator/edgefs/swift/controller.go
- pkg/operator/edgefs/swift/swift.go
Enables upgrade of EdgeFS cluster by editing edgefsImageName in cluster CRD
Resolves #2990
**Checklist:**
[skip ci]
> EdgeFS Rolling Upgrade support

- design/storage-class-device-set.md
A design doc for #3305 to define the notion of DeviceSets in Rook, with an example for rook-ceph.
Related: #919 
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>
[skip ci]
> Rook StorageClassDeviceSet design doc

- Documentation/ceph-csi-drivers.md
- cluster/examples/kubernetes/ceph/csi/example/cephfs/secret.yaml
- cluster/examples/kubernetes/ceph/csi/example/rbd/secret.yaml
- cluster/examples/kubernetes/ceph/csi/example/rbd/snapshotclass.yaml
- cluster/examples/kubernetes/ceph/csi/example/rbd/storageclass.yaml
- tests/integration/ceph_csi_test.go
cephcsi PR https://github.com/ceph/ceph-csi/pull/395 changed the way we are storing secrets. This PR will bring the same changes to the rook as well.
Resolves #3357
**Checklist:**
[skip ci]
Known issue
> Update rbd and cephfs secret

- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml.tmpl
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/agent/agent.go
- pkg/operator/discover/discover.go
- pkg/operator/k8sutil/node.go
- pkg/operator/k8sutil/node_test.go
Adding NodeAffinity Spec to Agent and Discover DaemonSet.
Resolves #2005 
**Checklist:**
[skip ci]
known issue.
> Added NodeAffinity to Agent and Discover Daemon

- Documentation/edgefs-cluster-crd.md
- pkg/apis/rook.io/v1alpha2/types.go
- pkg/operator/discover/discover.go
- pkg/operator/edgefs/cluster/target/layout.go
Resolves #3374 
**Checklist:**
[skip ci]
> support for rook Device.FullPath

- Documentation/ceph-object.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/object-ec.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
- cluster/examples/kubernetes/ceph/object-test.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- design/object-store.md
- pkg/operator/ceph/cluster/mgr/config.go
- pkg/operator/ceph/cluster/rbd/config.go
- pkg/operator/ceph/config/keyring/store.go
- pkg/operator/ceph/config/keyring/store_test.go
- pkg/operator/ceph/file/mds/config.go
- pkg/operator/ceph/object/config.go
- pkg/operator/ceph/object/config_test.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/rgw_test.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
- pkg/operator/k8sutil/daemonset.go
Backport of https://github.com/rook/rook/pull/3283
[skip ci]
> Bkp rgw refactor

- pkg/operator/ceph/cluster/controller.go
If we are running a Ceph cluster that has an unsupported version and if
we have set allowUnsupported: false, a newly bootstrap operator will
fail to start. To fix this, the user will update the CR and set
allowUnsupported: true, however at this point clusterInfo hasn't been
initialized so the operator will panic because we were referencing a nil
pointer.
To fix this, we re-populate clusterInfo if necessary and things go
smoothly.
Closes: https://github.com/rook/rook/issues/3137
(cherry picked from commit f183ad2bb19238eebfb827d5d6198055c4cb559f)
Backport of: https://github.com/rook/rook/pull/3388
[skip ci]
> backport: ceph: controller: fix panic on cr update

- Documentation/edgefs-cluster-crd.md
- pkg/apis/rook.io/v1alpha2/types.go
- pkg/operator/discover/discover.go
- pkg/operator/edgefs/cluster/target/layout.go
This replaces #3402 which was unintentionally closed. 
Resolves #3374
**Checklist:**
> Backport: EdgeFS support for device full path

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
For the v1.0.3 release, the docs and example yamls are updated in the release branch to reflect the same.
**Checklist:**
[skip ci]
> Update the yaml and doc versions to v1.0.3 for the release

- PendingReleaseNotes.md
- pkg/daemon/ceph/client/crush.go
- pkg/daemon/ceph/client/image.go
- pkg/daemon/ceph/config/keyring.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/config/keyring/admin.go
- pkg/operator/ceph/object/config.go
- pkg/operator/ceph/object/config_test.go
- pkg/operator/ceph/provisioner/provisioner.go
- tests/framework/installer/ceph_installer.go
- tests/framework/utils/k8s_helper.go
Backport of https://github.com/rook/rook/pull/3414 and https://github.com/rook/rook/pull/3409 and https://github.com/rook/rook/pull/3415 and https://github.com/rook/rook/pull/3410
[skip ci]
known issue
> Backport batch

- Documentation/ceph-object.md
Add a --region in the s3cmd tutorial
Related to #2945
**Checklist:**
[skip ci]
> Add a --region in the s3cmd tutorial

- pkg/operator/ceph/cluster/osd/health.go
Updated the condition check to avoid operator crash.
Resolves #3359
**Checklist:**
[skip ci]
> Updated condition check to avoid panic

- pkg/operator/ceph/cluster/controller.go
For all calls to detect the Ceph version, ensure they are consistent.
**Checklist:**
> Ceph: Fix crit bug in call to detect Ceph version

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
For the v1.0.4 release, the docs and example yamls are updated in the release branch to reflect the same.
**Checklist:**
[skip ci]
> Update the yaml and doc versions to v1.0.4 for the release

- .github/ISSUE_TEMPLATE.md
This is not a recommended workflow but useful if people click on "Don’t
see your issue here? Open a regular issue."
Resolves #
**Checklist:**
[skip ci]
> github: re-add default template for new issues

- pkg/operator/k8sutil/cmdreporter/cmdreporter.go
> cmdreporter: fix minor error bug

- Documentation/edgefs-upgrade.md
- pkg/apis/edgefs.rook.io/v1beta1/cluster.go
- pkg/operator/edgefs/cluster/cluster.go
- pkg/operator/edgefs/cluster/cluster_deployment_config.go
- pkg/operator/edgefs/cluster/configmap.go
- pkg/operator/edgefs/cluster/controller.go
- pkg/operator/edgefs/cluster/target/layout.go
- pkg/operator/edgefs/cluster/target/pod.go
- pkg/operator/edgefs/cluster/target/pod_test.go
- pkg/operator/edgefs/cluster/target/target.go
- pkg/operator/edgefs/cluster/utils.go
- pkg/operator/edgefs/iscsi/controller.go
- pkg/operator/edgefs/isgw/controller.go
- pkg/operator/edgefs/nfs/controller.go
- pkg/operator/edgefs/s3/controller.go
- pkg/operator/edgefs/s3x/controller.go
- pkg/operator/edgefs/swift/controller.go
- tests/framework/installer/edgefs_manifest.go
Provide functionality to add/remove Kubernetes nodes via EdgeFS cluster's CRD
Resolves #3462
**Checklist:**
> Add/remove nodes via EdgeFS cluster' CRD

- Documentation/helm-operator.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml.tmpl
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/agent/agent.go
- pkg/operator/discover/discover.go
- pkg/operator/k8sutil/tolerations.go
-  Allowed to set multiple tolerations for agent and discover pods 
Resolves #2896
**Checklist:**
[skip ci]
> ceph: allow to set multiple tolerations for agent and discover pods

- Documentation/edgefs-cluster-crd.md
- Documentation/edgefs-upgrade.md
- cluster/examples/kubernetes/edgefs/cluster.yaml
- pkg/apis/edgefs.rook.io/v1beta1/utils.go
- pkg/operator/edgefs/cluster/mgr/mgr.go
Liveness probe for Edgefs manager pod has been added
Resolves #3492 
**Checklist:**
[test edgefs]
> Add mgr pod liveness probe

- cluster/examples/kubernetes/ceph/csi/example/rbd/storageclass.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
- tests/framework/installer/ceph_csi_templates.go
- tests/integration/ceph_csi_test.go
ceph-csi https://github.com/ceph/ceph-csi/pull/457 made deployment template changes and also
removed node publish secrets and added node stage secrets.
Resolves #
**Checklist:**
> update ceph-csi templates

- .github/ISSUE_TEMPLATE/bug_report.md
fix wrong spells in bug_report.md
Resolves #
NONE
**Checklist:**
[skip ci]
> fix misspelling in bug_report.md

- pkg/operator/ceph/cluster/controller.go
Signed-off-by: ethan <guangming.wang@daocloud.io>
/kind cleanup
Resolves #
**Checklist:**
> cleanup: fix log message mis-spelled words

- design/ceph-managed-disruptionbudgets.md
> Ceph: Add design for managed poddisruptionbudgets.

- design/ceph-mon-pv.md
> design: ceph mon pv design

- cluster/examples/kubernetes/edgefs/cluster.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- pkg/operator/edgefs/cluster/cluster.go
- pkg/operator/edgefs/cluster/cluster_deployment_config.go
Signed-off-by: sabbot <sabbotagge@gmail.com>
Resolves #
**Checklist:**
[test edgefs]
> Add validation and extra columns to EfgeFS CRDs

- pkg/operator/edgefs/cluster/utils.go
Signed-off-by: ethan <guangming.wang@daocloud.io>
> logging message typo fix

- pkg/operator/ceph/cluster/mgr/mgr.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
Resolves #
**Checklist:**
- [ x ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
> mgr.go: logging error message typo

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-common-issues.md
- Documentation/ceph-csi-drivers.md
- Documentation/ceph-examples.md
Minor spelling mistakes and formatting cleanups.
**Checklist:**
[skip ci]
> Documentation (Ceph): Fix typos and formatting

- pkg/operator/edgefs/cluster/target/pod.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
fix some typos in comment, make it more readable
Resolves #
**Checklist:**
> edgefs: cleanup pod.go comment, fix typos

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
Update the version tags to v1.0.5 for the release.
**Checklist:**
[skip ci]
> Update the yaml and doc version to v1.0.5 for the release

- pkg/operator/ceph/cluster/mgr/spec.go
This fixes that the MGR is binding to the gateway IP instead of the
actual Pod IP, as seen in #3136.
When hostNetwork: true is set the public-addrr is not set so custom
network configs can be used.
Resolves #3136, possibly others.
**Checklist:**
> mgr: set public-addr flag for MGR

- pkg/daemon/ceph/osd/volume.go
- This PR  removes the 'sed' commands and uses golang utlities to update the lvm.conf file.
- OSD backed by PVC required updating the lvm.conf file which was done by executing the 'sed' commands.
- This PR  removes the 'sed' command and uses golang utlities to update the lvm.conf file.
- This is a follow up PR for the comment - https://github.com/rook/rook/pull/3451#discussion_r308957614
Resolves #3605
**Checklist:**
> Replace "sed" commands with native golang file handling

- design/yugabyte/yugabytedb-rook-design.md
[skip ci]
Resolves #
**Checklist:**
> Added a draft design doc for YugaByte Rook operator

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- tests/framework/installer/ceph_manifests.go
* Extend CephCluster
* Add validation for CephFilesystem,
* Add validation for CephNFS
* Add validation for CephObjectStore
* Syncronozed the validation of all three copies
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
Resolves #
**Checklist:**
> CRDs: Add some more validations

- design/ceph-managed-disruptionbudgets.md
Signed-off-by: Sakura <longfei.shang@daocloud.io>
fix typo in ceph-managed-disruptionbudgets.md
Resolves #
**Checklist:**
[skip ci]
> fix typo in ceph-managed-disruptionbudgets.md

- Documentation/ceph-block.md
Added imageFeature, imageFormat and fstype to Block Storage example, so that snapshots will work.
Resolves #
**Checklist:**
[skip ci]
> Added imageFeatures, imageformat and fstype so that it works with snapshots

- pkg/operator/ceph/cluster/mgr/spec.go
Backport of:
```
mgr: set public-addr flag for MGR
This fixes that the MGR is binding to the gateway IP instead of the
actual Pod IP, as seen in #3136.
When hostNetwork: true is set the public-addrr is not set so custom
network configs can be used.
(cherry picked from commit 6daf408)
```
Resolves #3136
**Checklist:**
[skip ci]
> Backport fix for #3136

- design/ceph-openshift-fencing-mitigation.md
Add a design for handling data resilience during fencing on Openshift 4.x
[skip ci]
> Design: ceph-openshift-fencing-mitigation

- Documentation/ceph-examples.md
- Gopkg.lock
- Gopkg.toml
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/object-bucket-claim-delete.yaml
- cluster/examples/kubernetes/ceph/object-bucket-claim-retain.yaml
- cluster/examples/kubernetes/ceph/storageclass-bucket-delete.yaml
- cluster/examples/kubernetes/ceph/storageclass-bucket-retain.yaml
- design/object-bucket.md
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/bucket.go
- pkg/operator/ceph/object/bucket/api-handlers.go
- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/bucket/rgw-handlers.go
- pkg/operator/ceph/object/bucket/s3-handlers.go
- pkg/operator/ceph/object/bucket/util.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/objectstore_test.go
- pkg/operator/ceph/object/user.go
- pkg/operator/ceph/object/user/controller.go
- tests/framework/clients/bucket.go
- tests/framework/clients/object.go
- tests/framework/clients/test_client.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.0.go
- tests/integration/ceph_base_object_test.go
- tests/scripts/minikube.sh
Based on initial work done by Travis;
Leveraging the [bucket provisioning lib](https://github.com/kube-object-storage/lib-bucket-provisioner) support rgw bucket provisioning in rook-ceph.
cc @travisn
> Bucket provisioner

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
- updated query for latency
- updated severity level for mgr down alert
Resolves #
**Checklist:**
[skip ci]
> fixes: alerting rules and recording rules

- cluster/olm/ceph/generate-rook-csv.sh
Resolves #
**Checklist:**
[skip ci]
> csv: Fix name SA name for CSI RBD provisioner

- pkg/operator/ceph/cluster/osd/health.go
Remove the osd pods that are marked out and are safe to destroy and also the pod is more than an hour old.
Resolves #3521 
**Checklist:**
> OSD: Remove osd pods that are marked out and the pod is more than an hour old.

- cluster/examples/kubernetes/edgefs/operator.yaml
CRD's versions fixed to v1
Resolves #3735
**Checklist:**
[skip ci]
> Edgefs:#3735 fix CRD's version to v1

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- tests/framework/installer/ceph_manifests.go
[ retest this please ]
Resolves #
**Checklist:**
> Reflect pdb rbac in helm template and ceph_manifests.

- pkg/apis/edgefs.rook.io/v1/resources.go
Resolves #3773 
**Checklist:**
[test edgefs]
> ISGW doesnt need large chunk cache

- tests/integration/ceph_base_block_test.go
- tests/integration/ceph_zblock_mount_unmount_test.go
- tests/longhaul/base_block_test.go
Just a typo fix in an integration test method name.
> Tests: Fix typo, defintion -> definition

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-crds.yaml
- tests/framework/installer/ceph_manifests.go
- Renamed MDSCOUNT to ActiveMDS & updated Description
This was to remove the confusion about what the count
is actually about (Active or Active+Standby).
Resolves #
**Checklist:**
> updating additionalPrinterColumns for CephFS

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/charts/rook-ceph/templates/clusterrolebinding.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cmd/rook/ceph/ceph.go
- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/client/crush.go
- pkg/daemon/ceph/client/crush_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/disruption/clusterdisruption/location.go
- tests/framework/installer/ceph_manifests.go
retest this please
Resolves #3632 
**Checklist:**
> Fix topologyAware on PVC-based OSDs

- Documentation/ceph-upgrade.md
Prepare user for 'required' settings earlier in the upgrade doc.
**Checklist:**
[skip ci]
> ceph docs: identify required ceph configs

- Documentation/edgefs-cluster-crd.md
- Documentation/edgefs-upgrade.md
- cluster/examples/kubernetes/edgefs/cluster.yaml
Resolves #3798 
**Checklist:**
[skip ci]
> edgefs image version update in examples and docs

- Documentation/ceph-cluster-crd.md
- Gopkg.lock
- Gopkg.toml
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cmd/rook/ceph/operator.go
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/disruption/clusterdisruption/reconcile.go
- pkg/operator/ceph/disruption/machinedisruption/add.go
- pkg/operator/ceph/disruption/machinedisruption/doc.go
- pkg/operator/ceph/disruption/machinedisruption/reconcile.go
- pkg/operator/ceph/disruption/machinelabel/add.go
- pkg/operator/ceph/disruption/machinelabel/doc.go
- pkg/operator/ceph/disruption/machinelabel/reconcile.go
- pkg/operator/ceph/disruption/register_controllers.go
- tests/framework/installer/ceph_manifests.go
This commit adds support for MDB controller anf machineLabel controller required for fencing during ocs upgrade.
**NOTE:** PR https://github.com/rook/rook/pull/3596 needs to be merged first before merging this.
Resolves #
**Checklist:**
> Adds MDB controller and machineLabel controller required for fencing

- PendingReleaseNotes.md
Resolves #
**Checklist:**
[skip ci]
[skip-ci]
> pending release update for EdgeFS

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/charts/rook-ceph/templates/role.yaml
- cluster/charts/rook-ceph/templates/rolebinding.yaml
update helm chats roles for leases roles
Resolves #3777
**Checklist:**
> Add leases rules to csi roles in helm chart

- Documentation/ceph-upgrade.md
The configuration for using Rook with CSI images has changed somewhat
since v1.0, and users of Ceph's CSI drivers will need to consider some
additional update steps.
Resolves #
**Checklist:**
[skip ci]
> ceph upgrade doc: document CSI image changes

- pkg/daemon/discover/discover.go
- adds regex to ignore updates on nbd device
similar to 'rbd' and 'dm'
Resolves #3540 
**Checklist:**
[skip ci] leseb: known random issue
> ignore updates on nbd device

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Previous alert description was confusing. This makes it more
generic and user understandable.
Resolves #
**Checklist:**
[skip ci]
> Changed description for CephDataRecoveryTakingTooLong alert

- Documentation/nfs.md
NFS: Added an example to consume the nfs export created by nfs operator.
Resolves #
**Checklist:**
[skip ci]
> NFS: Added an example to consume the nfs export created by nfs operator.

- pkg/operator/ceph/nfs/nfs.go
In order to run ganesha exporting cephfs we must have an MDS server
running. So, if not present we fail the instanciation of the CR.
Closes: https://github.com/rook/rook/issues/3835
Resolves https://github.com/rook/rook/issues/3835
**Checklist:**
> nfs: fail if no mds are running

- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
- pkg/operator/ceph/config/defaults.go
> pg autoscaler and osd bluefs fixes

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-quickstart.md
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- images/ceph/Makefile
- pkg/operator/ceph/cluster/controller_test.go
- tests/framework/installer/ceph_installer.go
- tests/longhaul/base_block_test.go
v14.2.4 just got released so let's use it.
Resolves #
**Checklist:**
> ceph: bump to v14.2.4

- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
- pkg/operator/ceph/config/defaults.go
> Backport: pg autoscaler and osd bluefs fixes

- pkg/daemon/ceph/client/upgrade.go
- pkg/daemon/ceph/client/upgrade_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/osd/osd.go
Backport of: https://github.com/rook/rook/pull/3870
> Backport: ceph: fix upgrade commands

- Documentation/ceph-block.md
- Documentation/ceph-common-issues.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_base_deploy_test.go
Backport of: https://github.com/rook/rook/pull/3724
> Backport: operator: ceph disable flexdriver

- PendingReleaseNotes.md
The pending release notes are now reset, ready for new features to be added in master towards the v1.2 release.
**Checklist:**
[skip ci]
> Reset the pending release notes for the next release

- pkg/daemon/ceph/agent/flexvolume/controller_test.go
Remove dead code.
Co-authored-by:: Tuan Do Anh <tuanda@vn.fujitsu.com>
Resolves #
**Checklist:**
> test: remove unused function

- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-apply.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-create.yaml
updated required rules for upgrading CSI from v1.0 to v1.1 and also updated the document with
required steps
Resolves #3868
**Checklist:**
[skip ci]
> update cephcsi upgrade document

- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-apply.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-create.yaml
updated required rules for upgrading CSI from
v1.0 to v1.1 and also updated the document with
required steps
(cherry picked from commit 4a8b821c79532f67f1c7193cbff5578ae97acb9e)
Resolves #
**Checklist:**
> Backport: update csi upgrade document

- pkg/operator/ceph/disruption/nodedrain/add.go
- pkg/operator/ceph/disruption/nodedrain/reconcile.go
- pkg/operator/ceph/disruption/nodedrain/reconcile_test.go
Should be ready, need to verify behavior by testing.
Resolves #3813 
**Checklist:**
> Tolerations for drain detection canaries

- cluster/olm/ceph/assemble/metadata-common.yaml
- cluster/olm/ceph/generate-rook-csv.sh
Resolves #3826 
**Checklist:**
[skip ci]
> Add CephNFS to OLM's clusterserviceversion

- cluster/olm/ceph/assemble/metadata-common.yaml
- cluster/olm/ceph/assemble/rook-ceph.package.yaml
Generate ClusterServiceVersion for release v1.1.1
Resolves #
**Checklist:**
[skip ci]
> Generate OLM clusterserviceversion v1.1.1

- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
Backport https://github.com/rook/rook/pull/3945
Resolves #
**Checklist:**
> Backport: Disable Flexdriver in helm chart and operator-openshift

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
When the flex driver is disabled, the check for
volume attachments will fail and the finalizer
is never removed. To avoid this, just log the
failure to list volumes and remove the
finalizer anyway.
Resolves #3912
**Checklist:**
> Ceph: Remove finalizer even if flex is disabled

- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-create.yaml
correct misspelled words in https://github.com/rook/rook/pull/3944/files
Resolves #
**Checklist:**
> Correct SYSTEM spelling

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
When the flex driver is disabled, the check for
volume attachments will fail and the finalizer
is never removed. To avoid this, just log the
failure to list volumes and remove the
finalizer anyway.
Resolves #3912
Signed-off-by: Kristoffer Grönlund <kgronlund@suse.com>
(cherry picked from commit fb599dd02be492fd9c097c94fa84c5cc32350480)
> Backport: Ceph: Remove finalizer even if flex is disabled

- pkg/operator/ceph/csi/spec.go
- pkg/operator/k8sutil/statefulset.go
previously we are not updating the service if it's already present. with this change,
we will update the service. this does not trigger any error message if service already present.
Resolves #
**Checklist:**
> Update service if already present

- pkg/daemon/ceph/osd/agent_test.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/osd/spec.go
> ceph: various osd fixes and improvements with lvm and ceph-volume

- pkg/operator/ceph/csi/spec.go
- pkg/operator/k8sutil/statefulset.go
previously we are not updating the service if it's already present. with this change, we will update the service. this does not trigger any error message if service already present.
(cherry picked from commit bdfdac8ee4fd5c9abbde3e15eb83e911c68e0396)
Resolves #
**Checklist:**
> backport: Update service if already present

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- tests/framework/installer/ceph_manifests.go
Signed-off-by: Rajat Singh rajasing@redhat.com
Added validation for cephBlockPool,cephfs and cephnfs
Resolves #3480 
**Checklist:**
> Added validation for cephBlockPool,cephfs and cephnfs

- PendingReleaseNotes.md
- pkg/daemon/ceph/config/config.go
- pkg/daemon/ceph/config/config_test.go
- pkg/daemon/ceph/osd/agent_test.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/device.go
- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/osd/spec.go
Backport of https://github.com/rook/rook/pull/3955 and https://github.com/rook/rook/pull/3969.
> Backport: various fixes

- build/makelib/golang.mk
This commit updates Makefile to allow compiling with golang 1.13.
Resolves #
**Checklist:**
> enhance: Updates Makefile to allow compiling with go 1.13

- Documentation/edgefs-cluster-crd.md
- cluster/examples/kubernetes/edgefs/cluster_kvssd.yaml
- pkg/apis/edgefs.rook.io/v1/cluster.go
- pkg/apis/edgefs.rook.io/v1/devices.go
- pkg/apis/edgefs.rook.io/v1/types.go
- pkg/operator/edgefs/cluster/cluster_deployment_config.go
- pkg/operator/edgefs/cluster/configmap.go
- pkg/operator/edgefs/cluster/target/config/config.go
- pkg/operator/edgefs/cluster/target/layout.go
- pkg/operator/edgefs/cluster/target/pod.go
- pkg/operator/edgefs/cluster/utils.go
Signed-off-by: Sergey Kaydalov <kayserg@gmail.com>
EdgeFS: added support for Samsung KV SSD
Resolves #3997 
**Checklist:**
[skip ci]
[skip-ci]
> EdgeFS: support for rtkvs disk engine and Samsung KVSSD

- cluster/charts/rook-ceph/templates/clusterrole.yaml
moved line https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/templates/clusterrole.yaml#L270 bellow `rook-ceph-osd` cluster role
Resolves #3993 
**Checklist:**
[skip ci]
> Updated rook-ceph-osd clusterrole for helm chart

- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
Update the manifests to point to the new v1.1.2 release
**Checklist:**
[skip ci]
> Updated image tags for the v1.1.2 release

- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-apply.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-create.yaml
Backport for #3944 and #3963 
**Checklist:**
[skip ci]
> Backport: Correct system namespace for csi driver settings during upgrade

- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/bucket/s3-handlers.go
Fixing issues related for OBC handling brownfield cases
Resolves #3792
Resolves #4010
**Checklist:**
> Fixing issues for object bucket claims for brownfield cases (delete policy)

- Documentation/ceph-csi-drivers.md
- design/object-bucket.md
During I was reading rook documents, I noticed some updated links.
Thus I updated the links.
Resolves #
**Checklist:**
[skip ci]
> doc: update outdated links

- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
Signed-off-by: awalker60 <awalker125@users.noreply.github.com>
Resolves #3885
**Checklist:**
> ceph: change imagepullpolicy for csi-snapshot image

- pkg/operator/ceph/disruption/clusterdisruption/osd.go
The clusterdisruption starts up before the Ceph cluster is created and
during the initilization, it'll display invalid error messages such as:
```
2019-10-14T04:22:21.243679454Z 2019-10-14 04:22:21.243668 E | clusterdisruption-controller: could not check cluster health: failed to get status: exit status 1
2019-10-14T04:22:22.524222494Z 2019-10-14 04:22:22.524179 I | exec: Running command: ceph status --connect-timeout=15 --cluster=openshift-storage --conf=/var/lib/rook/openshift-storage/openshift-storage.config --keyring=/var/lib/rook/openshift-storage/client.admin.keyring --format json --out-file /tmp/605071670
2019-10-14T04:22:22.617370007Z 2019-10-14 04:22:22.617321 I | exec: Error initializing cluster client: ObjectNotFound('error calling …
```
> ceph: hide wrong error for clusterdisruption controller

- cmd/rookflex/cmd/unmount.go
Using `df --type ceph` has proven not to be reliable enough, so let's try
with findmnt.
Closes: https://github.com/rook/rook/issues/4107
Resolves https://github.com/rook/rook/issues/4107
**Checklist:**
[test full]
[test ceph]
> ceph: detect mount fstype more accurately

- Documentation/yugabytedb.md
Updates the YugabyteDB docs to show a user how to access the Yugabyte dashboard locally. Just a nice feature when going through the quickstart!
Resolves N/A
[skip ci]
**Checklist:**
> yugabyte docs: add directions on how to access yugabytedb dashboard

- Documentation/ceph-block.md
- Documentation/ceph-filesystem.md
- cluster/examples/kubernetes/ceph/csi/cephfs/storageclass.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/snapshotclass.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass-test.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
- pkg/daemon/ceph/client/erasure-code-profile.go
- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/model/pool.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/cluster/mon/config_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
- pkg/operator/ceph/config/keyring/store.go
- pkg/operator/ceph/csi/secrets.go
- pkg/operator/ceph/csi/secrets_test.go
- pkg/operator/ceph/file/filesystem.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_csi_test.go
Backport of pull request #4086.
> ceph: rework csi keys and secrets (bp #4086)

- pkg/operator/ceph/cluster/mgr/config.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/dashboard_test.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
- pkg/operator/ceph/cluster/mgr/orchestrator.go
- pkg/operator/ceph/cluster/mgr/orchestrator_test.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/k8sutil/delete.go
The mgr modules take some time to run and have also been known to hang. While the hang issues should have been resolved separately (see #4021), an improvement is asynchronously configure the modules so the overall mgr configuration will be much faster.
**Checklist:**
[test ceph]
> Run the mgr module configuration asynchronously

- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the v1.1.3 patch release we need to set the new tag in the deployment manifests and documentation.
**Checklist:**
[skip ci]
> Set the v1.1.3 release tag

- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the v1.1.4 patch release we need to set the new tag in the deployment manifests and documentation.
**Checklist:**
[skip ci]
> Set the v1.1.4 release tag

- tests/integration/ceph_mon_test.go
Depending on the state of the orchestration, the operator might trigger re-creation of the deleted mon. In this case, consider the test successful rather than wait for the failover which will never occur.
**Checklist:**
[test full]
[test ceph]
> Improve reliability of the Ceph mon failover test

- cluster/charts/rook-ceph/Chart.yaml
[skip ci]
Signed-off-by: Sean Corkum <seancorkum81@gmail.com>
Update the helm chart icon
Resolves #3939
**Checklist:**
> update helm chart image

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- tests/framework/installer/ceph_manifests.go
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
Relates to https://github.com/sebastian-philipp/rook-ceph-client-python/commit/23bdcde086b446335db25c88fee4ad04efee7ec6#diff-547608f9971ab6854df920a365883ffe
Resolves #
**Checklist:**
> ceph: Add removeOSDsIfOutAndSafeToRemove to CRD

- Documentation/development-environment.md
Signed-off-by: mykaul <ykaul@redhat.com>
Both issues were already merged in Kubespray, so hopefully irrelevant anymore.
Resolves #
**Checklist:**
[skip ci]
> Remove comments on merged issues

- pkg/operator/ceph/cluster/mon/mon.go
If the cluster has previously been initialized and the operator
is restarted, the operator needs to perform the first orchestration
to confirm basic cluster health, then start watching for CR events.
If there was a single mon pod in a failed or pending pod state, the
orchestration was blocked even if just one mon was in this state.
The scenario is when a node is lost and a mon and the operator happen
to be running on that node. The operator will restart, but the mon
will not restart because it is tied to the node that died (unless running
on a PVC). The mon would remain in a pending state while attempting
to schedule on the node that is down indefinitely and the operator would
be blocked indefinitely. Now we will just log the error and attempt
to continue. …
> Continue with orchestration if a single mon pod fails to start

- images/ceph/Makefile
The yq tool changed and requires a new path from which to build.
Resolves: #4241 
**Checklist:**
[skip ci]
> Build Fix: Update the path to pull the yq tool

- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the v1.1.5 release we update the manifests with the new tag.
**Checklist:**
[skip ci]
> Set the v1.1.5 release tag

- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the v1.1.6 release we update the manifests with the new tag. The v1.1.5 release was skipped due to a merge to the release branch after the tag, but before the v1.1.5 official build was started. (see #4264) 
**Checklist:**
[skip ci]
> Set the v1.1.6 release tag

- pkg/util/exec/exec.go
- pkg/util/proc/monitoredproc_test.go
- pkg/util/sys/device.go
Cleanup codebase
Resolves #
**Checklist:**
> cleanup code in pkg/util

- pkg/operator/ceph/disruption/clusterdisruption/location.go
Resolves #
**Checklist:**
[test ceph]
> Silence disruption errors if necessary and add missing errors

- ROADMAP.md
The v1.2 release is coming up soon, so we need to solidify thef plan for what will be included in the release. Features in this list are planned, although not guaranteed for the next release.
This update is currently primarily for the Ceph provider. Other storage providers would open a separate PR as needed.
**Checklist:**
[skip ci]
> Update the roadmap for the rook v1.2 release

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cmd/rook/ceph/osd.go
- cmd/rook/ceph/osd_test.go
- pkg/operator/ceph/cluster/osd/topology.go
- pkg/operator/ceph/disruption/clusterdisruption/location.go
- pkg/operator/ceph/disruption/clusterdisruption/osd.go
- pkg/operator/ceph/disruption/nodedrain/reconcile.go
- tests/framework/installer/ceph_manifests.go
Backport of #4281 
[test ceph]
> Fix topology logic for drains (bp #4281)

- pkg/operator/k8sutil/cmdreporter/cmdreporter.go
The app name was not being set in k8sutil's cmdreporter code, resulting
in jobs being labeled `app=` with no name. Change cmdreporter's `New`
method to validate the contents of the config struct and not the inputs
to the `New` method to help prevent an issue like this from creeping up
in the future.
Does not resolve but was exposed by my investigation of #4300
**Checklist:**
> k8sutil: cmdreporter: properly set app name

- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
See the commits.
**Checklist:**
[test ceph]
> ceph: osd various lvm enhancement

- pkg/daemon/ceph/osd/daemon.go
The OSD needs to shut down quickly during upgrade, or other scenarios
where the OSD is being restarted. To facilitate this fast shutdown,
rook will run kill -9 on the osd process. The Ceph OSD is designed
to be safe even when killed like this. This allows the
ECONNREFUSED to be returned sooner, which will redirect the OSD
traffic to other OSDs and cause less downtime.
**Checklist:**
> Stop osd process more quickly during pod shutdown to reduce IO unresponsiveness

- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the v1.1.7 release we update the manifests with the new tag.
**Checklist:**
[skip ci]
> Set the v1.1.7 release tag

- pkg/operator/ceph/disruption/clusterdisruption/osd.go
Earlier, simultaneous drains could allow the drain detection to switch
disabled PDBs before the Ceph health had fully reflected the effects.
Resolves #
**Checklist:**
> Ceph: Add delay between drain switches

- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/rbd/mirror.go
Some log messages indicate when the upgrade checks will be
performed. If the Ceph image hasn't changed, the upgrade checks
are skipped. The messages were confusing if running a Rook
upgrade.
**Checklist:**
[test ceph]
> Clarify log message for Ceph upgrades

- pkg/operator/ceph/version/version.go
- pkg/operator/ceph/version/version_test.go
We now print the build number.
Resolves #
**Checklist:**
[test full]
> ceph: fix ceph version output

- pkg/operator/ceph/nfs/spec.go
- pkg/operator/nfs/server.go
Allow to run on OpenShift, see commits for more details.
Resolves https://github.com/rook/rook/issues/3525
**Checklist:**
[test ceph]
> ceph: openshift ganesha fixes

- design/ceph/multus-network.md
Add the design doc for integrating multus with the ceph backend.
[skip ci]
This PR is really an open discussion, nothing is set in stone and the goal is to find what's best for us as a group.
> design: rook multus design

- Documentation/ceph-object-bucket-claim.md
just a quick typo fix
N/A
**Checklist:**
[skip ci]
> docs: fix typo on ceph bucket claim description

- .mergify.yml
Add a new rule for the upcoming release-1.2 branch.
[skip ci]
> mergify: add backport-release-1.2 rules

- Documentation/edgefs-quickstart.md
removed dead link to edgefs-helm-operator
Signed-off-by: Cody Belcher <cody.t.belcher@gmail.com>
Removing a dead link from the documentation.
[skip ci]
N/A - no issue open for this
**Checklist:**
> removed dead link to edgefs-helm-operator

- cluster/examples/kubernetes/ceph/object-ec.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
- cluster/examples/kubernetes/ceph/object.yaml
Minor typographical correction in yaml comments.
[skip ci]
> Correct spelling error.

- images/nfs/Dockerfile
NFS: updated the current nfs version to a newer version
Trying to fix NFS integration tests.
#4437 
**Checklist:**
[test nfs]
> NFS: updated the current nfs version to a newer version

- pkg/operator/ceph/nfs/spec.go
Let's put the PID under the directory owned by ganesha.
Closes: https://github.com/rook/rook/issues/3525
Resolves https://github.com/rook/rook/issues/3525
**Checklist:**
[test ceph]
> ceph: change ceph-nfs pid location

- Documentation/ceph-toolbox.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the creation of the release-1.2 branch we need to tag
the manifests with the beta.0 tag for the initial beta test
release.
**Checklist:**
[skip ci]
> Update manifest tags to the v1.2.0-beta.0 tag

- Documentation/edgefs-cluster-crd.md
- cluster/examples/kubernetes/edgefs/s3PayloadSecret.yaml
- pkg/apis/edgefs.rook.io/v1/devices.go
- pkg/apis/edgefs.rook.io/v1/types.go
- pkg/operator/edgefs/cluster/configmap.go
- pkg/operator/edgefs/cluster/target/config/config.go
- pkg/operator/edgefs/cluster/target/layout.go
- pkg/operator/edgefs/cluster/target/pod.go
Signed-off-by: Sergey Kaydalov <kayserg@gmail.com>
edgefs: added support for data payload forwarding to an external S3
Resolves #4431
[test edgefs]
**Checklist:**
> EdgeFS: support for payload on external S3 server

- Documentation/branch.liquid
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/minio-object-store.md
- Documentation/nfs.md
Signed-off-by: AlexPunnen <alex.punnen@nokia.com>
Resolves #
**Checklist:**
[skip ci]
> add 'git clone' step to quickstart guides

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/crash/crash.go
- pkg/operator/ceph/cluster/crash/reconcile.go
- pkg/operator/ceph/csi/secrets.go
- pkg/operator/ceph/spec/label.go
Look at the individual commits.
**Checklist:**
[test ceph]
> ceph: various controller and crash fixes

- pkg/operator/ceph/object/config.go
- pkg/operator/ceph/object/spec.go
Fix rgw liveness probe error. See commits for more details.
Resolves https://github.com/rook/rook/issues/4471 and https://github.com/rook/rook/issues/4400
**Checklist:**
[test ceph]
> ceph: fix rgw liveness probe error

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Improved storage utilization alert description to make alert actionable.
Resolves #
**Checklist:**
[skip ci]
> ceph: Improve storage utilization alert description and message.

- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the v1.1.8 release we update the manifests with the new tag.
**Checklist:**
[skip ci]
> Set the v1.1.8 release tag in the manifests

- pkg/operator/edgefs/s3/s3.go
- pkg/operator/edgefs/s3x/s3x.go
- pkg/operator/edgefs/swift/swift.go
Resolves #4500 
**Checklist:**
[test edgefs]
> edgefs: Fix restapi image selection

- pkg/operator/edgefs/cluster/cluster.go
- pkg/operator/edgefs/cluster/cluster_deployment_config.go
- pkg/operator/edgefs/cluster/controller.go
- pkg/operator/edgefs/cluster/target/target.go
Additional check for invalid node creation/update
Resolves #4510 
**Checklist:**
[test edgefs]
> EdgeFS: prevent configuration removal

- Documentation/ceph-upgrade.md
To simplify the readability of the important sections for the upgrade we will increase the header size.
**Checklist:**
[skip ci]
> Increase size of headers in the Ceph upgrade doc

- Documentation/edgefs-cluster-crd.md
- Documentation/edgefs-quickstart.md
- Documentation/edgefs-upgrade.md
Signed-off-by: Dmitry Yusupov <dmitry@nexenta.com>
Resolves #4539 
**Checklist:**
[skip ci]
> EdgeFS: last minute doc changes for 1.2

- tests/framework/clients/client.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.0.go
- tests/integration/ceph_client_test.go
wait for client to be updated before verifying caps
Signed-off-by: Mateusz Los <los.mateusz@gmail.com>
Resolves #
**Checklist:**
> ceph: client CRD test fixes

- Documentation/helm-operator.md
- cluster/charts/rook-ceph/values.yaml
This increases the rook-ceph chart's memory limit from 128Mi to 256Mi.
Starting with the upgrade to rook v1.2.0 (from v1.1.7), the rook-ceph-operator pod started getting OOMkilled, see the following `describe` snippet for some more context:
```
Containers:
rook-ceph-operator:
Container ID:  containerd://26c0bae3f066fb3e4a53af96e4239cea8182ba4865fd440b486406ed98990b6c
Image:         rook/ceph:v1.2.0
Image ID:      docker.io/rook/ceph@sha256:ad8a75181d8814a6b6a99b04205abed3b5ea0c99205c363fd49364e6e0353ee9
Port:          <none>
Host Port:     <none>
Args:
ceph
operator
State:          Waiting
Reason:       CrashLoopBackOff
Last State:     Terminated
Reason:       OOMKilled
Exit Code:    137
Started:      Fri, …
```
> ceph: Bump operator mem limit

- Documentation/development-flow.md
This commits adds more documentation on how to contribute better commit
messages.
**Checklist:**
[skip ci]
> documentation: improve commit structure

- Documentation/ceph-disaster-recovery.md
Minor updates to documentation for Ceph disaster recovery after an incident. 
none
**Checklist:**
[skip-ci]
> doc: disaster recovery updates after an incident

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the v1.2.1 patch release the manifests are now updated
**Checklist:**
[skip ci]
> Set manifest version to v1.2.1

- PendingReleaseNotes.md
Need to reset the pending release notes for the 1.3 features..
**Checklist:**
[skip ci]
> Reset the pending release notes for 1.3

- build/makelib/golang.mk
Signed-off-by: taeuk_kim <taeuk_kim@tmax.co.kr>
Fix a typo in golang makelib
Resolves #
**Checklist:**
[skip ci]
> build: fix typo in makelib

- Documentation/ceph-cluster-crd.md
Updating CephCluster CRD documentation
Resolves #
**Checklist:**
[skip ci]
> Ceph: updates CephCluster CRD doc to include monitoring options

- pkg/operator/ceph/cluster/mon/mon.go
If all mons are down (e.g. set the replicas to 0 on all the mon deployments) and the operator is restarted, the operator waits indefinitely for a single mon to start. This PR fixes this issue by skipping the quorum check of mons if the number of ready mon pods is equal to 0.
Signed-off-by: Ashish Ranjan <ashishranjan738@gmail.com>
Resolves https://github.com/rook/rook/issues/4531
**Checklist:**
[test ceph]
> ceph: Skipping quorum check if no. of ready mons is 0

- pkg/operator/ceph/cluster/controller.go
When initialization of cluster failed,
devicesInUse variable can be set to true (if spec.storage.useAllDevices is set to true)
and then, when we update CephCluster k8s manifest
(to get initialization to work),
devicesInUse is already set to true
and "using all devices in more than one namespace is not supported" error can happen.
Closes: https://github.com/rook/rook/issues/4633
Resolves https://github.com/rook/rook/issues/4633
**Checklist:**
[test ceph]
> ceph: reset devicesInUse on orchestration error

- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the v1.1.9 release we update the manifests with the new tag.
**Checklist:**
[skip ci]
> Set the v1.1.9 release tag

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the v1.2.2 release we update the manifests with the new tag.
**Checklist:**
[skip ci]
> Set the v1.2.2 manifest tags

- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
We now use a defined directory for each prepare job so that logs won't
be entangled with each other.
Also, if an error occurs, we print the log file too so we don't have to
ssh onto a host to find the c-v debug log.
Closes: https://github.com/rook/rook/issues/3888
Resolves https://github.com/rook/rook/issues/3888
**Checklist:**
[test ceph]
> ceph: expose c-v log per pvc

- Documentation/ceph-cluster-crd.md
Signed-off-by: Satoru Takeuchi <satoru.takeuchi@gmail.com>
Add a note of OSD in placement.
Resolves #4582 
**Checklist:**
- [x ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
> ceph: add a note of osd in placement

- pkg/daemon/ceph/osd/volume.go
14.2.7 will only be a CVE fix release so 14.2.8 is the release that will
contain the fixes for ceph-volume partition.
Resolves #
**Checklist:**
[test ceph]
> ceph: bump raw block mode support to 14.2.8

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the v1.2.3 release we update the manifests to the new version.
**Checklist:**
[skip ci]
> Update manifests for the v1.2.3 release

- Documentation/openshift-issues.md
- adds guide to troubleshoot Ceph Cluster monitoring on OpenShift
Resolves #4636
**Checklist:**
[skip ci]
> Ceph: adds openshift common issues documentation

- Documentation/flexvolume.md
This PR clarifies the Kubespray section (which changed as of v2.11.0 and newer to use the kubelet default plugin directory)
This PR also rearranges the flow of the document to make more sense and be easier to jump straight to the relevant platform-specific section: adding anchor links for the platforms having special instructions on this page. Links to the platform's home page/docs page were moved to a "see also" as they may not be as relevant to someone already having deployed their cluster using it.
Resolves #4746
**Checklist:**
~- [ ] Unit tests have been added, if necessary.~
~- [ ] Integration tests have been added, if necessary.~
~- [ ] Pending release notes updated with breaking and/or notable …
> docs: Sort flexvolume docs, update for kubespray

- Documentation/ceph-common-issues.md
Signed-off-by: Satoru Takeuchi <satoru.takeuchi@gmail.com>
Add the description about the following issue to the common issues.
https://github.com/rook/rook/issues/3132
Resolves #3132 
**Checklist:**
[skip ci]
> Ceph: Add an rbd hang up problem in the common issues

- Jenkinsfile
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_block_test.go
- tests/integration/ceph_helm_test.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_smoke_test.go
- tests/integration/ceph_upgrade_test.go
- tests/longhaul/base_block_test.go
- tests/scripts/localPathPV.sh
This commit adds integration tests for osds provisioned over PVCs.
Resolves #
**Checklist:**
[test full]
[test ceph]
> Add integration test for OSDs over PVCs

- Jenkinsfile
This commit updates the jenkins file to pre clean the k8s cluster before the running the integeration tests.
Resolves #
**Checklist:**
> Jenkins: Updates jenkins file to pre clean the k8s cluster

- pkg/operator/k8sutil/k8sutil.go
- pkg/operator/k8sutil/k8sutil_test.go
- pkg/operator/k8sutil/volume_test.go
Resolves #
https://github.com/rook/rook/issues/4572
**Checklist:**
[test ceph]
> ceph: Fix md5 crypto to more secure sha256
