rook/rook

- Jenkinsfile
this is an alternate implementation of our Jenkins build process which can be versioned with the rest of the source tree. instead of using job DSL files which must be pre-seeded in Jenkins, we use a single Jenkinsfile which is loaded by Jenkins from the branch at the moment a build trigger (push/PR) is invoked
> adding production Jenkins build Pipeline

- build/clean
- build/common.sh
- build/run
concurrent runs of build/run are now supported. This is mostly
to benefit jenkins scenarios. removed the need to name containers
and also refactored the rsync path.
Fixes #202
> build: support concurrent runs of build/run

- cmd/rook/block-list.go
- cmd/rook/block-list_test.go
- cmd/rook/block_test.go
Block mount and unmount is not supported and will error so I've removed it from the rook client (only on mac) for now.
fixes #185
> rook: remove block mount and unmount on mac

- Jenkinsfile
currently the builds are always exiting 0 even when there are failures because the error handling mechanism is overriding the final exit code passed back up to jenkins
> setting proper exit code on stage failure

- build/common.sh
- build/run
we were starting the container and stopping it twice to rsync two dirs. with this fix only one start/stop happens.
> build: improve speed of rsync on exit

- pkg/cephmgr/mon/agent.go
- pkg/cephmgr/osd/agent.go
- pkg/cephmgr/osd/device.go
- pkg/util/exec/exec.go
- pkg/util/proc/monitoredproc.go
- pkg/util/proc/monitoredproc_test.go
- pkg/util/proc/procmanager.go
Issue https://github.com/rook/rook/issues/221. Now we will know which mon, osd, or other subprocess is logging.
> Write child process log entries with a very specific id

- cmd/rookd/main.go
- demo/vagrant/cloud-config.yml.in
- pkg/util/id.go
- pkg/util/id_test.go
The order of precedence for the id is as follows: (edited)
1) Load the id from the dataDir
2) generate a random id (12 random hex chars)
After generated at first run, it will be persisted to `$datadir/node-id`.
Fixes https://github.com/rook/rook/issues/216 and https://github.com/rook/rook/issues/182
> cache node id in the data dir

- cmd/rook/rook/rook.go
- cmd/rookd/main.go
- demo/kubernetes/README.md
- demo/kubernetes/mysql.yml
- demo/kubernetes/rook.yml
- pkg/util/flags/flags.go
This serves as a simple example of running rook in a kubernetes environment and shows how to consume a block device as a data dir for mysql.
Please see the following for changes need to coreos-kubernetes to run the demo: https://github.com/rook/coreos-kubernetes/commit/651dece8c62fef45d76889bd64247bd6eb51546a
Also added the ability to set global flags with environment variables in the rook cli.
Resolves #234
> Added a kubernetes demo

- cmd/rookd/main.go
the ceph daemons don't work with relative paths. See https://github.com/rook/rook/issues/183
> always use absolute path for data dir

- build/ceph-submodule-check
helper script to check submodule references are valid. see https://github.com/rook/rook/wiki/Ceph-submodule for details.
> build: add a script to check ceph submodule

- pkg/etcdmgr/bootstrap/client.go
- pkg/etcdmgr/bootstrap/context.go
- pkg/etcdmgr/bootstrap/discovery.go
- pkg/etcdmgr/bootstrap/discovery_test.go
- pkg/etcdmgr/bootstrap/etcd.go
Two improvements in this change:
1. Retry requests to the etcd discovery service in case the network is unstable. Retry up to 10 times, backing off another half second each time. If it still fails after that, the daemon that launched rook should restart it (ie. the k8s pod will restart)
2. When etcd members are starting concurrently the first time, there is a race condition that allows more servers to register with the etcd discovery service than the size specifies. If this were external etcd, the extra servers could simply fall back to be proxies. But in rook we would rather ignore the extra registered servers. The servers that registered first, up to the cluster size, will be returned.
> Improve stability of internal etcd at startup

- demo/kubernetes/rook.yml
To match the quickstart docs at https://github.com/rook/rook/tree/master/demo/kubernetes#using-the-storage
> Update rookd REST API service node port to worker node

- build/README.md
From a fresh clone of the rook source, you have to
update the git submodules before building rook.
Fix a bad reference to build/clean, it should
be build/reset
> Document submodules in README.md

- demo/vagrant/Vagrantfile
- demo/vagrant/cloud-config.yml.in
The approach of uncommenting from the Vagrantfile and cloud config to launch a local aci does not work long term during development because you have to constantly keep track of the two additional files checked out, for which you never have the intention of committing. With this change, you can set an environment variable to indicate that a local build (ACI) should be launched instead of pulling from quay.
Launch a local ACI build from vagrant:
```
export START_LOCAL_ROOKD=1
vagrant up
```
To download from quay again:
```
export START_LOCAL_ROOKD=
vagrant up
```
> load a local build into vagrant based on env var

- build/run
the go pkg directory was not bind mounted and resulted
in lots of rebuilds.
> build: fix incremental build on linux

- cmd/rook-operator/main.go
- cmd/rookd/osd.go
- pkg/cephmgr/osd/agent.go
- pkg/cephmgr/osd/daemon.go
- pkg/cephmgr/osd/daemon_test.go
- pkg/operator/operator.go
- pkg/operator/operator_test.go
- pkg/operator/osd/osd.go
Formatting devices for OSDs automatically is prone to data loss when there is a device that the admin is storing data on. This change will configure a directory under the data dir (/var/lib/rook) for an osd. A flag is exposed on the operator that will allow turning back on the previous behavior to format devices automatically. 
Fixes #401. To configure the devices as expected, we will need #397
> Use a directory by default rather than taking over devices

- pkg/operator/api/api.go
- pkg/operator/k8sutil/pod.go
- pkg/operator/k8sutil/pod_test.go
rook-operator does not support customize repository prefix of image quay.io/rook/rookd:TAG.
This prevent us from using our own image repository to deploy rook-operator.
fix #415 
I cannot squash all these commits right for #415 , so i open this new pr. closing #415.
@travisn 
Related to #418
> support customize repository prefix of image through environment

- cmd/rook-operator/main.go
- cmd/rook-operator/restapi.go
- demo/kubernetes/README.md
- demo/kubernetes/rook-cluster.yaml
- demo/kubernetes/rook-operator.yaml
- glide.lock
- glide.yaml
- pkg/api/k8s/cluster_handler.go
- pkg/api/k8s/node.go
- pkg/operator/api/api.go
- pkg/operator/cluster.go
- pkg/operator/cluster_list.go
- pkg/operator/event.go
- pkg/operator/k8sutil/k8sutil.go
- pkg/operator/k8sutil/pod.go
- pkg/operator/k8sutil/timer.go
- pkg/operator/mds/mds.go
- pkg/operator/mon/mon.go
- pkg/operator/mon/pod.go
- pkg/operator/operator.go
- pkg/operator/operator_test.go
- pkg/operator/osd/osd.go
- pkg/operator/rgw/rgw.go
- pkg/operator/tpr.go
A single instance of rook is still supported and will always be created in the `rook` namespace. In the future we may add support for multiple instances. 
This change also updated the k8s client-go library to the 2.0 tag instead of using the 1.5 tag.
> Watch for Rook third party resource before creating the cluster

- pkg/operator/operator.go
- pkg/operator/tpr.go
For the operator to avoid the timeout when initializing a cluster, a Rook cluster can be created in a goroutine. 
Fixes #438
> Start and resume clusters asynchronously

- pkg/cephmgr/osd/daemon.go
- pkg/cephmgr/osd/daemon_test.go
- pkg/operator/cluster.go
- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
Allows flexibility for selecting devices globally in the cluster. For the design, see #465. For more specific selection of devices, we will still need to implement #397
> Evaluate a regular expression for selecting devices

- pkg/operator/operator.go
- pkg/operator/tpr.go
This was a regression from #467. Fixes #473
> Use existing TPR when exists

- glide.lock
- glide.yaml
- pkg/api/daemon.go
- pkg/api/handlers.go
- pkg/api/handlers_test.go
- pkg/api/metrics.go
- pkg/api/metrics_test.go
- pkg/api/routes.go
- pkg/cephmgr/client/mon.go
- pkg/cephmgr/client/osd.go
- pkg/cephmgr/client/pool.go
- pkg/cephmgr/client/status.go
- pkg/cephmgr/client/usage.go
- pkg/cephmgr/collectors/health.go
- pkg/cephmgr/collectors/health_test.go
- pkg/cephmgr/collectors/log.go
- pkg/cephmgr/collectors/mon.go
- pkg/cephmgr/collectors/mon_test.go
- pkg/cephmgr/collectors/osd.go
- pkg/cephmgr/collectors/osd_test.go
- pkg/cephmgr/collectors/pool.go
- pkg/cephmgr/collectors/pool_test.go
- pkg/cephmgr/collectors/usage.go
- pkg/cephmgr/collectors/usage_test.go
- pkg/cephmgr/mon/conn.go
First commit is all the new work that should be reviewed thoroughly.  The second commit is all the Prometheus collectors that were adapted from https://github.com/digitalocean/ceph_exporter, so those can be less rigorously reviewed.
Addresses #426 
Note updated user guide/docs will be addressed by #471 (completed in https://github.com/jbw976/rook/tree/metrics-docs but waiting to open PR until a release with this PR is published)
> Expose metrics for Rook with Prometheus

- build/README.md
The README.md file wasn't updated when the
subdirectory "cross-image" was renamed to "container".
> Update README.md for 'container' subdirectory

- pkg/api/k8s/cluster_handler.go
- pkg/api/k8s/node.go
- pkg/cephmgr/mon/config.go
- pkg/cephmgr/mon/info.go
- pkg/cephmgr/mon/leader.go
- pkg/operator/api/api.go
- pkg/operator/api/api_test.go
- pkg/operator/cluster.go
- pkg/operator/cluster/cluster.go
- pkg/operator/cluster/cluster_list.go
- pkg/operator/cluster/cluster_test.go
- pkg/operator/cluster/spec.go
- pkg/operator/event.go
- pkg/operator/mds/mds.go
- pkg/operator/mds/mds_test.go
- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
- pkg/operator/mon/pod.go
- pkg/operator/mon/pod_test.go
- pkg/operator/operator.go
- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
- pkg/operator/rgw/rgw.go
- pkg/operator/rgw/rgw_test.go
The operator will monitor the cluster for health of the monitors.
- Every 10s query the monitor health
- If a monitor is not in quorum, start a new monitor
- Wait for the new monitor to join quorum
- Remove the dead monitor from quorum
- Update a configmap with the set of mon endpoints in quorum
The mon/osd/rgw/mds/api pods all pick up the mon endpoints from the configmap, which will pass the latest to the pods each time the pod is started
> Detect unhealthy monitors and start new monitors in their place

- Documentation/cluster-tpr.md
- Documentation/kubernetes.md
- Documentation/pool-tpr.md
- demo/kubernetes/rook-cluster.yaml
- demo/kubernetes/rook-operator-with-repo.yaml
- demo/kubernetes/rook-pool.yaml
- demo/kubernetes/rook-storageclass.yaml
- pkg/operator/cluster.go
- pkg/operator/cluster/cluster.go
- pkg/operator/cluster/pool.go
- pkg/operator/cluster/pool_list.go
- pkg/operator/cluster/pool_test.go
- pkg/operator/cluster/spec.go
- pkg/operator/event.go
- pkg/operator/operator.go
- pkg/operator/operator_test.go
- pkg/operator/pool.go
- pkg/operator/tpr.go
- pkg/operator/tracker.go
The `rookpool` TPR allows creating pools with replication or erasure coding. 
Take note that the `cluster` TPR is renamed to `rookcluster` for consistency of naming and to allow kubectl commands without fully qualifying the tpr name. For example:
```
kubectl get rookcluster
kubectl get rookpool
```
> Create storage pools through a TPR

- cmd/rookd/mon.go
this fixes our ability to configure the MON admin-secret via environment variable.
fixes #542
> rookd: fix MON admin-secret command flag.

- external/Makefile
- external/packages/aio/CMakeLists.txt
- external/packages/gperftools/CMakeLists.txt
- external/packages/jemalloc/CMakeLists.txt
- external/packages/rocksdb/CMakeLists.txt
- external/packages/snappy/CMakeLists.txt
- external/packages/zstd/CMakeLists.txt
Fixes #535. Copy the external packages to a private download directory
before building, and then copy them back to the shared directory.
> build: workaround for shared download dir

- Documentation/cluster-tpr.md
- demo/kubernetes/rook-cluster.yaml
- demo/kubernetes/rook-operator.yaml
Addresses #532 and enables rook on kubernetes users by default to start using `master-latest` and the single `quay.io/rook/rookd` container.
The `cluster-tpr.md` file can be more easily parsed/read at https://github.com/jbw976/rook/blob/storage-config-docs/Documentation/cluster-tpr.md
> Cluster TPR storage config examples and documentation

- demo/kubernetes/rook-cluster.yaml
- demo/kubernetes/rook-pool.yaml
- demo/kubernetes/rook-storageclass.yaml
- pkg/operator/tpr.go
Rook is not in beta yet, so the tpr version should be alpha
> Rename tpr version to alpha

- pkg/api/filesystem.go
- pkg/api/node.go
From a discussion on gitter: https://gitter.im/rook/rook?at=58e955297ea420cc424fbe67
I did a full audit of the API service and this is the only error condition not getting logged.
> API: Log errors encountered when getting nodes

- cmd/rook/block/block_test.go
- glide.lock
- glide.yaml
- pkg/api/k8s/cluster_handler.go
- pkg/api/k8s/node.go
- pkg/cephmgr/osd/agent_test.go
- pkg/cephmgr/osd/scheme_test.go
- pkg/operator/api/api.go
- pkg/operator/api/api_test.go
- pkg/operator/cluster.go
- pkg/operator/cluster/cluster.go
- pkg/operator/cluster/cluster_list.go
- pkg/operator/cluster/cluster_test.go
- pkg/operator/cluster/pool_list.go
- pkg/operator/event.go
- pkg/operator/k8sutil/pod.go
- pkg/operator/mds/mds.go
- pkg/operator/mds/mds_test.go
- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
- pkg/operator/mon/pod.go
- pkg/operator/operator.go
- pkg/operator/operator_test.go
- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
- pkg/operator/pool.go
- pkg/operator/rgw/rgw.go
- pkg/operator/rgw/rgw_test.go
- pkg/operator/tpr.go
- pkg/util/proc/monitoredproc_test.go
Updating package dependencies for Rook.
These is needed for the external volume provisioner work.
Partially fixes https://github.com/rook/rook/issues/538
> Updating dependency to support K8S 1.6

- Documentation/k8s-block.md
- Documentation/k8s-filesystem.md
- Documentation/k8s-object.md
- Documentation/kubernetes.md
- Documentation/toolbox.md
- demo/kubernetes/kube-registry.yaml
- demo/kubernetes/rgw-external.yaml
The docs are refactored so we now have block, file, and object all in the walkthrough. While I was refactoring I went ahead and included docs from a couple other sources.
@sajal, I took your content from #569 if you don't mind me including it here. In that case you can close that PR. One question I have is that when I go through the test section at the end, I didn't see a `docker` subfolder. Do I need to actually upload an image to the registry to get that folder to show up?
@rothgar, this includes object storage to fix #509. Your review is appreciated!
To see the docs in rendered form, you may want to refer to the branch: https://github.com/travisn/rook/blob/doc-update/Documentation/kubernetes.md
Thanks @sajal and @rothgar!
> Add object and file system walkthroughs

- Documentation/k8s-block.md
- Documentation/kubernetes.md
- build/makelib/golang.mk
- demo/kubernetes/rook-storageclass.yaml
- glide.lock
- glide.yaml
- pkg/operator/cluster/cluster.go
- pkg/operator/cluster/cluster_test.go
- pkg/operator/k8sutil/pod.go
- pkg/operator/operator.go
- pkg/operator/provisioner.go
- pkg/operator/provisioner_test.go
- pkg/operator/tpr.go
- The provisioner is a Kubernetes external volume provisioner
- It calls the Rook API to create and delete volumes on behalf
of Kubernetes
- It automatically discover Ceph monitor endpoints
- It locates RBD ceph user keys based on the Rook cluster location
- It uses the in-tree RBD volume plugin to do the map/unmap
- Also modified the documentation to reflect the changes on the
storageclass
Fixes  https://github.com/rook/rook/issues/538
> Added volume provisioner to Rook

- cmd/rook/object/connection.go
- cmd/rook/object/user.go
Helps fix #523, although even with a timeout of 60s it still may not be enough time to wait for the object store to init
> increase timeout for actions waiting for object store init

- Documentation/kubernetes.md
- demo/kubernetes/rook-operator.yaml
In case running in a different context, the operator artifacts should all be specified in the same namespace
> Operator artifacts all start in default namespace in the sample

- build/run
Change the script "build/run" to use "exit",
not "return".  "return" is only for use within
a function or a sourced script.
> Fix bash error when testing if DOCKER_HOST is set

- demo/kubernetes/rook-operator.yaml
As discussed on Gitter, this is a missing RBAC permission for bringing up rook in a vanilla 1.6.1 kubeadm cluster.
> Update rook operator for missing `replicasets` permission

- build/README.md
- build/release/containers.sh
> build: use the correct base container for armhf/aarch64

- pkg/clusterd/inventory/disk.go
- pkg/clusterd/inventory/disk_test.go
If OSDs go down while RBD devices are mounted, you cannot get the OSDs back up since the startup sequence hangs when trying to access `rbd*` devices. This commit excludes rbd devices from initial scanning.
I tried building rook with that commit but failed doing so, so this PR is sadly untested. I'll open a separate issue for that.
> Do not try to dump partition tables of RBD devices

- demo/kubernetes/rook-operator.yaml
- pkg/operator/api/api.go
- pkg/operator/api/api_test.go
The api service needs permission to execute kubernetes operations. These operations will not require as many privileges after TPRs are created for file and object, but this gets those service working for now with RBAC enabled. Fixes #612 and #635.
> Create a cluster role for the api service

- e2e/README.md
- e2e/framework/manager/rook_test_infra.go
- e2e/framework/objects/environment_manifest.go
- e2e/scripts/smoke_test.sh
- e2e/tests/cleanup_test_infra_test.go
- e2e/tests/smoke/block_storage_smoke_test.go
- e2e/tests/smoke/file_storage_smoke_test.go
fix for 629 and 640
We are calling clean up before starting a new test suite run so any residue of test infra from older runs are removed.
Also cleaning up test images and adding file system test.
> Cleanup test infra after e2e tests

- e2e/data/smoke/rgw_external.yaml
- e2e/framework/manager/rook_test_infra.go
- e2e/framework/utils/k8s_helper.go
- e2e/framework/utils/rook_helper.go
- e2e/framework/utils/s3_operations.go
- e2e/tests/smoke/file_storage_smoke_test.go
- e2e/tests/smoke/object_storage_smoke_test.go
- e2e/tests/smoke/smoke_test_helper.go
Enabling file system and object store smoke test. Also fixing variable names to follow go naming convention.
> enable file and object store smoke test and fix naming conventions

- demo/kubernetes/rook-operator.yaml
- pkg/operator/mon/mon.go
Pod failover does not handle well the case where the new mon actually fails to start. If that happens, yet another mon pod will be created at the next health check interval. If they continue to fail to start, the number of failed mon pods will grow. Fixes #607 as well as an RBAC issue that prevented the operator from deleting failed mon pods
> Mon failover retries the same pod instead of creating multiple

- demo/standalone/Vagrantfile
A couple of small typos meant that `vagrant up rook01` would only ever create another standalone single-node cluster (which you couldn't reach as only `rook00` has port-forwarding for the API).
Now both `rook00` and `rook01` are visible:
```
14:47 $ ./rook node ls
PUBLIC         PRIVATE        STATE     CLUSTER       SIZE        LOCATION       UPDATED
172.20.20.10   172.20.20.10   OK        rookcluster   33.46 GiB   root=default   0s ago    
172.20.20.11   172.20.20.11   OK        rookcluster   33.46 GiB   root=default   1s ago    
```
> Standalone w/ Vagrant: Fix typos that stop rook01 and rook02 joining the cluster

- e2e/README.md
- e2e/framework/manager/rook_test_infra.go
- e2e/framework/objects/environment_manifest.go
- e2e/images/README.md
- e2e/scripts/smoke_test.sh
- e2e/tests/smoke/block_storage_smoke_test.go
- e2e/tests/smoke/file_storage_smoke_test.go
- e2e/tests/smoke/object_storage_smoke_test.go
in case uses want to run tests against existing pre-installed version of rook.  #627
> adding new flag to skip rook set up

- demo/kubernetes/rook-operator.yaml
Rook complained that it is not allowed to patch in the default namespace. I added it to the clusterrole.
> Add patch to clusterrole

- e2e/framework/clients/rest_client.go
- e2e/framework/manager/rook_test_infra.go
- e2e/framework/utils/k8s_helper.go
- pkg/operator/mon/health.go
- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
- pkg/operator/mon/spec.go
- pkg/operator/mon/spec_test.go
- pkg/operator/test/client.go
One replicaset is created for each mon, with a replica count of 1. The mons are assigned to a node, which is critical for recovery of the mon. When a new pod is started, the same metadata dir will be available on the same node as long as a hostDir was specified. If no hostDir was specified then quorum is required to restore that monitor. Bringing up a new mon to replace a bad pod is dependent on #586. Until that is fixed, if the replicaset replaces a mon pod, it will just be killed off by the operator's health check and a new mon will be created altogether.
Fixes #579
> Mons started as a replicaset instead of directly as a pod

- demo/helm/rook-operator/README.md
Great addition!
Few suggestions:
i. namespace used till now for operator was: rook (not rook-operator).
ii. `helm delete --purge` (note the --purge), so one can retry again later with the same name.
With regards to charts.rook.io -> why not in the https://github.com/kubernetes/charts/tree/master/incubator , so you won't need to deploy a helmet yourself?
> fine tuning

- build/release/binaries.sh
- build/release/common.sh
Fix a regression introduced in 32cd0a1 where when publishing from master we were not updating the /current directory in s3. 
Fixes #652 and #651
> build: publish binaries to s3 current and remove version from archive name

- README.md
Removing the broken roadmap link until #638 is merged
[skip ci]
> docs: remove stale roadmap link

- demo/kubernetes/rook-operator.yaml
Without this patch, rook at v0.4.0 is broken if RBAC is enabled
> Added PATCH /api/v1/events RBAC privilege

- Documentation/client.md
Hi,
I came across a dead link while browsing the documentation. This pull request would fix that, assuming this is where the link was meant to go.
For reference, the dead link is the first link on this page: https://github.com/rook/rook/blob/master/Documentation/client.md
Take care
> docs: Fix a dead link in client.md

- Jenkinsfile
new build agents could take 1 hour + 15 mins to build and test everything with empty caches.
> build: extend the timeout to 2 hours

- Makefile
- build/makelib/common.mk
- build/makelib/golang.mk
- glide.lock
- glide.yaml
this will ensure that we do not have broken dependencies. Expected behavior:
Completely clean tree -- i.e. no vendor subdir
```
make -j4
== glide install runs
```
glide.yaml is updated and more recent than glide.lock
```
make -j4
== glide update runs
== glide install runs (not needed but really quick)
```
also addresses #789.
@kokhang this should probably be merged before #787
> build: run glide update when glide.yaml changes

- Makefile
- build/makelib/common.mk
- build/makelib/golang.mk
- glide.lock
2cdfdab3d regressed the build and we were building for linux_amd64 even when build.all was called
> build: fix regression in build

- pkg/operator/mon/health.go
- pkg/operator/mon/mon_test.go
> mon: using appName as monitor name on failover

- Documentation/kubernetes.md
Ceph journal, required 5GB to be correctly created, otherwise it will
fail with a InvalidArgumentError. Fixes #839
> docs: Add 5GB free requisite when using dataDirHostPath

- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
- pkg/operator/mon/spec.go
- pkg/operator/operator.go
- pkg/operator/provisioner/provisioner.go
- pkg/operator/provisioner/provisioner_test.go
Remove the provisioner's dependence on the Rook REST api. The image can be created directly by the operator and the mon endpoints retrieved from the configmap directly.
> operator: remove provisioner dependence on rest api

- Documentation/advanced-configuration.md
This adds a section to the advanced configuration documentation page about the `ROOK_REPO_PREFIX` variable.
> Added docs section about ROOK_REPO_PREFIX variable

- Jenkinsfile
- build/run
- tests/README.md
- tests/framework/installer/install_helper.go
- tests/framework/utils/k8s_helper.go
- tests/longhaul/block_on_k8s_test.go
- tests/scripts/kubeadm-install.sh
- tests/scripts/kubeadm.sh
- tests/scripts/minikube.sh
- converting results to junit
- better handling for apt-get install on slaves
- user standard minikube image, now that minikube v0.21.0 and above support cephfs
- update test framework to handle minikube and kubeadm env
> ci updates

- Makefile
- cmd/rook/api.go
- cmd/rook/main.go
- cmd/rook/mds.go
- cmd/rook/mgr.go
- cmd/rook/mon.go
- cmd/rook/operator.go
- cmd/rook/osd.go
- cmd/rook/rgw.go
- pkg/clusterd/join.go
- pkg/util/flags/flags.go
- pkg/util/flags/flags_test.go
- pkg/version/version.go
Fixes #286 
This had made debugging something in the field more difficult recently, so I wanted to knock it off since it's not a difficult fix.
Example start of the logs for an OSD pod:
```
2017-08-24 18:49:08.149736 I | rook: starting Rook v0.5.0-35.g136ce41.dirty with arguments '/usr/local/bin/rook osd'
2017-08-24 18:49:08.149850 I | rook: flag values: --admin-secret=*****, --ceph-config-override=/etc/rook/override.conf, --cluster-name=rook, --config-dir=/var/lib/rook, --data-device-filter=, --data-devices=, --data-directories=, --force-format=false, --fsid=, --help=false, --location=, --log-level=INFO, --metadata-device=, --mon-endpoints=rook-ceph-mon1=10.0.0.236:6790,rook-ceph-mon2=10.0.0.7:6790,rook-ceph-mon0=10.0.0.100:6790, --mon-secret=*****, --node-name=minikube, …
```
> log version, arguments and flags at start up

- Documentation/helm-operator.md
- cluster/charts/rook/templates/deployment.yaml
- cluster/charts/rook/values.yaml.tmpl
added log-level env in rook-operator deployment.yaml with variable .Values.logLevel
I hope this PR is complementary to #938
> Helm chart log-level extension

- pkg/ceph/client/image.go
- pkg/ceph/client/image_test.go
Fixes #942 
- Added simple brackets regex for ListImages with the assumption that stdout contains the relevant information as a json-block
- added test for different log-level
https://play.golang.org/p/fxA5beReir
> Stripping out debug log of rbd command output for ListImages

- Documentation/advanced-configuration.md
First, this depends on the MIN_SIZE parameter of a pool. Second even if the
MIN_SIZE is one this would only hold up to six node cluster. Imagine a nine
node cluster; losing two-thirds of a cluster can lead to a situation where all
replicas of an object are offline. I.e., you can only lose up to two failure
domains, in this case nodes, when you have a replication size of three.
> [doc] Remedy falsehood about losing up to 2/3 of a cluster

- Documentation/advanced-configuration.md
- cluster/charts/rook/templates/deployment.yaml
- cluster/charts/rook/values.yaml.tmpl
- cluster/examples/kubernetes/1.5/rook-operator.yaml
- cluster/examples/kubernetes/rook-operator.yaml
- cmd/rook/operator.go
- pkg/operator/cluster/controller.go
- pkg/operator/mon/health.go
- pkg/operator/mon/mon.go
- tests/framework/installer/install_data.go
- tests/scripts/minikube.sh
- tests/smoke/block_test.go
- tests/smoke/mon_test.go
```
operator/mon: check if node for the mon is not ready and time it out
separately (240s)
```
This is a try to implement a logic to check the node on which the mon(s) are running to take the readyness state of the node into account and use an extra timeout for it.
Tries to implement it a bit like the second point in #957.
The timeout and interval are not yet configurable.
> operator/mon: Use seperate "timeout" for mons if the node is not ready below

- pkg/api/k8s/cluster_handler.go
> rgw: avoid double encoding of certificate secret

- pkg/operator/mon/health.go
Not the other way arround.
***
Oops, I accidentally used the wrong conditional here for the time.
This fixes the condition of the time comparison, as in the commit written, it has to be:
```
Time since the mon has been added to list (duration) <= monOutTimeout (duration)
```
> Fix the condition: Time since added to list <= monOutTimeout

- Documentation/advanced-configuration.md
- Documentation/client.md
- Documentation/development-flow.md
- Documentation/standalone.md
- Documentation/toolbox.md
- Documentation/upgrade.md
Fixes #976 
Easy to read rendered markdown can be found at https://github.com/jbw976/rook/blob/upgrade-guide/Documentation/upgrade.md
> docs: user guide for upgrading a Rook cluster

- Documentation/cluster-crd.md
- cluster/examples/kubernetes/rook-cluster.yaml
- pkg/operator/k8sutil/placement.go
This adds `podAffinity` and `podAntiAffinity` to the placement spec.
Example: Setting the `podAntiAffinity` for mons would allow for having one mon per node and not multiple mons on one node.
**NOTE** `podAffinity` and `podAntiAffinity` feature isn't available in Kubernetes 1.5. The compatiblity is guaranteed as long as the specs aren't used/filled out in the rook cluster spec.
> Add podAffinity and podAntiAffinity to placement spec

- Documentation/cluster-crd.md
- cluster/examples/kubernetes/rook-cluster.yaml
- cluster/examples/kubernetes/rook-tools.yaml
- cmd/rook/api.go
- cmd/rook/mon.go
- pkg/api/k8s/cluster_handler.go
- pkg/ceph/client/image.go
- pkg/ceph/mon/config.go
- pkg/ceph/mon/daemon.go
- pkg/ceph/mon/leader.go
- pkg/operator/api/api.go
- pkg/operator/api/api_test.go
- pkg/operator/cluster/controller.go
- pkg/operator/cluster/types.go
- pkg/operator/mds/mds.go
- pkg/operator/mds/mds_test.go
- pkg/operator/mgr/mgr.go
- pkg/operator/mgr/mgr_test.go
- pkg/operator/mon/health.go
- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
- pkg/operator/mon/spec.go
- pkg/operator/mon/spec_test.go
- pkg/operator/osd/osd.go
- pkg/operator/osd/osd_test.go
- pkg/operator/rgw/rgw.go
- pkg/operator/rgw/rgw_test.go
- pkg/operator/test/client.go
- tests/framework/installer/install_data.go
See rook/rook#561.
***
This hasn't been tested yet as minikube or any other single node clusters won't work as Kubernetes detects which ports are used on host. I'll try to test on a three node cluster to verify the functionality.
Edit: ~~I'm looking at the failed tests.~~ Tests fixed.
> Add hostNetwork option to cluster spec

- cluster/examples/kubernetes/rook-tools.yaml
- images/toolbox/toolbox.sh
- pkg/operator/api/api.go
```
fix rook-api service clusterIP when hostNetwork is used
allow ROOK_API_SERVER_ENDPOINT to be set by user
toolbox: default to rook-api dns name when no k8s service env vars are
given
Added dnsPolicy to rook-tools (K8s required version >1.6)
```
This PR changes/fixes:
1. Fix the rook-api service to be also set to `None` when `hostNetwork: true` is used.
2. Allow the user to set the `ROOK_API_SERVER_ENDPOINT` by env var.
3. The rook-toolbox entrypoint script to fallback to the dns name when no K8s service env vars are given (this happens when `hostNetwork: true` is used).
4. Added the `dnsPolicy: ClusterFirstWithHostNet` to the rook-tools pod. This allows the fallback for `hostNetwork: true` for the dns name of the rook-api service to be used.
> Set rook-api service clusterIP to None when hostNetwork is used

- Documentation/k8s-object.md
- Documentation/object-store-crd.md
- cluster/examples/kubernetes/1.6/rook-object.yaml
- cluster/examples/kubernetes/rgw-external.yaml
- pkg/api/k8s/cluster_handler.go
- pkg/operator/rgw/controller.go
- pkg/operator/rgw/register.go
- pkg/operator/rgw/rgw.go
- pkg/operator/rgw/rgw_test.go
- pkg/operator/rgw/types.go
- tests/framework/clients/object.go
- tests/framework/installer/install_helper.go
- tests/framework/utils/k8s_helper.go
- tests/integration/block_createBlock_api_test.go
- tests/integration/block_createBlock_k8s_test.go
- tests/integration/helm_test.go
- tests/integration/multi_cluster_deploy_test.go
- tests/integration/smoke_test.go
- tests/longhaul/block_test.go
The ObjectStore CRD should be named as such rather than being named `Objectstore` just to pacify deprecated TPRs. Fixes #1010.
> rgw: proper naming for ObjectStore CRD

- Documentation/pool-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/rook-filesystem.yaml
- cluster/examples/kubernetes/rook-object.yaml
- cluster/examples/kubernetes/rook-pool.yaml
- cmd/rookctl/pool/create.go
- cmd/rookctl/pool/create_test.go
- pkg/api/handlers.go
- pkg/api/routes.go
- pkg/ceph/client/crush.go
- pkg/ceph/client/crush_test.go
- pkg/ceph/client/erasure-code-profile.go
- pkg/ceph/client/erasure-code-profile_test.go
- pkg/ceph/client/pool.go
- pkg/ceph/client/pool_test.go
- pkg/ceph/rgw/objectstore.go
- pkg/operator/mds/mds.go
- pkg/operator/mds/mds_test.go
- pkg/operator/pool/controller.go
- pkg/operator/pool/controller_test.go
- pkg/operator/pool/types.go
- pkg/operator/rgw/rgw.go
- pkg/operator/rgw/rgw_test.go
This change allows a failure domain to be set to any value in the crush map. The default is `host`. The recommend setting for erasure coded pools is `osd`. 
Fixes #1002
> crush: set failure domain for pools

- pkg/operator/mgr/mgr.go
See #1048.
Fixes #1048.
Note: the existing tests already test for a replicas of 3.
***
`rook-ceph-mgr0-2792268363-zhznq`:
```
2017-10-09 20:39:52.948648 I | ceph-mgr: 2017-10-09 20:39:52.948122 7f52edac4700  1 mgr.server send_report Not sending PG status to monitor yet, waiting for OSDs
2017-10-09 20:39:53.286555 I | ceph-mgr: 2017-10-09 20:39:53.286450 7f52ef2c7700  1 mgr finish mon failed to return metadata for osd.0: (2) No such file or directory
2017-10-09 20:39:54.306837 I | ceph-mgr: 2017-10-09 20:39:54.306749 7f52ef2c7700  1 mgr finish mon failed to return metadata for osd.0: (2) No such file or directory
2017-10-09 20:39:54.948710 I | ceph-mgr: 2017-10-09 20:39:54.948270 7f52edac4700  1 mgr send_beacon active
2017-10-09 20:39:56.948934 I | ceph-mgr: 2017-10-09 20:39:56.948574 …
```
> Run two MGRs to have one in standby mode

- Documentation/helm-operator.md
Using http based URLs with helm just returns errors when trying to redirect to https. 
````
0:0 ᐅ   helm repo add rook-alpha-test http://charts.rook.io/alpha 
Error: Looks like "http://charts.rook.io/alpha" is not a valid chart repository or cannot be reached: Failed to fetch http://charts.rook.io/alpha/index.yaml : 403 Forbidden
````
> Updated references to charts.rook.io to https

- Documentation/kubernetes.md
- Documentation/upgrade.md
Fixes https://github.com/rook/rook/issues/1050
[skip ci]. Only docs files are changed
> Replacing kubernetes PR link with a link for flexvolume docs

- cmd/rookctl/pool/delete.go
- pkg/api/filesystem_test.go
- pkg/api/object.go
- pkg/api/pool.go
- pkg/api/routes.go
- pkg/ceph/client/filesystem.go
- pkg/ceph/client/filesystem_test.go
- pkg/ceph/client/pool.go
- pkg/ceph/client/pool_test.go
- pkg/ceph/mon/config.go
- pkg/ceph/mon/daemon.go
- pkg/ceph/rgw/objectstore.go
- pkg/ceph/rgw/objectstore_test.go
- pkg/operator/pool/controller.go
- pkg/rook/client/client.go
- pkg/rook/client/pool.go
- pkg/rook/test/mockclient.go
- tests/integration/base_block_test.go
- tests/integration/base_object_test.go
- tests/integration/block_createBlock_k8s_test.go
Currently when a pool, object, or file CRD are deleted, all of their underlying Ceph pools remain in the system. This change will permanently delete the data pools corresponding to the service. Fixes #1001
> Purge data pools when file, object, and pool CRDs are deleted

- tests/scripts/helm.sh
To make it simpler to install stable helm charts in minikube and kubeadm...
[skip ci]
> add helm stable repo to test env

- pkg/api/daemon.go
- pkg/ceph/client/test/mon.go
- pkg/operator/mon/health.go
- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
Fixes #1073 
This overall improves the behavior when a mon isn't in the Ceph mon map anymore.
The mon will be placed in the monOutTimeout list to prevent a mon to be failovered when it is still starting (and simply taking a bit longer than the healthCheck interval).
> operator/mon: health check improvements

- Jenkinsfile
Our most frequent build error is an error about a missing go import. The error is about a different import every time. It is suspected that the error occurs due to the high concurrency on the build machine. This is an experiment to see if the build concurrency does have an impact.
[skip tests]
> Reduce build concurrency for more stable build step

- Documentation/cluster-crd.md
- cluster/examples/kubernetes/rook-cluster.yaml
- pkg/operator/cluster/controller.go
- pkg/operator/cluster/types.go
- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
- pkg/operator/mon/spec_test.go
Fixes #1074.
This allows setting the mon size/replicas by a key in the rook cluster CRD spec. The key is named `monSize`.
***
**Note**: ~~I'm currently testing this change.~~ Tests successful. I set the `monSize: 5` in the cluster CRD and I get:
```
$ kubectl get -n rook po
NAME                              READY     STATUS    RESTARTS   AGE
rook-api-1435667874-gj81r         1/1       Running   0          2m
rook-ceph-mgr0-2792268363-jb2nb   1/1       Running   0          2m
rook-ceph-mgr1-3797254331-x1fj7   1/1       Running   0          2m
rook-ceph-mon0-j467l              1/1       Running   0          2m
rook-ceph-mon1-kw722              1/1       Running   0          2m
rook-ceph-mon2-lj6xz              1/1       Running   0          2m
rook-ceph-mon3-9t7mt              1/1 …
```
> operator/mon: Allow to set the mon size by cluster CRD spec

- tests/scripts/minikube.sh
> fix kube-dns CrashLoopBackOff issue with RBAC enabled minikube

- Documentation/kubernetes.md
In the cleanup instructions on the kubernetes.md, the `rook-system` namespace is deleted by the first instruction since it is declared in the operator.yaml:
`kubectl delete -f rook-operator.yaml`
No need to explicitly delete the rook-agent daemonset or the rook-system namespace.
[skip ci]
> Docs: rook-system is already deleted during cleanup

- cmd/rook/osd.go
- pkg/ceph/client/crush.go
- pkg/ceph/client/crush_test.go
- pkg/ceph/mds/daemon.go
- pkg/ceph/mgr/daemon.go
- pkg/ceph/mon/config.go
- pkg/ceph/mon/config_test.go
- pkg/ceph/osd/agent.go
- pkg/ceph/osd/daemon.go
- pkg/ceph/osd/daemon_test.go
- pkg/ceph/osd/device.go
- pkg/ceph/rgw/daemon.go
The host name in the crush map is set by the `crush location` setting in the config file, rather than a hack to set the `hostname` of the pod. Fixes #1135
> crush: set host properly in the crush map

- Jenkinsfile
- tests/framework/installer/install_data.go
- tests/framework/installer/install_helper.go
- tests/integration/multi_cluster_deploy_test.go
- tests/scripts/kubeadm-install.sh
- tests/scripts/kubeadm.sh
going to run useAllDevices_test.go if the k8s cluster has aditional devices. The test is skipped if there are not additional(raw) devices. 
fix #1039
> adding support for testing with all devices on cluster

- cluster/examples/kubernetes/rook-tools.yaml
- cmd/rookctl/rook/rook.go
- images/toolbox/toolbox.sh
The toolbox should be able to launch and initialize its ceph settings without calling the rook REST api. The mons can be retrieved from the mon endpoints configmap. Thanks @jbw976 for the script help.
> Remove dependence on api service to launch toolbox

- tests/framework/clients/cluster.go
- tests/framework/installer/install_data.go
- tests/framework/installer/install_helper.go
- tests/integration/base_deploy_test.go
- tests/integration/base_file_test.go
- tests/integration/block_createBlock_api_test.go
- tests/integration/block_createBlock_k8s_test.go
- tests/integration/helm_test.go
- tests/integration/multi_cluster_deploy_test.go
- tests/integration/smoke_test.go
- tests/longhaul/base_block_test.go
The e2e tests take a really long time. We have five suites that create and teardown clusters. We need to consolidate these. In the meantime, here are some changes to:
- Run 1 mon instead of 3 in most of the suites
- The multi-cluster test will start the two clusters in parallel
- Tests will cleanup, but not wait for the cleanup to complete.
> Speedup tests

- Gopkg.lock
- Gopkg.toml
- pkg/operator/operator.go
- pkg/operator/provisioner/controller/controller.go
- pkg/operator/provisioner/controller/controller_test.go
- pkg/operator/provisioner/controller/leaderelection/leaderelection.go
- pkg/operator/provisioner/controller/leaderelection/resourcelock/interface.go
- pkg/operator/provisioner/controller/leaderelection/resourcelock/provisionpvclock.go
- pkg/operator/provisioner/controller/volume.go
- pkg/operator/provisioner/provisioner.go
- pkg/operator/provisioner/provisioner_test.go
moved external-storage/libcontroller into rook/rook for now. this helps us have a greater control over versioning it and keeping it updated as Kubernetes changes. The plan is to move it back out once https://github.com/kubernetes-incubator/external-storage/issues/423 is resolved.
> remove dependency on external-storage project

- MAINTAINERS_RULES.md
Responding to a community suggestion this change adds MAINTAINERS_RULES.md which documents the rules and guidelines maintainers are expected to follow.
[skip ci]
> Document the maintainers process

- Documentation/k8s-pre-reqs.md
I personally don't like the suggestion to have a user certificate signed with `O=system:masters`.  It is one of the easiest way to get started, but I think the context is important so I'd like to add a little color to it.
> Clarify the context of suggesting O=system:masters in k8s-pre-reqs.md

- Documentation/cluster-crd.md
- Documentation/common-problems.md
- Documentation/kubernetes.md
- cluster/examples/kubernetes/rook-cluster.yaml
- cmd/rook/agent.go
- cmd/rook/api.go
- cmd/rook/main.go
- cmd/rook/mds.go
- cmd/rook/mgr.go
- cmd/rook/mon.go
- cmd/rook/mon_test.go
- cmd/rook/operator.go
- cmd/rook/osd.go
- cmd/rook/rgw.go
- tests/scripts/minikube.sh
To survive pod and node restarts, the config dir needs to be persisted to the host. As an interim change until we get the full solution on top of the local storage (#796), this change will by default set the `dataDirHostPath` to `/var/lib/rook` so the default configuration will allow for restarts. If `/var/lib/rook` is not valid for the host, the mons will fail to start and the cluster will not initialize. 
If a test cluster is destroyed and a new one brought up in its place, the path on the host must be deleted. Otherwise, the new cluster will fail to start. The mon log will have an error such as the following and enter a crash backoff loop.
```
new mon keyring does not match existing keyring in /var/lib/rook/rook-ceph-mon0/data/keyring
```
Fixes #1155
> Set default dataDirHostPath to /var/lib/rook

- tests/scripts/minikube.sh
- There is a race condition where the k8s api is not finished
registering objects and the script tries to create RBAC objects
- Having the RBAC objects created after the images are copied should
give it enought time for the k8s api to finish registering objects
[skip ci]
> Execute createRBAC function after images are copied

- Documentation/common-problems.md
- Documentation/k8s-filesystem.md
- cmd/rookflex/cmd/mount.go
- pkg/agent/flexvolume/controller.go
- pkg/operator/agent/agent.go
- pkg/operator/mds/mds.go
- If kernel is older than 4.7, a warning message
will be printed in the agent's logs
Fixes https://github.com/rook/rook/issues/1044
> Handle cephfs mount for kernel older than 4.7

- pkg/operator/osd/osd.go
In kubernetes < 1.6.4, it is being mis-treated as true when the flag runAsNonRoot is present regardless of its value, ref. https://github.com/kubernetes/kubernetes/pull/47009
Instead of removing the line, I decided to leave it and comment it out with a little explanation, so we don't trip that again.
Should fix #1209.
Pull request #1197  should also be updated to reflect this.
> Don't set runAsNonRoot explicitly when it is false.

- build/makelib/golang.mk
dep ensure blindly updates the whole vendor tree causing everything to be rebuilt. This workaround will only call dep ensure if the .lock file changes or if the vendor dir is non-existent.
Addresses #1177
> build: speedup calls to dep ensure

- cluster/charts/rook/values.yaml.tmpl
- cluster/examples/kubernetes/1.5/rook-operator.yaml
- cluster/examples/kubernetes/rook-operator.yaml
- design/mon-health.md
- pkg/agent/flexvolume/controller.go
- pkg/agent/flexvolume/manager/ceph/manager.go
- pkg/ceph/client/mon.go
- pkg/ceph/client/test/mon.go
- pkg/operator/mon/health.go
- pkg/operator/mon/health_test.go
- pkg/operator/mon/mon.go
- pkg/operator/mon/mon_test.go
- pkg/operator/mon/util.go
Fixes #1193 and fixes #961
***
This adds a logic to the health check which checks if more than one mon is on one node. If one or more mons are on a node, one mon will be failovered to an available node.
This prevents single point of failures in cases for example when only three nodes are used for mons and one fails and comes back ready. When the third node appears again as "ready", the single point of failure is then removed by failovering one of mons to the third(/new) node.
***
**Edit**: This adds two checks. One for checking if there runs more than one mon on one node. Second is for checking that the nodes the mon(s) run on are still valid after the `placement` Cluster CRD spec.
> Failover mon when there is more than one mon on one node

- pkg/operator/provisioner/provisioner.go
This is a rather noisesome way of checking something which will only
happen during legacy conversion, so this may not be a desirable patch.
Fixes #1252
> operator: add existence checks for FlexVolume spec on Delete

- pkg/operator/provisioner/provisioner.go
Backports the fix for #1252 to the release-0.6 branch.
(cherry picked from commit 39e68a3c2b420f0b8b1abe46c101f966297a1a66)
> Add existence checks for FlexVolume on Delete

- Documentation/k8s-object.md
Store name is required to create a user or get environment variables command via toolbox.
> Create User / Env Vars missing store name

- Documentation/client.md
The client walkthrough was missing some new parameters in 0.6. Fixes #1185 
[skip ci]
> Add replica count param to client walkthrough

- cluster/examples/kubernetes/rook-filesystem.yaml
- cluster/examples/kubernetes/rook-object.yaml
The sample yaml files should work in all deployments by default, in particular where there is only a single osd
[skip ci]
> Default pool size for a single osd

- pkg/api/daemon.go
- pkg/operator/mon/mon.go
> api: recreate mon endpoint watcher when the result channel is closed

- tests/framework/objects/environment_manifest.go
found the issue after looking back at the commits and finding the commit the broke testify.m flag.  The current refator fixed the issue and running single test from a suite should be enabled again.
fix #1262 [smoke only]
> fix testify.m flag

- Documentation/k8s-monitoring.md
- cluster/examples/kubernetes/monitoring/prometheus.yaml
- cluster/examples/kubernetes/monitoring/service-monitor.yaml
The prometheus manifests are outdated and dont work with the latest kubernetes.
Upgrading it to work.
[skip ci]
> Updating outdated monitoring docs and manifest

- cluster/charts/rook/templates/deployment.yaml
- cluster/examples/kubernetes/rook-operator.yaml
- pkg/operator/k8sutil/rbac.go
- pkg/operator/k8sutil/rbac_test.go
Fixes https://github.com/rook/rook/issues/1221
(cherry picked from commit 735d2e71558ddde16248adfdfd31bd4e53be18f3)
> Not create rbac roles on k8s cluster that have rbac disabled.

- .github/ISSUE_TEMPLATE.md
The first part will be to add an issue template.
The rendered version of the template can be found here: https://github.com/galexrt/rook/blob/feature/1307/.github/ISSUE_TEMPLATE.md
[skip ci]
> Added GitHub issue template

- tests/framework/installer/install_helper.go
- tests/framework/objects/environment_manifest.go
test
Test flags in integration framework were being declared but not initialized. Moved flags.Parse() out of init function so both test flags and global flags(testify.m) are declated and initialized correctly. 
[smoke only]  fix #1316
> test: fix integration test flags initilization

- pkg/operator/cluster/mgr/mgr.go
Reverts rook/rook#1060.
This PR is required for #1154 as discussed in the rook meeting.
Fixes #1048.
> Revert "Run two MGRs to have one in standby mode"

- cluster/charts/rook/templates/NOTES.txt
NOTES instructs users to use the command `kubectl --namespace default get pods -l "name=rook-operator"`. The pods do not have a `name` label but an `app` label.
> Helm Chart: NOTES.txt: Fix label from name to app

- pkg/operator/cluster/osd/osd.go
When having a simple misconfiguration or a  unintentional indentation issue on the cluster resource the OCD controller right now fails without any further logs. This PR at least adds a warning on case no nodes are set and UseAllNodes is false.
> Add a warning to OSC cluster operator when no nodes are specified

- Documentation/advanced-configuration.md
Removes table of contents entry of section that has already been removed.
[skip ci]
> Remove ROOK_REPO_PREFIX doc toc entry

- .github/PULL_REQUEST_TEMPLATE.md
This is the second part of #1307.
The rendered version of the template can be found here: https://github.com/galexrt/rook/blob/feature/1307/.github/PULL_REQUEST_TEMPLATE.md
[skip ci]
***
Resolves #1307.
> Added GitHub pull request template

- Documentation/cluster-crd.md
- cluster/examples/kubernetes/rook-cluster.yaml
- pkg/operator/cluster/ceph/mon/spec.go
Clarify docs for mon Pod(Anti)Affinity
Remove Mon `Pod(Anti)Affinity` which when used, potentially breaks our own placement logic that uses `NodeSelector` to place mon Pods.
Relates #1369
Checklist:
@travisn I'm not sure if this should be added to the pending release notes and when under which category.
> Removed mon Pod(Anti)Affinity

- cmd/rook/operator.go
The log entries written by the kubernetes layer all show a prefix `ERROR: logging before flag.Parse`. This is fixed by simply initializing the flag parsing when the operator starts.
Resolves #1376
> Initialize flag parsing for the logs

- Documentation/k8s-monitoring.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/monitoring/service-monitor.yaml
- images/ceph/Dockerfile
- images/rook/Dockerfile.base
- pkg/daemon/ceph/client/mgr.go
- pkg/operator/cluster/ceph/mgr/mgr.go
- pkg/operator/cluster/ceph/mgr/mgr_test.go
Fixes #1111.
***
This **a)** create a service in front of the Ceph mgrs and **b)** enable the mgrs Prometheus module to provide prometheus metrics (instead of the rook-api).
This hasn't been tested yet. Will do in the next few days.
**ToDo**:
/cc @jpds
> Enable Prometheus metrics on Ceph mgr

- Documentation/cluster-crd.md
- Documentation/kubernetes.md
- Documentation/upgrade.md
- design/resource-constraints.md
- design/upgrade.md
- tests/framework/installer/install_data.go
The versionTag was removed in a previous PR, but the docs were not updated. 
Resolves #1378 
[skip ci]
> Remove versionTag from the cluster crd docs

- cluster/charts/rook/templates/deployment.yaml
- cluster/charts/rook/values.yaml.tmpl
Sometimes it is neccessary to override the volume plugin directory, mostly as a temporary solution.  See issue #1330 for an example use case. This pull requests includes this ability into the Helm chart of Rook.
> helm: make FLEXVOLUME_DIR_PATH configurable via values.yaml

- Documentation/flexvolume.md
This makes Rook work with Coreos on 1.9+
Partially addresses https://github.com/rook/rook/issues/1330
[skip ci]
> Adding documentation to specify a non-custom flexvolume dir on 1.9

- images/image.mk
ubuntu:zesty is longer supported and now that we are not building ceph from source xenial is more appropriate given that its LTS. 
Resolves #1417
Checklist:
> images: switch to ubuntu xenial LTS

- pkg/operator/cluster/ceph/mon/health_test.go
- pkg/operator/cluster/ceph/mon/mon.go
- pkg/operator/cluster/ceph/mon/mon_test.go
- pkg/operator/cluster/ceph/mon/spec.go
- pkg/operator/test/client.go
The kubernetes node has both a `name` and a `hostname` label. Rook was assigning node affinity of the mon pods based on the `name`. In some environments such as AWS where the `hostname` is different, this is incorrect. The `hostname` label of the node must match the node affinity of the mon pod. The `name` is still used internally as an immutable key. The `hostname` is only used where the node label is required.
@dgonzalezruiz thanks for providing the basis for these changes in #1289! This just makes a few edits to that change. I assumed you were busy since we hadn't heard from you for a while and wanted to unblock some people on this.
Resolves #1264
> Mon affinity to nodes based on correct hostname

- Documentation/README.md
- Documentation/block.md
- Documentation/development-flow.md
- Documentation/helm-operator.md
- Documentation/helm.md
- Documentation/quickstart.md
- Documentation/storage.md
The docs now have the `--version` flag for installing a master helm chart. Other clarifications to documentation were also added while reading through the install flow, such as readability for the Quickstart guide and more mentions of block, object, and file storage.
Resolves #944
Checklist:
[skip ci]
> Docs update for master helm chart

- tests/README.md
- tests/framework/installer/install_helper.go
- tests/framework/objects/environment_manifest.go
- tests/framework/utils/k8s_helper.go
- tests/framework/utils/mysql_helper.go
- tests/longhaul/base_block_test.go
- tests/longhaul/base_object_test.go
- tests/longhaul/block_test.go
- tests/longhaul/block_with_fencing_test.go
- tests/longhaul/longhaul_util.go
- tests/longhaul/object_test.go
- tests/pipeline/Jenkinsfile.longhaul
Description of your changes: 
- added new tests flag `--load_size` to control amount of data being written -S,M or L(less than 1M,1M and 10M respectively)
- added new test flag `--enable_chaos` - if this flag is present, random pods in rook cluster will be killed peridiocally
- update longhaul test pipeline (added new flags)
- updated docs
fix #1216
> adding test flags to control load size and test rook resilience 

- cluster/examples/kubernetes/monitoring/service-monitor.yaml
Fix the metrics path in the Prometheus ServiceMonitor.
The metrics were previously available at `/` and `/metrics`, which has changed now to only `/metrics`.
[skip ci]
> monitoring: Use new metrics path

- Documentation/pool-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/rook-pool.yaml
- pkg/apis/rook.io/v1alpha1/pool.go
- pkg/apis/rook.io/v1alpha1/types.go
- pkg/daemon/api/filesystem_test.go
- pkg/daemon/api/handlers_test.go
- pkg/daemon/api/object_test.go
- pkg/daemon/ceph/client/crush.go
- pkg/daemon/ceph/client/erasure-code-profile.go
- pkg/daemon/ceph/client/erasure-code-profile_test.go
- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
- pkg/daemon/ceph/rgw/objectstore.go
- pkg/model/pool.go
- pkg/operator/pool/controller.go
- pkg/operator/pool/controller_test.go
- tests/integration/block_createBlock_api_test.go
The performance characteristics of a pool depend on the osds included in the crush root. Now a crush root other than `default` can be specified in the pool spec. The crush root can be specified in the Pool, ObjectStore, or Filesystem CRDs where the pool spec is required. Thanks @dgonzalezruiz for providing the basis for this in #1288
Configuration of the CRUSH hierarchy is necessary with the `ceph osd crush` commands in the toolbox before creating a pool with the non-default root.
Resolves #1204
Checklist:
> Allow setting crush root on the pool

- design/security-model.md
This is an attempt to redefine the way rook uses service account and namespaces.
#1389 #1314 #1337 #1348 #1211 
Checklist:
[skip ci]
/cc @travisn @jbw976 @kokhang @lukeweber @ichekrygin @leseb @liewegas
> design: reworked security model

- Gopkg.lock
`dep ensure` was showing that a new hash was needed for the dep tool. This was causing the builds to show as dirty on jenkins
Resolves #1428
> build: update dep ensure hash

- Documentation/helm-operator.md
- cluster/charts/rook/templates/clusterrole.yaml
Description of your changes:  Updates helm chart files to ensure the operator has the permissions needed to complete the remove node flow (specifically updating replicasets).
Resolves #1447 
Checklist:
> helm: give operator permissions for removing storage nodes

- pkg/operator/cluster/ceph/osd/config/config.go
The imports for the capnslog are expected to be in `github.com/coreos/pkg/capnslog` instead of `github.com/coreos/capnslog`. This also appears to be causing dirty builds to be published since `go dep` is adding the parent package to the lock file.
> Consistent capnslog log import path

- pkg/daemon/api/object.go
- pkg/daemon/api/object_test.go
- pkg/daemon/ceph/rgw/daemon.go
- pkg/operator/cluster/ceph/osd/config/config.go
- pkg/operator/object/ceph/rgw.go
- pkg/operator/object/ceph/rgw_test.go
There were a couple of incorrect default rgw settings:
- The `rgw dns name` should not be set. Other configuration needs to be finalized as related to #1349 for this setting to be effective.
- The host name returned by the api should include the namespace suffix so clients in other namespaces will be able to connect to rgw.
This is related to #1349 although does not implement the fix.
> Correct rgw host name and set blank dns name

- pkg/daemon/ceph/client/mon.go
- pkg/daemon/ceph/client/mon_test.go
Ceph commands do not require arguments for the ceph.conf and keyring if the config is found under /etc/ceph/ceph.conf. All the rook pods would ideally follow this pattern so the arguments are simpler to read in the logs, this is just the first step.
> Skip ceph config args for default ceph cluster

- INSTALL.md
- images/image.mk
There is a deprecation warning in the `armhf` org on DockerHub.
> The armhf organization is deprecated in favor of the more-specific
arm32v7 and arm32v6 organizations, as per
https://github.com/docker-library/official-images#architectures-other-than-amd64.
Please adjust your usages accordingly.
Required changes to Rook:
`armhf` -> `arm32v7`
`aarch64` -> `arm64v8`
Install documentation has been updated as well, and it looks like my editor stripped a few trailing spaces at the same time.
Resolves #1419
> WIP: Update arm builds to more specific variants

- pkg/clusterd/disk.go
- pkg/clusterd/disk_test.go
- pkg/util/sys/device.go
This PR adds compatibility to clusters using raw devices that are decrypted at boot time with dmcrypt.
> OSD: Support crypt type devices

- pkg/operator/cluster/ceph/mgr/mgr.go
- pkg/operator/cluster/ceph/osd/osd.go
- pkg/operator/cluster/ceph/osd/osd_test.go
During deletion of the cluster CRD we expect all the k8s artifacts to be cleaned up for the cluster. An osd configmap and a mgr service had been missed previously, so this finishes that cleanup process. Now the only remaining cleanup between deleting and re-creating a cluster should be the dataDirHostPath. Resolves #1438
> Set owner reference on remaining components

- pkg/operator/agent/agent.go
- pkg/operator/cluster/ceph/osd/pod.go
- pkg/operator/object/ceph/rgw.go
- Daemonsets deployed by rook currently use the "delete" update
controller. Which means the pods have to be manually deleted
before being upgraded.
- Using the update controller will make daemonset behave like
deployments when it comes to upgrade.
Partially fixes https://github.com/rook/rook/issues/997
> Make daemonset use rolling update controller

- cmd/rook/main.go
- cmd/rook/operator.go
- cmd/rookflex/main.go
The flags parsing needs to be initialized in the agent to avoid an error printing in the logs. This change ensures it is initialized everywhere the rook binary runs and also the flex driver. Resolves #1414
> Init flags parsing in the agent

- Documentation/k8s-pre-reqs.md
- Documentation/quickstart.md
- Documentation/teardown.md
The cleanup instructions have been buried in the quickstart and overlooked by many people needing support. This raises the visibility of the teardown instructions and also adds some troubleshooting around cleanup of the crd finalizer when necessary.
Resolves #1488
Checklist:
[skip ci]
> Add cleanup instructions for the CRD finalizer

- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/daemon/ceph/osd/device.go
- pkg/operator/cluster/ceph/osd/config/scheme.go
- pkg/operator/cluster/ceph/osd/osd.go
- pkg/operator/cluster/ceph/osd/pod.go
- pkg/operator/cluster/ceph/osd/pod_test.go
* When marking an OSD device to be removed, ensure the correct data partition name is used.
* If watching the osd orchestration status map fails, ensure the loop is broken out of so a new watcher can be created.
* Log the osd device/dir mapping structures in a more friendly way.
Resolves #1461 
Checklist:
> Fixes for filestore OSD removal

- cmd/rook/rgw.go
- pkg/operator/object/ceph/rgw.go
- pkg/operator/object/ceph/rgw_test.go
- tests/integration/base_object_test.go
Description of your changes: This makes the RGWs commandline tool use the HOSTNAME environment variable, which has a randomized suffix, so the need of different name for different gateways is true.
Resolves #1483
> RGWs: Make multiple instances do not interfere with MGRs

- cluster/charts/rook/templates/wait-on-resources-job.yaml
- cluster/charts/rook/values.yaml.tmpl
Adds a post-install hook to the rook-operator chart to ensure all CRD\TPR resources are available for use before returning.
This greatly helps automated deployment solutions not require 'sleep\wait' logic between applying the operator chart & configuring any rook clusters.
Resolves #1511 
NOTE: I didn't think this change is worth putting in documentation, but would be happy to add a sentence if required.
Checklist:
> Ensure Helm waits for CRD\TPRs to be available before returning

- pkg/operator/cluster/ceph/mon/health.go
- pkg/operator/cluster/ceph/mon/mon.go
- pkg/operator/cluster/ceph/mon/mon_test.go
```
```
***
This fixes the assignment of the `PublicIP` for a new spawned mon during `failoverMon()`.
From the code logic this should fix the issue, but I'm going to test this in minikube soon to 100% verify the fix.
Resolves #1548
Checklist:
> Fix assignment of node address to mon in failover

- cluster/charts/rook/templates/wait-on-resources-job.yaml
Description of your changes: Ensures we have non-empty values for Kubernetes Major & Minor versions before using them to wait for TPR\CRD resources to become available.
Discussed in #1517
> Skips wait in chart when K8S version unavailable

- cluster/charts/rook/templates/wait-on-resources-job.yaml
Instead of matching a specific Kubernetes version (which seems to differ by environment), request specific API support and use that.
Resolves #1567
> Check for supporting API instead of specific K8S version

- cluster/charts/rook/templates/deployment.yaml
Fixes this error:
Error: UPGRADE FAILED: Deployment.apps "rook-operator" is invalid: spec
.template.metadata.labels: Invalid value:
map[string]string{"chart":"rook-0.7.1", "app":"rook-operator"}:
`selector` does not match template `labels`
See also: https://github.com/kubernetes/helm/issues/2494
Checklist:
> Remove chart version from deployment selector to allow upgrades

- Gopkg.lock
Cleaning the vendor directory and building results in a changed Gopkg.log. This results in a `dirty` build coming out of master since a file has been modified on the build machine.
> Remove obsolete packages from go dependencies

- Documentation/cluster-crd.md
- cluster/examples/kubernetes/rook-cluster.yaml
- cmd/rook/osd.go
- pkg/daemon/ceph/osd/agent.go
- pkg/daemon/ceph/osd/agent_test.go
- pkg/operator/cluster/ceph/osd/config/scheme.go
Bluestore on directories is only meant to be a test scenario during development and not meant to be used in production. The default store type is now dynamic: bluestore is the default for devices and filestore is the default for directories.
If the store type is specified explicitly in the crd, the setting will override the default.
Resolves #1463
Checklist:
> Bluestore is the default for devices and filestore for dirs

- tests/scripts/minikube.sh
If the ip address of the host is not the default `192.168.99.100`, the minikube environment will be fraught with dns and other random issues that trace back to setting the ip address to the wrong thing at startup. The integration tests no longer use NodePort for the external rgw service or api service, so we can disable this to unblock the unsuspecting minikube user.
[skip ci]
> Don't set the minikube kubelet ip address

- Documentation/filesystem.md
The old link doesn't work.
[skip ci]
> Fixing the link to kubernetes registry

- Documentation/common-issues.md
- Documentation/toolbox.md
- Documentation/tools.md
- PendingReleaseNotes.md
- pkg/daemon/agent/flexvolume/server.go
- pkg/daemon/ceph/mon/config.go
The ceph tools are already found in all the rook pods. However, they were not easily accessible because the config files were found in non-default paths that are inconvenient to track down. Now whenever the config is written, it is also copied to the default location `/etc/ceph` so the tools can run without any arguments. This is a convenience for troubleshooting so you don't have to load the toolbox. It does have the following issues:
- The pods do not update the config when mons failover. The config is only generated at pod startup, so the mons could be outdated and cause the commands to fail. The operator pod, however, will always be up to date
- If there is more than one cluster, the operator pod will have default config pointing at only one of the clusters, which will be …
> Run ceph tools from any rook pod

- pkg/operator/cluster/ceph/mon/health.go
* Log a info message when a mon that was in timeout is back in quorum.
* Log a warning when a mon has exceeded the out timeout and will be failovered.
Checklist:
> Log when mon is back in quorum and exceeded timeout

- cluster/charts/rook/templates/deployment.yaml
Correct definition of serviceAccountName already provided on the last lines of deployment.yaml
> Remove duplicate of serviceAccountName definition

- Documentation/common-issues.md
- PendingReleaseNotes.md
- pkg/util/exec/error.go
Description of your changes: In the `Error()` function for the `CommandError` type, include any output from stderr if the underlying error type is an `os/exec.ExitError`.  This will make error messages much more useful instead of losing stderr.
Also include a common issue entry for the behavior in #1502, which we've seen users hit recently.  Note that the new common issue entry has the new error output that includes stderr, making this issue much easier to troubleshoot.
Resolves #1612 
Checklist:
> include stderr output in CommandError.Error() output

- tests/framework/utils/helm_helper.go
`helm install` command slips into a perpetual loop if `install` routine fails (for any reason).
Remove retry loop from `helm_helper.go` install routine.
Rationale: If/when `install` fails there is a very high probability that all subsequent install attempts will fail as well. So far I have encountered a couple of times when `helm install` would fail, both dealing with invalid install configurations (wrong RBAC, duplicated resource, etc), i.e. nonrecoverable failures.
Resolves #1620 
Checklist:
> Remove RetryLoop on error from helm install.

- Documentation/teardown.md
- PendingReleaseNotes.md
- cluster/charts/rook/templates/clusterrole.yaml
- cluster/charts/rook/templates/resources.yaml
- cluster/examples/kubernetes/1.6/rook-operator.yaml
- pkg/operator/operator.go
- tests/framework/installer/install_data.go
- tests/framework/installer/install_helper.go
- tests/scripts/minikube.sh
Currently, `rook` CRD's are created during `rook-operator` initialization phase. 
This requires for `rook-operator` **ServiceAccount** to have permissions to manipulate [`get`, `list`, `watch`, `create`, `delete`] on `customresourcedefinitions`, which is a ClusterRole/RoleBinding scope. 
By moving `CRD` definitions into a Kubernetes manifest file we can avoid granting `rook-operator` ClusterScope permissions for `customresourcedefinitions` resource.
This work is related to: #1412
Checklist:
> Refactor Rook Operator CRD Initialization

- Documentation/object.md
- cluster/examples/kubernetes/rgw-external.yaml
Fix object storage documentation and kubernetes example
to reflect usage of S3 API and port 80.
Signed-off-by: jaa127 <jaa@sn127.fi>
[skip ci]
> docs: fix object storage docs and kubernetes example

- ROADMAP.md
Based on the community discussion this morning, here are the updates to the rook roadmap, primarily focusing on 0.8.
- no more need for api aggregation (@jbw976)
- moving CI to CNCF solution is independent of milestones
- clarification on least privileged with the improved security model
- shutdown/restart will be handled at the issue level, instead of in the roadmap. There isn't a clear blocking issue.
- mimic support moved to 0.9
[skip ci]
> Update the rook roadmap for 0.8

- tests/scripts/minikube.sh
Set the default version of k8s to be launched by the minikube test script to 1.10.0 rather than 1.9. Does not affect the integration tests. A next step will be to enable 1.10 in jenkins tests per #1623
[skip ci]
> Set default k8s version for minikube to 1.10.0

- Documentation/advanced/recover-mon-quorum.md
For the case where the mons lose quorum, these instructions will make it possible to restore the health of the cluster.
These instructions are in the `design` folder instead of the `Documentation` folder for now because they are intended for advanced users and it is not expected to be a normal usage for the mainline docs. When we have more docs around advanced scenarios, we could add to the documentation, but it didn't feel like we are ready for that yet.
[skip ci]
> Instructions for mon injection

- pkg/daemon/agent/flexvolume/attachment/tpr.go
- pkg/daemon/agent/flexvolume/controller.go
- pkg/operator/agent/agent.go
- pkg/operator/k8sutil/pod.go
- pkg/operator/provisioner/controller/controller.go
- pkg/operator/provisioner/controller/controller_test.go
- pkg/operator/provisioner/controller/leaderelection/resourcelock/provisionpvclock.go
- tests/framework/utils/k8s_helper.go
- tests/integration/smoke_test.go
Signed off by: Tony Allen tony@allen.gg
This patch replaces all of the Go Client invocations of "Core()" with "CoreV1()".
Resolves #1381
> Replace Core() with CoreV1().

- pkg/operator/agent/agent.go
Currently when the rook-operator flexvolume directory is updated the rook-agent has to be manually deleted and the operator restarted again for the rook-agent DaemonSet to be started with the correct flexvolume directory.
This makes a bit more convenient for users when they have used the wrong flexvolume directory path on the first operator start.
Checklist:
> operator: Update rook-agent DaemonSet if it already exists

- build/makelib/golang.mk
golang dep release v0.4.1 version on Jan 25 [1], this PR
bump its version from v0.3.2 to the latest version.
[1] https://github.com/golang/dep/releases
Resolves #
Checklist:
> Bump golang dep to v0.4.1 version

- Makefile
- build/makelib/golang.mk
- images/image.mk
This PR is used to support native build of the rook binaries and container images on arm64 system. After this PR is applied, we can build all the binaries and images for arm64 with `make -j4` command.
Resolves #1643 
Checklist:
> Native build support on AArch64

- cmd/rook/operator.go
- pkg/operator/agent/agent_test.go
- pkg/operator/cluster/ceph/osd/osd.go
- pkg/operator/k8sutil/pod.go
- pkg/operator/k8sutil/pod_test.go
The operator and osd pods need to know information about the container that they are running in such as the version of the image. Rook assumed pods were running with a single image, however this doesn't work with Istio which injects other containers to the pods for monitoring. This will allow multiple containers to be running in the rook pods. Rook does require that the container names are a constant name in order to find them. The operator pod must have a `rook-operator` container and the osd pod must have a `rook-ceph-osd` container.
Resolves #1633, #1638
> Allow multiple containers in rook pods

- Documentation/monitoring.md
- pkg/operator/cluster/ceph/mgr/mgr.go
- pkg/operator/cluster/ceph/mgr/mgr_test.go
This allows users to scrape their ceph-mgr deployment without being
forced to use the Prometheus operator
Resolves #
Checklist:
> Add standard Prometheus annotations to mgr deployment

- Documentation/common-issues.md
- Documentation/filesystem.md
- cluster/examples/kubernetes/rook-storageclass.yaml
- cmd/rookflex/cmd/mount.go
- pkg/daemon/agent/flexvolume/controller.go
- pkg/daemon/agent/flexvolume/controller_test.go
- pkg/daemon/agent/flexvolume/manager/ceph/manager.go
- pkg/daemon/agent/flexvolume/manager/ceph/manager_test.go
- pkg/daemon/agent/flexvolume/types.go
- pkg/operator/provisioner/provisioner.go
- pkg/operator/provisioner/provisioner_test.go
- tests/framework/installer/test_data.go
- tests/integration/block_createBlock_k8s_test.go
- tests/longhaul/base_block_test.go
cluster name and namespace are required to match.
clusterName still works for backward compatiblity
Signed-off-by: Rohan Gupta <rohanrgupta1996@gmail.com>
Resolves #1502
Checklist:
> updated storage class parameter clusterName to clusterNamespace

- Documentation/advanced/recover-mon-quorum.md
- Fix a typo in the keyring path in the `advanced/recover-mon-quorum.md` docs
Checklist:
[skip ci]
> Fix keyring typo in `recover-mon-quorum.md` docs

- pkg/operator/cluster/ceph/mon/health.go
- pkg/operator/cluster/ceph/mon/health_test.go
```
```
Start new mons when there are less in the mon map than wanted by the user `monCount`, but "only" when all other health checks go through fine.
Checklist:
> Start new mons when there are less in the mon map

- Documentation/disaster-recovery.md
- Documentation/tools.md
The TOC was unexpectedly showing a top-level topic. This puts the topic under Tools in the TOC and add missing links to the main Tools page.
Resolves #1682
Checklist:
[skip ci]
> docs: correct the toc hierarchy for the topic on restoring quorum

- INSTALL.md
- Added golang to the build tools.
I started setting up the rook build infrastructure and running `make` resulted in:
```cli
vagrant@ubuntu-xenial:~/rook$ make
/bin/bash: go: command not found
/bin/bash: go: command not found
/bin/bash: go: command not found
/bin/bash: go: command not found
```
Checklist:
> documentation: added golang to buildtools

- cmd/rook/discover.go
- cmd/rook/main.go
- pkg/clusterd/context.go
- pkg/clusterd/disk.go
- pkg/clusterd/disk_test.go
- pkg/daemon/ceph/osd/agent_test.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/daemon/ceph/osd/device.go
- pkg/daemon/ceph/osd/device_test.go
- pkg/daemon/discover/discover.go
- pkg/daemon/discover/discover_test.go
- pkg/operator/cluster/ceph/mon/util.go
- pkg/operator/cluster/ceph/osd/osd.go
- pkg/operator/discover/discover.go
- pkg/operator/discover/discover_test.go
- pkg/operator/k8sutil/rbac.go
- pkg/operator/k8sutil/rbac_test.go
- pkg/operator/operator.go
- pkg/util/sys/device.go
- pkg/util/sys/device_test.go
- pkg/util/sys/parse.go
- pkg/util/sys/parse_test.go
- tests/framework/utils/helm_helper.go
- tests/integration/base_deploy_test.go
- tests/integration/multi_cluster_deploy_test.go
First step following up #1563. This PR implements the device discovery part. It creates the discovery daemon and scans the devices. Provisioning and rest will come in next PR.
@travisn @jbw976 
Resolves #1655
Checklist:
> add device discovery daemon

- cmd/rookflex/cmd/root.go
- pkg/daemon/agent/agent.go
- pkg/daemon/agent/flexvolume/controller.go
- pkg/daemon/agent/flexvolume/server.go
- pkg/daemon/agent/flexvolume/server_test.go
- pkg/operator/provisioner/provisioner.go
- pkg/operator/provisioner/provisioner_test.go
- tests/framework/utils/k8s_helper.go
- tests/integration/base_file_test.go
Multiple rook system namespaces cannot be currently run because of the conflict between using the same flex driver. This change creates a driver name based on the namespace to avoid that conflict. For backward compatibility, the agent will also watch the unix socket for the old driver name (rook).
Resolves #1701
Checklist:
> Base flex driver name on the namespace

- INSTALL.md
- Makefile
- build/run
AArch64 platform doesn't support the `build.all` command due to the issue of `hypriot/qemu-register` on arm64 system, so we disable this kind of 'cross' build on AArch64 platform.
Resolves #
Checklist:
- [* ] Documentation has been updated, if necessary.
> Disable the 'cross' build on AArch64

- Jenkinsfile
- tests/framework/clients/filesystem.go
- tests/framework/clients/object.go
- tests/framework/installer/install_helper.go
- tests/framework/utils/k8s_helper.go
- tests/integration/base_block_test.go
- tests/integration/base_deploy_test.go
- tests/integration/base_file_test.go
- tests/integration/block_createBlock_k8s_test.go
- tests/integration/helm_test.go
- tests/integration/multi_cluster_deploy_test.go
- tests/integration/smoke_test.go
- tests/integration/zblock_mount_unmount_test.go
- tests/longhaul/base_block_test.go
- tests/longhaul/block_test.go
- tests/longhaul/block_with_fencing_test.go
- tests/longhaul/object_test.go
- tests/scripts/kubeadm.sh
Add support for K8s 1.10 in the jenkins integration tests. Given some changes in shutdown behavior, this had been dependent on #1701. A number of test improvements to help troubleshoot #1701 are also included in this PR.
Resolves #1623
Checklist:
> Support 1.10 in the integration tests

- Documentation/filesystem.md
- cluster/examples/kubernetes/rook-operator.yaml
- pkg/daemon/ceph/client/filesystem.go
- pkg/daemon/ceph/mds/filesystem.go
- pkg/operator/file/ceph/mds_test.go
Multiple file system support is still considered experimental in Ceph.
Disabling that as default in rook until such time it is production
ready.
A small code cleanup in filesystem file
Resolves #1720
Checklist:
> Ceph MDS: Control multi file system creation

- pkg/daemon/ceph/agent/flexvolume/controller.go
- pkg/operator/ceph/provisioner/provisioner.go
- pkg/operator/ceph/provisioner/provisioner_test.go
This patch attempts to address the issue where an operator restart
would result in failures to delete any PVs.
Resolves: #1721
> Fix PV delete failure over operator restarts

- tests/scripts/multi-node/build-rook.sh
Recent change to support multiple backends changed the docker image name
but missed the change in the test script. This patch addresses that
issue.
[skip ci]
> Rook test script fix for missed name changes from multiple storage type support

- pkg/operator/ceph/cluster/osd/pod.go
- pkg/operator/ceph/cluster/osd/pod_test.go
Description of your changes: This change mounts /run/udev in the container if any devices are mounted so that udevadm can provide enough information to correctly setup the OSDs.
Resolves #1738
The setup I have tested this on:
OS (e.g. from /etc/os-release): RHEL 7.3
Kernel (e.g. uname -a): 3.10.0-514.6.1.el7
Kubernetes version (use kubectl version): 1.9.3
Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): open source on-prem
Checklist:
> Fix udevadm providing incomplete info by mounting /run/udev

- design/nfs.md
Design documentation for the feature request #1551 
[skip ci]
> Design document for adding NFS as storage backend

- pkg/clusterd/disk.go
- pkg/daemon/ceph/osd/agent.go
The device and partition uuid was not being parsed after an osd pod was restarted. This resulted in new osd's being created on top of the same device and wiping out the old osds. It is a regression from the switch to udevadm a couple weeks ago.
The issue was that the device or partition UUID are found in three different properties from `udevadm` depending on the device: `ID_FS_UUID`, `ID_PART_TABLE_UUID`, or `ID_PART_ENTRY_UUID`. Only the first property was being parsed.
To see this issue, run the following command for different devices and partitions. In minikube, I see the different properties for sda, sdb, and sdb1.
```
udevadm info --query=property /dev/sdb
```
Resolves: #1754 
Checklist:
> Device discovery needs to load part uuid after restart

- PendingReleaseNotes.md
- build/codegen/codegen.sh
- build/codegen/header.txt
```
Update codegen header.txt to current year
Fixes #1664
```
This fixes issues with GNU and allows for GNU and BSD sed versions to work.
Resolves #1664
Checklist:
[skip ci]
> Make sed usage compatible with GNU and BSD

- Documentation/filesystem.md
- cluster/examples/kubernetes/ceph/kube-registry.yaml
This adds a one liner comment to mention that the `path` for filesystem must exist otherwise the mount will fail because the path/directory on the filesystem does not exist.
Resolves #
Checklist:
[skip ci]
> Clarify that path must exist for filesystem mount to succeed

- Documentation/helm-operator.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml.tmpl
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/discover/discover.go
* Document the discover DaemonSet toleration env vars in the helm chart and `operator.yaml`.
* Updates the discover DaemonSet when it already exists, this allows the toleration env vars to be changed "on the fly" of the operator and then directly rollout the change to the DaemonSet as already with the rook-agent DaemonSet.
Resolves #1732.
Checklist:
> Document discover DaemonSet toleration key

- Documentation/flexvolume.md
Make it clearer for which Kubernetes version the env var needs to be added to the Rook operator.
Also changed wording a bit so it is (hopefully) clearer to go through all sections that are applicable to the environment used (e.g. K8s 1.9 cluster on Rancher, that K8s 1.9 and Rancher section is read).
Resolves #
Checklist:
[skip ci]
> doc: Add missing version compare sign

- pkg/daemon/ceph/osd/device.go
- pkg/operator/ceph/cluster/osd/config/scheme.go
JournalPartitionType is defined but will never be used given rook will always
place journal file in the filestore's block partition. Cleaning out the code.
Resolves: #1775
Checklist:
> JournalPartition Code Cleanup

- Documentation/upgrade.md
- cmd/rook/ceph/mds.go
- cmd/rook/ceph/mds_test.go
- pkg/daemon/ceph/mgr/daemon.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
- pkg/operator/ceph/file/mds.go
- pkg/operator/ceph/file/mds_test.go
The naming of the deployments and pods will now be more correlated with the ceph daemon names when troubleshooting the ceph cluster.
- The name of the mgr is now `rook-ceph-mgr` instead of `rook-ceph-mgr0`. There is only ever one of them.
- The name of the mds daemon is now the entire suffix of the pod instead of just the last suffix. For example, if the pod name is `rook-ceph-mds-myfs-7b9c79f684-h7dqj`, the mds daemon name would be `myfs-7b9c79f684-h7dqj` as seen in `ceph -s`, instead of `h7dqj`.
Resolves #1752 
Checklist:
> Name mgr and mds pods more consistently

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- pkg/apis/ceph.rook.io/v1alpha1/types.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/migration.go
- pkg/operator/ceph/cluster/migration_test.go
- pkg/operator/ceph/cluster/mon/mon.go
```
Default to 3 mons when no `mon.count` is given.
The documentation and upgrade page has been updated accordingly to reflect the new
default.
```
This is breaks some lines at around 80 chars in the example Ceph `cluster.yaml`.
Default `mon.count` to `3` when not set, in addition to that `allowMultiplePerNode` is set to `true` to ease the migration of users that may not set a `monCount` before doing the upgrade.
That the `monCount` must be set has been added to the upgrade guide.
Relates #1710.
These default changes are needed now because if no `mon.count` and/or `monCount` is/was not given would cause the operator to start no mons at all.
I don't see an issue with enforcing the users to set a …
> Updated upgrade path for monCount

- pkg/clusterd/disk.go
- pkg/daemon/discover/discover_test.go
- pkg/util/sys/device.go
In 0.7 and earlier, the detection of disk uuid was done by `sgdisk`. This is critical for maintaining a consistent disk id at restart so that we can decide whether to start the same osd or create a new one. With the change to `udevadm` with #1637, some environments do not return the disk uuid. This change will revert to the 0.7 behavior for sgdisk to detect the uuid more reliably, while still detecting the more detailed device properties with udevadm.
Resolves #1776
Checklist:
> Detect disk uuid with sgdisk

- Documentation/minio-object-store.md
- PendingReleaseNotes.md
Description of your changes: small docs changes to fix minio service name in the minikube URL command and include minio in pending release notes.
Checklist:
[skip ci]
> docs: fix minio service name and include minio in pending release notes

- cmd/rook/ceph/ceph.go
- cmd/rook/ceph/mon.go
- pkg/clusterd/network.go
- pkg/daemon/ceph/mon/daemon.go
```
Fixes the issue that when the old IPv4 flags were set, the new flags
were still used because of the default being the new flags not being
empty.
```
Don't set a default for the IP flags so the IPv4 flags are not overriden through the "default" of the new IP flags.
Resolves https://rook-io.slack.com/archives/CAWE7BW10/p1530078642000121 and (probably) resolves #1823.
Checklist:
~~Will test it in a few minutes, but from the Slack discussion this seems like a valid fix.~~
> Don't set default for IP flags

- pkg/util/sys/device.go
There is trouble with retrieve device label In bare metal cluster (vmware vSphere, nodes: ununtu 16.04) configured by kubespray. Command `udevadm info --query=property /dev/sdb1` output only:
```
DEVPATH=/devices/pci0000:00/0000:00:15.0/0000:03:00.0/host32/port-32:1/end_device-32:1/target32:0:1/32:0:1:0/block/sdb/sdb1
DEVTYPE=partition
MAJOR=8
MINOR=17
PARTN=1
PARTNAME=ROOK-OSD0-BLOCK
SUBSYSTEM=block
```
There isn't key `ID_PART_ENTRY_NAME`, however label exists in `PARTNAME`.
I don't know why truncated output from udevadm on some nodes into rook app. But its still full output from same docker container like:
```
[root@node1 /]# udevadm info --query=property /dev/sdb1
DEVLINKS=/dev/disk/by-id/scsi-36000c295222ef6cd1cd2cf2441f918d5-part1 …
```
> Fix retrieve device label

- pkg/operator/minio/controller.go
Services in kubernetes can be reached at . without specifying svc.cluster.local. Removing this resolves issues with deployments where the kubernetes domain has been changed from the default.
Remove svc.cluster.local from the serverAddress
Resolves #1836
> remove svc.cluster.local from serverAddress

- Documentation/helm-operator.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml.tmpl
```
Closes #1571.
```
Adds a `nodeSelector` to the rook-ceph operator chart.
Resolves #1571.
Checklist:
> helm: Added `nodeSelector` to rook-ceph operator chart

- Documentation/rbac.md
- cluster/charts/rook-ceph/templates/clusterrole.yaml
The updates to the role names for rbac missed updating this username in the helm chart. 
Resolves #1833 
**Checklist:**
[skip ci]
> Rename user in helm chart to match the psp username

- pkg/operator/ceph/cluster/osd/status.go
- pkg/operator/discover/discover.go
- pkg/operator/discover/discover_test.go
The available devices passed to the provisioner should include the list of devices previously configured in the same cluster. In other words the provisioner should always be given the desired list of devices and directories. The provisioner is idempotent and will see that the osds were already configured on the devices or directories. 
Resolves #1864
**Checklist:**
> Available devices should include previously configured devices

- pkg/daemon/ceph/client/osd.go
The health checks for osds every minute in the operator are filling the logs. This only should be debug-level logging.
Resolves #
**Checklist:**
[skip ci]
(added the skip ci flag since we have two successful builds and integration tests passing on 3/4 of the platforms, but just failed on known random issues)
> Debug logging for the osd health check

- pkg/daemon/ceph/mon/config.go
ceph osd objectstore is optional
Resolves #
**Checklist:**
> omit empty osd objectstore

- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
Somehow the OwnerReference was not set on the mgr deployment, which means it is left behind when the CRD is deleted.
Resolves #
**Checklist:**
> Set the OwnerReference on the mgr deployment 

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/pod.go
Fix that no `placement` was applied to the Deployment object of an OSD.
Resolves #1895
**Checklist:**
> Apply placement to OSD Pod Spec

- Documentation/helm-operator.md
- Documentation/toolbox.md
- Documentation/upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
**Description of your changes:** Update the docs and examples to use the `v0.8.0` tag.
**Checklist:**
[skip ci]
> docs: update docs/yaml to use v0.8.0

- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
- pkg/daemon/ceph/rgw/objectstore.go
Set the `min_size` to `1` for erasure coded Pools.
Resolves #1795
**Checklist:**
> operator: Set min_size to dataChunkCount for ec pools

- INSTALL.md
- Makefile
- build/makelib/common.mk
- build/release/Makefile
- images/Makefile
- images/ceph-toolbox/Makefile
- images/ceph/Makefile
- images/cockroachdb/Makefile
- images/cross/Makefile
- images/image.mk
Raise the scope of the `IMAGES` config variable in the
`build/release/Makefile` to the `build/makelib/common.mk` file, and use
the `IMAGES` variable in the `images/Makefile` to allow users to build
only select images.
Examples of new use:
make IMAGES='ceph ceph-toolbox' build
make -C build/release IMAGES='ceph ceph-toolbox' publish
The 'images/image.mk' clean.build target was changed to use
`CLEAN_IMAGES` instead of `IMAGES`, as it was conflicting with use of
the parameter in image builds.
Added IMAGES option to top-level make's help text. The text for this
option exceeded 80 lines in the `Makefile` itself, so the help text was
refactored to eliminate `    @echo '<text>'`. The `Makefile` text should
now match exactly what is output to the user including line length.
Added IMAGES option to …
> make: Allow building select images

- pkg/operator/ceph/cluster/osd/config/config.go
- pkg/operator/ceph/cluster/osd/pod.go
- pkg/operator/ceph/cluster/osd/pod_test.go
- pkg/operator/k8sutil/k8sutil.go
- pkg/operator/k8sutil/k8sutil_test.go
Backport of #1908 "osd: Truncate too long name for prepare job".
Resolves #1907.
**Checklist:**
> Backport "osd: Truncate too long name for prepare job" #1908

- Documentation/block.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/storageclass.yaml
This brings Rook in line with the Ceph recommendations to use `xfs` for RBD volumes.
Resurrects PR #1835.
**Checklist:**
[skip ci]
> Added fstype: xfs as default in the examples

- Gopkg.lock
Ran `make vendor` to update the `Gopkg.lock` to the latest versions to resolve the `dirty` tag issue for the images.
Resolves #1933
**Checklist:**
> Updated Gopkg.lock by running `make vendor`

- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
- pkg/daemon/ceph/rgw/objectstore.go
Backports PR #1909.
Resolves #1795.
**Checklist:**
Should I add a separate commit that adds an entry to the pending release notes?
> Backport PR #1909 "operator: Set min_size to dataChunkCount for ec pools"

- PendingReleaseNotes.md
- images/ceph/ceph_version
Pick up the luminous 12.2.7 build, which includes the fix for the mons crash when there are multiple file systems.
Resolves #1027
**Checklist:**
> Update ceph to 12.2.7

- PendingReleaseNotes.md
- images/ceph/ceph_version
(cherry picked from commit 27ba0cb3c5a1adb87d3ced24c1545f61d03f3326)
Backport luminous 12.2.7 to the release-0.8 branch.
Resolves #1027
**Checklist:**
> Backport PR #1935 (Update Ceph to Luminous 12.2.7)

- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/util.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/k8sutil/node.go
- pkg/operator/k8sutil/node_test.go
Before deploying osd prepare job, operator should validate if the nodes are in the placement. Otherwise, the job won't be able to run and thus stuck in pending
Resolves #1925
**Checklist:**
> validate storage nodes before preparing osds

- pkg/operator/ceph/cluster/osd/pod.go
The change of the UpdateStrategy fixes issues with a new OSD Pod in the same Deployment coming up and directly entering CrashLoopBackOff because the old OSD Pod hasn't been fully
terminated yet (released it's locks).
Resolves #1920 and #1922.
**Checklist:**
***
@travisn @jbw976 Should I update the pending release notes to note that one should edit each Deployment with the new updateStrategy?
> operator/osd: Use UpdateStrategy Recreate

- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/util.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/k8sutil/node.go
- pkg/operator/k8sutil/node_test.go
Cherry-pick c6f463d0e7a514618585fdf23c13370d1a43217c to release-0.8
Resolves #
**Checklist:**
> Backport: Validate storage nodes before preparing osds

- pkg/client/clientset/versioned/fake/register.go
- pkg/client/clientset/versioned/scheme/register.go
Fixes #1962
I missed this change intended for PR #1952. Generated code should not be
modified.
Fixes #1962
**Checklist:**
> Undo spell fixes to generated code

- Documentation/ceph-cluster-crd.md
Remove dead "storage configuration settings" link and add missing `config` parameters.
**Checklist:**
[skip ci]
> Fix storage config Ceph Cluster CRD doc links

- Documentation/upgrade-patch.md
- Documentation/upgrade.md
- PendingReleaseNotes.md
- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/osd/agent.go
- pkg/daemon/ceph/osd/agent_test.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/device.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/pod.go
- pkg/operator/ceph/cluster/osd/pod_test.go
- pkg/operator/ceph/cluster/osd/status.go
- pkg/operator/k8sutil/deployment.go
- pkg/operator/k8sutil/pod.go
The OSD pods need the ceph.conf regenerated each time they launch for two scenarios:
- If the mons failover, the osd needs to start with the new mon config
- If the ceph config override configmap was updated, it needs to be merged again
With #1698, the config was only generated once initially in the "osd prepare" pod, and never re-generated. Now the config will be generated by an init container each time the osd pod restarts.
A couple other changes at the same time:
- If a directory is specified that is the same as the `dataDirHostPath` or the special path `/var/lib/rook`, the directory will be ignored when creating osds.
- The obsolete `prepareOnly` flag was removed from a number of placed
**Which issue is …
> Initialize OSD config at each startup with an init container

- Jenkinsfile
- tests/framework/utils/k8s_helper.go
- tests/integration/base_block_test.go
- tests/integration/block_createBlock_k8s_test.go
- tests/integration/multi_cluster_deploy_test.go
- tests/integration/smoke_test.go
- tests/scripts/minikube.sh
With the release of K8s 1.11, Rook needs to run the integration tests there. This PR also updates the older versions to their latest dot releases.
Resolves #1840
**Checklist:**
> Add k8s 1.11 to the test matrix

- tests/scripts/minikube.sh
With the addition of storage providers, add flexibility to the minikube script so you only load the storage provider docker images that are necessary.
To start minikube with all storage providers the command is the same:
```
tests/scripts/minikube.sh up
```
To start minikube with a single provider:
```
tests/scripts/minikube.sh up [ceph | minio | cockroachdb]
```
The same option works for the `update` command.
**Checklist:**
[skip ci]
> Update only the images desired in minikube

- Documentation/upgrade-patch.md
- Documentation/upgrade.md
- Gopkg.lock
- PendingReleaseNotes.md
- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/osd/agent.go
- pkg/daemon/ceph/osd/agent_test.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/device.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/pod.go
- pkg/operator/ceph/cluster/osd/pod_test.go
- pkg/operator/ceph/cluster/osd/status.go
- pkg/operator/k8sutil/deployment.go
- pkg/operator/k8sutil/pod.go
(cherry picked from commit 1d928ecd3678d487c854a21b83929a604b7eeb02)
Backport: The osd pod now has an init container for generating the ceph.conf every time the pod starts up. This is needed in case the mons failover or the ceph-config-override configmap changes
Resolves #1919 #1939 
**Checklist:**
> Backport: OSD init container to initialize config at startup

- OWNERS.md
Thanks to the Rook senior maintainers for giving me the possibility to be a standard maintainer!
This adds me, Alexander Trost (galexrt) to the maintainers list.
[skip ci]
> Add Alexander Trost (galexrt) as a maintainer

- cluster/examples/kubernetes/ceph/kube-registry.yaml
- tests/integration/base_file_test.go
Update example filesystem (kube-registry.yaml) to use `clusterNamespace` since 0.8.0. If `clusterName` is used, it will cause the kubelet to not find the correct volume plugin.
Ref: #1965
> Update clusterName to clusterNamespace in example

- images/cross/run.sh
Doing a chown on /var/run/docker.sock when using `osfx` on docker for Mac corrupts the file. A workaround is to chown the file instead.
Resolves #1986
**Checklist:**
> Fix build/run when running on macos

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-pool-crd.md
This splits the pool samples into two: one for replication and one for erasure coding. The sample was confusing being together with one of them commented out.
**Checklist:**
[skip ci]
> Docs: clarify pool replication samples

- .github/stale.yml
To help us focus on the issues that are most important to fix in a world of limited resources, issues will be automatically closed after a period of inactivity of 90 days. There is a grace period of 7 days between marking the issue as stale and closing the issue. Any comment or activity on the issue will keep it from being closed.
The [probot-stale](https://github.com/probot/stale) Github app has already been enabled in the `rook/rook` repo. This configuration file will activate the bot. 
The bot will only close issues and is not configured to monitor PRs for now. The number of PRs can be managed manually.
**Checklist:**
[skip ci]
> Configure the bot to close stale issues

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/status_test.go
We don't need to handle other osd(s) related tasks if there's no valid nodes available in the cluster to run
osd(s), output an error message to help user identify the cause of the issue.
Return immediately if no valid node(s) is ready to run osd, output an error message to help users identify the cause why an OSD is not launched.
Resolves #1988
**Checklist:**
> Return error when no valid nodes available to run osd

- tests/framework/installer/cockroachdb.go
- tests/framework/installer/install_helper.go
- tests/framework/utils/k8s_helper.go
- tests/integration/base_file_test.go
- tests/integration/block_createBlock_k8s_test.go
- tests/integration/zblock_mount_unmount_test.go
The tests take a long time to delete the crds and namespaces during cleanup of each suite. There is no need for the tests to wait, so we can pass `--wait=false` to `kubectl`. The timeouts are only manifested in the 1.11 builds.
Resolves #1970 
**Checklist:**
> Continue with tests while namespace and crds are being deleted

- Documentation/helm-operator.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml.tmpl
Signed-off-by: Terje Sannum <terje.sannum@nav.no>
Added the possibility to add annotations to the rook-ceph-operator pod
> helm: support adding annotations on pod

- tests/framework/installer/install_helper.go
- tests/scripts/helm.sh
At least two builds (such as [this](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/master/runs/714/nodes/41/steps/60/log/?start=0)) in the last 12 hours have failed waiting for OSDs to start because the test framework thought an rbd device was available to consume on an osd, but then Rook refuses to actually start the osds on rbd, which is expected. This is manifest with the message in the test log:
```
installer: available device: rbd1
```
Another error in the same build was that [helm failed to install](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/master/714/pipeline/43). It's not clear yet why 200 seconds was not sufficient to wait for …
> Tests: skip rbd volumes for osds

- pkg/daemon/ceph/mgr/daemon.go
This enables using modules that expect OSD/MDS access to work, and makes Rook match how other deployment tools like ceph-deploy set up the ceph-mgr caps.
> Fix ceph-mgr caps

- pkg/daemon/ceph/mon/config.go
The "allow" format has been deprecated for several years, and does not allow people to do "ceph tell mds..." commands.
Signed-off-by: John Spray <john.spray@redhat.com>
> Fix client.admin's default MDS capabilities

- tests/integration/smoke_test.go
[This build](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-1999/7/pipeline/48) hit an error where a substring was empty and caused the tests to crash. An `err` had been returned from a previous call and isn't being checked until after calling this helper test method. So if the string is empty, the helper should just return and allow the test to fail elsewhere.
Resolves #
**Checklist:**
> Tests: skip checking substring if empty

- pkg/daemon/ceph/agent/agent.go
- pkg/daemon/ceph/agent/flexvolume/manager/ceph/manager.go
- pkg/util/sys/kmod.go
Current Ceph volume manager code doesn't take the builtin kernel module into
the account, so the `modinfo` will fail in this case. Also, we need to add error handling
code to make sure the volume manager does work when proceeding to continue.
Resolves #
**Checklist:**
> Enhancement of Ceph volume manager kmod detection

- Jenkinsfile
The integration tests sometimes fail when mounting a block image such as [here](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/master/runs/719/nodes/43/steps/105/log/?start=0). This will collect the kubelet log so we can troubleshoot in more detail what is happening.
Resolves #
**Checklist:**
> Collect the kubelet log from integration tests

- pkg/operator/ceph/pool/controller.go
Set application name to "rbd" when creating a RBD pool
Resolves #2011 
**Checklist:**
> Set application name to "rbd" when creating a RBD pool

- CONTRIBUTING.md
**Description of your changes:** This PR updates the contribution documentation to include a command for amending a previous commit to include the sign-off message.  This commonly happens for first time contributors to the repo.
**Checklist:**
[skip ci]
> docs: add instruction for amending commit to include sign-off message

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
We want to have good code documentation in the future, and we would like
to slowly develop better documentation for existing code. As a checklist
item for PRs, add a requirement for godoc-style comments when (1) new
code items are added and (2) when existing items are sufficiently
modified.
**Checklist:**
[skip ci]
> PR template: Add godoc comments to checklist

- build/makelib/common.mk
Currently, VERSION generation does not handle the case with the `-dirty` branch and no commits since the previous tag, which results in invalid semantic version, which in turn, fails `make build`.
For example, a branch with:
```
git describe --dirty --always --tags
v0.8.1-dirty
```
will result in `VERSION=v0.8.1.dirty`, which will fail `make build` with the following message:
```
make build                                                                                                                                                                 
=== helm package rook-ceph
==> Linting /home/user/go/src/github.com/rook/rook/cluster/charts/rook-ceph
Lint OK
1 chart(s) linted, no failures
Error: Invalid Semantic Version
build/makelib/helm.mk:48: recipe for target …
```
> Update VERSION generation to produce a valid semantic version

- Documentation/ceph-teardown.md
**Description of your changes:** This PR updates the command to manually delete finalizer from ceph cluster CRD, as shared in https://github.com/rook/rook/issues/1488#issuecomment-397336663.
Resolves #1488 
**Checklist:**
[skip ci]
> docs: update command to manually delete finalizer from ceph cluster CRD

- INSTALL.md
- Jenkinsfile
- PendingReleaseNotes.md
- build/release/Jenkinsfile.promote
- build/release/Makefile
- build/release/README.md
**Description of your changes:** This PR removes support for quay.io, the Rook container images will only be published to docker hub going forward.
Resolves #2049 
**Checklist:**
> build: remove support for quay.io

- Documentation/ceph-filesystem-crd.md
- Documentation/filesystem.md
- Documentation/upgrade.md
- cluster/examples/kubernetes/ceph/ec-filesystem.yaml
- design/multiple-storage-types-support.md
- tests/scripts/multi-node/build-rook.sh
This adds an "Advanced example" to the Ceph filesystem docs. Also the `erasureCoded` example is "removed" from the default example and moved to the mentioned "advanced example".
**Checklist:**
[skip ci]
> Ceph: Improve erasure coded filesystem docs

- Documentation/block.md
- Documentation/ceph-filesystem-crd.md
- Documentation/ceph-pool-crd.md
- Documentation/common-issues.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/ec-storageclass.yaml
- cluster/examples/kubernetes/ceph/storageclass.yaml
- pkg/daemon/ceph/agent/flexvolume/controller.go
- pkg/daemon/ceph/agent/flexvolume/controller_test.go
- pkg/daemon/ceph/client/image.go
- pkg/daemon/ceph/client/image_test.go
- pkg/operator/ceph/provisioner/provisioner.go
- pkg/operator/ceph/provisioner/provisioner_test.go
This change allows block storage to use a given Ceph pool for it's data. `dataPool` must be given if soemone wants to use erasure coded RBD data.
The `pool` paramter would then be the metadata pool.
I haven't updated the docs yet, but just want to get some feedback in, if this seems sane. :)
Resolves #1733
**Checklist:**
> Add dataPool parameter to StorageClass

- cmd/rookflex/cmd/root.go
As the `rookflex` volume plugin, the root command should be `rookflex` instead of `rook`, else we'll get below confusing message:
```
...bin/#./rookflex help
Rook Flex volume plugin
Usage:
rook [command]
Available Commands:
help        Help about any command
init        Initialize the volume plugin
mount       Mounts the volume to the pod volume
unmount     Unmounts the pod volume
```
Resolves #
**Checklist:**
[skip ci]
> Correct the usage information of rookflex volume plugin

- build/release/Makefile
- images/ceph-toolbox/Makefile
- images/ceph/Makefile
- images/cockroachdb/Makefile
- images/minio/Makefile
Add an option `SKIP_IMAGE_SAVE` to the Ceph image makefiles with the
intent that a developer can set this variable to `1` or some other
nonzero value to skip the lengthy image saving part of the Rook build.
This will allow Ceph developers to iterate more quickly on dev builds.
N/A
**Checklist:**
> Image build/release: do not save image for builds; save only for release

- pkg/daemon/ceph/agent/agent.go
- pkg/daemon/ceph/agent/cluster/controller.go
- pkg/daemon/ceph/agent/cluster/controller_test.go
- pkg/daemon/ceph/agent/flexvolume/server.go
We don't use volume manager argument in NewClusterController() and NewFlexvolumeServer() functions, so remove the volume manager argument from those functions prototype.
Resolves #
**Checklist:**
> Remove unused volume manager parameters

- Documentation/common-issues.md
- Documentation/toolbox.md
- Documentation/upgrade.md
- cluster/examples/kubernetes/ceph/toolbox.yaml
Currently documentation about rook-tools is describe how to run `rook-tools` as a pod. This change add rook-tools to be deployed via deployment method.   
**Checklist:**
> Add rook-tools deployment instead clear pod definition. 

- Documentation/openshift.md
- cluster/examples/kubernetes/ceph/scc.yaml
- pkg/daemon/ceph/agent/agent.go
Loading of multiple flex drivers too quickly on 1.11 causes a race condition where the driver(s) fail to load. This will throttle the flex driver loading as a workaround until we transition to a csi driver.
Resolves #2064
**Checklist:**
> Load flex driver more slowly to avoid race condition

- README.md
**Description of your changes:** This PR adds the CII Best Practices badge to the Rook README.  The full CII Best Practices checklist can be viewed for the Rook project at https://bestpractices.coreinfrastructure.org/en/projects/1599.  There is more work to do for complying with all the best practices, but we are at 80% now with the recent effort and we should start displaying the badge in the repo.
Partially addresses #1440 
**Checklist:**
[skip ci]
> add CII Best Practices badge to README

- pkg/operator/ceph/cluster/osd/pod.go
Rook no longer supports Kubernetes < 1.7
Remove a workaround for k8s < 1.6.4 where `runAsNonRoot` could not be
explicitly set to false.
Resolves #1942 
**Checklist:**
> ceph osd operator: Allow explicit runAsNonRoot=false

- pkg/daemon/ceph/client/image.go
- pkg/daemon/ceph/client/image_test.go
Current code will truncate the generated RBD volume image in some cases, this PR will round up the size to make sure the final RBD image can accommodate the actual data if any.
Resolves #
**Checklist:**
> Roundup the size of the RBD volume image

- pkg/daemon/ceph/agent/agent.go
(cherry picked from commit 1a86a8cb7b04467fb22c4fb863a13697831a49eb)
Loading of multiple flex drivers too quickly on 1.11 causes a race condition where the driver(s) fail to load. This will throttle the flex driver loading as a workaround until we transition to a csi driver. This is just a workaround until a fix comes upstream: https://github.com/kubernetes/kubernetes/issues/60694
Resolves #1501 
**Checklist:**
> metered loading of flex drivers

- Documentation/ceph-quickstart.md
- Documentation/upgrade.md
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/pod_test.go
- pkg/operator/k8sutil/pod.go
The -id portion of the name is unnecessary and inconsistent with the other
pod names.
Resolves #
**Checklist:**
> Remove unnecessary "-id" from OSD pod names

- pkg/operator/ceph/provisioner/provisioner.go
We maybe roundup the requested size to the next `MB` boundary in some cases when creating the volume, thus we need to make sure the size of the PV generated is consistent with the actual one.
Align the actual size of the PV to the one when creating the volume. For example:
```
--- a/cluster/examples/kubernetes/wordpress.yaml
+++ b/cluster/examples/kubernetes/wordpress.yaml
@@ -24,7 +24,7 @@ spec:
- ReadWriteOnce
resources:
requests:
-      storage: 20Gi
+      storage: 1048698
```
Before this PR, the `kubectl get pvc` will output:
```
NAME          STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
wp-pv-claim   Bound …
```
> Align the size of the PV to the actual one

- ROADMAP.md
- design/decouple-ceph-version.md
The version of Ceph deployed by the Rook operator should be flexible and specified by the admin in the cluster CRD. This change will allow Rook's version to be independent of the ceph version.
- In production clusters, admins want to very carefully control when they upgrade their ceph clusters since the data path is so critical.
- During development, Rook can be tested against any version of Ceph, whether a stable version of luminous or mimic, or a private dev build.
Resolves #2004
**Checklist:**
[skip ci]
> Design doc for decoupling the Ceph version

- tests/integration/upgrade_test.go
The upgrade integration test has failed several times in the last few days when reading/writing to the pod with the filesystem mount after upgrading from 0.8 to master. This will retry the read/write to help stabilize the tests.
**Checklist:**
> Retry file operations after upgrade in integration test

- cmd/rook/ceph/mds.go
- cmd/rook/ceph/mgr.go
- cmd/rook/ceph/mon.go
- cmd/rook/ceph/osd.go
- cmd/rook/ceph/rgw.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
- pkg/operator/ceph/cluster/mon/util.go
- pkg/operator/ceph/file/mds.go
- pkg/operator/ceph/object/rgw.go
- tests/integration/base_object_test.go
FYI: This branch is built on top of #2081
As discussed in https://github.com/rook/rook/pull/2081#issuecomment-418785257, 
to help with code readability, include daemons from `pkg/daemon/ceph`
as `<dmn>daemon "github.com/rook/rook/pkg/daemon/ceph/<dmn>`. This will
make it easier to understand code lines without needing to scroll up to
check the includes, as there are mon/mds/mgr/osd/rgw packages for
daemons as well as operator and cmd.
N/A
**Checklist:**
> Ceph: refactor daemon includes to <dmn>daemon for grokkability

- Jenkinsfile
This is a temporary patch to help us figure out what is causing the random
issues on concurrent builds and re-using an instance.
Resolves # NA
> Enable CI system logs in artifacts

- images/nfs/Dockerfile
The original base image `fedora:25` doesn't support multi-arch, so we get below error message with `docker pull fedora:25`:
```
25: Pulling from library/fedora
no matching manifest for unknown in the manifest list entries
```
This PR bumps the fedora base image to `:26` which is multi-arch version, to address the build issue.
Resolves #2084 
**Checklist:**
> Fix rook nfs docker image build failure on AArch64

- Documentation/nfs.md
It is required to install nfs client packages on the nodes where the nfs server pod will run.
If the client packages are not present, the PVC will give an [error](https://askubuntu.com/questions/525243/why-do-i-get-wrong-fs-type-bad-option-bad-superblock-error) when the volume is mounted to another pod.
Updated Prerequisite to instruct users to install `nfs-common` on ubuntu nodes or `nfs-utils` on centos nodes.
Resolves #
**Checklist:**
[skip ci]
> [Documentation] Updated NFS prerequisite

- build/makelib/golang.mk
Now the golang version 1.11 has been released by the official website[1], so let's add support for this version, else we'll get below build error when using golang 1.11:
```
build/makelib/golang.mk:103: *** unsupported go version. Please
make install one of the following supported version: '1.7|1.8|1.9|1.10'.  Stop.
```
[1] https://golang.org/dl/
Bump the golang version to 1.11
Resolves #
**Checklist:**
> Add golang 1.11 version support

- images/nfs/Dockerfile
- images/nfs/Makefile
We need to pull the base image for `arm64`, not for `amd64`. This PR adds prefix `arm64v8` to`fedora:26` for pull the right image.
Add prefix of `arm64v8` to the base image to pull the right image when cross-building `nfs-arm64`.
Resolves #2110
**Checklist:**
> Fix Rook NFS image cross-build issue on AArch64

- pkg/daemon/ceph/client/image.go
While creating a PVC, if the operator dies between successfully creating a rbd
image and associating it with a PV, that PVC will never be completed. A
restarted operator will also fail to complete the task as the requested rbd
image already exists. With the assumption that a PVC UID will always be unique,
this patch will try to use the existing volume and complete the PVC request.
Resolves: #2072
> PVC create resiliency

- pkg/daemon/ceph/client/image.go
Backport of fix to improve PVC resiliency
Resolves #2072
> Backport 0.8 pvc create resiliency

- Documentation/flexvolume.md
FlexVolume on Rook doesn't work out of the box on Google's Kubernetes Engines (GKE). GKE uses a non-standard FlexVolume directory which isn't currently documented.
It only updates documentation for FlexVolume. 
**Checklist:**
[skip ci]
> GKE uses a non-standard FlexVolume directory which is not documented.

- Documentation/block.md
- PendingReleaseNotes.md
- pkg/operator/ceph/provisioner/controller/controller.go
- pkg/operator/ceph/provisioner/controller/controller_test.go
- pkg/operator/ceph/provisioner/provisioner_test.go
- tests/framework/clients/block.go
- tests/framework/clients/pool.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v0.8.go
- tests/framework/utils/k8s_helper.go
- tests/integration/base_block_test.go
- tests/integration/block_create_test.go
- tests/integration/zblock_mount_unmount_test.go
- tests/longhaul/base_block_test.go
This adds support for processing `reclaimPolicy` attribute of a `StorageClass` and set it the `PersistentVolume` created for `PersistentVolumeClaim` using that storage class.
Resolves #1259
**Checklist:**
> Support storageclass reclaimpolicy

- tests/framework/installer/ceph_installer.go
- tests/framework/utils/k8s_helper.go
Two changes to help the tests be more resilient to random failures:
- The CRD instances are sometimes not purged even though the definitions were purged. The tests now ensure the instances are purged when the definitions are purged
- When a mon is created, the operator should wait until the pod is running before it checks to quorum. [This test](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/master/769/pipeline) failed on 1.9 due to the operator hanging on the query before the mon started. This will also benefit the operator in production.
Resolves #2118
**Checklist:**
> Make integration tests more resilient to crd deletion failure

- design/external-management.md
This partially addresses https://github.com/rook/rook/issues/1868 -- it's the part about making pool creation optional, rather than any of the broader ideas around adoption/migration paths.
This is a design doc with some bonus code that implements it.  Please review the design doc and treat the code as illustrative -- the reason I've skipped ahead to the implementation is that my ceph-mgr work already uses it, so I have the patches handy.
Resolves #1868
Additions to docs and tests pending consensus on design doc.
- N/A Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
[skip ci]
> Design doc for making Ceph pool creation/deletion optional

- cmd/rookflex/cmd/mount.go
It has been observed on slow systems that a volume is incorrectly formatted when k8s does not see the existing format. We need to understand this by adding logging and find why the device is incorrectly reporting status.
The same `blkid` command run by k8s is run here in rook to see if we get consistent output. @jbw976 can you think of any other logging that would be useful?
Related to #1553 
**Checklist:**
> Log the output of blkid to see if device should be formatted

- cmd/rookflex/cmd/mount.go
(cherry picked from commit c67542829b0f4042bb2ef57e8ed96efedbc91656)
It has been observed on slow systems that a volume is incorrectly formatted when k8s does not see the existing format. We need to understand this by adding logging and find why the device is incorrectly reporting status. This is believed to be fixed by #2121, although it will need time to stabilize in master before we consider backporting. For now we will at least collect logging in v0.8.2.
Related to #1553, but expected to be resolved by PR #2121.
**Checklist:**
> Backport: Log the output of blkid to see if device should be formatted

- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/k8sutil/pod.go
When a mon is created, the operator should wait until the pod is running before it checks to quorum. [This test](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/master/769/pipeline) failed on 1.9 due to the operator hanging on the query before the mon started. This will also benefit the operator in production.
@galexrt this was separated from PR #2127.
**Checklist:**
> Wait for mon pods to start before checking for quorum

- build/makelib/golang.mk
the exit code from dep ensure --dry-run was not being checked correctly resulting a lots of false negatives. This probably explains why we've been seeing lots of issues with vendor dirs being out of date.
**Checklist:**
> build: fix the check for dep ensure

- PendingReleaseNotes.md
- cmd/rook/ceph/mgr.go
- cmd/rook/ceph/mon.go
- pkg/daemon/ceph/config/info.go
- pkg/daemon/ceph/config/pod.go
- pkg/daemon/ceph/mgr/init.go
- pkg/daemon/ceph/mon/init.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/mon/spec_test.go
- pkg/operator/ceph/spec/spec.go
- pkg/operator/ceph/spec/spec_test.go
- pkg/operator/ceph/test/container.go
- pkg/operator/test/client.go
- pkg/operator/test/info.go
- pkg/operator/test/spec.go
- pkg/operator/test/spec_test.go
- pkg/operator/test/volumes.go
- pkg/operator/test/volumes_test.go
The initial (still very WIP) part of these changes include changes to mon and config as well to pull out duplicated and nearly-duplicated code between these 2 and the mgr into shared packages. The first changes have focused on some shared test methods.
Progress toward issue #2003.
Includes design from design doc PR #1578
Progress toward issue #2003.
**Checklist:**
> Ceph mgr: initialize mgr config in init container

- Documentation/ceph-quickstart.md
- Documentation/openshift.md
- Documentation/rbac.md
- cluster/examples/kubernetes/ceph/scc.yaml
- design/resource-constraints.md
Backport #2035.
Resolves #2035.
**Checklist:**
> Backport: Added missing RBAC in quickstart Cluster definition

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/mon/spec_test.go
- pkg/operator/ceph/cluster/osd/pod.go
- pkg/operator/ceph/cluster/osd/pod_test.go
- pkg/operator/ceph/file/mds.go
- pkg/operator/ceph/file/mds_test.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/rgw_test.go
- pkg/operator/k8sutil/pod.go
Ceph expects to be able to reason about physical hardware / nodes.
Before this patch the NODE_NAME that was available referred to the pod
name. This patch exposes the underlying node name, pod, and pod
namespace for the ceph daemons to consume.
Resolves #2078
> ceph: expose node,pod,ns names to ceph daemons

- cmd/rook/ceph/operator.go
- cmd/rook/cockroachdb/operator.go
- cmd/rook/minio/operator.go
- cmd/rook/nfs/operator.go
- cmd/rook/rook/rook.go
- pkg/util/flags/flags.go
Change enables glog logging and also make default flag values
configurable.
Resolves: #2105
> Enable glog logging

- cmd/rookflex/cmd/mount.go
as seen here, extra console logging causes trouble for flex driver
This reverts commit c67542829b0f4042bb2ef57e8ed96efedbc91656.
Resolves #2149 
**Checklist:**
skipping ci only because three builds in a row have failed for random issues and the fix is verified
[skip ci]
> Revert "log the output of blkid to see if device should be formatted"

- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/osd/init.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/k8sutil/volume.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/utils/k8s_helper.go
The OSD pod spec required two changes to allow for running the ceph image directly with the [decoupled version image](https://github.com/rook/rook/blob/master/design/decouple-ceph-version.md).
- `tini` is not included in the ceph image and cannot be used when running the daemon directly with the image. `ceph-osd` can be called directly in the daemon image and there is no need for `tini`.
- The "filestore on a device" scenario requires rook to mount the device before the daemon can be started, then unmount the device when completed. Therefore, an init container is used to copy the `tini` and `rook` binaries into an emptydir mount, which is then mounted to the ceph daemon container to run the osd.
**Which issue is …
> Enable filestore on device scenario to run with ceph image

- design/ceph-nfs-ganesha.md
Add design doc for Ceph NFS-Ganesha CRD that will orchestrate highly available, scalable Ganesha server pods as NFS gateways to the Ceph filesystem and object stores already setup by rook. This will allow NFS client pods to consume Ceph filesytem and object stores setup by rook.
Related issue: https://github.com/rook/rook/issues/1799
[skip ci]
> Add Ceph NFS-Ganesha CRD design doc

- cmd/rookflex/cmd/mount.go
This reverts commit c67542829b0f4042bb2ef57e8ed96efedbc91656.
(cherry picked from commit 3832708c4faae245fe86999e872d35ab80273988)
Resolves #2149
**Checklist:**
> Backport: Revert "log the output of blkid to see if device should be formatted"

- .github/PULL_REQUEST_TEMPLATE.md
- Gopkg.lock
- Gopkg.toml
- Jenkinsfile
- Makefile
- build/makelib/golang.mk
This PR updates dep to version 0.5, and adds a check during
CI runs that enforces that the vendor dependencies have not changed.
There is a now a makefile target `make vendor.check` that performs
this check. Also removed the requirement that PR run make vendor as
this will be done by CI.
Also all vendor deps have now been made explicit. You should add a constraint for each entry
in Gopkg.toml. this prevent the drifting of deps as people run `make vendor`
Resolves #1822
Resolves #2173 
**Checklist:**
> add vendor checks

- Documentation/helm-operator.md
- Documentation/toolbox.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/pod.go
- pkg/operator/ceph/cluster/osd/pod_test.go
- pkg/operator/discover/discover.go
- pkg/operator/k8sutil/node.go
- tests/framework/installer/install_helper.go
- tests/framework/utils/k8s_helper.go
- Backport the changes that allow configuring of osds when the hostname is different from the k8s node name.
- Update the release version in the yamls in anticipation of the v0.8.3 release
Resolves #2148
**Checklist:**
> Backport: Configure OSDs when hostname is different from node name

- cmd/rookflex/cmd/unmount.go
flex volume driver calls capture console messages as replies. Don't log command during driver calls.
Resolves #2165 
/assign @travisn 
**Checklist:**
> don't print console logs during flex driver call

- cluster/examples/kubernetes/README.md
These will fix the link in the kubernetes example readme to link to the correct quickstart.
none
[skip ci]
> Fix quickstart link in kubernetes examples

- pkg/operator/k8sutil/resources.go
- pkg/operator/k8sutil/resources_test.go
Resources are now correctly merged when "not set".
Example:
```
requests:
cpu: 500m
```
will result in only `cpu` be set and not `memory` being set to `0` because it is not set in this case.
Slack message of error because of this issue: https://rook-io.slack.com/archives/C46Q5UC05/p1538818496000100
TL;DR Now it actually does what the comment says:
> if the first has a value not set check if second has and set it in first
Before we didn't check `second` if it has the value(s) set.
**Checklist:**
> Fix MergeResourceRequirements() func

- Documentation/k8s-pre-reqs.md
Adds documentation about applying an imagePullSecret to a service account to allow all pods spawned by the operator to have this imagePullSecret. This is necessary to access an image (e.g. ceph-agent) from a private/authenticated docker registry without changing the current operator code.
Resolves #1713
**Checklist:**
- rest does not apply
[skip ci]
> docs: add documentation about imagePullSecrets #1713

- images/nfs/Dockerfile
- images/nfs/Makefile
f26 has been EOL'ed for a while now, so we shouldn't be relying on it.
Update to fedora 28. This necessitates installing libnsl2 for ganesha,
which is not installed in the base image these days.
Long term, we should probably find some way to keep this in sync with
the Fedora release cadence, or rebase onto something more stable like
Centos.
-----8<-------
Build tested only as I don't have a great way to test this at the moment.
> nfs: rebase nfs image onto fedora 28

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
We need this environment variable in the main container, not the init
container, as it's used by the rook ceph-mgr module.
Fixes: ca71b7a311e4 (Ceph mgr: Set up config in init container)
> Ensure that $ROOK_CLUSTER_NAME is set for mgr daemon

- pkg/daemon/ceph/client/filesystem.go
- pkg/daemon/ceph/mds/filesystem.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/mds.go
- pkg/operator/k8sutil/deployment.go
- tests/framework/clients/filesystem.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v0.8.go
- tests/integration/base_file_test.go
fix #2193
Fix regression introduced by PR allowing MDS config creation in init
container. This allows the new deployment-based mds clusters to scale
down where currently they can only remain constant or scale up.
Resolves #
**Checklist:**
> ceph mds: allow mds deployment scale-down

- pkg/daemon/ceph/osd/agent.go
- pkg/operator/ceph/agent/agent.go
- pkg/operator/ceph/object/rgw.go
- pkg/util/exec/exec.go
Previous code tried to interpret the string output as a `fmt.Sprintf`
string formatter, mangling `%` into `%!(MISSING)`, etc.
Thanks to go, I don't belive these are exploitable (unlike the similar
error in C).
Since this seemed to be a common error in the codebase, I did a quick
audit by visually inspecting the results of `git grep 'f([^"]'` and I believe this PR
fixes all occurrences found.  I don't have a good suggestion for automated
tests to prevent this in future :(
Example error (look for `(MISSING)`):
```
E0927 05:31:07.618429   11227 driver-call.go:237] Failed to unmarshal output for command: unmount, output: "2018-09-27 05:31:07.191711 I | exec: Running command: df --type ceph /var/lib/kubelet/pods/95461479-c216-11e8-bcf0-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch\n2018-09- …
```
> Don't misinterpret command output as string format

- Gopkg.lock
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/operator.yaml
- cmd/rook/discover.go
- pkg/daemon/discover/discover.go
- pkg/operator/discover/discover.go
The device discovery on each node is currently performed every 30s and is not configurable. This frequency actually has a performance impact on some systems. We can reduce this frequency and also make it configurable. The operator currently doesn't take action when new devices are discovered anyway, which we will need to handle better in the future separately.
**Checklist:**
> Reduce frequency of device discovery

- Documentation/upgrade.md
> Add doc changes for upgrade with incomplete PVCs

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- pkg/daemon/ceph/client/test/mon.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
The number of mons in the cluster can be changed by updating the `mon.count` in the cluster CRD. For example:
- When changed from 3 to 5, the operator will start two more mons.
- When changed from 5 to 3, the operator will remove two mons.
The mons will be added or removed by the periodic health check of the mons (every 45s by default). Since the CRD is applied in a different goroutine from the health check, there is a mutex to protect updating the number of mons. Note that once there are two or more mons, the operator cannot reduce the mon count below two because a quorum of two cannot remove a member.
Resolves #1636 #2130
**Checklist:**
[skip ci]
> Allow mons to scale up or down

- tests/scripts/minikube.sh
In the dev environment this will launch k8s 1.12.2 by default. Requires minikube 0.30.0.
Resolves #
**Checklist:**
[skip ci]
> Start minikube with k8s 1.12.2 by default

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-dashboard.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/apis/ceph.rook.io/v1beta1/types.go
- pkg/daemon/ceph/client/mgr.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
Allows serving dashboard behind a reverse proxy under a subpath.
Resolves #1902
**Checklist:**
(skipping build due to known build issues)
[skip ci]
> Add urlPrefix setting for ceph dashboard

- Documentation/minio-object-store-crd.md
- Gopkg.lock
- Gopkg.toml
- PendingReleaseNotes.md
- cluster/examples/kubernetes/minio/object-store.yaml
- images/minio/Dockerfile
- pkg/apis/minio.rook.io/v1alpha1/types.go
- pkg/operator/minio/controller.go
- pkg/operator/minio/controller_test.go
- tests/scripts/minikube.sh
- Add cluster domain to minio spec
- Remove port configuration from minio spec
- Include unused packages for codegen repos
- Update Minio version to pick up latest fixes
- Helper to load cockroachdb demo images into minikube
Resolves #2258 
Resolves #2264 
**Checklist:**
> Fixes for running Ceph, CockroachDB, Minio demos

- Gopkg.lock
- cmd/rookflex/cmd/init.go
SELinux relabelling breaks (times out) on large filesystems, and
doesn't work with cephfs ReadWriteMany volumes (last relabel wins).
See also https://github.com/kubernetes/kubernetes/blob/02cca1f11a8ae570369540564604d0cde06e0720/pkg/volume/cephfs/cephfs.go#L209
Fixes #2177
**Checklist:**
> Disable SELinux relabelling

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
When the cluster CRD is updated, the major version of the ceph image remains blank, which results in the default behavior of assuming luminous. This breaks mimic and nautilus clusters. This change will ensure the correct version of the image is detected, either by using the previously detected version if the image did not change, or by detecting the new version if it did change.
Resolves #2260
@laevilgenius PTAL
**Checklist:**
skip ci due to known build issues
[skip ci]
> Set ceph version when cluster crd is updated

- pkg/daemon/ceph/client/image.go
- pkg/daemon/ceph/client/image_test.go
- pkg/operator/ceph/provisioner/provisioner_test.go
As described in #2248, executing `rbd ls` to get an image's info after creating it takes a long time when having 1000+ images. This PR uses [`rbd info {pool-name}/{image-name}`](http://docs.ceph.com/docs/mimic/rbd/rados-rbd-cmds/#retrieving-image-information) instead.
Resolves #2248 
**Checklist:**
[skip ci]
> ceph: use "rbd info" to get image info after creating it

- pkg/daemon/ceph/osd/agent.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/discover/discover.go
- pkg/operator/ceph/cluster/osd/status.go
- pkg/operator/discover/discover.go
- pkg/util/sys/device.go
- tests/framework/utils/k8s_helper.go
This fixes additional "problematic sections" as a user affected by this problem reported that running just the bash snippet didn't fix it for him, but running a Rook version based on release-0.8 branch with those fixes in worked for him when doing the upgrade.
I would add the bash snippet/issue link to the release notes when a backport for v0.8 has been decided.
Resolves #2272.
**Checklist:**
> Use truncated node name for missed sections

- design/ceph-volume-provisioning.md
This design document describes transitioning the provisioning of OSDs to `ceph-volume` instead of Rook's own partitioning and provisioning. Due to the recent development of ceph-volume, this needs to be a transition rather than cutting off the old implementation completely. Where ceph-volume has the required features, Rook will be able to call it. The `ceph-volume lvm batch --prepare` flag was just merged to ceph/ceph master and will soon be backported to luminous and mimic.
The `rook` and `tini` binaries need to be copied into the osd pod so that `ceph-volume` can mount the config in the same container that the `ceph-osd` is started. Rook will not be able to run `ceph-osd` as the entrypoint to the container. …
> Design: Provisioning OSDs with ceph-volume

- pkg/apis/rook.io/v1alpha2/storage.go
- pkg/apis/rook.io/v1alpha2/types.go
As @jbw976 requested, I moved the change to the Rook alpha storage selection API out of #2132 so that we have that change already in.
The PR does not contain documentation as no actual implementation for Ceph, Minio and so on is done in this PR.
The implementation for using PVC templates (and adding documentation for that) will be done #2132.
**Checklist:**
> Added PersistentVolumeClaimTemplates to storage selection

- Documentation/flexvolume.md
Updating the flexvolume.md file to include specific rancher rke configuration info and highlight in the rancher section that kubelets runs as a docker container and that the flex volume needs to be mounted, the updated docs show how this is done.
The docs now show the specific configuration operations to include, this can be easily copied and pasted from the docs.
This is a docs only update.
Resolves #2302
**Checklist:**
(../blob/master/CONTRIBUTING.md#comments)
[skip ci]
> Update flexvolume docs for rancher rke

- pkg/operator/ceph/cluster/mon/util.go
Newer versions of ceph have deprecated this option, and the commands
will fail if you try to pass it in.
Resolves #
**Checklist:**
(skipping the build for known random issues and jenkins overload)
[skip ci]
> remove --set-uid option from ceph-authtool calls

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-quickstart.md
- Documentation/k8s-pre-reqs.md
- Documentation/openshift.md
- Documentation/rbac.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/scc.yaml
- pkg/apis/ceph.rook.io/v1beta1/types.go
- pkg/apis/rook.io/v1alpha2/zz_generated.deepcopy.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/osd/status_test.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/integration/upgrade_test.go
This is to enable the `rook` ceph-mgr module to drive
the Rook and k8s APIs, exposing functionality via
its own CLI and GUI.
For the moment this uses an externally populated
ServiceAccount: we'll probably want to auto-create
this with clusters.
Signed-off-by: John Spray <john.spray@redhat.com>
See design doc: https://github.com/rook/rook/issues/1868
**Checklist:**
[skip ci] // due to flaky builds
> Set service account on ceph-mgr pod

- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
- pkg/operator/ceph/file/filesystem_test.go
- pkg/operator/ceph/file/mds.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/k8sutil/test/deployment.go
Use the `UpdateDeploymentAndWait` method used by the osd operator to
update the deployments for ~mons,~ mgrs, mdses, and rgws when the Rook
orchestrator image is updated.
**Note:** mons deferred to v0.9.1 release because (1) the mons will still update properly from v0.8.x -> v0.9.0 due to the legacy replicaset handling code and (2) the mons require some nontrivial changes to incorporate `UpdateDeploymentAndWait`. Mon issue: #2331 
Signed-off-by: Blaine Gardner <blaine.gardner@suse.com
Resolves 997? #997 is sufficiently broad that I'm not sure I would say that this resolves it or not. It seems to me like an ongoing goal where this is the first (main) step.
I still have some TODO items for myself on this PR:
**Checklist:**
> ceph: Update deployments on rook img update

- pkg/apis/ceph.rook.io/v1beta1/types.go
- pkg/daemon/ceph/client/filesystem.go
- pkg/daemon/ceph/mds/filesystem.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/filesystem_test.go
I opened issue #2313 yesterday and decided to take a stab at it. This patchset seems to do the right thing. If no dataPool is specified then this just has the daemon just verify that the filesystem already exists and then spin up the MDS daemons for it.
> Allow filesystem specifications without pools

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- tests/framework/installer/ceph_manifests.go
it enhances the output of commands like `kubectl get cluster.cpeh.rook.com` like so:
```
$ kubectl get cluster.ceph.rook.io
NAME        DATADIRHOSTPATH   MONCOUNT   AGE
rook-ceph   /var/lib/rook     1          4h
```
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
> Ceph CRDs: Add additionalPrinterColumns to enhance command line output

- Documentation/cockroachdb-cluster-crd.md
- Documentation/minio-object-store-crd.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/cockroachdb/cluster.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/minio/object-store.yaml
- pkg/apis/cockroachdb.rook.io/v1alpha1/types.go
- pkg/apis/cockroachdb.rook.io/v1alpha1/zz_generated.deepcopy.go
- pkg/operator/cockroachdb/controller.go
- pkg/operator/cockroachdb/controller_test.go
- pkg/operator/minio/controller.go
- pkg/operator/minio/controller_test.go
- tests/framework/installer/cockroachdb_manifests.go
```
selection field.
```
This PR enables enables the CockroachDB and Minio operator to use the newly added Rook Storage Selection field `volumeClaimTemplates` to use for storage.
Partly _resolves_ #919.
**Checklist:**
[skip ci]
> Cockroachdb + Minio: Use PersistentVolumeClaimTemplates storage

- pkg/operator/ceph/object/rgw.go
The rgw daemon was not being updated during the upgrade from v0.8. This change will ensure the pod spec is updated whenever the orchestration runs for the object store.
Resolves #2347
**Checklist:**
// skip ci due to flaky builds
[skip ci]
> Update the rgw deployment or daemonset when the pod spec changes

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- tests/framework/installer/ceph_manifests.go
- tests/integration/upgrade_test.go
…espace
The creation of the ceph-mgr service account a few days ago missed granting access for ceph-mgr to the configmaps in the rook-ceph-system namespace. This is needed for the inventory to look at available devices. @jtlayton 
**Checklist:**
// skip ci due to flaky builds
[skip ci]
> Grant access for ceph-mgr to access the configmaps in the system namespace

- Documentation/openshift.md
- cluster/examples/kubernetes/ceph/scc.yaml
The SecurityContextConstraints has changed from `v1` to `security.openshift.io/v1`, as observed in my testing on openshift 1.11. Users should be moving off 1.9 with the known security issue, where the previous version `v1` had been tested to be working.
**Checklist:**
[skip ci]
> Openshift update for the SCC Kind

- Documentation/ceph-toolbox.md
- Documentation/helm-operator.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
Use v0.9.0 tag for the images on the `release-0.9` branch.
**Checklist:**
[skip ci]
> use v0.9.0 for the image tag

- pkg/operator/edgefs/cluster/target/config/config.go
- pkg/operator/edgefs/cluster/target/configmap.go
- pkg/operator/edgefs/cluster/target/target.go
Default setting for UseMetadataOffload changed to false, and added NodeType definition
Resolves #2359
**Checklist:**
> EdgeFS: Wrong condition in devices discovery

- Documentation/ceph-block.md
The command `kubectl delete -n rook-ceph pool replicapool` returns the error `error: the server doesn't have a resource type "pool"`. The actual resource type is `cephblockpools.ceph.rook.io`.
**Checklist:**
[skip ci]
> Fix the documented command to delete replicapool

- tests/scripts/multi-node/build-rook.sh
The command `kubectl delete -n rook-ceph pool replicapool` used to work, but currently returns the error `error: the server doesn't have a resource type "pool"`. The actual resource type is `cephblockpools`. The resource type `cluster` was also recently changed to `cephcluster`.
Since the function commands end with `|| true`, the errors are silently masked and the resources are not deleted.
This PR adds delete commands for `cephblockpools` and `cephcluster`, so that regardless of whether you're testing old or new versions of Rook the delete commands will work.
(I previously fixed the documentation in https://github.com/rook/rook/pull/2387, then I noticed that the build-rook.sh script still used the old resource name, so I fixed the script too.)
**Checklist:**
[skip ci]
> Fix the test function that deletes the replicapool

- Documentation/cassandra-cluster-crd.md
- Documentation/openshift.md
Fixes indention in openshift doc.
Haven't found too many more while searching through some other pages.
**Checklist:**
[skip ci]
> Fix code block indention in openshift doc

- cmd/rook/ceph/mgr.go
- pkg/daemon/ceph/client/mgr.go
- pkg/daemon/ceph/mgr/init.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
The `server_addr` needs to be set on the mgr so the prometheus and dashboard mgr modules can bind to the pod ip when starting their endpoints. The mgr key is not sufficient to set this setting, so the admin key is used in the config-init container, then the admin key is deleted before the init container completes.
Resolves #2335 
**Checklist:**
> Set the server_addr for the dashboard and prometheus modules

- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/dashboard_test.go
- pkg/operator/ceph/cluster/mgr/mgr.go
After enabling a mgr module, it takes some short period of time before the module is ready to accept commands. If the module is not yet ready, it will respond with error `22 invalid argument`. In this case, we should retry the operation until the module is ready. 
Resolves #2298
**Checklist:**
> Retry creating self signed cert if module is not ready

- Documentation/helm-operator.md
**Description of your changes:** Quick docs update to include the stable channel for the rook ceph helm chart in the docs
Resolves #2340
**Checklist:**
[skip ci]
> docs: add stable channel to rook ceph helm chart docs

- cmd/rook/ceph/mgr.go
- pkg/daemon/ceph/client/mgr.go
- pkg/daemon/ceph/mgr/init.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/dashboard_test.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
Backport the mgr changes:
- Bind the prometheus and dashboard mgr modules to the pod ip instead of `[::]`
- Retry generation of the self-signed cert if the dashboard module is not yet initialized
Resolves #2298 #2335 
**Checklist:**
> Backport: Bind server_addr to mgr pod ip and retry cert generation

- images/ceph/Dockerfile
- images/ceph/Makefile
The `rook/ceph` image is always using the amd64 base image. The base image was set to `ceph/ceph:v13` and since the build machine is amd64 even while cross compiling arm, the arm base image was not used. We must specify the arch-specific base image. 
Resolves #2406
**Checklist:**
> Build with arch-specific Ceph base image

- images/ceph/Dockerfile
- images/ceph/Makefile
(cherry picked from commit 8ea61fdc66341144b0e792f1ceab30d7b4a68a24)
Backport the fix to build the ceph operator for different architectures, in particular, arm64.
Resolves #2406
**Checklist:**
// skip build due to random failure
[skip ci]
> Backport: Build with arch-specific Ceph base image

- Documentation/advanced-configuration.md
It appears this reference to 'rook' was inadvertently not updated
to 'rook-ceph' when multiple backend storage system support was
added.  Both the surrounding documentation and code seem to support
the idea that this is the correct value.
Signed-off-by: James E. Blair <jeblair@redhat.com>
Resolves #
**Checklist:**
[skip ci]
> docs: Correct typo in advanced config docs

- Documentation/ceph-pool-crd.md
[skip ci]
Based on discussion in issue #2411, clarify Rook and Ceph's behavior
around allowing the user to create a cluster where data replication
cannot tolerate the cluster's failure domain safely.
> doc: clarify Ceph pool `failureDomain` setting

- Documentation/minio-object-store-crd.md
- Documentation/minio-object-store.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/minio/object-store.yaml
- pkg/operator/minio/controller.go
Added minio_objectstore label to Minio objects
This allows multiple object stores to be in the same namespace and
to be selected separately from each other.
Resolves #1861.
**Checklist:**
> Added minio_objectstore label to Minio objects

- pkg/daemon/ceph/client/mgr.go
- pkg/daemon/ceph/mgr/init.go
This patch fixes an issue I was seeing when starting the mgr with recently-built nautilus ceph-container images. Apparently until the mgr is started, you need to add in --force when setting these values.
This fixes the problem for me, but I'm now wondering whether we need to exclude this flag on ceph versions =< mimic.
> ceph: add --force to mgr settings

- Documentation/ceph-dashboard.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/dashboard_test.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
adds support for a dashboard `port` option and `ssl` option.
Resolves: #2433, maybe #2412
> add ceph dashboard port/ssl options

- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml.tmpl
- cluster/examples/kubernetes/ceph/operator.yaml
- cmd/rookflex/cmd/init.go
- pkg/operator/ceph/agent/agent.go
- pkg/operator/ceph/agent/agent_test.go
Added an enviroment variable for disabling Selinux relabeling. It was disabled by default in https://github.com/rook/rook/pull/2219 . It is now enabled by default with the option to turn it off if needed.
Resolves #2417
**Checklist:**
> Add ENV flag for selinux labeling

- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
this mounts secret as volume to rgw container
this adds certificate path to init container
Signed-off-by: Jack Lauritsen <jack.lauritsen@teradata.com>
when CephObjectStore has a value for sslCertificateRef, this mounts secret as volume to rgw container and retains the certificate path for the init-container. 
Resolves https://github.com/rook/rook/issues/2435
**Checklist:**
not required, not changes from expected functionality
not required previous release does not call out any issue with tls on s3
> fix for enabling tls on rados gateway s3 api:

- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
this mounts secret as volume to rgw container
this adds certificate path to init container
Signed-off-by: Jack Lauritsen <jack.lauritsen@teradata.com>
(cherry picked from commit ea3e0fca26acf1578bf5e6b0dc4b67a1f94bae1c)
when CephObjectStore has a value for sslCertificateRef, this mounts secret as volume to rgw container and retains the certificate path for the init-container.
Resolves https://github.com/rook/rook/issues/2435
**Checklist:**
not required, not changes from expected functionality
not required previous release does not call out any issue with tls on s3
> Backport: Fix for enabling tls on rados gateway s3 api:

- Documentation/common-issues.md
In our 0.9 rook deployment, the `app` label assigned to the operator is `rook-ceph-operator` which was incorrectly speficied in the documentation:
```
$ kubectl describe pod/rook-ceph-operator-765bcd58b-6rr2q | grep app=
Labels:             app=rook-ceph-operator
```
Here's where the app label is defined:
https://github.com/rook/rook/blob/84ad5afb6b7cfd0028853568519ce4ecf491b561/cluster/charts/rook-ceph/templates/deployment.yaml#L17
I didn't bother opening an issue for such a minor problem.
**Checklist:**
[skip ci]
> fix operator app label

- pkg/operator/ceph/cluster/mgr/mgr.go
The dashboard is currently failing due to not being able to load the rbd mirroring settings. Until the fix for [this issue](http://tracker.ceph.com/issues/37870) is released, the mgr needs access with `mon "allow *"` instead of `mon "allow profile mgr"`.
Resolves #2404
**Checklist:**
> Set mgr privs for access to the rbd mirroring settings

- Documentation/edgefs-monitoring.md
- cluster/examples/kubernetes/edgefs/monitoring/prometheus-service.yaml
- cluster/examples/kubernetes/edgefs/monitoring/prometheus.yaml
- cluster/examples/kubernetes/edgefs/monitoring/service-monitor.yaml
- pkg/operator/edgefs/cluster/mgr/mgr.go
- pkg/operator/edgefs/cluster/mgr/mgr_test.go
This enables automatic prometheus scarping and fixes /metrics access. It also adds documentation on how to get it all configured. 
Resolves #2401 
**Checklist:**
> added support for edgefs-monitoring via Prometheus

- tests/scripts/kubeadm-install.sh
There is an issue with the Jenkins CI/CD process when it comes to running integration tests in GCE (Kubernetes 1.13x). The base image used in GCE is out of date and had too many updates to install before the process times out. This is a quick fix. It ups the timeout from 20 attempts to 100. 
The long term plan is to rebuild the base image with Packer and have a process in place to keep that image updated monthly.
Resolves #2549 
**Checklist:**
Signed-off-by: Christopher P. Maher <chris@mahercode.io>
> Change timeout for dpkg unlock for Ubuntu GCE test systems

- tests/scripts/kubeadm-install.sh
There is an issue with the Jenkins CI/CD process when it comes to running integration tests in GCE (Kubernetes 1.13x). The base image used in GCE is out of date and had too many updates to install before the process times out. This is a quick fix. It ups the timeout from 20 attempts to 100. 
The long term plan is to rebuild the base image with Packer and have a process in place to keep that image updated monthly.
Resolves #2549 
**Checklist:**
Signed-off-by: Christopher P. Maher <chris@mahercode.io>
> Backport: Changing timeout for dpkg unlock for Ubuntu GCE CI/CD systems

- pkg/operator/ceph/cluster/mgr/mgr.go
(cherry picked from commit 9afbe36ae698787245ad2eaa61bf923fc5c74047)
Backport the change to the mgr privileges to prevent the dashboard from crashing.
Resolves #2404 
**Checklist:**
[skip ci]
> Backport: Set mgr privs for access to the rbd mirroring settings

- design/ceph-config-updates.md
Propose a new design to update Rook's Ceph configuration strategy to
align with Ceph's recent changes to the config process.
[skip ci]
> design: ceph: update ceph configuration strategy

- Documentation/ceph-csi-drivers.md
Documented how to implement ceph-csi drivers in a k8s 1.12+ cluster with Rook.
Resolves #2233 
**Checklist:**
[skip ci]
> Document ceph-csi drivers implementation

- pkg/daemon/ceph/client/command.go
- pkg/daemon/ceph/client/command_test.go
- pkg/daemon/ceph/client/mon_test.go
The Ceph CLI has the flag option '--connect-timeout' which controls the
timeout of the command when reaching out to a monitor. If the connection
cannot be established within 15 seconds, the command will fail. The
default value in Ceph is relatively long (300sec IIRC). This is a
problem when monitors have trouble reaching out quorum, since this means
the command will only fail after 300 sec.
Now we fail faster.
Resolves: https://github.com/rook/rook/issues/2574
> pkg: timeout ceph commands

- Documentation/ceph-dashboard.md
Update the Ceph dashboard documentation to retrieve dashboard password in a cleaner way
- no issue created
**Checklist:**
[skip ci]
> Ceph Dashboard Documentation: retrieve dashboard password in a cleaner way

- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/k8sutil/volume.go
- pkg/operator/k8sutil/volume_test.go
- tests/framework/installer/ceph_manifests.go
Rook's behavior should not be to create a default OSD in dataDirHostPath
when no devices are present on a node. Any preexisting fallback osd
should be kept as long as no dirs or disks have been specified to keep
the legacy behavior for those clusters running with these osds in place.
The legacy deletion behavior is also kept, removing the osd as soon as
any dir or device is specified other than the dataDirHostPath dir.
Resolves #2569
**Checklist:**
> ceph: no longer create fallback osd

- Documentation/ceph-teardown.md
[skip ci]
Add steps to clean the disks on a node after Rook has been removed so
that they are in a usable state again.
**Checklist:**
> Ceph doc: Update teardown with disk reset steps

- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
We now refuse to start more than one monitor on the same machine if
hostnetworking is enabled.
Supporting this creates a lot more complexity from the rook side. Also
having 3 monitors running on the same machine is not a production setup.
This means multi-cluster support on the same machine
is not possible anymore when hostnetworking is enabled.
Resolves: https://github.com/rook/rook/issues/2604
> ceph: check num mon for hostnetworking

- Documentation/ceph-quickstart.md
The namespace referred to by the prose text in the "Create a Rook Cluster" when creating the cluster was incorrect and did not match the example below, which was correct.
[skip ci]
> docs: correct prose in quickstart to match example

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-filesystem-crd.md
- Documentation/ceph-pool-crd.md
This adds more detailed documentation on how to use the CRUSH location setting in CephCluster CRD with new and existing CephClusters. It also provides an example configuration.
Resolves #2635
**Checklist:**
cc @travisn @galexrt
[skip ci]
> Added documentation for custom CRUSH location settings

- Documentation/flexvolume.md
extra_binds has to be on same level as extra_args. Currently it will be interpreted as another argument resulting in kubelet being called with the non-existent argument "--extraBinds=/usr/libexec/kubernetes/kubelet-plugins/volume/exec:/usr/libexec/kubernetes/kubelet-plugins/volume/exec" leading to a crash/reboot-loop of the kubelet.
Resolves #
**Checklist:**
[skip ci]
> fix indent to prevent kubelet/cluster crash

- Documentation/common-issues.md
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
- pkg/operator/ceph/cluster/mon/service.go
The operator has had several issues recently when all the mons are not in a healthy state, which are fixed by these changes:
- After a mon is failed over, the old mon fails to be deleted until the next health check cycle
- If the operator is restarted when the mons are not all in quorum, the operator will wait indefinitely for all mons to come back in quorum before continuing. This fix will only require majority quorum at startup instead of all mons to be online.
- Entries to the operator log are confusing, indicating such things as waiting indefinitely when "4/3 mons are running". The counts of mons are misleading
These changes have been thoroughly tested manually by killing mons, restarting the operator at inconvenient times, etc. Unit and integration …
> Handle mon failover more gracefully

- pkg/operator/ceph/nfs/config.go
Ganesha recently grew the ability to watch a RADOS object for
notifications, which will cue it to reload its configuration. Add the
directive to the RADOS_URLS config block.
Resolves #
**Checklist:**
> nfs: add watch_urls directive to watch a RADOS object for notifications

- Documentation/ceph-teardown.md
[skip ci]
Backport 79362688f32ba60cbc66ebeb82024e5dcf1b191f to Rook 0.9 branch.
**Checklist:**
> Backport: Ceph doc: update disk teardown steps

- pkg/operator/edgefs/isgw/isgw.go
- tests/integration/mon_test.go
There were some lingering changes needed to switch to the apps api from the extensions, a follow up from #2611. This fixes the master build that is modifying the Gopkg.lock file to add back in the extensions which were intended to be removed.
**Checklist:**
> Convert remaining extensions to apps api

- Documentation/ceph-nfs-crd.md
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/nfs/nfs.go
Rename createCephNFS to upCephNFS and have it take a parameter with the
old active count. Rename deleteGanesha to downCephNFS and have it take a
parameter with the new desired active count. Both the existing callers
pass in "0" for the new count parameters.
Fix up the onUpdate handler for CephNFS objects, such that changes to
the active count are reflected in the number of active servers. Have it
pass in the appropriate values when scaling servers up or down.
Finally, fix downCephNFS to shut down the highest-index servers first
and counting down instead of doing them in the order they were started.
This should eventually allow us more predictable behavior when scaling
down the number of server nodes.
**Which issue is resolved by this Pull …
> nfs: scale up/down ganesha servers with Active count

- cmd/rook/ceph/ceph.go
- pkg/daemon/ceph/config/config.go
- pkg/daemon/ceph/config/config_test.go
- pkg/daemon/ceph/config/info.go
- pkg/daemon/ceph/util/util.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/cluster/mon/env.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/node_test.go
- pkg/operator/ceph/cluster/mon/service.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/mon/spec_test.go
- pkg/operator/ceph/cluster/mon/util.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/config/store.go
- pkg/operator/ceph/file/spec.go
- pkg/operator/ceph/file/spec_test.go
- pkg/operator/ceph/nfs/spec.go
- pkg/operator/ceph/object/spec_test.go
- pkg/operator/ceph/spec/spec.go
- pkg/operator/k8sutil/pod.go
- pkg/operator/test/spec.go
This commit introduces the necessary changes to support the new
messenger feature coming with Ceph Nautilus (currently in development).
What changes? Now the monitor listens on two port:
* old 6789 for messenger v1, which will help us support older client
(e,g: krbd)
* new 3300 for messengers v2, which brings new improvement in the
messaging layer. This new transport layer brings numerous advantages
such as encryption improvement, speed improvement, pluggable nature to
support different network stack than TCP and many more.
We still have one Service IP, however it has 2 ports, see:
```
NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
rook-ceph-mon-a           ClusterIP   10.106.217.160   <none>        3300/TCP,6789/TCP   4h
rook-ceph-mon-b …
```
> Support for Ceph messenger 2

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-quickstart.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/integration/upgrade_test.go
I had some trouble with RBAC under minikube when testing some
ceph-mgr functionality. This patch tweaks rook-ceph-mgr-system to
be a ClusterRole, and rook-ceph-mgr-cluster to use a
ClusterRoleBinding.
Suggested-by: Travis Nielsen <tnielsen@redhat.com>
> ceph: fix up RBAC permissions

- pkg/daemon/ceph/rgw/init.go
- pkg/daemon/ceph/rgw/init_test.go
As per: https://github.com/ceph/ceph/pull/26599, Beast is now the
default fronted for rados gateway.
Newly created cluster as of Nautilus will use it by default.
Resolves: https://github.com/rook/rook/issues/2707
> rgw: change default frontend on nautilus

- Documentation/ceph-csi-drivers.md
This PR removes the namespace creation from the ceph-csi document
and also uses `kubectl create` instead of `kubectl apply`
Resolves #2710 
**Checklist:**
[skip ci]
> Fix ceph-csi deployment document

- Documentation/ceph-cluster-crd.md
As can be seen in pkg/apis/ceph.rook.io/v1/types.go the Cluster CRD documentation is missing details about the dashboard configuration
> Add missing documentation for dashboard options in Cluster CRD

- Documentation/cassandra-operator-upgrade.md
- pkg/operator/cassandra/constants/constants.go
Backport of [PR 2444 (cassandra: fix wrong mount point)](https://github.com/rook/rook/pull/2444) to release-0.9.
Resolves #2443
> [backport] cassandra: fix wrong mount point

- Documentation/common-issues.md
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
The operator has had several issues recently when all the mons are not in a healthy state, which are fixed by these changes:
* After a mon is failed over, the old mon fails to be deleted until the next health check cycle
* If the operator is restarted when the mons are not all in quorum, the operator will wait indefinitely for all mons to come back in quorum before continuing. This fix will only require majority quorum at startup instead of all mons to be online.
* Entries to the operator log are confusing, indicating such things as waiting indefinitely when "4/3 mons are running". The counts of mons are misleading
These changes have been thoroughly tested manually by killing mons, restarting the operator at inconvenient times, etc. Unit and integration …
> Backport: Improved mon failover and operator startup when a mon is down

- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/orchestrator.go
It takes a little time between a mgr module being enabled and its commands being recognized. This adds a retry loop similar to the one in the dashboard setup code so that the orchestrator setup works correctly. There is also a minor cleanup patch to more properly define invalidArgErrorCode in terms of the syscall.EINVAL constant.
> Retry orchestrator initialization if command is unrecognized

- Documentation/helm-operator.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml.tmpl
This adds a Helm chart value to set `ROOK_HOSTPATH_REQUIRES_PRIVILEGED` env var on the operator.
Resolves #2735.
**Checklist:**
> Added ROOK_HOSTPATH_REQUIRES_PRIVILEGED as value to Helm Chart

- cluster/examples/kubernetes/ceph/scc.yaml
- design/ceph-volume-provisioning.md
- pkg/operator/ceph/cluster/osd/spec.go
this is needed as cryptsetup in the pod and udev on the host coordinate
via a semaphore that must be visible in both contexts. note that additionally the host needs to have dmcrypt compiled with udev synchronization, which at least one minikube version does not have.
the similar fix for containers in ceph-ansible also needed ipc host sharing on the osd container to properly handle reboots, but this did not appear to be needed for rook which is probably related the avoidance of systemd units for various things.
there are two things I want to do before merging this which shouldn't take long:
1. write up some docs for the dmcrypt cluster crd setting
2. change the crd setting to accept a real boolean instead of string "true"
In the mean time I pushed a built image with this change to …
> ceph: share host ipc namespace with provision pod

- cluster/examples/kubernetes/ceph/scc.yaml
- design/ceph-volume-provisioning.md
- pkg/operator/ceph/cluster/osd/spec.go
this is needed as cryptsetup in the pod and udev on the host coordinate
via a semaphore that must be visible in both contexts.
note that additionally the host needs to have dmcrypt compiled with udev
synchronization, which at least one minikube version does not have.
fixes: #923
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
(cherry picked from commit 6597531ed0b0324f48141bfdc65c8b6431abaff7)
// skip ci for random failure
[skip ci]
> backporto: ceph: share host ipc namespace with provision pod

- tests/framework/clients/block.go
- tests/framework/clients/filesystem.go
- tests/framework/clients/object.go
- tests/framework/clients/object_user.go
- tests/framework/clients/pool.go
- tests/framework/clients/read_write.go
- tests/framework/installer/cassandra_installer.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/cockroachdb_installer.go
- tests/framework/installer/nfs_installer.go
- tests/framework/utils/k8s_helper.go
- tests/integration/base_block_test.go
- tests/integration/base_file_test.go
- tests/integration/block_create_test.go
- tests/integration/ceph_csi_test.go
- tests/integration/filesystem_mountuser_test.go
- tests/integration/multi_cluster_test.go
- tests/integration/pool_test.go
- tests/integration/smoke_test.go
- tests/integration/upgrade_test.go
- tests/integration/zblock_mount_unmount_test.go
- tests/longhaul/base_block_test.go
- tests/longhaul/block_with_fencing_test.go
The integration tests check for the return of substrings from calls to kubectl in a number of places. On occasion these return something slightly different and cause an unnecessary failure in the integration tests. It is sufficient and complete to check the `err` from these calls to determine failure. There is no need to return strings from create, delete, or apply operations.
**Checklist:**
> Remove unreliable string checks from integration tests

- Documentation/ceph-filesystem.md
- cluster/examples/kubernetes/ceph/kube-registry.yaml
Signed-off-by: k911 <konradobal@gmail.com>
HA Docker Registry without explicitly set `REGISTRY_HTTP_SECRET`, behind any load-balancing thing (e.g. kubernetes service), does not work correctly, because if omitted, value is generated randomly and thus diffrent on different pods. As outcome I was unable to push image to such registry.
https://github.com/docker/docker.github.io/blob/master/registry/deploying.md#load-balancing-considerations
I've also added:
-  link to configuration reference (can be useful)
-  `imagePullPolicy: Always` because IMO, not doing this, without setting explicit version, can cause inconsistency in cluster
- liveness/readinessProbes for stability
I also wanted to change `ReplicationController` to `Deployment` but I've seen this PR …
> docs: Improve HA docker registry example

- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/device.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/osd/status.go
- pkg/operator/discover/discover.go
- pkg/operator/discover/discover_test.go
- pkg/operator/edgefs/cluster/controller.go
- pkg/util/sys/device.go
- tests/framework/installer/device.go
There were several issues around OSDs that this PR will get properly working:
- The `deviceFilter` was not working at all
- All devices detected by the discovery pod were being passed to the OSD provisioning pod, thus not always honoring the desired device list that should be provisioned. Now the provisioning pod will be given the "desired" state from the crd, then apply that state depending on the actual devices detected
- Added a helper to ensure OSDsPerDevice is always valid (default of 1 instead of 0)
- In the rook-ceph-system namespace, two configmaps were being stored: one for the discovered devices, and one for the devices already configured. The latter device list was always storing everything discovered rather than what was configured, so it was …
> Clean up provisioning of OSDs on devices

- Documentation/flexvolume.md
OpenStack Magnum uses Atomic Host as its default deployment. The Atomic
docs for rook point to the openshift docs, which are a bit complex to
follow if one is not actually using OpenShift. For magnum, the path
/var/lib/kubelet/volumeplugins is the correct path, so it's easier to
just point to that directly rather than sending users to OpenShift docs.
Resolves #2373
**Checklist:**
[skip ci]
> Add configuration note about OpenStack Magnum flexvolume

- Documentation/ceph-block.md
Added this at @galexrt's suggestion — not being very familiar with how the `Retain` reclaim policy works in Kubernetes, I was quite surprised when I deleted PVs and found out later that the backing RBD images were still hanging around, so I think a note in the docs might be useful for others, too.
[skip ci]
> [ceph docs] Add note of RBD image retention after the corresponding PV is deleted

- Documentation/flexvolume.md
Fix indentation as described in #2662 and https://rancher.com/docs/rke/v0.1.x/en/config-options/services/services-extras/.
Also as this is a docs change, I'd like to backport to v0.9 branch.
Resolves #2662 
**Checklist:**
[skip ci]
> Fix indentation for Rancher Flexvolume docs

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/mon/spec_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/file/spec.go
- pkg/operator/ceph/nfs/spec.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
- pkg/operator/ceph/spec/spec.go
- pkg/operator/ceph/test/containers.go
- pkg/operator/k8sutil/pod.go
The mgr orchestrator modules need the container image to run the ceph image for blinking the lights when a disk is down. By setting the container image name as an env var on the pod, the orchestrator can detect the image. For consistency across the daemons it is set on all the daemons, even though only the mgr would consume it.
@liewegas @leseb 
Now all the daemon pods have these env vars generated:
```
Environment:
CONTAINER_IMAGE:  ceph/ceph:v13
POD_NAME:         rook-ceph-mon-a-85689bdf8f-nw5pl (v1:metadata.name)
POD_NAMESPACE:    rook-ceph (v1:metadata.namespace)
NODE_NAME:        (v1:spec.nodeName)
```
**Checklist:**
> Add CONTAINER_IMAGE env var to the ceph daemon pods

- cluster/charts/rook-ceph/templates/NOTES.txt
- Add to NOTES.txt the need for manually installed RBAC
- Add links to example CephCluster manifests that include match-version RBAC
As per #2454, no sample manifest has been included in the chart, only links.
Resolves #2020, #2023
[skip ci]
> Add to NOTES.txt the need for manually installed RBAC and links

- Documentation/flexvolume.md
Backport of the two changes to the flexvolume docs change.
Backport of #2759 and #2762.
Both commits are different than in the PR as there were merge conflicts.
**Checklist:**
[skip ci]
> Backport of flexvolume doc changes (#2759 and #2762)

- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/filesystem_test.go
- pkg/operator/ceph/file/mds/config.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/file/mds/spec_test.go
Separate `file` operator from `mds` tasks logically for easier code
navigation.
**Checklist:**
> ceph file: tidy up file/mds operator code

- pkg/daemon/ceph/client/filesystem.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/mds/spec.go
The MDS mds_standby_for_*, mon_force_standby_active, and mds_standby_replay
configuration options have been obsoleted. Instead, the operator may now set
the new "allow_standby_replay" flag on the CephFS file system. This setting
causes standbys to become standby-replay for any available rank in the file
system.
Closes: https://github.com/rook/rook/issues/2768
> ceph: filesystem: deprecate flags and updates for Nautilus

- pkg/operator/ceph/cluster/mon/spec_test.go
- pkg/operator/ceph/test/podspec.go
Use the new spec test lib with the mon as well.
**Checklist:**
> ceph mon: update tests with new spec test lib

- pkg/daemon/ceph/osd/agent.go
- pkg/daemon/ceph/osd/agent_test.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/device.go
- tests/framework/installer/ceph_installer.go
- tests/framework/utils/k8s_helper.go
> Ceph integration tests: add more verbose logging

- cluster/examples/kubernetes/cockroachdb/operator.yaml
- tests/framework/installer/cockroachdb_manifests.go
Signed-off-by: zhangyue <zy675793960@yeah.net>
According to [security-model](https://github.com/rook/rook/blob/master/design/security-model.md#proposed-changes), the rbac work can split into two parts:
* rbac for cockroachdb operator, which have already done but have some privileges it don't need, fix in this PR.
* rbac for cockroachdb pod, for now it only support insecure install, so I think the default serviceAccount is enough.
Resolves #1813
> cockroachdb: add minimal rbac access for cockroachdb pod

- build/common.sh
- build/makelib/common.mk
- build/run
- images/cassandra/Makefile
- images/ceph/Makefile
- images/cockroachdb/Makefile
- images/cross/Makefile
- images/edgefs/Makefile
- images/image.mk
- images/minio/Makefile
- images/nfs/Makefile
These changes make the build process support more environments by specifying alternate commands. The user can build with a custom docker command, like `make DOCKER=/path/to/docker`.
The user can build with a custom command for sha-256 hashing, like `make SHA256SUM=sha256sum`.
**Checklist:**
> Add build variables for docker and sha sum calculation

- cluster/examples/kubernetes/edgefs/cluster.yaml
Fixes https://github.com/rook/rook/issues/2795
rook-edgefs-cluster serviceaccount PSP rolebinding is missing
Resolves #2795 
**Checklist:**
> Added PSP RBAC for rook-edgefs-cluster SA

- pkg/operator/cassandra/sidecar/config.go
"unmarshaling" to "unmarshalling" in line 321.
> Fix typo in config.go

- Documentation/flexvolume.md
updated page to include information about how the flexvolume path is setup in kubespray
Signed-off-by: Mark <marklester>
Resolves #
**Checklist:**
[skip ci]
> docs: add kubespray instructions to flexvolume doc

- tests/framework/utils/k8s_helper.go
- tests/integration/filesystem_mountuser_test.go
Recently we are seeing the file mount test fail intermittently. This is an attempt to see if a simple retry will improve the reliability.
Resolves #2760
**Checklist:**
[skip ci]
> Retry the file mount integration test for stability

- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/k8sutil/node.go
Added an "Informer" to the rook-operator notification loop to get notified when either a new k8s node got added or if the NoSchedule taint got removed from a k8s node. 
Resolves #2208 
**Checklist:**
// build is passing except known CI issues
[skip ci]
> #2208 OSDs not automatically started when adding nodes to existing cluster

- build/makelib/golang.mk
Added Golang v1.12 to supported versions
Well I already got the newest Golang update and now can't run `make go.vet` and so on :cry:
**Checklist:**
[skip ci]
> Added Golang v1.12 to supported versions

- tests/integration/cockroachdb_test.go
Signed-off-by: Ryo Nakao <nakabonne@gmail.com>
The cause for the tests mentioned in the #1870 to fail is trying to create a table that already exists.
All tests fail after outputting the following.
```
kubectl exec command /cockroach/cockroach failed on pod rook-cockroachdb-operator-7d5554bdc-npv92 in namespace cockroachdb-ns-system: Failed to run: kubectl [exec -n cockroachdb-ns-system rook-cockroachdb-operator-7d5554bdc-npv92 -- /cockroach/cockroach sql --insecure --host=cockroachdb-public.cockroachdb-ns -e create database rookcockroachdb; use rookcockroachdb; create table testtable ( testID int ); insert into testtable values (123456789); select * from testtable;] : Failed to complete 'kubectl': exit status 1. . output: Error: pq: database …
```
> Add 'if not exists' to the command that creates a test database/table

- Gopkg.lock
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
- pkg/operator/ceph/cluster/mon/node.go
- pkg/operator/ceph/cluster/mon/node_test.go
- pkg/operator/ceph/cluster/mon/service.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/mon/spec_test.go
The orchestrations need to be triggered on any update to the crd. Users today restart the operator for various scenarios when the operator could take care of it automatically. If unsupported options are updated, they should just be ignored.
The subsequent change needed for this is it became apparent there was a race condition for updating the mons. There are two goroutines that are working with the mons. The first is an orchestration that is triggered by the operator at startup, or when the cluster crd is updated. The second is the health check that triggers periodically by default every 45 seconds. These goroutines must not try to make updates at the same time. A mutex is added so one will block if the other is …
> Trigger an orchestration on any crd update

- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/node_test.go
- pkg/operator/ceph/cluster/mon/spec_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/rbd/spec_test.go
- pkg/operator/ceph/file/filesystem_test.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/file/mds/spec_test.go
- pkg/operator/ceph/object/spec_test.go
- pkg/operator/ceph/spec/spec.go
- pkg/operator/ceph/test/containers.go
- pkg/operator/ceph/test/podspec.go
- pkg/operator/ceph/test/podtemplatespec.go
- pkg/operator/k8sutil/pod.go
- pkg/util/display/bytes.go
- pkg/util/display/bytes_test.go
So this is a simple first step moving torward a better utilisation of resources by the Ceph processes. This initial implementation simply relies on whatever the user specified in the daemon spec and acknowledge it.
The rest of the job is up to Ceph, for now we set the flag at daemon's initialisation but obviosuly the best way to handle that would be to have Ceph reading the `POD_` env variables and change its interval values.
I also have a commit that have been reluctant to push that enforces POD to run with a minimum amount of memory. I believe that's more intended for production clusters but might not please all the users.
But if you think we want something like this I can push it. It basically check of limits are enabled and fail if they are lower than …
> Ceph memory process tuning

- design/ceph-external-cluster.md
Commonly users may already have a ceph cluster and want a K8s cluster to connect to that ceph cluster for storage, instead of running a full ceph cluster locally. This design shows the approach that would be used for managing the external cluster while still providing an integrated rook storage experience.
**Checklist:**
[skip ci]
> Design: Managing an external ceph cluster

- Documentation/edgefs-nfs-crd.md
- Documentation/edgefs-s3-crd.md
- Documentation/edgefs-s3x-crd.md
Uppercase symbols are not allowed in k8s objects
Signed-off-by: Dmitry Mishin <dmitry.mishin@gmail.com>
Modified the documentation examples to have proper k8s names
Resolves #
**Checklist:**
[skip ci]
> Fixed k8s object names

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/node.go
- pkg/operator/ceph/cluster/mon/node_test.go
The desired number of mons could change depending on the number of nodes in a cluster. For example, three mons would be the min number of mons in a production cluster with at least three nodes. If there are five or more nodes, the number of mons could increase to five in order to increase the failure tolerance to two nodes.
This is accomplished by a new setting in the cluster CRD preferredCount. If the number of hosts exceeds preferredCount, more mons are added to quorum. If the number of hosts drops below the preferred count, the operator would reduce the quorum size to the smaller desired count.
The implementation of increasing and decreasing mons is already implemented in the health check, so this change is …
> Increase the number of mons when nodes are added

- images/ceph/Makefile
- pkg/daemon/ceph/client/image.go
- pkg/daemon/ceph/client/image_test.go
- tests/framework/clients/nfs.go
- tests/framework/clients/test_client.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v0.9.go
- tests/integration/base_block_test.go
- tests/integration/base_file_test.go
- tests/integration/helm_test.go
- tests/integration/multi_cluster_test.go
- tests/integration/smoke_test.go
- tests/integration/upgrade_test.go
With the v1.0 release we will plan on supporting nautilus. With that in mind, we should start running some integration tests on nautilus. This change moves the SmokeSuite over to nautilus, while also adding a test for starting the ceph nfs daemons with the new crds.
**Checklist:**
> Base the rook ceph operator on Nautilus

- Documentation/edgefs-csi.md
- cluster/examples/kubernetes/edgefs/csi/iscsi/edgefs-iscsi-csi-driver-config.yaml
- cluster/examples/kubernetes/edgefs/csi/nfs/edgefs-nfs-csi-driver-config.yaml
Add multiple EdgeFS clusters support for CSI configuration files
Resolves #2878
**Checklist:**
> Edgefs #2878. Add multiple cluster support for CSI driver

- tests/scripts/kubeadm-install.sh
This adds the kubernetes-cni package for integration tests. This is a required component and was blocking the integration testing steps. 
Resolves # [2906](https://github.com/rook/rook/issues/2906)
**Checklist:**
> Adding install for kubernetes-cni for integration tests

- Documentation/ceph-dashboard.md
- cluster/examples/kubernetes/ceph/dashboard-ingress-https.yaml
The examples folder has Service examples but no Ingress examples. This example Ingress is important because it demonstrates how to configure and Ingress that will work with the self-signed certificate the `rook-ceph` installs. The Service name and Namespace matches the default `rook-ceph` install.
Resolves #2433 
[skip ci]
> Add a Kubernetes Ingress example for dashboard

- Documentation/k8s-pre-reqs.md
The RBD module is an important prerequisite for Rook. It is mentioned as a possible problem on the Common Issues page, but that is the ambulance at the bottom of the cliff 😄. We should mention the perquisite for new users, tell them how to check, and note any major Kubernetes-as-a-service providers that do not have the RBD module.
https://rook.io/docs/rook/master/common-issues.html#rook-agent-rbd-module-missing-error
Resolves:
#2448 
[skip ci]
> Document the RBD module prerequisite for Rook Ceph

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
- pkg/operator/ceph/test/containers.go
pass env vars with rook-ceph-system namespace and API version to
ceph-mgr containers to remove hardcoded values from rook orchestrator in
ceph-mgr
Resolves #2843 
**Checklist:**
> ceph: update env vars for ceph-mgr containers

- pkg/operator/ceph/version/version.go
Now we are able to detect a Ceph Octopus version.
**Checklist:**
> ceph: add support octopus version detection

- cluster/charts/rook-ceph/templates/deployment.yaml
Bind `DISCOVER_TOLERATION` env variable to `.Values.discover.toleration` (instead of `agent`)
Signed-off-by: Olivier Cloirec <5033885+clook@users.noreply.github.com>
Bind `DISCOVER_TOLERATION` env variable to `.Values.discover.toleration` (instead of `agent`)
Resolves #2927
**Checklist:**
> Fix Helm Chart `DISCOVER_TOLERATION` binding

- design/ceph-csi-driver.md
Update the design doc for supporting Ceph CSI (at version 1.0) in Rook. Adds an overview of topics needed to smoothly use CSI from Rook.
**Checklist:**
[skip ci]
> Ceph-CSI 1.0 support and integration doc update

- pkg/operator/ceph/object/user/controller.go
- tests/framework/clients/object_user.go
- tests/integration/base_object_test.go
When deleting a CephObjectStoreUser the deleteUser function
attempts to delete the stored secret using the wrong name. This
patch updates deleteUser to use the same fmt.Sprintf call used in
the createUser function
Updated the Secrets().Delete() in deleteUser() to use the use the same format as the Secrets().Create()
in createUser().
Resolves #2660
**Checklist:**
> Deleting CephObjectStoreUser does not delete secret

- pkg/daemon/ceph/client/auth.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
- pkg/operator/ceph/cluster/mon/service.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/config/keyring/store.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/k8sutil/daemonset.go
- pkg/operator/k8sutil/deployment.go
- pkg/operator/k8sutil/k8sutil.go
- pkg/operator/k8sutil/name.go
- pkg/operator/k8sutil/pod.go
- pkg/operator/k8sutil/replicaset.go
- pkg/operator/k8sutil/service.go
- pkg/operator/k8sutil/statefulset.go
- pkg/operator/test/deployment.go
- tests/integration/upgrade_test.go
The Ceph mon flag `--public-bind-addr` does not keep the same port as
the previous daemon run when the port is left off the flag's value. A
port is undesired since that could interfere with Nautilus' msgr2
protocol, so instead configure the mon's services to forward the default
bind port on pods (6789) to the mon endpoint's port. The endpoint port
will be 6789 for new mons, but it may be 6790 for legacy clusters.
Resolves #2854 
**Checklist:**
> ceph: fix for masked upgrade failures and getting integrations running again

- ROADMAP.md
[skip ci]
Update roadmap with recent triage of v1.0 release.
There are 2 commits here:
- commit 1 is a very granular, technical roadmap
- commit 2 is more genercized, and I believe the direction we want the roadmap to go in.
Developers should be able to compare the two commits to make sure the more generalized commit doesn't remove any important information. When there is approval, these 2 PRs will be squashed. 
Who else should I add as reviewers from the various storage backend groups?
Should I include the April 1 (5th?) estimated Rook v1.0 release date?
> Roadmap: update for recent v1.0 triage

- PendingReleaseNotes.md
- pkg/operator/ceph/version/version.go
- pkg/operator/ceph/version/version_test.go
- tests/framework/installer/ceph_installer.go
With the release of Ceph Nautilus (v14), Rook needs to add official support for Nautilus for the 1.0 release.  
This PR is initially simply moving Nautilus to the list of supported versions. Testing still needs to be done to verify if there are any remaining functionality missing.
**Checklist:**
> Add nautilus to the list of supported Ceph versions

- images/ceph/Dockerfile
Commit 91cc62676d95783dfff7190993f3261d73def6ab changed our base ceph
version from Mimic to Nautilus.
Update the comment in the Dockerfile to reflect this change.
[skip ci]
> images: remove comment about ceph mimic image

- Documentation/ceph-csi-drivers.md
- cluster/examples/kubernetes/ceph/operator-with-csi.yaml
- cmd/rook/ceph/operator.go
- images/ceph/Dockerfile
- images/ceph/Makefile
- pkg/operator/ceph/csi/spec.go
This PR implements some of lthe lowest hanging fruit for improvements in the intergration of ceph csi mentioned in PR #2857.
It simplifies the globally enabling CSI and reduces the delta between the configuration of Rook when deploying for flex vs deploying for CSI.
Still TODO: updating docs to match
Resolves #
**Checklist:**
[skip ci]
> Simplify Ceph CSI setup

- pkg/daemon/ceph/client/filesystem.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/filesystem.go
A ceph filesystem was brought down by marking the filesystem as down and individually failing the MDSes. From nautilus onwards, this could be more simply and efficiently done by using `fs fail` command. See, https://github.com/ceph/ceph/commit/4c49f165ec1
Resolves: #2841
Signed-off-by: Ramana Raja <rraja@redhat.com>
[skip ci]
>  ceph filesytem: use `fs fail` to bring down filesystem

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/k8sutil/daemonset.go
- pkg/operator/k8sutil/deployment.go
- pkg/operator/k8sutil/job.go
- pkg/operator/k8sutil/k8sutil.go
[skip ci] to merge due to random build failures.
Add a `rook-version` label to all controller resources used by Ceph:
deployments, daemonsets, and jobs. Labels are added to controller
resources only and not to the pod templates within because changing pod
templates causes updates due to the label change. The controller
resources themselves are not updated with the label addition and
therefore don't cause an unnecessary upgrade.
While this *is* a feature, this will be very helpful for the v1.0 upgrade docs since there isn't a good way to explain to users how to know when Rook is done upgrading/updating their cluster. With this, it will be possible to write a one-liner that will allow them to see the Rook version associated with all …
> ceph: add 'rook-version' label to controllers

- pkg/daemon/ceph/agent/flexvolume/controller.go
- pkg/operator/ceph/provisioner/provisioner.go
This fixes issues for users trying to delete volumes and failing because
they only have `clusterNames` set on them in Rook earlier v0.8.
Resolves #2373
**Checklist:**
> rookflex: Use `clusterName` if available for backwards compatibility

- pkg/operator/ceph/cluster/controller.go
the k8s Node add/update events can fire before a cluster is fully
configured, which may leave some state undefined. skip orchestration
when the cluster is in this state.
fixes: #3001
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
// for known CI issues
[skip ci]
> ceph: skip orch on non-ready clusters

- pkg/operator/ceph/cluster/osd/spec.go
When Ceph OSD spins up with ceph-volume `lvs` is run which can cause
significant delays without mounting /run/udev from the host.
Before:
```
[root@rook-ceph-osd-0-858f49b5-md4t9 /]# time lvs
WARNING: Failed to connect to lvmetad. Falling back to device scanning.
WARNING: Device /dev/sda not initialized in udev database even after waiting 10000000 microseconds.
...
LV                                            VG                                        Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
osd-data-729c1fb6-440f-434c-be49-f199fa59f1c0 ceph-3bf7823b-6db3-42b6-bf8f-c36301e85238 -wi-ao---- <10.00g
real    1m30.545s
```
After:
```
[root@rook-ceph-osd-0-d8c4698b8-5vqnk /]# time lvs
WARNING: Failed to connect to lvmetad. Falling back to device scanning.
LV …
```
> ceph/osd: mount /run/udev for lvs speedup

- Documentation/ceph-csi-drivers.md
* common.yaml is pre-req for deploying the ceph cluster, as ceph-csi has a pre-req to deploy rook operator and create  ceph cluster, we can  remove the common.yaml  from ceph-csi doc
* updated the resource cleanup order for the RBD
Resolves #
**Checklist:**
[skip ci]
@travisn @phlogistonjohn PTAL
> rearrange RBD resource cleanup order in ceph-csi doc

- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/k8sutil/deployment.go
Because the deployment update-and-wait function waits for the deployment
to be ready, and that cannot happen due to the keyring not
having been updated yet. The keyring has its
owner set to the deployment so that no special keyring handling must
be done, but it must be created after the deployment UID is known.
Change the order of operations so that the existing deployment's UID can
be retrieved if it exists and the keyring created/updated before the
update-and-wait function is called.
This order-of-operations issue currently only applies to the mds. Other
daemons whose keyrings are owned by the replication controller do not
use the update-and-wait function.
Resolves #2989 …
> ceph mds: update keyring before deployment update

- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
When ceph-volume is called, the default python logging will buffer everything until
the process exits, which means the pod log doesnt show what is happening
until ceph-volume is done. This change will allow logs to be written
immediately as tasks are performed inside ceph-volume
**Checklist:**
[skip ci]
> Write ceph-volume log entries as they occur

- PendingReleaseNotes.md
- pkg/daemon/discover/discover.go
- pkg/daemon/discover/discover_test.go
- pkg/operator/ceph/cluster/controller.go
Respond to new block devices promptly by running an orchestration round.
1. watch the device configmap and trigger new orchestration on change
2. monitor udev for block device changes and run a device probe (which may update the config map)
fixes: #1435 
[skip ci]
> ceph udev monitor / hotpluggin

- PendingReleaseNotes.md
- pkg/daemon/ceph/client/osd.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/osd/status.go
Set noout when a kubernetes node is moved to maintenance, and unset when no nodes are in maintenance
Resolves #2825
**Checklist:**
**TODO**
[skip ci]
> Ceph: Set noout on cluster when storage nodes are in maintenance

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/charts/rook-ceph/values.yaml.tmpl
- tests/framework/installer/cassandra_installer.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/cockroachdb_installer.go
- tests/framework/installer/edgefs_installer.go
- tests/framework/installer/nfs_installer.go
- tests/framework/utils/k8s_helper.go
- tests/integration/base_object_test.go
Two updates for the helm chart:
1. When looking into the intermittent integration test issues, a major cause of failures is that the helm chart tests frequently time out when waiting for the object or file CRs to install. The daemons don't start up in the expected time. In a local test of the helm chart I also saw that creating these CRs takes a lot longer than expected. When running inside the helm chart it takes over 3 minutes to create an object store instead of 30-45 seconds when not using the helm chart. The issue is that the helm chart limits the operator pod to 1/10 of a CPU. In general this is plenty since the operator is frequently dormant, but during an orchestration the operator should be able to burst higher. Now the operator can burst up to …
> Helm chart: Improve operator performance and add CephNFS CRD

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- pkg/operator/ceph/cluster/mon/mon.go
- tests/integration/upgrade_test.go
This code path is no longer necessary, and removing it allows removing
the `replicasets` RBAC permission for the operator.
**Checklist:**
[skip ci]
> ceph mon: remove code to delete legacy replicasets

- Documentation/edgefs-csi.md
Adding a raw tag wrapper tells liquid to ignore this section and compile
this text without trying to interpret it. Otherwise an error is thrown
during builds
**Checklist:**
[skip ci]
> This prevents a liquid template error during jekyll build

- Jenkinsfile
This change will cause master and release builds to be published before the integration tests are run. There are some positive and negative aspects to this:
PROS:
- Published builds match what has been merged
- Random integration test failures don't block the publishing of the build
CONS:
- If there is a significant failure shown by the integration tests, the build will be published anyway
I wouldn't be surprised if there is much debate around this, but the reality of the situation is that the random failures in integration tests are too painful not to do this. It doesn't mean we deprioritize fixing the integration test issues, but this will help us ensure our published images match what has been merged to the …
> Publish the build independent from the integration test results

- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/spec/label.go
Add 'rook-version' label to Ceph mon services, as it could be useful
there during upgrades as well.
Add a 'ceph-version' label to application controllers in the same manner
as the prior 'rook-version' label to help with upgrades.
Resolves #
**Checklist:**
[skip ci]
> Add `ceph-version` labels to Ceph application controllers

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-quickstart.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
Nautilus is now the recommended version to install with Rook. The documentation and example manifests are updated to reflect this recommendation.
**Checklist:**
[skip ci]
> Set nautilus as the default Ceph version to deploy

- Documentation/common-issues.md
- PendingReleaseNotes.md
- build/codegen/codegen.sh
- pkg/client/clientset/versioned/typed/ceph.rook.io/v1/ceph.rook.io_client.go
- pkg/client/clientset/versioned/typed/ceph.rook.io/v1/cephnfs.go
- pkg/client/clientset/versioned/typed/ceph.rook.io/v1/fake/fake_ceph.rook.io_client.go
- pkg/client/clientset/versioned/typed/ceph.rook.io/v1/fake/fake_cephnfs.go
- pkg/client/informers/externalversions/ceph.rook.io/v1/cephnfs.go
- pkg/client/informers/externalversions/ceph.rook.io/v1/interface.go
- pkg/client/informers/externalversions/generic.go
- pkg/client/listers/ceph.rook.io/v1/cephnfs.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/controller_test.go
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/nfs/nfs.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/controller_test.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
- tests/framework/clients/nfs.go
The CR controllers were previously all acting independently and there was not a pattern for communicating to trigger orchestrations in other controllers. In particular, the CephCluster CR is the parent of each of the other CRs. If the CephCluster is updated, the daemons started by the others CRs (mds, rgw, nfs) may need to be updated as well, for example if the Ceph version is updated. Now the daemons will be updated without requiring an operator restart.
When calling the controllers from another controller, we ensure that only a single goroutine is handling CRs at any given time to prevent contention across multiple CRs of the same type. The same locking pattern is used that the mon health check is using to coordinate with the CephCluster updates.
As an …
> Upgrade all daemons during Ceph upgrade

- pkg/daemon/ceph/client/upgrade.go
- pkg/daemon/ceph/client/upgrade_test.go
- pkg/daemon/ceph/config/config.go
- pkg/operator/ceph/cluster/mon/mon.go
This commits allows the upgrade from Mimic to Nautilus to work by:
* removing the v2 brackets on the operator ceph config file generation,
we stick with v1 and can revert this back once we deprecate mimic there
is no rush since mons keep on listening to v1.
* enable messengers 2 when the cluster runs on Nautilus
Fixes: https://github.com/rook/rook/issues/2973
[skip ci]
> Ceph: fix upgrade to Nautilus

- cluster/examples/kubernetes/minio/operator.yaml
**Description of your changes:** Adds the missing `update` verb to the minio RBAC which is now needed since the minio operator does updates in its reconcile loop
Resolves #3043 
**Checklist:**
[skip ci]
> minio: add necessary update verb in minio RBAC

- pkg/daemon/ceph/client/mgr.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/dashboard_test.go
- pkg/operator/ceph/cluster/mgr/mgr.go
The mgr listens on the wrong ports.
A config dump looked like that:
```
WHO                     MASK LEVEL    OPTION                            VALUE        RO 
mgr                        advanced mgr/orchestrator_cli/orchestrator rook         *  
mgr.                     advanced mgr/dashboard/server_port         7000         *  
mgr.                     advanced mgr/dashboard/ssl                 false        *  
```
It should be mgr.a
Resolves #2875
**Checklist:**
[skip ci]
> Fix mgr settings

- PendingReleaseNotes.md
- pkg/daemon/ceph/client/osd.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/osd/status.go
This reverts commit b7a564e929f85fdb17c2bc45c5fae264b7f13b1f, reversing
changes made to 6996571b5c53474d1354c9e19b00abea404585e7.
Revert requiring setting noout on detecting a NoSchedule taint.
Resolves #3014 
[skip ci]
> Revert "Merge pull request #2986 from rohantmp/mainMon"

- pkg/daemon/ceph/config/config.go
- pkg/operator/ceph/config/store.go
This commits fixes the upgrade for cluster running on 0.9.x and thus
have monitors listening on 6790.
The only downside is that the new messengers 2 protocol can not be
enabled because Ceph expects monitors to listen on 6789.
In order to enable messengers 2 your monitors will have to failover so
they can pick up both 6789 and 3300 ports, then and only then messenger
2 can be enabled.
Fixes: https://github.com/rook/rook/issues/3048 and
https://github.com/rook/rook/issues/3049
> ceph: fix upgrade for monitor listening on 6790 port

- Jenkinsfile
- tests/scripts/helm.sh
- tests/scripts/minikube.sh
Since k8s 1.14 was released recently, this will now add k8s v1.14.0 to the integration test matrix. At the same time, the other supported versions are updated in the CI to a more recent version.
Resolves #2918 
**Checklist:**
[skip ci]
> Add k8s 1.14 to the integration test matrix

- pkg/daemon/ceph/client/osd.go
- pkg/operator/ceph/cluster/osd/osd.go
Setting `noscrub` during osd orchestration raises ceph health warnings since the feature is disabled. Users of the ceph dashboard are seeing this more often as the operator is triggering the orchestration more often when adding nodes or devices. Per @liewegas the `noscrub` really doesn't need to be set by rook. 
Resolves #1703 
**Checklist:**
[skip ci]
> Ceph: Stop disabling scrubbing during osd orchestration

- pkg/daemon/discover/discover.go
- pkg/operator/ceph/cluster/controller.go
this is an attempt to reduce the number of false positive config map
updates used to trigger orchestration for hotpluggin
Which issue is resolved by this Pull Request: Resolves #3029
[skip ci]
> ceph: check for equiv device config maps in operator

- pkg/operator/ceph/cluster/controller.go
this skips orchestration when the device configmap receives an update
but the cluster hasn't been fully configured, which may leave some state
undefined and cause nil pointer dereferences accessing the cluster info
structure.
Resolves #3001
> ceph: skip orchestration when cluster is not yet configured

- Documentation/helm-operator.md
- PendingReleaseNotes.md
- build/release/Jenkinsfile.promote
- build/release/Makefile
- build/release/README.md
The `alpha`, `beta`, and `stable` channels do not match the rook release process. Each storage provider defines their own stability based on the CRDs rather than defining it with the release process. Rook really only has two release streams: master and the official releases. Master is published with each merge, while releases go through a signoff process to ensure quality. Thus, the `alpha`, `beta`, and `stable` channels are removed and replaced with a single `release` channel. See [the detailed notes on this change](https://github.com/rook/rook/issues/1885#issuecomment-460444455).
The `release` channel is only used for promoting the helm chart. The docker images do not receive a channel tag so the versioning …
> Promote builds to master and release rather than alpha, beta, and stable

- tests/scripts/k8s-vagrant-multi-node.sh
Signed-off-by: Santosh Pillai sapillai@redhat.com
"test/scripts/k8-vagrant-multi-node.sh up ceph" was giving syntax error. Removed the braces around OR statement in the git pull command. 
Resolves #3034
**Checklist:**
[skip ci]
> Add missing semicolon to k8-vagrant-multi-node.sh file to fix syntax error

- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- pkg/daemon/ceph/osd/agent.go
- pkg/daemon/ceph/osd/volume.go
When this change, I can place block-db of multiple OSDs on a ssd, simply with what `ceph-volume lvm batch` already does.
for an osd node with 1 ssd (sdb) and 3 hdd:
```
sdb                                                                                                                     8:16   0   20G  0 disk 
├─ceph--block--dbs--f95e4aba--9900--403a--9d2c--6fbb55e71710-osd--block--db--15c7a93a--4c41--4aac--8388--d4a30eb861cf 252:1    0    6G  0 lvm  
├─ceph--block--dbs--f95e4aba--9900--403a--9d2c--6fbb55e71710-osd--block--db--732d4aa5--ce75--4c3e--a10f--d7dff89160f1 252:3    0    6G  0 lvm  
└─ceph--block--dbs--f95e4aba--9900--403a--9d2c--6fbb55e71710-osd--block--db--f8e9d19d--26e0--4b6b--bae0--8a44a2795f74 252:5    0    6G  0 lvm  
sdc …
```
> Support metadataDevice for ceph-volume based osd

- pkg/operator/ceph/cluster/mgr/spec.go
Fix this issue: https://github.com/rook/rook/issues/1796 ; set mgr Replicas=2 for HA, two mgrs run normally : the active mgr pod accesses metrics normally, the standby mgr pod accesses metrics return empty.
my test environment:
rook version: master
ceph version: v13
mgr Cluster.Replicas: 2
after my change, ceph config as shown below:
[root@ceph-wangxiao-test1 diamond]# ceph config dump
WHO   MASK LEVEL   OPTION                       VALUE                                                        RO 
mgr      unknown mgr/dashboard/a/server_addr  10.107.1.232                                                 *  
mgr      unknown mgr/dashboard/b/server_addr  10.107.1.235                                                 *  
mgr      unknown mgr/dashboard/password …
> Set mgr daemon name in server_addr config setting path

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
- pkg/operator/ceph/version/version.go
- pkg/operator/ceph/version/version_test.go
this reverts binding to the pod IP which was added to deal with a bug in
cherrypy when binding to the default anyaddr "::". this has been
resolved in ceph, so we can eliminate this workaround.
fixes: #2492
> ceph: dashboard/prom should bind to anyaddr

- PendingReleaseNotes.md
- cmd/rookflex/cmd/init.go
- pkg/daemon/ceph/agent/flexvolume/server.go
- pkg/daemon/ceph/agent/flexvolume/server_test.go
- pkg/operator/ceph/provisioner/provisioner_test.go
The settings for `ROOK_ENABLE_SELINUX_RELABELING` and `ROOK_ENABLE_FSGROUP` have been ignored since `v0.9.3`. The flex settings cannot be passed to the driver with environment variables. There is no context available for returning the flex settings except that the flex driver can look in a config file in the same directory. When the flex driver is copied to the flex directory, the settings will also be written in a "flex.config" file in the same directory. The flex driver will look in its current directory for these settings. If there is an error loading the file, the default settings will be used.
At the same time, the second commit will remove obsolete version checks for unsupported versions of K8s. The flex driver no longer needs to check whether a …
> Ceph Flex driver: properly configure SELinuxRelabeling and FSGroup settings

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/nfs/nfs.go
- pkg/operator/k8sutil/job.go
The ceph controller will delete and recreate the detect-version job, when
an already existing job is found. This helps avoid cluster creation from
getting hung up on waiting for an already existing/stale job to finish.
Fixes #3081.
**Checklist:**
[skip ci]
> ceph: Delete and recreate rook-ceph-detect-version job

- Documentation/k8s-pre-reqs.md
**Description**
As discussed in Issue 2591 (https://github.com/rook/rook/issues/2591) the lvm2 package may be missing from some Linux distributions, this documentation update alerts the user to this pre-req.
**Resolves**
[Issue 2591](https://github.com/rook/rook/issues/2591)
Signed-off-by: Sachin Agarwal <sachinkagarwal@gmail.com>
**Checklist:**
@travisn - as discussed on Slack
[skip ci]
> Add lvm2 package to pre-reqs in docs

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- tests/framework/installer/ceph_installer.go
With the nautilus 14.2.1 image now generated in the `ceph/ceph` dockerhub, we can update the latest examples that rook is using.
**Checklist:**
[skip ci]
> Ceph: Update tests and examples to Nautilus 14.2.1

- Documentation/edgefs-cluster-crd.md
- pkg/apis/edgefs.rook.io/v1beta1/cluster.go
- pkg/operator/edgefs/cluster/target/pod.go
- pkg/operator/edgefs/cluster/utils.go
- tests/framework/installer/edgefs_manifest.go
Add optional container count parameter into devicesResurrectMode cluster CRD option
Resolves #3087
**Checklist:**
> Add optional containers count for restore/zap option

- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/spec.go
when upgrading to a newer version of ceph that doesn't need the http
binding fix, this patch unwinds the configuration fix which may still be
present when upgrading from a cluster without the fix. if the
configuration fix remains then the dashboard and prometheus servers will
not be able to properly configure themselves.
Resolves n/a
> ceph: rewind http bind fix on upgrade

- pkg/operator/edgefs/cluster/target/pod.go
- pkg/operator/edgefs/iscsi/iscsi.go
- pkg/operator/edgefs/isgw/isgw.go
- pkg/operator/edgefs/nfs/nfs.go
- pkg/operator/edgefs/s3/s3.go
- pkg/operator/edgefs/s3x/s3x.go
- pkg/operator/edgefs/swift/swift.go
K8S_NAMESPACE env been added to specific EdgeFS containers
Resolves #3097
**Checklist:**
[skip ci]
> Add K8S_NAMESPACE env to EdgeFS containers

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/k8sutil/node.go
This removes the unnecessary check for taints on nodes in the
`GetNodeSchedulable()` function. This fixes that even though the user
has specified `tolerations` for, e.g., `NoSchedule` taints, that would
be ignored and the node(s) directly be "marked" as unschedulable.
Resolves #3050.
**Checklist:**
[skip ci] Added due to known CI issues
> ceph-op: Remove taint check in "is node scheduable" func

- pkg/daemon/ceph/osd/init.go
Before performing the copy, the OSD init container now checks
destination path exists, and unlinks it if it does.
The OSD pods copy the rook and tini binaries into a shared volume using
an init container. In restarting pods, this copy could fail with 'text
file busy'(ETXTBUSY), because the destination file in the shared volume
could be under execution. The restarting pods will enter a
'Init:CrashLoopBackOff' state after this, leaving the ceph cluster
degraded.
Unlinking the destination file before copying will allow the copy to
successfully complete and the pod to restart successfully. This leaves a
stale file in the shared volume, which will be cleaned up when the
process that was executing it exits.
Fixes #2674.
**Checklist:**
> ceph: Check before copying binaries in osd pods

- images/ceph/Makefile
ceph image v14.2.0-20190319 has 3 high vulnerabilities so
updated it to v14.2.1-20190430
Resolves #3120 
**Checklist:**
> Updated ceph image from v14.2.0-20190319 to v14.2.1-20190430

- pkg/daemon/ceph/osd/agent_test.go
- pkg/daemon/ceph/osd/volume.go
- Provision OSDs when metadataDevice is set instead of only running a ceph-volume report.
- Add ceph-volume report prior to provisioning to log what ceph-volume will configure before configuring it.
Resolves #3108
[skip ci]
> ceph: provision OSDs with metadataDevice config

- pkg/operator/ceph/cluster/mon/node_test.go
- pkg/operator/ceph/cluster/mon/spec.go
Clusters using host networking will not work if the non-default port is being used by the mons. Previous to rook 1.0 the mons were all using the non-default port 6790 and now they are using the default port of 6789 from 1.0. Now host networking will preserve the non-default port to allow upgrades to continue working.
This change will allow the mons to continue working on the non-default port after upgrade. However, the mons cannot enable msgr2 with this configuration. The mons will need to be failed over so they will start using the default ports before msgr2 can be enabled. This will also be added to the upgrade doc.
Resolves #3111 
**Checklist:**
> Ceph: Preserve the non-default port during upgrade for hostnetworking

- cluster/charts/rook-ceph/templates/clusterrole.yaml
1b21e42a90c3a452b6ac736122ce0c60ca64fa89 introduced a regression, where
podsecuritypolicy resource has been changed from 'extensions' group to
'apps', when it should be changed to 'policy'.
This prevents rook operator from spawning on a cluster with PSP enabled.
Resolves #
**Checklist:**
> helm: fix PSP use cluster role

- pkg/daemon/ceph/osd/agent_test.go
- pkg/daemon/ceph/osd/volume.go
Signed-off-by: Michael Vollman michael.b.vollman@gmail.com
- Provision OSDs when metadataDevice is set instead of only running a ceph-volume report.
- Add ceph-volume report prior to provisioning to log what ceph-volume will configure before configuring it.
Resolves #3108
(cherry picked from commit a8395274218fa28da0726fc3ad6c003df9a48e7c)
[skip ci]
> Backport: Provision OSDs with metadataDevice config

- Documentation/ceph-upgrade.md
- pkg/operator/ceph/cluster/mon/node_test.go
- pkg/operator/ceph/cluster/mon/spec.go
Two upgrade fixes backported to 1.0:
- Documentation: The default mon port has changed from 6790 to 6789. With the msgr2 work in nautilus, the mons need to be listening on the default ports. These instructions will direct users to failover the mons to the new default port.
- Clusters using host networking will not work if the non-default port is being used by the mons. Previous to rook 1.0 the mons were all using the non-default port 6790 and now they are using the default port of 6789 from 1.0. Now host networking will preserve the non-default port to allow upgrades to continue working. This change will allow the mons to continue working on the non-default port after upgrade. However, the mons cannot enable msgr2 with this configuration. The mons will …
> Backport: Ceph host networking upgrade and document mon failover after upgrade

- Documentation/ceph-teardown.md
This corrects the cleanup instructions to delete operator.yaml but also
common.yaml to remove the reamining objects in one go.
Resolves #3148 
**Checklist:**
[skip ci]
> docs: added missing delete for new manifest structure

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- pkg/apis/rook.io/v1alpha2/types.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/edgefs/cluster/utils.go
- pkg/operator/k8sutil/node.go
- pkg/operator/k8sutil/node_test.go
This PR reads the labels on a Kubernetes node, looking for provider topology information (e.g. `failure-domain.kubernetes.io`) and appending any it found to the Ceph OSD location.
Resolves #2883
**Checklist:**
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>
> Read node labels for provider topology

- Documentation/ceph-pool-crd.md
- PendingReleaseNotes.md
- pkg/apis/ceph.rook.io/v1/blockpool.go
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/apis/ceph.rook.io/v1beta1/pool.go
- pkg/apis/ceph.rook.io/v1beta1/types.go
- pkg/daemon/ceph/client/erasure-code-profile.go
- pkg/daemon/ceph/client/erasure-code-profile_test.go
- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
- pkg/daemon/ceph/model/pool.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
- Updated code to use deviceClass property when a pool is created for both "replicated" and "erasure coded".
- Updated (ceph-pool-crd.md )documentation to reflect the changes. 
- One know [issue](https://github.com/rook/rook/issues/2016) is reproducible when updating erasure code pool with different settings - 
Resolves #2890 
**Checklist:**
[skip ci]
> added device class pool property

- Documentation/edgefs-csi.md
- cluster/examples/kubernetes/edgefs/cluster.yaml
- pkg/operator/edgefs/cluster/target/pod.go
Statefulset pod's template antiAffinity changed
Resolves #3181
**Checklist:**
[skip ci]
> Edgefs: Prevents multiple targets deployment on the same node

- tests/scripts/minikube.sh
The minikube script now uses the proper disk path (vda) when minikube is
configured to run with the libvirt driver.
Resolves #
**Checklist:**
> tests/scripts: Fix minikube script for libvirt

- pkg/daemon/ceph/agent/flexvolume/server.go
This allows to export persistent volume metrics.
Signed-off-by: Maksim Nabokikh <maksim.nabokikh@flant.com>
According to https://github.com/kubernetes/kubernetes/issues/67400 in kubernetes 1.13 metrics support for flex volume was added.
I wonder, is adding support metrics flag enough to fix the issue?
Resolves #1659
**Checklist:**
> ceph: add metrics for flexvolume driver

- Documentation/ceph-upgrade.md
[skip ci]
The sed replace step is prerequisite for the toolbox step but was listed
after. Fix this.
I labeled this backport since it affects an older release version, but it isn't a backport per se, as this bug doesn't exist in master.
Resolves #2394
**Checklist:**
> Doc: ceph upgrade: move sed step before toolbox

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/nfs/spec.go
Fix the host path for the Ceph NFS pod's log volume
Resolves #3139 
**Checklist:**
> ceph nfs: fix the host path for pod volume

- tests/scripts/k8s-vagrant-multi-node.sh
This fixs that the `git describe` is run with the `-C REPO_PATH` flag to
correctly get the latest tag of the k8s-vagrant-multi-node repo and not
the Rook repository.
Resolves the issues @jbw976 had in Slack #dev channel (https://rook-io.slack.com/archives/C741SA742/p1558197621001100).
**Checklist:**
[skip ci]
> tests: fix git describe repo path in k8s-vagrant-multi-node script

- tests/scripts/minikube.sh
Default to virtualbox driver. `minikube config get vm-driver` does not
work when default is used.
Resolves #3208
**Checklist:**
[skip ci]
> tests/scripts: Fix minikube script

- Documentation/ceph-upgrade.md
version 0.9 of the upgrade doc is located at ceph-upgrade.html not upgrade.html
Signed-off-by: Andrew Lavery <laverya@umich.edu>
Docs were updated to fix the link to the 0.8->0.9 ceph upgrade instructions (from the 0.9->1.0 ceph upgrade instructions doc)
Resolves #
**Checklist:**
[skip ci]
> docs: fix ceph upgrade 0.8->0.9 docs link

- cluster/examples/kubernetes/ceph/operator.yaml
[skip ci]
This commit fixes misaligned example values in operator.yaml and adds a
newline at the end of the file, which is considered a good practice.
Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>
**Checklist:**
> ceph/operator.yaml: fix alignment and add newline

- cluster/olm/ceph/generate-rook-csv.sh
With operator-sdk version 0.8.1, default csv file is created with following message:
```
NFO[0000] Created deploy/olm-catalog/ceph/1.0.1/ceph.v1.0.1.clusterserviceversion.yaml
```
Without this patch, `mv` in the script fails, as default file does not
exist.
I honestly don't know if this is the right approach, since I never generated such CSV files, but I've made some whitespace changes in #3240 and I wanted to test them and I found that this is not really working for me.
Logs from the error I saw:
```
$ bash -x cluster/olm/ceph/generate-rook-csv.sh 1.0.1 k8s rook/ceph:v1.0.1
+ set -e
+ OLM_CATALOG_DIR=cluster/olm/ceph
+ CSV_PATH=cluster/olm/ceph/deploy/olm-catalog
+ DEFAULT_CSV_FILE_NAME=cluster/olm/ceph/deploy/olm-catalog/ceph.csv.yaml
+ …
```
> generate-rook-csv.sh: fix DEFAULT_CSV_FILE_NAME

- Makefile
- cluster/olm/ceph/README.md
- cluster/olm/ceph/generate-rook-csv.sh
[skip ci]
0fc3775b990d0c79356be33f8fc8416a897560fc added `csv-ceph` Makefile target, but in documentation and examples it was inconsistently referred as `csv`. This PR makes things consistent.
Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>
**Checklist:**
> Fix inconsistency regarding csv-ceph Makefile target

- pkg/daemon/ceph/osd/agent.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- Updated getCephVolumeOSDs method to use fsid filter while retriving devices.
- This solves "failed to fetch mon config (--no-mon-config to skip)" error when multiple ceph clusters are running on same Node
- Multiple ceph clusters on single node creates incorrect UUID in the "getCephVolumeOSDs" method. 
- This results in OSD failures with "failed to fetch mon config (--no-mon-config to skip)"  error.  
- Updated getCephVolumeOSDs to filters available devices based on ceph FSID
- Updated unit tests to handle this case. 
Resolves #2696
**Checklist:**
[skip ci]
> use ceph fsid to filter ceph volume OSDs

- pkg/operator/ceph/cluster/osd/health.go
for the osd recovery case (DOWN->UP) log at a matching log level as the
message indicating the OSD went down.
fixes: #2904
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
[skip ci]
> ceph: log osd recovery at info level

- PendingReleaseNotes.md
- pkg/operator/ceph/object/spec.go
We now check if the pod responds on http port 80.
**Checklist:**
[skip ci]
> ceph: rgw add liveness probe check

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-rules.yaml
Added latest prometheus alerting rules for ceph
New rules added:
- CephMgrIsAbsent
- CephMgrIsMissingReplicas
- CephMdsMissingReplicas
- CephMonHighNumberOfLeaderChanges
- CephOSDVersionMismatch
- CephMonVersionMismatch
Signed-off-by: Shubhendu <shtripat@redhat.com>
[skip ci]
> Added latest prometheus alerting rules for ceph

- pkg/daemon/ceph/osd/agent.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
Multiple ceph clusters on single node creates incorrect UUID in the "getCephVolumeOSDs" method.
This results in OSD failures with "failed to fetch mon config (--no-mon-config to skip)" error. Updated getCephVolumeOSDs method to use fsid filter while retriving devices.
Resolves #2696
**Checklist:**
[skip ci]
> Backport multi cluster osd failure

- cmd/rookflex/cmd/mount.go
- pkg/daemon/ceph/agent/flexvolume/types.go
With #2540 we have the ability to disable setting the fsGroup on K8s 1.13 and newer. This is particularly needed when there are large volumes that will take time to recursively set on all files. This PR revives #2259 to still set the fsGroup on the top level of the mount.
Resolves #2254
**Checklist:**
> Set fsgroup on the top level of the mount

- Documentation/ceph-teardown.md
The command had the namespace twice, remove the typo and used a working
command.
Resolves #
**Checklist:**
[skip ci]
> doc: fix patch command

- pkg/daemon/ceph/agent/flexvolume/server.go
Signed-off-by: Ashish Ranjan <ashishranjan738@gmail.com>
This commit enables server to search for `rookflex` binary instead of assuming it to be present in `/usr/local/bin/`.
Resolves # https://github.com/rook/rook/issues/2486
**Checklist:**
[skip ci]
> ceph: enhance server to search for rookflex

- PendingReleaseNotes.md
- pkg/operator/ceph/object/config.go
- pkg/operator/ceph/object/config_test.go
As per: ceph/ceph#26599, Beast is now the
default fronted for rados gateway.
Newly created cluster as of Nautilus will use it by default.
Re-added version of 03587352d531becc4d53ff7635a3d183176fa51b
Resolves: #2707
(cherry picked from commit 0317de90968d40d5783255d8366ad7f952d4a4ea)
[skip ci]
> backport: rgw: change default frontend on nautilus

- PendingReleaseNotes.md
- pkg/daemon/ceph/client/upgrade.go
- pkg/daemon/ceph/client/upgrade_test.go
- pkg/operator/ceph/cluster/osd/osd.go
When OSDs are running on Nautilus we always disable old osd features and
aplpy the onces for Nautilus as described in the upgrade doc.
During an upgrade or the next time an orchestration will be called the
command will be applied. The command is idempotent so we can run it each
time.
This can be backported for 1.0.3
Closes: https://github.com/rook/rook/issues/2960
Resolves #
**Checklist:**
[skip ci]
> ceph: upgrade apply osd nautilus flag

- PendingReleaseNotes.md
- pkg/daemon/ceph/client/upgrade.go
- pkg/daemon/ceph/client/upgrade_test.go
- pkg/operator/ceph/cluster/osd/osd.go
When OSDs are running on Nautilus we always disable old osd features and
aplpy the onces for Nautilus as described in the upgrade doc.
During an upgrade or the next time an orchestration will be called the
command will be applied. The command is idempotent so we can run it each
time.
This can be backported for 1.0.3
Closes: https://github.com/rook/rook/issues/2960
(cherry picked from commit cba9a359a0b546aa84e852936d11d3a2c5eb2f92)
Resolves #
**Checklist:**
[skip ci]
> backport: ceph: upgrade apply osd nautilus flag

- Documentation/ceph-csi-drivers.md
- cluster/examples/kubernetes/ceph/csi/example/rbd/storageclass.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
- cluster/examples/kubernetes/ceph/operator-with-csi.yaml
- pkg/operator/ceph/cluster/mon/endpoint.go
- pkg/operator/ceph/cluster/mon/mon.go
Create and maintain a config map that meets the requirements of
the ceph csi such that Rook can maintain the contents of config
map with up-to-date mon information to be used later by csi.
Comes with matching changes to csi templates and things. Right now the PR requires an ceph csi "canary" image which ought to be temporary but should be useful to demonstrate the feature in rook.
Resolves #2649
**Checklist:**
[skip ci]
> ceph csi: Create and maintain mon config to be consumed by csi

- pkg/operator/cockroachdb/controller.go
- pkg/operator/edgefs/cluster/controller.go
- pkg/operator/minio/controller.go
- pkg/operator/nfs/controller.go
onDelete obj in some case will return DeletedFinalStateUnknown type, we need use assert.
Signed-off-by: xiaorui.zou <xiaorui.zou@gmail.com>
//  * OnDelete will get the final state of the item if it is known, otherwise
//      it will get an object of type DeletedFinalStateUnknown. This can
//      happen if the watch is closed and misses the delete event and we don't
//      notice the deletion until the subsequent re-list.
so  a run-time panic  will occur.   
[skip ci]
> Fix onDelete func panic

- Documentation/ceph-object-store-crd.md
- Documentation/ceph-object.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/object-ec.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
- cluster/examples/kubernetes/ceph/object-test.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/object-store.md
- pkg/operator/ceph/cluster/mgr/config.go
- pkg/operator/ceph/cluster/rbd/config.go
- pkg/operator/ceph/config/keyring/store.go
- pkg/operator/ceph/config/keyring/store_test.go
- pkg/operator/ceph/file/mds/config.go
- pkg/operator/ceph/object/config.go
- pkg/operator/ceph/object/config_test.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/rgw_test.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
- pkg/operator/k8sutil/daemonset.go
* remove legacy code
* remove support for AllNodes where we would deploy one rgw per node on
all the nodes
* a transition path is implemented in the code so that if someone has an
existing deployment, daemonsets will be removed and replaced by an
deployments
* when using "instances", each rgw deployed has its own key which makes
Ceph reporting the exact number of rgw running, see:
```
[root@rook-ceph-operator-775cf575c5-bh4sr /]# ceph -s
cluster:
id:     611fcf39-0669-4864-9a12-debb35c0397a
health: HEALTH_OK
services:
mon: 3 daemons, quorum a,b,c (age 12h)
mgr: a(active, since 12h)
osd: 3 osds: 3 up (since 12h), 3 in (since 12h)
rgw: 3 daemons active (my.store.a, my.store.b, my.store.c)
data:
pools:   6 pools, 600 pgs
objects: 235 objects, 3.8 KiB
usage:   3.0 GiB used, 84 GiB / 87 GiB …
```
> ceph: refactor rgw bootstrap

- cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml
PR #3217 changed the CSI pod manifest to drop some parameters to the
ceph-csi pods. This also resulted in a change to the operator with CSI
yaml for non-openshift case, but failed to update similar yaml's for
the openshift case.
This commit rectifies the problem for openshift.
Updates #3312
[skip ci]
> Update openshift with Ceph-CSI image versions as in Kubernetes case

- Documentation/ceph-psp.md
- cluster/examples/kubernetes/ceph/psp.yaml
The current doc was outdated and hardcoded, so removing the example from
the doc and add a proper psp.yaml file that people can use and
contribute too.
Closes: https://github.com/rook/rook/issues/3309
[skip ci]
> ceph: add psp.yaml example

- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
This commit adds a new flag to the osd startup so that on msgr2 (default
on Nautilus and above) the osd is able to find the IP address in the
container to bind to.
This requires this Ceph patch https://github.com/ceph/ceph/pull/28589
and is already present in Octopus.
Closes: https://github.com/rook/rook/issues/3140
[skip ci]
> ceph: osd: fix startup on sdn

- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/cluster/migration_test.go
- pkg/operator/ceph/operator.go
- tests/integration/multi_cluster_test.go
When the operator first starts, the only operation needed is to watch for new cephcluster CRs to be created. The agent, discover pods, and the volume provisioning can all be delayed
starting until the first cluster is created.
@leseb This was the first commit in the branch for external clusters, I've separated it now since it wasn't directly related to that feature.
**Checklist:**
[skip ci]
> Delay starting the Rook system daemons until a CephCluster CR is created

- PendingReleaseNotes.md
- pkg/daemon/ceph/client/crush.go
This requirement is long gone and was reported in 2017. Clients should
have been updated by then, so there is no reason to set the CRUSH
tunable to such an old client. Actually, we should let Ceph run its own
tunable. They can always be changed later. Also, this was really
restrictive and applied on every orchestration and thus would override
any other config done by an administrator. Even worse, this will trigger
data movement back and forth.
Closes: https://github.com/rook/rook/issues/3138
**Checklist:**
[skip ci]
CI known issue.
> ceph: stop forcing crush tunable

- PendingReleaseNotes.md
- pkg/daemon/ceph/client/crush.go
This requirement is long gone and was reported in 2017. Clients should
have been updated by then, so there is no reason to set the CRUSH
tunable to such an old client. Actually, we should let Ceph run its own
tunable. They can always be changed later. Also, this was really
restrictive and applied on every orchestration and thus would override
any other config done by an administrator. Even worse, this will trigger
data movement back and forth...
Closes: https://github.com/rook/rook/issues/3138
(cherry picked from commit d3845e7f7598d154a7ab39d4b35090ec7c3e4c30)
Resolves #
**Checklist:**
[skip ci]
Known CI issue.
> backport: ceph: stop enforcing crush tunable

- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
Add selectors to Container Linux update operator daemonsets. 
Resolves #3339
**Checklist:**
[skip ci]
> Container Linux - Daemonsets missing required field "selector"

- Documentation/ceph-upgrade.md
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.0.go
- tests/framework/installer/installer.go
- tests/integration/upgrade_test.go
The upgrade test is intended to upgrade from the previous release to the latest. Given the 1.0 release recently, the upgrade test will now be from 1.0 to master. There is no longer a need in master to upgrade from 0.9. The manifests in ceph_manifests.go are basically copied to ceph_manifests_v1.0.go to give the baseline for the upgrade.
The upgrade guide is also updated in master to be crystal clear for users not to attempt to upgrade to master.
**Checklist:**
[skip ci]
> Ceph: upgrade test from 1.0 to master instead of 0.9 to master

- pkg/daemon/ceph/osd/init.go
Similarly to #2675, try to find the rook binary
on PATH in case it isn't found in /usr/local/bin/rook.
Signed-off-by: Kristoffer Grönlund <kgronlund@suse.com>
[skip ci]
> ceph: Look for binaries on PATH if not found

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner.yaml
- tests/framework/installer/ceph_csi_templates.go
Ceph-CSI repository had a recent PR [1] merged that contains
changes to the pod manifests.
This PR to Rook updates the pod manifests to catch up with the
changes to Ceph-CSI master.
Once Ceph-CSI has a 1.1.0 release, future PRs to Rook on manifest
changes would track that branch (at least for Rook 1.1 release).
[1] PR in ceph-csi changing the manifest:
https://github.com/ceph/ceph-csi/pull/443
Signed-off-by: ShyamsundarR <srangana@redhat.com>
[skip ci]
> Update Ceph-CSI manifests as per changes to ceph-csi repository

- pkg/daemon/ceph/config/keyring.go
Adjust keyring template because ceph-mon in Octopus fails to
parse keyring file which has leading indention.
Fixes: https://github.com/rook/rook/issues/3384
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
Resolves #3384 
**Checklist:**
> Ceph: fix error when creating monmap in Octopus

- Jenkinsfile
- PendingReleaseNotes.md
With the release of K8s 1.15 we need to add it to the test matrix. In continuing with our pattern of supporting the most recent five releases, we will drop 1.10 at the same time.
**Checklist:**
[skip ci]
> Add k8s 1.15 and remove 1.10 from integration tests

- pkg/operator/ceph/cluster/osd/spec.go
Somehow during startup the arg got misinterpreted by ceph-osd and was
failing with:
2019-06-19 15:23:09.098967 I | exec: Running command: ceph-osd --foreground --id 0 --osd-uuid feceb7d7-3148-4a0d-af7a-753ba2f21a92 --conf /var/lib/rook/osd0/rook-ceph.config --cluster ceph --default-log-to-file false --ms-learn-addr-from-peer false
2019-06-19 15:23:09.135921 I | unrecognized arg false
failed to start osd. Failed to complete '': exit status 1.
Now we are concatenating the whole flag to avoid that.
Resolves #
**Checklist:**
[skip ci]
known issue
> ceph: osd: fix cli arg

- pkg/operator/ceph/cluster/osd/spec.go
Somehow during startup the arg got misinterpreted by ceph-osd and was
failing with:
2019-06-19 15:23:09.098967 I | exec: Running command: ceph-osd --foreground --id 0 --osd-uuid feceb7d7-3148-4a0d-af7a-753ba2f21a92 --conf /var/lib/rook/osd0/rook-ceph.config --cluster ceph --default-log-to-file false --ms-learn-addr-from-peer false
2019-06-19 15:23:09.135921 I | unrecognized arg false
failed to start osd. Failed to complete '': exit status 1.
Now we concatenate the whole flag to avoid that.
(cherry picked from commit 6d620054723d4fc0ebc47d6d103d8410b4a8a544)
Backport of: https://github.com/rook/rook/pull/3389
[skip ci]
Known CI issue
> backport: ceph: osd: fix cli arg

- Documentation/ceph-csi-drivers.md
The word "storegeclass" should be "storageclass"
Signed-off-by: Joel Huang <joelhy@gmail.com>
Resolves #
**Checklist:**
[skip ci]
> ceph: fix typo error storegeclass

- pkg/operator/ceph/cluster/controller.go
If we are running a Ceph cluster that has an unsupported version and if
we have set allowUnsupported: false, a newly bootstrap operator will
fail to start. To fix this, the user will update the CR and set
allowUnsupported: true, however at this point clusterInfo hasn't been
initialized so the operator will panic because we were referencing a nil
pointer.
To fix this, we re-populate clusterInfo if necessary and things go
smoothly.
Closes: https://github.com/rook/rook/issues/3137
Resolves #
**Checklist:**
[skip ci]
> ceph: controller: fix panic on cr update

- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- images/ceph/Makefile
- tests/framework/installer/ceph_installer.go
Currently in cluster deploy, ceph image points to ceph/ceph:v14.2.1-20190430.
Changing this to use ceph/ceph:latest-nautlius-devel as its the latest nautilus.
Signed-off-by: Poornima G <pgurusid@redhat.com>
[skip ci]
> Change the ceph image to point to latest-nautilus-devel

- Documentation/ceph-csi-drivers.md
The word "storegeclass" should be "storageclass"
Signed-off-by: Joel Huang <joelhy@gmail.com>
(cherry picked from commit d4945d65333d34c30325255a557275e675c540cb)
Resolves #
**Checklist:**
[skip ci]
> ceph: backport of PR #3396 "fix typo error storegeclass" to release-1.0 branch

- tests/framework/installer/ceph_installer.go
- tests/framework/utils/k8s_helper.go
The CI instances are not always being properly cleaned up between runs. This is an attempt to get the Ceph tests to ensure a clean install before proceeding with the test.
Resolves #
**Checklist:**
> Tests: Ensure cluster does not exist before starting a test

- Documentation/ceph-csi-drivers.md
- cluster/examples/kubernetes/ceph/csi/example/cephfs/storageclass.yaml
* This error is found in creating CephFS StorageClass using document `Documentation/ceph-csi-drivers.md`: "expect a pool named `cephfs_data` in your Ceph cluster"
* **`kubectl apply -f pool.yaml` using metadata.name "cephfs_data" produce error:** The CephBlockPool "cephfs_data" is invalid: metadata.name: Invalid value: "cephfs_data": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
* accoding to `Documentation/ceph-filesystem-crd.md` linked from `Documentation/ceph-csi-drivers.md` file and field test, it should be `myfs-data0`
Signed-off-by: Joel Huang <joelhy@gmail.com>
**Description …
> ceph: wrong pool name for CephFS StorageClass

- pkg/daemon/ceph/client/image.go
- pkg/operator/ceph/provisioner/provisioner.go
Example of failure scenarios:
```
- requested PVC 500M = 500,000,000 bytes
- PV is created as:
(500M / 2**20)Mi = "476"Mi
But 476Mi = 476 * 2**20 = 499122176 < 500M
```
So, rounding back up loses some of the precision.
From the k8s documentation:
> Claims will remain unbound indefinitely if a matching volume does not
exist. Claims will be bound as matching volumes become available. For
example, a cluster provisioned with many 50Gi PVs would not match a
PVC requesting 100Gi. The PVC can be bound when a 100Gi PV is added
to the cluster.
which is inline with the behavior observed in which a 500M PVC is never
bound. However, the documentation also states:
> If a PV was dynamically provisioned for a new PVC, the loop will
always bind that PV to the PVC. Otherwise, the user will always get
at …
> ceph: adjust M-to-Mi rounding in PV creation

- PendingReleaseNotes.md
- pkg/daemon/ceph/client/crush.go
- pkg/daemon/ceph/config/keyring.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/config/keyring/admin.go
This commit does:
* remove dead code SetCrushTunables()
* stop creating initial crushmap
There is no need to create an initial crushmap, since Ceph natively does
that for us.
We don't delete the existing configmap containing the initial crush map
of already deployed cluster, perhaps people are using for whatever
reason. It does not harm to keep it around.
Closes: https://github.com/rook/rook/issues/3138
**Checklist:**
> ceph: stop creating initial crushmap

- pkg/operator/ceph/object/config.go
- pkg/operator/ceph/object/config_test.go
The beast fronted configuration for rgw is quite different than civetweb
so we adapted the construct of the arg line based on that configuration
requirement.
Closes: https://github.com/rook/rook/issues/3411
[skip ci]
known ci issue
> ceph: rgw: set proper port syntax on beast

- pkg/clusterd/disk.go
- pkg/clusterd/disk_test.go
Signed-off-by: Ash Wu <hSATAC@gmail.com>
`clusterd.GetAvailableDevices` method is no longer used anywhere.
It could be removed along with the test if it's not required anymore.
**Checklist:**
[skip ci]
> Remove unused clusterd.GetAvailableDevices

- PendingReleaseNotes.md
- pkg/clusterd/disk.go
- pkg/util/sys/device.go
Signed-off-by: Ash Wu <hSATAC@gmail.com>
Allow linear disks create by `mdadm --create --level=linear ...` can be used as OSD device.
Tested against `ceph/ceph:v13.2.4-20190109` image.
**Checklist:**
> Add linear to support diskType

- Documentation/ceph-psp.md
- cluster/charts/rook-ceph/templates/role.yaml
- cluster/charts/rook-ceph/templates/rolebinding.yaml
- cluster/charts/rook-ceph/templates/serviceaccount.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cmd/rook/main.go
- cmd/rook/rook/rook.go
- cmd/rook/util/cmdreporter.go
- cmd/rook/util/copybins.go
- cmd/rook/util/doc.go
- pkg/daemon/util/cmdreporter.go
- pkg/daemon/util/cmdreporter_test.go
- pkg/daemon/util/copybins.go
- pkg/daemon/util/copybins_test.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/migration_test.go
- pkg/operator/ceph/operator.go
- pkg/operator/k8sutil/cmdreporter/cmdreporter.go
- pkg/operator/k8sutil/configmap.go
- pkg/operator/k8sutil/configmap_test.go
- pkg/operator/k8sutil/delete.go
- pkg/operator/k8sutil/delete_test.go
- pkg/operator/k8sutil/job.go
- pkg/operator/k8sutil/options.go
- tests/framework/installer/ceph_manifests.go
- tests/integration/upgrade_test.go
First, create new cmd-reporter daemon.
cmd-reporter runs a command and puts the results of the command into a
ConfigMap defined by its `--config-map-name` commandline flag.
cmd-reporter is intended to be run as a Kubernetes job where an
operator needs to run a single command and get return information back
from the command which is more than just success/failure.
The ConfigMap returned includes `stdout`, `stderr`, and `retcode` data
from the command. The ConfigMap may be preexisting, in which case
cmd-reporter will overwrite the return information in the ConfigMap.
cmd-reporter labels the ConfigMap with `app=cmd-reporter`, and if the
ConfigMap already has an app label which is different, cmd-reporter
fails without modifying the ConfigMap so as not to overwrite another
application's data …
> Add cmd-reporter daemon; use it to get ceph version

- .github/PULL_REQUEST_TEMPLATE.md
- INSTALL.md
The CI is automatically triggered for each PR update, merge to master, and merge to release branches. Sometimes the CI does not need to run. For efficiency the CI can be skipped for documentation, yaml, or other changes that will not be validated at all by the CI. This adds a new option to the PR template and updated docs that make it more clear how users besides maintainers should be adding this flag.
**Checklist:**
[skip ci]
> Add documentation for skipping the CI

- pkg/operator/k8sutil/k8sutil.go
- pkg/operator/k8sutil/k8sutil_test.go
Replace any invalid characters and ensure length
and format for the rook version label, to avoid
problems with version strings that contain
illegal characters (common characters that aren't
valid in labels would be + and ~, for example).
Kubernetes label syntax:
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
Resolves #3434 
**Checklist:**
> k8sutil: Ensure rook version label has valid syntax

- pkg/operator/k8sutil/k8sutil.go
- pkg/operator/k8sutil/pod.go
One commit to use the label max length constant from Kubernetes rather than
hard-coding it, and one commit to add missing docstrings to functions in pod.go.
Resolves #
**Checklist:**
> k8sutil: 1. Use label max length constant from k8s, 2. Add missing docstrings in pod.go

- Documentation/development-flow.md
- contrib/backport_to_stable_branch.sh
Run the script like this:
./contrib/backport_to_stable_branch.sh STABLE_BRANCH_NAME COMMIT_SHA1 BACKPORT_BRANCH_NAME
Resolves #
**Checklist:**
[skip ci]
> contrib: add an helper script to perform backports

- Documentation/ceph-advanced-configuration.md
- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
- pkg/operator/ceph/cluster/mon/node.go
- pkg/operator/ceph/cluster/mon/node_test.go
- pkg/operator/k8sutil/node.go
ceph: schedule mons across failure domains
Resolves #2603 
this patch introduces failure-domain aware scheduling for monitor pods.
previously the only policy was to avoid scheduling monitors on the same
nodes. the new policy tries to spread monitors across zones and nodes.
NOTE: this patch only enforces the well-known k8s "zone"
failure-domain label (i.e. it does not look for region labels). this
decision is made for two reasons. first, eliminating explicit
scheduling is an important goal and will be done as part of upcoming
work. this will enable all supported failure-domain labels to be
handled. second, the "zone" domain is likely more appropriate for a
larger portion of users (as opposed to the …
> ceph: schedule mons across failure domains

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
This fixes https://github.com/rook/rook/issues/3204
Don't set prometheus to a deployment spec but rather to a pod template
Signed-off-by: Dinar Valeev <k0da@opensuse.org>
Resolves #
**Checklist:**
[skip ci]
> Fix mgr prometheus annotations

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
This fixes https://github.com/rook/rook/issues/3204
Move prometheus Annoation logic before Deployment is initialized,
otherwise, podSpec is not uptodate
Signed-off-by: Dinar Valeev <k0da@opensuse.org>
Resolves #
**Checklist:**
[skip ci]
Known issue
> Mgr: fix prometheus annotations for 1.0

- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/config/config.go
- pkg/operator/ceph/config/store.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/spec/spec.go
- pkg/operator/ceph/spec/spec_test.go
Ceph daemons will run as the 'ceph' user instead of the 'root' user.
Existing data store (osd and mon) owned by root will continue to run as
'root'.
CLI calls also inherate from this and will use them when fetching a key
for instance. If we run on a version of ceph that does not know these
flags they will simply get ignored.
Consider the following:
```
[leseb@tarox~/go/src/github.com/rook/rook][use-ceph-user !] kubectl get pods -n rook-ceph
NAME                                     READY     STATUS      RESTARTS   AGE
rook-ceph-mds-myfs-a-67cff7df69-fq4l5    1/1       Running     0          3m
rook-ceph-mds-myfs-b-85bd5f59f5-d8hdn    1/1       Running     0          3m
rook-ceph-mgr-a-7d88b9457b-jzln6         1/1       Running     2          4m
rook-ceph-mon-a-64bf697496-r94tc         1/1 …
```
> ceph: run ceph processes with the 'ceph' user

- pkg/operator/ceph/cluster/osd/spec.go
I removed  invalid "both" in the code comment
[skip ci]
> Correct typo about skipVolumeForDirectory's code comment

- pkg/operator/ceph/cluster/mon/spec.go
OpenShift environment requires privileged containers when interacting
with the host filesystem, typically via dataDirHostPath.
The init container that changes the ownership of dataDirHostPath was
missing the privileged flag and users were getting permission denied
errors on the chown command.
Fixes: https://github.com/rook/rook/issues/3485
Resolves #
**Checklist:**
[test ceph]
> ceph: mon: init chown for openshift

- pkg/operator/ceph/cluster/osd/osd.go
The crush location was being stored in `c.ValidStorage.Nodes`, but the value was being stored in `c.DesiredStorage.Nodes`. I ensured that DesiredStorage was being updated as well.
I have verified that the failure-domain labels are being read and propagated to the crush map.
Resolves #3430
**Checklist:**
> Fix: topologyAware does not pick up failure domains.

- pkg/apis/edgefs.rook.io/v1beta1/utils.go
- pkg/operator/edgefs/cluster/mgr/mgr.go
- pkg/operator/edgefs/isgw/isgw.go
Resolves #3481 
**Checklist:**
[test edgefs]
> make getModifiedRookImagePath be generic and use it for isgw too

- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- images/ceph/Makefile
- tests/framework/installer/ceph_installer.go
14.2.2 is out and along with it numerous fixes so let's use it.
Resolves #
**Checklist:**
[test ceph]
> ceph: use latest 14.2.2 code

- Jenkinsfile
If no storage provider is found, let's assign env.testProvider with an
empty string so that we wil run all the tests.
Resolves #
**Checklist:**
[test edgefs]
> ci: do not skip if null

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/object/spec.go
Before each pod starts, the daemon changes the ownership of
/var/log/ceph which is bindmounted on a hostPath.
On OpenShift envionments, the container must be privileged in order to
successfully change the owernship.
Closes: https://github.com/rook/rook/issues/3499
**Checklist:**
[test ceph]
> ceph: run pod with privileged

- pkg/operator/ceph/cluster/controller.go
Currently the ClusterController logs out a message like:
```
Cluster %s is not ready. Skipping orchestration.rook-ceph
```
without the "placeholders" fullfilled. This is because the code uses the
logger.Info() instead of logger.Infof() function.
This change fixes that to use Infof and therefore corrects the log
message.
Resolves #
**Checklist:**
> fix usage of Infof in CephClusterController

- Jenkinsfile
- tests/framework/installer/installer.go
The integration tests for storage providers will be skipped, for example if the "test ceph" tag is specified. If the "test" tag is not specified all tests should be run. If the tag is not specified, the Jenkinsfile will pass "null", which needs to be handled by the test code deciding to run all the tests.
**Checklist:**
> Trigger the integration tests for all branches if tags not set

- tests/scripts/minikube.sh
The minikube dev helper script should deploy 1.15 by default.
**Checklist:**
[skip ci]
> Update minikube script to 1.15.1

- pkg/operator/ceph/cluster/mgr/spec.go
Because the manager is running under the 'ceph' user the cephfs
subvolume plugin can not create directories anymore. It fails with a
permission denied because of the usage of the 'ceph' user, root is need
here, hence the special startup line to go over this.
Closes: https://github.com/ceph/ceph-csi/issues/486
Resolves #
**Checklist:**
[test ceph]
> ceph: mgr fix startup

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- pkg/daemon/ceph/osd/volume.go
Fail when metadataDevice is specified but ceph-volume batch does not
automatically use the metadataDevice as the block.db.
Resolves #3092
**Checklist:**
> ceph: fail when metadataDevice not used by cephvol

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/edgefs/cluster/controller.go
The status messages on the CRs had much duplicated code for logging an error if the status update failed. Now any failures around the status update are logged consistently within the updateClusterStatus method so there is no need to return an error and duplicate the error handling everywhere.
This commit is split out of #3450 
**Checklist:**
> Simplify CR status updates for Ceph and EdgeFS

- cluster/examples/kubernetes/edgefs/s3.yaml
- pkg/apis/edgefs.rook.io/v1beta1/types.go
- pkg/operator/edgefs/cluster/mgr/mgr.go
- pkg/operator/edgefs/iscsi/iscsi.go
- pkg/operator/edgefs/isgw/isgw.go
- pkg/operator/edgefs/nfs/nfs.go
- pkg/operator/edgefs/s3/s3.go
- pkg/operator/edgefs/s3x/s3x.go
- pkg/operator/edgefs/swift/swift.go
- pkg/operator/k8sutil/service.go
- pkg/operator/k8sutil/service_test.go
Allow users to define Kubernetes users to define ServiceType and NodePort via the CRD spec.  This changes the current behavior, which deploys all services into the K8s cluster as NodePort services on auto-selected ports.  The intent is to provide users more control over services and make accessing services via other methods simpler (e.g., LaodBalancer, ingress controller).  It also reduces the number of ports exposed outside of the Kubernetes cluster.
N/A
**Checklist:**
[test edgefs]
> EdgeFS: Allow control over K8s service type via CRD

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
Ceph CSI now requires a tempfs mountpoint and will not function without
it. These changes are cloned from the ceph csi yaml.
While working on PR#3373 I found none of my ceph csi pvc were getting bound. Logging indicated an issue getting keys to ceph commands. Coordinated with @ShyamsundarR  and learned about the newly required changes to the templates.
Resolves #
**Checklist:**
> ceph csi: add new required tempfs mounts to csi templates

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/edgefs/cluster/cluster.go
- pkg/operator/edgefs/cluster/controller.go
If you restart your whole kubernetes cluster or when you have a short interruption in the etcd or kube-api service (like 10 seconds) kubernetes can trigger a rebuild of the whole internal object graph af which a full garbage collector run is performed. When this happens all components in the CephCluster are beeing deleted by the kubernetes garbage collector. This includes all the secrets and configmaps!
If cause of this issue is that all components in the CephCluster have an ownerreference referencing the CephCluster by UID. When the CephCluster is destroyed all components in it will be as well. By the "name" in the ownerreference that of the namespace in witch the CephCluster is deployed.
When the kubernetes garbage collector does a full run it makes an …
> Ceph (and EdgeFS?) cluster is being deleted after K8S cluster restart or api/etcd issues

- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/osd/init.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
Replace usage of the custom osd copybins command with the new top-level
copy-binaries command introduced with cmd-reporter.
**Checklist:**
[test ceph]
// known random failure
[skip ci]
> ceph: osd use copy-binaries top level cmd

- Documentation/ceph-monitoring.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/monitoring/rbac.yaml
- pkg/operator/ceph/cluster/mgr/mgr.go
this adds the access for rook to create monitoring resources
across namespaces and provides servicemonitor config to
monitor the current service being created
Resolves #
**Checklist:**
// 
[test ceph]
> fix Prometheus permissions and servicemonitor configurations

- pkg/operator/k8sutil/deployment.go
fix word `ressource` to `resource`
make the comment more readable
[skip ci]
> fix word `ressource` to `resource`

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mon/health.go
a helper flag indicating the exitence of an empty zone (empty = no
monitor pods) is computed when checking the health of the cluster in
order to determine if mons from overloaded zones have some new location
they can be scheduled. the computation of this flag did not check that
the empty zone contains valid nodes that pods can be scheduled on to.
this lead to a mon creation loop.
fixes: #3545
**Checklist:**
> ceph: check that empty zone contains valid nodes

- PendingReleaseNotes.md
- cmd/rook/ceph/osd.go
- cmd/rook/ceph/osd_test.go
- pkg/daemon/ceph/osd/device.go
- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/osd/spec.go
When device list is specified, allow for metadataDevice to be specified per device in the device specific configuration section.
Example config:
```
nodes:
- name: "osd001"
devices:
- name: "sdd"
config:
metadataDevice: "sdb"
- name: "sde"
config:
metadataDevice: "sdb"
- name: "sdf"
config:
metadataDevice: "sdc"
- name: "sdg"
config:
metadataDevice: "sdc"
```
> ceph: Add ceph-volume support for per OSD metdataDevices

- tests/framework/installer/cassandra_installer.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/cockroachdb_installer.go
- tests/framework/installer/edgefs_installer.go
- tests/framework/installer/installer.go
- tests/framework/installer/nfs_installer.go
- tests/framework/installer/provisioners.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_multi_cluster_test.go
Now we collect logs for all pods and all their init and main containers during the integration tests. No longer will we be missing logs from the integration tests as long as the pods  are available when they are collected at the end of the test. The pod descriptions are also written to a log file instead of being included inline with the test output.
**Checklist:**
> Tests: Collect all logs for pods in the integration tests

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-examples.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/mon/spec_test.go
- pkg/operator/ceph/spec/label.go
- pkg/operator/ceph/spec/spec.go
- pkg/operator/ceph/test/podspec.go
- pkg/operator/k8sutil/deployment.go
Optionally run monitors on PVC-based storage.
This PR is ready for an initial review, but unit test failures are expected.
I've also updated the design document to reflect the current implementation description:
https://github.com/noahdesu/rook/blob/ceph-mon-pv-design/design/ceph-mon-pv.md
I will wait to add documentation to this PR until the review is complete.
Resolves #3351 
**Checklist:**
> ceph: base monitor storage of pvc

- cluster/charts/rook-ceph/templates/role.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- tests/framework/installer/ceph_manifests.go
In order for the osd service account to reference the cephcluster CR in the owner references, OpenShift requires access to the CephCluster CRD. This adds the minimal changes needed to appease OpenShift.
Resolves #3466 
@ron1 I also hit this in OpenShift, thanks for helping track it down!
**Checklist:**
> Add CephCluster RBAC to the OSD service account

- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/spec/spec.go
there is a build here for testing `noahdesu/rook-ceph-master-no-lifecycle-e`
1. initializes ownership on files using init container rather than life cycle hook. see commit message for explanation.
2. make sure that pvc file system mount uses empty directory for daemon data
ext4 adds some extra directories in the root, so this PR mounts in a subdirectory.
```
[vm 0 ~]$ oc -n rook-ceph log rook-ceph-mon-a-5cf4748c6-nvmzd -c list-container-data-dir
total 20
drwxrwsr-x. 3 root 1000630000  4096 Aug  8 20:06 .
drwxr-x---. 1 ceph ceph          20 Aug  8 20:06 ..
drwxrwS---. 2 root 1000630000 16384 Aug  8 20:06 lost+found
```
Resolves #3591 
**Checklist:**
> ceph: fix monitor pvc storage on ebs

- pkg/operator/ceph/spec/spec.go
- pkg/operator/ceph/spec/spec_test.go
I have implemented the trivial solution with a test to verify that it is working and to avoid future problems.
Besides that, I have explored another possibility, basically is to use "LimitRange" in common.yaml.
I think that if we are going to use just one container by pod, this could be other approach that will allow us to avoid to hardcode the memory limits for each kind of pod ("cephRbdMirrorPodMinimumMemory", "cephMgrPodMinimumMemory", "cephMonPodMinimumMemory", "cephMdsPodMinimumMemory" ) and to have a function to check this limits.
As disadvantage we have that we cannot use a default value for each kind of pod.
It can be done using this specification in "common.yaml" (default values can be adjusted)
```
---
apiVersion: v1
kind: LimitRange
metadata:
name: mem-limit-range
namespace: …
```
> Memory limit checked if it really exists

- Documentation/ceph-upgrade.md
- Changed an instruction that used vi to a kubectl scale command
Signed-off-by: Danilo Riecken P. de Morais <danilo.riecken@gmail.com>
Minor improvement that reduces the time to execute the update by eliminating one step that uses vi.
Also uses the shell variable as the rest of the document.
Resolves #
**Checklist:**
[skip ci]
> Documentation(Ceph) Improve update 0.9 to 1.0 docs

- cluster/examples/kubernetes/ceph/common.yaml
If you try to uncomment items under 'allowedHostPaths:' and load the file you get an error.
I correct with right syntax.
Resolves #
**Checklist:**
[skip ci]
> ceph: Update Pod Security Policy definition

- cluster/examples/kubernetes/ceph/csi/rbd/storageclass-test.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
we have seen better performance in device format and mounting by setting the fstype to xfs from default ext4.
More info https://github.com/ceph/ceph-csi/issues/507
Resolves #
**Checklist:**
[skip ci]
> Add xfs fstype as default type in storageclass

- pkg/daemon/ceph/client/pool.go
This is not changing the behavior of the code but making the
flow of logic in the createReplicationCrushRule() function consistent
by removing an else branch. This was just a reflex when I was reading
the code.
Resolves no issue, merely some code hygiene.
**Checklist:**
> ceph:pools: polish logic flow a bit in createReplicationCrushRule()

- Documentation/ceph-block.md
- Documentation/ceph-filesystem-crd.md
- Documentation/ceph-object-store-crd.md
- Documentation/ceph-object.md
- Documentation/ceph-pool-crd.md
- Improve readability of 'Replicated' and 'Erasure Coded' sections
- Clarify replicated sample requires 1 OSD located on 3 different nodes
- Add whitespace to 'Pool Settings' section
- Add link to the k8s 'StorageClass' concept
- Rename instances of 'object store' as literal
`CephObjectStore`
- Rename instances of 'object store user' as literal
`CephObjectStoreUser`
- Other minor verbiage and syntax clean-up
Signed-off-by: Michael Fritch <mfritch@suse.com>
**Checklist:**
[skip ci]
> docs: Add Clarity to Ceph CRDs

- cluster/examples/kubernetes/ceph/csi/rbd/pvc.yaml
The ceph rbd pvc example points to a storageclass that doesn't match the name in the example storageclass manifests. This causes the rbd example manifests for the pod and pvc fail. 
**Checklist:**
[skip ci]
> Update example pvc.yaml to reflect name of example rdb storageclass

- tests/framework/clients/block.go
- tests/framework/clients/filesystem.go
- tests/framework/clients/nfs.go
- tests/framework/clients/object.go
- tests/framework/clients/object_user.go
- tests/framework/clients/pool.go
- tests/framework/clients/read_write.go
- tests/framework/installer/installer.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_base_file_test.go
- tests/integration/ceph_block_create_test.go
- tests/integration/ceph_csi_test.go
- tests/integration/ceph_filesystem_mountuser_test.go
- tests/integration/ceph_upgrade_test.go
- tests/longhaul/base_block_test.go
- tests/longhaul/block_with_fencing_test.go
Some integration tests fail due to resources from a previous integration
run not being cleaned up properly. Instead of using 'kubectl create' --
which fails with an error if the resource already exists -- to create
resources, use 'kubectl apply' -- which does not fail for pre-existing
resources. 'kubectl apply' will give a warning that it should be used to
apply changes to resources created with 'create' or 'apply', but there
is no error.
Resolves #
**Checklist:**
> Integration tests: use 'kubectl apply' vs create

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- tests/framework/installer/ceph_manifests.go
The k8sevents mgr module needs to access the k8s
events api, so the corresponding auth for the mgr
pod needs to change.
Signed-off-by: Paul Cuzner <pcuzner@redhat.com>
> ceph: add rbac permissions for events api access

- tests/framework/utils/k8s_helper.go
Add an environment variable to the test code such that instead of docker cli being required an equivalent cli tool, such as "podman" can be used instead.
As far as I could see this was the only use of a container runtime tool anywhere else in the test code.
Resolves #
**Checklist:**
> tests: do not require actual docker cli

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner.yaml
- tests/framework/installer/ceph_csi_templates.go
The Ceph-CSI provisioners can hit a resource limit that is configured by
the container runtime (CRI-O restrict the number of processes/threads in
a container to 1024 by default). When there are spikes in the
provisioning, it is possible that the provisioners or helper executables
are not able to start new child processes, causing delays in the volume
creation or deletion.
A new --pidlimit command flag has been introduced with ceph/ceph-csi#517
and can be used to prevent the resource restrictions. This makes it
possible for the provisioners to stay responsive during spikes in the
requests.
The PID limit is configured to 'max' (value -1), but this can be adapted
to a (large) static value if needed.
Resolves …
> ceph-csi: pass --pidlimit option to provisioners

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/edgefs/cluster/cluster.go
- pkg/operator/edgefs/cluster/controller.go
If the CephCluster `name` is different from the `namespace`, the K8s garbage collector will delete resources unexpectedly when it is rebuilding its GC info. See #3530 for more details.
By default the name and namespace are both `rook-ceph`, so this is only an issue if one of those was changed).
Resolves #3575 
**Checklist:**
> Backport: Set correct name of OwnerReferences to avoid unexpected garbage collection

- Documentation/ceph-block.md
- Documentation/ceph-filesystem.md
Update the rbd and cephfs docs to include the new prefixed style
of name for the rook-managed csi instances. Document that this
prefix must match the namespace the rook operator is deployed in.
Resolves #3617
**Checklist:**
[skip ci]
> doc: document csi naming "prefix" as the rook operator namespace

- pkg/operator/ceph/cluster/osd/spec.go
Correctly set osd mem target for inited clusters
Previously, the value was set to commonArgs, resulting in dead code,
since common arg isn't used after the append (see the first commit in the PR).
Then fix some duplicated code (the second commit).
The bug was introduced in https://github.com/rook/rook/pull/3005
Resolves #
**Checklist:**
> Correctly set osd mem target for inited clusters

- pkg/operator/ceph/file/mds/spec.go
When deleting mds deployment the error is logged, but not propagated
further down (it always returns nil). The two places using the function
checks the error, and acts upon it.
Resolves #
**Checklist:**
> ceph: properly propagate errors when deleting mds deployment

- Documentation/disaster-recovery.md
Added instructions about how to bring orphaned rook/ceph cluster back.
None
**Checklist:**
[skip ci]
> doc: Add disaster recovery doc

- pkg/daemon/ceph/osd/volume.go
This change addresses 2 issues regarding per OSD metadata devices:
- When setting the metadata device per OSD, provisioning will fail because the check is only looking at the storage global metadata device setting
- ceph-volume args are not being re-initialized for each iteration thru the metadata device dict
Resolves #
**Checklist:**
> ceph: fix per osd metadata support

- Documentation/helm-operator.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml.tmpl
`ROOK_CURRENT_NAMESPACE_ONLY` environment variable was added to the deployment of the ceph operator.
It was hard-coded to `true` into the template.
This variable is now configurable using `helm` deployment strategy.
Resolves #3327
> ROOK_CURRENT_NAMESPACE_ONLY environment variable configurable with helm for operator deployment

- pkg/operator/ceph/cluster/controller.go
This commit fixes cluster namespace not showing in the rook operator logs.
**Checklist:**
> fix ceph cluster namespace not showing in the logs

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
This commit fixes resource limits and placements not getting applied to osd pods provisioned using storageClassDeviceSets
Resolves #
**Checklist:**
> fix(storageClassDeviceSet): fixes resource limits and placements not getting applied to osds

- Documentation/ceph-csi-drivers.md
- Documentation/ceph-monitoring.md
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
- cluster/examples/kubernetes/ceph/monitoring/csi-liveness-service-monitor.yaml
- tests/framework/installer/ceph_csi_templates.go
Deploy csi liveness side car for metrics collection 
This is dependent on [this](https://github.com/ceph/ceph-csi/pull/438) being pulled into ceph-csi
Signed-off-by: Daniel-Pivonka <dpivonka@redhat.com>
> ceph: deploy liveness sidecar with csi

- Makefile
- cluster/olm/ceph/generate-rook-csv-templates.sh
- cluster/olm/ceph/generate-rook-csv.sh
- images/ceph/Dockerfile
- images/ceph/Makefile
The ocs-operator would like to consume a CSV template from the rook-ceph operator's container image. This template is used to merge the rook-ceph operator into the ocs-operators unified CSV file.
In addition to the CSV templates, I've also included the rook related CRDs in the container image for extraction. 
**Usage Example** extracting CSV template for OCP from the rook-ceph container image. 
```
ROOK_CEPH_IMAGE=<some-image>
docker run --rm -it --entrypoint=cat $ROOK_CEPH_IMAGE /etc/ceph-csv-templates/rook-ceph-ocp.vVERSION.clusterserviceversion.yaml.in
```
**Usage Example** extract a crd
```
ROOK_CEPH_IMAGE=<some-image>
docker run --rm -it --entrypoint=cat $ROOK_CEPH_IMAGE /etc/ceph-csv-templates/crds/ceph_crd.yaml
```
**Usage Example** List all CRDs. …
> Rook-Ceph CSV templates

- Documentation/ceph-csi-drivers.md
The CSI doc is not showing up in the table of contents in the master branch. Instead it is showing up at the root and has the title "Rook", which happens for all topics that have an incorrect header. 
The fix is to remove an extra line before the title info.
[skip ci] 
**Checklist:**
> Docs: Add CSI doc back to the TOC

- pkg/apis/rook.io/v1alpha2/types.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
fix potential problematic misspell in struct definition
Resolves #
**Checklist:**
[skip ci]
Known failure.
> types.go: fix bug in struct definition

- Documentation/development-environment.md
This is necessary as the current kubespray VM's dockerd engine
depreciated the --graph daemon option.
Resolves #
**Checklist:**
[skip ci]
> docs: Update kubespray development-environment instructions

- cluster/examples/kubernetes/ceph/filesystem-ec.yaml
- cluster/examples/kubernetes/ceph/filesystem.yaml
- adds podAntiAffinity as default to spread MDS across different nodes
Resolves #3332 
**Checklist:**
[skip ci]
> updates ceph filesystem yaml

- design/multi-homed-cluster.md
This design propose change to cluster network definition to enable multi-homed networking using cni multi-plugin such as multus.
Related #2621
**Checklist:**
[skip ci]
> Design: Multi-homed Cluster Network Spec

- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/osd/spec.go
Fix variable scoping issue that is ignoring osdsPerDevice config
setting.  Ensure that in all scenarios both the global and per OSD
osdsPerDevice setting are honored.  When both are set the more specific
setting will be used.
Resolves #3599 
**Checklist:**
> ceph: fix osdsPerDevice config

- pkg/apis/rook.io/v1alpha2/types.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
Added portable and failure-domain label to the OSD deployment.
Resolves #
**Checklist:**
> Added portable and failure-domain label to the OSD deployment

- pkg/operator/ceph/file/mds/spec.go
When deleting mds deployment the error is logged, but not propagated
further down (it always returns nil). The two places using the function
checks the error, and acts upon it.
Signed-off-by: Odin Ugedal <odin@ugedal.com>
(cherry picked from commit 43baf63b86e5eee9b9058bc5ca228029b54c2651)
Resolves #
**Checklist:**
[skip ci]
leseb: random failure
> backport: properly propagate errors when deleting mds

- pkg/operator/ceph/cluster/osd/spec.go
Backport #3638
Resolves #
**Checklist:**
> Backport: Correctly set osd mem target for inited clusters

- .gitignore
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/olm/ceph/generate-rook-csv-templates.sh
- cluster/olm/ceph/generate-rook-csv.sh
The CSV template that ocs-operator consumes needs the ceph csi rbac roles included.
It looks like I made a lot of changes, but in reality I just reorganized common.yaml to include some new '# OLM: ...." related headers. 
For example, ```OLM: BEGIN CSI CEPHFS RBAC``` has been split up into separate sections for ServiceAccount, Role, RoleBinding, ClusterRole, and ClusterRoleBinding. This allows the csv generation logic to parse out the CSI related RBAC by object type.
I did a quick search on the previous headers like ```OLM: BEGIN CSI CEPHFS RBAC``` and they don't appear to be used anywhere in the source tree for anything, so it doesn't appear that changing these headers will disrupt anything. 
**Checklist:**
> Include csi cephfs and rbd in CSV template

- pkg/operator/ceph/operator.go
The decision to start the device discovery daemonset is made by an env var on the operator pod since in some scenarios the discovery needs to be started immediately with the operator
instead of being delay to start with the cluster. The discovery service is already started [here](https://github.com/rook/rook/blob/master/pkg/operator/ceph/operator.go#L100-L105), so there is no need to start it inside `startSystemDaemons()`.
Resolves #3697
**Checklist:**
> Start the ceph device discovery only based on env var

- tests/scripts/minikube.sh
Let's create the symlink one directory above dataDirHostPath so that
chown won't complain that this is a symlink.
Closes: https://github.com/rook/rook/issues/3529
Resolves https://github.com/rook/rook/issues/3529
**Checklist:**
[skip ci]
> minikube: fix symlink

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/k8sutil/deployment.go
Added a new property in the `storageClassDeviceSet` named `portable`. 
- `true`: The CRUSH map will use the PVC name in place of the host (already the behavior with the OSDs on PVCs)
- `false`: The CRUSH map will use the host name (the traditional behavior)
Resolves #3648 
**Checklist:**
>  OSD: CRUSH map can be based on node or PVC in case of PVC backed OSD

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
For the external cluster setup, we don't have monitors to deploy because
we connect to external ones. So in the common.yaml we must not require a
mon section to be defined in the cluster CR.
Resolves: #3713 
**Checklist:**
> ceph: do not require mon in common.yaml

- pkg/daemon/ceph/osd/volume.go
Ensure that the metadata device and osd devices are passed as a space
separated list to ceph-volume.  Currently osds-per-device is placed
between the `metadataDevice` and the osd devices causing a provisioning error
whenever `metadataDevice` is specified. PR #3696 fixes this issue as well.
Resolves #
**Checklist:**
> ceph: fix md and dev ordering for c-v batch

- cmd/rook/ceph/osd.go
Since Rook is no longer creating partitions and leaving all that work to ceph-volume, we should let ceph-volume choose the defaults for the database size and use the max available. The default of 20GB in fact doesn't even make sense since Ceph will only use the first 3GB of that size and the other 17GB was wasted.
Resolves #3448 
@alfredodeza If `--block-db-size` is not specified, c-v will use the max possible space on the ssd that can accommodate all the OSDs being configured in the batch, right?
@mvollman fyi
**Checklist:**
[skip ci]
leseb: known ci failure
> Ceph: Remove default database size for OSDs

- pkg/operator/ceph/cluster/osd/spec.go
Fixed label selector for osd prepare job pod.
Resolves #3727 
**Checklist:**
> OSD: fixed label selector for osd prepare job pod

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
Add pidlimit flag  for cephfs and rbd plugin
Resolves #
**Checklist:**
> Add pidlimit flag  for cephfs and rbd plugin

- cluster/examples/kubernetes/ceph/csi/rbd/pvc-restore.yaml
update storageclass name in  pvc-restore
Resolves #
**Checklist:**
[skip ci]
> update storageclass name in  pvc-restore

- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/_helpers.tpl
- cluster/charts/rook-ceph/templates/serviceaccount.yaml
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/common.yaml
Allow to specify imagePullSecrets to pull operator images from private registry
Signed-off-by: Maksim Nabokikh <maksim.nabokikh@flant.com>
Helps to keep image of rook operator in private registry in terms of security, latency issues or public registry access problems.
With this PR deployments and daemonsets cat recive imagePullSecrets either from command line or from operator pod specs.
Resolves #
**Checklist:**
> rook: Add image pull secrets option

- pkg/operator/ceph/cluster/osd/spec.go
The init container for copying binaries was being overwritten by the init container for initializing pvcs. This change appends the init containers so all expected init containers are preserved. This is related to #3573 that just merged where the copy binaries container was converted to an init container.
With this issue all clusters with OSDs on PVCs will fail to create the OSD prepare jobs. Evidence that we need an integration test using PVCs...
**Checklist:**
> Copy binaries init container for osds on pvcs provisioning

- PendingReleaseNotes.md
- cmd/rook/ceph/osd.go
- cmd/rook/ceph/osd_test.go
- pkg/daemon/ceph/osd/device.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/osd/config/config.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
Adding support for the db-devices flag for ceph versions 14.2.1 and
newer.  This flag will allow for explicitly setting the db device for
bluestore configurations to the device specified as metadataDevice.
Fixing the databaseSizeMB config parameter to ensure it is used to set
the size of the db-device partition when specified at either the global
or individual device level. (#3652)
Resolves #3652 
**Checklist:**
> ceph: add db-devices flag and fix DatabaseSizeMB

- Documentation/ceph-csi-drivers.md
- Documentation/ceph-monitoring.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-svc.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-svc.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
- cluster/examples/kubernetes/ceph/monitoring/csi-liveness-service-monitor.yaml
- cluster/examples/kubernetes/ceph/monitoring/csi-metrics-service-monitor.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cmd/rook/ceph/operator.go
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/util.go
- pkg/operator/k8sutil/daemonset.go
- pkg/operator/k8sutil/deployment.go
- pkg/operator/k8sutil/statefulset.go
- tests/framework/installer/ceph_csi_templates.go
- tests/framework/installer/ceph_manifests.go
grpc metrics is made an option in rook this can be enabled with ROOK_CSI_ENABLE_GRPC_METRCS variable in operator.yaml this will help admin who wants to check the grpc metrics of the ceph-csi plugins
This also changes the liveness probe port range of 9080 ad 9081
depends on https://github.com/ceph/ceph-csi/pull/566
Resolves #
**Checklist:**
[skip ci]
leseb: known ci issue
> Implement grpc metrics for cephcsi

- cmd/rook/ceph/osd.go
Backport: Since Rook is no longer creating partitions and leaving all that work to ceph-volume, we should let ceph-volume choose the defaults for the database size and use the max available. The default of 20GB in fact doesn't even make sense since Ceph will only use the first 3GB of that size and the other 17GB was wasted.
Resolves #3448 
**Checklist:**
> Backport: Remove default database size for OSDs

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator-with-csi.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
Set the version of the rook/ceph image to v1.0.6 for the release.
**Checklist:**
[skip ci]
> Set image version in manifests to v1.0.6
