- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/disruption/clusterdisruption/reconcile.go
A few minor log messages to cleanup the operator logs... The log messages for orchestrations being skipped due to nodes still being schedulable or unschedulable is filling the logs. The log message for reconciling is now debug, and also fixed another formatting log message.
**Checklist:**
> Clean up verbose Ceph logging

- pkg/daemon/ceph/osd/volume.go
udev is not running in the container so lvm might be stuck requesting lvm
devices. So let's not talk to udev to get lvm devices.
**Checklist:**
> ceph: osd lvm flag

- build/makelib/helm.mk
In order to not leave any modified file after release, lets put
chart tree aside and run sed logic on it.
Signed-off-by: Dinar Valeev <k0da@opensuse.org>
Resolves  #3746
**Checklist:**
> bugfix: copy helm chart aside for packaging

- cluster/charts/rook-ceph/.gitignore
Since values.yaml is no longer generated from a template
thanks to #3701, the .gitignore file shouldn't be needed.
[skip ci]
**Checklist:**
> Remove outdated cluster/charts/rook-ceph/.gitignore

- Documentation/ceph-toolbox.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the creation of the release-1.1 branch, we need a stable image tag for testing of the release to match the tag v1.1.0-beta.0. This PR updates the related manifests to point to that tag, such as `rook/ceph:v1.1.0-beta.0`
Resolves #3757 
**Checklist:**
[skip ci]
> Set image tag for the v1.1.0-beta.0 release

- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/scc.yaml
attacher is part of provisioner deployment, so provisioner service account will be used
for provisisoner deployments, no need of attacher service account.
Resolves #
**Checklist:**
[skip ci]
> Remove attacher service account

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/config/config.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/spec/version.go
- pkg/operator/ceph/version/version.go
- pkg/operator/ceph/version/version_test.go
Add various upgrade tests so that the local cluster does not fail if
an upgrade is available on the external cluster.
Also, add better upgrades handling on update and on add. We now rely as
much as possible on a unique function that works both local and external
cluster 'detectAndValidateCephVersion()'. So the code will act the same
way wether a CR update is triggered or if the operator is restarted.
The health check now reports any topology changes on the external
cluster such as odd number of mons and low number. It will also detect
if the external cluster has been upgraded and will log that information,
helping the admin in his/her decision to trigger an image upgrade.
Finally, we prevent the creation of new CRs if the external cluster
version has a …
> ceph: external be a bit more flexible on upgrade

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-quickstart.md
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- images/ceph/Makefile
- pkg/operator/ceph/cluster/controller_test.go
- tests/framework/installer/ceph_installer.go
- tests/longhaul/base_block_test.go
Let's use the latest minor release of Ceph.
Resolves #
**Checklist:**
> ceph: bump to 14.2.3

- Documentation/ceph-block.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/flex/storageclass-ec.yaml
- cluster/examples/kubernetes/ceph/flex/storageclass-test.yaml
- cluster/examples/kubernetes/ceph/flex/storageclass.yaml
- cmd/rookflex/cmd/expander.go
- pkg/daemon/ceph/agent/flexvolume/controller.go
- pkg/daemon/ceph/agent/flexvolume/manager/ceph/manager.go
- pkg/daemon/ceph/agent/flexvolume/manager/fake.go
- pkg/daemon/ceph/agent/flexvolume/server.go
- pkg/daemon/ceph/agent/flexvolume/types.go
- pkg/daemon/ceph/client/image.go
- pkg/daemon/ceph/client/image_test.go
- tests/framework/clients/block.go
- tests/framework/clients/pool.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.0.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_base_block_test.go
- tests/integration/ceph_block_create_test.go
- tests/integration/ceph_zblock_mount_unmount_test.go
- tests/longhaul/block_with_fencing_test.go
Allow to dynamic resize of rook volums.
Signed-off-by: Maksim Nabokikh <maksim.nabokikh@flant.com>
1. Increase PVC size.
2. Delete stateful pod.
3. Magic.
4. Your volume grows up!
Works for kubernetes 1.14.0+
Tested with minikube 1.14.1.
Resolves #1169
**Checklist:**
> ceph: Add dynamic flexvolume expansion

- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
OSD pods when running on PVC fail randomly due to some race condition:
OSD daemon pod was activating the volume group using vgchange -an without any volume group name.
- This caused the pods to fail randomly when number of OSDs is more, say greater than 10.
- This fix adds Volume group name while activating/deactivating volume groups to fix this
Resolves #3612
**Checklist:**
> fix random OSD daemon pod failures when running OSD on PVC

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/charts/rook-ceph/templates/clusterrolebinding.yaml
The bucket provisioning feature was merged without the rbac for the helm chart. This brings the helm chart back into parity with common.yaml and avoid seeing errors in the operator log about attempting to watch the bucket provisioning CR.
Resolves #3777 
**Checklist:**
> Add the rbac to the helm chart for bucket provisioning

- pkg/daemon/ceph/osd/volume.go
Osd pods getting into panic state due to index out of range error.
logs of osd prepare job:
```
[aranjan@localhost:~]$ oc logs -f rook-ceph-osd-prepare-set1-0-data-6f2nh-zh4zl
2019-09-06 07:48:11.448085 I | cephcmd: desired devices to configure osds: [{Name:/mnt/set1-0-data-6f2nh OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: IsFilter:false}]
2019-09-06 07:48:11.449841 I | rookcmd: starting Rook v1.0.0-623.gc18d575c.dirty with arguments '/rook/rook ceph osd provision'
2019-09-06 07:48:11.449866 I | rookcmd: flag values: --cluster-id=308f232a-d07a-11e9-96ba-0adfe2bb9bfc, --data-device-filter=, --data-devices=/mnt/set1-0-data-6f2nh, --data-directories=, --encrypted-device=false, --force-format=false, --
help=false, --location=, --log-flush-frequency=5s, --log-level=INFO, …
```
> fix(osd prepare): osd prepare job getting into panic state

- tests/integration/ceph_base_block_test.go
Master was broken from a bad merge with #3759 
**Checklist:**
> Fix build break from bad merge with method rename

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/osd/osd.go
Some users have reported issues running Ceph OSDs in environments
without beefy systems. After consulting with Ceph experts, we believe
2Gb is still a safe minimum for Ceph for users with more modest systems
that won't result in disfunction in Ceph.
We hope this will help with #3132 but are not certain it will resolve the issue.
**Checklist:**
[test ceph]
> Ceph osd: lower OSD pod minimum mem to 2Gb

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
https://github.com/ceph/ceph-csi/pull/550 made the servers configurable to avoid noise on the GRPC metrics and also to avoid unnecessary server starting
Resolves #
**Checklist:**
> configure cephfs  and rbd servers

- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
Replace canary tag with release ceph-csi v1.2.0 tag
Resolves #3766
Resolves #3635 
**Checklist:**
> Use v1.2.0 ceph-csi version

- cluster/examples/kubernetes/nfs/operator.yaml
NFS operator.yaml example file had Windows (CRLF) line endings instead
of the Unix (LF) line endings used elsewhere. Fix this.
[skip ci]
**Checklist:**
> NFS: Fix operator.yaml line endings

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
rounded the value of MonLeaderChange Rate to 2 decimal points (e.g. 2.44)
previously, we had 16 decimal points (e.g. 2.4406779661016946).
This makes the alert notification more sensible and readable.
Resolves #
**Checklist:**
[skip ci]
> Fixed HighMonLeaderChanges Alert

- pkg/operator/ceph/disruption/clusterdisruption/location.go
- pkg/operator/ceph/disruption/clusterdisruption/reconcile.go
- pkg/operator/ceph/disruption/nodedrain/add.go
- pkg/operator/ceph/disruption/nodedrain/reconcile.go
Edit: retest this please
Testing PR #3781 revealed a bug where drain requests were being triggered by unschedulable masters in the same region/zone.
Have verified that the new behavior works
Resolves #
**Checklist:**
> Fix: only schedule node drain canaries on nodes with osds

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
At present, the request timeout of sidecars are at the 60s and this is a request to increase
this time out value to 150s or higher. The higher timeout value can help to reduce the
load of our backend ceph cluster and also can avoid throttling issues at sidecars to an extent.
ceph-csi issue https://github.com/ceph/ceph-csi/issues/602
Resolves 
**Checklist:**
> Increase sidecar timeout from 60s to 150s

- pkg/daemon/ceph/osd/agent_test.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
ceph-volume now sends status and log output to stderr, which breaks
`ceph-volume lvm prepare` if not other things as well. Use the combined
stdout and stderr output from ceph-volume to fix this.
Resolves #3795 
**Checklist:**
[test ceph]
> Ceph: use combined output from ceph-volume

- cluster/charts/rook-ceph/templates/deployment.yaml
- tests/framework/installer/ceph_installer.go
- tests/framework/utils/helm_helper.go
- tests/integration/ceph_base_deploy_test.go
The boolean helm settings were only being applied if their value was true. If the desired value was false, the value would be skipped in the chart instead of adding it with the value of false.
Also adds a check to the integration tests a non-default setting to disable the discovery service with the helm chart and verify whether it is running.
Resolves #3804 
**Checklist:**
> Helm: Always apply boolean settings

- pkg/operator/ceph/cluster/osd/health.go
- pkg/operator/ceph/cluster/osd/spec.go
1. Set the Command property for the OSD prepare init container blkdevmapper
If a Ceph container image is specified which has a entrypoint then the Init container for osd prepare job blkdevmapper will fail. So set the Command property.
2. Changed the OSD DOWN message to debug level
We want the OSD DOWN message to be shown when debug option is set to true in the rook-ceph operator.
Resolves #
**Checklist:**
> Set the Command property for the OSD prepare init container blkdevmapper

- Documentation/ceph-upgrade.md
Add step to update CephObjectStores as part of the upgrade guide now
that `allNodes` has been deprecated for 2 releases.
**Checklist:**
[skip ci]
> Ceph upgrades: object RGW allNodes deprecation

- pkg/operator/ceph/config/config.go
It looks like on large store, the `--verbose` option is going over grpc
message buffer, since the output might be quite big.
See the error:
([chown --recursive --verbose ceph:ceph /var/log/ceph /data/rook-storage/osd11]) for
Container "osd" in Pod "rook-ceph-osd-11-85dbbb5cd6-djttp_rook-ceph(4bf77ccd-d631-11e9-8334-fa163ed365ca)" failed - error: rpc error: code = ResourceExhausted desc = grpc: trying
to send message larger than max (15133688 vs. 8388608), message: ""
Removing the verbose flag should fix this.
Resolves #
**Checklist:**
> ceph: make lifecycle hook chown less verbose

- build/makelib/helm.mk
- cluster/charts/rook-ceph/values.yaml
Remove %% around VERSION in charts yaml, so helm can process it.
Otherwise helm complains:
"unmarshal vendor values: yaml: line 7: found character that cannot start any token"
Signed-off-by: Dinar Valeev <k0da@opensuse.org>
Resolves #
**Checklist:**
> Remove helm incompatible chars from values.yaml

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
liveness container is deployed as part of the provisioner pod so it has to connect to the provisioner container and check the liveness.
Resolves #
**Checklist:**
[skip ci] leseb: random known issue
> correct liveness container socket file

- pkg/operator/ceph/disruption/machinedisruption/reconcile.go
This commit changed mdb controller to make use of cephCluster's namespace instead of cephCluster's name for checking the ceph health as the ceph config is located in the cephCluster's namespace folder which can makes mdb controller fail when rook operator is deployed in any other namespace apart from rook-ceph.
Resolves #
**Checklist:**
[skip ci] leseb:
remote file operation failed: /home/ubuntu/workspace/rook_rook_PR-3879-VEMWZ3RY63VMCDNM6XBATOZHMQGANT464RZQUBAQPAFKHZFDWHBQ at hudson.remoting.Channel@7b32ff8f:rook-node-ec2 (i-0cb6424dba95b249c): hudson.remoting.ChannelClosedException: Remote call on rook-node-ec2 (i-0cb6424dba95b249c) failed. The channel is …
> fix(fencing): changes mdb controller to use namespace for checking ceph status

- cluster/examples/kubernetes/ceph/cluster.yaml
With #3626, the default value for ssl changed
from enabled to disabled, so to get SSL for
the dashboard we will need to enable it
explicitly.
Resolves #3626
**Checklist:**
[skip ci]
> Ceph: Enable SSL for dashboard by default

- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/cluster/mon/config_test.go
The CSI secret was only being created for new clusters. Upgraded clusters did not have the secret generated. To support upgraded clusters to use CSI, we always ensure the csi secret exists when the orchestration runs.
Resolves #3874 
**Checklist:**
> Ensure the ceph-csi secret exists on upgrade

- pkg/daemon/ceph/client/upgrade.go
- pkg/daemon/ceph/client/upgrade_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/osd/osd.go
Several commands were not using the cli finalizer function which builds
up the right argument to run a ceph command. This was working on the
operator since it used to have an /etc/ceph/ceph.conf file so we could
ran the command without specifying the ceph conf and key paths.
However, we recently removed that and it silently broke this "already"
broken code :).
Resolves #
**Checklist:**
> ceph: fix upgrade commands

- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/cluster/mon/config_test.go
(cherry picked from commit 60290943efbb06f91503e2533cd5a92d8b7cfcbc)
The CSI secret was only being created for new clusters.
Upgraded clusters did not have the secret generated. To support
upgraded clusters to use CSI, we always ensure the csi secret
exists when the orchestration runs.
Resolves #3876 
**Checklist:**
> Backport: Ensure the ceph-csi secret exists on upgrade

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
liveness container is deployed as part of the provisioner pod so it has to connect to the provisioner container and check the liveness.
(cherry picked from commit https://github.com/rook/rook/commit/3c7dc1efe40e4b52f52ef90b5391865f6c32ea68)
Resolves #
**Checklist:**
[skip ci]
> backport: correct liveness container socket file

- Documentation/ceph-block.md
- Documentation/ceph-common-issues.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_base_deploy_test.go
Since Ceph CSI is stable and deployed by default, we don't need to
deploy the rook-ceph-agent daemonset.
**Checklist:**
> operator: ceph disable flexdriver

- pkg/operator/ceph/cluster/mgr/config.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
- pkg/operator/ceph/cluster/mgr/spec.go
Using port 8443 / dashboardHTTPS when not running HTTPS
is confusing, so use the dashboardHTTP port (7000 by
default) instead.
Also don't expose the dashboard port as "https-dashboard"
when not using https, instead expose as "dashboard".
Resolves #3810
**Checklist:**
> Ceph: Use HTTP port if SSL is disabled

- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
The Helm Chart should include values for the CSI images so Rook with CSI can pull the required images from a private container registry.
Resolves #3855
**Checklist:**
> Include CSI image in helm chart values

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-quickstart.md
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- images/ceph/Makefile
- pkg/operator/ceph/cluster/controller_test.go
- tests/framework/installer/ceph_installer.go
- tests/longhaul/base_block_test.go
Backport of https://github.com/rook/rook/pull/3889
> Backport ceph: bump to v14.2.4

- pkg/operator/ceph/cluster/mgr/config.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
- pkg/operator/ceph/cluster/mgr/spec.go
Using port 8443 / dashboardHTTPS when not running HTTPS
is confusing, so use the dashboardHTTP port (7000 by
default) instead.
Also don't expose the dashboard port as "https-dashboard"
when not using https, instead expose as "dashboard".
Resolves #3810
**Checklist:**
> Backport #3822: Ceph: Use HTTP port if SSL is disabled

- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
The Helm Chart should include values for the CSI images so Rook with CSI can pull the required
images from a private container registry.
cherry-pick of https://github.com/rook/rook/pull/3884
Resolves #
**Checklist:**
> Backport: Include CSI image in helm chart values

- cluster/examples/kubernetes/ceph/cluster.yaml
With #3626, the default value for ssl changed
from enabled to disabled, so to get SSL for
the dashboard we will need to enable it
explicitly.
Signed-off-by: Kristoffer Grönlund <kgronlund@suse.com>
(cherry picked from commit 35109e69f28d6477402780c4ddaf3db225f9098a)
Resolves #
**Checklist:**
> Backport #3862: Ceph: Enable SSL for dashboard by default

- pkg/operator/ceph/cluster/osd/spec.go
It's fine to enable debug logs from c-v, it's not so verbose and really
useful when debugging.
Resolves #
**Checklist:**
> ceph: enable ceph-volume debug logs

- pkg/operator/ceph/cluster/osd/spec.go
It's fine to enable debug logs from c-v, it's not so verbose and really
useful when debugging.
(cherry picked from commit c96fe8b5f83ce340cfe614bee8e03b61251737d2)
Backport of: https://github.com/rook/rook/pull/3907
> backport: ceph: enable ceph-volume debug logs

- INSTALL.md
- Jenkinsfile
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_block_create_test.go
- tests/integration/ceph_csi_test.go
- tests/integration/ceph_helm_test.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_smoke_test.go
- tests/integration/ceph_upgrade_test.go
- tests/integration/ceph_zblock_mount_unmount_test.go
There are six test suites and six k8s versions where we currently run the tests. For efficiency we can restrict the testing to one suite per k8s version. Bigger or riskier changes should still run the full set of suites on all versions. To trigger the smaller test matrix, add this to the PR description:
**Checklist:**
> Allow running minimal test matrix for ceph tests

- pkg/operator/ceph/disruption/machinedisruption/reconcile.go
This commit changed mdb controller to make use of cephCluster's namespace instead of cephCluster's name for checking the ceph health as the ceph config is located in the cephCluster's namespace folder which can makes mdb controller fail when rook operator is deployed in any other namespace apart from rook-ceph.
**NOTE:** This is the backport of https://github.com/rook/rook/pull/3879
**Checklist:**
> backport: change mdb controller to use namespace for checking status

- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/osd/spec.go
- When LVM uses a block PV (either via the OSD prepare job or the OSD pod), it appears to open the device and not release it when the accessing container terminates. This results in kube/OCP being unable to detach the PV from that node (and so can't attach to a different node).
One possible solutions (short-term-fix) is to use lvchange -an and ask LVM to release the device.
Code Changes:
- Running `lvchange -an <vg group name>` to deactivate the device.
- This command runs after 'osd prepare' completes.
- This command also runs after the 'osd daemon pod' is deleted or if the ceph-osd process terminates for some reasons. 
Resolves #
**Checklist:**
[skip-ci]
> [osd on pvc] deactivate device from lvm after OSD Prepare and OSD daemon pod ends

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/k8sutil/node.go
The node selector for running OSDs on PVCs was using the k8s node name rather than the node's hostname. In clusters where the node name is different from the hostname this would cause the osd daemons to be in pending state indefinitely. Now the node selector will use the hostname as expected.
**Checklist:**
> Ceph: OSD pods should always use hostname for node selector

- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cmd/rook/ceph/operator.go
- pkg/operator/ceph/csi/spec.go
currently, CSI templates have hardcoded kubelet path which will be used for mounting PVC,this will not work if kubelet is configured to use a different path, with this PR  kubelet path can be configured for CSI.
Resolves #3921
**Checklist:**
[test min ceph]
> Make kubelet path configurable in operator for csi

- pkg/daemon/ceph/osd/volume.go
RHEL8 introduces some lvm changes. If the base image for the ceph daemons (`cephVersion.image` in the cluster CR) is based on RHEL8 the configuration by ceph-volume will fail without the new setting. For OSDs on PVs to work we need to set `allow_changes_with_duplicate_pvs = 1`. This is required since we're copying the block image under another location.
**Checklist:**
> Configure additional LVM setting for rhel8

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-crds.yaml
- tests/framework/installer/ceph_manifests.go
While [validating](https://github.com/sebastian-philipp/rook-ceph-client-python#regenerate) the CRD validation, I had to fix six issues:
* disruptionManagement: Some validations were missing
* cluster.yaml example: `spec.mgr.modules` is not explicitly set to `nullable`
* Also: Removed `required: mon` in `ceph_manifests.go`
* `volumeClaimTemplate` was missing
* `storageClassDeviceSets` was missing
* `external.enable` was missing
> Fix CRD Validation: disruptionManagement and mgr modules

- Documentation/yugabytedb.md
Use the correct hostname when accessing the API.
Resolves #3816
[skip ci]
**Checklist:**
> Doc (Yugabyte DB): Fix hostname in API connection (#3816)

- Documentation/minio-object-store-crd.md
creating custom access/secret keys without properly base64 encoding them resulted in failed access to minio dashboard
Signed-off-by: jbmcfar <jbmcfar@sandia.gov>
Updated the minio object store documentation in regards to changing `accessKey` and `secretKey` values that could potentially result in failed to access to the minio dashboard. An example was shown with how it was resolved and links were added to the corresponding GitHub issues.
Resolves #3478 
**Checklist:**
[skip ci]
> minio: update documentation in regards to #3478

- cluster/examples/kubernetes/ceph/common.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
When displaying the CRDs OLM looks into the alm-examples field in the
CSV file, the NFS CRD example was missing so let's add it.
Resolves #
**Checklist:**
[skip ci]
> rook-ceph olm: add missing nfs crd example

- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
In commit https://github.com/rook/rook/commit/c7b861a21d729da0a4e5a86349efc8a290130bb8
flex driver got enabled  by mistake, This will fix it
Resolves #
**Checklist:**
[skip ci]
> Disable Flexdriver in helm chart and operator-openshift

- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-apply.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-create.yaml
CSI pods should look for the resources created in ROOK_SYSTEM_NAMESPACE instead
of ROOK_NAMESPACE 
Resolves #
**Checklist:**
[test min ceph]
> correct namespace for csi resources  in upgrade doc

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-crds.yaml
- tests/framework/installer/ceph_manifests.go
1. CephCluster CRD: Added `network.provider` to validation and `network.selectors`
2. Ceph CRDs: minor sync between copies
Test failure in https://github.com/ceph/ceph/pull/29427
**Checklist:**
> CephCluster CRD: Added additional network attributes to validation

- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
when nodeplugin restarts we are facing an issue with unmounting the application pod because
we are seeing double mount inside the container
More info on:
https://github.com/ceph/ceph-csi/pull/628
https://github.com/ceph/ceph-csi/issues/466
Resolves #3923
**Checklist:**
> Fix umount issue when rbd-nodeplugin restarts

- cluster/examples/kubernetes/ceph/csi/rbd/storageclass-test.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
We were defaulting to `ext4` at first and then moved to`xfs`. 
However further testing shows that, ext4 should be
the default or preferred fs for RBD devices.
This patch bring that change
Resolves #
**Checklist:**
[skip ci]
> Set default FS to "ext4" on RBD device

- cluster/examples/kubernetes/ceph/csi/rbd/storageclass-test.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
We were defaulting to `ext4` at first and then moved to`xfs`.
However further testing shows that, ext4 should be
the default or preferred fs for RBD devices.
This patch bring that change
(cherry picked from commit 3da95141910ffc51430d0ea3f46b4dc00e7f8337)
Resolves #
**Checklist:**
[skip ci]
> Backport: Set default FS to "ext4" on RBD device

- PendingReleaseNotes.md
- pkg/daemon/ceph/config/config.go
- pkg/daemon/ceph/config/config_test.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/device.go
Previously, "run dir" was used to place a number of file and config on
dataDirHostPath. Now, since a lot of configs and options have moved
either on the OSD's startup CLI line or remove with bluestore we don't
need to change the default.
Also, it was confusing for user and difficult to find the socket.
The is is not breaking any config in dataDirHostPath since all the
elements (keyrings) are hardcoded in the config file
Resolves https://github.com/rook/rook/issues/3966
**Checklist:**
> ceph: osd reset 'run dir' to default location

- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
Encrypted OSDs are failing because ceph-volume is unable to determine
how to contact the monitors.  Setting the CEPH_CONF env variable for OSD
pods fixes this issue.
Resolves #3846 
**Checklist:**
> ceph: fix encrypted osd startup

- Documentation/ceph-advanced-configuration.md
The configmap for advanced configuration can be created before the cluster is created. In that case, the daemons will all pick up the settings the first time they are started. Otherwise, the daemons need to be restarted
**Checklist:**
[skip ci]
> Clarify docs around the custom ceph.conf settings configmap

- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
updated CSI deployment templates and doc to use new cephcsi 1.2.1 release
Resolves #
**Checklist:**
> use new cephcsi release

- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
update CSI deployment templates and doc to use new cephcsi v1.2.1 release
(cherry picked from commit 0a516d5f329720d5e943bbfa75511424030c96db)
Resolves #
**Checklist:**
[skip ci]
> backport: use v1.2.1 cephcsi release

- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/cluster.go
A job is started to detect the Ceph version. This job now allows setting the node affinity and tolerations with the same setting that is specified for the mon placement. No new placement spec is required, but we will simply use the same spec that the mons use.
Resolves #3976 
**Checklist:**
> Allow setting affinity on the ceph version job

- pkg/daemon/ceph/client/filesystem_test.go
- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
- pkg/operator/ceph/object/objectstore_test.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
currently, we are not checking the pool is empty or not before deleting, This PR adds a check to check
if any images/snapshots using the pool, if yes it will not delete the pool
Resolves #
**Checklist:**
> Check Pools is in use before deleting it

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/csi/spec.go
Add a finalizer to the CephCluster to check the PV created by CSI so that we can block the
cluster deletion till the PVC's are deleted.
@ShyamsundarR is busy with other CSI work I sent a PR for this one.
Resolves #3913
**Checklist:**
> Add check for csi volumes before cluster delete

- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/cluster.go
(cherry picked from commit 0f5f2a81d74d5f02ac176816de2d16b84751ca8c)
A job is started to detect the Ceph version. This job now allows setting the node affinity and tolerations with the same setting that is specified for the mon placement. No new placement spec is required, but we will simply use the same spec that the mons use.
**Checklist:**
> Backport: Allow setting affinity on the ceph version job

- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/apis/rook.io/v1alpha2/placement_test.go
- pkg/operator/ceph/agent/agent.go
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/util.go
- pkg/operator/discover/discover.go
- pkg/operator/k8sutil/node.go
- pkg/operator/k8sutil/node_test.go
- pkg/operator/k8sutil/tolerations.go
Add Toleration and NodeAffinity to CSI provisioners deployment or statefulset through ENV variables
Resolves #3942
**Checklist:**
> Add Toleration and NodeAffinity to CSI provisioners

- Documentation/disaster-recovery.md
- PendingReleaseNotes.md
This updates the Ceph mon disaster recovery guide to use the correct
paths and commands for the current Rook Ceph release.
Not sure if there is an actual issue open to update the guide.
**Checklist:**
[skip ci]
> docs: updated Ceph mon disaster recovery guide

- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-svc.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-svc.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/util.go
- pkg/operator/ceph/csi/util_test.go
provided ENV variables to configure the grpc and liveness metrics port for both cephfs and rbd CSI drivers.
Resolves #3987
**Checklist:**
> CSI: Make metrics and liveness port configurable

- cmd/rook/ceph/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
This PR fixes the rook-config-override feature for OSDs. Currently, config overrides are not honored on OSDs.
Resolves https://github.com/rook/rook/issues/3926
**Checklist:**
> Ceph: fix rook-config-overrides for OSDs

- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
The scripts for running backend dashboard requests in rook expect this
to be an SSL-enabled port. Ensure that it is.
https://tracker.ceph.com/issues/42089
[skip ci]
> ceph: set ssl to true in cluster-minimal.yaml

- Documentation/ceph-filesystem-crd.md
- Documentation/ceph-filesystem.md
- Documentation/ceph-object-store-crd.md
- Documentation/ceph-object.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/filesystem-ec.yaml
- cluster/examples/kubernetes/ceph/filesystem-test.yaml
- cluster/examples/kubernetes/ceph/filesystem.yaml
- cluster/examples/kubernetes/ceph/object-ec.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
- cluster/examples/kubernetes/ceph/object-test.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/daemon/ceph/client/filesystem.go
- pkg/daemon/ceph/client/filesystem_test.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/objectstore_test.go
- pkg/operator/ceph/object/rgw.go
New setting to avoid delete pools on <filesystem>/<object store> deletion
Despite of the suggestion of @travisn  i have preferred to include a new "preservePools" attribute in the Ceph filesytem and Ceph Object store k8 objects.
My decision is based in the fact that these objects need several pools to keep their integrity healthy. So if we want to avoid to delete the pools storing the information in a filesystem/onject store we must be sure that all the pools are preserved always.
To have the "reclaimpolicy" (retain/delete) attribute at pool level , implies to specify this attribute for each pool, and therefore this increase the probability of error and make less comfortable to set this type of change
In any case, we also can include the "reclaim policy" …
> New setting to avoid delete pools on <filesystem>/<object store> deletion

- pkg/operator/ceph/csi/spec.go
Set the default Ceph CSI images as vars in the code instead of consts.
This allows these values to be overridden at build time with Go linker
-X flags. This allows users to build Rook in such a way that it will
automatically update the CSI images to a custom opinionated default
without having to manually manage the environment variable-based
overrides at upgrade time.
Resolves #
**Checklist:**
> ceph: set default Ceph CSI images as var not const

- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
Dashboard requires ssl to be turned on for running backend requests in rook.
Fixes: https://tracker.ceph.com/issues/42089
[skip ci]
> ceph: set ssl to true in cluster-test.yaml

- cluster/charts/rook-ceph/values.yaml
In the original help chart hyperkube was used in the prototype.
The usage of hyperkube has long since been removed from the
chart. This is cleanup to remove the reference to hyperkube
in the chart settings.
**Checklist:**
[skip ci]
> Remove obsolete hyperkube settings from the helm chart

- pkg/operator/ceph/cluster/osd/status.go
When osd nodes do not finish the prepare jobs, the user remove the
nodes manully and it causes nodes always is
'OrchestrationStatusStarting' status.
Try to remove them after completeProvisionTimeout.
Signed-off-by: James Lu <jamesluhz@gmail.com>
Resolves #
**Checklist:**
> Nodes always in OrchestrationStatusStarting

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/daemon/ceph/client/mon.go
- pkg/daemon/ceph/config/config.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/disruption/clusterdisruption/reconcile.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/version/version.go
We now differentiate the cases where:
* we only consume the external cluster
* we consume the external cluster as well as creating stateless
resources in Kubernetes (bootstrap mds,rgw, nfs)
This is mostly controlled via the image property spec. If not defined,
not extra CRs won't be able to be created.
Now the external cluster feature supports cluster as of Luminous 12.2.
Resolves #
**Checklist:**
> ceph: relax pre-requisite for external cluster

- pkg/operator/ceph/cluster/osd/spec.go
Fixes https://github.com/rook/rook/issues/4045
Drop decimal places for `--osd-memory-target` OSD argument.
Resolves #4045
**Checklist:**
> remove decimal point for osdMemoryTargetValue

- .mergify.yml
Let's not do a rebase, but only merge. Rook is configured to refuse the
rebase and mergify fails with the following Github error:
GitHub error message: Rebase merges are not allowed on this repository.
Resolves #
**Checklist:**
[skip ci]
> mergify: change config to allow auto-merging

- pkg/operator/ceph/disruption/clusterdisruption/pools.go
[test ceph min] 
Take activeStandby into account for CephFileSystem disruption budget. The minAvailable for the PDB will be incremented by 1 if activeStandby is set.
Resolves #
**Checklist:**
> [Ceph] Fix: PDB for MDS not created when activeStandby:true and activeCount: 1

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
when multiple CSI drivers are running in a cluster, each should use unique socket for registration.
Resolves #
**Checklist:**
> csi: update cephfs registration directory name

- INSTALL.md
- Jenkinsfile
The CI runs the integration tests on several versions of K8s. By default the integration tests have all been running on all versions of K8s. With the recent option to run a minimum matrix for ceph tests it has shown to be reliable for PRs and is much faster to have the test distribution. So we will make this the default to run the tests in a distributed way.
Larger or riskier PRs should run the full test suite by the new option:
```
test full
```
Master and release builds will still always run the full set of test suites on all versions of K8s.
**Checklist:**
> Run the distributed test matrix in PRs

- build/release/Makefile
The master branch uses the first tag from the last release to create the version tag. Since the 1.1 release this tag can include the alpha, beta, or rc tags, which only make sense for the release tags, but not the master tag. This change removes the suffix from the master tag.
The most recent master tag is `v1.1.0-beta.0.228.gb40321f`. 
With the change, the tag would now be `v1.1.0.228.gb40321f`.
**Checklist:**
[skip ci]
> Sanitize the master tag

- pkg/clusterd/disk.go
- pkg/daemon/ceph/osd/daemon.go
`PopulateDeviceInfo()` in `pkg/clusterd/disk.go` returns nil as `*sys.LocalDisk` if an error has occurred.
This causes a nil pointer exception at `getAvailableDevices()` in `pkg/daemon/ceph/osd/daemon.go`.
At least the returned value should be checked at the caller.
I added an explicit error to the return value of `PopulateDeviceInfo()`.
This naturally revokes an error check at the caller.
I modified `PopulateDeviceUdevInfo()` in the same file too.
**Checklist:**
> Return explicit errors

- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/config.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/config/config.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/spec/spec.go
- pkg/operator/ceph/spec/spec_test.go
- pkg/operator/ceph/test/podspec.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_upgrade_test.go
The goal is to run dir-based OSDs using the new config patterns used by the other Ceph daemons.
This will hopefully be several very small commits that each still have reasonably working dir-based OSDs.
**Checklist:**
[test ceph]
> Ceph directory-based OSDs: config refactoring

- pkg/operator/ceph/cluster/osd/spec.go
add missing env variables to OSD pods
Signed-off-by: Mateusz Los <los.mateusz@gmail.com>
Resolves https://github.com/rook/rook/issues/4101
**Checklist:**
[test ceph]
> ceph: fix topologyAware support

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
The current implementation was overriding any previous annotations set on
the object meta.
Moving the logic to its own method as well as adding unit tests.
Closes: https://github.com/rook/rook/issues/4106
Resolves https://github.com/rook/rook/issues/4106
**Checklist:**
> ceph: mgr do not override annotation

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- tests/framework/installer/ceph_manifests.go
Fixes
```
rook_ceph_client/tests/test_examples.py::test_filesystem[filesystem-ec] FAILED                                                                                                                                                                                                       [ 58%]
rook_ceph_client/tests/test_examples.py::test_filesystem[filesystem-test] FAILED                                                                                                                                                                                                     [ 62%]
rook_ceph_client/tests/test_examples.py::test_filesystem[filesystem] FAILED …
```
> Ceph CRD Validation: Add reservePoolsOnDelete

- pkg/operator/edgefs/cluster/cluster_deployment_config.go
If no devices specified in cluster.yaml then autoRtlfs mode should be selected and 4 folders should be created on each node
Resolves #4103
**Checklist:**
> Edgefs: Rtlfs devices should be more then 3 on all nodes fix

- design/object-bucket.md
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/objectstore_test.go
This is used for S3 multipart uploads and should be configured in the same way as other metadata pools.
Added the `non-ec` pool to the list of metadata pools to be configured, and updated the list of metadata pools in the design doc.
I haven't added tests as bucket creation is already covered in unit testing by `TestCreateObjectStore` in `pkg/operator/ceph/object/rgw_test.go`. 
The only other tests I could think that may be worth adding were: 
- An S3 multipart upload as part of the smoke suite. As per #4073 this would still have passed without this fix (because the replication factor in the integration testing environment is high enough to support the default pool size), so maybe this is a separate issue?
- Some kind of test for the edge case where a …
> Issue 4073 configure rgw non ec pool as metadata

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- pkg/apis/ceph.rook.io/v1/resources.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/osd/status_test.go
The osd-prepare jobs should not inherit osd resources since this might
cause scheduling issues.
Instead, we can now use the new CRD property `prepareosd` in the resource section.
Refer to the documentation for more details.
Closes: https://github.com/rook/rook/issues/2502
Resolves #
**Checklist:**
> ceph: expose prepare pod resource limits

- Documentation/ceph-cluster-crd.md
- pkg/operator/ceph/cluster/osd/osd.go
OSD on PVC provisioning fails if k8s version is less than 1.13.0
- updated document to reflect minimum k8s version required.
- Added check to skip OSD on pvc provisoning if the minimum k8s version requirement is not met.
Resolves #4008
**Checklist:**
[test ceph]
> [OSD on PVC] add kubernetes version check.

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- pkg/apis/ceph.rook.io/v1/resources.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/osd/status_test.go
The osd-prepare jobs should not inherit osd resources since this might
cause scheduling issues.
Instead, we can now use the new CRD property `prepareosd` in the resource section.
Refer to the documentation for more details.
Closes: https://github.com/rook/rook/issues/2502
(cherry picked from commit 1765ad65083b55bab91c774081ff9ee12521e9bd)
Resolves #
**Checklist:**
> Backport: ceph: expose prepare pod resource limits

- Jenkinsfile
- PendingReleaseNotes.md
- pkg/operator/ceph/object/user/controller.go
- tests/framework/clients/object_user.go
- tests/framework/installer/edgefs_manifest.go
- tests/framework/installer/provisioners.go
- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_base_object_test.go
- tests/scripts/helm.sh
K8s 1.16 was released today. This adds v1.16.0 to the test matrix and also updates the other k8s versions to the latest patch releases for testing.
Still need to update documentation about supported versions...
**Checklist:**
[test full]
> Add k8s 1.16 to the integration test matrix

- Documentation/ceph-block.md
- Documentation/ceph-filesystem.md
- cluster/examples/kubernetes/ceph/csi/cephfs/storageclass.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/snapshotclass.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass-test.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
- pkg/daemon/ceph/client/erasure-code-profile.go
- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/model/pool.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/cluster/mon/config_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
- pkg/operator/ceph/config/keyring/store.go
- pkg/operator/ceph/csi/secrets.go
- pkg/operator/ceph/csi/secrets_test.go
- pkg/operator/ceph/file/filesystem.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_csi_test.go
We know create 4 secrets containing 4 ceph keys where each of them have
limited permissions to access the cluster.
Closes: https://github.com/rook/rook/issues/4074
Resolves https://github.com/rook/rook/issues/4074
**Checklist:**
> ceph: rework csi keys and secrets

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/osd/health.go
- pkg/operator/ceph/cluster/osd/health_test.go
OSDs can be removed automatically with the current mechanism if a new
setting removeOSDsIfOutAndSafeToRemove is set to true. The default for
all new or upgraded clusters should be false.
Added removeOSDsIfOutAndSafeToRemove to Cluster CR
Fixed the logs that are verbose when the osds are safe to remove and the messages keep logging even after the osd deployment is removed.
Resolves #4000 
**Checklist:**
[test ceph]
> Ceph: Added removeOSDsIfOutAndSafeToRemove to Cluster CR

- pkg/daemon/ceph/osd/agent.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/util/sys/device.go
.Signed-off-by: Santosh Pillai <sapillai@redhat.com>
OSD on PVC does not upgrade when the user upgrades the ceph version on cluster-on-pvc yaml.
The solutions includes:
- upgrade osd prepare and daemon pods on upgrade
- skip c-v prepare if file system is already present on the pvc device.
- skip lvm release in case of upgrade.
Resolves #3956
**Checklist:**
> fix operator reconcile to restart osd daemons

- pkg/daemon/ceph/client/status.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/orchestrator.go
- pkg/operator/ceph/cluster/mgr/orchestrator_test.go
- pkg/operator/ceph/cluster/mon/mon.go
When testing the scenario of restoring a cluster after rebuilding k8s (described [here](https://github.com/rook/rook/issues/1653#issuecomment-536696481)), there are some small fixes to enable the scenario:
1. When creating mon quorum, immediately create all mon deployments. The operator was waiting for quorum after starting the first one, but at least two mons needed to be up. After starting all mons, then check for quorum.
1. Certain requests to mgr modules are hanging while the OSDs are still down. Changed this to timeout when these requests are not responsive. 
1. Unrelated change to reduce operator verbose logging around checking for clean PGs.
Related to #1653 
**Checklist:**
> Enable restoring a cluster after disaster recovery

- pkg/operator/ceph/cluster/osd/spec.go
(Split out from #4131) 
Legacy bluestore osds (not provisioned with ceph-volume) were still running with --conf, which was causing the config overrides not to be picked up. 
Resolves #4063 
**Checklist:**
> ceph: osd remove --conf flag

- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-create.yaml
- pkg/operator/ceph/csi/spec.go
This will be helpful to list the CSI drivers deployed in the kubernetes cluster. if we have N number of
CSI drivers deployed in the cluster, the user can query `kubectl get csidriver` and get  the list of
registered CSI drivers and it requires kube 1.14+ and also the functionality is disabled by default
More info here: https://github.com/ceph/ceph-csi/pull/698
Resolves #
**Checklist:**
[skip ci]
> CSI: Add support for CSIDriver object creation

- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.0-create.yaml
- pkg/operator/ceph/csi/spec.go
I merged https://github.com/rook/rook/pull/4169 too quickly and didn't
noticed we were supposed to wait for csi 1.2.2.
This reverts commit 520ad44d71a23342913e8a84862bdd6d85fad01f.
[skip ci]
> ceph: revert "CSI: Add support for CSIDriver object creation"

- pkg/daemon/ceph/config/config.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/k8sutil/pod.go
The filestore OSDs in the 1.1 release require the --conf option. In master this was not necessary due to the changes to OSD configuration in #3554. In the release branch we still need to merge the config overrides and specify --conf.
Resolves #4164 
**Checklist:**
> Restore --conf option for filestore osds and config override settings

- pkg/operator/ceph/csi/spec.go
- pkg/operator/k8sutil/statefulset.go
Add rook version label to CSI deployments/daemonsets/statefulsets just as the Ceph daemons.
Signed-off-by: Song Gao <2695690803@qq.com>
Add rook-version label for CSI deployments/daemonsets/statefulsets.
Resolves #4120
**Checklist:**
[test ceph]
> ceph: add label for CSI deployments/daemonsets/statefulsets

- pkg/daemon/ceph/client/command_test.go
- pkg/daemon/ceph/client/mon.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/mon.go
In Octopus, this commit
https://github.com/ceph/ceph/pull/30859/commits/c09b82a80a392ccd0da7677c7b424ce5cd3fa5d6
moved the quorum_status command to a socket call. Thus, the `ceph
quorum_status` command does not exist anymore, to use it we need to do
`ceph daemon mon.$ID quorum_status`. However, this command only works
locally so it won't work if we run it from the operator.
The `ceph mon_status` command is a general command that run from
anywhere and returns the mon map, let's use this one on the operator
code.
This is not a breaking change.
**Checklist:**
> ceph: use quorum_status instead of mon_status

- pkg/daemon/ceph/agent/flexvolume/controller.go
- pkg/daemon/ceph/agent/flexvolume/controller_test.go
If a volume is being attached, it should be verified that the volume is safe to attach. The volume was assumed to be safe to attach if it was for the same pod. But this was assuming the pod of the same name would be on the same node. This is true for pods created from deployments, but not for pods that are part of a stateful set. A stateful set will maintain the pod name even as the pod is failed over to a new node. Therefore, the fencing must check if the pod is from the same node before allowing the attach to continue. Otherwise, we need to wait for the volume to be detached from the other node.
The critical part of this change is adding the check for `&& attachment.Node == node`. The other changes are just for readability.
**Which issue is resolved by …
> Flex driver should not allow attach before detach on a different node

- pkg/operator/ceph/cluster/osd/osd.go
Use the right struct field. Previously it was pointing to the osd global
resource now it does the osd prepare.
Closes: https://github.com/rook/rook/issues/4182
Resolves https://github.com/rook/rook/issues/4182
**Checklist:**
[test ceph]
> ceph: fix set osd prepare resources

- tests/README.md
PR #3611 added the possibility of using something other
than docker as the container CLI, but the readme wasn't
updated.
[skip ci]
Signed-off-by: Kristoffer Grönlund <kgronlund@suse.com>
**Checklist:**
> Tests: Document the DOCKERCMD environment variable

- pkg/operator/ceph/object/bucket/provisioner.go
This issue is seen in brownfield cases in which max_bucket
size for the user is set to 0. In rgw, if the max_bucket is 0
then the user can create an unlimited no of buckets.
So for preventing users creating new buckets, set the value to
any negative value
Resolves #4080
**Checklist:**
> objectstore: set quota for max_bucket into -1 in Grant()

- pkg/operator/ceph/cluster/osd/config.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/config/keyring/store.go
Generating keyrings after deployments created a race condition
resulting in intermittent OSD pod failure on the first attempt.
This change creates keyrings prior to creation of OSD deployments
and updates the owner after the creation of a deployment.
Resolves #4089
**Checklist:**
> ceph: Generate keyrings before OSD deployment

- pkg/operator/ceph/cr_manager.go
- pkg/operator/ceph/disruption/controllerconfig/context.go
- pkg/operator/ceph/disruption/nodedrain/reconcile.go
Previously, the drain-canary used the busybox image. This changes that to the rook/ceph image. This is so that we don't needlessly consume another image that we don't control.
The footprint of running the image should remain small. Even though the image itself is so large, its runtime footprint would be reasonable if it's just loading tini and sleep. The image is necessary on all the nodes running rook/ceph anyway.
> Ceph: use the rook image for drain-canaries.

- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/mon/env.go
- pkg/operator/ceph/cluster/osd/spec.go
Some testing on OpenShift has shown that enabling Hostnetworking causes
issues with ceph-volume creating OSD.
This is a pure Red Hat OpenShift downstream issue.
This is meant to be temporary while we are waiting for the Selinux team
to get back to us.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1764275
**Checklist:**
> ceph: osd hide 'restorecon' when necessary

- pkg/operator/ceph/cluster/controller.go
when running OSD on PVC, orchestration should not be started again if there is any change in the device config map.
Added a check to skip orchestration on device CM update when StorageClassDeviceSets are available, that is, when running osd on pvc.
Resolves #4124
**Checklist:**
> stop orchestration restart on device config map update for osd on pvc

- pkg/operator/ceph/disruption/controllerconfig/toleration.go
- pkg/operator/ceph/disruption/controllerconfig/toleration_test.go
- pkg/operator/ceph/disruption/nodedrain/reconcile.go
The drain canary collects tolerations from OSDs as there are multiple sources
of tolerations and the canary needs to follow the OSD. There was an issue with
the deduplication that caused very frequent updates to the drain-canary toleration.
This rendered it unusable is some scenarios.
- Change map key to a string to ensure it is deterministic. The old key was a struct that included a pointer. 
- Sort the outputted list by this key to ensure the order is deterministic.
- Get the tolerations from the deployment instead of the pod as pod tolerations are sometimes modified by the system. We only want user provided tolerations in our deployment.
Resolves # …
> Ceph: fix the deduplication of tolerations collected for the drain-canary

- cluster/charts/rook-ceph/templates/clusterrolebinding.yaml
- Include missing role bindings already present in `common.yaml` file and not in the
`clusterrolebindings.yaml` file for the Ceph Helm chart.
- Added the file `cluster-psp.yaml` which is needed to include the basic
resources, cluster roles , and role bindings to make work PodSecurityPolicy
admission controller in the k8 cluster.
Resolves #3851 
**Checklist:**
- [ x ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
[test ceph]
> ceph: Included missing rolebindings for PSP in Helm chart

- .github/stale.yml
Issues are already being marked as stale if there is no activity for 90 days and then closed after a week. Pull requests have not been closed automatically. While all contributions are valued, if a PR is not getting attention for a long period of time, it is not adding any value and requires attention to move forward. 
This change will cause pull requests to be marked as stale after six months of inactivity. If there is no further activity, the PR will be closed after one more month.
**Checklist:**
[skip ci]
> Close stale pull requests if no activity

- pkg/operator/edgefs/cluster/target/pod.go
CAP_NET_ADMIN capability added to corosync container in edgefs's operator
(Re-submitted w/ DCO; original PR: https://github.com/rook/rook/pull/4121)
Resolves https://github.com/Nexenta/edgefs/issues/393
**Checklist:**
[test edgefs]
> edgefs: Add NET_ADMIN to corosync container capabilities

- tests/framework/clients/pool.go
- tests/integration/ceph_base_block_test.go
- tests/integration/ceph_block_test.go
- tests/integration/ceph_upgrade_test.go
The block integration tests are a source of intermittent failures in the CI. The PVCs were not being confirmed as removed before the pools were deleted. Then the pool would not be removed since there might still be a block image from the PVC that wasn't deleted yet. Now the tests will ensure the PVCs and their block images are removed before the pool is deleted.
K8s APIs are also called to delete resources during the test instead of recreating entire yaml snippets in order to delete the resources.
**Checklist:**
[test ceph]
> Clean up block integration tests more reliably

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cmd/rook/ceph/osd.go
- cmd/rook/ceph/osd_test.go
- pkg/operator/ceph/cluster/osd/topology.go
- pkg/operator/ceph/cluster/osd/topology_test.go
- pkg/operator/ceph/disruption/clusterdisruption/pools.go
- pkg/operator/k8sutil/node.go
The node labels were already supported for zones and regions to add to the CRUSH map. Now all layers of the CRUSH map will be supported with the new labels such as `topology.rook.io/rack`. The labels will be detected at the osd startup time similar to the zone and region labels already being detected.
The example cluster.yaml will also have `topologyAware` set to true by default. In the future we should just remove this setting and always use topology labels automatically. This will be done with #4131.  
**Checklist:**
[test ceph]
[skip ci]
> Support all layers of CRUSH map with node labels

- Documentation/helm-operator.md
- cluster/charts/rook-ceph/templates/deployment.yaml
ceph: helm: fix operator chart rbdGrpcMetricsPort
This fixes the conditional for the `rbdGrpcMetricsPort` option.
Previously the `rbdGrpcMetricsPort` was useless as it was not used,
instead the Helm chart looked for `cephfsrbdGrpcMetricsPort` option.
docs: added missing Rook Ceph operator helm values
Added missing csi values of the Rook Ceph operator helm chart to the
documentation.
Resolves #4177 
**Checklist:**
[test ceph]
> ceph: helm: fix operator chart rbdGrpcMetricsPort

- pkg/operator/ceph/cluster/cluster.go
Fix for automatic orchestration triggering even if the cluster CRD is unchanged.
Added a condition to check if there is any difference while comparing the new and old cluster CRD, the only returns the `true` value.
Resolves #4201 
**Checklist:**
> ceph: added a check for triggering the orchestration

- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
Mgr annotation was previously not being set.
Signed-off-by: d-luu <david@davidluu.info>
Add setting of annotations in mgr pod that was previously missing.
Resolves #
**Checklist:**
> ceph: fix set mgr annotations

- pkg/operator/ceph/object/config.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/rgw_test.go
- pkg/operator/ceph/object/spec.go
Failure to create a keyring prior to creating a deployment
dependent on that keyring created a race conditition resulting
in an intermittent and unnecessary pod failure. This change
creates a keyring prior to any RGW deployment.
Partially fixes: #4089
Signed-off-by: egafford <egafford@redhat.com>
**Checklist:**
> ceph: Generate RGW keyrings before creating dependent deployments

- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/filesystem_test.go
- pkg/operator/ceph/file/mds/config.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/file/mds/spec_test.go
Failure to create a keyring prior to creating a deployment
dependent on that keyring created a race conditition resulting
in an intermittent and unnecessary pod failure. This change
creates a keyring prior to deployment creation for MDS
daemons.
Partially fixes: rook#4089
Signed-off-by: egafford <egafford@redhat.com>
**Checklist:**
> ceph: Generate MDS keyrings before creating dependent deployments

- Documentation/ceph-object-bucket-claim.md
- Documentation/ceph-object.md
Adding OBC details to Rook Documentation in ceph-object.md and CRD definitions as ceph-object-bucket-claim-crd.md
Resolves #3655
**Checklist:**
[skip ci]
> Add object bucket claim details to admin guide

- cmd/rook/discover.go
- pkg/clusterd/disk.go
- pkg/daemon/discover/discover.go
- pkg/daemon/discover/discover_test.go
- pkg/operator/ceph/operator.go
- pkg/operator/discover/discover.go
- pkg/operator/discover/discover_test.go
- pkg/operator/edgefs/operator.go
- pkg/util/sys/device.go
This modification adds the information extracted from 'ceph-volume inventory':
command to the device configmaps generated by the discovery daemon when "rook discover" starts with the new boolean "--use-cv" parameter. 
This parameter is set if the new env. var "ROOK_DISCOVER_USES_CEPH_VOLUME" is
set to 'true' in the operator CRD.
Resolves #
https://github.com/rook/rook/issues/2606
**Manual verification:**
_1. Use ceph-volume inventory_
```
$ grep "ROOK_DISCOVER_USES_CEPH_VOLUME" operator.yaml -a2
- name: ROOK_DISCOVER_USES_CEPH_VOLUME
value: "true"
$ kubectl  get nodes
NAME      STATUS    ROLES     AGE       VERSION
master    Ready     master    5d18h     v1.16.0
node1     Ready     <none> …
```
> Get <ceph-volume inventory> data in dev. configmaps

- pkg/operator/ceph/object/spec_test.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
The only things that should be required are the name of the pool and the
namespace. We don't need to enforce the replication type as a
requirement.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1767249
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1767249
**Checklist:**
[test ceph]
> ceph: relax cr block requirements

- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
Signed-off-by: Rajat Singh  rajasing@redhat.com
ceph: Simplification of addOrRemoveMonitor() 
Modified `addOrRemoveMonitor()` such a way that `clusterInfo` will get cleaned every time the function is being called and then get populated with `status.MonMap.Mons`
Resolves #3692 
**Checklist:**
> ceph: Simplification of addOrRemoveMonitor()

- pkg/operator/ceph/object/user/controller.go
- tests/integration/ceph_base_object_test.go
- tests/integration/ceph_mon_test.go
- retry ObjectUser creation as long as valid input is provided
or it times out. Retry every 15sec for 5min.
- integration test creates ObjectUser before ObjectStore to
ensure that ObjectUser waits for ObjectStore to be created
and available
Resolves https://github.com/rook/rook/issues/3937
**Checklist:**
[test ceph]
[test full]
> adds retry to ObjectUser creation

- pkg/operator/ceph/cluster/controller.go
Once the cluster is connected, we need to create the CSI keys so that we
can provide persistent storage to containers, via ceph csi.
Resolves #
**Checklist:**
[test ceph]
> ceph: create csi keys and secrets for external cluster

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
When an orchestration is restarted or retriggered and starts new osd prepare pods, they are unable to start because the device is already in use by the osd daemon pods.
This fix skips the osd prepare pod creation if the daemon is already running.
- Checks if OSD daemon is already present before creating OSD prepare pod for that PVC.
- If OSD daemon is present, the skip osd prepare pod creation and update the config map. 
Resolves #
**Checklist:**
> ceph: skip osd prepare job creation if osd daemon exists for the pvc

- Jenkinsfile
- tests/framework/installer/environment.go
- tests/framework/installer/installer.go
Using the current working directory as the base test directory
fails with an unclear error message when running mkfs for OSDs
if tests are run when the k8s master node is not running on
localhost.
This change creates a new flag for the test suite to set the
base test directory, but uses a default that is safe for
virtualized test environments ("/data").
Fixes: #4205
Signed-off-by: egafford <egafford@redhat.com>
**Checklist:**
> test: functional default baseTestDir for remote k8s master

- pkg/operator/ceph/cluster/mgr/config.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/osd/config.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/rbd/config.go
- pkg/operator/ceph/cluster/rbd/mirror.go
- pkg/operator/ceph/config/keyring/store.go
- pkg/operator/ceph/file/mds/config.go
This change standardizes the ownerRefs of Ceph keyrings to
k8s Deployment resources across all daemons and refactors a
bit of duplicate code on keyring association for ease of
maintenance.
Resolves #4089
Signed-off-by: egafford <egafford@redhat.com>
**Checklist:**
> ceph: Standardize association of keyrings with deployments

- Documentation/disaster-recovery.md
As mentioned in title, the kubectl edit command should be kubectl patch
Signed-off-by: Jeffrey Chu <peihuachu1112@gmail.com>
**Checklist:**
[skip ci]
> ceph: kubectl edit should be kubectl patch

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
This PR updates the Cluster storage utilization alert threshold and timing. This is an enhancement based on some experiments and observations.
This mainly takes a proactive approach to alert the user to take action when the cluster is getting close to the maximum capacity. Since ceph stops I/O at 95% utilization, the user should be warned before it. 
**Checklist:**
[skip ci]
> ceph: update cluster storage utilization alert threshold and timing

- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/mon/env.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
This reverts commit d224fbd.
Since ceph/ceph#31421, the monkey patching of
'restorecon' is not needed anymore.
This will tell ceph-volume not to run any restorecon commands by using the new environment variable `CEPH_VOLUME_SKIP_RESTORECON`.
This relies on ceph/ceph#31421
Resolves #
**Checklist:**
[test ceph]
> Ceph-volume skip restorecon

- Documentation/ceph-upgrade.md
Older CRDs from previous versions prevented VolumeSnapshots from working correctly
This PR updates the docs for upgrades that may happen from Rook v1.0 to v1.1+. The snapshot CRDs will be outdated if the CSI drivers were used which will prevent the VolumeSnapshots to be taken successfully. Retargeting to `release-1.1` as per https://github.com/rook/rook/pull/4292#issuecomment-553032019
Resolves #4178 
**Checklist:**
[skip ci]
> ceph: docs: added a note around snapshot CRD cleanup

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cmd/rook/ceph/osd.go
- cmd/rook/ceph/osd_test.go
- pkg/operator/ceph/cluster/osd/topology.go
- pkg/operator/ceph/disruption/clusterdisruption/location.go
- pkg/operator/ceph/disruption/clusterdisruption/osd.go
- pkg/operator/ceph/disruption/nodedrain/reconcile.go
- tests/framework/installer/ceph_manifests.go
[test ceph]
- Fix bug where not cleaning up drain-canaries was leading to a drain deadlock.
- Add an owner reference from the drain-canary to the node.
- As a prerequisite to fixing that, fix some topologyAware issues:
- In a discussion, I forgot to mention one place where topologyAware changes had to be brought, so parts of the clusterdisruption controller had to be updated to support the newly supported crush types.
- Label the drain canaries to make them selectable by crush type.
Resolves #
**Checklist:**
> Ceph: Fix topology logic for drains.

- pkg/daemon/ceph/osd/volume.go
The following commit from LVM
https://github.com/lvmteam/lvm2/commit/08396b4bce45fb8311979250623f04ec0ddb628c#diff-13c602a6258e57ce666a240e67c44f38
updated the lvm.conf and thus changed our filter. So now it does not
match anymore.
Updating the filter to match fixes that issue.
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1770910
**Checklist:**
[test ceph]
> ceph: update lvm filter

- pkg/operator/ceph/disruption/clusterdisruption/osd.go
- pkg/operator/ceph/disruption/clusterdisruption/reconcile.go
- Checking whether drain was incorrectly checked map instead of string length.
- Unsetting drain did not check if the cluster was clean.
- Fix: noout timestamp was being periodically reset.
Been stress testing the drain logic and noticed that a deleted node with nowhere for the OSD to go resulted in ceph NOOUT being revoked prematurely.
Resolves #
**Checklist:**
[test ceph]
> Ceph: Ensure draining state is set and checked correctly. 

- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.0.go
- tests/framework/installer/installer.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_base_file_test.go
- tests/integration/ceph_helm_test.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_upgrade_test.go
During upgrade tests, Rook should verify that it can still run legacy
OSDs. This includes directory-based OSDs, filestore disk OSDs, and
bluestore disk OSDs installed without ceph-volume (i.e., before mimic
v13.2.2) can still be run after upgrade.
This necessitates running the upgrade test twice; once with filestore
and once with bluestore.
Resolves #
**Checklist:**
[test ceph]
[test full]
[all logs]
> ceph: in upgrade test, ensure legacy osds run

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
OSDs on PVCs need some anti-affinity or other node affinity in order
to attempt to spread the OSDs across nodes. The OSD anti-affinity
is only effective when the number of OSDs matches the node count,
but at least it is a start.
**Checklist:**
[skip ci]
> Add osd anti-affinity to the example of OSDs on PVCs

- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
A recent PR #4172 added the ability for rook to create
the CSIDriver object on a kubernetes cluster. The change also
made it so that attachRequired value in the ceph CSI drivers
were set to false.
This leads to the entire attach skipping the AD controller
that deals with RWO attachment enforcement. Thus, if a
CephFS volume is marked RWO, 2 pods on different hosts can
end up mounting the same and consuming it at the same time.
Further for RBD, currently the image watchers are the only ones
that prevent a double mount of an image, other than the AD controller
enforcement of single attach for RWO RBD PVs. This has proven
not to be reliable in the face of MON failures, as the watcher
information is lost, and a second mount is allowed.
Thus, we need to bring …
> CSI: Make attach mandatory in ceph CSIDriver object

- Documentation/ceph-upgrade.md
- Documentation/helm-operator.md
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
update csi sidecar images to fix CVE-2019-11255
more info:
https://github.com/kubernetes/kubernetes/issues/85233
https://github.com/kubernetes-csi/external-snapshotter/issues/193
https://github.com/kubernetes-csi/external-provisioner/issues/380
Resolves #
**Checklist:**
> CSI: update kubernetes sidecar images

- Documentation/ceph-upgrade.md
- Documentation/helm-operator.md
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
cephcsi v1.2.2 release is out and the image is available for use, updating rook to use latest available release image
Resolves #
**Checklist:**
[test full]
[test ceph]
> CSI: update ceph-csi from v1.2.1 to v1.2.2

- pkg/operator/ceph/cluster/crash/crash.go
When running on OCP we must use priv containers so that we can chown the
hostpath dir properly.
Resolves #
**Checklist:**
[test ceph]
> ceph: add missing pod sec context for crash

- Documentation/nfs.md
In NFS document, the document example explain with `-l name=nfs-busybox` label, however no corresponding label in previous section. Fix to the label mentioned in the previous section.
Nothing
**Checklist:**
- [V] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [V] Documentation has been updated, if necessary.
- [V] Unit tests have been added, if necessary.
- [V] Integration tests have been added, if necessary.
- [V] Pending release notes updated with breaking and/or notable changes, if necessary.
- [V] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [V] Code generation …
> Fix NFS document with wrong label

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
Because of this, the mgr would be restarted if the operator image
change. This must not happen.
Added unit tests for cephMgrOrchestratorModuleEnvs() as well.
Closes: https://github.com/rook/rook/issues/4361
Resolves #
**Checklist:**
[test ceph]
> ceph: remove ROOK_VERSION from the mgr pod

- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/version/version.go
- pkg/operator/ceph/version/version_test.go
Look at the commits for more details but essentially:
* add support for build release with a ceph version output of 14.2.4-64
* update the deployment for rgw/mds even if this is not an upgrade
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1775624
**Checklist:**
[test ceph]
> ceph: fix upgrade of mds/rgw on build release

- pkg/operator/ceph/file/mds/config.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/object/config.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/spec.go
ceph: rgw and mds use ceph mon config store
The Ceph Mimic release introduced the monitor config store which allows
us to set configuration flag per daemon in a centralized fashion. Let's
use it for Mimic and newer and keep the CLI flag of daemon startup for
older versions.
The main benefit is that the config of a daemon can now be overridden.
Resolves https://github.com/rook/rook/issues/4307
**Checklist:**
[test ceph]
> ceph: rgw and mds use ceph mon config store

- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
[skip ci]
Remove non-existent topologyAware CRD option from Ceph example. This option was removed by the following commit.
commit ef6815ebfa95a9be1b7b5809268a1cfdfb573fab
Resolves #4384 
**Checklist:**
> ceph example: remove non-existent topologyAware CRD option

- Documentation/ceph-examples.md
There is a broken link in the documentation removed .md from the url to fix 
Resolves # 
**Checklist:**
[skip ci]
> doc: fixed broken link in ceph-examples

- Documentation/edgefs-quickstart.md
This is a small addition to the EdgeFS quickstart guide to clarify storage device count requirements, especially for new users that may be testing it on a single-node cluster, to make them aware of why their storage cluster does not initialize, and offer a workaround.
[skip ci]
> EdgeFS doc quickstart min storage devices and single-node workaround

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/cluster_test.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/object/controller.go
We recently discovered a race condition which happens not to update the
child CRDs when CR image changes.
The race happens under the following sequence:
* orchestration onAdd() is called when the operator image restarts
or its image updated
* the orchestration then goes into processing mon/mgr/osd
* during this the cluster CR is updated so onUpdate() is called,
however, onAdd() is not done yet for child CRDs (mds, rgw)
* onUpdate() runs against the cluster CR and updates the cluster images
* by the time the child CRDs reached onUpdate() from their respective
ParentClusterChanged() methods, the image is already up to date
so we were exiting since our check for updating
these resources are based on the cluster image version
To fix this, we changed the …
> ceph: fix race condition on crd child update

- cmd/rook/util/cmdreporter.go
In some cases in which the rook-ceph-detect-version job fails to
write to the ConfigMap, this should not cause the job to fail.
However, in the case of a temporary network partition, failing
the job improves resiliency.
This change causes the job to fail in the case that the k8s client
cannot read, create, or update the ConfigMap.
Fixes: #4301
**Checklist:**
> ceph: terminate detect-version if config write fails

- tests/scripts/minikube.sh
The helper script to start minikube has dead code that is
no longer used. Specifically, the flex driver config isn't needed
anymore and the RBAC rules are all configured in the manifests.
Neither is there a need to have a restart option on minikube.
**Checklist:**
[skip ci]
> Remove unused commands in minikube helper script

- pkg/daemon/ceph/osd/volume.go
lvmFilter doesn't contain a newline character. So when we will add more lines after lvm.conf's filter configuration line, lvm.conf will corrupt.
**Checklist:**
> ceph: add the missing newline in lvm.conf's filter configuration line

- Documentation/helm-operator.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
with this change, the snapshotter sidecar container won't be deployed by default with the rbd provisioner. we need to set a ENV `CSI_RBD_ENABLE_SNAPSHOTTER` variable in the operator template to enable deployment of snapshot sidecar in ceph-csi rbd provisioner.
Resolves #4401
**Checklist:**
[test ceph]
> CSI: Ability to disable snapshotter from ceph-csi rbd

- Gopkg.lock
- pkg/operator/ceph/cr_manager.go
Reusing the kubeconfig was resulting in concurrent access issues.
There is no DeepCopy function for rest.Config, so I just generated a new one.
Resolves #4350 
**Checklist:**
[test ceph]
> Ceph: Generate new client config for controller-runtime

- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/osd/osd.go
During an orchestration if there were failures to update any OSD deployment, the orchestration would fail and continue trying again. If the OSD(s) continued failing, the operator would be stuck in a loop and never respond to other CR updates.
Now the operator will log the OSD errors, if any, and complete the orchestration. We will rely on K8s to continue to attempt to start the OSD pods instead of the operator being stuck in the loop.
This will result in the cluster CR controller behaving similarly to the other controllers that will simply log the errors instead of being stuck in a loop. Overall we need to improve this when we update to the controller runtime so we can continue retrying upon failure, while not blocking other operations.
**Checklist:**
> Continue orchestration on osd update errors

- pkg/daemon/ceph/osd/volume.go
The append puts the filter at the end of the file and it's out of any
lvm section, so it does not work anymore.
LVM complains with:
Configuration setting "filter" invalid. It's not part of any section.
Hence we revert https://github.com/rook/rook/commit/75533182352f41368363b66e9fbc55765db40f9b and https://github.com/rook/rook/commit/eb908e8959261640b445133cbed9fe5d201cfa93.
Release 1.1 is not impacted since the most recent changes were not backported.
Resolves #
**Checklist:**
[test ceph]
> ceph: lvm filter again

- Documentation/direct-tools.md
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
Made changes by modifying the following in `toolbox.yaml`
- Adding an `emptyDir` in `toolbox.yaml`
- Deleting `privileged: true`
- Deleting `hostnetwork: true`
-   Deleting All volume and mounts except `mon-endpoint-volume`
Also Deleted all the occurrences for `direct-tools.md`.
Resolves #4297 #3706 
**Checklist:**
[test ceph]
> Ceph: Toolbox does not need to run privileged

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/csi/cluster_config.go
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/operator.go
This change:
a) Assigns an ownerRef to the CSI ConfigMap for all CSI resources.
b) Adds callback hooks to the operator for cluster deletion.
c) Deletes all CSI resources if no remaining clusters are managed
by the ClusterController.
Resolves #4234 
**Checklist:**
> ceph: clean up CSI resources on cluster deletion

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/common.yaml
- cmd/rook/ceph/osd.go
- cmd/rook/ceph/osd_test.go
- design/ceph/cluster-update.md
- pkg/apis/ceph.rook.io/v1/spec_test.go
- pkg/apis/rook.io/v1alpha2/storage.go
- pkg/apis/rook.io/v1alpha2/storage_test.go
- pkg/apis/rook.io/v1alpha2/types.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/daemon/ceph/osd/device.go
- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/osd/spec.go
Add `devicePathFilter` to Storage Selection Settings which enables device selection
with a regular expression for device path names.
For example, `devicePathFilter: "^/dev/disk/by-path/pci.*-sas-.*"` selects all SAS
devices.
This PR contains a small fix for using `ceph-volume`.
When using `devicePathFilter`, I found some device caused an error in `ceph-volume`.
This is because `ceph-volume` cannot handle a device correctly if the device has an alias
under `/dev/mapper/`.
This PR fixes it by checking whether the device has that kind of alias
and using the alias as an argument for `ceph-volume`.
Resolves #4275
**Checklist:**
> ceph: support device selection for OSDs by device path name patterns

- PendingReleaseNotes.md
- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
Essentially, this commits allows us to upgrade the operator image without having to restart the OSDs.
See commits for more details.
Resolves https://github.com/rook/rook/issues/4362 and https://github.com/rook/rook/issues/4363
**Checklist:**
[test ceph]
> ceph: do not restart the osds when upgrading the operator

- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
Add hostNetwork: true flag to rook-operator deployment.
There is use case when need to run rook operator on host network since ceph-mon is not accessible from kubernetes pod network.
**Checklist:**
> Allow to run rook operator on host network

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cmd/rook/ceph/osd.go
- design/ceph/storage-class-device-set.md
- pkg/clusterd/disk.go
- pkg/daemon/ceph/osd/agent.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/util/sys/device.go
"OSD on PVC" doesn't work for PV backed by LV. Fixing this problem
by the following changes.
- Rook accepts LVM disk type.
- If a LV-backed device is passed, Rook/Ceph invokes
"ceph-volume lvm prepare" with "--data vg/lv"
instead of "--data /path/to/device".
- If a LV-backed device is passed, Rook/Ceph suppresses
activation/deactivation of VG that owns this LV.
Resolves #4185 
**Checklist:**
> ceph: support OSD on PVC backed by LV

- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
The deviceFilter property needs to have a value rather than be completely empty as it was in the settings. This is a side effect of the schema update in common.yaml from [this commit](https://github.com/rook/rook/commit/40d868ebd73f71e2006773a24291eef700b800a0).
**Checklist:**
[skip ci]
> ceph: comment out empty deviceFilter property

- pkg/operator/ceph/cluster/osd/osd.go
When a node has been removed, cordoned, or is otherwise missing from the filters that rook uses to evaluate deploying osds on nodes, the orchestration should continue instead of failing. Otherwise, the orchestration will stay stuck in a retry loop if any nodes are cordoned or removed in the middle of an orchestration.
Such an old issue and such a simple fix...
Resolves: #2587 
**Checklist:**
[test ceph]
> Continue orchestration on missing node for osd

- pkg/util/sys/device.go
- pkg/util/sys/device_test.go
Since https://github.com/rook/rook/pull/4219, lv devices are now
presented to ceph-volume when preparing the device.
So on this initial run, this won't fail because the dm hasn't been
created yet but if an orchestration is re-triggered, the prepare pod
ensures idempotency with the ceph-volume batch command.
Unfortunately, c-v seems to have a bug where it doesn't read the dm to
detect whether or not they are ceph members already.
Ceph bug: https://tracker.ceph.com/issues/43209
**Checklist:**
[test ceph]
> ceph: reject ceph dm devices

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/crash/crash.go
- pkg/operator/ceph/cluster/crash/reconcile.go
- pkg/operator/ceph/version/version.go
This change adds rook-version and ceph-version tags to crash
collector deployments, in keeping with other Ceph deployments.
Resolves #4357
**Checklist:**
[test ceph]
> ceph: add rook-version and ceph-version tags to crash deployment

- pkg/operator/nfs/server.go
Integration tests are failing with the ganesha pid location. No need for this argument.
Resolves #4437 
**Checklist:**
[test nfs]
> Revert nfs operator pid location

- PendingReleaseNotes.md
- pkg/daemon/ceph/osd/agent.go
- pkg/daemon/ceph/osd/agent_test.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
Just as with the mon, mgr, mds, rgw, and rbd-mirror daemons, do not
generate a ceph.conf in an init container for filestore OSDs.
Instead use the commandline to supply all the needed arguments for
running these OSDs.
**Checklist:**
[test ceph]
> Ceph: OSD: refactor config for filestore OSDs

- PendingReleaseNotes.md
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/daemon/discover/discover.go
Related to https://github.com/rook/rook/issues/3772
added an environmental variable and used the variable to parse inside the regex to make the discover daemon configurable
Resolves #
**Checklist:**
[test ceph]
> ceph: make the discover daemon filter configurable

- Jenkinsfile
- build/release/Jenkinsfile.tag
- build/release/Makefile
The version suffix such as alpha.0, beta.0, or rc.0 only apply
when running the tag pipeline or the release build. Otherwise,
we don't want to use the suffix from the master build.
**Checklist:**
[skip ci]
> Always use the version suffix from release build or tag pipeline

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-quickstart.md
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- images/ceph/Makefile
- pkg/operator/ceph/cluster/controller_test.go
- tests/framework/installer/ceph_installer.go
- tests/longhaul/base_block_test.go
With https://github.com/ceph/ceph-container/pull/1529, we now build
vX.X.X version so we don't need to have the timestamp. Also we will
automatically get the last changes from the OS/packages too more
frequently.
Closes: https://github.com/rook/rook/issues/4414
Resolves https://github.com/rook/rook/issues/4414
**Checklist:**
[test ceph]
> rook-ceph: stop using ceph version with timestamp and bump to 14.2.5

- tests/framework/installer/ceph_installer.go
The new CephClient CRD needed to be cleaned up between the test suite runs. The integration tests are currently failing in master when the full test suites are run. This was missed in the PR build since only one suite was run per test machine.
**Checklist:**
[test ceph]
[test full]
> Cleanup the client crd between tests

- PendingReleaseNotes.md
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
As performed with mon, gateways from same ceph object store must not run on the same host if hostNetwork is set to true
Resolves #
**Checklist:**
> ceph: enforce pod anti affinity on gateways if hostNetwork is true

- Documentation/ceph-cluster-crd.md
Signed-off-by: taeuk_kim <taeuk_kim@tmax.co.kr>
Typo Fix in ceph cluster crd documentation
Resolves #
**Checklist:**
[skip ci]
> docs: fix typo on ceph cluster crd description

- pkg/operator/ceph/object/spec.go
to the RGWs swift objectstorage healthcheck api url [1]
which resolves an OCS false-positive CLBO of the RGW pod.
[1] https://docs.openstack.org/swift/latest/middleware.html#healthcheck
Signed-off-by: Mark Kogan <mkogan@redhat.com>
Resolves #
**Checklist:**
[test ceph]
> ceph: rgw change the liveness probe url

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Currently, there are alerts only on the cluster utilization. In the scenarios where one osd fills up more than total cluster utilization, the user should be notified for the same. This PR adds two alerts on OSD utilization for 75% and 85% thresholds.
Resolves #
**Checklist:**
[skip ci]
> ceph: Added OSD utilization alerts

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/crash/crash.go
- pkg/operator/ceph/cluster/crash/crash_test.go
- pkg/operator/ceph/cluster/crash/keyring.go
- pkg/operator/ceph/cluster/crash/keyring_test.go
- pkg/operator/ceph/config/keyring/admin.go
- pkg/operator/ceph/config/keyring/volume.go
- pkg/operator/ceph/csi/secrets.go
Add client.crash key for the crash-collector controller so it does not use the admin key.
Closes: https://github.com/rook/rook/issues/4388
Resolves https://github.com/rook/rook/issues/4388
**Checklist:**
[test ceph]
> ceph: add crash key

- tests/framework/installer/ceph_manifests_v1.0.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_base_file_test.go
- tests/integration/ceph_upgrade_test.go
Reset the integration test k8s helper's `RetryLoop` to its original
value, and instead only wait an extra long time to allow the mgr module
updates to take a long time after Ceph is updated from Mimic to Nautilus
as part of Ceph's upgrade integration test.
Updating mgr modules can hang for quite a while, which causes the tests
to time out waiting for the OSDs to be updated. Allow this to take a
long time so the tests aren't as flaky.
**Checklist:**
[test full]
[test ceph]
> ceph: integration: upgrade: long wait for mgr module - disable dashboard

- PendingReleaseNotes.md
- pkg/daemon/discover/discover.go
- pkg/operator/discover/discover.go
- pkg/operator/discover/discover_test.go
Add owner references to the discover daemon pod as well as the config map. So, when the Operator is deleted both will go away too.
Resolves #
**Checklist:**
[test ceph]
> rook: add missing owner references to the discover daemon

- build/release/Makefile
To support upgrades, the operator relies on a changing tag between versions so that when a pod spec is updated, k8s will restart the pod due to the new image name. If the image name does not change, the operator cannot control the upgrade deployment. Therefore, we do not support a generic docker tag such as `rook/ceph:release`. For production we expect specific version tags to be specified in the operator such as `rook/ceph:v1.0.0`.
If someone desires to deploy the latest release build, the expectation is that they will sync the latest manifests in the release branch, then deploy. The release branch always has the latest release tags (ie. `rook/ceph:v1.0.0`) in the manifests so the user doesn't have to think about which one to deploy. 
Rook does not have a …
> No longer generate "release" docker tag during release build promotion

- pkg/daemon/ceph/client/osd.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/osd/health.go
- pkg/operator/ceph/cluster/osd/health_test.go
It's not 100% safe since before Nautilus osd safe-to-destroy command
didn't have any json output. So added a version check.
Added a version check before `osd safe-to-destroy` command to check if ceph version is at least Nautilus.
Resolves #3421 
**Checklist:**
> Ceph: Added version check for ceph osd safe-to-destroy command

- cluster/olm/ceph/assemble/metadata-common.yaml
Signed-off-by: Swati Kale <swkale@redhat.com>
As suggested by Jason Riveria and Kaushal Madappa in given PR openshift/ocs-operator#260, added metadata for Operand form here.
Resolves #
Creates Operand form for CephObjectStore
**Checklist:**
[test ceph]
> ceph: Metadata for creation of operand form for CephObjectStore

- Documentation/ceph-osd-mgmt.md
- PendingReleaseNotes.md
- pkg/daemon/ceph/osd/agent.go
- pkg/daemon/ceph/osd/agent_test.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/status.go
Removing an OSD unintentionally can result in data loss, which is to be prevented at all costs. Rook's functionality to remove OSDs automatically when a node was removed from the cluster CR has led on several occasions to users having OSDs unintentionally removed from their cluster.
If the admin decides they really need to remove OSDs they should do it as a one-time action that they intentionally run rather than the operator attempting to manage the deletion with desired state. The risk of misinterpreting the desired state, even with a typo, is too great. Now a help topic is provided for manual steps to remove OSDs when absolutely necessary.
Resolves #1827 
**Checklist:**
> Document OSD removal and stop removing OSDs automatically

- pkg/daemon/discover/discover.go
- pkg/operator/discover/discover.go
- pkg/operator/k8sutil/resources.go
An owner reference cannot be set with `BlockOwnerDeletion: true` if the operator does not have privs to add a finalizer to the parent. The discover resources don't need to block deletion based on the parent so we remove that property from the owner reference.
This issue was causing the following error when running on OpenShift:
```
2019-12-13 06:29:56.309823 I | cephcmd: starting operator
failed to run operator
: error starting device discovery daemonset: Error starting discover daemonset: failed to create rook-discover daemon set. daemonsets.apps "rook-discover" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```
**Checklist:**
[test ceph]
> Set discover ownerrefs without blocking parent deletion

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- pkg/apis/rook.io/v1alpha2/types.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
gp2 devices present themselves as SSDs,
but have much more variable performance.
Ceph attempts to adjust some settings based on the drive type,
HDD/SSD
In this case client I/O can be impacted too much by assuming gp2 devices are like other SSDs
(an example is https://bugzilla.redhat.com/show_bug.cgi?id=1765923#c6)
In order to prevent this, rook can set the following for OSDs on gp2 devices:
```
osd_recovery_sleep = 0.1
osd_snap_trim_sleep = 2
osd_delete_sleep = 2
```
Closes: https://github.com/rook/rook/issues/4298 and https://bugzilla.redhat.com/show_bug.cgi?id=1771047
Resolves https://github.com/rook/rook/issues/4298
**Checklist:**
[test ceph]
> ceph: add CR flag to tune slow device class for OSD on PVC in the Cloud

- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.1-apply.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.1-crds.yaml
- tests/framework/installer/ceph_manifests.go
Several updates to the upgrade guide:
- Removed some obsolete instructions from the 1.1 upgrade
- With the addition of the CephClient CRD, the CRD needs to be created before the upgrade or else the operator log will be filled with errors until it is created. 
- The CSI driver had an error when registering after the upgrade due to an RBAC change.
**Checklist:**
[skip ci]
> Clarifications to v1.2 upgrade guide

- Documentation/ceph-upgrade.md
- Documentation/helm-operator.md
- Documentation/k8s-pre-reqs.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
In ceph-csi v1.2.2 we have added a flag `forcecephkernelclient` to force use Ceph Kernel clients on kernel < 4.17 which support quotas for Cephfs
Resolves #4055
**Checklist:**
[test ceph]
> CSI: Add ENV variable to use ceph kernel client

- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/nfs/spec.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/k8sutil/pod.go
- pkg/operator/k8sutil/pod_test.go
Reduce from 5 minutes to less than 50 seconds the time needed to restart a mgr,mon, and toolbox pod that was running in a k8 "NotReady" Node.
Resolves #4342
**Details:**
Kubernetes automatically adds a toleration for node.kubernetes.io/not-ready with tolerationSeconds=300 in each pod if this toleration is not set explicetelly.
I have added it to the pods where the recovery from a situation where we have a "notReady" node can be improved. (mgr, mon, toolbox)
I have done several tests and the time needed to have the new pods running is typically less than 50 seconds:
**Example:** ( using the change included in this PR)
Lab: A k8 cluster with master and three workers, in "ku-worker-01" we have a mgr-a, mon-b …
> Ceph: Toleration for <NotReady> nodes set to 5 seconds

- Documentation/ceph-block.md
- Documentation/ceph-filesystem.md
- Documentation/ceph-upgrade.md
- Documentation/helm-operator.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
CSI nodeplugins, specifically when using cephfs FUSE or rbd-nbd as the mounters, when upgraded, will cause existing mounts to become stale/not-rechable (usually connection timeout errors).
This is due to losing the mount processes running within the CSI nodeplugin pods.
This PR adds updated the Daemonset update strategy based on the ENV variable to take care of the above issue with some manual steps
Moreinfo: https://github.com/ceph/ceph-csi/issues/703
Resolves https://github.com/rook/rook/issues/4248
**Checklist:**
[test ceph]
> CSI: cephfs and rbd daemonset upgrade strategy

- pkg/daemon/ceph/client/mgr.go
- pkg/daemon/ceph/client/mgr_test.go
Enabling pg_autoscalar module fails most probably becasue `ceph mgr module enable <>` is happening very quickly after ceph mgr starts.
This PR adds a retry (5 times) with a sleep interval of 5 seconds (for each interval) to handle failure while enabling mgr modules.
- Add a retry (5 times) when trying to enable mgr modules. 
- Add a wait for 5 seconds for reach retry iteration. 
Resolves #4497
**Checklist:**
[test ceph]
> ceph: add retry while enabling mgr modules

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/cluster_test.go
- pkg/operator/ceph/cluster/controller.go
The isUpgrade flag was being set every time the operator was started. This caused the upgrade checks to be run every time the operator restarted. Thus, if any mons were down, you likely would get stuck on the upgrade checks since another mon could not be stopped. We need to rely on the upgrade being detected either by a different image name from the cluster CR
update, or from different versions of the daemons running in case the operator was restarted in the middle of an upgrade.
This was a side effect of detecting the upgrades more aggressively in #4403. Besides this change, the behavior was also improved by #4373 which added the detection of the build version of Ceph.
(Not the primary issue that was fixed, but this is also a side effect to treat every …
> Only perform upgrade checks when the image changes

- Documentation/ceph-filesystem.md
- Documentation/ceph-teardown.md
This corrects the used StorageClass name in the docs and example
snippets shown in the docs.
Resolves #
**Checklist:**
[skip ci]
> docs: fix storageclass name used

- Documentation/ceph-advanced-configuration.md
Added table of contents to the Ceph advanced configuration page to make
it easier to find the right section till the theme / layout of the
homepage can autogenerate a toc if enabled.
/cc @travisn 
**Checklist:**
[skip ci]
> docs: added toc to Ceph advanced configuration page

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
The OSDs on PVCs were changing location in the CRUSH hierarchy after an operator restart due to the location property not being re-discovered on the OSD daemon. Since OSDs on PVCs do not run the prepare pod again to discover this property, the operator must read it off the existing osd deployment. The operator was reading other properties, but now will read the location as well.
Resolves #4543 
**Checklist:**
[test ceph]
> Rehydrate the osd CRUSH location for PVCs

- Documentation/ceph-toolbox.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
Update the tags in the manifests to use the v1.2.0 release
[skip ci]
> release: update manifest tags to v1.2.0 GA release

- cluster/examples/kubernetes/ceph/upgrade-from-v0.9-create.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v0.9-delete.yaml
According to upgrade manual https://rook.io/docs/rook/v1.0/ceph-upgrade.html, you need to delete and create some of the RBAC things, because of changes within it. But there was missed needed some parts to delete and create.
Because of this you can get such messages in rook-ceph-operator:
```
2019-12-17 09:46:00.208988 I | cephcmd: starting operator
2019-12-17 09:46:00.284655 I | op-agent: getting flexvolume dir path from FLEXVOLUME_DIR_PATH env var
2019-12-17 09:46:00.285462 I | op-agent: discovered flexvolume dir path from source env var. value: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
2019-12-17 09:46:00.285552 I | op-agent: no agent mount security mode given, defaulting to 'Any' mode
`failed to run operator. Error starting agent daemonset: error starting agent daemonset: …
```
> ceph: fixed RBAC delete\create before upgrade

- pkg/operator/ceph/object/bucket/provisioner.go
Solves issue where provisioner would not handle other ports
Signed-off-by: Brian Sperduto <brian.sperduto@gmail.com>
Added handling so Aws endpoint URI includes port if not 80
Resolves #4049 
**Checklist:**
> ceph: fix object bucket provisioner when rgw not on port 80

- pkg/operator/ceph/cluster/osd/spec.go
"ceph-volume activate" on encrypted osds needs a ceph.conf as well as
connectivity to the mons. This commit adds that to that "activate-osd"
init container.
Closes: https://github.com/rook/rook/issues/4558
Resolves https://github.com/rook/rook/issues/4558
**Checklist:**
[test ceph]
> ceph: add missing vol mount for encrypted osds

- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
The ROOK_CEPH_MON_HOST env var was missing from the pod env so the
CEPH_ARGS won't be populated correctly.
Closes: https://github.com/rook/rook/issues/4558
Resolves https://github.com/rook/rook/issues/4558
**Checklist:**
[test ceph]
> ceph: osd add missing ROOK_CEPH_MON_HOST env

- pkg/operator/edgefs/cluster/controller.go
If obj is not successfully cast into an e dgefsv1.Cluster, ok will be false, resulting in the .Update(cluster) operation not running, and the declared err variable retaining its default nil value. Subsequently, a check against err is performed, which will evaluate to false, resulting in logging the finalizer as removed when it in fact was not.
**Short Term Fix**
Resolves #4577
**Checklist:**
> edgeFs: Fix logic of error handling in the finalizer method

- pkg/util/sys/parse.go
Fix security issues identified by TrailOfBits:
Logging of sensitive information in debug mode
In this case, instead of removing the log lines I have preferred to leave them
but without printing sensitive information.
I think it could be useful when debug to know if the function has been called
and if it has found any matching line.
Resolves #4568 
**Checklist:**
> ceph: Do not log sensitive information in debug mode

- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/dashboard_test.go
Replaced `math/rand` with more secure `crypto/rand` which will generate CSPRNG.
Changed the length of dashboard password from 10 to 20 and included more special characters that can strengthen password.
Passwords before this change: QoMmqLkaOf
Passwords after this change: L{QZ@_c'Rl7$uvW:UHU1
Resolves #4571 
**Checklist:**
> ceph: Generating a strong ceph dashboard password

- pkg/operator/ceph/cluster/controller.go
Fix security issues identified by TrailOfBits:
If we obtain an error trying to get a Node object is better not
continue executing this function.
Resolves #4567 
**Checklist:**
[test ceph]
> ceph: Avoid invalid execution state

- Gopkg.lock
- pkg/daemon/ceph/agent/cluster/controller.go
- pkg/daemon/ceph/agent/flexvolume/attachment/resource.go
- pkg/operator/ceph/client/controller.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/crash/crash.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/operator.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/cockroachdb/controller.go
- pkg/operator/cockroachdb/operator.go
- pkg/operator/edgefs/cluster/controller.go
- pkg/operator/edgefs/iscsi/controller.go
- pkg/operator/edgefs/isgw/controller.go
- pkg/operator/edgefs/nfs/controller.go
- pkg/operator/edgefs/operator.go
- pkg/operator/edgefs/s3/controller.go
- pkg/operator/edgefs/s3x/controller.go
- pkg/operator/edgefs/swift/controller.go
- pkg/operator/k8sutil/customresource.go
- pkg/operator/minio/controller.go
- pkg/operator/nfs/controller.go
- pkg/operator/yugabytedb/controller.go
- pkg/operator/yugabytedb/operator.go
The operator kit had more utility originally when the operator was creating and managing the TPRs and CRDs directly. Since the CRDs are now created from a manifest and no longer by the operators, the utility of operator kit is limited to the controller watcher. Since we are moving to the controller runtime, this PR first removes the dependency to make the transition smoother. Now there is only a simple WatchCR method that will need to be replaced as we make that transition.
Related to #1981 
**Checklist:**
> Remove operator kit dependency

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/osd/status_test.go
- pkg/operator/ceph/cluster/rbd/mirror.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/nfs/nfs.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/k8sutil/deployment.go
- pkg/operator/k8sutil/test/deployment.go
- pkg/util/retry.go
A new CRD option `continueUpgradeAfterChecksEvenIfNotClean` is added.
When upgrading, Rook goes OSD by OSD and then waits for PGs to be clean
before proceeding to the next OSD. Currently, Rook waits for 5 hours but
there might be circumstances where PGs need more time to settle.
Thus setting `continueUpgradeAfterChecksEvenIfNotClean` to true will
pursue the upgrade process, even if PGs are not 100% active+clean.
**Checklist:**
[test ceph]
> ceph: add option to continue on unclean PGs

- pkg/operator/edgefs/cluster/configmap.go
This commit fixes the variable shadowing in configMap which leads to a potential misconfiguration.
Resolves #4563 
**Checklist:**
> edgeFS: Took care of the Variable shadowing in ConfigMap

- pkg/operator/k8sutil/node.go
Add support for the k8s 1.17 official zone/region failure domain labels.
Our earlier guess that the official labels would be
<failure-domain.kubernetes.io> was wrong; the official is now
<topology.kubernetes.io>.
Added to milestone 1.3 when we will eventually be supporting 1.17.
Resolves #
**Checklist:**
> core: k8s 1.17 zone/region failure domain labels

- Documentation/k8s-pre-reqs.md
- Jenkinsfile
- PendingReleaseNotes.md
- tests/integration/ceph_base_deploy_test.go
Since the release of K8s 1.17 this week Rook needs to run the integration tests on 1.17. Following the same pattern as traditional tests, we run the tests on the five most recent releases, thus removing 1.12 from the test matrix.
Resolves #4488 
**Checklist:**
[test full]
> Run integration tests on K8s 1.17

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
currently, we are making use of host path directory to store the provisioner socket, as this
the socket is not needed by anyone else other than containers inside the provisioner pod using the empty directory to store this socket is the best option.
On systems with SELinux enabled, non-privileged containers can't access data of privileged containers. Since the socket is exposed by privileged containers, all sidecars must be privileged too. This is needed only for containers running in daemonset as we are using bidirectional mounts in daemonset
Resolves #
**Checklist:**
[test ceph]
> CSI: Use EmptyDir to store provisioner socker and run all containers as privileged in daemonset pod

- build/makelib/golang.mk
Current Rook code uses go dep 0.5.0 and separates handling
for Arm and x86. It's because there's no dep 0.5.0 binary for 
arm64.Dep has updated to 0.5.4 and supports arm64. Rook
code can be simplified by upgrading dep to fix gaps of Arm
and x86.
Resolves #
Signed-off-by: Haichao Li <haichao.li@arm.com>
**Checklist:**
> Dep: Update golang dep to support Arm64

- design/ceph/ceph-config-updates.md
- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
- pkg/daemon/ceph/config/config.go
As agreed in https://github.com/rook/rook/issues/2543, Rook must not set
min_size for a pool and should let Ceph handle that calculation.
**Checklist:**
[test ceph]
> ceph: remove last bits of osd min_size

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
currently, we are running plugin-container as privileged in the provisioner pod for both cephfs and rbd.
we are also running snapshotter container as privileged in the provisioner pod for rbd.
as we are executing the ceph and rbd commands in provisioner pod we don't need to be privileged, This PR removed the privileged capability from the templates.
Resolves #
**Checklist:**
[test ceph]
> CSI: run containers as non-privileged in provisioner pod

- cmd/rook/ceph/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/k8sutil/node.go
For non-portable OSDs on PVCs (e.g. local volumes), the host name of an OSD in the CRUSH map should actually be the host name. It was incorrectly being set to the PVC name, which should only be used for portable OSDs. Now the non-portable OSDs based on PVCs will correctly have the host name set to the node name.
**Checklist:**
> Set hostname properly in the CRUSH map for non-portable OSDs on PVCs

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.1-crds.yaml
- tests/framework/installer/ceph_manifests.go
Kubernetes Service fail to be created when specified rgw ports are invalid.
Add range validation to port in following CRD fields
* `CephObjectStore.Gateway.Port` / `CephObjectStore.Gateway.SecurePort` 1~65535
* `CephCluster.Spec.Dashboard.Port` 0~65535 when `CephCluster.Spec.Dashboard.Enabled`
Resolves #4574
**Checklist:**
[test ceph]
> ceph: Add range validation to port in CRDs 

- pkg/operator/yugabytedb/controller.go
- pkg/operator/yugabytedb/controller_test.go
- pkg/operator/yugabytedb/create_controller.go
- pkg/operator/yugabytedb/update_controller.go
This PR takes care of the following things:
1) Fixes the issue of the replication factor not being honored in Yugabyte due to the incorrect flag being set.
2) Hardens the discovery of master servers by passing in the FQDNs as the addresses rather than just the headless service.
3) Bumps the version of Yugabyte to 2.0.10.0-b4.
Resolves #4625 
**Checklist:**
[test yugabytedb]
> yugabytedb: fixed replication factor flag and the master addresses.

- tests/framework/installer/environment.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_base_deploy_test.go
When the tests run in a PR, they can only run against a single version of K8s by default. If more than five k8s versions are supported in the CI, we will need to run some of the suites on multiple versions. The versions are comma-separated in the list.
Running integration tests locally on k8s 1.13 was causing an error with parsing the command line flags. The tests can't call flags.Parse() from an init() method.
**Checklist:**
> Allow integration tests in minimal config to run on multiple versions

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Updated the query to include correct ceph_daemon & hostname and referenced it with the original query.
Also updated the alert message.
**Old alert description**: Ceph Monitor "rook-ceph-mgr": instance 10.131.0.16:9283 has seen 3.86 leader changes per minute recently.
**New alert description**: Ceph Monitor mon.c on host ip-10-0-157-75.ec2.internal has seen 1.42 leader changes per minute recently.
Resolves #4665 
Reference PR: https://github.com/ceph/ceph-mixins/pull/80
**Checklist:**
[skip ci]
> ceph: Fixed CephMonHighNumberOfLeaderChanges alert

- cmd/rook/ceph/osd.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
Added a check for `--crush-location`, if `--crush-location` is not present,
the node topology is not applied and the operator will need to determine
the value based on the node labels instead of skipping this setting.
Resolves #4616 
**Checklist:**
[test ceph]
> osd: Added check for `--crush-location`

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-quickstart.md
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- images/ceph/Makefile
- pkg/operator/ceph/cluster/controller_test.go
- tests/framework/installer/ceph_installer.go
- tests/longhaul/base_block_test.go
14.2.6 is released, let's use it!
Builds running here:
* https://2.jenkins.ceph.com/job/ceph-container-build-ceph-base-push-imgs-arm64/233/
* https://2.jenkins.ceph.com/job/ceph-container-build-ceph-base-push-imgs/250/ 
Resolves https://github.com/rook/rook/issues/4619
**Checklist:**
> ceph: bump to 14.2.6

- tests/framework/installer/ceph_manifests_v1.0.go
- tests/framework/installer/ceph_manifests_v1.1.go
- tests/framework/installer/ceph_manifests_v1.2.go
- tests/framework/installer/ceph_manifests_v1.3.go
- tests/framework/installer/installer.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_upgrade_test.go
Modify Ceph upgrade test to upgrade from v1.0 -> v1.1 -> v1.2 -> v1.3 (master) to ensure legacy OSD functionality.
Resolves #
**Checklist:**
[test full] - test upgrade on all k8s versions
> upgrade v1.0->v1.1->v1.2->v1.3 in upgrade test

- Documentation/ceph-quickstart.md
- Documentation/k8s-pre-reqs.md
- Jenkinsfile
- tests/integration/ceph_base_deploy_test.go
With production environments remaining up for much longer than the lifetime of upstream k8s releases due to the downstream releases of k8s, let's keep running more versions of k8s in the integration tests to give some assurance that Rook will continue to run in those older K8s versions. If an older release of K8s hits an issue with a Rook change we will evaluate whether we can continue to support that version. But there is no technical reason that Rook wouldn't currently run at least back to 1.11.
Resolves #4548 
**Checklist:**
> Add K8s 1.11 to the integration tests for Rook v1.2 

- Documentation/ceph-cluster-crd.md
- pkg/clusterd/disk.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/util/sys/device.go
- pkg/util/sys/device_test.go
We now support partitions via 2 ways:
* if `useAllDevice: true`: partitions will be taken into account and
presented as OSD candidate
* if specified in the cluster CR: it'll picked up as well
Resolves: https://github.com/rook/rook/issues/2215
**Checklist:**
[test ceph]
> ceph: add partition support

- Jenkinsfile
Checking that the flex driver tests succeed on 1.17.1 as well to see if there is an issue related to #4695.
**Checklist:**
[test ceph]
[test full]
> Run tests on k8s 1.17.1

- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
Now, we purely rely on what the user puts in the CR and apply it.
Prior to this commit we were putting 0 if not declared, this was not the
intentional.
Closes: https://github.com/rook/rook/issues/4713
Resolves https://github.com/rook/rook/issues/4713
**Checklist:**
[test ceph]
> ceph: fix resources for prepare job

- cmd/rook/ceph/osd_test.go
- pkg/operator/ceph/cluster/osd/osd.go
Currently each time the ceph operator restart, osds also restart.
This is due to a change in the crush-location args with location not ordered
At each restart the location order can change and lead to that kind of change in the osd deployment
```
104c105
<                             "--crush-location=root=default host=hostname datacenter=PAR pod=2 rack=2",
---
>                             "--crush-location=root=default host=hostname pod=2 rack=2 datacenter=PAR",
```
Sorting the topology to ensure stability of this command arg
Resolves #
**Checklist:**
> ceph: ensure crush-location osd command args is always the same to avoid useless osds restart

- pkg/operator/ceph/cluster/controller.go
If an image is specified in the external cluster CR, the
'rook-ceph-config' config map will be created and then child CRs like
rgw/mds/nfs can be created.
Also, calling config.GetStore() was a mistake since it's calling by the
health check if new mons are being added to clusterInfo.
Closes: https://github.com/rook/rook/issues/4686
Resolves https://github.com/rook/rook/issues/4686
**Checklist:**
[skip ci]
> ceph: fix external cluster config override cm creation

- pkg/daemon/ceph/osd/daemon.go
Signed-off-by: Dustin Guerrero <dguerrero@twilio.com>
Changes device filter log messages to only print when a match actually occurs.
Resolves #4711 
**Checklist:**
> osd: fix misleading log messages when matching device filters

- pkg/operator/ceph/file/mds/config.go
- pkg/operator/ceph/version/version.go
- pkg/operator/ceph/version/version_test.go
We now force the mds daemon to join the fs that was created by Rook.
This can always be changed by using the ceph config store.
Resolves https://github.com/rook/rook/issues/4707
**Checklist:**
[test ceph]
> ceph: add mds_join_fs option when running mds daemon

- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/crash/reconcile.go
- pkg/operator/ceph/spec/label.go
- pkg/operator/ceph/version/version.go
In order for deployments managed outside the immediate scope of
the ClusterController to accurately detect the Ceph version of
their images, the ClusterController must store the detected
version. This change records the Ceph version as part of the
cluster status and modifies the crashcollector deployment to
consume this field to record its own Ceph version. This replaces
an earlier solution to this problem in which the Ceph version
for a given image to version mapping was stored in a global
in-memory map by the operator.
Resolves: rook#4357
**Checklist:**
> ceph: add ceph version to cluster status

- Documentation/ceph-nfs-crd.md
- fixup RADOS pool name to match what is used by the CRD
- add missing RADOS namespace to the Sample description
- move/merge description of the RADOS pool/namespace config into the
sample text instead of inline comments within the CRD yaml
- add inline code block for `spec.server.active` field
Signed-off-by: Michael Fritch <mfritch@suse.com>
Resolves #
**Checklist:**
[skip ci]
> docs: clean-up Ceph NFS Gateway CRD

- Documentation/ceph-configuration.md
Ceph recently changed its default PG count in
https://github.com/ceph/ceph/pull/32788, it also changed from 8 to 16
then 16 to 32. So let's remove the 8 PGs mention which is incorrect.
Resolves #
**Checklist:**
[skip ci]
> doc: update doc for PG count

- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/mon/spec_test.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
- pkg/operator/ceph/spec/spec.go
- pkg/operator/k8sutil/pod.go
- pkg/operator/k8sutil/pod_test.go
Refacto setPodPlacement for ceph mon and gateways to use a common one
Resolves #4473
**Checklist:**
> ceph: create a generic setPodPlacement used by mon and gateways

- Jenkinsfile
The CI will now use the current latest K8S releases.
v1.15: v1.15.9
v1.16: v1.16.6
v1.17: v1.17.2
**Checklist:**
> test: update k8s versions for CI

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.1-crds.yaml
- pkg/operator/ceph/object/rgw.go
- tests/framework/installer/ceph_manifests.go
Recent integration tests have failed due to a null value in the
securePort field in their CephObjectStore manifests. This patch
adds a standard 443 value for these fields.
Fixes: #4693
**Checklist:**
[test ceph]
[test full]
> ceph: add securePort values for objectstore integration tests

- cluster/examples/kubernetes/ceph/filesystem-ec.yaml
- cluster/examples/kubernetes/ceph/filesystem.yaml
- pkg/operator/ceph/file/mds/mds.go
With this modification is guaranteed that at least 1 MDS pod is going to be
placed in each of the available zones in the k8s cluster.
This would be improved in the future using: "Pod Topology Spread Constraints"
<Pod Topology Spread Constraints> (still in alpha state since kubernetes V.1.16)
This modification obtain the number of zones in the k8s cluster and appends an
<antiaffinity> term using the topologyKey
<topology.kubernetes.io/zone> in the same number of MDS pods.
In the case that will be more MDS pods than zones, the <antiaffinity> term won't
be added in these extra pods.
Important Note:
The antiaffiniy term only will work with nodes labeled using the NEW label:
<topology.kubernetes.io/zone> present in k8s V.1.17 clusters.
For previous versions of …
> Ceph: MDS pod placement adheres to fault domain topology

- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_upgrade_test.go
The integration tests only have a single node so the upgrade checks do not provide any real safety for the cluster during the upgrade. We will be able to improve the reliability and speed of the tests by disabling these checks. In particular, the filesystem update spends a lot of time waiting for the mds daemons.
**Checklist:**
[test ceph]
[test full]
> Skip the upgrade checks in integration tests

- pkg/operator/ceph/cluster/crash/reconcile.go
As CephVersion is pointer added a nil check for CephVersion in status to avoid panic.
Resolves #4762
**Checklist:**
[test ceph]
> ceph: Add nil check for ceph version

- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/node_test.go
- pkg/operator/ceph/cluster/mon/service.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/mon/spec_test.go
~With this modification the mon failover process is not executed if there is
no available nodes where to schedule the mon pod.
This avoid to have mon canary pods in Pending state because no nodes
available.~
If for any cause the operator processing a mon failover is restarted, the
mon canary pods created in order to get the right placement for this
kind of pods can remain in <pending> state forever.
The following labels have been added to the mon canary deployments:
"mon_type" = "canary"
"canary_pvc_name" = <PVC name used for the canary pod>
A separate <removeCanaryDeployments> has been implemented for
removing the dependence of the variable <canaryCleanup>.
This function uses the <canary> labels to obtain the <real>
and <existing> list of mon canary …
> Ceph: Assure mon canary pods deletion

- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.0.go
- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_block_test.go
- tests/integration/ceph_helm_test.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_smoke_test.go
- tests/integration/ceph_upgrade_test.go
- tests/longhaul/base_block_test.go
Add coverage in the CI for the external cluster feature.
Closes: https://github.com/rook/rook/issues/3691
Resolves https://github.com/rook/rook/issues/3691
**Checklist:**
[test ceph]
[test full]
> ci: add external cluster functional test

- cluster/examples/kubernetes/ceph/common.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/config/conditions.go
- tests/framework/installer/ceph_installer.go
Did the changes which required to implement conditions on the rook ceph cluster
Conditions will eliminate the current status.State and incorporates a type which
provides much more description to the current status of the cluster.
As per the discussions in #4066 
Resolves #
**Checklist:**
[test ceph]
> ceph: Implementing Conditions on rook-ceph

- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/daemon/ceph/osd/volume.go
If we detect a partition we should not use it if the ceph version is not
at least 14.2.8 since it has the necessary changes to support partitions
with ceph-volume.
Resolves #
**Checklist:**
[test ceph]
> ceph: skip partitions depending on the ceph version

- Documentation/ceph-filesystem.md
- cluster/examples/kubernetes/ceph/csi/cephfs/kube-registry.yaml
- cluster/examples/kubernetes/ceph/csi/cephfs/pvc.yaml
- cluster/examples/kubernetes/ceph/csi/cephfs/storageclass.yaml
This fixes the StorageClass name example and doc to be `rook-cephfs`
instead of just `csi-cephfs`.
Closes #4130.
**Checklist:**
[skip ci]
> doc: fix CephFS CSI StorageClass name

- pkg/operator/ceph/csi/spec.go
The CSI driver was disappearing in some clusters after certain events such as restarting the operator or master nodes being restarted. This is due to an incorrect owner reference on the csi driver back to the configmap. The owner reference must specify apps/v1 instead of v1 for the APIVersion of the configmap. This issue is only hit when the k8s garbage collector rebuilds its cache, which would happen at indeterminate times from Rook's perspective. This GC behavior was introduced by #4354.
Resolves #4590 
**Checklist:**
[test ceph]
> ceph: fix garbage collection for csi driver

- pkg/daemon/ceph/client/mgr.go
- pkg/daemon/ceph/client/mgr_test.go
- pkg/operator/ceph/cluster/mgr/mgr.go
The balancer module is a special module that needs particular actions to
be enabled.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1790500
Resolves #
**Checklist:**
[test ceph]
> ceph: ability to enable the balancer module

- pkg/daemon/ceph/osd/agent_test.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
If we detect a partition we should not use it if the ceph version is not
at least 14.2.8 since it has the necessary changes to support partitions
with ceph-volume.
Inspiration of https://github.com/rook/rook/pull/4783.
Resolves #
**Checklist:**
// integration tests previously run successfully
[skip ci]
> backport: ceph: skip partitions depending on the ceph version

- pkg/apis/ceph.rook.io/v1/annotations.go
- pkg/apis/ceph.rook.io/v1/annotations_test.go
- pkg/apis/ceph.rook.io/v1/keys.go
When the annotations are generated for a ceph daemon, the `all` annotations are merged with the component annotations. If there are no `all` annotations, the component annotation calculation was crashing. Now we check for the case where the `all` annotations are not defined.
Resolves #4351
**Checklist:**
[test ceph]
> Allow for empty "all" annotations

- Documentation/cassandra-cluster-crd.md
- Documentation/cassandra.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- design/cassandra/cluster-creation.md
- images/cassandra/Dockerfile
- pkg/apis/cassandra.rook.io/v1alpha1/types.go
- pkg/apis/cassandra.rook.io/v1alpha1/zz_generated.deepcopy.go
- pkg/operator/cassandra/controller/util/resource.go
- pkg/operator/cassandra/sidecar/config.go
Export prometheus metrics for cassandra in sidecar container
Signed-off-by: Maksim Nabokikh <maksim.nabokikh@flant.com>
Add jmx exporter with standard configuration to sidecar container.
Test steps:
* Start minikube with `tests/scripts/minikube.sh up`
* Deploy cassandra from `cluster/examples/kubernetes/cassandra`
* Get the metrics with curl
This dashboard seems ok https://grafana.com/dashboards/5408 for monitoring
Resolves #2530
**Checklist:**
> cassandra: JMX prometheus exporter

- pkg/daemon/ceph/osd/daemon.go
This will likely happen when re-running an orchestration and
bootstrapping a new cluster with unclean drives.
The prepare pod won't prepare nor list existing disks, thus the code
will later fail on reading disks properties.
Closes: https://github.com/rook/rook/issues/4810
Resolves https://github.com/rook/rook/issues/4810
**Checklist:**
[test ceph]
> ceph: fail if no devices found

- pkg/operator/ceph/disruption/clusterdisruption/pools.go
- pkg/operator/ceph/disruption/nodedrain/reconcile.go
[test ceph]
- Improve detection of drain-canaries 
- Log significant nodedrain scheduling events
Resolves #
**Checklist:**
> Ceph: Improve detection of drain-canaries and info-log significant nodedrain scheduling events

- Documentation/ceph-pool-crd.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/filesystem.yaml
- cluster/examples/kubernetes/ceph/pool.yaml
- pkg/apis/ceph.rook.io/v1/blockpool.go
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/daemon/ceph/client/erasure-code-profile.go
- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/model/pool.go
- tests/framework/installer/ceph_manifests.go
target_size_ratio is used the tell the Ceph cluster the excepted
occupancy of a pool in the cluster.
Resolves #
**Checklist:**
[test ceph]
> ceph: ability to set target_size_ratio

- pkg/operator/ceph/cluster/osd/status.go
- pkg/operator/ceph/disruption/machinelabel/add.go
Fix security issues identified by TrailOfBits
**Modifications in `osd/status.go:`**
I opted by remove the offending variables because "c.checkNodesCompleted" provides this variables always, so no need to initialize them.
<statuses> var was not used, so i have replaced it by the blank identifier.
**Modifications in `machinelabel/add.go:`**
I have followed the same criteria used in other disruption packages, and return the error if it is produced when we try to "_watch_" machines.
Resolves #4565 
**Checklist:**
[test ceph]
[test full]
> ceph: Remove ineffectual assignments

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
For the patch release, set the manifest versions to v1.2.4.
**Checklist:**
[skip ci]
> Set manifest versions to v1.2.4

- pkg/daemon/ceph/client/upgrade.go
- pkg/daemon/ceph/client/upgrade_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/version/version.go
Once osds will run on octopus we will activate the necessary features for these OSDs.
Resolves #
**Checklist:**
[test ceph]
> ceph: allow osd full upgrade to octopus

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.1-crds.yaml
- tests/framework/installer/ceph_manifests.go
The replication and erasure code settings are mutually exclusive so must both be treated as optional by the schema validation. The minimum must be set to 0 to treat them as optional.
Resolves #4750 
**Checklist:**
[test ceph]
> Set min size to 0 on pool replication

- cluster/charts/rook-ceph/templates/clusterrole.yaml
Updating clusterrole cephfs-external-provisioner-runner-rules to allow patching for volume attachments on storage.k8s.io apiGroup
Resolves an issue when utilizing cephfs. The error occurs in csi-attacher when a pod attempts to utilize a rook-cephfs storage class PVC. 
`is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-cephfs-provisioner-sa" cannot patch resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope`
[test ceph]
> Update Chart for Patch to Volume Attachment in Storage apiGroup

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- pkg/apis/rook.io/v1alpha2/types.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/daemon/ceph/osd/device.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/util/sys/device.go
We now support the addition of the PVC that acts as a metadata device
for a given OSD.
For this, you need to create a new `volumeClaimTemplates`, its name must
be "metadata" otherwise, Rook won't pick it up.
A template will look like this:
```
volumeClaimTemplates:
- metadata:
name: data
spec:
resources:
requests:
storage: 10Gi
storageClassName: gp2
volumeMode: Block
accessModes:
- ReadWriteOnce
- metadata:
name: metadata
spec:
resources:
requests:
storage: 6Gi
storageClassName: gp2
volumeMode: Block
accessModes:
- ReadWriteOnce
```
Closes: https://github.com/rook/rook/issues/3852
Resolves https://github.com/rook/rook/issues/3852
**Checklist:**
Things I'd like …
> ceph: add support for metadata PVC for OSD on PVC

- pkg/daemon/ceph/client/mgr.go
When running old client version, we must force the compatibility
features so that the orchestration does not fail in a loop.
Closes: https://github.com/rook/rook/issues/4842
Resolves https://github.com/rook/rook/issues/4842
**Checklist:**
[test ceph]
> ceph: force enabling balancer module with older clients

- pkg/operator/k8sutil/prometheus.go
- pkg/operator/k8sutil/prometheus_test.go
- pkg/operator/k8sutil/service_test.go
This change sets the ResourceVersion on the PrometheusRule object before
it is updated in Kubernetes.
This change fixes the following error
```
is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```
which can occur during update when no ResourceVersion is set.
Resolves #4528
Resolves #4528
**Checklist:**
> k8sutil: set ResourceVersion for PrometheusRule

- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/util.go
- pkg/operator/k8sutil/configmap.go
- pkg/operator/k8sutil/configmap_test.go
"rook-operator-config" can be used to override ENV VAR
initialized during operator deployment.
This commit makes use of this ConfigMap to determine NodeAffinity
and Tolerations for ceph-csi drivers.
Resolves https://github.com/rook/rook/issues/3239
**Checklist:**
[test ceph]
[test full]
> Ceph: adds "rook-operator-config" configmap

- tests/scripts/localPathPV.sh
This commit updates localPV.sh to clean existing localPVs before applying the new one.
Signed-off-by: Ashish Ranjan <ashishranjan738@gmail.com>
Resolves #
**Checklist:**
[test ceph]
> Update localPV.sh to clean localPVs before applying

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/csi/cluster_config.go
The configmap for csi wasn't created so csi wasn't working.
Closes: https://github.com/rook/rook/issues/4816
Resolves https://github.com/rook/rook/issues/4816
**Checklist:**
[test ceph]
> ceph: populate CSI configmap for external cluster

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/operator/ceph/cluster/osd/spec.go
Rook-Ceph now supports specify device by their fullpath instead of links
created by the kernel like /dev/sdb.
Closes: https://github.com/rook/rook/issues/1228
Co-authored-by: Sean Micklethwaite <sean@wayve.ai>
Resolves https://github.com/rook/rook/issues/1228
**Checklist:**
[test ceph]
> ceph: add support for disk selection by full path

- Documentation/ceph-cluster-crd.md
The `cephVersion` was missing in the PVC based Ceph Cluster example.
Otherwise the Ceph Cluster would fail to be created due to no Ceph
version being specified.
**Checklist:**
[skip ci]
> docs: fix CephCluster PVC based example

- pkg/operator/ceph/cluster/crash/crash.go
- pkg/operator/ceph/cluster/crash/keyring.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/csi/secrets.go
- pkg/operator/ceph/test/podspec.go
- pkg/operator/edgefs/cluster/target/layout.go
This commit fixes the gosec warning
G101: Potential hardcoded credential variable by adding a #nosec tag and relavant comment
Resolves #
**Checklist:**
> rook: Fixing the potential hardcoded credential warnings

- pkg/operator/ceph/cr_manager.go
- pkg/operator/ceph/operator.go
Limit namespace watches when ROOK_CURRENT_NAMESPACE_ONLY is true
Resolves #
**Checklist:**
[test ceph]
> Limit namespace watches when ROOK_CURRENT_NAMESPACE_ONLY is true

- pkg/daemon/ceph/config/info.go
- pkg/operator/edgefs/cluster/utils.go
This commits adds encoders for input and output
of ceph
Closes: https://github.com/rook/rook/issues/4575
Signed-off-by: crombus <pkundra@redhat.com>
Resolves #
**Checklist:**
> ceph: Add encoders for input and output of ceph

- tests/README.md
[skip ci]
- setting config path is necessary between kubeadm.sh and helm.sh
- fix the path of integration test binary
Signed-off-by: Satoru Takeuchi <satoru.takeuchi@gmail.com>
Resolves #
**Checklist:**
> tests: enhance README.md

- cluster/examples/kubernetes/ceph/pool-ec.yaml
- pkg/operator/ceph/pool/controller.go
Creating an EC pool was succeeding, but then the update to the status was failing because of an incorrect check for changing EC parameters. Now we correctly check if EC parameters are changing unexpectedly.
Resolves #4883 
**Checklist:**
[test ceph]
> EC pool creation should have successful status

- tests/framework/utils/k8s_helper.go
The integration tests have failed intermittently due to needing just a little longer to start the file test pod. This increases the wait timeout.
**Checklist:**
[test ceph]
> Increase timeout for file test pod start

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- images/ceph/Makefile
- pkg/operator/ceph/cluster/controller_test.go
The ceph/ceph:v14.2.7 image is released so we can pick these fixes up as the recommended version of ceph.
**Checklist:**
[test ceph]
> Bump ceph version to v14.2.7

- README.md
- SECURITY.md
This PR adds an initial security disclosure policy and defines a security release process for the Rook project.  This is an explicit criterion for CNCF graduation and is timed with the kick-off of the security audit being performed by [Trail of Bits](https://www.trailofbits.com/) this week.
As called out in SECURITY.md, this policy and process is adapted from previous CNCF projects Envoy and CoreDNS.  Credit and appreciation to those projects for their efforts.
Resolves #4296 
**Checklist:**
[skip ci]
> security: disclosure policy and release process

- pkg/daemon/ceph/config/config.go
- pkg/daemon/ceph/config/config_test.go
The Ceph daemons no longer use the ceph.conf for settings generated by the operator. The operator only generates the ceph.conf in order to connect to the mons and configure the cluster. Now we reduce to the minimal required settings.
**Checklist:**
[test ceph]
> Remove obsolete operator settings from ceph.conf

- pkg/operator/ceph/nfs/spec.go
- pkg/operator/ceph/spec/spec.go
Do not use the Rook binary to generate minimal config for Ceph's
NFS-Ganesha pods. Instead, `cat` the minimal file in an init container
using the Ceph container.
Resolves #
**Checklist:**
[test ceph]
> ceph: nfs do not use rook binary

- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- pkg/apis/rook.io/v1alpha2/types.go
- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
When the OSD on PVC is backed by a metadata block PVC, the Ceph CRUSH
device class should be set to something else rather than the rotational
property of the drive.
Closes: https://github.com/rook/rook/issues/4881
Resolves https://github.com/rook/rook/issues/4881
**Checklist:**
[test ceph]
> ceph: set crush device class via annotations on PVC

- Documentation/ceph-pool-crd.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass-test.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
- cluster/examples/kubernetes/ceph/filesystem-test.yaml
- cluster/examples/kubernetes/ceph/filesystem.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- cluster/examples/kubernetes/ceph/pool.yaml
- pkg/apis/ceph.rook.io/v1/blockpool.go
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/daemon/ceph/client/erasure-code-profile.go
- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
- pkg/daemon/ceph/config/config.go
- pkg/daemon/ceph/model/pool.go
- pkg/operator/ceph/file/filesystem_test.go
- pkg/operator/ceph/object/rgw_test.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
- tests/framework/installer/ceph_manifests.go
As of Octopus, Ceph will prevent you from creating a pool with a
replica size of 1. Allowing such pool could lead to data loss, so enable
the new option: allowUnsafeSingleReplica: true if you are **ABSOLUTELY**
certain that is what you want.
Closes: https://github.com/rook/rook/issues/4889
Resolves https://github.com/rook/rook/issues/4889
**Checklist:**
[test ceph]
> ceph: add CRD setting for pool size 1

- design/ceph/orchestrator-osd-add-remove.md
Add a design document to plan how Rook will allow Ceph's Rook
Orchestrator Mgr Module to add and remove OSDs to/from a Rook-Ceph
cluster including changes needed in both the Orchestrator Module and in
Rook.
**Update 30 Jan**
I made extensive edits to the design based on huddle discussions from the past couple days. I am leaving all conversations as unresolved so that they continue to be shown. I think it's important to make sure everyone with concerns is able to see the past discussion for this one.
**Checklist:**
[skip ci]
> design: ceph orchestrator module add/remove OSDs

- CODE-OWNERS
- CONTRIBUTING.md
- GOVERNANCE.md
- OWNERS.md
Updates and clarifications to the Rook governance including:
- Add a steering committee to oversee the project starting with three members: @jbw976 @dyusupov @travisn 
- Rename approvers to maintainers, who have push access to the repo
- Clarify process for adding and removing maintainers
- Move @bassam to emeritus maintainer
- Add reviewers for YugabyteDB
- Remove inactive reviewers
- Other clarifications for maintainer and reviewer responsibilities
Per requirements for current Rook governance, this must be approved by majority of current Rook maintainers before this is merged or the changes take effect.
**Checklist:**
[skip ci]
> Governance updates including a steering committee

- pkg/operator/ceph/cluster/controller.go
This commit will add a phase and also a condition to display a Failed status on the external rook-ceph cluster if its failed to establish a connection.
Resolves #
**Checklist:**
> ceph: Failed Condition to the external rook-ceph cluster

- images/ceph/toolbox.sh
The toolbox was generating a ceph.conf with mons based on the assumption that they all had the prefix rook-ceph. This is no longer true for external clusters. The external clusters may have mons with any variety of names. So we can remove the filter that was added for legacy mons.
**Checklist:**
[test ceph]
> Allow mons from external cluster in toolbox config

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/csi/cluster_config.go
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/operator.go
Prior attempts to delete CSI drivers using owner references to the
Ceph ConfigMap resulted in garbage collection of the driver
resources as described in #4590. This patch manually deletes these
resources by name as a stopgap to provide an appropriate user
experience while the team investigates this issue further.
Resolves: #4824
**Checklist:**
[test ceph]
> ceph: delete CSI drivers with deletion of last cluster

- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_multi_cluster_test.go
Simplify verbose function names and a wrong var name.
None
**Checklist:**
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [o] Comments have been added or updated based on the …
> ceph: simplify verbose function names and a wrong var name

- .github/stale.yml
The bot should not close issues that are related to reliability. Rook's reliability is too critical to allow the bot to close these issues.
This will facilitate opening 17 new issues for moving to the controller runtime, related to #1981, and not risk having the issues closed before they are implemented.
**Checklist:**
[skip ci]
> Keep reliability issues open from the stale bot

- pkg/operator/ceph/csi/spec.go
As a safeguard against the error case described in #4934, this
change sets BlockOwnerDeletion to false on the ownerReference
of all Ceph CSI resources.
**Checklist:**
[test ceph]
> ceph: set BlockOwnerDeletion=false for csi driver ownerReference

- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/config/conditions.go
Most of the OLM UI currently uses status.Phase to show the status of the cluster and in some case it uses status.State to show the information. Having both would be a redundant information but for now we can just use it and slowly deprecate the use of status.state is the most appropriate way to do now.
Resolves #
**Checklist:**
[test ceph]
> ceph: Adding status.state variable and assigned it to status.phase

- pkg/operator/ceph/pool/controller.go
- tests/framework/clients/pool.go
- tests/framework/installer/ceph_installer.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_smoke_test.go
With a finalizer on the pools, the pools were not always being purged
during the integration tests. Now the multicluster suite will ensure
its pool is purged.
Resolves #4954 
**Checklist:**
[test ceph]
[test full]
> Ensure pools are purged during integration tests

- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/config/conditions.go
Added back the status.State to the exact way it was implemented on the ceph cluster. Added the States as a Constant and used that constant to call the status.State.
Follow up of https://github.com/rook/rook/pull/4931
Resolves #
**Checklist:**
[test ceph]
> ceph: Follow up for adding the state variable

- tests/framework/installer/ceph_installer.go
The CI is failing currently in the OSD-on-pv scenario due to a change in v14.2.8. Until that is resolved, we need to unblock the tests by running against v14.2.7.
To track the issue with v14.2.8 see #4960. 
**Checklist:**
[test ceph]
> Nautilus tests run on 14.2.7 instead of latest nautilus release

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
The osd prepare job is now always working with devices so we always need to mount /dev and run privileged. There is no scenario for not mounting /dev since filestore support was removed.
The issue was the /dev was not being mounted in the osd prepare pods when the devices were specified under the `storage.nodes.devices` section.
Resolves: #4967 
**Checklist:**
[test ceph]
> OSD prepare pod should always mount /dev

- pkg/daemon/ceph/osd/daemon.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/status.go
- pkg/operator/ceph/cluster/osd/status_test.go
The OSD prepare pod must always update status on the status configmap in order to alert the operator that the OSD configuration on the node is completed. This fixes an issue where the status was not being reported if no devices were configured.
Also, a simplification to the helper that updates the status... The communication between the operator and OSD prepare job is done through updates to the configmap. If an update fails
to the configmap, we are anyway going to need to check the logs for failure. So let's just log the error and make a best effort to continue the orchestration. If the failure was temporary,
the next update to the status would succeed and likely continue working as expected.
**Checklist:**
[test ceph]
> OSD prepare pod was not signaling completion when zero OSDs configured

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/register_controllers.go
- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/controller/object_operations.go
- pkg/operator/ceph/controller/predictate.go
- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/user.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/object/user/controller_test.go
- pkg/operator/ceph/operator.go
- pkg/operator/ceph/operator_test.go
Now, the CephObjectStoreUser CRD is managed with the controller-runtime.
So the watcher is outside of the main controller reconciliation loop of
CephCluster which brings numerous benefit such as:
* having its own reconciliation loop
* won't block anything from the main CephCluster controller loop
* fast than waiting for CephCluster loop to completion
Related to: https://github.com/rook/rook/issues/1981
Resolves #
**Checklist:**
[test full]
[test ceph]
> ceph: separate controller for CephObjectStoreUser CRD

- tests/framework/installer/ceph_installer.go
- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_multi_cluster_test.go
- The operator logs are necessary for troubleshooting why the pools may still exist at the end of the integration tests.
- Remove dead test code.
**Checklist:**
[test ceph]
[test full]
> Gather operator logs when the test pools are not deleted

- Documentation/ceph-advanced-configuration.md
- Documentation/ceph-cluster-crd.md
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/topology.go
- pkg/operator/ceph/cluster/osd/topology_test.go
- pkg/operator/ceph/disruption/clusterdisruption/location.go
- pkg/operator/ceph/disruption/nodedrain/reconcile.go
- pkg/operator/k8sutil/node.go
- pkg/operator/k8sutil/node_test.go
The OSDs pick up on several topology labels for CRUSH hierarchy. The GA label topology.kubernetes.io was partially implemented, but not picked up by the OSDs. Now the OSDs will pick up both the topology labels from pre-1.17 such as failure-`domain.beta.kubernetes.io/zone` and `topology.kubernetes.io/zone`.
Also removes some dead code in k8sutil/nodes.go.
Resolves #4980 
**Checklist:**
[test ceph]
> Properly lookup the topology.kubernetes.io label for OSD topology

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/csi/util.go
- pkg/operator/ceph/operator.go
- pkg/operator/k8sutil/configmap.go
- pkg/operator/k8sutil/configmap_test.go
- pkg/operator/k8sutil/k8sutil.go
watches the rook-ceph-operator-config ConfigMap and updates Ceph csi driver based on watch events
Resolves #rook-ceph-operator deployment based on watch events
**Checklist:**
[test ceph]
[test full]
> Ceph: adds watch to rook-ceph-operator-config ConfigMap

- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
The OSD needs to talk to the udev socket to get information about a device.
like serial, vendor etc. So that it can populate the output of:
`ceph osd metadata $n` correctly.
Resolves #
**Checklist:**
[test ceph]
> ceph: osd re-add udev bindmount

- Documentation/ceph-advanced-configuration.md
- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- images/ceph/Makefile
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/osd/topology.go
- pkg/operator/ceph/cluster/osd/topology_test.go
- pkg/operator/ceph/disruption/clusterdisruption/location.go
- pkg/operator/ceph/disruption/nodedrain/reconcile.go
- pkg/operator/k8sutil/node.go
- pkg/operator/k8sutil/node_test.go
Backport multiple fixes that had merge conflicts preventing the bot from backporting.
- #5001 Mount /udev so the osds can discover device info
- #4960 Update to Ceph v14.2.8 and fix an issue with OSDs running on PVs on that version
- #4989 Properly look up the topology.kubernetes.io labels
- Log a warning when useAllNodes is true, but `nodes` are defined in the cluster CR.
**Checklist:**
[test full]
[test ceph]
> Backport: Multiple OSD fixes and default to Ceph v14.2.8

- tests/framework/installer/yugabytedb_manifests.go
The integration tests for yugabyte were pointing to an image outside of the rook repo. Since that image changed unexpectedly it broke the rook integration tests. The tests need to use the image built by rook.
**Checklist:**
[test yugabytedb]
> Yugabyte tests should use image built by rook

- pkg/operator/ceph/cluster/crash/crash.go
The crash deployment was missing the 'rook_cluster' label to indicate
which ceph cluster it is part of.
Resolves #
**Checklist:**
[test ceph]
> ceph: add missing 'rook_cluster' label to crash

- pkg/daemon/ceph/config/config.go
- pkg/operator/ceph/config/defaults.go
Left from https://github.com/rook/rook/pull/4895
Also more cleanup on the ceph.conf since we config is in the mon store.
Resolves #
**Checklist:**
[test ceph]
> ceph: allow setting pool size 1 on octopus

- .github/stale.yml
Some issues should not be closed by the stale bot, whether because an
issue is taking a long time to design, implement, or if we need an
owner for the issue, but we know we need the feature or fix.
The keepalive label will cause the bot to skip closing stale issues.
This label should be used sparingly
**Checklist:**
[skip ci]
> Add keepalive label to exempt issues from the stalebot

- cluster/charts/rook-ceph/templates/role.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.2-apply.yaml
- tests/framework/installer/ceph_manifests.go
The Ceph mgr orchestrator module needs access to restart the daemon pods when the configuration changes for the daemons.
**Checklist:**
[test ceph]
> Grant access to the Ceph mgr to restart pods

- tests/scripts/kubeadm-install.sh
Only kubectl for amd64 is currently available.This modification adds
arm64 version of kubectl that can successfully deploy kubernetes on
arm64 machine.
Signed-off-by: Haichao Li <haichao.li@arm.com>
Resolves #
**Checklist:**
> test: Kubeadm-install add support for arm64

- cluster/charts/rook-ceph/templates/role.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.2-apply.yaml
- tests/framework/installer/ceph_manifests.go
This is needed to allow the ceph manager rook module to read the output
of the <lsmcli> command used to switch disk identification light on/off on
physical disk devices
[test ceph]
**Checklist:**
> Ceph: Added rook manager module rights for read pod logs

- pkg/operator/ceph/object/objectstore.go
The pool size for cephObjectStore `(object.yaml)` , are not getting updated in the cluster upon changing.
Resolves #4341 
**Checklist:**
[test ceph]
> Ceph: ObjectStore replica size will not change

- Documentation/ceph-prerequisites.md
The default RancherOS configuration breaks the Ceph OSD recovery, because the logical volumes will not be activated during the boot process. This documenation update for the `Ceph Prerequisites` describes the needed `cloud-init` configuration change to fix the RancherOS behavior.
Resolves #5027
**Checklist:**
[skip ci]
> LVM infos for RancherOS added to Ceph docs

- pkg/operator/ceph/config/defaults.go
This flag only exists in Pacific, not Octopus.
Resolves #
**Checklist:**
[test ceph]
@neha-ojha @ideepika @liewegas
> ceph: allow size option on pacific only

- design/ceph/ceph-cluster-cleanup.md
This design doc covers the automatic clean up of the dataDirHostPath when the user intentionally deletes the ceph cluster.
Resolves #3222
**Checklist:**
[skip ci]
> Design for ceph cluster clean up

- Documentation/openshift-issues.md
OpenShift requires the monitoring to be bound to the openshift-monitoring namespace instead of the rook default
**Checklist:**
[skip ci]
> Document monitoring namespace for OpenShift

- pkg/daemon/ceph/osd/volume.go
To make debugging easier, make sure each error path has
a unique message.
Resolves #
**Checklist:**
> ceph: Make error unique when OSD on PVC fails to initialize

- pkg/operator/ceph/object/controller.go
The bump from 0.2 to 0.4 controller-runtime versions which happened
during the use of Go Modules (bumping Go version to 1.13) introduced an
an issue where the deployment annotations keep getting changed during
watch update event.
The easy fix is to stop watching Deployment objects for now.
Related to: #5047 
**Checklist:**
[test ceph]
> ceph: child controller-runtime stop watching for deployment

- Documentation/ceph-upgrade.md
Signed-off-by: Paul <paulcatinean@gmail.com>
Update documentation to mention helm chart upgrade path for csi driver. 
Prevents the user from manually applying the RBAC roles when the helm chart does it for him also notifies him where to set the images for CSI in the helm chart.
**Checklist:**
Update documentation to mention helm chart upgrade path for csi driver. 
Prevents the user from manually applying the RBAC roles when the helm chart does it for him also notifies him where to set the images for CSI in the helm chart.
[skip ci]
> ceph: mention helm upgrade path for csi driver

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/register_controllers.go
- pkg/operator/ceph/controller/predicate.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/controller_test.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/filesystem_test.go
- pkg/operator/ceph/file/mds/config.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/file/mds/spec_test.go
- pkg/operator/ceph/operator.go
- pkg/operator/ceph/operator_test.go
- tests/framework/clients/filesystem.go
- tests/framework/clients/pool.go
- tests/framework/utils/k8s_helper.go
The CRD watcher has been replaced by the new controller-runtime
framework.
This brings robustness in our operator, meaning that any resources that
are modified will be reconciled into the desired state.
Resolves https://github.com/rook/rook/issues/4940
**Checklist:**
[test ceph]
[test full]
> ceph: convert Filesystem controller to the controller-runtime

- go.mod
- go.sum
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/register_controllers.go
- pkg/operator/ceph/controller/predicate.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/controller_test.go
- pkg/operator/ceph/nfs/config.go
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/nfs/controller_test.go
- pkg/operator/ceph/nfs/nfs.go
- pkg/operator/ceph/nfs/spec.go
- pkg/operator/ceph/nfs/spec_test.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/controller_test.go
- pkg/util/exec/exec.go
- pkg/util/exec/test/mockexec.go
- pkg/util/exec/translate_exec.go
The CRD watcher has been replaced by the new controller-runtime
framework.
This brings robustness in our operator, meaning that any resources that
are modified will be reconciled into the desired state.
Resolves https://github.com/rook/rook/issues/4941
**Checklist:**
[test ceph]
[test full]
> ceph: convert NFS controller to the controller-runtime

- Documentation/edgefs-cluster-crd.md
- cluster/examples/coreos/rbac.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/monitoring/prometheus.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/cluster.yaml
- cluster/examples/kubernetes/edgefs/cluster_kvssd.yaml
- cluster/examples/kubernetes/edgefs/monitoring/prometheus.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
- design/ceph/security-model.md
- tests/framework/installer/cassandra_manifests.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.1.go
- tests/framework/installer/cockroachdb_manifests.go
- tests/framework/installer/edgefs_manifest.go
- tests/framework/installer/nfs_manifests.go
- tests/framework/installer/yugabytedb_manifests.go
- tests/integration/ceph_upgrade_test.go
There are many namespace fields in ClusterRole{,Binding}. However,
ClusterRole{,Binding} are not namespaced. So we can remove these.
**Checklist:**
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [o] Comments have been added or …
> remove unnecessary namespace fields

- pkg/apis/rook.io/v1/placement.go
- pkg/apis/rook.io/v1/placement_test.go
The default pod anti-affinity for the mons that rook adds automatically intended to be appended to any anti-affinity that is specified in the cluster CR.
There is a bug in the ApplyToPodSpec() method that has long existed. The issue is that when antiaffinity is appended, it will append not only to the pod spec, but will modify the original placement spec. Thus, each mon that is started will have one more antiaffinity clause than the previous mon.
This condition is rarely hit or noticed because it commonly is only hit in the canary pods. Since these pods are immediately deleted, there are no side effects of the duplicate affinity clauses. The place where it becomes an issue is when the mons are backed by a PVC. In this case, the mons do not have node …
> ceph: avoid duplication of mon anti-affinity

- pkg/daemon/ceph/client/pool.go
Rook should always set the pgnum of the new block pool
to the default value("0"). The current implementation accidentally
works fine because newPool.Number is always 0 here.
Nothing
**Checklist:**
- [o] Code generation (`make …
> ceph: set pgnum of block pools to the default value

- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/objectstore_test.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/rgw_test.go
The object store pools may already be created by the mgr module before creating the object CR. If the pool specs are not specified in the object CR, skip pool creation and deletion for the object store. 
If the pools are not specified, the operator will verify that they exist before continuing.
**Checklist:**
[test ceph]
> Allow creation of object store with pre-existing pools

- pkg/operator/ceph/csi/spec.go
If the user has specified the custom ceph-csi image name in the operator the starting of the resizer
will fail, this Fix will use the last index of the slice to check the image version is v2.x or not.
Resolves #5073
**Checklist:**
[test ceph]
> CSI: Fix enable resizer for custom ceph-csi image

- Documentation/ceph-advanced-configuration.md
- pkg/util/sys/device.go
- sgdisk's path shouldn't be hardcoded.
- fix a wrong comment.
Nothing
**Checklist:**
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [o] Comments have been added or updated …
> ceph: some minor cleanups

- pkg/daemon/ceph/osd/daemon.go
- pkg/util/sys/device.go
It appears that udev does not report `ID_FS_TYPE` sometimes so let's try
again with lsblk before not skipping the device.
Closes: https://github.com/rook/rook/issues/5022
Resolves https://github.com/rook/rook/issues/5022
**Checklist:**
[test ceph]
> ceph: double check for a filesystem

- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
disk/partition smaller than 5GiB will be skipped and not used for OSD.
**Checklist:**
[test ceph]
> ceph: reject small devices

- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/k8sutil/deployment.go
If a deployment stays in pending we should give early by looking at
ProgressDeadlineExceeded, this will reduce the time to wait from 20 min
to 10 min because ProgressDeadlineExceeded default is 600 seconds.
Prior to this patch we would wait 20min since we take
currentDeployment.Spec.ProgressDeadlineSeconds which is typically 600
then retry every 2 seconds, which makes it 20min total.
Related to: #5090
**Checklist:**
[test ceph]
> k8sutil: mitigate UpdateDeploymentAndWait condition to help controllers

- pkg/daemon/ceph/client/command.go
- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
- pkg/operator/ceph/config/monstore.go
- pkg/operator/ceph/object/objectstore.go
The PG count on metadata pools should default to rgw_rados_pool_pg_num_min
instead of the more general default pg count. This means rgw pools
will default to 8 PGs instead of 32 PGs, which means a lot more pools
can be created before hitting the default PG limit.
This targets release-1.2 since there will be many merge conflicts in master and will open a separate PR for master.
Resolves #5091
**Checklist:**
[test ceph]
> Backport: Set pg_num for rgw metadata pools to lower default

- pkg/operator/ceph/cluster/crash/reconcile.go
The CrashCollector pod remains in pending state indefinitely after
running on a k8s node that was deleted. The code now deletes the
deployment after the node is deleted.
When a node is deleted, the crash controller reconciles and if a node is not found, the code checks for deployments with label selector for the node and deletes the crashcollector deployment if present
Resolves #5000 
**Checklist:**
> Remove crashcollector pod automatically when the node is deleted.

- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cmd/rook/ceph/operator.go
- go.mod
- go.sum
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/util.go
- pkg/operator/ceph/csi/util_test.go
- pkg/operator/ceph/operator.go
- pkg/operator/k8sutil/configmap.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.1.go
adds all the CSI configurations to ConfigMap.
This configMap can be used in combination with Env Vars
to configure Ceph CSI drivers in rook.
Resolves # remaining parts of #4817 
**Checklist:**
[test ceph]
> Ceph: add CSI configurations to ConfigMap

- pkg/clusterd/disk.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/daemon/ceph/osd/volume.go
- pkg/util/sys/device.go
- tests/framework/installer/device.go
This adds support for LVs to the device availability check in the OSD prepare pod.
The availability of an LV is checked by "ceph-volume lvm list".
If it returns non-empty result, the LV is in use and not available.
This also fixes the argument for "ceph-volume inventory".
When a device "/dev/mapper/foo" is being checked for its availability, the argument should not be "/dev/foo" nor "/dev/dm-1".
Resolves #5075
**Checklist:**
[test ceph]
> ceph: check LV availability by "ceph-volume lvm list"

- Makefile
- images/Makefile
- images/image.mk
This uses grep, sort and awk to auto generate the `make help` menu based
on comments after each target.
Removed `clean.all` and `prune.all` targets as they are not available
anymore.
CI is not skipped as the Makefile might cause issues where I haven't been able to test them locally.
**Checklist:**
> makefile: auto generate target help menu

- pkg/daemon/ceph/client/command.go
- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
- pkg/operator/ceph/config/monstore.go
- pkg/operator/ceph/object/objectstore.go
The PG count on metadata pools should default to rgw_rados_pool_pg_num_min instead of the more general default pg count. This means rgw pools will default to 8 PGs instead of 32 PGs, which means a lot more pools can be created before hitting the default PG limit.
Resolves #5091
**Checklist:**
[test ceph]
> Set pg_num for rgw metadata pools to lower default

- tests/framework/installer/ceph_manifests.go
The flex agent was mistakenly disabled in the CSI config change for #5032. The agent must
be enabled for integration tests. The flex and smoke suites have all been failing in master since the merge earlier today. This was missed before merge because it has similar behavior as an intermittent issue with the flex driver.
**Checklist:**
[test ceph]
[test full]
> Reenable flex driver in the integration tests

- cluster/examples/kubernetes/ceph/operator-openshift.yaml
It is not necessary to have 2 same environment variables and not desired as
changing only one may lead to the second variable being applied with unexpected
value. It is better to have only 1 ROOK_HOSTPATH_REQUIRES_PRIVILEGED environment
variable.
Resolves #5107 
**Checklist:**
[skip ci] skip-ci
> ceph: Removed 2nd env variable ROOK_HOSTPATH_REQUIRES_PRIVILEGED

- build/codegen/boilerplate.go.txt
- build/codegen/codegen.sh
- build/makelib/golang.mk
This specifies `--go-header-file` option at executing `code-generator` to solve this issue(https://github.com/rook/rook/issues/5083) ~~and modifies the header of the generated codes based on `build/codegen/header.txt`.~~
Since this also specifies `--output-base` option to solve the dependencies of `$GOPATH`, we can work outside `$GOPATH` now. (`code-generator` generates files into `$GOPATH` by default.)
Resolves #
- https://github.com/rook/rook/issues/5083
**Checklist:**
> Fix `codegen` to find boilerplate outside of the $GOPATH

- pkg/apis/edgefs.rook.io/v1/resources.go
- pkg/operator/edgefs/cluster/mgr/mgr.go
- pkg/operator/edgefs/cluster/target/pod.go
- pkg/operator/edgefs/iscsi/iscsi.go
- pkg/operator/edgefs/isgw/isgw.go
- pkg/operator/edgefs/nfs/nfs.go
- pkg/operator/edgefs/s3/s3.go
- pkg/operator/edgefs/s3x/s3x.go
- pkg/operator/edgefs/swift/swift.go
/etc/timezone now exposed by operator
/etc/timezone now exposed
Resolves #5118 
**Checklist:**
> edgefs: TZ needs to be exposed

- pkg/operator/ceph/object/config.go
- pkg/operator/ceph/object/config_test.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
When running on SDN, the container is not privileged and the network
stack is not exposed so running the gw on port 80 will not work (not
enough privileged).
Closes: https://github.com/rook/rook/issues/5106
Resolves https://github.com/rook/rook/issues/5106
**Checklist:**
[test ceph]
> ceph: use a different port for rgw on sdn

- Jenkinsfile
The CI is using an older version of git that doesn't recognize git restore.
**Checklist:**
[skip ci]
> Use git checkout instead of git restore

- tests/integration/ceph_base_deploy_test.go
With 1.18 in the test matrix we need to update which versions will run the different ceph test suites.
**Checklist:**
[test ceph]
> Update K8s versions for ceph tests with K8s 1.18

- pkg/operator/ceph/controller/predicate.go
- pkg/operator/ceph/object/user/controller.go
- tests/framework/installer/ceph_installer.go
- tests/integration/ceph_flex_test.go
- tests/integration/ceph_smoke_test.go
With the release of Octopus we need to run the integration tests on Octopus in order to have validation as a supported platform.
We won't want to merge this until after the official release of octopus so we can work with a stable release tag instead of latest-devel.
**Checklist:**
[test ceph]
[test full]
> Run integration tests against octopus

- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/crash/crash.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/rbd/mirror.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/config/config.go
- pkg/operator/ceph/config/datapath.go
- pkg/operator/ceph/controller/spec.go
- pkg/operator/ceph/controller/spec_test.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/test/podspec.go
- pkg/operator/ceph/test/podtemplatespec.go
- pkg/operator/ceph/test/spec.go
Now Kubernetes will perform liveness checks on mon, mds and osd daemons.
The command will:
* call the socket (check for existence)
* execute a command and check the return code (success if 0)
This handles the case where the daemon is stuck locally and
unresponsive. It's unlikely but not impossible.
These checks bring more robustness to the implementation.
rbd-mirror and NFS have been leftover for the following reason. The …
> ceph: add liveness probe to mon, mds and osd daemons

- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.2-apply.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.2-crds.yaml
Update both documents and `upgrade-from-v1.2*.yaml` files for Rook v1.3
release.
Fixes #5130 
Of note:
- note when the upgrade to CSI driver v2.0 can be done
- note that CSI image envs can be removed to have Rook use defaults
- update Ceph version upgrade section
- update supported Ceph version info
- add information about new Operator ConfigMap
- update CRDs before upgrade b/c new 'status' fields
Resolves #
**Checklist:**
[skip ci]
> Ceph: upgrade docs: update upgrade docs for v1.3

- Documentation/ceph-pool-crd.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/filesystem-ec.yaml
- cluster/examples/kubernetes/ceph/filesystem-test.yaml
- cluster/examples/kubernetes/ceph/filesystem.yaml
- cluster/examples/kubernetes/ceph/object-ec.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
- cluster/examples/kubernetes/ceph/object-test.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- cluster/examples/kubernetes/ceph/pool-ec.yaml
- cluster/examples/kubernetes/ceph/pool-test.yaml
- cluster/examples/kubernetes/ceph/pool.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.2-crds.yaml
- images/image.mk
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
- pkg/operator/ceph/pool/controller_test.go
- pkg/operator/ceph/pool/validate.go
- tests/framework/installer/ceph_manifests.go
This commit enables configuring a compression_mode for CephPools that takes the values as specified for bluestore OSD `compression_mode` values,
https://docs.ceph.com/docs/master/rados/configuration/bluestore-config-ref/#inline-compression
Resolves #5116 
**Checklist:**
- **NOTE**: I do not think there are any, but would like an opnion if integration tests need to be added for this PR
[test ceph]
> ceph: Add ability to specify compression mode for pools

- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/osd/spec.go
Thanks to https://github.com/ceph/ceph/pull/33633, when running on
Octopus, we don't need to use `--pid=host`. This means we are not using
the host PID but use the PID namespace of the pod.
**Checklist:**
[test ceph]
> ceph: do not use host PID anymore

- build/makelib/golang.mk
This adds v1.14 to the supported Golang versions in the makefile.
**Checklist:**
> build: allow go 1.14

- Documentation/ceph-prerequisites.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-teardown.md
- Documentation/ceph-upgrade.md
- Documentation/helm-operator.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.2-apply.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.2-crds.yaml
- tests/README.md
Various updates are needed for the v1.3 release.
- The pending release notes were missing some features
- Added a section to the upgrade guide for breaking changes to OSDs
- Clarifications around Ceph prereqs and min version
- Other misc clarifications
Resolves #4724 
**Checklist:**
[skip ci]
> Updated docs need for the Rook v1.3 release

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-filesystem-crd.md
- Documentation/ceph-nfs-crd.md
- Documentation/ceph-object-store-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/filesystem-ec.yaml
- cluster/examples/kubernetes/ceph/filesystem.yaml
- cluster/examples/kubernetes/ceph/nfs.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- design/ceph/filesystem.md
- design/ceph/object/store.md
- pkg/apis/rook.io/v1/placement.go
- pkg/apis/rook.io/v1/placement_test.go
- pkg/apis/rook.io/v1/types.go
- pkg/apis/rook.io/v1/zz_generated.deepcopy.go
Support topologySpreadConstraints to spread OSD pods among failure domains.
https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
Without this feature, the number of OSD pods would be different between the failure domains very much. At worst, there is a possibility that a failure domain has many OSDs and other failure domains have no OSDs. It can partly be mitigated with podAntiAffinity. However, it only works if there are at most one OSD per node. For more detail, please refer to the following document.
https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml#L59
Resolves #4387 
**Checklist:**
- [o] Reviewed the developer guide on …
> ceph: support topoplogySpreadConstraints

- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
Fix the following error message due to unnecessary whitespaces.
```console
$ kubectl create -f cluster-on-pvc.yaml
error: error parsing cluster-on-pvc.yaml: error converting YAML to JSON: yaml: line 85: mapping values are not allowed in this context
```
Resolves #5149
**Checklist:**
- [o] Upgrade from previous release is …
> ceph: remove unnecessary whitespaces in the example

- cmd/rook/ceph/cleanup.go
- pkg/operator/ceph/cluster/cleanup.go
- pkg/operator/ceph/cluster/cleanup_test.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mon/config.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.1.go
This is a follow up PR of #4959
In case of multiple clusters, we don't want to delete all the mon directories under the dataDirHostPath during cluster cleanup.
This PR deletes the mon directory only if the monitor secret key matches.
- Fetch the monitor secret before all the ceph daemons are deleted. 
- Pass on this monitor secret as plain text (its ok to send as a plain text since the cluster is being deleted) to the clean up job. 
- (Another reason for passing the secret like this is the original `rook-ceph-mon-keyring` secret will get deleted before the clean up job will start. So it can't be mounted on to the clean up job as a volume)
- Clean up job deletes a mon directory only if this monitor secret …
> Cluster CleanupPolicy: Delete correct mon directories under the dataDirHostPath

- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.1.go
The CephManifests interface is intended for manifests that install the product (RBAC, CRDs, operator, etc). These cleanup methods are more about test code. The test code needs to behave the same whether it is a normal install or an upgrade. We don't need to version it differently for upgrades between the CephManifestsMaster and CephManifestsV1_1 implementations
- Removed GetCleanupPods() and GetCleanupVerificationPod() out of CephManifests interface. 
- Moved both of these into ceph_installer.go file.
Resolves #
**Checklist:**
[test ceph]
> Integration Tests: moving GetCleanupPod() and GetCleanupVerificationPod() methods out of CephManifests interface

- pkg/operator/ceph/cluster/mon/mon.go
The canary pod does not run any daemon so the liveness check probe will
fail.
Closes: https://github.com/rook/rook/issues/5150
Resolves https://github.com/rook/rook/issues/5150
**Checklist:**
[test ceph]
> ceph: do not set liveness check on canary pod

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/charts/rook-ceph/templates/role.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- pkg/operator/ceph/disruption/nodedrain/reconcile.go
- tests/framework/installer/ceph_manifests.go
- Some k8s clusters need RBAC permissions for both extensions and apps api groups. Added both.
- Handled a not-found error in a delete operation.
Resolves #
**Checklist:**
[test ceph]
> Fix RBAC and handle error to enable deleting of drain-canaries

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/role.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.2-apply.yaml
- cmd/rook/rook/rook.go
- go.mod
- go.sum
- pkg/clusterd/context.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/config/config.go
- pkg/operator/ceph/config/network.go
- pkg/operator/ceph/config/network_test.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/nfs/spec.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/rgw_test.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/k8sutil/network.go
- pkg/operator/k8sutil/network_test.go
- tests/framework/installer/ceph_manifests.go
You can now use Rook along with Multus. Multus must be up and running
and the right ressources must exist such as NetworkAttachmentDefinition
CR.
The Cluster CR spec has new fields to work with multus:
```
network:
provider: multus (or 'host' for hostNetworking)
selectors:
public: NetworkAttachmentDefinition name
cluster: NetworkAttachmentDefinition name
```
If only a single NetworkAttachmentDefinition is provided Rook will use
both anyway for the Ceph traffic.
Please refer to the doc to learn more.
Resolves https://github.com/rook/rook/issues/4716
**Checklist:**
[test ceph]
> ceph: add multus support

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/controller/predicate.go
- pkg/operator/ceph/controller/predicate_test.go
When the CephCluster CR gets updated with a new image version, we need
to notify the child controllers of that upgrade.
For this, we set a 'ceph_version' label on the CR itself which will
effectively trigger a reconcile based on an update event.
This needs to be revisited and see how we can make use of
`EnqueueRequestsFromMapFunc` which might be a better approach using
controller-runtime built-in.
Closes: https://github.com/rook/rook/issues/5153
Resolves  https://github.com/rook/rook/issues/5153
**Checklist:**
[test ceph]
> ceph: trigger update on child controllers

- tests/integration/ceph_base_block_test.go
- tests/integration/ceph_base_file_test.go
- tests/integration/ceph_upgrade_test.go
The upgrade test requires the CSI driver to be running so we cannot run the test on older versions than k8s 1.13. This means K8s 1.11 in the release branch will be skipping the upgrade test. The only Ceph tests running on K8s 1.11 will be the CephFlexSuite, which should be sufficient for maintenance mode.
This fixes a failure in the release branch CI for the k8s 1.11 tests where we weren't skipping the upgrade test soon enough.
**Checklist:**
[test ceph]
[test full]
> Skip upgrade test when CSI is not supported on older K8s

- Documentation/ceph-toolbox.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
Set the manifests versions for the latest beta release. Interestingly enough there was a bug in the first beta release where the tags were set to alpha instead beta.
**Checklist:**
[skip ci]
> Set deployment manifest versions to v1.3.0-beta.1

- tests/integration/ceph_base_block_test.go
- tests/integration/ceph_base_file_test.go
- tests/integration/ceph_upgrade_test.go
The upgrade test requires the CSI driver to be running so we cannot run the test on older versions than k8s 1.13.
This is to port #5168 to master since we needed to first verify in the release branch.
**Checklist:**
[test ceph]
> Skip upgrade test where csi is not supported

- pkg/operator/ceph/object/rgw.go
Delete client.rgw.storeName.daemonletter user instead of client.storeName.daemonletter which doesn't exist when we delete all components related to the deletion of a CephObjectStore
Resolves #5178 
**Checklist:**
> ceph: remove appropriate rgw ceph user when CephObjectStore is deleted

- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/controller/predicate.go
- tests/integration/ceph_base_file_test.go
- tests/integration/ceph_upgrade_test.go
The upgrade test will now support upgrading from nautilus to octopus and that files and be read and written after the upgrade.
Resolves #5153
**Checklist:**
[test ceph]
[test full]
> Integration test for upgrade from nautilus to octopus

- pkg/operator/ceph/config/monstore.go
- pkg/operator/ceph/object/objectstore.go
Since e396379 rook create rgw metadata pools with 8 PGs instead of
32. But the pg_autoscaler increase it back to 32 as the pg_num_min parameter
is not set on those pools.
Resolves #5176 
**Checklist:**
> ceph: set pg_num_min for rgw metadata pools

- PendingReleaseNotes.md
Clarify that PID namespace changes apply only to Ceph Octopus.
Resolves #
**Checklist:**
[skip ci]
> Ceph: Clarify PID/Octopus in pendingreleasenotes

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
This fixes the resync of the Deployment of the OSD pod that uses
an LV-backed PV.
`getOSDInfo()` reads the configuration of the OSD pod from the existing
Deployment, but it overlooked this case.
Resolves #5139
**Checklist:**
[test ceph]
> ceph: fix resync failure of OSD pod using LV-backed-PV

- build/codegen/codegen.sh
- pkg/client/informers/externalversions/generic.go
The path was copied in the wrong location, ending up with a duplicated
directory in pkg/pkg/api. We need pkg/ only.
Resolves #
**Checklist:**
[test ceph]
> rook: fix codegen

- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
Co-authored-by: donggyu_park donggyu_park@tmax.co.kr
Signed-off-by: taeuk_kim <taeuk_kim@tmax.co.kr>
In replicated pool,
- Add replica_size to pool create command
- Delete pool set command
By doing this, pool min_size is computed correctly.
Resolves #5127 
**Checklist:**
> Ceph: Add replica_size flag in replicated pool creation time

- build/release/Makefile
This updates the manifest-tools from v1.0.0 to v1.0.2 to
pickup the following fix
https://github.com/estesp/manifest-tool/pull/90.
This currently prevents the build to push images to Docker
hub.
Resolves #5194
This should be enough as the default of the `--tags` flags is `false`, see https://github.com/estesp/manifest-tool/blob/fa20a3b9b43f7c1acedb8d97c249803cc923e009/inspect.go#L21-L24.
Resolves #5194
**Checklist:**
> build: update manifest-tools version to v1.0.2

- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
Merely appending rook to the cd path on this quickstart doc page.
**Checklist:**
- [x ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [x ] Documentation has been updated, if necessary.
- [ x] Unit tests have been added, if necessary.
- [x ] Integration tests have been added, if necessary.
- [ x] Pending release notes updated with breaking and/or notable changes, if necessary.
- [x ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ x] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ x] Comments have been added or updated based on the standards set in …
> ceph: Fixing path on ceph-quickstart to include rook

- .github/PULL_REQUEST_TEMPLATE.md
The commitlint bot is rarely understood and flags to skip the CI are rarely used by new contributors. This update to the PR template aims to make these options more discoverable to newer members of the community
**Checklist:**
[skip ci]
> Clarify the CI flags in the PR template

- cluster/charts/rook-ceph/templates/resources.yaml
The subresources field was missing, this was missed in
https://github.com/rook/rook/pull/4964.
The .metadata.generation field is updated if and only if the value at the .spec subpath changes.
Additionally, if the spec does not change, .metadata.generation is not updated.
This is a must-have for the controller-runtime work, if we don't have
this, the generation field will always be incremented, resulting in a
endless reconcile loop.
Closes: https://github.com/rook/rook/issues/5173
Resolves https://github.com/rook/rook/issues/5173
**Checklist:**
[test ceph]
> ceph: helm add missing subresources to CRD

- pkg/operator/ceph/cluster/mgr/config.go
mgr should only include "mon allow profile mgr" instead
of "mon allow *"
Resolves #2529 
Reverts: /pull/2523
**Checklist:**
[test ceph]
[test full]
> Ceph: revert mgr to minimal privilege

- pkg/operator/ceph/controller/predicate.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/pool/controller.go
The controllers should ignore events for status updates. The reconcile only needs to happen when the spec is updated or the resource is marked for deletion. Otherwise, the controllers may stay in an update loop as the reconcile events are triggered again every time there is a status update during the reconcile.
The second commit is to more reliably update the status. When updating the status on resources sometimes the update fails due to the resource being an outdated version. This frequently occurs when the same reconcile loop updates the status multiple times, or the finalizer is added, or some other update to the resource. Upon the next reconcile the error would generally go away since the status or finalizer didn't need to be updated multiple times. …
> Skip reconcile events where the spec is not updated

- cluster/charts/rook-ceph/values.yaml
Without the default value helm does not have chance
to infer the field type and fails during type check
when custom `nodeSelector` value is specified;
Closes: https://github.com/rook/rook/issues/5236
Signed-off-by: Ivan Kurnosov <zerkms@zerkms.com>
Added a default `{}` for the `nodeSelector`.
Resolves #5236
**Checklist:**
> ceph: helm add default value for the `nodeSelector`

- tests/framework/installer/ceph_installer.go
LVs in a VG are removed with vgremove. So lvremove before vgremove is not necessary.
None
**Checklist:** …
> ceph: remove unnecessary lvremove in test

- Documentation/k8s-pre-reqs.md
This fixes a markdwon link on the k8s-pre-reqs doc page.
Resolves #
**Checklist:**
[skip ci]
> doc: fix link in k8s-pre-reqs page

- Jenkinsfile
- tests/README.md
- tests/framework/installer/cassandra_installer.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/cockroachdb_installer.go
- tests/framework/installer/edgefs_installer.go
- tests/framework/installer/environment.go
- tests/framework/installer/installer.go
- tests/framework/installer/nfs_installer.go
- tests/framework/installer/provisioners.go
- tests/framework/installer/yugabytedb_installer.go
- tests/integration/ceph_upgrade_test.go
The command line flags parsing inside an init() method was causing issues at runtime when trying to add certain new features, which is a limitation of the flag parsing. We now move away from using any command line flags in the tests and only use environment variables to simplify adding new parameters to the tests.
**Checklist:**
[test full]
> Convert integration test CLI params to env vars

- pkg/operator/ceph/file/filesystem.go
CSI CephFS provisioner fails to provision a Persistent Volume after upgrading from Rook Ceph Operator 1.1.2 to 1.1.7.
This issue can be fixed by removing givePoolAppTag function call if the `fsname` is not `cephfs`.
Resolves #4494 
**Checklist:**
[test ceph]
[test full]
> Ceph: PV provisioning fails upon upgrade

- build/codegen/codegen.sh
The codegen output is moving the apis and client folders to the root folder instead of under pkg. @leseb Why was this changed in #5200? Perhaps there is a difference in dev environment setup.
**Checklist:**
[skip ci]
> Codegen needs to copy to pkg subfolder

- cluster/charts/rook-ceph/templates/psp.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- tests/framework/installer/ceph_manifests.go
This commit adds seccomp annotations to the PSP shipped with Rook
Operator. In this way the operator when deployed will be more secure and
will only be allowed the syscalls defined the runtime's seccomp profile.
[test ceph]
> PSP: Add seccomp annotations

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.2-crds.yaml
- tests/framework/installer/ceph_manifests.go
Signed-off-by: zoetrope <a.ikezoe@gmail.com>
Add requireSafeReplicaSize in CephObjectStore CRD
Resolves #5260 
**Checklist:**
> Ceph: Add requireSafeReplicaSize in CephObjectStore CRD

- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_flex_test.go
- tests/integration/ceph_helm_test.go
- tests/integration/ceph_smoke_test.go
- tests/integration/ceph_upgrade_test.go
Refactor the StartTestCluster method to make it more readable.
I have put most of the parameters used in this function in the <TesCluster> struct.
In this way the call to this function is more easy to understand and to use.
The addition of new parameters to this method started to be annoying.
[test ceph]
**Checklist:**
> ceph: refactor <StartTestCluster>

- Jenkinsfile
- tests/README.md
- tests/framework/installer/ceph_installer.go
- tests/scripts/localPathPV.sh
Make it possible to pass the Ceph integration test in the local environment. Currently, it's difficult due to the lack of documentation and some CI-environment-specific configurations.
Nothing
**Checklist:** …
> Ceph: make it possible to pass the integration test in the local environment

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/common-external.yaml
- cluster/examples/kubernetes/ceph/create-external-cluster-resources.sh
- cluster/examples/kubernetes/ceph/import-external-cluster.sh
- pkg/daemon/ceph/client/command.go
- pkg/daemon/ceph/client/command_test.go
- pkg/daemon/ceph/client/mon.go
- pkg/daemon/ceph/client/mon_test.go
- pkg/daemon/ceph/client/status.go
- pkg/daemon/ceph/config/config.go
- pkg/daemon/ceph/config/config_test.go
- pkg/daemon/ceph/config/info.go
- pkg/daemon/ceph/config/keyring.go
- pkg/operator/ceph/cluster/cephstatus.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/cluster/mon/env.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/rbd/controller.go
- pkg/operator/ceph/csi/secrets.go
- pkg/operator/ceph/object/admin.go
- tests/integration/ceph_base_file_test.go
Currently, we need to configure the Ceph external Admin key in the Rook deployment to be able to connect to an external Ceph cluster.
If we wanted to run in a multi-tenant fashion were several K8s/Rook clusters wanted to connect to the same external ceph cluster, each K8s deployment would have the access to the External Ceph Admin key and could potentially access or delete the Data from pools that belong to other k8s/Rook Clusters.
Now the admin key is optional but the helper script create-external-cluster-resources.sh
will help create the necessary keys/users to connect to that cluster.
Closes: https://github.com/rook/rook/issues/4917 and https://github.com/rook/rook/issues/5249
**Which issue is resolved by …
> ceph: make admin key optional for external cluster

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- images/ceph/toolbox.sh
As another option to run Ceph commands, a script can be executed with Ceph commands as if running in the toolbox, but will instead run in a job where the logs can be collected and analyzed separately. This would be useful where automation is in place to collect information about the cluster periodically or upon some failure that is detected, without requiring an interactive shell.
**Checklist:**
[test ceph]
> Toolbox job for running a ceph script

- Documentation/ceph-object-bucket-claim.md
This commit adds the missing `AWS_` prefix to the data keys
of a Secret generated by an OBC.
The documentation on the Ceph ObjectBucketClaim CRD
erroneously states that the generated Secret resource
contains keys `ACCESS_KEY_ID`, `SECRET_ACCESS_KEY`.
According to ceph-object.md, and when mounting the secret
into a container via secretRef, or inspecting it with kubectl,
the variables have an `AWS_` prefix.
Like so: `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`.
**Checklist:**
[skip ci]
> doc: fix secret env keys on ObjectBucketClaim

- images/ceph/toolbox.sh
The toolbox script is used for configuring the toolbox. If the mons are to fail over while the toolbox is running, the new list of mons needs to be updated. However, if run temporarily
as a one-time job, the script only needs to initialize the ceph.conf and then exit.
This is a minimal backport. The main feature will remain in master for v1.4 as seen in #5284.
**Checklist:**
[test ceph]
> Backport: Allow toolbox script to skip watching mons

- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/object/user/controller_test.go
- pkg/operator/ceph/pool/controller_test.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.2.go
- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_upgrade_test.go
The name of a CephCluster is commonly the same as the namespace, but not always. When looking up the ceph cluster we can look for the first one in the namespace rather than requiring the name to be the same as the namespace.
Resolves #5302 
**Checklist:**
[test ceph]
[test full]
> Lookup of the cluster cannot rely on namespace name

- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/object/user/controller_test.go
- pkg/operator/ceph/pool/controller_test.go
The name of a CephCluster is commonly the same as the namespace,
but not always. When looking up the ceph cluster we can look for
the first one in the namespace rather than requiring the name
to be the same as the namespace.
**Checklist:**
[test ceph]
> Lookup of the cluster cannot rely on namespace name (bp #5304)

- Documentation/ceph-teardown.md
Improved the "Removing the Cluster CRD Finalizer" section of Ceph / Cleaning up a Cluster
Resolves #1488 
[skip ci]
**Checklist:**
> docs: improve ceph finalizer patching (#1488)

- Documentation/ceph-examples.md
- Documentation/ceph-quickstart.md
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- The cluster-test.yaml example is useful for small test clusters where only one mon is required and certain settings can be disabled when not running in production.
- Added the external cluster examples to the ceph-examples.md.
Resolves #5301 
**Checklist:**
[skip ci]
> Restore the cluster-test.yaml example

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/charts/rook-ceph/templates/role.yaml
- cluster/charts/rook-ceph/templates/serviceaccount.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- tests/framework/installer/ceph_manifests.go
Currently, helm chart is somehow outdated and has differences with
example/common.yaml.
This commit modifies both manifests to use the same resources.
Resolves #
**Checklist:**
[test ceph]
[test full]
> ceph: update helm chart manifests

- pkg/daemon/ceph/osd/volume.go
When the metadataDevice is specified, it was a regression that it was being interpreted also as a data device. ceph-volume was failing when the metadataDevice was added as both a data and metadata device. So we ensure it is not added to the list of data devices.
Resolves #5300 
**Checklist:**
[test ceph]
> Metadatadevice should not be added to osd data device list

- pkg/operator/ceph/config/monstore.go
- pkg/operator/ceph/config/monstore_test.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/object/config.go
- pkg/operator/ceph/object/rgw.go
Remove specific rgw config added to the mon configuration database when deleting a CephObjectstore or when scaling down number of rgw
Resolves #5185 
**Checklist:**
[test ceph]
> ceph: remove specific rgw configuration on mon configuration database

- cluster/examples/kubernetes/ceph/common.yaml
- tests/framework/installer/ceph_manifests.go
Adding seccomp annotations to the PSP has made Kubernetes start choosing
the recommended Kubernetes "default" PSP over the Rook privileged PSP,
causing operator start errors. Append 00 (double zero) to the beginning
of the PSP name to make sure it is one of the first PSPs checked by
Kubernetes and will be matched before the "default" one.
Resolves #5293 
**Checklist:**
[test ceph]
> ceph: append 00 to rook-privileged PSP name

- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
The pg_autoscaler is enabled by default in octopus. In nautilus it was a new feature and was not enabled by default for that reason. Now that the pg_autoscaler is more stable and is essentially the same as the autoscaler in octopus, we can enable it by default.
The pg_autoscaler module is already enabled in the integration tests and already mentioned by docs, this is just to enable it by default in the example cluster.yaml.
**Checklist:**
[skip ci]
> Enable pg_autoscaler module in default examples

- README.md
- SECURITY.md
- cluster/olm/ceph/assemble/metadata-k8s.yaml
This PR updates the readme and docs with the new Rook mailing lists hosted by the CNCF:
- cncf-rook-info@lists.cncf.io
- cncf-rook-security@lists.cncf.io
- cncf-rook-distributors-announce@lists.cncf.io
**Checklist:**
[skip ci]
> docs: update rook mailing lists to new lists.cncf.io addresses

- pkg/clusterd/disk.go
Regression caused by ab83738aacf844c9727eadee699d41076cf690e7 commit. This PR isn't revert. It addressing the case when empty PKNAME and path.Base()
Resolves #5244
**Checklist:**
> edgefs: raw disk empty check regression fix

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/osd/health.go
- pkg/operator/ceph/cluster/osd/health_test.go
If the OSD pod is portable and is on a failed node, the node will be stuck indefinitely in the terminating state. The pod can be force deleted in this scenario in order to allow the underlying volume to be detached and then mounted on another node.
Resolves #5348
**Checklist:**
[test ceph]
> Restart portable osd pod if stuck

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/osd/health.go
- pkg/operator/ceph/cluster/osd/health_test.go
If the OSD pod is portable and is on a failed node, the node will be stuck indefinitely in the terminating state. The pod can be force deleted in this scenario in order to allow the underlying volume to be detached and then mounted on another node.
(cherry picked from commit c713fd30f961953b9c954629f09cc4711c8686ab)
**Checklist:**
[test ceph]
> Restart portable osd pod if stuck (bp #5376)

- cluster/examples/kubernetes/ceph/cluster.yaml
Since the rbd mirror has been extracted to its own CR, it does not exist
in cluster.yaml anymore.
Resolves #
**Checklist:**
[skip ci]
> ceph: remove leftover rbd mirror in cluster.yaml

- images/cassandra/Makefile
- images/ceph/Makefile
- images/cockroachdb/Makefile
- images/cross/Makefile
- images/edgefs/Makefile
- images/image.mk
- images/nfs/Makefile
- images/yugabytedb/Makefile
Automatically detect Podman if Docker is not available.
This allows me to run make and complete it succesfully without Docker
and without the need to set the DOCKERCMD env. variable.
Fixes: #5335 
Signed-off-by: Yaniv Kaul <ykaul@redhat.com>
Resolves #5335
**Checklist:**
> Images: allow building images using Podman.

- pkg/daemon/ceph/osd/daemon.go
If we fail to release an LVM device, we should not fail the deployment.
We just print the error and let the backend handle the rest. Some
CSI backend will force detach the device anyway.
This prevents the deployment to get stuck in terminating.
[test ceph]
> ceph: do not fail on deactivate

- Documentation/ceph-common-issues.md
Fix dead links in ceph document.
Resolves #5396
**Checklist:** …
> ceph: fix dead links

- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/create-external-cluster-resources.sh
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/storageclass-bucket-delete.yaml
- cluster/examples/kubernetes/ceph/storageclass-bucket-retain-external.yaml
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/bucket/provisionner_test.go
- pkg/operator/ceph/object/bucket/util.go
- pkg/operator/ceph/object/user.go
- tests/framework/installer/ceph_manifests.go
We can now consume an external s3 endpoint which is not managed by Rook.
Resolves #
**Checklist:**
**many things need to be fleshed out but I'm opening this early for review and discussion**
[test ceph]
> ceph: add support for OBC on external cluster

- pkg/daemon/ceph/osd/daemon.go
If we fail to release an LVM device, we should not fail the deployment.
We just print the error and let the backend handle the rest. Some
CSI backend will force detach the device anyway.
This prevents the deployment to get stuck in terminating.
(cherry picked from commit 65aae84bdd1c1975b5fde1c16328be185712fe66)
**Checklist:**
Backport of #5398
[test ceph]
> ceph: do not fail on deactivate (bp #5398)

- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/create-external-cluster-resources.sh
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/storageclass-bucket-delete.yaml
- cluster/examples/kubernetes/ceph/storageclass-bucket-retain-external.yaml
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/bucket/provisionner_test.go
- pkg/operator/ceph/object/bucket/util.go
- pkg/operator/ceph/object/user.go
- tests/framework/installer/ceph_manifests.go
We can now consume an external s3 endpoint which is not managed by Rook.
(cherry picked from commit b86bb9c5286d7bc953848907be0dee7bccb3c27c)
Resolves #
**Checklist:**
[test ceph]
> ceph: add support for OBC on external cluster (bp #5372)

- pkg/operator/ceph/csi/spec.go
If ROOK_CSI_ALLOW_UNSUPPORTED_VERSION=false and the csi canary image is set to quay.io/cephcsi/cephcsi:canary, the csi driver fails to load as expected since it is not supported. But if the flag is set to true, it is expected to allow the canary image which isn't versioned. The supported version check was requiring that the version be detected in the image.
**Checklist:**
[test ceph]
> Allow csi driver version to be undetected if unsupported flag is set

- pkg/operator/ceph/cluster/osd/health.go
- pkg/operator/ceph/cluster/osd/health_test.go
When an OSD pod is stuck in terminating state, there is no need to check if the OSD is marked as out before force deleting. As long as the portable osd is down and it's on a node that is not available, we will force delete the pod.
Resolves #5348
**Checklist:**
[test ceph]
> Delete terminating osd pods even if not out

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/spec.go
There are many duplicated code to judge whether an OSD is on PVC or not. Instead, let's introduce a function for this purpose. It can also be applied to the logic of judging whether an OSD on PVC has metadata device or not.
Nothing
**Checklist:** …
> ceph: judge whether an OSD is on PVC or not by function

- pkg/operator/ceph/object/spec.go
ceph gid (167) provided as supplementary group to FsGroup, so that all the volume mounts can
be accessed by the same. This is required for ssl certificate consumed by the rgw server from ceph octopus on-wards.
Resolves #5265
**Checklist:**
[test ceph]
> objectstore: Add ceph group to FsGroup

- pkg/clusterd/disk.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/util/sys/device.go
When configuring an OSD on a multipath device, ceph-volume inventory is failing to detect that the device is available, complaining about insufficient space. 
```
ceph-volume inventory --format json /dev/mapper/3600605b000ac584025e796091b840018
{"available": false, "lvs": [], "rejected_reasons": ["Insufficient space (<5GB)"], "sys_api": {}, "path": "/dev/mapper/3600605b000ac584025e796091b840018", "device_id": ""}
```
Instead of relying on c-v inventory to determine if the device is available, just call c-v raw list to determine if there is already an osd configured on the pv. Otherwise, just attempt to configure the OSD. Instead we should get a fix from c-v, but this will allow testing to see if the OSD config can get path that error while preparing the …
> Multipath support for OSD on PVC

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/k8sutil/deployment.go
An OSD on a PVC when portable=false is assigned to a node with a node selector. The same node assignment is expected for the lifetime of the cluster. On subsequent reconciles, the operator was looking up the node assignment from the nodeName on the pod spec, which is not set if the pod is down. The operator needs to retrieve the assignment from the deployment spec node selector.
Resolves #5416
**Checklist:**
[test ceph]
> OSD on PVC node assignment should be the node selector rather than nodeName

- pkg/daemon/ceph/osd/daemon.go
The activation of the LVs for OSDs had an invalid argument to vgchange. The invalid argument is now reverted to enable the OSDs in this scenario again.
This was a regression from #5398.
The invalid argument is seen in the osd log from the deactivate command.
```
2020-05-06T10:20:11.82040536Z 2020-05-06 10:20:11.820313 I | rookcmd: starting Rook 4.4-12.1d7fdd95.release_4.4 with arguments '/rook/rook ceph osd start -- --foreground --id 1 --fsid 76f7ef91-7fce-47cf-bea3-debd3be7c4bb --cluster ceph --setuser ceph --setgroup ceph --setuser-match-path /var/lib/rook/osd1 --crush-location=root=default host=ocs-deviceset-0-0-2w27c rack=rack0 region=us-west-1 zone=us-west-1a --default-log-to-file false --ms-learn-addr-from-peer=false'
2020-05-06T10:20:11.82040536Z …
```
> Remove invalid verbose params from lv activate

- pkg/daemon/ceph/osd/daemon.go
The activation of the lvs for OSDs had an invalid argument to vgchange. The invalid argument is now reverted to enable the OSDs in this scenario again.
(cherry picked from commit af54349a5ef245bdf54bb85dd818be12a4faf426)
**Checklist:**
[test ceph]
> Remove invalid verbose params from lv activate (bp #5438)

- cluster/examples/kubernetes/ceph/cluster-test.yaml
In test environments there may only be a single node, so we set the default pool size in the test example to one.
**Checklist:**
[skip ci]
> Set test default pool size to one

- cluster/examples/kubernetes/ceph/import-external-cluster.sh
The cephfs csi driver expects both adminID and adminKey instead of
userID and userKey which are only specific to rbd.
Closes: https://github.com/rook/rook/issues/5432
Resolves https://github.com/rook/rook/issues/5432
**Checklist:**
[skip ci]
> ceph: fix import script csi details

- tests/scripts/kubeadm.sh
Signed-off-by: Haichao Li <haichao.li@arm.com>
Add the makeTestImages tag of arm64 in kubeadm installation script.
Resolves #
**Checklist:**
> tests: Kubeadm add the makeTestImages tag of arm64

- Documentation/ceph-upgrade.md
Because of the ClusterRole api version change,  #5341  may occur
when upgrading the rook chart to the latest version.
This pull request updates `ceph-upgrade.md` for handling the issue.
Resolves #5341
**Checklist:**
[skip ci]
> Doc: update ceph-upgrade.md for handling a known issue

- Jenkinsfile
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/environment.go
- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_flex_test.go
- tests/integration/ceph_helm_test.go
- tests/integration/ceph_mgr_test.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_smoke_test.go
- tests/integration/ceph_upgrade_test.go
First approach to see if the Ceph manager integration tests can be implemented in this way
[test ceph]
[test full]
**Details about execution of this test**
```
[jolmomar@juanmipc rook]$ go test -v -timeout 1800s -run TestMgrSmokeSuite ./tests/integration 
=== RUN   TestMgrSmokeSuite
2020-02-25 13:49:38.773506 I | exec: Running command: kubectl config view -o json
2020-02-25 13:49:38.822631 I | testutil: Loaded kubectl context kubernetes at https://192.168.122.136:6443. secure=false
2020-02-25 13:49:38.822912 I | integrationTest: running all tests
2020-02-25 13:49:38.827730 I | exec: Running command: kubectl config view -o json
2020-02-25 13:49:38.878703 I | testutil: Loaded kubectl context kubernetes at …
```
> Ceph: manager integration tests

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
OSD on PVC supports multipath thanks to the following commit.
ceph: add support for multipath devices
32730123ea542710ccae48c90d91016e6afc0b55
However, it's not documented yet.
Nothing.
**Checklist:** …
> ceph: write down the multipath support in the documents

- cluster/examples/kubernetes/ceph/operator-openshift.yaml
Resync with operator.yaml
Resolves #
**Checklist:**
[skip ci]
> ceph: add missing op option for ocp

- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/user.go
When a user or a bucket does not exist anymore, let's stop the reconcile
loop instead of waiting forever.
Also, unlink the user before deleting it otherwise the deletion fails.
**Checklist:**
[test ceph]
> ceph: obc relax error handling and user deletion

- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/user.go
When a user or a bucket does not exist anymore, let's stop the reconcile
loop instead of waiting forever.
Also, unlink the user before deleting it otherwise the deletion fails.
(cherry picked from commit 58577a353743fe28c5df243675d585bb68dd12ae)
Backport of #5465
[test ceph]
> ceph: obc relax error handling and user deletion (bp #5465)

- Jenkinsfile
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/environment.go
- tests/framework/utils/exec_utils.go
- tests/integration/ceph_multi_cluster_test.go
The PVCs for OSD on PVC test is perepared before running the integration test. In addition, users are forced to run this script for this by themselves. To avoid this problem, running this script inside the integration test.
Nothing
**Checklist:** …
> Ceph: prepare pvc just before osd on pvc test

- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/util.go
- pkg/operator/k8sutil/deployment.go
- pkg/operator/k8sutil/statefulset.go
sometimes the kube schedular will schedule the provisioner pod on the same node. it doesn't make
sense to have both provisioner pod running on the same node, we need to set the pod anti-affinity to make sure that no provisioner pods runnings on the same node.
Resolves #5271
**Checklist:**
[test ceph]
> CSI: set pod anti affinity to provisioner pod

- pkg/operator/ceph/cluster/cluster_external.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/cluster/rbd/controller.go
- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/operator.go
During cluster deletion, we currently only retry for a couple minutes to wait for the pvcs to be deleted. After the timeout, we proceed with the cluster deletion. To properly protect the pvcs for proper cleanup, the finalizer should not be removed until the pvcs are all confirmed to be deleted. In order to not block other cluster events, we re-queue the deletion event to run again every 10s until the pvcs are deleted or the finalizer is manually removed.
**Checklist:**
[test ceph]
> Wait for volume deletion before removing the cluster finalizer

- pkg/operator/ceph/object/objectstore.go
pg_num_min needs to be set on all new and existing rgw metadata pools so the autoscaler won't immediately increase the pg count. The pg_num_min was only being set on existing pools and not on new pools.
Resolves #5091 
**Checklist:**
> Set pg_num_min on new rgw metadata pools

- pkg/operator/ceph/nfs/config.go
CACHEINODE has been deprecated in favor of MDCACHE
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/454929
https://github.com/nfs-ganesha/nfs-ganesha/commit/4f4d624ceb361e2ac05e9e304583f35832921790
Signed-off-by: Michael Fritch <mfritch@suse.com>
Resolves #
**Checklist:**
[test ceph]
> ceph: replace CACHEINODE with MDCACHE

- pkg/operator/ceph/cluster/controller.go
We must return `err` instead of nil so that we can fail the
orchestration properly.
Resolves https://github.com/rook/rook/issues/5498
**Checklist:**
[test ceph]
[test full]
**MASTER DOES NOT HAVE THE BUG SO PUSHING TO RELEASE BRANCH DIRECTLY.**
> ceph: fail for unsupported version

- pkg/operator/ceph/object/bucket/util.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/objectstore_test.go
- This PR is for rebasing #4683 with master. With controller run time changes, most of the changes in #4683 got redundant. Only change is waiting for all the object buckets to be deleted before removing the finalizer. 
- When deleting object store, reconciler will check if all the object buckets are cleaned up or not.
- If not, the reconcile will fail and keep on trying again. 
- Once the buckets are deleted, reconcile operation will succeed and continue to delete the object store.  
Resolves #4486
**Checklist:**
[test ceph]
> finalizer for OBC cleanup

- pkg/operator/ceph/cluster/cleanup.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
Two changes to improve the cluster cleanup:
1. During cluster deletion, the finalizer will not be removed until all the PVCs are removed. Since this could wait for a long time, as long as the deletion event is re-queued, we need to cancel the goroutine that is watching for cluster deletion so it can avoid running multiple goroutines as the event runs again and again.
1. When a cluster is requested for deletion there is no longer a reason to monitor the cluster health such as whether mons are in quorum, osds are up and in, or monitor the ceph status.
The cluster will wait potentially for a long time if the PVCs are not deleted by the admin, therefore we stop monitoring the cluster even before the finalizer is removed.
**Checklist:**
[test ceph]
> Stop monitoring a cluster immediately when deleted

- pkg/daemon/ceph/client/osd.go
- pkg/operator/ceph/cluster/cephstatus.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/cluster_external.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/osd/health.go
- pkg/operator/ceph/cluster/osd/health_test.go
The monitoring goroutines that check for mon and osd health, the ceph cluster status, and the bucket provisioner should only be started once for each cluster. Previous to this change
and since the controller runtime conversion the goroutines were being started again every time a reconcile was run. This means you could potentially have many goroutines monitoring the same thing.
A separate commit removes versioning info that is no longer needed since dropping mimic. 
**Checklist:**
[test ceph]
> Only run the cluster monitoring goroutines once

- pkg/daemon/ceph/client/filesystem.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/mds/mds.go
Ceph MDS deactivate is not a valid command for nautilus, changing it to use the new way, that means to scale down the MDS to 1 and then updating it with the new count.
Resolves #5278 
**Checklist:**
[test ceph]
> Ceph: Newer mechanism to scale MDS for Nautilus+

- tests/framework/clients/pool.go
- tests/integration/ceph_smoke_test.go
In Octopus 15.2.2 there is an rbd change that causes the rbd ls command to hang if there are not sufficient OSDs. The smoke suite just started hanging today since the 15.2.2 image was released. Therefore, the test that resizes the pool to replica 3 must resize back to 1 before cleaning up.
**Checklist:**
[test ceph]
[test full]
> Pool resize test hangs during cleanup with latest v15.2.2

- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/deviceset_test.go
In 1.3 we added support for the metadata pvcs, thus requiring the name to be set on the templates to differentiate between data and metadata. For backward compatibility we need to assume the template is for data if it is not set.
Also added a much needed unit test for generating the device set PVCs.
**Checklist:**
[test ceph]
> ceph: default the device set template name to data

- pkg/daemon/ceph/osd/daemon.go
The verbose args recently added are consistently causing the lv release to fail for LVM-based OSDs. The side effect is that the OSD then fails intermittently when starting since the LV is still being held by the prepare pod. This fix was missed as part of fixing related regressions in #5441. 
The error from the operator log shows as:
```
2020-05-21 19:04:21.508429 E | op-osd: orchestration for node ocs-deviceset-1-0-blt56 failed: &{OSDs:[] Status:failed PvcBackedOSD:true Message:failed
to release device from lvm: failed to deactivate LVM ceph-54699d63-dc4e-445c-b60b-c7d160be8275. output: Udev is running and DM_DISABLE_UDEV environment
variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.
Udev is running and …
```
> Revert verbose args for lv release

- pkg/operator/ceph/cluster/osd/spec.go
As of Nautilus Ceph auto-tunes its osd_memory_target on the fly so we don't need to force it.
ROok does not support Mimic anymore so this can be removed.
Resolves #
**Checklist:**
[test ceph]
> ceph: do not enforce osd-memory-target

- .mergify.yml
That rule posts a comment as soon as a pull request is in conflict, notifying the pull request author that they need to intervene!
[skip ci]
> mergify: ping user if PR has conflicts

- cluster/olm/ceph/generate-rook-csv.sh
A square bracket check on <shell_command> return status
will not work in an 'if' condition.
Signed-off-by: Arun Kumar Mohan <arun.iiird@gmail.com>
Resolves #
**Checklist:**
[skip tests]
> Ceph: A minor fix to 'generate-rook-csv.sh' script

- pkg/operator/ceph/cluster/crash/crash.go
The crash collector was missing the security context to properly run on
OCP, thus crashing when trying to post a crash dump.
Resolves #
**Checklist:**
[test ceph]
> ceph: add missing security context to crash collector

- build/makelib/helm.mk
Currently, Helm v2.5.1 is used, but this version is released in 2017
and a little outdated.
To use the latest version of helm v2.x.x would be beneficial
as we can use more useful Helm commands like `helm template`.
This commit updates Helm version and stop using `helm lint` with `--strict` option 
because Helm v2.16.7 does not allow to use undefined values in values.yaml 
and the Helm upstream is now stopping using the `--strict` option.
Resolves #
**Checklist:**
> ceph: update helm version

- pkg/apis/cassandra.rook.io/v1alpha1/types.go
The lack of the json tag required manifests to use 'Annotations' rather than 'annotations' to propogate annotations to the stateful set pods. This change will allow the software to function as documented.
Structs changed:
x ClusterSpec
x RackSpec
Resolves https://github.com/rook/rook/issues/5097
**Checklist:**
> cassandra: Adds json struct tags to fix cassandra annotations

- Jenkinsfile
Enabling buildDiscarder which keeps only the newest 200 builds
component: Enabling buildDiscarder which keeps only the newest 200 builds
Enabling buildDiscarder which keeps only the newest 200 builds
Resolves #
**Checklist:**
[test ceph]
[test full]
build: Enable the build discarder
Enabling buildDiscarder which keeps only the newest 200 builds
Signed-off-by: adam kraitman <akraitma@redhat.com>
DCO
> Enabling buildDiscarder

- CODE-OWNERS
There are two additions to the reviewers list that I would like to recommend. Both are actively contributing to the project, frequently responding to Slack questions, and helping investigate github issues:
- @satoru-takeuchi Contributed to several areas including Ceph OSD improvements.
- @Madhu-1 Owner for the CSI driver integration with the Ceph provider.
Also there was a typo in the yugabytedb owners list. They should be listed as `reviewers` instead of `approvers`.
Per the Rook governance, approval requires 2/3 majority vote of the steering committee. @jbw976 @dyusupov Your input is needed, thanks!
**Checklist:**
[skip ci]
> Governance: Added reviewers for Ceph

- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_multi_cluster_test.go
Fix the two regressions of the integration test
- Wrong cluster's health check
- OSD on PVC tests doesn't work
Nothing
**Checklist:**
- [o] Reviewed the developer guide …
> ceph: fix regressions in the integration tests

- Documentation/ceph-quickstart.md
It's better to tell users to know whether their devices can be used as OSD in the quick start guide.
Actually, some users want to know this kind of information.
https://rook-io.slack.com/archives/C46Q5UC05/p1589496154417600
Nothing
**Checklist:** …
> ceph: add the description how to know whether there is a filesystem on top of a device

- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/osd/health.go
- pkg/operator/ceph/cluster/osd/health_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/k8sutil/deployment.go
- pkg/operator/k8sutil/pod.go
Several improvements to handle node failure more gracefully:
- During the mon health check, if the mon is stuck terminating on a bad node, force delete the mon pod to allow it to start on another node if possible
- Reduce the OSD health check interval from 300s to 60s for faster response time in the event of node failure
- Misc osd logging improvements and refactor of the force deletion helper from osds
**Checklist:**
[test ceph]
> Handle node failure more gracefully

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Without the double quotes, operator is unable to parse the json output from the script
Signed-off-by: Arun Kumar Mohan <arun.iiird@gmail.com>
Resolves #
**Checklist:**
[skip ci]
> Ceph: Added the missing double quotes in JSON output

- ROADMAP.md
The roadmap was severely out of date from Rook v1.2. 
- The Ceph roadmap is updated to target 1.4 features and future features
- The structure of the doc allows for more flexibility in areas of focus that are not assigned to a release.
- Details for other storage providers can be submitted as separate PRs. Attempting to collect in a single PR has caused too much delay in the past.
**Checklist:**
[skip ci]
> core: update the Rook roadmap for 1.4 and beyond

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/osd/health.go
- pkg/operator/ceph/cluster/osd/health_test.go
- pkg/operator/k8sutil/pod.go
Backport changes to improve the node failure handling.
- The monitoring goroutines that check for mon and osd health, the ceph cluster status, and the bucket provisioner should be started immediately with the first reconcile after an operator restart instead of waiting until the first reconcile is completed. This way the cluster health will be monitored even during the first reconcile.
- During the mon health check, if the mon is stuck terminating on a bad node, force delete the mon pod to allow it to start on another node if possible
- Reduce the OSD health check interval from 300s to 60s for faster response time in the event of node failure
This is a manual backport due to conflicts with the controller runtime updates in master.
**Checklist:**
[test …
> Handle node failure more gracefully (bp #5556)

- Documentation/ceph-object-bucket-claim.md
- Documentation/ceph-object.md
- Documentation/development-flow.md
The OBC provisioner name changed recently to include the namespace as a prefix, but the docs were not updated.
Another minor fix is the whitespace on the list of commit prefixes that are allowed.
**Checklist:**
[skip ci]
> docs: update the obc provisioner name

- Documentation/ceph-object-bucket-claim.md
- Documentation/ceph-object.md
The OBC provisioner name changed recently to include the namespace
as a prefix, but the docs were not updated.
(cherry picked from commit 0d1c83c9c37b8ab5b7f744f28139dff90152411b)
Resolves #
**Checklist:**
**MANUAL BACKPORT OF https://github.com/rook/rook/pull/5565**
[skip ci]
> docs: update the obc provisioner name (bp #5565)

- pkg/operator/ceph/csi/cluster_config.go
- pkg/operator/ceph/csi/csi.go
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/spec_test.go
- pkg/operator/ceph/operator.go
The csi driver does not need to be started before the cluster is created. When the csi driver fails to load, neither should it prevent the cluster from being created. Therefore, we initialize the basic constructs in the csi driver that are required for cluster creation, then start the csi driver in a goroutine so the cluster creation can continue. If the csi driver fails (e.g. quay.io is down) or takes a long time to load, it will no longer affect cluster creation.
Also included is some other minor refactoring of the csi init code.
- Init the owner ref for the csi driver in one place instead of two, and pass the ownerRef param to the needed places
- Move a couple helper methods between the operator and csi packages 
- Remove obsolete code for removing the …
> Start csi driver in parallel of cluster configuration

- pkg/operator/ceph/csi/csi.go
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/spec_test.go
- pkg/operator/ceph/operator.go
The csi driver does not need to be started before the cluster is created. When the csi driver fails to load, neither should it prevent the cluster from being created. Therefore, we initialize the basic constructs in the csi driver that are required for cluster creation, then start the csi driver in a goroutine so the cluster creation can continue. If the csi driver fails or takes a long time to load, it will no longer affect cluster creation.
(cherry picked from commit 6c249e751b12425602351eae6b393da6973ccaef)
**Checklist:**
[test ceph]
> Start csi driver in parallel of cluster (bp #5568)

- pkg/operator/ceph/object/bucket/provisioner.go
Some external consumers of Rook-Ceph are using the
lib-bucket-provisioner operator which creates different CRDs for both
objectbuckets.objectbucket.io and objectbucketclaims.objectbucket.io.
They have the `additionalConfig` declared in their spec. Rook-Ceph does
not and thus ignores it.
For the OB creation to work, the `additionalConfig` must be acknowledged
by the operator and populate or initialize it if empty.
This is preventing the following error:
controller.go:190] error syncing 'default/ceph-retain-bucket-converged': error creating OB "": ObjectBucket.objectbucket.io "obc-default-ceph-retain-bucket-converged" is invalid: spec.endpoint.additionalConfig: Invalid value: "null": spec.endpoint.additionalConfig in body must be of type object: "null", …
> ceph: fix obc additionalConfig field

- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
Updated initializeBlockPVC method to add 
crushDeviceClass along with 
immediateExecuteArgs instead of
metadataArg. Also added unit tests for this method.
Closes: https://github.com/rook/rook/issues/3893
Resolves #
**Checklist:**
[test ceph]
> ceph: Updated initializeBlockPVC method and added unit tests.

- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/bucket/s3-handlers.go
When obc is deleted, the attached ceph user will be also removed
This will cause obc creation failure for the same bucket since user
was missing. With this patch the user will be retained revoking his permissions
Resolves #5510
**Checklist:**
[test ceph]
> obc: Do not delete user for retain policy if it is owner

- Jenkinsfile
If the PR is a draft, it's not ready for review and most likely the CI
pipeline should not run as the code might be broken in some places.
**Checklist:**
[skip ci]
> ci: do not run the pipeline if PR is draft

- pkg/operator/ceph/cluster/mon/node.go
- pkg/operator/ceph/cluster/mon/node_test.go
- pkg/operator/test/client.go
When the cluster is using HostNetworking, Rook was either picking up the
external or internal IP of the node. This resulted in mon endpoints have
public IP addresses. Those IP are not reachable from within the cluster
so OSD/CSI couldn't access the monitors from the configmap endpoint.
Also, exposing the cluster on a public network does not seem realistic,
so sticky with private/internal IP addresses is better.
Closes: https://github.com/rook/rook/issues/5495
Resolves https://github.com/rook/rook/issues/5495
**Checklist:**
[test ceph]
> ceph: do not use external node IP for mon endpoint

- pkg/operator/ceph/object/spec.go
Set podAntiAffinity to preferredDuringSchedulingIgnoredDuringExecution on rgw when cluster is not running in hostNetwork.
This will improve when possible the spread of rgw when possible
Resolves #5564
**Checklist:**
> ceph: fallback podAntiAffinity to preferredDuringSchedulingIgnoredDuringExecution on rgw

- Documentation/ceph-osd-mgmt.md
Removing a disk is not mandatory after the data in the corresponding OSD is moved to other OSDs.
It's better to just let users to know it's safe to remove the disk.
Nothing
**Checklist:** …
> ceph: fix the document of OSD management

- design/nfs/nfs.md
This commit rename nfs object kind with actually implemented name `NFSServer`
instead of `NetworkFileSystem`. This commit also fix some bad url.
Signed-off-by: Ahmad Nurus S. <prksu.sh@gmail.com>
**Checklist:**
[skip ci]
> design: rename nfs object kind

- cluster/olm/ceph/generate-rook-csv-templates.sh
- cluster/olm/ceph/generate-rook-csv.sh
- images/ceph/Makefile
Newer versions of operator-sdk (since 0.15.0, released Jan 2020) have a different command line to generate CSV. Make changes to the script generating the CSV so that it works with these new versions.
**Checklist:**
[skip tests]
> chore: Make csv generation work with operator-sdk 0.15.0 and later, remove support for previous versions.

- pkg/daemon/ceph/client/upgrade.go
If the cluster has 3 OSDs, during the upgrade when the OSD restarts it
will temporarily disappear from the "ceph versions" list so we need
a more robust way to list the number of OSDs and always returns the total
number of OSDs.
Resolves https://github.com/rook/rook/issues/5521
**Checklist:**
[test ceph]
> ceph: fix osd number detection on upgrade

- pkg/operator/ceph/controller/spec.go
- pkg/operator/ceph/controller/spec_test.go
When the cluster is loaded and we restart an OSD, it will need some time
to respond to socket calls, basically more to be ready.
Increasing the initialDelaySeconds of the liveness probe fixes that
issue. For OSD, it waits for 45 sec, where other daemons 10 sec.
Closes: https://github.com/rook/rook/issues/5492
Resolves https://github.com/rook/rook/issues/5492
**Checklist:**
[test ceph]
> ceph: increase liveness probe start delay on OSD

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/service.go
- pkg/operator/ceph/cluster/mon/spec.go
Trying to integrate rook-ceph with istio, but getting service port name errors as referenced here: https://kiali.io/documentation/validations/#_kia0601_port_name_must_follow_protocol_suffix_form
Understanding that istio isn't the only game in town, I think that it would be best to make the port name configurable at cluster creation. 
Not sure what all needs to be changed in the source, but here are my starting edits. Assistance would be appreciated. 
Resolves #5587 
**Checklist:**
[test ceph]
> Configurable Service Port Names

- pkg/apis/rook.io/v1/types.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/deviceset_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/status.go
When the PVC template increases in size for the storageClassDeviceSet in the cluster CR, we need to increase the size of the PVC and restart the OSD. The OSD is restarted by changing a variable on the pod spec that indicates the desired size of the OSD.
@paalkr will plan on getting this in v1.3.6...
Resolves #5309 
**Checklist:**
[test ceph]
> Increase OSD size when the template size increases

- tests/framework/installer/ceph_installer.go
During checking [my pull request test result](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/PR-5573/runs/12/nodes/60/steps/129/log/?start=0), I noticed that the error message is not appropriate.
```
...
--- FAIL: TestCephFlexSuite (517.73s)
...
--- PASS: TestCephFlexSuite/TestFileSystem (105.79s)
ceph_installer.go:490: 
Error Trace:	ceph_installer.go:490
ceph_installer.go:459
ceph_base_deploy_test.go:192
ceph_flex_test.go:237
suite.go:106
suite.go:139
ceph_flex_test.go:64
Error:      	pool %q still exists
Test:       	TestCephFlexSuite
Messages:   	block-pool-rwo
```
Therefore, I fixed the error message. …
> ceph: fix error message

- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/bucket/rgw-handlers.go
When obc creation fails in Grant() or Provision() the resources such as rgw user or bucket
created while provisioning need to remove.
Resolves #
**Checklist:**
> ceph: obc clean up resources incase of failure

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- pkg/apis/rook.io/v1/types.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/deviceset_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
Support schedulerName in storageClassDeviceSets to use another scheduler for OSD pod placement.
This will enable more flexible pod placement.
Resolves #5536
**Checklist:**
> ceph: add schedulerName property to storageClassDeviceSet

- Makefile
Currently olm will be removed as part of clean command, but it cleans up
all the dependent modules as well
Resolves #
**Checklist:**
> build: add a seperate make command for cleaning olm files

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
The script wasn't allowing IPs like 192.168.0.2, 0 has part of the
subnet is valid.
Resolves #
**Checklist:**
[skip ci]
> ceph: fix script IP parsing

- pkg/daemon/discover/discover.go
Fix the info log statement to log the discovered devices as their string
representation instead of pointers.
This uses a loop to generate the sprintf output for each device and then
strings.Join to join the outputs.
Resolves #5625
Resolves #
**Checklist:**
> discover: fix info log for discovered devices

- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cmd/rook/ceph/operator.go
- cmd/rook/rook/rook.go
- images/ceph/Makefile
- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/object/bucket.go
- tests/integration/ceph_base_object_test.go
Since 1.3 will support both Nautilus and Octopus, let's use Octopus for
the base image. Newer images have retro-compatibility with older Ceph
versions.
Closes: https://github.com/rook/rook/issues/1765 and https://github.com/rook/rook/issues/5666
Resolves https://github.com/rook/rook/issues/1765
**Checklist:**
[test ceph]
[test full]
> ceph: use octopus base image

- pkg/operator/ceph/cluster/mon/mon_test.go
- pkg/operator/ceph/cluster/mon/util.go
When the operator loads the mons and checks for a valid maxMonId the check of the id against the currently running mons was outdated from legacy mon ids. The check now has to parse the new id which is just the letter instead of having a number from legacy mon ids. Without this fix, the maxMonId would stay incorrect if it was somehow corrupted.
Resolves #5644 
**Checklist:**
> ceph: Update maxMonId if incorrect

- pkg/operator/ceph/cluster/cluster_external.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/cluster/rbd/controller_test.go
- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/file/controller_test.go
- pkg/operator/ceph/nfs/controller_test.go
- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/bucket/rgw-handlers.go
- pkg/operator/ceph/object/controller_test.go
- pkg/operator/ceph/object/user.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/object/user/controller_test.go
- pkg/operator/ceph/pool/controller_test.go
- pkg/util/exec/exec.go
Now, the object store user is capable of creating s3 users on an
external Ceph cluster.
Resolves #
**Checklist:**
> ceph: add external support for object store user

- pkg/operator/ceph/cluster/crash/keyring.go
When I was debugging, I noticed that [`CreateCrashCollectorSecret` function](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/crash/keyring.go#L40) have `clusterName` as its second argument, but the passed value is the namespace ([this](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/cluster_external.go#L129) and [this](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/cluster.go#L411)) and the `clusterName`  is also used as the namespace in the functions which gets the value ([this](https://github.com/rook/rook/blob/master/pkg/operator/ceph/config/keyring/store.go#L49) and [this](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/crash/keyring.go#L73)).
Therefore, this commit fixes the argument name as `namespace`. …
> ceph: fix an argument name

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Added a new critical alert CephClusterReadOnly which notifies when the cluster becomes read-only.
Updated the warning and critical alert to accomodate the new alert.
Resolves #
**Checklist:**
[skip ci]
> ceph: Added CephClusterReadOnly alert and updated utilization alerts.

- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
Since partition's DevLinks are empty in osd-prepare-pod, the device specification with non-kname, for example devicePathFilter, doesn't work.
Resolves #5504 
**Checklist:**
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-stora …
> ceph: fix ignoring device specification with non-kname

- Documentation/ceph-cluster-crd.md
There is a wrong link to the monitoring document.
Nothing
**Checklist:** …
> ceph: fix a wrong link

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.2.go
The tuning parameter of slow devices is defined as "tuneDeviceClass". However, it's written in the document as "tuneSlowDeviceClass".
Nothing
**Checklist:**
- …
> ceph: fix the wrong document of tuneDeviceClass

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Added warning and critical alerts for all the PVC's created by rook-ceph provisioners. This is required to notify a admin timely to check on PVC utilization and take a required action to prevent workloads from failing.
Closes: BZ1849723
Resolves #
**Checklist:**
[skip ci]
> ceph: added PVC utilization alerts

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Added warning and critical alerts for all the PVC's created by rook-ceph provisioners. This is required to notify a admin timely to check on PVC utilization and take a required action to prevent workloads from failing.
Closes: BZ1849717
Resolves #
**Checklist:**
[skip ci]
> ceph: updated PVC utilization alerts

- Documentation/admission-controller-usage.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/charts/rook-ceph/templates/clusterrolebinding.yaml
- cluster/charts/rook-ceph/templates/serviceaccount.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/config-admission-controller.sh
- cmd/rook/ceph/admission.go
- cmd/rook/ceph/ceph.go
- cmd/rook/main.go
- pkg/daemon/admission/controller.go
- pkg/daemon/admission/server.go
- pkg/daemon/admission/tlsutil.go
- pkg/operator/ceph/admission.go
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/util.go
- pkg/operator/ceph/operator.go
- pkg/operator/ceph/webhook.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_base_deploy_test.go
- tests/scripts/deploy_admission_controller.sh
- tests/scripts/deploy_admission_controller_test.sh
- tests/scripts/webhook-config.yaml
- tests/scripts/webhook-create-signed-cert.sh
- tests/scripts/webhook-patch-ca-bundle.sh
Adds various scripts and code changes to deploy admission controllers alongside rook. 
**What are admission controllers**
Admission controllers help in validating the CRDs at native kubernetes  level, accepting or rejecting an api request based on our custom criteria
For example, The PR here attempts to provide solution for one of the issues mentioned in  https://github.com/rook/rook/issues/4819
**Cannot change the dataDirHostPath after initial creation**
Our webhooks have the logic defined in them to to continuously check if an api request is an update for an existing ceph cluster and validates if the dataDirHostPath has been changed or not. 
If it has been changed from initial creation, it will reject the request and throw the below error
`for: …
> ceph: Adding support for admission controllers

- pkg/util/exec/exec.go
The previous code was overriding the content of `out`, now we just
return after the error.
Resolves #
**Checklist:**
> ceph: fix exec output

- pkg/operator/ceph/cluster/mon/health.go
Two improvements to mon failover:
- If the mon is backed by a pvc, ensure the pvc is deleted when the mon is failed over. The pvc was being left in a bound state even though it will no longer be used in the cluster.
- During mon failover if the mon fails to be removed, the new mon config was not being saved. The mon removal anyway is not retried if it fails, so it should make a best effort to remove all the resources related to the mon, and then always update the mon config after the failover.
Resolves #5644 
**Checklist:**
> ceph: During mon failover remove the backing pvc

- Documentation/ceph-object-store-crd.md
- cluster/examples/kubernetes/ceph/rgw-external.yaml
Explaining about port and target port in rgw-external.yaml. Also distinguishing internal port used by rgw daemon with service port given in object store crd
Resolves #
**Checklist:**
[skip ci]
> doc: Update port information for object store

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Backport PR for #5682 
Updated warning and critical alerts for all the PVC's created by rook-ceph provisioners. Added the recommendation to expand the PVCs.
Closes: BZ1849717
Resolves #
**Checklist:**
[skip ci]
> ceph: updated PVC utilizaztion alerts

- pkg/operator/ceph/cluster/mon/mon.go
The stuck mons were only being force deleted in the mon health checker. After an operator restart, the health check may not be executed for 20 minutes until after the timeout during the main reconcile which is holding onto a lock for mon reconcile. Now the stuck mon will be deleted during the reconcile as well.
**Checklist:**
> ceph: Force delete stuck mons in every reconcile instead of only in the health check

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- tests/framework/installer/ceph_manifests.go
The tuning parameter of slow device is defined as "tuneDeviceClass". However, it's written in the document as "tuneSlowDeviceClass".
This is the backport of #5691 
Nothing
**Checklist:** …
> Backport v1.3: ceph fix the wrong document of tune device class

- Documentation/ceph-object-bucket-claim.md
update the object bucket claim doc with ROOK_OBC_WATCH_OPERATOR_NAMESPACE option
Resolves # 5675
**Checklist:**
> docs: update ROOK_OBC_WATCH_OPERATOR_NAMESPACE in obc doc

- PendingReleaseNotes.md
- images/cassandra/Dockerfile
Due to CVEs in the alpine:3.8, we need to update the base image.
[test cassandra]
Resolves #
**Checklist:**
> cassandra: update base image to alpine:3.12

- tests/scripts/kubeadm-install.sh
Experimenting with the CI script to resolve the issue with kubeadm on older versions than k8s 1.18 where the cluster is failing to start.
Resolves #5711 
**Checklist:**
// run minimal tests just so the integration tests are triggered
[test nfs]
> CI: Stop downgrading the kubeadm components for the integration tests

- Documentation/ceph-cluster-crd.md
This functionality was merged in with #3696, but not documented. [skip ci]
> ceph: document the `deviceClass` setting for OSDs

- cluster/examples/kubernetes/ceph/upgrade-from-v1.3-crds.yaml
Adding object store crds related to realm, zone, zonegroup to upgrade-from-v1.3-crds
Resolves #
**Checklist:**
[skip ci]
> ceph: adding missing ceph object crds in upgrade-from-v1.3-crds

- tests/scripts/kubeadm-install.sh
kubelet in aws_1.11.x test requires kubernetes-cni 0.7.5.
Nothing.
**Checklist:** …
> tests: fix aws_1.11.x test failure

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/ceph/ceph-cluster-cleanup.md
- images/ceph/Makefile
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/cluster_external_test.go
- pkg/operator/ceph/cluster/mgr/dashboard_test.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/rbd/spec_test.go
- pkg/operator/ceph/nfs/spec_test.go
- pkg/operator/ceph/object/spec_test.go
- tests/framework/installer/ceph_installer.go
- tests/scripts/k8s-vagrant-multi-node.sh
- tests/scripts/minikube.sh
Update the base operator image and cluster examples to use the latest Octopus release v15.2.4. Also cleanup some old examples and unit tests that were still based on mimic.
**Checklist:**
> ceph: Update master to the latest Octopus release v15.2.4

- cluster/examples/kubernetes/ceph/filesystem.yaml
The target_size_ratio moved under the parameters element of the pool settings. While the target size ratio is still supported under the previous location for backward compatibility, the example is preferred under parameters.
Resolves #5742 
**Checklist:**
[skip ci]
> ceph: remove legacy target_size_ratio example

- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/config/defaults.go
- pkg/operator/ceph/controller/spec.go
The OSD daemon has been missing critical flags for logging to stderr where k8s can capture the logs. Without the --log-to-stderr=true, all the OSD logging was essentially lost until now.
Resolves #5744 
**Checklist:**
[test full]
> ceph: Capture logging from the OSD daemons

- cluster/examples/kubernetes/ceph/operator.yaml
Fix an ambiguous comment of CSI_FORCE_CEPHFS_KERNEL_CLIENT flag in operator.yaml.
Now it delivers what the flag does and which problem can be incurred more clearly.
Resolves #
**Checklist:**
[skip-ci]
> ceph: fix cephfs kernel comment in operator

- pkg/operator/ceph/csi/csi.go
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/spec_test.go
- pkg/operator/ceph/operator.go
- pkg/operator/k8sutil/service.go
- pkg/operator/k8sutil/statefulset.go
remove csi drivers when drivers
are up and the default setting
changed to false and there is no active
mounts.
Resolves #4490
**Checklist:**
> ceph: remove csi drivers when disable 

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.2-crds.yaml
Some CRDs definitions were missing, rending some CRD unusable. Now if
someone upgrades from 1.2, all CRDs will work as expected.
Closes: https://github.com/rook/rook/issues/5742
Resolves https://github.com/rook/rook/issues/5742
**Checklist:**
> ceph: resync crds when update from 1.2

- Documentation/ceph-block.md
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
- cluster/examples/kubernetes/ceph/flex/storageclass-ec.yaml
- cluster/examples/kubernetes/ceph/flex/storageclass-test.yaml
- cluster/examples/kubernetes/ceph/flex/storageclass.yaml
When mounting a ceph volume, xfs may cause issues with potential deadlocks if the volume is on the same node as the OSDs. To avoid this issue the default recommendation is ext4. This default had already been changed long ago in the csi example yamls, but the docs were not updated yet.
**Checklist:**
> docs: Remove references to xfs for ceph volumes

- Documentation/ceph-cluster-crd.md
Clarify in the docs that changing networking modes after a Cpeh cluster
has been deployed is not supported and can result in a nonfunctional
cluster.
Resolves #
**Checklist:**
[skip ci]
> docs: ceph: add no support for changing networking

- PendingReleaseNotes.md
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/controller_test.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/rgw_test.go
- pkg/operator/ceph/object/status.go
- pkg/operator/ceph/object/status_test.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/object/user/controller_test.go
- tests/integration/ceph_base_object_test.go
Now, when an S3 user gets created, Rook will add the S3 endpoint to the
Secret along with the credentials.
**Checklist:**
[skip ci]
> ceph: add s3 endpoint to the rgw user cr

- cluster/examples/kubernetes/ceph/cluster.yaml
Adjust the comment for `cephVersion:allowUnsupported` in the
`cluster.yaml` manifest to correctly document that Nautilus and
Octopus are supported (not Mimic and Nautilus).
Resolves #
**Checklist:**
[skip ci]
> ceph: fix manifest ceph version support comment

- cluster/examples/kubernetes/ceph/cluster.yaml
Adjust the comment for `cephVersion:allowUnsupported` in the
`cluster.yaml` manifest to correctly document that Nautilus and
Octopus are supported (not Mimic and Nautilus).
(cherry picked from commit b8aea86cedf1a7c3a299950f2792f10c153e8e46)
[skip ci]
Resolves #
**Checklist:**
> backport #5808: ceph: fix manifest ceph version support comment

- Documentation/ceph-cluster-crd.md
Although the document describes we can't set Pod{,Anti}Affinity to mon's placement, the current implementation permits us to do so.
Nothing
**Checklist:**
- …
> ceph: remove an outdated document of mon placement

- pkg/operator/ceph/object/bucket/provisioner.go
The output of the bucket policy change should not be logged in case there is sensitive information in the output.
Resolves #4570 
**Checklist:**
[skip ci]
> ceph: Skip logging output of bucket policy change

- images/ceph/toolbox.sh
When hostname has hypen and/or numbers, the mon endpoints are incorrectly split and can point
to invalid monitor names inside toolbox, Add fix to split the hostname/ip that can include
hypen, underscore or numbers.
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>
Resolves #
**Checklist:**
> ceph: Fix toolbox when mon hosts can contain numbers and hype

- pkg/apis/ceph.rook.io/v1/types.go
- pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/object/user/controller_test.go
adding secret name in cephobjectstoreUser
status field in order to programmatically
retrieve the name of the secret generated
by the cephobjectstoreuser crd.
Resolves #5684
**Checklist:**
> ceph: report secret in cephobjectstoreuser status field 

- pkg/apis/ceph.rook.io/v1/validate_resources_test.go
- pkg/operator/ceph/controller/predicate.go
Most of the CRs expect CephCluster and CephBlockPool were not
reconciling on updates. The predicate must return true on CR diff.
**Checklist:**
> ceph: fix CRs not reconciling on updates

- Jenkinsfile
- tests/framework/installer/environment.go
- tests/integration/ceph_mgr_test.go
- The OSD creation has been fixed in Ceph master, therefore we can reenable the Ceph mgr test that runs against master.
- The mgr integration test was running unexpectedly in master due to a change in the env vars in Jenkins. Now the test will only be enabled in PRs again as expected.
**Checklist:**
[test ceph]
> Re-enable the Ceph Mgr integration test that runs against Ceph master

- Documentation/ceph-cluster-crd.md
- pkg/operator/ceph/cluster/version.go
Signed-off-by: Hiroshi Muraoka <h.muraoka714@gmail.com>
This PR updates `detect-version` not to have the same placement with `mon`'s.
I think that there are 4 options as written below to fix the issue #5810 , and I chose 1 because it seems to provide a necessary and sufficient functionality with users.
1. Add only the `all` placement to `detect-version` (NOT merge `mon` with `all`).
2. Define the `detect-version` field under the `placement` in CRD and merge `detect-version` with `all`.
This might need many changes but I am not sure many users will require the field because `detect-version` is a very short-lived pod low on resources.
3. Merge `mon` with `all` as rook does currently, but ignore just `PodAntiAffinity`.
IMO, 2 is better than 3 because 3 might …
> ceph: update detect-version's placement to ignore mon's PodAntiAffinity

- Documentation/ceph-cluster-crd.md
- pkg/operator/ceph/cluster/cluster.go
When a PodAntiAffinity is set to mon, detect-version may not be scheduled because detect-version has the same PodAntiAffinity with mon. The anti-affinity will no longer be applied to the detect version job.
Signed-off-by: Hiroshi Muraoka <h.muraoka714@gmail.com>
(cherry picked from commit e2b1a2230df871b4feaf3ac22dc7775e9804539a)
FYI @tapih 
Resolves #5810 
**Checklist:**
> ceph: Ignore PodAntiAffinity for detect-version placement (bp #5820)

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-monitoring.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules-external.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/apis/ceph.rook.io/v1/validate_clusters.go
- pkg/operator/ceph/cluster/cluster_external.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
- pkg/operator/ceph/object/spec.go
We can now connect an external Prometheus exporter to Rook to collect
metrics and generate alerts from Prometheus.
Just enable this in the `CephCluster` CR:
```
spec:
external:
enable: true
monitoring:
enabled: true
externalMgrEndpoints:
- ip: 192.168.39.182
```
Closes: https://github.com/rook/rook/issues/5516
Resolves https://github.com/rook/rook/issues/5516
**Checklist:**
> ceph: add external prometheus endpoint

- cluster/examples/kubernetes/ceph/filesystem.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- cluster/examples/kubernetes/ceph/pool.yaml
The pool parameters must be strings. In the pool examples now we add quotes around the sample target_size_ratio to avoid deserialization errors.
Resolves: #5848 
**Checklist:**
[skip ci]
> ceph: Pool parameters must be strings

- PendingReleaseNotes.md
- cmd/rook/ceph/osd.go
- cmd/rook/ceph/osd_test.go
- pkg/operator/ceph/cluster/osd/config/config.go
- pkg/operator/ceph/cluster/osd/spec.go
Pass desired devices to the OSD provisioning container by
JSON-marshalling/-unmarshalling a disk ID with StorageConfig settings.
This will allow disks to be specified that contain special characters.
Notably, this will support /dev/disk/by-path/pci-HHHH:HH:HH.H devices
that were unsupported previously due to the format which separated
devices from params with colons (:).
Fixes #5056
Fixes #5535
Resolves #
**Checklist:**
[test ceph]
> ceph: support device names with special chars

- Documentation/ceph-upgrade.md
- PendingReleaseNotes.md
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/nsenter.go
- pkg/daemon/ceph/osd/nsenter_test.go
- pkg/operator/ceph/cluster/osd/spec.go
A long-standing issue that was only solved via a documentation note. Now,
during the prepare pod instantiation, we check for the presence of the
lvm binary on the host. Success will indicate that we can bootstrap
OSDs where failure will refuse to prepare the OSD.
Closes: https://github.com/rook/rook/issues/5627
Resolves https://github.com/rook/rook/issues/5627
**Checklist:**
[skip ci]
> ceph: fail prepare pod if lvm2 pkg is missing

- tests/framework/installer/ceph_installer.go
Signed-off-by: Vineet Badrinath <vbadrina@redhat.com>
Disables admission controller tests for k8s version less than 1.15.
Resolves #5841
> ceph:  disables admission controller tests for k8 v1.14 and older.

- PendingReleaseNotes.md
- images/cassandra/Dockerfile
The Cassandra sidecar uses the Jolokia javaagent to expose a REST API of
Cassandra's administrative interface, which is normally only exposed via
JMX, a Java-only RPC protocol. Update the Jolokia javaagent to a newer
version, containing new features and security bug fixes.
Issue was reported via mailing list. cc @galexrt 
**Checklist:**
[test cassandra]
> cassandra: Update Jolokia lib in Cassandra sidecar image

- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/cluster/mon/config_test.go
Whether we run an external cluster or not we need to load the
appropriate clusterInfo.
**Checklist:**
> ceph: re-hydrate clusterInfo for external mode

- pkg/daemon/ceph/client/status.go
- pkg/operator/ceph/cluster/cephstatus.go
If the healthcheck goroutine cannot check for the ceph status/times out
(if the mons are not in quorum) this should still be reflected in the
CRD status field.
Example:
```
status:
ceph:
details:
error:
message: 'failed to get status. . timed out: exit status 1'
severity: Urgent
health: HEALTH_ERR
lastChanged: "2020-07-20T14:11:05Z"
lastChecked: "2020-07-20T14:11:05Z"
previousHealth: HEALTH_WARN
```
Resolves #
**Checklist:**
> ceph: report error on timeout

- pkg/daemon/ceph/client/filesystem.go
- pkg/operator/ceph/file/filesystem.go
Ceph The operator starts an infinite loop for deleting Filesystem, this happens when it tries to delete the filesystem when it doesn't exist. The filesystem should only be deleted when it exists.
Resolves #5783 
**Checklist:**
> Ceph: Delete Filesystem only when it exists

- cluster/charts/rook-ceph/templates/clusterrole.yaml
When defining `.Values.agent` without a `.Values.agent.mountSecurityMode` key, the Helm chart now defaults to an empty string, so that it may be compared to `"Any"` using the `ne` function.
Resolves #5858
**Checklist:**
> ceph: Default .Values.agent.mountSecurityMode to empty string.

- pkg/daemon/ceph/client/mon.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/mon.go
The user creds should not be passed to the ceph helper methods since the clusterInfo already has the needed context. Removing a final reference that was missed in the refactor.
**Checklist:**
> ceph: Additional clusterInfo cleanup for user creds

- Documentation/ceph-pool-crd.md
`requireSafeReplicaSize` is now a sub-param of `replicated` and not of
Ceph's `parameters`.
[skip ci]
Resolves #
**Checklist:**
> docs: fix placement of param in Ceph Pool CRD

- Documentation/ceph-disaster-recovery.md
In the latest version of rook-ceph, disaster recovery does not work properly with the following command. Therefore, the command was updated to the latest command.
Changed the monmap to add 3300, the port of messenger v2.
Resolves #5662, #5649 
**Checklist:**
[skip ci]
> ceph: change command to add 3300 port for monmap

- pkg/daemon/ceph/client/info.go
- pkg/operator/edgefs/cluster/prepare/prepare.go
- pkg/operator/edgefs/cluster/utils.go
- pkg/operator/edgefs/isgw/isgw.go
- pkg/operator/k8sutil/prometheus.go
Several changes to follow up from the security review:
- EdgeFS: Error checking for ineffectual assignments
- EdgeFS: Simplify string formatting for labels
- Ceph: remove an obsolete log method that was unnecessarily formatting in json format
Resolves #4564
**Checklist:**
> Error checking for EdgeFS related to the security review

- Documentation/ceph-cluster-crd.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cmd/rook/ceph/cleanup.go
- pkg/apis/ceph.rook.io/v1/cleanup.go
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/daemon/ceph/cleanup/disk.go
- pkg/daemon/ceph/cleanup/disk_test.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/cleanup.go
- pkg/operator/ceph/object/controller.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_flex_test.go
Now, we can not only cleanup monitor data, logs and crashes but the
disks too. As part of the cleanupPolicy CR spec, we have a new setting
called sanitizeDisk which holds more details:
* sanitizeDiskConfirmation: the confirmation message to sanitize disks,
use "yes-really-sanitize-disks" to confirm
* sanitizeMethod: indicates if the entire disk should be sanitized or simply ceph's metadata.
Possible choices are 'data' or 'metadata' (default)
* sanitizeDataSource: indicate where to get random bytes from to write on the disk.
Possible choices are 'zero' (default), 'random' or 'urandom'.
Using random sources will consume entropy from the system and will take much more time then the zero source
* sanitizeIteration: overwrite N times instead of the default (1). …
> ceph: enhancement disk sanitize options

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- tests/framework/installer/ceph_csi_templates.go
metadatastore and mountcache are required for PVC created by cephcsi v1.0.0 as rook doesn't use ceph-csi v1.+ version
we can remove this flag. Removing these flags doesn't affect the functionality of anything.
more info on https://github.com/ceph/ceph-csi/pull/1226 and https://github.com/ceph/ceph-csi/issues/882
Resolves #
**Checklist:**
[test ceph]
> ceph: remove unwanted metadatastore and mountcache flag

- pkg/operator/ceph/cluster/mon/health.go
At startup there is a race condition between the goroutine checking for mon health and the first reconcile of the mons. There is a lock that ensures only one of them will check the mon health at a time. 
The issue is that if the wrong one gets there first, it will not have the desired mon count initialized from the cluster CR as expected and the healther checker will use a desired mon count of 0. The desired count of 0 leads the health checker to remove a mon since there are extra mons. Only one mon is allowed to be removed at a time, and adjusting to fewer than two mons is disallowed once there are at least two mons.
After the health checker is completed, the main reconcile of the mons will proceed with the correct desired mon count of 3 and attempt to …
> ceph: Avoid removing a healthy mon unexpectedly when the operator restarts

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
- pkg/operator/ceph/cluster/mon/node_test.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/mon/spec_test.go
- pkg/operator/ceph/cluster/monitoring.go
The mon was starting with a partial spec. There was a race condition that was causing incorrect initialization in the health check goroutine that could remove a mon upon operator restart. Now the mon will be properly initialized with the full spec.
The side effect of this issue was that when the operator was restarted, it could mistakenly think the desired number of mons was 0 and remove a healthy mon. This was also seen to cause instability in the upgrade integration tests. Evidence of can be seen with the message in the operator log:
```
op-mon: removing an extra mon. currently 3 are in quorum and only 0 are desired
```
This is a more complete fix than what was done in the 1.3 branch with #5868.
This fix also removes some duplication in fields that are …
> ceph: Require the cluster spec for initialization of the mons to avoid removing a healthy mon

- pkg/apis/ceph.rook.io/v1/types.go
- pkg/daemon/ceph/client/deviceclass.go
- pkg/operator/ceph/cluster/osd/health.go
- pkg/operator/ceph/cluster/osd/health_test.go
Signed-off-by: kesavan <kvellalo@redhat.com>
The admin needs to start the toolbox and run a command such as ceph osd tree to see the device classes for each OSD. This PR simplifies it by storing the deviceclass info in the CephCluster CR status
Resolves #5754
**CephCluster CR status** 
```
Status:
Ceph:
Health:        HEALTH_OK
Last Checked:  2020-07-10T11:42:30Z
Storage:
Device Classes:
Name:  hdd
Version:
Image:    ceph/ceph:v15.2.3
Version:  15.2.3-0
```
**Checklist:**
> ceph: Adding deviceClasses info to CephCluster CR

- cluster/examples/kubernetes/ceph/object.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
- pkg/operator/ceph/object/health.go
- pkg/operator/ceph/object/spec.go
this commit allows us to disable livenessprobe for
cephobjectstore crd.
Resolves #5807
**Checklist:**
> ceph: ability to configure livenessprobe for cephobjectstore crd

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/import-external-cluster.sh
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/apis/ceph.rook.io/v1/validate_clusters.go
- pkg/operator/ceph/cluster/cephstatus.go
- pkg/operator/ceph/cluster/cephstatus_test.go
- pkg/operator/ceph/cluster/cluster_external.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/monitoring.go
- pkg/operator/ceph/config/conditions.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/controller_test.go
- pkg/operator/ceph/object/health.go
- pkg/operator/ceph/object/status.go
- tests/framework/clients/block.go
- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_base_object_test.go
- tests/integration/ceph_flex_test.go
Instead of setting the Phase of the CR once the reconcile is done, let's actually set in from the healthcheck so it is more accurate.
Resolves https://github.com/rook/rook/issues/5249 and https://github.com/rook/rook/issues/5840
**Checklist:**
> ceph: let the healthcheck set the status phase

- Documentation/cassandra-cluster-crd.md
- cluster/examples/kubernetes/cassandra/cluster.yaml
- tests/framework/installer/cassandra_manifests.go
This also updates the cassandra version in the tests.
This is to provide safe and secure defaults to users running Cassandra.
Resolves #
**Checklist:**
[test cassandra]
> cassandra: use latest 3.11.6 version in examples

- pkg/operator/ceph/csi/spec.go
Added provisioner toleration to the csi version check job, so that we can schedule the csi version check on the node where the nodes are tainted.
Resolves #5879
**Checklist:**
[test ceph]
> ceph: add provisioner toleration for csi version check job

- pkg/operator/ceph/csi/csi.go
- pkg/operator/ceph/csi/spec.go
If the AllowUnsupported flag is set to true we should not check the csi version as it will be kind of no-op as even in case of failure we continue. if we disable the version check, in this case, the deployment will be a little faster as we don't wait for version check to complete to start CSI pods.
Resolves #
**Checklist:**
[test ceph]
> ceph: skip csi version detect if allowunsupported is set

- cmd/rook/rook/rook.go
- pkg/daemon/ceph/agent/flexvolume/server.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/util/copybins.go
- pkg/util/exec/exec.go
To ensure a file handle is closed, we defer the close command so it is guaranteed to run when the method returns. The closing of the file handle is not going to fail in our usage since we aren't using the SetDeadline on the files that would cancel a request and return an error.
Resolves (partially) #3765 
**Checklist:**
> Suppress gosec errors for closing files

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
As 'rgw_endpoint' argument itself is optional, making it's check / validation also optional
Resolves #
**Checklist:**
[skip ci]
> ceph: make 'rgw_endpoint' check/validation also optional

- cmd/rookflex/cmd/expander.go
- cmd/rookflex/cmd/unmount.go
- pkg/daemon/ceph/agent/flexvolume/server.go
- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/webhook.go
- pkg/operator/nfs/server.go
- pkg/util/exec/exec.go
this commit suppress the gosec errors for
g204: Audit use of command execution
g304: File path provided as taint input
g101: Look for hard coded credentials
after this commit:-
`$GOPATH/bin/gosec -include=G204,G304,G101 cmd/... -severity=medium`
```
Summary:
Files: 35
Lines: 2955
Nosec: 3
Issues: 0
```
`$GOPATH/bin/gosec -include=G204,G304,G101 pkg/... -severity=medium`
```
Summary:
Files: 519
Lines: 82514
Nosec: 17
Issues: 0
```
Resolves #3765
**Checklist:**
> ceph: suppress gosec errors for g204,g304,g101

- .github/stale.yml
The stalebot has not been closing PRs that are stale. Reducing the timeout from 6 months to 3 months.
**Checklist:**
[skip ci]
> ci: Reduce the PR stale time to 90 days

- cluster/examples/kubernetes/ceph/cluster-test.yaml
In test environments the default pool size is set to 1, so there is no
redundancy. This causes recent Ceph versions to complain with
HEALTH_WARN as POOL_NO_REDUNDANCY get set.
By disabling the mon_warn_on_pool_no_redundancy option in ceph.conf, the
warning is not reported and the cluster is marked HEALTHY.
This resolves difficulties with deploying recent rook/ceph version for testing ceph-csi.
**Checklist:**
[skip ci]
> ceph: do not warn about no redundancy in test cluster

- Jenkinsfile
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_base_deploy_test.go
- tests/integration/nfs_test.go
The CI in the release branch should run back to k8s v1.11 until we officially remove support for that version.
PRs in the release branch will not run the mgr test either, which is only intended to run in master PRs.
**Checklist:**
> ci: Enable the builds to run back to 1.11

- cmd/rook/rook/rook.go
- pkg/daemon/ceph/agent/flexvolume/server.go
- pkg/daemon/ceph/util/util.go
- pkg/operator/cassandra/controller/util/util.go
- pkg/operator/ceph/object/bucket/util.go
- pkg/operator/edgefs/isgw/isgw.go
- pkg/util/exec/exec.go
- pkg/util/file.go
a few of the gosec errors were left. like
G109: Potential Integer overflow made by strconv.Atoi result conversion to int16/32
(suppressing G109 )
G302: Poor file permissions used with chmod
G306: Poor file permissions used when writing to a new file
G307: Deferring a method which returns an error (suppress G307)
G404:  Insecure random number source (rand) 
so this commit will resolve all the above gosec errors.
Resolves #
**Checklist:**
> ceph: handling all the gosec errors

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.3-apply.yaml
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.2.go
- tests/integration/ceph_upgrade_test.go
updated the cluster role of the rook operator to delete the csidrivers object when csi-drivers are disabled, without the required access rook operator cannot delete the csidrivers object.
current code where we are deleting the csidrivers object https://github.com/rook/rook/blob/c2db463eb2baa098fc81b217be569b0d7a38e6a3/pkg/operator/ceph/csi/spec.go#L581-L589
Resolves #
**Checklist:**
[test ceph]
> ceph: update clusterrole of operator for csidrivers

- tests/integration/ceph_mgr_test.go
During debugging my PR, I noticed the following error does not output properly in [this test](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/PR-5909/runs/6/nodes/57/steps/123/log/?start=0).
This is because of using `logger.Info`, so I fixed it.
```
2020-07-28 20:46:54.684364 D | exec: Running command: kubectl exec -i rook-ceph-tools -n mgr-ns -- ceph orch status --connect-timeout=15
2020-07-28 20:46:55.772286 W | installer: Error executing command "ceph": <exit status 22>
2020-07-28 20:46:55.772353 I | integrationTest: %s. no valid command found; 10 closest matches:
pg stat
pg getmap
pg dump [all|summary|sum|delta|pools|osds|pgs|pgs_brief...]
pg dump_json [all|summary|sum|pools|osds|pgs...]
pg dump_pools_json
pg ls-by-pool <poolstr> …
```
> ci: fix log output

- cmd/rook/rook/rook.go
- pkg/daemon/ceph/agent/flexvolume/server.go
- pkg/daemon/util/copybins.go
- pkg/util/exec/exec.go
using defer for the closing files which are open
for writing is not safe. so closing file again
following  below steps:
1. open files
2. defer file.close()
3. write 
4.file.close()
these will make sure files are closed.
Resolves #
**Checklist:**
> ceph: closing file which are open for writing

- Documentation/ceph-object-bucket-claim.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/object-bucket-claim-delete.yaml
- cluster/examples/kubernetes/ceph/object-bucket-claim-retain.yaml
- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/bucket/util.go
- pkg/operator/ceph/object/user.go
- tests/framework/clients/bucket.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.2.go
- tests/integration/ceph_base_object_test.go
- tests/integration/ceph_smoke_test.go
Adding support for quota in Object bucket claims. Currently users can set quota on bucket/user via toolbox using radosgw-admin command. With this change there is configurable parameter in object bucket claim CRD 
Please not the quota scope used is here is user, so that OBC with same bucket can have different quota.
Resolves #5274
**Checklist:**
> ceph: adding support for quota in object bucket claims

- pkg/operator/ceph/object/bucket/provisioner.go
using deleteOBCResourceLogError() instead of deleteOBCResource to resolve issues related to GOSEC. Also fixed a bug in deleteOBCResourceLogError()
Resolves #
**Checklist:**
> ceph: use deleteOBCResourceLogError instead of deleteOBCResource

- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/labels.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/controller/spec.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/nfs/spec.go
- pkg/operator/ceph/object/spec.go
add 'ceph_daemon_type' label to pod labels
This can help users identify the daemon type similarly to how
'ceph_daemon_id' helps identify the daemon ID. This also makes it so
scripts users create don't have to parse "app=rook-ceph-<daemonType>"
into "<daemonType>" if they desire that bit of info.
Add this label to OSDs and to NFSes.
Resolves #
**Checklist:**
> ceph: add ceph_daemon_type label to Ceph daemon pods

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
If we are unable to get a default ceph data pool name,
script won't be throwing an error.
Resolves #
**Checklist:**
[skip ci]
> ceph: Allowing ceph filesystem argument to be optional

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
If no endpoint is specified, we don't need to validate the rgw pools.
Resolves #
**Checklist:**
[skip ci]
> ceph: do not validate rgw pool if no endpoint

- Documentation/ceph-dashboard.md
- PendingReleaseNotes.md
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/objectstore_test.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/user.go
Ceph Dashboard will be available when mgr pods start, but object-store metrics cannot be viewed. This PR fixes that by providing necessary permissions for the dashboard via admin user
Resolves #2722
**Checklist:**
> ceph: enable/disable dashboard for rgw

- Documentation/ceph-block.md
- Documentation/ceph-cluster-crd.md
- Documentation/ceph-filesystem.md
add CSI expand secret details to CSI storage-class template in md files.
Resolves #
**Checklist:**
[skip ci]
> ceph: add expand secret to storageclass examples

- design/nfs/nfs-provisioner-controlled-by-operator.md
Design implementation nfs provisioner controlled by operator to address the issue about nfs provisioner share the same directory between PV https://github.com/rook/rook/issues/4982
**Checklist:**
> doc: design nfs provisioner controlled by operator

- pkg/operator/ceph/csi/spec.go
create CSI driver object if the kubernetes version is greater than 1.14 modified the check to allow Csidriver object creation if kubernetes major version is greater than 1.
Resolves #
**Checklist:**
[skip ci]
> ceph: create csidriver if kube version is >1.14

- tests/README.md
The OS version for CI environment is ubuntu 18.04 now.
Nothing
**Checklist:**
[skip ci]
> ci: fix os version

- Documentation/ceph-object-multisite.md
- Documentation/ceph-object-store-crd.md
reformatting in many planes in ceph-object-multisite.md.
also a minor fix in object-store crd docs.
Resolves #
**Checklist:**
[skip ci]
> ceph: minor fixes for multisite docs

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cmd/rook/ceph/osd.go
- pkg/apis/ceph.rook.io/v1/validate_clusters.go
- pkg/apis/ceph.rook.io/v1/validate_clusters_test.go
- pkg/apis/rook.io/v1/types.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/encryption.go
- pkg/daemon/ceph/osd/encryption_test.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/osd/config.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/envs.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/volumes.go
- pkg/operator/ceph/controller/controller_utils.go
- pkg/util/sys/device.go
- tests/framework/installer/ceph_manifests.go
We can now encrypted OSD device that were provisioned via a storage
class using the PV interface.
The encryption works at the storageClassDeviceSets level, which means we
can have encrypted and non-encrypted sets.
Using the new key `encrypted` we can turn it on.
Resolves https://github.com/rook/rook/issues/5590 and https://github.com/rook/rook/issues/5589
**Checklist:**
**Remaining work:**
> ceph: add encryption support for osd pvc

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
RGW poolPrefix is required for the UI and alerting, to provide right information about the respective pool in external mode.
Resolves #
**Checklist:**
[skip ci]
> ceph: added rgw poolPrefix on ceph external script output

- pkg/operator/ceph/cluster/mon/service.go
The service selector labels cannot be updated during the upgrade or else the mon commands will not respond until the mon deployment is also updated. Since there is a mon command to check for the ceph versions before the deployment is updated, the operator would remain stuck during the upgrade.
I should have seen this coming with the related change to immutable match selectors on deployments.
**Checklist:**
> ceph: During upgrade the mon service selector cannot be changed

- tests/scripts/localPathPV.sh
It's not necessary to use random string for mon directory.
In addition, current implementation leaves garbage under /var/lib/rook.
Nothing
**Checklist:**
[test ceph]
> ceph: use fixed mon directory in ci

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v15-rules-external.yaml
- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v15-rules.yaml
The prometheus manifests should be symlinked in the same directory instead of from the root of the repo for building across all platforms. This was causing the build to fail on mac.
Resolves: #5958 
**Checklist:**
> ceph: Symlink prometheus manifests in same dir

- pkg/operator/ceph/cluster/cephstatus.go
- pkg/operator/ceph/config/conditions.go
The cluster CR status needs to be updated with the latest object instead of a cached copy or else it could fail if there is some other update. Using the Rook clientset ensures it is the latest instead of using the cached controller runtime object.
Resolves #5955 
**Checklist:**
> ceph: Update the cluster status with a non-cached object

- Documentation/ceph-cluster-crd.md
- pkg/operator/ceph/config/network.go
- pkg/operator/ceph/config/network_test.go
- pkg/operator/k8sutil/network.go
In the whereabouts config, the network range is determined by range
option unlike other cni plugins that use Subnet option.
Resolves #
**Checklist:**
[test ceph]
> ceph: fix networkAttachmentConfig to be compatible with whereabouts cni

- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/upgrade-from-v1.3-apply.yaml
Upgrades need the RBAC in order to enable the admission controller. Otherwise, the admission controller fails to start if they enable it after the upgrade.
**Checklist:**
[skip ci]
> ceph: Admission controller rbac for the upgrades

- cluster/examples/kubernetes/ceph/csi/rbd/storageclass-ec.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass-test.yaml
- cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
Ceph csi storageclass examples should point that provisioner name prefix depends on which namespace the rook ceph operator has benn deployed.
This is pointed in the documentation but not in the examples:
https://github.com/rook/rook/blob/master/Documentation/ceph-block.md#provision-storage
**Checklist:**
> docs: add provisioner prefix namespace comment in ceph csi examples

- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/util.go
- pkg/operator/k8sutil/deployment.go
- pkg/operator/k8sutil/statefulset.go
sometimes the kube schedular will schedule the provisioner pod on the same node. it doesn't make sense to have both provisioner pod running on the same node, we need to set the pod anti-affinity to make sure that no provisioner pods runnings on the same node.
Resolves #
**Checklist:**
[test ceph]
> ceph: set pod anti affinity to provisioner pod

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
In the interest of having the metrics available generically for all the storage provisioners and just not ceph provisioners, the superseding metrics will be added to Openshift directly. Thus, these metrics won't be required in rook.
PR on OCP for the same functionality: https://github.com/openshift/cluster-monitoring-operator/pull/892
Also, fixes: #6011 
Resolves #
**Checklist:**
[skip ci]
> ceph: Removed the storage provisioners usage rules.

- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
For external cluster, it is not an issue to have a mon count set to 0
since Rook is not deploying/managing the monitors.
Resolves #
**Checklist:**
> ceph: fix healtcheck for external cluster

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.3-crds.yaml
- tests/framework/installer/ceph_manifests.go
Previously, we did not had crush root definition in the CRDs for fileSystems , Blocks and others. After this change, we have added the definition, one can define the crushRoot and it will be used.
Resolves # https://github.com/rook/rook/issues/5809
**Checklist:**
> ceph: adding ability to specify crushroot in the CRD

- cluster/charts/rook-ceph/templates/clusterrole.yaml
With the removal of aggregate roles from the ClusterRole specs, the psp:rook clusterrole was mistakenly removed. Now we rename the clusterrole properly so the operator will be granted privileges as expected for psp.
Resolves #6015 
**Checklist:**
[skip ci]
> ceph: Fix psp clusterrole name for helm chart

- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
A couple of small changes:
- Test cluster settings for mon failover interval to simplify testing the mon failover in test clusters
- Clarify comment in operator.yaml for enabling privileged host paths when selinux is enabled 
Resolves #6009 
**Checklist:**
[skip ci]
> ceph: Test cluster settings for mon failover interval

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- pkg/daemon/ceph/cleanup/disk.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/osd/envs.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/cluster/osd/volumes.go
Based on the feature of metadata PVC for OSD: https://github.com/rook/rook/pull/4818/, add the wal device.
For this, you need to create a new volumeClaimTemplates, its name must be "wal", if "wal" is set, "metadata" device will refer specially for block.db device, and "wal" refers for block.wal device in BlueStore.
A template will look like this:
```
volumeClaimTemplates:
- metadata:
name: data
spec:
resources:
requests:
storage: 10Gi
storageClassName: gp2
volumeMode: Block
accessModes:
- ReadWriteOnce
- metadata:
name: metadata
spec:
resources:
requests:
storage: 5Gi
storageClassName: io1
volumeMode: Block
accessModes:
- ReadWriteOnce
- metadata:
name: wal
spec:
resources:
requests:
storage: 5Gi
storageClassName: io1
volumeMode: Block
accessModes:
- ReadWriteOnce
```
We now map block, …
> ceph: add support for wal device for OSD on PVC

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
This pool is not present when this is no bucket yet. So we don't need to
validate its presence.
(cherry picked from commit 0c8d20ffb48fdb8649207468f105d6941d23e015)
(cherry picked from commit 46b0b95d4c6d3e39a3d20762de17d86dd24081cd)
Resolves #
**Checklist:**
[skip ci]
> ceph: do not validate default.rgw.buckets.index

- tests/scripts/kubeadm.sh
This commit will remove "sudo rm /usr/local/bin/kube*" and "sudo rm kubectl" in "tests/scripts/kubeadm.sh".
I think that CI-test doesn't make those files.
Nothing
**Checklist:**
[skip ci]
> ci: remove unnecessary "rm" command

- pkg/daemon/ceph/osd/daemon_test.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/osd/config.go
- pkg/operator/ceph/cluster/osd/config_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
Now the metadata pvc will also be encrypted if the storageClassDeviceSet
has the "encrypted" flag turned on.
**Checklist:**
[skip ci]
> ceph: add support for encrypted metadata pvc

- pkg/operator/ceph/cluster/operator_watchers.go
To avoid operator panic we should check the channel is open before closing as a safety measure.
```text
2020-08-11 06:18:26.485261 I | operator: shutdown signal received, exiting...
panic: close of closed channel
goroutine 1 [running]:
github.com/rook/rook/pkg/operator/ceph/cluster.(*ClusterController).StopWatch(0xc000731600)
/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/operator_watchers.go:47 +0x82
github.com/rook/rook/pkg/operator/ceph.(*Operator).cleanup(...)
/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/operator.go:106
github.com/rook/rook/pkg/operator/ceph.(*Operator).Run(0xc00063e8a0, 0x2602900, 0xc00011aac0)
/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/oper …
```
> ceph: check channel is open before closing
