rook/rook

- pkg/clusterd/disk.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/util/sys/device.go
- tests/integration/ceph_upgrade_test.go
If the device is a partition and this partition is owned by rook, we
accept it.
Closes: https://github.com/rook/rook/issues/4797
Resolves https://github.com/rook/rook/issues/4797
**Checklist:**
[test ceph]
[test full]
> ceph: accept rook owned partitions

- tests/framework/installer/ceph_installer.go
The wipe job in the integration tests is failing frequently. This backport will help the tests be more stable.
**Checklist:**
[test ceph]
> Backport: Improve integration test block wipe job

- pkg/operator/ceph/disruption/clusterdisruption/pools.go
- pkg/operator/ceph/disruption/nodedrain/reconcile.go
- Use %q when possible
- don't use fmt.Errorf
- use the right type when returning errors
Resolves #
**Checklist:**
[test ceph]
> ceph: nits from https://github.com/rook/rook/pull/4679

- PendingReleaseNotes.md
update pending release note.
Resolves #
**Checklist:**
[skip ci]
> release: add osd on pvc raw mode note

- pkg/daemon/ceph/agent/flexvolume/server.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/util/util.go
- pkg/daemon/util/copybins.go
- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/csi/util.go
- pkg/operator/k8sutil/prometheus.go
- pkg/util/file.go
This commit is also part of gosec error handling which handles the following issue:
Fixed G304: Potential File inclusion by cleaning up the file path
Resolves #
**Checklist:**
> rook: Fixing the potential file inclusion error

- design/ceph/object/ceph-multisite-overview.md
- design/ceph/object/realm.md
- design/ceph/object/store.md
- design/ceph/object/zone-group.md
- design/ceph/object/zone.md
Design for #1584 
**Checklist:**
[skip ci]
> object-store-realm: Initial design doc

- ADOPTERS.md
This PR contains new additions to the production adopters list.  We received a lot of great responses to the survey that was sent out to gather information on production usage, and these are the production adopters that are OK with being shared publicly.
This update is needed for the [CNCF graduation criteria v1.3](https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc).
**Checklist:**
[skip ci]
> Update ADOPTERS.md with public production adopters in preparation for CNCF graduation proposal

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
For the patch release, set the manifest versions to v1.2.5.
**Checklist:**
[skip ci]
> Tag the manifests for the v1.2.5 release

- pkg/operator/ceph/csi/spec.go
Fixes #4934 
OpenShift reverts to run jobs if `blockOwnerDeletion` is set when it cannot set finalizers due to missing permissions.
[test ceph]
> Ceph: Ceph CSI fails to start. #4934

- pkg/operator/ceph/pool/controller.go
- tests/framework/clients/pool.go
Resolves https://github.com/rook/rook/issues/4973
**Checklist:**
[test ceph]
[test full]
> ceph: only delete pool if exists

- pkg/operator/ceph/cluster/mgr/orchestrator.go
- pkg/operator/ceph/cluster/mgr/orchestrator_test.go
With https://github.com/ceph/ceph/pull/33131, the CLI has been rename
'orch' instead of 'orchestrator'.
Octopus only.
**Checklist:**
[test ceph]
> ceph: orchestrator cli name change

- build/release/Makefile
The manifest tool is needed for pushing images to dockerhub. The tool has been failing the past two days apparently due to running an old version.
**Checklist:**
[skip ci]
> Update manifest tool version to v1.0.0

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/cluster-minimal.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- images/ceph/Makefile
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/cluster/osd/spec.go
Ceph 14.2.8 just got released so let's use it.
Resolves #
**Checklist:**
[test ceph]
> Ceph v14.2.8 is causing failure with OSDs on PVCs

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
For the patch release set the manifest versions and docs to v1.2.6.
**Checklist:**
[skip ci]
> Update manifests for the v1.2.6 release

- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/rbd/mirror.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/nfs/nfs.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/k8sutil/test/deployment.go
As part of the transition to support Ceph release **as of** Nautilus, we
left over that portion of code.
We don't need it anymore.
Resolves #
**Checklist:**
[test ceph]
> ceph: remove dead code

- cluster/examples/kubernetes/ceph/pool.yaml
Expose:
* crushRoot
* deviceClass
To the example pool.yaml for awareness.
**Checklist:**
[skip ci]
> ceph: update pool.yaml with more options

- pkg/operator/k8sutil/prometheus.go
with older implementation, servicemonitor was not getting
updated due to missing resource version. This fix adds
resource version to the servicemonitor definition and
ensures that the object is properly created or
updated.
Resolves #4528 . Follow-up for #4603 
**Checklist:**
> Ceph: fix updates for servicemonitor

- go.mod
- go.sum
- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/controller_test.go
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/nfs/controller_test.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/controller_test.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/object/user/controller_test.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
- tests/framework/utils/k8s_helper_test.go
Various controller runtime fixes.
Resolves:
* https://github.com/rook/rook/issues/5059
* https://github.com/rook/rook/issues/5047
**Checklist:**
[test ceph]
[test full]
> Misc controller runtime fixes

- .mergify.yml
- Makefile
* fix make helper
* add mergify configuration for release-1.3 branch
**Checklist:**
[skip ci]
> Enable mergify for backport commits to release-1.3

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/minio/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
Set the manifest versions and docs to v1.2.7 for the patch release
**Checklist:**
[skip ci]
> Set manifest versions to v1.2.7 for the patch release

- Jenkinsfile
- Makefile
- go.sum
Every developer should commit all the files that need to be changed in a given set of changes. The go.sum file was not being generated as expected since the update to go modules. Since the Jenkinsfile was running make mod.check, the build was ending up with a modified file, which caused a dirty tag on the build. Now it is expected that each PR will merge with the corresponding go.sum changes.
**Checklist:**
> Ensure go.sum is updated with every PR

- pkg/apis/nfs.rook.io/v1alpha1/types.go
- pkg/apis/nfs.rook.io/v1alpha1/zz_generated.deepcopy.go
- pkg/operator/nfs/controller.go
This feature adds the standard `Placement` label to the `NFSServer` spec.
**Checklist:**
> nfs: Add placement support for NFSServer

- tests/integration/ceph_base_object_test.go
This fix is added to ensure that everything works as expected
when user tries to create ObjectStoreUser before creating
ObjectStore itself. ObjectStoreUser will wait for ObjectStore
to be up and running.
Resolves #
**Checklist:**
[test ceph]
[test full]
> Ceph: integration test creates ObjectStoreUser before ObjectStore

- tests/framework/installer/ceph_installer.go
Run the tests on latest nautilus with the tag ceph/ceph:v14 (currently v14.2.8) so we are constantly testing on the latest release.
**Checklist:**
[test ceph]
[test full]
> Run Ceph integration tests on latest nautilus

- Jenkinsfile
- go.sum
The recent change to go modules is causing a file to change during the build, which results in a dirty tag to be generated.
**Checklist:**
// CI changes already verified, just getting this in sooner...
[skip ci]
> Ensure files are not modified during build

- Jenkinsfile
The master build is publishing with the dirty tag so we need to ensure that the files do not remain modified.
**Checklist:**
[skip ci]
> Check for modified files in build

- Jenkinsfile
The go modules are changed by the install of the junit tool for the unit tests. Before the release build we need to ensure that the modules are tidied.
**Checklist:**
[skip ci]
> Tidy the go modules before the release build

- Jenkinsfile
With the release of k8s 1.18 we now will run the integration tests on 1.14 through 1.18 in master. At the same time we also run on the latest patch releases for previous minor releases.
**Checklist:**
[test full]
> Test rook on K8s 1.18

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Jenkinsfile
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
- tests/integration/ceph_base_deploy_test.go
- Set build manifest versions to v1.3.0-alpha.0
-  Updated k8s versions for Ceph integration tests
**Checklist:**
> Updated example manifests and basic upgrade docs for the tentative 1.3.0-beta.0 release

- Documentation/ceph-prerequisites.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-teardown.md
- Documentation/ceph-upgrade.md
- Documentation/helm-operator.md
- PendingReleaseNotes.md
- tests/README.md
Various updates are needed for the v1.3 release.
- The pending release notes were missing some features
- Added a section to the upgrade guide for breaking changes to OSDs
- Clarifications around Ceph prereqs and min version
- Other misc clarifications
**Checklist:**
[skip ci]
> Backport: Update docs for Rook v1.3 release

- Documentation/ceph-upgrade.md
- pkg/operator/ceph/controller/predicate.go
After testing the upgrade there are some updates to the upgrade guide.
Also added comments about the helm chart upgrades
**Checklist:**
[test ceph]
> Upgrade doc clarifications for v1.3

- pkg/daemon/ceph/agent/cluster/controller.go
- pkg/operator/cassandra/controller/controller.go
- pkg/operator/cassandra/sidecar/sidecar.go
- pkg/operator/ceph/cluster/crash/add.go
- pkg/operator/ceph/cluster/osd/status.go
- pkg/operator/ceph/disruption/nodedrain/add.go
- pkg/operator/cockroachdb/controller.go
- pkg/operator/edgefs/cluster/controller.go
- pkg/operator/nfs/controller.go
- pkg/operator/yugabytedb/create_controller.go
- pkg/operator/yugabytedb/update_controller.go
Handles the unhandled type assertions throughout the codebase
Resolves #4566 
**Checklist:**
> Handle type assertions

- Documentation/edgefs-quickstart.md
- Documentation/edgefs-smb-crd.md
- pkg/operator/edgefs/cluster/controller.go
Resolves #5195 
**Checklist:**
[test edgefs]
> edgefs: fix SMB controller update path

- Documentation/ceph-toolbox.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
The example manifests are now updated for the v1.3.0 release
**Checklist:**
[skip ci]
> Update manifest version for v1.3.0 release

- tests/framework/installer/ceph_installer.go
- tests/scripts/helm.sh
**Checklist:**
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [o] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](https://github.com/rook/rook/blob/master/CONTRIBUTING.md#comments)
- [o] Add the flag for skipping the CI if …
> Ceph: prevent pre-existing lvms from wipe

- pkg/operator/nfs/server.go
Fix a comment typo.
**Checklist:**
> nfs: fix comment typo

- Documentation/ceph-cluster-crd.md
**Description of your changes:** Add example for using a specific partition for storage
None. ocumentation improvement.
**Checklist:**
- [x ] Documentation has been updated, if necessary.
[skip ci]
> ceph: Add example for using a specific partition for storage

- PendingReleaseNotes.md
Since we ship 1.3, we need to reset this file.
**Checklist:**
[skip ci]
> rook: reset PendingReleaseNotes

- pkg/operator/ceph/object/spec.go
In the v1.3 release the target port for the rgw daemons changed to 8080. The upgrade was skipping the service update anytime the service already existed. Now the service will be updated with every reconcile to ensure the target port is correct.
Resolves #5228 
**Checklist:**
// known ci issue
[skip ci]
> Update the object store service port during upgrade

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
Set the manifest version to v1.3.1 for the patch release.
**Checklist:**
[skip ci]
> Set manifest versions to v1.3.1

- pkg/operator/ceph/file/filesystem.go
Changing the metadataPool and dataPools replicated size no effect.
The old Filesystem's pool is not getting updated when changed with the new File system.
So, we added two helper functions that will generate the names of the pools and then change those pool's values using the `SetPoolSize` method.
Resolves #3144 
**Checklist:**
[test ceph]
[test full]
> Ceph: Filesystem Pool Size are ignored

- Documentation/ceph-advanced-configuration.md
- Documentation/ceph-common-issues.md
- Documentation/ceph-configuration.md
Update pg_num related documents.
Resolves #1329
**Checklist:** …
> ceph: Update pg_num related documents

- tests/scripts/kubeadm-install.sh
- tests/scripts/kubeadm.sh
Fix some bugs in kubeadm related tools.
Noting
**Checklist:** …
> Tests: fix k8s install scripts

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- pkg/operator/ceph/cluster/controller_test.go
With the release of ceph v14.2.9 we set the default examples to this version.
**Checklist:**
[test ceph]
> Set defaults to the Ceph v14.2.9 release

- pkg/operator/ceph/cluster/mgr/mgr.go
The mgr modules take some time to configure during every reconcile loop (20-30s). The OSDs were waiting until the mgr module config was completed. Since the mgr module config is optional or at least not critical to the rest of the reconcile we can do it in parallel.
In the past we waited before continuing the orchestration primarily because the logging was so verbose with all the mgr modules. In v1.3 the logging is much less concern so it won't hide the osd config so much.
**Checklist:**
[test ceph]
> Configure mgr modules in parallel of rest of reconcile loop

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/common-external.yaml
- cluster/examples/kubernetes/ceph/create-external-cluster-resources.sh
- cluster/examples/kubernetes/ceph/import-external-cluster.sh
- pkg/daemon/ceph/client/command.go
- pkg/daemon/ceph/client/command_test.go
- pkg/daemon/ceph/client/mon.go
- pkg/daemon/ceph/client/mon_test.go
- pkg/daemon/ceph/client/status.go
- pkg/daemon/ceph/config/config.go
- pkg/daemon/ceph/config/config_test.go
- pkg/daemon/ceph/config/info.go
- pkg/daemon/ceph/config/keyring.go
- pkg/operator/ceph/cluster/cephstatus.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/controller_test.go
- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/cluster/mon/env.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/csi/secrets.go
- pkg/operator/ceph/object/admin.go
- tests/integration/ceph_base_file_test.go
Backport of https://github.com/rook/rook/pull/5227
[test ceph]
> ceph: make admin key optional for external cluster (bp #5227)

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the latest patch release we set the manifest version to v1.3.2
**Checklist:**
[skip ci]
> Set the manifest versions to v1.3.2

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/cluster/mon/mon.go
Since we now added more keys and secrets, they need to be deleted once
the cluster goes away.
**PUSHING DIRECTLY IN RELEASE BRANCH SINCE THIS CODE IS UNDER DRASTIC CHANGE ON MASTER**
[test ceph]
> ceph: external cluster purge csi secrets

- CONTRIBUTING.md
- pkg/clusterd/disk.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/yugabytedb/controller.go
- pkg/operator/yugabytedb/controller_test.go
- pkg/operator/yugabytedb/create_controller.go
Update documents and comments for user's convenience. In addition, cleanup some code to improve maintainerbility.
Nothing
**Checklist:**
- [o] Reviewed the developer …
> update documents and cleanup code

- Documentation/ceph-advanced-configuration.md
fix the wrong log collection script in the documentation
**Checklist:**
> docs: fix log collection script

- Documentation/ceph-cluster-crd.md
Document that the CRUSH hierarchy requires unique names at each location.
Resolves #5329
**Checklist:**
[skip ci]
> Document unique crush name requirement

- pkg/daemon/discover/discover_test.go
During the sgdisk command test, there was no output assignment, causing uuid not found for device /dev/testa. Follow the log.
2020-04-27 18:24:21.921337 I | rook-discover: RUN Command lsblk [--all --noheadings --list --output KNAME]
2020-04-27 18:24:21.921491 I | rook-discover: RUN Command lsblk [/dev/testa --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME]
2020-04-27 18:24:21.921549 I | rook-discover: RUN Command sgdisk [--print /dev/testa]
2020-04-27 18:24:21.921576 W | inventory: skipping device "testa" because 'lsblk' failed. uuid not found for device /dev/testa. output=
2020-04-27 18:24:21.921592 I | rook-discover: localdevices: []
2020-04-27 18:24:21.921598 I | rook-discover: available devices: []
--- FAIL: TestProbeDevices …
> tests: Fix ProbeDevices function unit test failure

- pkg/daemon/ceph/osd/daemon.go
If we fail to release an LVM device, we should not fail the deployment.
We just print the error and let the backend handle the rest. Some
CSI backend will force detach the device anyway.
This prevents the deployment to get stuck in terminating.
**BACKPORT ON RELEASE-1.2 BECAUSE MASTER HAS DIVERGED**
[test ceph]
> ceph: do not fail on deactivate

- Documentation/ceph-storage.md
correct wordings so that they pass grammar checkings and better understood by non-English native readers. Thanks!
[skip ci]
> doc: correct the wordings

- pkg/operator/k8sutil/configmap.go
The operator settings can come either from the configmap, an
env var, or a default value. Knowing where the setting is loaded
from is an important detail to see in the log.
**Checklist:**
[test ceph]
> Log the operator settings and their source

- images/ceph/Makefile
The v14.2.9 release and updated base image have security fixes that the operator needs to pick up.
Resolves #5383
**Checklist:**
[test ceph]
[test full]
> Set v14.2.9 as base image for the operator

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release the new version is v1.3.3
**Checklist:**
[skip ci]
> Set manifest version to v1.3.3

- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
there is a typo in operator.yaml and operator.openshift.yaml file for csi priority class, This PR fixes the typo.
Resolves #5442
**Checklist:**
> CSI: fix typo in operator.yaml and operator-openshift.yaml

- images/Makefile
The version of tini being used is getting rather stale, time to update.
**Checklist:**
> Update tini version to v0.19.0

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
This script will generate JSON format of all the needed resources.
Script can also generate the output in Shell script format.
Signed-off-by: Arun Kumar Mohan <arun.iiird@gmail.com>
Resolves #
**Checklist:**
[skip ci]
> Python script to generate needed external cluster resources in JSON format

- pkg/operator/ceph/cluster/cluster_external.go
When Rook-Ceph is connected to an external cluster and the admin tries
to create resources such as CephFilesystem or CephObjectStore, we must
create the rook-ceph-config secret so that the daemons can get their mon
information.
Closes: https://github.com/rook/rook/issues/5439
Resolves https://github.com/rook/rook/issues/5439
**Checklist:**
[test ceph]
> ceph: create missing secret on external cluster

- pkg/operator/ceph/cluster/controller.go
When Rook-Ceph is connected to an external cluster and the admin tries
to create resources such as CephFilesystem or CephObjectStore, we must
create the rook-ceph-config secret so that the daemons can get their mon
information.
Adapted version of 1fef75bc6ab86f3f747bfea44c7e310356029f00 since
cherry-picking wasn't possible.
Backport of https://github.com/rook/rook/pull/5450
[test ceph]
> ceph: create missing secret on external cluster (bp #5450)

- cluster/olm/ceph/generate-rook-csv.sh
We now include the newly created script for external cluster in the CSV.
Resolves #
**Checklist:**
**HOLD until https://github.com/rook/rook/pull/5388 merge**
[test ceph]
> csv: add external cluster script

- cluster/olm/ceph/generate-rook-csv.sh
We now include the newly created script for external cluster in the CSV.
(cherry picked from commit c4c873c27e810de37d7039d3265a5aaf87c25084)
Backport of #5421
[test ceph]
> csv: add external cluster script (bp #5421)

- cluster/olm/ceph/assemble/metadata-common.yaml
Somehow the CephFilesystem was not present so adding it.
Resolves #
**Checklist:**
[skip tests]
> csv: add missing CephFilesystem

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
* Clarify the helper for the run-as-user argument
* Add 2 new storage class and put the data so we stick with the same
pattern as the Secret and ConfigMap
Resolves #
**Checklist:**
[skip tests]
> script: add 2 new SC

- Makefile
makefile items such as "check test", "mod.update", "mod.check" were
missing from help menu.
Resolves #
**Checklist:**
> makefile: complete the help menu

- pkg/operator/ceph/cr_manager.go
- pkg/operator/ceph/operator.go
The operator continues to run even though the controller-runtime
failed to start. Since the controller-runtime is essential, the operator
is non-functional after that. It makes troubleshooting more difficult.
Resolves #5434
**Checklist:** …
> ceph: gave up to run the operator if the controller-runtime failed to start

- pkg/operator/ceph/cluster/controller.go
If the admin key is available, set the external creds struct
to use that admin username and key instead of requiring the
callers to check every time if they should use the admin
key or the external key.
Co-authored-by: Travis Nielsen <tnielsen@redhat.com>
(cherry picked from commit 90fa3a6)
Resolves #
**Checklist:**
[test ceph]
Partial backport of #5490
> ceph: set external creds if admin key is available (partial bp-#5490)

- pkg/daemon/ceph/osd/daemon.go
Add the valid verbose flags back.
Resolves #
**Checklist:**
[test ceph]
> ceph: fix lvm arg

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
For the v1.3.4 release we update the manifest versions.
**Checklist:**
[skip ci]
> Update manifest versions to v1.3.4

- Documentation/ceph-upgrade.md
Simple broken link fix for web site.
[skip ci]
> Fix broken link on 1.0 upgrade page.

- .commitlintrc.json
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/commitlint.yml
- Documentation/development-flow.md
We now use the semantic bot instead of the deprecated commitlint bot.
Closes: https://github.com/rook/rook/issues/5547
Resolves https://github.com/rook/rook/issues/5547
**Checklist:**
[skip ci]
> add commitlint github action

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the release of v1.3.5 we update the documentation and example manifests.
**Checklist:**
[skip ci]
> Set the release version to v1.3.5

- INSTALL.md
- Jenkinsfile
If no Golang files were modified we don't want to run the integration
test.
**Checklist:**
> ci: do not run when no code changes

- INSTALL.md
- Jenkinsfile
If the PR follows our contribution guideline https://rook.io/docs/rook/master/development-flow.html#commit-structure
and then the PR title contains for example "ceph: add a feature", then
the CI will run the ceph storage integration tests.
Resolves https://github.com/rook/rook/issues/5612
**Checklist:**
> ci: auto-detect storage provider

- pkg/operator/nfs/server.go
Reopen PR 5554, because I picked the wrong branch to PR into.
Implementing the changes @prksu mentioned in #4259
tested and build in docker aberfeldy/nfs:ganesha-fix
Signed-off-by: Andreas Feldmann an.feldmann@googlemail.com
implementing the changes @prksu mentioned regarding the memory leak of the nfs server
Resolves #4259
Resolves #
**Checklist:**
> nfs: changing the loglevel into INFO

- Documentation/ceph-teardown.md
blkdiscard is the better tool for cleaning SSDs instead of dd.
@kfox111 any other suggested clarifications for the cleanup docs while we're at it?
Resolves #5307 
**Checklist:**
> docs: clean ssds with blkdiscard

- design/ceph/ceph-external-cluster.md
Enhance the external cluster functionality by plugin monitoring.
Resolves #
**Checklist:**
[skip ci]
> docs: add external monitoring design

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
For the patch release set the manifest versions and docs to v1.3.6.
**Checklist:**
[skip ci]
> Set manifest versions to v1.3.6

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/file/controller_test.go
- pkg/operator/ceph/nfs/controller_test.go
- pkg/operator/ceph/object/bucket/rgw-handlers.go
- pkg/operator/ceph/object/controller_test.go
- pkg/operator/ceph/object/user.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/object/user/controller_test.go
- pkg/operator/ceph/pool/controller_test.go
- pkg/util/exec/exec.go
[test ceph]
**BACKPORT OF https://github.com/rook/rook/pull/5664**
> ceph: add external support for object store user (bp #5664)

- cluster/charts/rook-ceph/templates/clusterrole.yaml
Rewrite of line in Helm chart to correctly reflect intent.
Resolves #5378. See https://golang.org/doc/go1.14#text/template
**Checklist:**
[test ceph]
> Fix for Go 1.14 templating

- pkg/apis/ceph.rook.io/v1/annotations.go
- pkg/apis/ceph.rook.io/v1/annotations_test.go
- pkg/apis/ceph.rook.io/v1/keys.go
- pkg/apis/ceph.rook.io/v1/resources.go
Signed-off-by: Vineet Badrinath <vbadrina@redhat.com>
This is a small code cleanup for unused functions and constants for rgw and rbd
Resolves #5546
> ceph: removes unused rgw functions and constants from rook.io/v1 pkg

- pkg/operator/ceph/object/user.go
Stop check for the output, but read it instead.
Resolves #
**Checklist:**
> ceph: fix GetUser

- pkg/operator/ceph/object/user.go
- pkg/util/exec/exec.go
> ceph: fix exec output and GetUser (bp #5730 and bp#5696)

- PendingReleaseNotes.md
- images/cassandra/Dockerfile
Due to CVEs in the alpine:3.8, we need to update the base image.
(cherry picked from commit 849cf84bf8e1df0dbc7e277b77708964a988cdc6)
**Checklist:**
> cassandra: update base image to alpine:3.12

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
Set manifest versions to v1.3.7 for the release
**Checklist:**
[skip ci]
> Update the manifests for the v1.3.7 release

- tests/framework/installer/environment.go
The master CI is not expected to run the mgr test suite, which runs against ceph master.
First step is to add some logging to see why it is not being skipped.
**Checklist:**
> ceph: Add logging for mgr integration test suite in master

- tests/framework/installer/environment.go
- tests/integration/ceph_mgr_test.go
Due to an issue in ceph master, the mgr integration test is failing. Until this is fixed, we will temporarily disable the test. A fix is expected with https://github.com/ceph/ceph/pull/35915.
**Checklist:**
// known ci issue
[skip ci]
> ceph: Disable ceph mgr test temporarily

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- images/ceph/Makefile
- pkg/operator/ceph/cluster/controller_test.go
Update to the latest ceph release build for nautilus as the base image for the operator and the default in cluster.yaml
**Checklist:**
> ceph: Update to the latest Ceph Nautilus release v14.2.10

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.3-crds.yaml
- tests/framework/installer/ceph_manifests.go
Add missing API fields.
**Checklist:**
> ceph: resync crds

- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/controller_test.go
Do not delete ceph object store until ceph object users are cleaned up
Resolves #5712
**Checklist:**
> ceph: check for ceph object user cleanup

- Documentation/nfs.md
- cluster/examples/kubernetes/nfs/nfs-ceph.yaml
- cluster/examples/kubernetes/nfs/nfs.yaml
- cluster/examples/kubernetes/nfs/scc.yaml
- pkg/operator/nfs/spec.go
- tests/framework/installer/nfs_manifests.go
This PR fix nfs issue on openshift
Resolves #2721
**Checklist:**
[test nfs]
> nfs: fix nfs issue on openshift

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
If there is a typo in the rgw endpoint, then the user will be notified
that the gateway is not accessible or does not return the 200 HTTP code.
Error example:
```
[root@mon0 ~]# python p.py --rbd-data-pool-name test --rgw-endpoint 192.168.111.11:8080
Excecution Failed: failed to connect to rgw endpoint http://192.168.111.11:8080
```
Resolves #
**Checklist:**
[skip ci]
> ceph: add http dial to verify external endpoint

- pkg/operator/ceph/object/user/controller.go
This PR fixes issue for fixing the updation related issue for `CephObjectStoreUser` CRD
Resolves #5713
**Checklist:**
> ceph: display name updation for existing ceph object store users

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
Set manifest versions to v1.3.8 for the release
**Checklist:**
[skip ci]
> build: set manifest versions to v1.3.8

- pkg/daemon/ceph/client/status.go
- pkg/operator/ceph/cluster/cephstatus.go
- pkg/operator/ceph/cluster/cephstatus_test.go
- pkg/operator/ceph/cluster/controller.go
**Backport of #5837 and #5856**
> ceph: let the healthcheck set the status phase (bp #5837) and report error on timeout (bp #5856)

- Documentation/nfs.md
This PR updates documentation for nfs openshift security context constraints as follow up of this [review](https://github.com/rook/rook/pull/5785#discussion_r454509677)
Resolves #
**Checklist:**
> doc: update nfs openshift scc documentation

- Documentation/ceph-advanced-configuration.md
updating OSD_DATA_DIR path in script
**Checklist:**
> [skip ci] Docs: update OSD_DATA_DIR path in script

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v15-rules-external.yaml
- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v15-rules.yaml
Add monitoring rules for octopus clusters.
Closes: https://github.com/rook/rook/issues/5897
Resolves https://github.com/rook/rook/issues/5897
**Checklist:**
[skip ci]
> ceph: add monitoring rules for octopus

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Resolves #
**Checklist:**
[skip ci]
> Added rules for PVC requested and used capacity for telemeter and updated PV count query

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Some clusters do not have rgws deployed so let's make it optional.
**Checklist:**
[skip ci]
> ceph: make rgw option on external script

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Now the rgw pool with a given prefix will also be checked by the script.
**Checklist:**
[skip ci]
> ceph: validate pools with prefix

- cmd/rook/ceph/config.go
- cmd/rook/util/cmdreporter.go
- cmd/rook/util/copybins.go
- cmd/rookflex/cmd/mount.go
- cmd/rookflex/cmd/root.go
- cmd/rookflex/main.go
- pkg/util/flags/flags.go
this commit handles all the gosec error code
g104: Audit errors not checked
g404: Insecure random number source (rand)
Resolves #3765
**Checklist:**
> ceph: handling gosec errors code g104  and g404

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/provisioner.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the first beta release for v1.4 the versions in the deployment manifests are updated.
**Checklist:**
[skip ci]
> build: Set the manifest versions to v1.4.0-beta.0

- cluster/charts/rook-ceph/templates/clusterrolebinding.yaml
- cluster/charts/rook-ceph/templates/resources.yaml
Remove duplicated lines from the rook-ceph chart.
Nothing.
**Checklist:**
[test ceph]
> ceph: remove duplicated lines from Helm chart

- .mergify.yml
- Add release-1.4 as a mergify backport target
- Remove release-1.1 as a mergify backport target since we no longer plan to backport there. If needed, we can still backport manually.
**Checklist:**
[skip ci]
> ci: Enable 1.4 backport bot

- .github/workflows/gosec.yaml
this commit will add gosec check in ci
and it will help us increase code quality.
Resolves #4578
**Checklist:**
[skip ci]
> ci: adding gosec tool in ci

- design/ceph/object/bucketpolicy.md
Adding design doc for bucket policy feature for ceph object store for the opinion from wider audience.
Resolves #
**Checklist:**
> docs: design doc for bucket policy feature

- Documentation/ceph-cluster-crd.md
Added a StorageClass example for better document usability to test CephExternal cluster
Solves: None
Signed-off-by: Alex Punnen <alexcpn@gmail.com>
Documentation improvement for Ceph External Cluster
Resolves # None
**Checklist:**
[skip ci]
> Documentation improvement for Ceph External Cluster

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
backport of #5952 #5931 #5833 
[skip ci]
> ceph: bulk backport for create-external-cluster-resources.py

- pkg/operator/ceph/csi/csi-cephfsplugin-provisioner.yaml
- pkg/operator/ceph/csi/spec.go
Removed unused file and variable and did some cleanup in csi folder.
Resolves #
**Checklist:**
[skip ci]
> ceph: cleanup csi package

- pkg/clusterd/disk.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
- pkg/util/sys/device.go
Support crypt type device in OSD on PVC.
Nothing
**Checklist:**
[test ceph]
> ceph: support crypt type device in OSD on PVC

- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_multi_cluster_test.go
This commit will fix outdated function comments.
Nothing
**Checklist:**
[skip ci]
> ci: fix function comments

- pkg/operator/ceph/object/controller_test.go
Mock the user creation otherwise the health check fails and panics.
Closes: https://github.com/rook/rook/issues/5976
Resolves https://github.com/rook/rook/issues/5976
**Checklist:**
[skip ci]
> ceph: fix unit test mock

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cmd/rook/ceph/osd.go
- pkg/apis/ceph.rook.io/v1/validate_clusters.go
- pkg/apis/ceph.rook.io/v1/validate_clusters_test.go
- pkg/apis/rook.io/v1/types.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/encryption.go
- pkg/daemon/ceph/osd/encryption_test.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/osd/config.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/envs.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/volumes.go
- pkg/operator/ceph/controller/controller_utils.go
- pkg/util/sys/device.go
- tests/framework/installer/ceph_manifests.go
**BACKPORT OF #5873.**
[test ceph]
> ceph: add encryption support for osd pvc (bp #5873)

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release we update the manifest versions to v1.3.9
**Checklist:**
[skip ci]
> Update manifests with the v1.3.9 version

- pkg/operator/ceph/object/status.go
in a couple of unit testing, the tests are panicking with nil pointer exception,This commit adds a check for status pointer before
operating on it.
the test was failing in https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/PR-5982/runs/1/nodes/37/steps/38/log/?start=0
```
2020-08-05 15:24:58.226444 D | ceph-object-controller: creating s3 user "rook-ceph-internal-s3-user-checker-"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x158a1a1]
goroutine 52 [running]:
github.com/rook/rook/pkg/operator/ceph/object.updateStatusBucket(0x1c234e0, 0xc0005fdc20, 0x192c776, 0x9, 0x192b66d, 0x8, 0x192a378, 0x7, 0xc0006b8000, 0xa6) …
```
> ceph: add check for nil object status

- tests/integration/ceph_base_object_test.go
The object bucket check is sometimes not completed yet that causes the integration test to fail intermittently.
```
--- FAIL: TestCephSmokeSuite/TestObjectStorage_SmokeTest (192.07s)
suite.go:62: test panicked: runtime error: invalid memory address or nil pointer dereference
goroutine 1363 [running]:
runtime/debug.Stack(0xc00066d568, 0x1823220, 0x2ad3900)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/stretchr/testify/suite.failOnPanic(0xc000775e00)
/home/rook/go/pkg/mod/github.com/stretchr/testify@v1.4.0/suite/suite.go:62 +0x57
panic(0x1823220, 0x2ad3900)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rook/rook/tests/integration.runObjectE2ETest(0xc0002eaeb0, 0xc00061c210, 0xc0007c09b0, 0xc0007c09c0, 0xc000775e00, 0x1a4d4e6, 0x8) …
```
> ceph: Improve object bucket test stability

- Documentation/ceph-toolbox.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/provisioner.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the release of v1.4.0 we update the manifest version to match the tag.
**Checklist:**
[skip ci]
> Update the manifest version to v1.4.0 for the release

- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
For external cluster, it is not an issue to have a mon count set to 0
since Rook is not deploying/managing the monitors.
(cherry picked from commit f66473a8f8ac65f4f0dbb04ee8cc7b3570f487bf)
Resolves #
**Checklist:**
> ceph: fix health check for external cluster (bp #6018)

- PendingReleaseNotes.md
Since the v1.4 release is completed, reset the pending release notes for v1.5.
**Checklist:**
[skip ci]
> Reset the pending release notes

- Documentation/ceph-cluster-crd.md
Make the document of cleanup policy clearer.
Nothing
**Checklist:**
[skip ci]
> docs: fix clean policy confirmation

- tests/integration/ceph_base_object_test.go
The object bucket tests will now always check if the conditions being waited upon for creating users and buckets were completed, instead of allowing the test to continue even when they didn't succeed.
**Checklist:**
[test full]
> ceph: Improve stability of object bucket tests

- cluster/olm/ceph/assemble/metadata-common.yaml
The newly object store CRDs were missing from the CSV.
Resolves #
**Checklist:**
[skip tests]
> ceph: add missing crds in csv

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
This pool is not present when this is no bucket yet. So we don't need to
validate its presence.
Resolves #
**Checklist:**
[skip ci]
> ceph: do not validate default.rgw.buckets.index

- cluster/olm/ceph/generate-rook-csv.sh
This line is needed so that we can access resources from the operator.
Resolves #
**Checklist:**
[skip ci]
> ceph: re-add missing RBAC to CSV

- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
When a mon is failed over, the new mon is started before the old mon is removed from quorum and purged from the cluster. If the mon has anti-affinity, in small clusters or specific topologies where sufficient nodes are not available, the new mon may be prevented from starting simply because the dead mon pod still exists. To ensure a clean failover, the dead mon pod must first be stopped before the new mon is started.
**Checklist:**
[skip ci]
> ceph: Mon failover should first scale down the failed mon before starting the new mon

- .mergify.yml
If a PR has a title that starts with "ceph", the ceph label will be
added as well the reviewers.
**Checklist:**
[skip ci]
> bot: add mergify rule for ceph label and reviewer

- pkg/daemon/ceph/osd/daemon_test.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/osd/config.go
- pkg/operator/ceph/cluster/osd/config_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
> ceph: add support for encrypted metadata pvc (bp #5977)

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/provisioner.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release we update the vesrions to v1.4.1
**Checklist:**
[skip ci]
> build: Set the manifest version to v1.4.1

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Further optional output into JSON file.
Resolves #
**Checklist:**
[skip ci]
> Making RBD provisioner, Ceph provisioner and Ceph node optional

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
**BACKPORT OF  #6048** 
[skip ci]
> Making RBD provisioner, Ceph provisioner and Ceph node optional (bp #6048)

- tests/framework/utils/k8s_helper.go
`anon-user-access` clusterrolebinding is created when installing rook operator.
However each test suite does not delete the clusterrolebinding, and cause errors like bellow.
This error occurs even if ci passes in master branch.
```
2020-08-11 06:21:50.775376 D | exec: Running command: kubectl create clusterrolebinding anon-user-access --clusterrole cluster-admin --user system:anonymous
2020-08-11 06:21:51.016248 E | utils: Failed to execute: kubectl [create clusterrolebinding anon-user-access --clusterrole cluster-admin --user system:anonymous] : exit status 1. Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "anon-user-access" already exists
2020-08-11 06:21:51.016279 W | testutil: anon-user-access not created
``` …
> ci: skip the creation of already existing clusterrolebinding

- pkg/operator/ceph/object/realm/controller_test.go
Add unit tests for the ceph object realm
controller.
Resolves #
**Checklist:**
> ceph: object realm controller unit tests

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-common-issues.md
There is a critical flaw in OSD on LV-backed PVC. So it's necessary to let users to know what they should do.
Nothing
**Checklist:**
- [o] Reviewed the …
> docs: add a note of OSD on LV-backed PVC's known problem

- cluster/examples/kubernetes/ceph/object-ec.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
the commit apply latest changes or sync the
object-prefixed manifests with object.yaml
and keeping object-test.yaml simple and
without lastest change.
Resolves #6108
**Checklist:**
[skip ci]
> ceph: applying latest changes to object-prefixed manifests

- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
* ceph: support osd deployment update on encrypted pvc
If the deployment spec was updated or restarted, the "encryption-open"
init container would fail to open the device since it was already
opened on the node.
Because they are no reliable post stop hook on Kubernetes, the trick is
to use a small bash init container.
* ceph: add pvc expansion support for encrypted osds
We now support the expansion of encrypted osds. We added a new init
container to run "cryptsetup resize".
* ceph: add encrypted block status container
This init container displays the status of the encrypted pvc. This can
be really useful for debugging purpose.
**Checklist:**
> ceph: add expansion support for encrypted osd on pvc

- Documentation/development-environment.md
CRC aka code ready containers provide openshift cluster 4.x in a single host machine.
Resolves #
**Checklist:**
> docs: provide link for crc documentation

- Documentation/development-flow.md
Rook supports building images with podman, mention it the documentation
Resolves #
**Checklist:**
> docs: mention about podman in development workflow

- Documentation/ceph-advanced-configuration.md
apply new host network API in documentation
- `hostNetwork: true`  ->  `provider: host`
Signed-off-by: taeuk_kim <taeuk_kim@tmax.co.kr>
Resolves #
**Checklist:**
[skip-ci]
> docs: fix OSD Dedicated Network docs

- build/makelib/golang.mk
Added Golang 1.15 to the supported versions in the Makefile check.
**Checklist:**
> build: allow golang 1.15

- .github/workflows/codegen.yml
- hack/validate-codegen.sh
- pkg/apis/rook.io/v1/zz_generated.deepcopy.go
Fail if a PR is submitted and has not run "make codegen"
**Checklist:**
[skip ci]
> ci: run make codegen validation in workflow

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-filesystem-crd.md
- Documentation/ceph-object-store-crd.md
- cluster/examples/kubernetes/ceph/cluster-with-drive-groups.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/filesystem-ec.yaml
- cluster/examples/kubernetes/ceph/filesystem.yaml
- cluster/examples/kubernetes/ceph/object-ec.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- pkg/apis/ceph.rook.io/v1/annotations.go
- pkg/apis/ceph.rook.io/v1/keys.go
- pkg/apis/ceph.rook.io/v1/labels.go
- pkg/apis/ceph.rook.io/v1/labels_test.go
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
- pkg/operator/ceph/cluster/cleanup.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/nfs/spec.go
- pkg/operator/ceph/object/spec.go
This allows users to specify additional labels to be added to the components
created by the Rook Ceph operator.
**This PR will be a draft till #6082 is merged.**
Relates to #6050
**Checklist:**
// known issue
[skip ci]
> ceph: allow user to add labels to pods

- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/bucket/provisionner_test.go
- pkg/operator/ceph/object/bucket/s3-handlers.go
- pkg/operator/ceph/object/bucket/util.go
**BACKPORT OF https://github.com/rook/rook/pull/6170 IN RELEASE-1.3**
[test ceph]
> ceph: run obc requests with debug (bp #6170 on release-1.3)

- pkg/operator/ceph/object/bucket/provisioner_test.go
- pkg/operator/ceph/object/controller_test.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/rgw_test.go
- pkg/operator/ceph/object/s3-handlers.go
- pkg/operator/ceph/object/status_test.go
**BACKPORT OF https://github.com/rook/rook/pull/6170 IN RELEASE-1.4**
[test ceph]
> ceph: run obc requests with debug (bp #6170 on release-1.4)

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/provisioner.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
For the release update the manifest versions to v1.4.2
**Checklist:**
[skip ci]
> build: Update manifest versions for the v1.4.2 release 

- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
For the release update the manifest versions to v1.3.10
**Checklist:**
[skip ci]
> build: Update manifest versions for the v1.3.10 release 

- .github/workflows/unit-test.yml
- Jenkinsfile
We now run the unit tests separately from the pipeline, only on PRs.
Resolves #
**Checklist:**
[test ceph]
> ci: run unit test in a github workflow

- Jenkinsfile
- tests/framework/installer/environment.go
- tests/scripts/localPathPV.sh
Resolves https://github.com/rook/rook/issues/6189
**Checklist:**
[test ceph]
> ci: change disk used by the CI

- Jenkinsfile
- tests/framework/installer/environment.go
- tests/scripts/localPathPV.sh
> ci: change disk used by the CI (bp #6190)

- pkg/operator/ceph/nfs/config.go
As setting them to small value affects the performance and they are not related
to metadata caching. https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/495185
Resolves #
**Checklist:**
> ceph: Remove NParts and Cache_Size from MDCACHE block

- Documentation/ceph-object-store-crd.md
- Documentation/ceph-object.md
- cluster/examples/kubernetes/ceph/object-multisite-pull-realm.yaml
- cluster/examples/kubernetes/ceph/object-multisite.yaml
- cluster/examples/kubernetes/ceph/object-test.yaml
apply latest changes to prefixed manifests and
related docs.
Resolves #
**Checklist:**
[skip ci]
> ceph: update object prefixed manifests and related docs

- pkg/operator/ceph/object/controller.go
currently, cephobjectstore monitoring is never
stopped for the following flow:
```
1. objectstore is deleted
2. go routine is stopped
3. objectstore is created
4. objectstore is deleted
```
so, removing clusterResourceDeleted flag and
working with the map only.
Resolves #6186
**Checklist:**
> ceph: update cephobjectstore monitoring logic

- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/provisioner.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release we update the manifests and documentation to v1.4.3
**Checklist:**
[skip ci]
> build: Update manifests and docs to v1.4.3

- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release we update the manifests and documentation to v1.3.11
**Checklist:**
[skip ci]
> build: Update manifests and docs to v1.3.11

- tests/framework/clients/block.go
- tests/framework/clients/filesystem.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.2.go
- tests/framework/utils/k8s_helper.go
- tests/framework/utils/snapshot.go
- tests/integration/ceph_base_block_test.go
- tests/integration/ceph_base_file_test.go
- tests/integration/ceph_upgrade_test.go
Adding the E2E testing to test below functionalities of  CSI
* Create PVC And write Data to PVC
* Create Snapshot From  PVC
* Create a new PVC from a snapshot
* Verify PVC content is matching the parent PVC
* Create PVC And write Data to PVC
* Create a new PVC from PVC
* Verify PVC content is matching the parent PVC
These tests will be done for both cephfs and rbd.
Resolves #
**Checklist:**
[test ceph]
[test full]
> ceph: Add E2E testing for csi snapshot and clone

- Documentation/ceph-cluster-crd.md
[skip ci]
- Corrects what I think was a typo ("when then" -> "when they")
- Picks a single tense
- capitalizes OSD
Resolves # none
**Checklist:**
> ceph: tweak removeOSDsIfOutAndSafeToRemove wording

- pkg/operator/ceph/cluster/osd/status.go
Signed-off-by: fanjunwei <fanjunwei@t2cloud.net>
Resolves #
**Checklist:**
> ceph: Use truncated node name

- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/provisioner.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release we update the manifests and documentation to v1.4.4
**Checklist:**
[skip ci]
> build: update manifests and docs to v1.4.4

- pkg/daemon/ceph/client/config.go
- pkg/daemon/ceph/client/config_test.go
Some parameter like bluestore_min_alloc_size, bluestore_min_alloc_size_hdd need to be set during the bootstrap of the
ceph cluster in order to have bluestore created accordingly.
To do so rook users rely on the rook-config-override configmap.
Sadly the rook-ceph-osd-prepare job does not take in account this configmap to generate its ceph config leading to bluestore still being created with default config
Changing the behaviour to merge the config from rook-config-override configmap to the default ceph config
Resolves #6032
**Checklist:**
> ceph: merge config from rook-config-override configmap to the default global config file

- ROADMAP.md
This is a draft primarily of the Ceph features planned for v1.5 and mention of some features that may extend beyond v1.5. Roadmap additions for other storage providers are expected separately by each of the storage provider owners.
**Checklist:**
> docs: Update the roadmap for v1.5

- pkg/operator/ceph/object/realm/controller_test.go
- pkg/operator/ceph/object/zonegroup/controller.go
- pkg/operator/ceph/object/zonegroup/controller_test.go
Add unit tests for CephObjectZoneGroup, with
minor fixes to the realm unit tests.
Resolves #
**Checklist:**
> ceph: add unit tests for zone group

- Documentation/ceph-common-issues.md
When the system has a low ow aio-max-nr setting, the osd prepare pod can
fail to complete. This value must be increased.
Adding a documentation section for it.
Closes: https://github.com/rook/rook/issues/6279
Resolves https://github.com/rook/rook/issues/6279
**Checklist:**
> docs: common issue low aio-max-nr setting

- pkg/operator/yugabytedb/controller.go
This updates the YugabyteDB image to a latest stable version.
Resolves https://github.com/yugabyte/yugabyte-db/issues/5525
**Checklist:**
[test yugabytedb]
> yugabytedb: update YugabyteDB container image

- cluster/examples/kubernetes/ceph/filesystem-ec.yaml
- cluster/examples/kubernetes/ceph/filesystem-test.yaml
- cluster/examples/kubernetes/ceph/object-multisite.yaml
- cluster/examples/kubernetes/ceph/object-test.yaml
- cluster/examples/kubernetes/ceph/pool-test.yaml
Makes the example yamls all use a consistent format for `compression_mode:`
Resolves #6318
**Checklist:**
> [skip ci] example yamls: use new style parameters.compression_mode

- design/nfs/nfs-quota.md
Design nfs quota
Resolves #
**Checklist:**
[skip ci]
> nfs: design nfs quota

- pkg/operator/yugabytedb/controller.go
this commit reverts the changes done in
controller file as previous changes( [here](https://github.com/rook/rook/pull/6306/files#diff-6393982850daa8060e0b285f67a89e5dL179-L510)) failing
in ci and those changes are related to linter(#6306 ).
so we can supress them.
Resolves #6320 
**Checklist:**
[test yugabytedb]
> yugabytedb: integration test failing

- cluster/charts/rook-ceph/templates/role.yaml
Allow manipulations on monitoring.coreos.com resources to operator within helm chart
Resolves #6255
**Checklist:**
> ceph: allow manipulations on monitoring.coreos.com resources to operator within helm chart

- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/provisioner.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release we update the docs and manifest versions to v1.4.5
**Checklist:**
[skip ci]
> build: update release versions to v1.4.5

- pkg/operator/ceph/cluster/osd/spec.go
During the initialization encrypted OSD initialization sequence, we check
for the presence of the encrypted container. If it exists we don't try
to open it again since this will result in an error.
However, there is another case we need to handle, when the underlying
device is gone. For instance, if the pod/PV couple was drained and move
back, living the orphan dm. Once the pod comes back, the dm is still
present and perfectly matches. Unfortunately, the underlying disk is
different and thus the dm must be removed and the disk re-opened.
**Checklist:**
> ceph: check underlaying block status

- Documentation/ceph-object-bucket-claim.md
Remove wrong information from OBC CRD example
**Checklist:**
> docs: update obc documentation

- README.md
This updates the badge image url and removes one differently styled
badge design param.
**Checklist:**
[skip ci]
> docs: updated badge url

- README.md
To more quickly show the graduation status on the main readme, we add a badge that shows rook is graduated.
**Checklist:**
> docs: Add a badge for graduation status

- pkg/operator/ceph/object/zone/controller.go
- pkg/operator/ceph/object/zone/controller_test.go
Add unit tests for CephObjectZone controller.
Resolves #
**Checklist:**
> ceph: add unit tests for object/zone

- tests/README.md
- tests/framework/installer/ceph_installer.go
- tests/integration/ceph_multi_cluster_test.go
Fix tests/README.md for users to use proper test tools. Use "go test..." rather than "_output/tests/integration".
Nothing
**Checklist:**
- [o] Reviewed the …
> ci: ceph fix tests/README.md

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
An '--upgrade' option is added to the option list, which upgrades the user
permissions (caps) to match newer version.
Resolves #
**Checklist:**
> ceph: adding '--upgrade' option to external script

- pkg/daemon/ceph/osd/volume.go
When deploying on non-PVC, we still need to gather c-v logs on failures.
Now if the bootstrap fails, the c-v log will be printed.
Resolves #
**Checklist:**
> ceph: add ceph-volume log to non-pvc scenario

- .github/workflows/canary-integration-test.yml
- cluster/examples/kubernetes/ceph/nfs-test.yaml
- hack/validate_cluster.sh
The CI runs a github action that builds and deploys a Rook cluster and
then execute various tests on the create-external-cluster-resources.py
script.
Resolves #
**Checklist:**
[skip ci]
> ci: add integration test for external python script

- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/provisioner.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
The manifests and docs are now updated for the v1.4.6 release.
**Checklist:**
> build: Update manifests for v1.4.6 release

- CODE-OWNERS
- OWNERS.md
Add a new Ceph maintainer.
Nothing
**Checklist:** …
> ceph: add a maintainer

- go.mod
using v0.0.0 is causing issues with unknown version even
though the replace block uses correct version. So updating
requires block to match replaces block version.
Resolves #6428 
**Checklist:**
> fixing "requires" for kube-controller-manager

- Documentation/nfs.md
- cluster/examples/kubernetes/nfs/nfs-ceph.yaml
- cluster/examples/kubernetes/nfs/nfs.yaml
- cluster/examples/kubernetes/nfs/psp.yaml
- cluster/examples/kubernetes/nfs/rbac.yaml
(cherry picked from commit c22189ba74616e2829a0678516395c3bdb212caa)
We need to backport PR #6440 to `release-1.4` as well
Resolves #
**Checklist:**
[skip ci]
> nfs: update documentation and example

- Documentation/ceph-disaster-recovery.md
The paranthesis around the arguments have been removed to pass the value
Eg: ROOK_CEPH_MON_INITIAL_MEMBERS
Signed-off-by: MG <gmadhavi@gmail.com>
Resolves #
**Checklist:**
[skip ci]
> docs: Ceph disaster recovery

- Documentation/nfs.md
> Remove provisioner from nfs docs

- Documentation/nfs.md
- cluster/examples/kubernetes/nfs/nfs-xfs.yaml
- cmd/rook/nfs/provisioner.go
- images/nfs/Dockerfile
- pkg/operator/nfs/provisioner.go
- pkg/operator/nfs/provisioner_test.go
- pkg/operator/nfs/quota.go
- pkg/operator/nfs/quota_fake.go
Design #6112
Resolves #5788 
**Checklist:**
> nfs: implement disk quota

- .github/workflows/canary-integration-test.yml
- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Changes related to Monitoring endpoint
a. for any monitoring endpoint and port (either user given through arguments
or internally found), added code to make sure we convert the endpoint
host_name to a proper IP address.
b. checks added to make sure we have a valid and reachable endpoint
Resolves #
**Checklist:**
> ceph: added additional checks on accepting monitoring endpoint

- pkg/daemon/ceph/osd/remove.go
The osd purge job was not removing the osd prepare job or the osd pvc due to an invalid label query for the pvc. Now the prepare job and pvc will be removed as expected from the job.
**Checklist:**
> ceph: Remove the osd pvc when purging the osd

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/charts/rook-ceph/templates/role.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.4-apply.yaml
- tests/framework/installer/ceph_manifests.go
as we are approaching the rook 1.5 release, we are making the required RBAC changes for cephcsi ahead of the cephcsi release to provide a smooth upgrade experience for the users without any RBAC changes in rook minor release.
Resolves #
**Checklist:**
[test ceph]
> ceph: update required rbac for csi

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
On top of https://github.com/rook/rook/pull/6504, need rebase.
Resolves #
**Checklist:**
[skip ci]
> ceph: lint exporter script file

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Some cosmetic changes and an extra negative test
Resolves #
**Checklist:**
> ceph: some minor changes to external python script

- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/provisioner.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
Update the manifest versions to v1.4.7 for the patch release.
**Checklist:**
> build: Update manifest version to v1.4.7

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/ceph/ceph-cluster-cleanup.md
- images/ceph/Makefile
- pkg/apis/ceph.rook.io/v1/types.go
For the v1.5 release we use the latest version of ceph by default.
**Checklist:**
> ceph: Update base image and examples to v15.2.5

- .mergify.yml
Update mergify to auto backport PR with label on release 1.5 branch and
auto-merge.
**Checklist:**
> bot: update mergify to release 1.5 branch

- .github/workflows/codespell.yaml
As a follow up to #6563 which fixed all the typos found in the
repository, to avoid adding more obvious typos.
Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>
**Checklist:**
> ci: .github/workflows: add codespell pipeline

- Documentation/helm-operator.md
push all helm2 user to upgrade to helm3 asap.
Signed-off-by: Deshi Xiao <xiaods@gmail.com>
Resolves #6460
**Checklist:**
> fix: issue#6460 remove helm2 section, upgrade helm3

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/nfs-test.yaml
- cluster/examples/kubernetes/ceph/nfs.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/nfs/spec.go
- tests/framework/installer/ceph_manifests.go
this commit allows changing the default 
log-level from nfs.yaml file by adding 
new command.
Resolves #6566 
**Checklist:**
> ceph: change nfs-ganesha log level

- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-stretched.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster-with-drive-groups.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- Some minor updates to the Ceph upgrade guide for the v1.5 release after final testing.
- The CRs must be created in a separate kubectl create command from the creation of the CRDs, otherwise the create command will fail.
**Checklist:**
[skip ci]
> docs: Minor updates to the 1.5 Ceph upgrade guide

- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-stretched.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster-with-drive-groups.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- Some minor updates to the Ceph upgrade guide for the v1.5 release after final testing.
- The CRs must be created in a separate kubectl create command from the creation of the CRDs, otherwise the create command will fail.
**Checklist:**
> docs: Minor updates to the 1.5 Ceph upgrade guide (bp #6629)

- .github/workflows/integration-test.yaml
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/environment.go
- tests/framework/utils/k8s_helper.go
as we are planning to move toward Github actions
for integration test. This commit runs ceph 
suites using Github action.
Resolves #
**Checklist:**
> ci: run integration test on github actions

- tests/scripts/create-bluestore-partitions.sh
- tests/scripts/localPathPV.sh
* Use sudo to read the disks
* Wait for partprobe and udev events to finish
Resolves https://github.com/rook/rook/issues/6580
**Checklist:**
> ci: fix device intermittent failure

- .github/workflows/build.yml
- .github/workflows/canary-integration-test.yml
- .github/workflows/codegen.yml
- .github/workflows/golangci-lint.yaml
- .github/workflows/mod-check.yml
- .github/workflows/unit-test.yml
- .mergify.yml
We now allow mergify to auto-merge pull requests against the master
branch under the following conditions:
* all CI tests passed
* the PR has no label 'do-not-merge'
* the PR has the label 'ready-to-merge'
* has been approved by at least one maintainer
* has not requested changes
Also, the CI will not run when no Go files have been modified.
We just validate Rook builds correctly.
**Checklist:**
[skip ci]
> bot: auto-merge pull request under conditions and do not run ci when no code changes

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
For the patch release we update the version to v1.5.1
**Checklist:**
[skip ci]
> build: Update release version to v1.5.1

- .github/workflows/codespell.yaml
- design/ceph/object/ceph-multisite-overview.md
- design/nfs/nfs.md
Make the bot happy.
**Checklist:**
> bot: fix codespell issue

- tests/scripts/minikube.sh
> Minikube script fixes

- tests/README.md
Fixed an example test name "TestARookClusterInstallation_SmokeTest". it was "TestRookClusterInstallation_SmokeTest" which is not existing in the test suites.
[skip ci]
None
**Checklist:**
> test: Fixed a wrong test suite name

- OWNERS.md
[skip ci]
Resolves #
**Checklist:**
> docs: update Blaine's email in OWNERS.md

- PendingReleaseNotes.md
The pending release notes were for v1.5, now cleared for adding v1.6 features.
**Checklist:**
> docs: Clear the pending release notes for 1.6

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-with-drive-groups.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/ceph/ceph-cluster-cleanup.md
- images/ceph/Makefile
- pkg/apis/ceph.rook.io/v1/types.go
With the release of the latest octopus v15.2.7 we update the base of the operator image and set the examples to use the same release to pick up the security and other bug fixes.
Resolves #6690 
**Checklist:**
> ceph: Update examples and base image to v15.2.7

- Documentation/ceph-cluster-crd.md
correct the name of policy mentioned
Resolves #
**Checklist:**
> docs: update vault kms integration doc

- pkg/operator/ceph/object/bucket/provisioner.go
Does not resolve 
**Checklist:**
> ceph: add more debug logging to obj bucket claims

- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/provisioner.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
For the patch release we update the manifest versions to v1.4.8.
**Checklist:**
[skip ci]
> build: Update release version to v1.4.8

- cluster/olm/ceph/generate-rook-csv.sh
It has been a couple of releases since we started deploying Rook along
with Ceph-CSI by default. So let's include Ceph-CSI natively in our CSV
generation.
Closes: https://github.com/rook/rook/issues/6659
Resolves https://github.com/rook/rook/issues/6659
**Checklist:**
> ceph: include csi by default in the csv

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
Update manifest versions to v1.5.2 for the release
**Checklist:**
[skip ci]
> build: Update manifest versions to v1.5.2 for the release

- cluster/examples/kubernetes/ceph/cluster.yaml
Uncomment the `cleanupPolicy:` so that the file can be injected.
Closes: https://github.com/rook/rook/issues/6762
Resolves https://github.com/rook/rook/issues/6762
**Checklist:**
> ceph: fix cluster.yaml example

- design/common/multiple-storage-types-support.md
Replace the old links which were broken.
Signed-off-by: aisuko <urakiny@gmail.com>
Resolves #6756
**Checklist:**
[skip ci]
> docs: Replace the broken addresses of the document

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
Update manifest versions to v1.5.3 for the critical release regarding potential data loss for OBCs. See #6767. 
**Checklist:**
[skip ci]
> build: Update manifest versions to v1.5.3 for the critical release

- go.sum
(cherry picked from commit e7ac118dd41781d2164be78237024b72ee0dd0f9)
Resolves #
**Checklist:**
> build: add missing junit line to go.sum

- pkg/operator/ceph/pool/controller_test.go
The TestCephBlockPoolController test is failing intermittently due to a failure to update the rbd mirroring status on the pool CR. Improve the test reliability by trying again several times if needed.
Resolves #6736 
**Checklist:**
> ceph: Retry mirror status update in tests

- pkg/operator/ceph/object/rgw.go
The legacy rgw deployments were removed in 1.0, so there is no more need for the operator to keep checking for those!
**Checklist:**
> ceph: No need for removal of legacy rgw deployments

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release we update the version to v1.5.4
**Checklist:**
> build: Update release manifest version to v1.5.4

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-upgrade.md
Fix advanced config doc link on the quickstart guide to the advanced configuration for clusters in multiple namespaces.
Resolves #6882 
**Checklist:**
> docs: Fix advanced config doc link on the quickstart guide

- Documentation/ceph-osd-mgmt.md
Current document of OSD removal only describe the case of broken OSDs.
Nothing
**Checklist:** …
> docs describe how to remove healthy Ceph OSDs

- Documentation/helm-operator.md
- Jenkinsfile
- build/makelib/helm.mk
- cluster/charts/rook-ceph/Chart.yaml
- cluster/charts/rook-ceph/templates/NOTES.txt
- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/charts/rook-ceph/templates/clusterrolebinding.yaml
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/charts/rook-ceph/templates/role.yaml
- cluster/charts/rook-ceph/templates/rolebinding.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/environment.go
- tests/framework/utils/helm_helper.go
- tests/integration/ceph_multi_cluster_test.go
- tests/scripts/helm.sh
In the interest of getting helm working in the release-1.4 branch, we now convert to helm 3 in that branch as well. The changes in #6891 to attempt to continue using helm 2 are not yet working and may be simpler to backport these changes from 1.5 to 1.4. However, the original change in #6556 is much bigger than we want to backport to 1.4. This just includes the minimal to build with helm 3.
- Convert the resources from v1beta1 to v1
- Use helm 3
- Update the integration tests
Resolves #6887
**Checklist:**
> Update the v1.4 release branch to Helm 3

- pkg/operator/ceph/controller/controller_utils.go
After the operator restarts, the controllers will not all be able to reconcile until the ceph config has been generated by the reconcile of the CephCluster controller. The message printed to the operator log is frequently seen as an error condition even though it is a normal condition where we requeue the reconcile until the config is available.
**Checklist:**
> ceph: Suppress reconcile error after operator restart

- pkg/operator/ceph/object/user.go
DeleteUser was returning error "failed to delete user ... with buckets"
without corresponding buckets information. Now it will check buckets, If
buckets are present then return error with buckets info.
While deleting a user which contains buckets rook does not log info about buckets in error msg when it fails. With these changes, now rook will log a list of buckets also. 
Resolves #
**Checklist:**
> ceph: enhance delete cephObjectStoreUser logging

- Documentation/admission-controller-usage.md
this commit update the paths in
admission controller quick start doc.
Resolves #
**Checklist:**
> doc: update path in admission controller quick start doc

- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/provisioner.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release we update the manifest and doc version
to v1.4.9
**Checklist:**
[skip ci]
> build: Set release version to v1.4.9

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release we update the manifest and doc version to v1.5.5
**Checklist:**
[skip ci]
> build: Set release version to v1.5.5

- pkg/operator/ceph/object/objectstore.go
If the object store is not found during deletion of the object store CR, proceed with the deletion instead of blocking and re-queueing the deletion reconcile in an endless loop. This was causing instability in the integration tests.
**Checklist:**
> ceph: During object store deletion return success if not found

- ROADMAP.md
Update the roadmap for rook v1.6 with known high-level work items.
**Checklist:**
> docs: Update the roadmap for rook v1.6

- CODE-OWNERS
- OWNERS.md
Dmitry is no longer participating in Rook and has moved on from the EdgeFS team. Thanks @dyusupov for all your contributions!
The position on the steering committee is now open. Per the governance, we are looking for an owner of a storage provider other than Ceph who has overall perspective and interest in taking Rook forward.
**Checklist:**
> docs: Remove inactive member from steering committee

- go.mod
- images/cross/Dockerfile
Update the cross build container to use golang 1.15.6 instead of 1.13.8. The update to build with 1.15 had only been made in the AMI, and is now updated in the container as well. Golang 1.15 is required in the latest master builds.
**Checklist:**
> ci: Build with golang 1.15.7

- Documentation/ceph-disaster-recovery.md
Update docs to stop livenessProbe to prevent pod deletion while operation.
Resolves #
**Checklist:**
> docs: stop livenessProbe

- Documentation/storage-providers.md
The expectations for storage provider development are now set forth for joining Rook and maintaining existing storage providers. This will help ensure the longevity of storage providers in the project and for the health of the community.
This doc is proposed to show up under the "Contributing" node of the table of contents.
On a related note, see the [proposal for maintaining or removing storage providers](https://docs.google.com/document/d/1TSPfqX3D08lN5RjIf2wbQideIMOv09bXreRMUFzIycY/edit) that do not have sufficient community support.
**Checklist:**
> docs: Expectations for storage provider development

- cluster/olm/ceph/generate-rook-csv.sh
It looks like combining --append with --overwrite will cause duplicate
entries of our CRDs in the CSV definition. Removing the flag fixes the
duplicates.
Diff before and after the fix:
```
1118c1118
<     createdAt: 2021-01-22T11-07-27Z
---
>     createdAt: 2021-01-22T11-06-24Z
1126a1127,1159
>       - kind: CephBlockPool
>         name: cephblockpools.ceph.rook.io
>         version: v1
>       - kind: CephClient
>         name: cephclients.ceph.rook.io
>         version: v1
>       - kind: CephCluster
>         name: cephclusters.ceph.rook.io
>         version: v1
>       - kind: CephFilesystem
>         name: cephfilesystems.ceph.rook.io
>         version: v1
>       - kind: CephNFS
>         name: cephnfses.ceph.rook.io
>         version: v1
>       - …
```
> ceph: remove the append flag when overriding

- design/ceph/object/ceph-bucket-notification-crd.md
This documents the Ceph topics and buckets notification management by rook through CRs.
Signed-off-by: Guillaume Moutier <guillaume.moutier@gmail.com>
Resolves #
**Checklist:**
[skip ci]
> ceph: bucket notifications CRD documentation

- OWNERS.md
The "Friends of Rook" section in OWNERS.md has long been outdated. With the growing community it is really impossible to keep an active list of those who are contributing to the project. Thanks to the community for all the support! 
As discussed in the community meeting there are other ways to find who is active in the project such as looking at github contributions, issues, PRs, and joining the Slack community.
**Checklist:**
> docs: Replace friends of rook with community

- build/codegen/codegen.sh
See individual commits.
Resolves #
**Checklist:**
> ceph: fix code generation

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the release the versions are now updated to v1.5.6.
**Checklist:**
[skip ci]
> build: Update manifest versions to v1.5.6 for the release

- tests/framework/installer/ceph_installer.go
disable admission controller for helm suite.
v1 version of admissionregistration.k8s.io/v1
require minimum v1.16.0 of k8s. All other suite
was disabled earlier this was left.
Resolves #
**Checklist:**
[test full]
> ceph: disable admission controller for helm suite 

- cluster/examples/kubernetes/ceph/object-openshift.yaml
this commit ceph: create a route as
a part of the example in `object-openshift.yaml`.
Route is a feature of OpenShift so, changes
are only for object-openshift.yaml.
Resolves #
**Checklist:**
> ceph: create a route for ceph-rgw

- build/codegen/codegen.sh
- tests/scripts/validate_modified_files.sh
Fix code generation, resync boiler plate and fails if any files are found when running `make codegen`.
Resolves https://github.com/rook/rook/issues/7074
**Checklist:**
> ceph: fix codegen (again)

- pkg/operator/ceph/csi/csi.go
Before this patch, csi detection will run whether or
not rbd and cephfs are all disabled. Run detection only
if it is necessary.
Before this patch, csi detection will run whether or
not rbd and cephfs are all disabled. Run detection only
if it is necessary.
Resolves #
**Checklist:**
> ceph: skip csi detection if CSI is disabled

- pkg/operator/ceph/disruption/clusterdisruption/add.go
PDB watcher watches for all namespaces. This PR updates the PDB watcher to watch for only operator namespace.
It also updates the watcher not to reconcile for create and delete events.
Resolves #7011
**Checklist:**
> ceph: skip reconcile on PDBs are created, deleted and when on different namespace

- tests/framework/installer/ceph_installer.go
integration test was failing frequently due to some
intermittent failures.
```
Error from server (InternalError): error when creating
"STDIN": Internal error occurred: failed calling webhook.
```
(This error is not coming from us most probably)
This is kind of workaround so we get a green build
as we still don't know the root cause till now.
Resolves #7102 
**Checklist:**
[test full]
> ceph: Intermittent integration test failures due to admission controller

- pkg/operator/ceph/cluster/crash/crash.go
- pkg/operator/ceph/disruption/machinedisruption/reconcile.go
- pkg/operator/ceph/object/realm/controller.go
Some settinc controller reference code can be replaced with `controllerutil.SetControllerReference`. It's better to use it since it provides ownerReference verification.
**Checklist:**
- [o] Reviewed the …
> ceph: replace setting controller reference with utility function

- pkg/operator/ceph/cluster/osd/spec.go
Wrong file was used...
Resolves #
**Checklist:**
> ceph: fix wrong payload path

- pkg/operator/ceph/config/conditions.go
Order CephCluster false condition before its corresponding true Ready condition.
Resolves #6977
**Checklist:**
> ceph: Order CephCluster false condition before true Ready condition

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release today, the release version will be v1.5.7.
**Checklist:**
[skip ci]
> build: Update the release version to v1.5.7

- Documentation/ceph-object.md
Avoids use of grep and awk.
Supersedes #7023 
Resolves #
**Checklist:**
> docs: use -o jsonpath in ceph-object.md

- pkg/operator/ceph/cluster/osd/osd.go
We were missing the error.
Resolves #
**Checklist:**
> ceph: embed error in return

- pkg/daemon/ceph/osd/kms/vault.go
If the cluster was expanded we would iterate over the entire list of
OSDs again, create a new key and override in Vault... The Secret store
is not impacted since we have a handler for "already exist".
Resolves #
**Checklist:**
> ceph: do not override existing keys

- Documentation/ceph-block.md
- Documentation/ceph-examples.md
- Documentation/ceph-filesystem-crd.md
- Documentation/ceph-filesystem.md
- Documentation/ceph-fs-mirror-crd.md
- Documentation/ceph-object-multisite.md
- Documentation/ceph-openshift.md
- Documentation/ceph-rbd-mirror-crd.md
- Documentation/k8s-pre-reqs.md
The links from the documentation to github need to use the branch name in order to point to the correct path. The docs should reference a common script that will parse the branch name instead of copying the script contents to all the docs.
A couple links were broken because this script was not being included.
**Checklist:**
> docs: Include doc script for referencing github branches

- Documentation/ceph-cluster-crd.md
- design/ceph/update-osds-in-parallel.md
> design: add design to update ceph osds in parallel

- pkg/apis/rook.io/v1/placement.go
- pkg/apis/rook.io/v1/placement_test.go
- pkg/operator/ceph/cluster/cleanup.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/cluster/version.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/nfs/spec.go
- pkg/operator/edgefs/cluster/mgr/mgr.go
- pkg/operator/edgefs/cluster/prepare/prepare.go
- pkg/operator/edgefs/cluster/target/pod.go
- pkg/operator/edgefs/iscsi/iscsi.go
- pkg/operator/edgefs/isgw/isgw.go
- pkg/operator/edgefs/nfs/nfs.go
- pkg/operator/edgefs/s3/s3.go
- pkg/operator/edgefs/s3x/s3x.go
- pkg/operator/edgefs/smb/smb.go
- pkg/operator/edgefs/swift/swift.go
- pkg/operator/k8sutil/pod.go
this commit is kind of bp PR for 7192 and 7247
directly to release branch as there was conflicts
due some removed stroage providers.
Resolves #
**Checklist:**
> ceph: do not merge nodeAffinity (bp #7192)

- Documentation/nfs.md
Resolves #
**Checklist:**
[skip ci]
> nfs: the number of containers displayed is wrong due to sidecar

- pkg/daemon/ceph/client/upgrade.go
- pkg/operator/ceph/file/mirror/config.go
- pkg/operator/ceph/file/mirror/controller.go
- pkg/operator/ceph/file/mirror/mirror.go
- pkg/operator/ceph/file/mirror/spec.go
- pkg/operator/ceph/file/mirror/spec_test.go
- pkg/operator/ceph/test/podspec.go
See commit messages.
**Checklist:**
> ceph: misc improvement for the ceph-fs-mirror implementation

- Documentation/ceph-common-issues.md
For common slack questions... Forming mon quorum is one of the most common issues to troubleshoot when starting a new cluster, whether it is the network configuration or the previous install was not cleaned properly.
**Checklist:**
> docs: Additional network troubleshooting details for mons

- pkg/operator/ceph/cluster/osd/osd_pvc_test.go
This was a race condition where the test would sometimes finish before a
deferred watcher.Stop() command was called and sometimes would not.
Resolves #
**Checklist:**
> ceph: fix flaky OSD on PVC unit test

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
The patch release version is now v1.5.8
**Checklist:**
[skip ci]
> build: update release version to v1.5.8

- .github/workflows/build.yml
- .github/workflows/codegen.yml
- .github/workflows/mod-check.yml
- .github/workflows/unit-test.yml
- tests/scripts/validate_modified_files.sh
Look at individual commit message.
Resolves #7287 
**Checklist:**
[skip ci]
> ci: fix codegen err

- Documentation/ceph-osd-mgmt.md
**Description of your changes:** 
The osd purge job link requires an absolute url depending on the branch name since links to the examples do not work as relative paths.
**Checklist:**
> docs: Fix link to the sample osd purge job

- tests/manifests/test-cluster-on-pvc-encrypted.yaml
The latest 14.2.14 has all the patches that are needed for KMS.
Resolves #
**Checklist:**
> ceph: use latest stable nautilus

- pkg/operator/ceph/cluster/osd/spec.go
The API path when the KV enfine is used in version is different and must
be adapted. We need to append a 'data' path, thus the path and response
are changing.
v1 is https://vault.local.com:8200/v1/test-kv1/key
v2 is https://vault.local.com:8200/v1/test-kv2/data/key
Resolves #
**Checklist:**
> ceph: fix vault when used with kv version 2

- tests/README.md
Although the integration test creates test logs, the location is not documented yet.
**Checklist:** …
> ci: describe the location of test logs

- .github/workflows/yaml-lint.yaml
- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules-external.yaml
- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
- cluster/examples/kubernetes/ceph/monitoring/prometheus-service.yaml
- cluster/examples/kubernetes/ceph/monitoring/prometheus.yaml
- cluster/examples/kubernetes/ceph/monitoring/rbac.yaml
- cluster/examples/kubernetes/ceph/monitoring/service-monitor.yaml
this commit add monitoring folder to yamllint
ignore list.
Resolves #
**Checklist:**
> ceph: ignore monitoring folder from yamllint

- pkg/operator/ceph/cluster/controller.go
deletion of cluster is stuck when cluster is not configured. The PR skips the cleanup and removes the finalizers if the cluster was not configured, that is, if clusterInfo could not be loaded.
Resolves #
**Checklist:**
> ceph: skip cleanup if cluster is not configured correctly.

- .github/workflows/canary-integration-test.yml
- tests/scripts/create-bluestore-partitions.sh
- tests/scripts/localPathPV.sh
- tests/scripts/validate_cluster.sh
We now create 2 disks that will give us 2 OSDs and potentially help us
to catch more errors in our scenarios, especially on iterations.
Resolves #
**Checklist:**
> ceph: add more osds to the ci

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
Update the example manifests and docs to v1.5.9 for the patch release
**Checklist:**
[skip ci]
> build: Updated release version to v1.5.9

- .github/workflows/.yamllint
- .github/workflows/yaml-lint.yaml
this commit silence yamllint warnings
Resolves #
**Checklist:**
> ci: silence yamllint warnings

- pkg/daemon/ceph/osd/kms/envs.go
- pkg/daemon/ceph/osd/kms/envs_test.go
- pkg/operator/ceph/cluster/osd/spec.go
See commits.
Resolves #
**Checklist:**
> ceph: set default backend for vault and remove temp key

- .github/workflows/crds-gen.yml
- Makefile
- build/crds/build-crds.sh
- rename "make crds-gen" to "make crds"
- always pull the version of controller-gen and yq instead of relying on the system binaries
Resolves #
**Checklist:**
> ceph: simply "make crds"

- tests/scripts/validate_modified_files.sh
this commit update make crds-gen to make crds
Resolves #
**Checklist:**
[skip ci]
> ci: update make crds-gen to make crds

- Documentation/ceph-nfs-crd.md
Added creation of NFS exports in the documentation.
Closes: https://github.com/rook/rook/issues/7064
Signed-off-by: parth-gr <partharora1010@gmail.com>
Resolves #
**Checklist:**
> docs: updated the documentation of ceph-nfs-crd

- .github/workflows/codespell.yaml
- pkg/operator/ceph/cluster/predicate_test.go
- pkg/operator/ceph/cluster/watcher_test.go
- pkg/operator/ceph/controller/predicate_test.go
- pkg/operator/nfs/server.go
- pkg/operator/test/volumes_test.go
Document codespell flags that are necessary. Remove codespell flags with
minor code changes if possible.
Resolves #
**Checklist:**
> test: document or clean up codespell flags

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
Since the recent auto crds generation, I missed a few fields, re-adding
now:
* additionalPrinterColumns
* min and max
Resolves #
**Checklist:**
> ceph: add a few missing crd fields

- images/ceph/Makefile
Signed-off-by: Michael Adam <obnox@redhat.com>
Make sure the crds are generated so that they are added to the ceph image.
Resolves #
**Checklist:**
> ceph: fix image generation by generating crds to be included

- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/mime.go
- pkg/operator/ceph/object/objectstore.go
See commit messages.
Resolves #
**Checklist:**
> ceph: enforce pg_auto_scaler on rgw pools

- build/crds/build-crds.sh
On mac the make crds command was failing on the sed commands. Now we remove the dependency on sed and just append the files to generate the helm resources
**Checklist:**
> ceph: Compatibility for generating crds without sed

- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
this commit enable IT test to run on master push.
Resolves #
**Checklist:**
> ci: Enable master and release branch integration tests on push

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/nfs.md
- Jenkinsfile
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- design/nfs/nfs-controller-runtime.md
- design/nfs/nfs-provisioner-controlled-by-operator.md
- tests/integration/ceph_base_deploy_test.go
Resolves #
- The CI in the release branch will run back to k8s v1.11
- In the documentation and example manifests set the beta.0 release version for v1.6.0 in preparation for the release soon.
**Checklist:**
[skip ci]
> build: Changes to prepare for the release-1.6.0-beta.0 release

- .mergify.yml
// skip jenkins
[skip ci]
Resolves #
**Checklist:**
> bot: auto backport on  backport-release-1.6 label

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
> ceph: add status subresource to CRDS

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
this commit update the github action
minikube version as minikube setup on
latest k8s version are failing.
closes: #7542 
Resolves #7542 
**Checklist:**
> ci: update minikube version

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v16-rules-external.yaml
- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v16-rules.yaml
New release, new files!
Resolves #
**Checklist:**
> ceph: add monitoring rules for pacific

- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
We have seen the CI failing to run the minikube action, reaching the API
limit. By using authenticated requests, we can overcome this limitation.
Follow-up of https://github.com/rook/rook/pull/7503/commits/1504fb869b5ed5b8f7df362bc9df3b45dd8ac9ea
(cherry picked from commit 15901277d57bf39ce1d8c5939abad510139ee792)
Resolves #
**Checklist:**
**BACKPORT OF #7585**
> ci: use authenticated requests for minikube action on suite (bp #7585)

- .mergify.yml
We need to pass the complete name of the action.
Resolves #
**Checklist:**
[skip ci]
> bot: fix mergify auto-merge rule

- .github/workflows/golangci-lint.yaml
This action wasn't not running on release branch. Now enabling it.
(cherry picked from commit 89f4c4a81a577429c19c30f759604d33c032e925)
Resolves #
**Checklist:**
[skip ci]
> ci: always run golangci-lint

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
add quota usage alerts for pools with quota set.
Resolves #
**Checklist:**
[skip ci]
> ceph: add pool quota usage alerts

- pkg/operator/ceph/client/controller.go
- pkg/operator/ceph/config/keyring/store_test.go
- pkg/operator/ceph/controller/spec_test.go
- pkg/operator/ceph/disruption/clusterdisruption/osd.go
- pkg/operator/ceph/disruption/clusterdisruption/osd_test.go
- pkg/operator/ceph/nfs/nfs.go
- pkg/operator/ceph/nfs/spec_test.go
- pkg/operator/ceph/pool/validate.go
- pkg/operator/ceph/provisioner/provisioner.go
This fixes additional double-imports.
Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
**Checklist:**
> ceph: fix multiple imports

- Documentation/ceph-upgrade.md
Resolves #7528 
**Checklist:**
> update Ceph upgrade docs for 1.6

- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/dashboard_test.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/objectstore_test.go
ceph: update ceph dashboard credential command
in the latest ceph releases, there are
few changes in ceph commands to access
ceph dashboard. This commit update
ceph dashboard credentials command.
Older command
```
ceph dashboard set-login-credentials <username> <password>
```
New command
```
ceph dashboard ac-user-create <username> -i <file-containing-password> administrator
```
Closes: #7498
Resolves #7498 
**Checklist:**
> ceph: update ceph dashboard credential command

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release the example manifests and documentation is updated to v1.5.10
**Checklist:**
[skip ci]
> build: Update release version to v1.5.10

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- design/nfs/nfs-controller-runtime.md
- design/nfs/nfs-provisioner-controlled-by-operator.md
> build: update images 1.6.0-beta.0 -> 1.6.0

- go.sum
The build is failing due to missing imports for go.sum.
**Checklist:**
[skip ci]
> build: Package updates for go.sum in the release-1.5 branch

- pkg/operator/ceph/object/admin.go
related to #7600 
Resolves #
**Checklist:**
> ceph: change radosgw-admin workaround log to debug

- .github/workflows/canary-integration-test.yml
- Documentation/ceph-advanced-configuration.md
- cluster/examples/kubernetes/ceph/common-second-cluster.yaml
Long due but finally there, the CI now test the block mirroring between
2 clusters.
Resolves #
**Checklist:**
[test ceph]
> ci: add rbd-mirror integration test

- .github/workflows/canary-integration-test.yml
- .github/workflows/macos-build.yml
- Documentation/ceph-advanced-configuration.md
- Makefile
- build/crds/build-crds.sh
- build/makelib/golang.mk
- cluster/examples/kubernetes/ceph/common-second-cluster.yaml
- images/ceph/Makefile
Backports of ci: add rbd-mirror integration test (bp #7623) and build and run various make commands on MacOS (bp #7691)
> ci: add rbd-mirror integration test (bp #7623) and build and run various make commands on MacOS (bp #7691)

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
The device class can be any arbitrary value for a pool, depending on the device class either automatically detected for the OSDs or an arbitrary device class applied to OSDs in the cluster.
**Checklist:**
> ceph: Allow any device class for the osds in a pool

- Makefile
- images/cross/Dockerfile
No need to include darwin and windows in the list of platforms since rook is only containerized and expected to run in a linux environment. This should slightly speed up the build, but otherwise not expecting any side effects. The non-containerized standalone client artifacts have not been needed since support for standalone rook was removed long ago.
**Checklist:**
> build: Only build linux platform

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/ceph/ceph-cluster-cleanup.md
- pkg/apis/ceph.rook.io/v1/types.go
The latest octopus release is v15.2.11 so we should use it in the default examples to pick up the latest fixes.
**Checklist:**
> ceph: Example manifests to deploy with v15.2.11

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- design/nfs/nfs-controller-runtime.md
- design/nfs/nfs-provisioner-controlled-by-operator.md
The new release version for documentation and example manifests is v1.6.1
**Checklist:**
[skip ci]
> build: Set release version to v1.6.1

- Documentation/ceph-cluster-crd.md
**Checklist:**
- [o] Documentation has been updated, if …
> docs: fix ceph pacific related descriptions

- tests/integration/ceph_base_object_test.go
Add an integration regression test for Ceph Object Storage Object Bucket
Claim (OBC) to verify that the OBC stays in "Bound" state after being
created. The claim should not fall back into "Pending" (or any other)
state soon after being created.
This is a re-do of #6752 
Resolves #
**Checklist:**
> ceph: add regression test for obc infinite pending

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-cassandra-suite.yaml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- tests/scripts/github-action-helper.sh
we have lots of duplicate codes for
github action. this commit refactor
them to a bash script which will minimize
duplicate codes.
Resolves #7376 
**Checklist:**
> ci: improve github action writing

- pkg/operator/nfs/controller_test.go
This removes multiple imports.
Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
**Checklist:**
> nfs: fix multiple imports

- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/health.go
- pkg/operator/ceph/object/rgw.go
OBC operations will fail if RGW only enabled HTTPS. With this change, OBC operations
will use needed TLS certs to succeed in the operation. Similar changes were made into healthcheck and liveprobe code path of RGW
Resolves #
**Checklist:**
> ceph: support for OBC operations if it uses TLS RGW endpoint 

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
add a Phase to columns that should be printed
Resolves #
**Checklist:**
> ceph: add phase to cephfilesystems crd

- PendingReleaseNotes.md
- pkg/daemon/ceph/client/filesystem.go
- pkg/daemon/ceph/client/filesystem_test.go
- pkg/operator/ceph/file/filesystem_test.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/file/mds/spec.go
Upgrading mds requires extra steps than simply
replacing ceph image.
Resolves #7373 [updated by @BlaineEXE]
**Checklist:**
> ceph: complete missing steps of upgrading mds

- .github/workflows/build.yml
- cluster/olm/ceph/generate-rook-csv.sh
- images/ceph/Makefile
- tests/scripts/github-action-helper.sh
See commits.
Resolves https://github.com/rook/rook/issues/7655
**Checklist:**
> build: fix parallel build 

- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
updating cephcsi to the latest v3.2 release which includes the CVE bugfix.
Release details at https://github.com/ceph/ceph-csi/releases/tag/v3.2.2
Resolves #
**Checklist:**
> ceph: update cephcsi to v3.2.2

- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
The deviceClass was only being set for LVM mode OSDs and was missed for the raw mode for non-PVC. Now the deviceClass will be set for all expected scenarios.
Resolves #7811 
**Checklist:**
> ceph: Set the device class on raw mode osds

- pkg/daemon/ceph/osd/volume_test.go
The unit test TestConfigureCVDevices was failing intermittently due to comparing the first element of the slice of two elements. The slice ordering is not guaranteed, which caused a failure intermittently. The test only compares the critical values in the test and no need to check elements of the slice.
**Checklist:**
> ceph: Fix intermittent volume unit test

- .github/workflows/push-build.yaml
- Jenkinsfile
- tests/scripts/build-release.sh
push build image to Dockerhub every time when
there is a push in the master branch using GH actions.
Resolves #
**Checklist:**
[skip ci]
> ci: push build images to Docker hub

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
Update the release version and example manifests to v1.6.2
**Checklist:**
[skip ci]
> build: Set the patch release to v1.6.2

- .github/workflows/push-build.yaml
- tests/scripts/build-release.sh
this commit update the api token
to use correct secret.
Resolves #
**Checklist:**
> ci: update action api token 

- Documentation/ceph-disaster-recovery.md
The JSON was invalid.
Resolves #
**Checklist:**
> doc: fix patch command

- tests/framework/installer/ceph_settings.go
We now retry up to 3 times if the manifest fails to be fetched online.
Closes: https://github.com/rook/rook/issues/7927
Resolves #
**Checklist:**
[skip ci]
> ci: retry when fetching online manifests

- .github/workflows/push-build.yaml
tags are missing in master pushed images
to shallow problem. this commit add command
to unshallow.
Resolves #7903 
**Checklist:**
> ci: add missing tag in master push images

- Documentation/ceph-dashboard.md
- cluster/examples/kubernetes/ceph/dashboard-ingress-https.yaml
The ingress kind is found in apiversion networking.k8s.io/v1 since K8s 1.19. We now update the examples to use v1 instead of v1beta1.
Resolves #7905 
**Checklist:**
> ceph: Updated dashboard ingress example for v1

- cluster/examples/kubernetes/ceph/rbdmirror.yaml
corrected the component in mirroring yaml and added appropriate mirroring related affinity example.
Resolves #
**Checklist:**
[skip ci]
> ceph: correct component in mirroring yaml

- .github/workflows/integration-test-nfs-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
this commit add github action for NFS
integration test.
Resolves #7934 
**Checklist:**
> nfs: add github action for NFS integration test

- pkg/operator/ceph/cluster/osd/spec.go
The 'ceph-volume raw list' command used to list OSDs on nodes by the
rook-ceph-osd-prepare- jobs return user-friendly device names (e.g.,
/dev/sda) rather than persistent device names. Friendly device names
often change when systems reboot, and even persistent device names can
change under certain circumstances (e.g., a disk controller is replaced
with a different one). To prevent OSD Pods created for raw OSDs on
nodes from crashing repeatedly if the device it was created with is
renamed, scan the list of OSDs on the host with 'ceph-volume raw list'
to find the right OSD to activate in the OSD pod's OSD activation init
container.
Fixes #7918
**Tested this is working by:**
1. Stop my single-node K8s cluster VM (vbox)
2. Edit the SATA port order for the disks while the VM is stopped to …
> ceph: scan raw OSDs on nodes in OSD init container

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
The patch release version is updated to v1.6.3
**Checklist:**
[skip ci]
> build: Set release version to v1.6.3

- .github/workflows/helm-lint.yaml
adding GitHub action for helm lint to catch the static check errors in helm charts.
Resolves #
**Checklist:**
[skip ci]
> ceph: add github action for helm lint

- tests/scripts/deploy_admission_controller.sh
see individual commits.
Resolves #7955 #7876 
**Checklist:**
> ceph: fix cert manager errors

- README.md
As discussed in the community meeting, the build status is only interesting to maintainers of the project and is not relevant to community members who are considering running the project. The release builds are always considered stable. Whether the master build is intermittently failing is not important to the community.
Separately, to ensure emails on the topics of security questions are sent to the correct list, another link is added to the list of contacts.
**Checklist:**
> docs: Remove build status badge

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
With the patch release the examples are updated to v1.5.12
**Checklist:**
[skip ci]
> build: Set release version to v1.5.12

- Documentation/ceph-teardown.md
update ceph teardown doc to include cleanupPolicy which enables automatic clean up of the dataDirHostPath and the drives
Resolves #7312
**Checklist:**
[skip ci]
> docs: update ceph-teardown doc

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
With the patch release update the example manifests to the new version.
**Checklist:**
[skip ci]
> build: Set release version to v1.6.4

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
The version is updated for the latest patch release v1.6.5.
**Checklist:**
[skip ci]
> build: Update the release version to v1.6.5

- pkg/operator/ceph/cluster/controller.go
Investigate a possible memory leak around CephCluster cleanup's
stopCleanupCh channel. Add more close() statements and comment that Go's
garbage collector is able to close the channel when there are no more
referents to the channel.
Resolves #8106 
**Checklist:**
> ceph: handle CephCluster stopCleanupCh better

- pkg/operator/ceph/cluster/crash/add.go
- pkg/operator/ceph/cluster/crash/crash.go
- pkg/operator/ceph/cluster/crash/crash_test.go
- pkg/operator/ceph/cluster/crash/reconcile.go
this commit update cronjob from v1beta1 to v1
Resolves #7837 
**Checklist:**
> ceph: update cronjob from v1beta1 to v1

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
If there is no rgw endpoint provided, let's not try to create the user.
Resolves #
**Checklist:**
> ceph: only require rgw-admin-ops user when an endpoint is provided

- pkg/operator/ceph/cluster/osd/spec.go
When evaluating the potential "warning" key from the json output we were
not hiding stdout (1) from the output, so the key was leaked. Also the
warning check for the key was not perfect, it only checked for the
command to succeed, but we should introspect it since the "warning" key
is always present unlike the "error" one.
We now only print the warning or the error is present.
Resolves #
**Checklist:**
> ceph: do not leak key encryption key

- .github/workflows/build.yml
- .github/workflows/canary-integration-test-arm64.yml
- .github/workflows/canary-integration-test.yml
- .github/workflows/codegen.yml
- .github/workflows/crds-gen.yml
- .github/workflows/integration-test-cassandra-suite.yaml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-nfs-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- .github/workflows/mod-check.yml
- .github/workflows/push-build.yaml
- .github/workflows/unit-test.yml
For all Rook-maintained GH actions, use a default shell that has xtrace
enabled to help debug any errors.
Enable xtrace on all actions except these that use only external tools:
- codespell
- commitlint (wagoid/commitlint)
- golangci-lint
- helm-lint (chart-testing)
- stale
- yamllint
Help debug https://github.com/rook/rook/issues/8126
**Checklist:**
> test: add xtrace logging to github actions

- .github/workflows/canary-integration-test.yml
The ceph-mgr needs some time to come up so we need to wait for an IP
address to be available.
Closes: https://github.com/rook/rook/issues/8126
Resolves #
**Checklist:**
> ci: wait for the ceph-mgr IP to be available

- cluster/examples/kubernetes/ceph/cluster-test.yaml
Hoping to solve some flappy OSD preparation in the CI.
More information in the issue.
Closes: https://github.com/rook/rook/issues/7728
Resolves #
**Checklist:**
> ci: try to mitigate runner I/O errors

- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
In a production cluster we never should have two mons running on the same node. However, if two mons have ended up on the same node, whether from a bug or some other unintentional event, the operator will evict one of them and failover to a new mon. This only applies when allowMultiplePerNode is false.
**Checklist:**
> ceph: Evict a mon if colocated with another mon

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
For the patch release we update the example manifests
**Checklist:**
[skip ci]
> build: Update release version to v1.6.6

- .github/workflows/canary-integration-test.yml
- .github/workflows/commitlint.yml
- .github/workflows/helm-lint.yaml
- .github/workflows/integration-test-cassandra-suite.yaml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-nfs-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- .github/workflows/yaml-lint.yaml
this commit update the versions in the
action. example minikube, python, commitlint
and others.
Resolves #
**Checklist:**
> ci: update versions in the gh action

- tests/scripts/github-action-helper.sh
We have seen cases where the build might fail due to a small network
hiccup so let's retry up to 3 times if this is the case. **look at https://github.com/rook/rook/commit/3ea0a69d3a541903100b903c516483f2fe87c8a7`, it's the relevant change.**
Resolves #
**Checklist:**
> ci: retry build on network failures

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
The script will now accept a certificate that later will be configured
by the operator.
Resolves https://github.com/rook/rook/issues/7804
**Checklist:**
> ceph: add tls support to external rgw endpoint

- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
this commit remove read access from kube
config file for group and others.
Resolves #8169 
**Checklist:**
> ci: remove read access from kube config

- PendingReleaseNotes.md
New features were in the "breaking changes" section.
Resolves #
**Checklist:**
> docs: add news feature in the features section

- pkg/operator/ceph/pool/controller.go
update blockPoolChannel `monitoringRunning` field to `true` before starting the goroutine to monitor mirroring
Resolves #
**Checklist:**
> ceph: update blockPoolChannel before starting the mirror monitoring

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- Documentation/cassandra.md
- Documentation/ceph-common-issues.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
With the patch release we update the docs and manifests to v1.6.7
**Checklist:**
[skip ci]
> build: Update release version to v1.6.7

- pkg/operator/ceph/object/health.go
The adminops client is already created in newBucketChecker(), use that
instance in checkObjectStoreHealth() than creating a new one.
**Checklist:**
> ceph: remove creation of adminops client in checkObjectStoreHealth()

- .github/workflows/helm-lint.yaml
- build/makelib/helm.mk
- tests/scripts/helm.sh
this commit update helm version to `3.6.2`
Resolves #
**Checklist:**
> ci: update helm version to 3.6.2

- tests/scripts/github-action-helper.sh
Seen today in https://github.com/rook/rook/pull/8272/checks?check_run_id=3010477951
```
github.com/rook/rook/pkg/apis/ceph.rook.io/v1 imports
github.com/hashicorp/vault/api: github.com/hashicorp/vault@v1.4.2: reading https://proxy.golang.org/github.com/hashicorp/vault/@v/v1.4.2.zip: 503 Service Unavailable
server response: Service Unavailable
github.com/rook/rook/pkg/daemon/ceph/osd/kms imports
github.com/libopenstorage/secrets/vault imports
github.com/hashicorp/vault/command/agent/auth: github.com/hashicorp/vault@v1.4.2: reading https://proxy.golang.org/github.com/hashicorp/vault/@v/v1.4.2.zip: 503 Service Unavailable
server response: Service Unavailable
github.com/rook/rook/pkg/daemon/ceph/osd/kms imports
github.com/libopenstorage/secrets/vault imports …
```
> ci: retry on network errors

- pkg/operator/ceph/disruption/clusterdisruption/pools.go
Fix the improper breaking from the loops to add PDBs.
Resolves #
**Checklist:** …
> ceph: create pdb for all rgw and cephfs

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-on-local-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
Resolves #
**Checklist:**
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a …
> docs: add the example of pvc-based ceph cluster on top of bare metal

- tests/scripts/github-action-helper.sh
So it will override any existing installation.
Resolves #
**Checklist:**
> ci: change `yq` path to /usr/local/bin/yq

- .github/workflows/canary-integration-test.yml
Override the default install of yq that may come on the host. 
This is the corresponding backport for #8352 to get tests passing in the release-1.6 branch. The CI has been refactored in master so this isn't a cherry-pick.
**Checklist:**
> ci: Change yq path to /usr/local/bin/yq

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- Documentation/cassandra.md
- Documentation/ceph-common-issues.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
With the patch release the version is updated in the manifests and examples
**Checklist:**
[skip ci]
> build: Update build version to v1.6.8 for the release

- .github/workflows/push-build.yaml
- tests/scripts/build-release.sh
this commit adds github action for
release builds and also modify the
helper script `build-release.sh`.
Resolves #8041
**Checklist:**
> ci: action for release build

- .github/workflows/integration-test-cassandra-suite.yaml
- .github/workflows/integration-test-nfs-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- tests/scripts/github-action-helper.sh
Update the docs and example manifests for 1.7 beta release
**Checklist:**
> build: Update docs and example manifests for 1.7 beta release

- .github/workflows/integration-tests-on-release.yaml
The integration test actions were not running on the release branch or tags due to an incorrect condition.
See the skipped actions on the release branch and tags [here](https://github.com/rook/rook/actions/workflows/integration-tests-on-release.yaml?query=).
**Checklist:**
> build: run integration tests on release branch and tags

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Ceph dashboard link will be used for the
external cluster in OCS.
Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>
Resolves #
**Checklist:**
> ceph: add ceph dashboard link

- tests/scripts/build-release.sh
The beta releases should have the tag suffix included in the helm chart and release version tags.
The v1.7.0-beta.0 [promote step](https://github.com/rook/rook/runs/3166512308?check_suite_focus=true) failed due to the suffix being stripped from the desired version.
Resolves #8378 
**Checklist:**
> build: Promote the build with tag suffix if needed

- .github/workflows/integration-test-nfs-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- tests/scripts/github-action-helper.sh
Update the release version to v1.7.0-beta.1 for another test release based on the latest fixes and attempt to get a beta helm release.
**Checklist:**
> build: Update the release version to v1.7.0-beta.1

- Documentation/ceph-upgrade.md
> docs: ceph: update upgrade docs for Rook v1.7

- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
This PR depends on  https://github.com/openshift/ocs-operator/pull/1276.
This PR adds 'managedBy' label to the ceph metrics if the
cephcluster is managed by another higher Resource. The optional label shall
be added as part of cephcluster CRs monitoring labels.
Resolves #
**Checklist:**
> ceph: added monitoring managedBy label to metrics

- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/cluster_test.go
- pkg/operator/ceph/cluster/controller.go
Moving and factoring code here and there to hopefully make the
initialization sequence easier to go by.
Resolves #
**Checklist:**
> ceph: small bootstrap sequence refactor

- Documentation/ceph-teardown.md
Add the namespace option to the `kubectl patch` command.
Resolves none
**Checklist:**
> docs: fix command to remove cluster CRD finalizer

- .github/workflows/canary-integration-test.yml
- pkg/daemon/ceph/client/mirror.go
- pkg/daemon/ceph/client/test/info.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/controller/mirror_peer.go
- pkg/operator/ceph/controller/mirror_peer_test.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/peers.go
> ceph: add an rbd-mirror bootstrap token on cluster creation 

- .github/workflows/canary-integration-test.yml
- pkg/daemon/ceph/client/mirror.go
- pkg/daemon/ceph/client/test/info.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/controller/mirror_peer.go
- pkg/operator/ceph/controller/mirror_peer_test.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/peers.go
> ceph: add an rbd-mirror bootstrap token on cluster creation (backport #8379)

- pkg/daemon/ceph/client/mirror.go
- pkg/operator/ceph/controller/mirror_peer.go
- pkg/operator/ceph/controller/mirror_peer_test.go
We don't need to put this information in the token.
It's not useful and not used anywhere.
Resolves #
**Checklist:**
> ceph: remove pool id from the peer

- cluster/charts/rook-ceph/templates/deployment.yaml
Adds volumes and mounts for `/var/lib/rook` and `/etc/ceph` to the operator deployment in the Helm chart. This is consistent with the [example operator manifest](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml) and was [suggested](https://rook-io.slack.com/archives/CK9CF5H2R/p1627580573146700?thread_ts=1627489001.136000&cid=CK9CF5H2R) by @travisn on Slack.
Resolves #
**Checklist:**
> ceph: add empty dirs for /var/lib/rook and /etc/ceph

- pkg/operator/ceph/cluster/cleanup.go
Before running the cleanup job we now also wait for the fs-mirror pods
to be gone.
Also, small refactor to print nicely the list of remaining daemons.
Resolves #
**Checklist:**
> ceph: add fs-mirror to cleanup list

- .github/workflows/canary-integration-test.yml
- pkg/daemon/ceph/client/filesystem_mirror.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/mirror/config.go
- pkg/util/retry.go
> ceph: ignore errors when mirroring is not enabled on the filesystem (backport #8447) 

- Documentation/ceph-cluster-crd.md
Added information about which pods will have multus annotations.
Resolves #7563 
**Checklist:**
> docs: added information about which pods will have multus annotations

- .github/workflows/integration-test-nfs-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- tests/scripts/github-action-helper.sh
The manifests and documented release version is updated for the minor release v1.7.
**Checklist:**
> build: Set release version to v1.7.0

- tests/scripts/github-action-helper.sh
No wonder why the build has been taking longer... We were building 3
times.
We just got at least 2 minutes back of build time thanks to this fix.
Resolves #
**Checklist:**
> ci: break if no errors on build

- .github/workflows/integration-test-cassandra-suite.yaml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-nfs-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
1.22 just got released. We now bump our tests one version higher too.
Resolves #
**Checklist:**
> ci: test on kubernetes 1.22

- .github/workflows/create-tag.yaml
- tests/scripts/gen_release_notes.sh
since we moved to github action for the release,
we maunally have to push the tag to build image.
with this change,
first, this action will set some
environment variable which will be consume by
the script to print release notes.
then,
it will ask for 1 input from
github UI(in Action tab)
tag: where we'll give the tag for the release
after creating tag it will run the script and
print release notes.
**NOTEs** 
(i) please verify the environment var
and release notes after the successful action run.
(ii) we have to trigger this after-action
for the release, the build is a success. (@travisn  can correct me)
Resolves #
**Checklist:**
> ci: create tag and print release notes

- CODE-OWNERS
Thanks to the contributions of Satosh and Subham for the past year or two! They have been contributing significantly to the project and their reviews are valued so would like to propose they be added to the official project reviewers group for the Ceph operator.
**Checklist:**
> doc: Add Santosh and Subham as reviewers

- pkg/operator/ceph/cluster/mon/health.go
Stretch clusters in Ceph do not yet support failing over the arbiter mon, so we now disable the arbiter mon from failing over. Soon Ceph will support the arbiter mon failover and we will reenable this failover feature.
This is similar to a restriction made in https://github.com/openshift/rook/pull/198 for all mons to failover prior to v16.2.5. Since that release, this failover issue only affects the arbiter mon.
Here are the Ceph trackers required to get the arbiter mon failover enabled again:
- https://tracker.ceph.com/issues/52126
- https://tracker.ceph.com/issues/52127
**Checklist:**
> ceph: Refuse to failover the arbiter mon on stretch clusters

- .github/workflows/create-tag.yaml
having brackets around if is showing
errors. this commit removes the brackets.
Resolves #
**Checklist:**
> ci: remove brackets when checking repo

- PendingReleaseNotes.md
Reset the release notes for v1.8
**Checklist:**
> docs: Reset the release notes for v1.8

- .github/workflows/integration-test-nfs-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- tests/scripts/github-action-helper.sh
The release version and example manifests are updated to v1.7.1 for the patch release.
**Checklist:**
> build: Update release version to v1.7.1

- tests/integration/ceph_mgr_test.go
Rook orchestrator is going to use PVs as _devices_ for OSDs.
These PVs must use one storage class present in the cluster and configured properly in the manager.
With this change we include this new requirement in the Rook manager module integration test.
Resolves #8530
> ceph: fix error in <ceph orch device ls> test

- cluster/charts/rook-ceph/templates/role.yaml
- cluster/examples/kubernetes/ceph/common.yaml
This commit adds permissions to the rook-ceph-mgr role to delete PVCs and deployments and patch deployment scale
to remove OSDs using `ceph orch osd rm` in the rook orchestrator.
Resolves #
**Checklist:**
> ceph: add permissions to rook-ceph-mgr role for osd removal in rook orchestator

- pkg/daemon/ceph/client/mirror.go
- pkg/operator/ceph/cluster/cleanup.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/watcher.go
- pkg/operator/ceph/object/objectstore.go
Converting util.NewSet() instance to use sets.NewString() instance
Closes:https://github.com/rook/rook/issues/8479
Resolves #
**Checklist:**
> core: convert util.NewSet() to sets.NewString()

- pkg/operator/ceph/disruption/clusterdisruption/reconcile.go
Removing the deleteLegacyPDBForOSD method
because we don't support legacyPDBs
Closes: https://github.com/rook/rook/issues/8360
Resolves #
**Checklist:**
> ceph: Remove legacy PDBs methods

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- Documentation/cassandra.md
- Documentation/ceph-common-issues.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
With the patch release the example manifests and build actions are updated.
**Checklist:**
> build: update release version to v1.6.9

- pkg/operator/ceph/operator.go
As of Golang 1.16, we can use `signal.NotifyContext()` from the signal
package. Essentially it combines signal handling for termination as well
as canceling the context to stop any ongoing operations.
Resolves #
**Checklist:**
> ceph: signal signals handling with context

- .github/workflows/build.yml
- build/crds/crds.go
- build/makelib/golang.mk
The CI now runs the build test against Golang 1.15 and 1.16
Resolves #
**Checklist:**
> ci: build on golang 1.16 and 1.17

- build/makelib/golang.mk
Instead of using the root let's only lookup our packages. Otherwise we
will format files from ./.work.
Resolves #
**Checklist:**
> core: parse go files only subdirs

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-osd-mgmt.md
- design/ceph/storage-class-device-set.md
A single entry is a storageClassDeviceSet in the code, but in YAML
the name that appears is the one of the whole array.
> docs: Correct field name.

- build/release/Makefile
- build/run
- images/cross/run.sh
- tests/scripts/build-release.sh
> ci: add debugging to release build script

- pkg/operator/ceph/cluster/mgr/drain.go
- pkg/operator/ceph/cluster/mgr/drain_test.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
Currently PDB for MGR is not been created,
Creating the PDB for MGR if its count is 2
Closes: https://github.com/rook/rook/issues/8275
Resolves #
**Checklist:**
> ceph: add pdb for mgr

- cluster/examples/kubernetes/ceph/cluster.yaml
Minor change to comment in cluster CRD.
> fixed typo on version reference in comment

- pkg/operator/ceph/object/rgw.go
- tests/integration/ceph_base_object_test.go
> ci: fix object store test

- Documentation/ceph-object-store-user-crd.md
- pkg/operator/ceph/object/user/controller.go
- tests/integration/ceph_base_object_test.go
Addressing remaining nits from the PR #8211 
Resolves #
**Checklist:**
> ceph: addressing nits from #8211

- build/release/Makefile
Rename the master docs to latest. This will be easier to understand for users who are new to the project. The url will also contain latest, which will be more clear to reference instead of the master path. This also follows the pattern of the ceph docs site.
This will need to be merged at the same time a change is also made to the website repo.
**Checklist:**
> docs: Publish master docs to latest path

- tests/scripts/github-action-helper.sh
update validate_yaml method to dry-run yaml files only
Closes: https://github.com/rook/rook/issues/8707
Resolves #8707 
**Checklist:**
> ci: update validate_yaml method

- tests/scripts/github-action-helper.sh
--dry-run is deprecated and replaced with --dry-run=client
Resolves #
**Checklist:**
> ci: dry-run is deprecated and replaced with --dry-run=client

- .github/workflows/stale.yaml
Let's be a bit more aggressive to ensure a consistent amount of
in-progress PRs and issues.
So now PR will go stale after 30 days and issues after 45 days.
Resolves #
**Checklist:**
> bot: change issue and pr stale days

- go.mod
- go.sum
- pkg/apis/ceph.rook.io/v1/annotations_test.go
- pkg/apis/ceph.rook.io/v1/labels_test.go
- pkg/apis/ceph.rook.io/v1/network_test.go
- pkg/apis/ceph.rook.io/v1/placement_test.go
- pkg/apis/ceph.rook.io/v1/priorityclasses_test.go
- pkg/apis/ceph.rook.io/v1/spec_test.go
- pkg/operator/ceph/csi/util.go
- pkg/operator/ceph/csi/util_test.go
- pkg/operator/k8sutil/resources.go
- pkg/operator/k8sutil/tolerations.go
We don't need to use github.com/ghodss/yaml since
"k8s.io/apimachinery/pkg/util/yaml" provides the same functionality and
we already import it.
Resolves #
**Checklist:**
> ceph: remove unnecessary package

- .github/workflows/canary-integration-test.yml
- Documentation/ceph-cluster-crd.md
- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph-cluster/values.yaml
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-on-local-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-stretched.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/images.txt
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/ceph/ceph-cluster-cleanup.md
- images/ceph/Makefile
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/filesystem_test.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/file/mds/spec_test.go
- pkg/operator/ceph/object/user.go
- tests/framework/installer/ceph_installer.go
- tests/integration/ceph_base_file_test.go
> ceph: use next ceph v16.2.6 pacific version

- tests/framework/installer/ceph_helm_installer.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/installer.go
- tests/framework/installer/settings.go
- tests/integration/ceph_flex_test.go
- tests/integration/ceph_helm_test.go
- tests/integration/ceph_mgr_test.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_smoke_test.go
- tests/integration/ceph_upgrade_test.go
- tests/scripts/github-action-helper.sh
The integration tests must always be run against the local build of rook, and an image should never be pulled from dockerhub. To prevent pulling a release or master tag, the local build will use a tag specific to the build and not ever be published elsewhere.
**Checklist:**
> test: Run release branch tests against the correct local build version

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/commitlint.yml
- .mergify.yml
- Documentation/ceph-advanced-configuration.md
- Documentation/development-environment.md
- Documentation/pre-reqs.md
- Documentation/storage-providers.md
- INSTALL.md
- README.md
- cluster/charts/rook-ceph-cluster/templates/NOTES.txt
- cluster/charts/rook-ceph-cluster/values.yaml
- cluster/charts/rook-ceph/templates/NOTES.txt
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/cluster-stretched-aws.yaml
- cluster/examples/kubernetes/ceph/cluster-stretched.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- design/README.md
- design/ceph/ceph-stretch-cluster.md
With the renaming of master docs to latest, all the links also need to be updated.
**Checklist:**
> docs: Update master doc links to latest

- Documentation/ceph-dashboard.md
Corrected secret name in one-liner for getting admin password from kubernetes.
**Checklist:**
> ceph: Fix typo in dashboard admin password

- tests/integration/ceph_object_test.go
Multiple CephObjectStores should be able to run at the same time. In CI,
test this by:
1. Create the primary object store under test (store A) (this was
already done)
2. Verify that store A starts and becomes ready (already done but is
moved here)
3. Create a second object store (store B) (new)
4. Verify that store B starts and becomes ready (new)
5. Delete store B, and ensure it is deleted (new)
6. , etc. Continue to verify primary store A operations as before (this
was already done)
This is necessary to ensure that the Rook operator is using
`radosgw-admin` and the RGW Admin Ops API properly to support multiple
ObjectStores running at once. …
> test: run multiple object stores at once in CI

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- Documentation/cassandra.md
- Documentation/ceph-common-issues.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
The patch release for v1.6.9 is ready, thus updating the example manifests and documentation.
**Checklist:**
> build: Update release version to v1.6.10

- .github/workflows/canary-integration-test.yml
- Documentation/ceph-monitoring.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/images.txt
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- tests/integration/ceph_base_object_test.go
- tests/scripts/github-action-helper.sh
With the patch release we update the examples and docs to v1.7.4
**Checklist:**
> build: Update release version to v1.7.4

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
This PR is on top of PR https://github.com/rook/rook/pull/8774
Resolves #
**Checklist:**
> monitoring: add namespace to ceph node down query

- .mergify.yml
Since master and release branches run a different version of Kubernetes,
the conditions must be adapted.
Closes: https://github.com/rook/rook/issues/8865
Resolves #$https://github.com/rook/rook/issues/8865
**Checklist:**
> bot: change mergify config for k8s versions

- tests/scripts/github-action-helper.sh
Try to avoid the following:
```
error pulling image configuration: received unexpected HTTP status: 500 Internal Server Error
```
Resolves #
**Checklist:**
> ci: retry on image pull error

- Documentation/ceph-monitoring.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/images.txt
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- tests/scripts/github-action-helper.sh
The example manifests and documentation are updated to v1.7.7
Resolves #
**Checklist:**
> build: update the patch version to v1.7.7

- .github/workflows/canary-integration-test.yml
- .github/workflows/collect-logs/action.yaml
- .github/workflows/daily-nightly-jobs.yml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-object-suite.yaml
- .github/workflows/integration-test-setup/action.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- .github/workflows/setup-cluster-resources/action.yaml
Using Github Compositoin to reduce the yaml duplication.
https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/
Closes: https://github.com/rook/rook/issues/8637
Resolves #8637 
**Checklist:**
> ci: use github composition to reduce duplication

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
The permissions set for ceph auth principals for
external storage are too broad, which leads to
maintenance and security risk
Modified auth principals permissions to specific pools
and Added a clusterName as a suffix on ceph auth
principals for external cluster
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1996829
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1996829
https://bugzilla.redhat.com/show_bug.cgi?id=1996830
**Checklist:**
> security: update auth permissions for external cluster

- Documentation/cassandra.md
- Documentation/ceph-common-issues.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
With the patch release we update the example manifest version to v1.6.11
**Checklist:**
> build: Set the release version to 1.6.11

- Documentation/ceph-monitoring.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/quickstart.md
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/images.txt
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- tests/scripts/github-action-helper.sh
With the patch release the examples are updated to the version v1.7.8
**Checklist:**
> build: Set the release version to v1.7.8

- pkg/operator/ceph/object/objectstore.go
avoid failed reconcile when multiple multisite objectstore are configured
Signed-off-by: Olivier Bouffet <olivier.bouffet@infomaniak.com>
Resolves #9100
**Checklist:**
> object: fix search user in objectstore

- deploy/olm/assemble/metadata-common.yaml
- deploy/olm/generate-rook-csv.sh
Add the missing CRDs as well as a check to prevent missing CRDs from the
CSV file.
Resolves #
**Checklist:**
> build: add missing topic and notification crd to csv

- Documentation/ceph-monitoring.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
For the new 1.8 branch we create the new v1.8.0-beta.0 manifests and doc updates.
**Checklist:**
> build: Set release version to v1.8.0-beta.0

- Makefile
- build/rbac/get-helm-rbac.sh
- deploy/examples/common.yaml
- deploy/olm/generate-rook-csv-templates.sh
- deploy/olm/generate-rook-csv.sh
- images/ceph/Makefile
In order to generate common.yaml from Helm charts, we have to have a
different way of generating CSV than from meta-comments in common.yaml.
This implementation changes what appears in the CSV's RBAC somewhat, but
these changes could be considered bugs fixed by using the new Helm
generation method.
- a few PSP related resources are removed from CSV
- resources related to 'rook-ceph-purge-osd' Job are added to CSV
- ClusterRoleBinding 'rook-ceph-object-bucket' is added to CSV
Resolves #
**Checklist:**
> build: generate CSV from helm charts

- deploy/charts/rook-ceph-cluster/templates/ingress.yaml
Updating minor versions of kubernetes test environments, and running helm charts against all supported environments.
Resolves #9174 
**Checklist:**
> helm: Use a more explicit value for ingress for K8s 1.18

- Documentation/ceph-monitoring.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/flex-to-csi-migration.md
- Documentation/quickstart.md
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/flex-migrator.yaml
- cluster/examples/kubernetes/ceph/images.txt
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- tests/scripts/github-action-helper.sh
> build: Set the release version to v1.7.9

- build/rbac/common.yaml.header
- deploy/examples/common.yaml
In anticipation of generating common.yaml from the Helm charts, sort
common.yaml using the same script used to sort the output from Helm
charts.
This was done using the flow here:
```
cat build/rbac/common.yaml.header > new-common.yaml
cat deploy/examples/common.yaml | build/rbac/keep-rbac-yaml.sh >> new-common.yaml
mv new-common.yaml deploy/examples/common.yaml
```
Resolves #
**Checklist:**
> docs: sort common.yaml example (Backport #9279)

- Documentation/ceph-object-bucket-notifications.md
Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>
**Checklist:**
> rgw: add note that bucket notifications are experimental

- build/rbac/get-helm-rbac.sh
Let's fail nicely if the helm command is not available.
Resolves #
**Checklist:**
> build: check for the existence of helm

- Documentation/ceph-upgrade.md
> docs: revise upgrade doc for Rook v1.8

- Documentation/ceph-upgrade.md
Since the cluster helm chart was created in v1.7, the new helm chart specifies the ceph image, so we clarify the upgrade doc with the latest info.
**Checklist:**
> docs: Clarify helm chart version upgrades

- Documentation/ceph-monitoring.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
The minor release v1.8.0 is ready to go! This updates the example manifests and documents to point to the latest release.
**Checklist:**
> build: Update the release version to v1.8.0

- Documentation/ceph-monitoring.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/flex-to-csi-migration.md
- Documentation/quickstart.md
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/flex-migrator.yaml
- cluster/examples/kubernetes/ceph/images.txt
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- tests/scripts/github-action-helper.sh
With the latest patch release we update the docs and example manifests.
**Checklist:**
> build: Update release version to v1.7.10

- .github/workflows/canary-integration-test.yml
- Documentation/ceph-monitoring.md
- Documentation/ceph-upgrade.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
> build: update examples and manifests for v1.8.1

- README.md
The info email list and rook-dev forum are targeted frequently by spam and otherwise not used by the community. Let's focus on the useful channels of slack, github, and security emails.
Related to #9508 
**Checklist:**
> docs: Remove mailing lists from main readme

- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- tests/framework/clients/block.go
- tests/framework/installer/ceph_helm_installer.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests_previous.go
- tests/framework/installer/environment.go
- tests/framework/installer/installer.go
- tests/framework/utils/helm_helper.go
- tests/integration/ceph_base_block_test.go
- tests/integration/ceph_helm_test.go
- tests/integration/ceph_mgr_test.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_object_test.go
- tests/integration/ceph_smoke_test.go
- tests/integration/ceph_upgrade_test.go
The helm tests were previously only for new installs, and did not have an upgrade path. Now the upgrade path is tested to give confidence in the helm upgrades.
At the same time, include some test code cleanup... The test suites were triggered by Jenkins potentially using different versions of K8s and environment variables. There is no longer a need for these environment vars to determine which test suites should be run. The test suites to run can just be triggered directly.
**Checklist:**
> tests: Helm upgrade integration test

- .github/workflows/canary-integration-test.yml
- .github/workflows/daily-nightly-jobs.yml
- .github/workflows/encryption-pvc-kms-ibm-kp/action.yml
- Documentation/ceph-kms.md
- cmd/rook/secret.go
- go.mod
- go.sum
- pkg/apis/ceph.rook.io/v1/security.go
- pkg/daemon/ceph/osd/encryption.go
- pkg/daemon/ceph/osd/kms/envs.go
- pkg/daemon/ceph/osd/kms/envs_test.go
- pkg/daemon/ceph/osd/kms/ibm_key_protect.go
- pkg/daemon/ceph/osd/kms/ibm_key_protect_test.go
- pkg/daemon/ceph/osd/kms/k8s.go
- pkg/daemon/ceph/osd/kms/kms.go
- pkg/daemon/ceph/osd/kms/kms_test.go
- pkg/daemon/ceph/osd/kms/vault.go
- pkg/daemon/ceph/osd/kms/vault_test.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/osd/create.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/volumes.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
- tests/manifests/test-kms-ibm-kp-secret.in
- tests/manifests/test-kms-ibm-kp-spec.in
> osd: add ibm key protect kms

- .github/workflows/canary-integration-test.yml
- .github/workflows/daily-nightly-jobs.yml
If the secret is not present in the run then let's skip it.
Resolves #
**Checklist:**
> ci: skip encryption test if env is not set

- Documentation/ceph-monitoring.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/quickstart.md
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/flex-migrator.yaml
- cluster/examples/kubernetes/ceph/images.txt
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- tests/scripts/github-action-helper.sh
With the patch release the example manifests and docs are updated to v1.7.11
**Checklist:**
> build: Update release version to v1.7.11

- Documentation/ceph-monitoring.md
- Documentation/ceph-upgrade.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
With the patch release the example manifests and docs are updated to v1.8.3
**Checklist:**
> build: Update the release version to v1.8.3

- .github/workflows/daily-nightly-jobs.yml
The secret is called secrets.IBM_INSTANCE_ID instead of
secrets.IBM_KP_INSTANCE_ID. Now the daily test should pass.
Resolves #
**Checklist:**
> ci: fix daily encryption ibm kms test

- deploy/charts/rook-ceph-cluster/templates/volumesnapshotclass.yaml
- deploy/charts/rook-ceph-cluster/values.yaml
add support to specify annotations and labels for the volumesnapshotclass.
Resolves  #9655
**Checklist:**
> helm: add annotations and labels for VSC

- pkg/operator/ceph/object/spec.go
When the strategy type of deployment is `Recreate`, it terminate at once as follows.
pods
```
NAME                     READY   STATUS        RESTARTS   AGE
echo-bc6fd5bf7-6hlld     1/1     Terminating   0          66d
echo-bc6fd5bf7-9sd2k     1/1     Terminating   0          66d
echo-bc6fd5bf7-bgxvb     1/1     Terminating   0          66d
echo-bc6fd5bf7-cqclp     1/1     Terminating   0          66d
echo-bc6fd5bf7-h4v7k     1/1     Terminating   0          66d
```
endpoints
```
NAME         ENDPOINTS                           AGE
echo         <none>                              689d
```
After that, when all pods are terminated, a new one is created at the same time.
pods
```
NAME                     READY   STATUS    RESTARTS   AGE
echo-97b48fcc6-98k4r …
```
> rgw: gateway deployment strategy RollingUpdate on Pacific

- ROADMAP.md
Update the roadmap for v1.9 with overall features and updates planned.
**Checklist:**
> docs: Update the roadmap for v1.9

- Documentation/ceph-monitoring.md
- Documentation/ceph-upgrade.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
With the patch release the example manifests and docs are updated to v1.8.5
**Checklist:**
> build: Update release version to v1.8.5

- .github/workflows/canary-integration-test.yml
- pkg/operator/ceph/object/spec.go
- tests/scripts/deploy-validate-vault.sh
The backend path was added with additional `transit` to it.
Also added test case in this PR to check transit engine
Resolves #
**Checklist:**
> object: fix backend path for transit engine for rgw kms

- Documentation/development-environment.md
- Documentation/quickstart.md
If Rook is run on a developer machine, devices may accidentally be consumed by rook and cause data loss.
@kconde2 Would this doc change have been helpful to help you catch the issue soon enough to avoid running with kind? Or what suggestion do you have for the docs?
**Checklist:**
> docs: Warn in quickstart guide about using a vm

- Documentation/ceph-object-multisite.md
The docs have links pointing /design directory in the codebase which
hidden in https://rook.io so change them to rook github repo links.
Resolves #9768
**Checklist:**
> docs: fix broken links in ceph-object-multisite.md

- Documentation/ceph-kms.md
Based on my testing with the guide above, the original value in the sample code here:
`VAULT_BACKEND_PATH: rook/ver1`
...did not work and resulted in a Vault path error when Rook attempted to provision the OSD filesystem.  When I simplified it to:
`VAULT_BACKEND_PATH: rook`
... then it worked.
I also took the opportunity to add a comment/clarification about the `VAULT_ADDR` URL.
Co-authored-by: Shahak Nagiel <snagiel@yahoo.com>
Resolves #
**Checklist:**
> docs: Correct VAULT_BACKEND_PATH

- pkg/operator/ceph/file/filesystem.go
If the filesystem is in a bad state such as never being created successfully in the first place, the filesystem removal will continuously fail and prevent the CR from being removed. Thus, we treat the filesystem removal as a best effort and log the issue instead of failing the uninstall reconcile.
Resolves #9792 
**Checklist:**
> file: Allow filesystem removal even with failures

- Documentation/ceph-monitoring.md
- Documentation/ceph-upgrade.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
With the patch release we update the examples and docs to v1.8.6.
**Checklist:**
> build: Update release version to v1.8.6

- Documentation/ceph-advanced-configuration.md
- PendingReleaseNotes.md
- deploy/examples/csi-ceph-conf-override.yaml
- pkg/operator/ceph/csi/ceph_config.go
- pkg/operator/ceph/csi/ceph_config_test.go
- pkg/operator/ceph/csi/controller.go
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
- pkg/operator/ceph/csi/version.go
- pkg/operator/ceph/csi/version_test.go
- tests/framework/installer/ceph_installer.go
Currently, the admin/user can configure the ceph.conf for daemon pods using https://rook.io/docs/rook/v1.7/ceph-advanced-configuration.html#custom-cephconf-settings. This the above custom ceph.conf is only for ceph pods. the support to provide custom ceph.conf for cephcsi is added in cephcsi ceph/ceph-csi#2476
This PR adds the support to create/update ceph.conf for csi pods.
Resolves #9220
**Checklist:**
@travisn what is the best place to add this documentation? can I add this as a sub section under https://rook.io/docs/rook/v1.7/ceph-advanced-configuration.html#custom-cephconf-settings
> csi: add custom ceph.conf for csi pods

- .github/PULL_REQUEST_TEMPLATE.md
The PR checklist has a couple links that were outdated and some other items that are generally not necessary to consider in every PR. Now the checklist is more concise and links are updated.
**Checklist:**
> docs: Update the pr template checklist

- .github/workflows/canary-integration-test.yml
- deploy/examples/create-external-cluster-resources-tests.py
- deploy/examples/create-external-cluster-resources.py
split the external script main code and unit test in a different files.
Resolves #9588 
**Checklist:**
> core: split external script unit test and main code in diff file

- deploy/charts/rook-ceph/templates/resources.yaml
- deploy/examples/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/cephstatus.go
FSID will be updated with cephcluster CR status
when monitoring check get start
Resolves #
**Checklist:**
> core: sync ceph fsid on cephcluster status

- Documentation/ceph-monitoring.md
- Documentation/ceph-upgrade.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
With the patch release the example manifests and docs are updated to v1.8.7
**Checklist:**
> build: Set release version to v1.8.7

- .github/workflows/linters.yaml
adding pylint in ci.
Closes: https://github.com/rook/rook/issues/9866
Resolves #9866 
**Checklist:**
> ci: add pylint in ci

- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/controller_test.go
This work is in prep for the filesystem portion of #8068 
Resolves #
**Checklist:**
> file: add events to filesystem reconcile

- pkg/operator/ceph/object/controller_test.go
**Description of your changes:** Added two test cases to check creation and deletion of external object stores.
Resolves #9025 
**Checklist:**
> rgw: add unit tests for the external ceph object store reconciler

- deploy/examples/create-external-cluster-resources.py
pylint was failing with used-before-assignment error
fixed it by making the variables assignmet before it was used
Resolves #
**Checklist:**
> ci: fixed pylint failure

- Documentation/ceph-monitoring.md
- Documentation/ceph-upgrade.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
Updating the example manifests and docs to point to the latest release v1.8.8.
**Checklist:**
> build: Update release version to v1.8.8

- Documentation/ceph-monitoring.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
For the new 1.9 branch we create the new v1.9.0-beta.0 manifests and doc updates. The v1.9.0 release is planned to be out in the next week or two after final testing.
**Checklist:**
> build: Set the release version to v1.9.0-beta.0

- Documentation/authenticated-registry.md
- PendingReleaseNotes.md
- deploy/charts/library/templates/_cluster-serviceaccount.tpl
- deploy/examples/common-second-cluster.yaml
- deploy/examples/common.yaml
- deploy/examples/operator-openshift.yaml
- pkg/apis/ceph.rook.io/v1/scc.go
- pkg/operator/ceph/object/spec.go
- tests/framework/installer/ceph_settings.go
For supporting features like service account authentication for vault
KMS , a service account account need to attach with pod.
Resolves #
**Checklist:**
> object: add service account for RGW pod

- Documentation/ceph-monitoring.md
- Documentation/ceph-pool-crd.md
- Documentation/ceph-upgrade.md
- PendingReleaseNotes.md
- deploy/examples/cluster-test.yaml
- deploy/examples/pool-builtin-mgr.yaml
- design/common/object-bucket.md
Update upgrade and supporting docs for release of Rook v1.9.
Include pending release notes as part of this update.
Resolves #9995
**Checklist:**
> Upgrade docs for 1.9

- Documentation/ceph-upgrade.md
The bluestore_fsck_quick_fix_on_mount fix was only needed when upgrading to
versions of Ceph older than v16.2.6. Everyone on pacific should now be
on v16.2.7, so we can remove this section from the v1.9 upgrade guide.
Also cleaning up a few other small issues in the guide.
**Checklist:**
> docs: Remove obsolete section of upgrade guide

- Documentation/ceph-advanced-configuration.md
- Documentation/ceph-csi-snapshot.md
- Documentation/ceph-csi-volume-clone.md
- Documentation/ceph-pool-crd.md
The script to get the branch name was not being imported on several doc pages, causing any links using `{{ branchName }}` to be broken on those pages.
**Checklist:**
> docs: Add missing references to branch name script

- design/ceph/multus-network.md
update design doc path in multus design.
Resolves #
**Checklist:**
> docs: update design doc path in multus design

- Documentation/helm-ceph-cluster.md
- Documentation/helm-operator.md
Update the formatting so third-level headers are more visible, sections are more consistent between the operator and cluster chart docs, and some other minor updates.
**Checklist:**
> docs: Clarify helm install documentation

- Documentation/ceph-monitoring.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
With the minor release we update manifest versions and documentation to v1.9.0.
**Checklist:**
> build: Update release version to v1.9.0

- Documentation/ceph-csi-drivers.md
- Documentation/ceph-nfs-crd.md
- Documentation/ceph-upgrade.md
- deploy/examples/nfs-load-balancer.yaml
- deploy/examples/nfs-test.yaml
- deploy/examples/nfs.yaml
Update the NFS docs with the latest available info for Ceph Quincy
including the CSI provisioner driver.
Resolves #
**Checklist:**
> docs: update NFS docs including latest CSI work

- pkg/operator/ceph/file/subvolumegroup/controller.go
- pkg/operator/ceph/file/subvolumegroup/controller_test.go
improved the logging and also reorganized code to handle external and non-external cases for better code readability.
Resolves #
**Checklist:**
> subvolumegroup: refractor subvolumegroup controller

- Documentation/ceph-monitoring.md
- Documentation/ceph-upgrade.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
Update the docs and example manifests for the v1.8.9 release.
**Checklist:**
> build: Update release version to v1.8.9

- Documentation/ceph-monitoring.md
- Documentation/ceph-upgrade.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
Update the docs and example manifests for the v1.9.1 release.
**Checklist:**
> build: Set the release version to v1.9.1

- pkg/operator/ceph/csi/csi.go
- pkg/operator/ceph/csi/spec.go
moving setting csi parameter to `setParams` function as `startDrivers` is mostly used to set the csi parameters for the templates.
Resolves #
**Checklist:**
> csi: move setting csi param to setParams

- tests/framework/utils/k8s_helper.go
The K8sHelper has a number of methods that are no longer in use that we can remove.
**Checklist:**
> test: Remove dead test helper code

- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-object-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- .mergify.yml
- Documentation/ceph-block.md
- Documentation/ceph-cluster-crd.md
- Documentation/development-flow.md
- Documentation/helm-ceph-cluster.md
- Documentation/helm-operator.md
- Documentation/quickstart.md
- deploy/charts/rook-ceph-cluster/templates/_helpers.tpl
- pkg/operator/ceph/cluster/osd/create.go
- pkg/operator/ceph/cluster/osd/create_test.go
- tests/framework/installer/ceph_helm_installer.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_settings.go
- tests/integration/ceph_multi_cluster_test.go
- tests/scripts/deploy_cert_manager.sh
Support is removed for k8s for various limitations such as priority classes not working and csi driver feature incompleteness and missing snapshots. Documentation is updated with the new min version of k8s 1.17 and also the tests are updated to run on the min version of 1.17.
Let's hold this for a few days to wait for feedback on #10115. 
Resolves #10115 
**Checklist:**
> build: Update min version to k8s 1.17

- deploy/charts/rook-ceph-cluster/values.yaml
Currently annotations are not set which results in a non-working ingress after setting the key ssl: true
Resolves #
**Checklist:**
> helm: add ingress annotations for ssl

- Documentation/ceph-monitoring.md
- Documentation/ceph-upgrade.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
For the patch release we update the example manifests and docs to v1.9.2
**Checklist:**
> build: Update release version to v1.9.2

- .github/workflows/canary-integration-test.yml
- tests/scripts/create-bluestore-partitions.sh
- tests/scripts/github-action-helper.sh
OSD on PVC is tested in many patterns but OSD on device is not.
It's preferable to add the following patterns for OSD on device.
- An OSD on a raw disk
- Two OSDs on a device
**Checklist:**
> test: add canary integration tests for osd on device

- deploy/charts/rook-ceph/templates/configmap.yaml
- deploy/charts/rook-ceph/values.yaml
Signed-off-by: Yuval Manor <yuvalman958@gmail.com>
currently, it is not possible to disable hostNetwork. This pr fix this issue.
Resolves #10252
**Checklist:**
> csi: add the option to disable hostNetwork

- Documentation/ceph-monitoring.md
- Documentation/ceph-upgrade.md
- Documentation/quickstart.md
- deploy/examples/direct-mount.yaml
- deploy/examples/images.txt
- deploy/examples/operator-openshift.yaml
- deploy/examples/operator.yaml
- deploy/examples/osd-purge.yaml
- deploy/examples/toolbox-job.yaml
- deploy/examples/toolbox.yaml
For the patch release the example manifests and documentation is updated to v1.9.3
**Checklist:**
> build: Update the release version to v1.9.3

- deploy/charts/rook-ceph/templates/clusterrole.yaml
- deploy/examples/common.yaml
Remove unwanted cephfs clusterRole RBAC.
Resolves #
**Checklist:**
> csi: Remove extra cephfs node rbac

- .docs/overrides/main.html
Just a tiny rewording of the main doc link
**Checklist:**
> docs: Update wording for latest doc link

- .github/workflows/push-build.yaml
- build/release/Makefile
The doc build generation script is failing to install the needed dependencies for mkddocs, so we update the CI to use ubuntu 20.04 and pip3.
**Checklist:**
> ci: Install and use pip3 for the docs generation script

- design/ceph/ceph-telemetry.md
Add a design doc for adding Rook telemetry to Ceph telemetry capture.
Resolves #
**Checklist:**
> docs: add ceph telemetry design doc

- build/release/Makefile
- build/release/mkdocs.yml
This should fix the docs build release issue mentioned here: https://github.com/rook/rook/issues/10282#issuecomment-1135222267
Resolves #10282
**Checklist:**
> docs: fix docs_dir build issue

- build/release/Makefile
> docs: don't cd during docs publish

- build/release/Makefile
- mkdocs.yml
> docs: build docs from repo root

- Documentation/Getting-Started/Prerequisites/prerequisites.md
- Documentation/Getting-Started/quickstart.md
Signed-off-by: Gaurav Sitlani <gaurav@koor.tech>
Resolves #
**Checklist:**
> docs: Added CPU requirements
