rook/rook

- pkg/apis/rook.io/v1/annotations.go
- pkg/apis/rook.io/v1/annotations_test.go
Two changes:
1.  Initialize merged annotations when empty. This was causing the cassandra operator to fail when annotations were added to the cluster
1. Move annotations helper into test code since it's not needed in production code.
Resolves #6054 
**Checklist:**
> cassandra: Initialize merged annotations when empty

- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/nsenter_test.go
Older versions of lvm do not implement "--help" but "help" only where
new versions support both so let's use "help" so the check works for all
the versions.
Closes: https://github.com/rook/rook/issues/6057
Resolves https://github.com/rook/rook/issues/6057
**Checklist:**
// Known issue!
[skip ci]
> ceph: use different command for lvm2 presence

- pkg/operator/ceph/cluster/crash/reconcile.go
If a node is gone, we try to remove crash collector deployments so they
don't stay stale or pending. We must ensure the node is gone and not
just return an error even if we successfully deployment the orphan
deployment.
Resolves #
**Checklist:**
// known issue
[skip ci]
> ceph: check for gone node on crash collector

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/status.go
- pkg/operator/ceph/object/status_test.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.2.go
currently, the object store schema requires the
port to be non-zero. This does not allow http
access to the object store to be disabled.
so setting the port minimum to 0 to from 1 in the cr.
Resolves #5806
**Checklist:**
> ceph: disable object store port when secureport specified

- Documentation/ceph-rbd-mirror-crd.md
- pkg/apis/ceph.rook.io/v1/types.go
This adds some basic RBDMirror CRD documentation and fixes the types.go
comments accordingly.
I will skip the CI as only comments and documentation has been updated, but if we see the need as code has been changed we can run the full Ceph test.
**Checklist:**
[skip ci]
> docs: added rbd mirror crd documentation

- Documentation/ceph-object.md
- cluster/examples/kubernetes/ceph/object-external.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- tests/framework/installer/ceph_manifests.go
Reverting some of
23f0ac7
to re-use `bucket` for the healthcheck configuration.
**Checklist:**
[skip ci]
> ceph: fix object store healthcheck yaml

- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
Similar to https://github.com/rook/rook/pull/5977 but for wal devices.
So if a cluster is deployed on PVC and wal devices, those will be
encrypted as well.
**Checklist:**
> ceph: add support for wal encrypted device on pvc

- Documentation/helm-operator.md
This fixes the helm commands to be compatible with Helm v3.x and adds an
example / notes for Helm v2.x users.
Resolves #5491
Resolves #5491
**Checklist:**
[skip ci]
> doc: fix helm command usage

- cluster/examples/kubernetes/ceph/upgrade-from-v1.3-apply.yaml
There is a missing YAML document / object separator in the apply file.
This PR adds it so it can be applied without errors.
Resolves #
**Checklist:**
[skip ci] because the file is a "example" file.
> ceph: fix v1.3 to v1.4 upgrade apply file syntax

- pkg/daemon/ceph/osd/daemon_test.go
- pkg/daemon/ceph/osd/drivegroups.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
callCephVolume() was using our exec interface with CombinedOutput which
means return both stdout and stderr. This is fine when preparing OSDs
since we read back the stdout and also want any errors if any (stderr).
However when listing OSD we only want the output since ceph-volume tends
to mix stdout and stderr in the output and does not always silence the
warning types/harmless errors. If the listing has a problem we report it
by printing the ceph-volume log file.
Resolves #
**Checklist:**
> ceph: improve callCephVolume() for list and prepare

- tests/integration/ceph_mgr_test.go
`Giving up waiting for Rook Toolbox to be ready` error always
logs.
Because [this code](https://github.com/rook/rook/blob/master/tests/integration/ceph_mgr_test.go#L126-L136) goes `logger.Error("Giving up waiting for Rook Toolbox to be ready")` even if `ceph orch status` command successes.
Example:
https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/PR-5573/runs/78/nodes/60/steps/118/log/?start=0
```
2020-08-17 22:47:10.759998 I | integrationTest: Rook Toolbox ready to execute commands
2020-08-17 22:47:10.760005 E | integrationTest: Giving up waiting for Rook Toolbox to be ready
```
Resolves #
**Checklist:**
> ci: fix inconsistent error log

- cluster/charts/rook-ceph/values.yaml
Currently, the CSI resources are getting passed as the map instead of a string, due to this the yaml unmarshal is getting failed. This commit adds the missing '|' to pass the resources as the string instead of map
Resolves #5501
**Checklist:**
[skip ci]
added skip ci as this changes only the commented line.
> ceph: pass csi resources as string in helm

- pkg/daemon/ceph/osd/nsenter.go
- pkg/daemon/ceph/osd/nsenter_test.go
On rancher OS, the lvm binary is in a different location and cannot be
accessed via the root namespace. So we now also check directly from
/rootfs. When using nsenter, itbreaks out of container's mount
namespace and executes an lvm command.
Closes: https://github.com/rook/rook/issues/6078
Resolves https://github.com/rook/rook/issues/6078
**Checklist:**
> ceph: check rootfs for lvm too

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- pkg/apis/rook.io/v1/types.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
The osd prepare jobs and osd daemons may have different placement requirements. In particular, the topology spread constraints or pod anti-affinity should only work on either the prepare job or osd daemon, but does not work effectively on both types at the same time. Therefore, we split out the osd prepare placement to be separate from the osd daemon placement. 
If the osd prepare placement is not set the operator will fall back to the osd daemon placement for backward compatibility.
This only applies to OSDs created by portable storageClassDeviceSets. Non-portable OSDs will be tied to the host on which the OSD prepare job runs.
Resolves: #5932 
**Checklist:**
> ceph: Separate placement for osd prepare jobs from osd daemons

- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
The osd prepare resources were only being set on the main container while the init containers either did not have resources set, or were inheriting the resource settings from the device set resources for osds. Now the osd prepare resources will be consistently set based on the prepareosd resources in the main section of the cluster CR.
Also a small code simplification to remove an extra check for whether the OSDs are encrypted. There is no change in functionality for this commit.
Resolves: #5586 #6117
**Checklist:**
> ceph: Set the OSD prepare resources

- pkg/daemon/ceph/osd/daemon.go
It is fine to use /mnt/set1-data-0-k47mc, it looks like I thought there
was an issue with udev but there is none...
Closes: https://github.com/rook/rook/issues/5996
Resolves https://github.com/rook/rook/issues/5996
**Checklist:**
> ceph: do not use realPath for osd on pvc

- Documentation/ceph-cluster-crd.md
- pkg/apis/ceph.rook.io/v1/resources.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/node_test.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/rbd/mirror.go
- pkg/operator/ceph/controller/spec.go
- pkg/operator/ceph/controller/spec_test.go
- pkg/operator/ceph/file/mds/mds.go
The operator will now allow the resource limits to be applied below the recommended minimums. In small clusters, even the recommended minimums may not be necessary. A warning is still printed to the operator log, but we allow the configuration to continue.
Resolves: #5079 
**Checklist:**
> ceph: Continue with memory limits below min settings

- tests/integration/ceph_smoke_test.go
Currently, SmokeTest is not cleaned up after the test.
As this can affect other following tests, this commit sets rookCephCleanup as true.
To use cleanup job, it needs to be cleaned `rook-ceph-rbd-mirror` pod beforehand [here](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/cleanup.go#L163-L220).
Therefore, this commit also deletes CephRBDMirror resource after its test is over
Resolves #
**Checklist:**
[test ceph]
> ci: clean up after SmokeTest

- Documentation/ceph-cluster-crd.md
- pkg/operator/ceph/csi/csi.go
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/spec_test.go
- pkg/operator/ceph/operator.go
- pkg/operator/k8sutil/network.go
CSI pods now utilize multus networking and connect to public
network specified in the CephCluster CR.
Resolves #5356 
**Checklist:**
[test ceph]
> ceph: added support for multus for csi

- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/health.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/rgw.go
There is incorrect usage of log functions in object directory, changing those instances
Resolves #
**Checklist:**
> ceph: use proper log functions in object package

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
- tests/framework/installer/ceph_csi_templates.go
The lifecycle preStop hook fails on container stop/exit because /bin/sh is not present in the driver registrar container image.
the driver-registrar will remove the socket file before stopping. we don't need to have any preStop hook to remove the socket as it was not working as expected
Resolves #4427
**Checklist:**
// known issue in master
[skip ci]
> ceph: remove preStop from daemonset template

- pkg/operator/ceph/csi/spec.go
We must only return if multus got configured successfully.
Resolves https://github.com/rook/rook/issues/6151
**Checklist:**
> ceph: correctly return if multus was applied

- go.mod
- go.sum
package golang.org/x/text v0.3.3 fixes the Vulnerability
in golang.org/x/text which could lead to infinite loop when
providing single byte to utf16 decoder.
Resolves #
**Checklist:**
> ceph: vulnerability in package golang.org/x/text

- pkg/operator/ceph/cluster/watcher.go
This change is the first part to improve the watch OSD nodes logic in
the Rook Ceph operator.
This commit changes the "is node valid check" to use the OSD placement
instead of the all placement. The OSD placement is "merged" with the
all placement already.
Second step will be to skip the first "iteration" of the "nodes added"
events and then start the actual watch logic.
Partially resolves #6111.
Partially resolves #6111.
**Checklist:**
> ceph: operator should only "watch" OSD placement nodes

- Documentation/ceph-common-issues.md
node-hangs-after-reboot problem can't be fixed with ceph-csi:2.0.1 if Rook is v1.2.x. It's because this version doesn't have a bind mount that is needed to fix this problem.
Nothing
**Checklist:** …
> ceph: improve common issues document

- pkg/operator/ceph/object/bucket/provisioner_test.go
- pkg/operator/ceph/object/controller_test.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/rgw_test.go
- pkg/operator/ceph/object/s3-handlers.go
- pkg/operator/ceph/object/status_test.go
Use debug log to all the s3 calls so it's either to debug. Also, it's
not so verbose.
Example output of a bucket creation:
```
2020/08/26 16:10:19 DEBUG: Request s3/CreateBucket Details:
---[ REQUEST POST-SIGN ]-----------------------------
PUT /leseb-testing HTTP/1.1
Host: rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local
User-Agent: aws-sdk-go/1.34.10 (go1.13.4; linux; amd64)
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=KWT9T5AMC6X7DOIPI0KP/20200826/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=494fd28799922239355a30a701ba5aa899f06a2eedc881b7b15715b9baaee80c
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: …
```
> ceph: run obc requests with debug

- pkg/daemon/ceph/osd/nsenter.go
- pkg/daemon/ceph/osd/nsenter_test.go
Trying to execute a binary from the host within the container can result
in mismatched libraries. The host version is compiled with paths of
libraries on the host where the libs inside the container can differ.
Because the path is known and we only need to make sure whether the bin
exists or not then simply doing a lookup when we fallback on /rootfs is
sufficient.
Resolves https://github.com/rook/rook/issues/6078
**Checklist:**
> ceph: do not exec on rootfs just lookup

- Jenkinsfile
- tests/framework/installer/ceph_manifests_v1.2.go
With the pending release of k8s 1.19 we need to start running the integration tests on 1.19. In master we remove support for 1.14 to keep the last five releases running in master.
**Checklist:**
// known issue
[skip ci]
> ci: Run integration tests on k8s 1.19

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/controller.go
This adds an uninstall mode to the ceph cluster. If the UninstallMode CR spec is set to `yes-really-uninstall-even-if-in-use` then the cluster deletion does not wait for the PVs to be deleted.
Resolves #
**Checklist:**
> ceph: add uninstall mode

- tests/scripts/kubeadm.sh
It's messy to answer `y` everytime in `tests/script/kubeadm.sh clean.` Since the cluster only exists for testing, it's safe to reset without prompting.
Nothing
**Checklist:**
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-sto …
> ci: reset test cluster without prompting

- Documentation/ceph-cluster-crd.md
Fixes formatting issue in markdown. On the website the code blocks are not being rendered into HTML because of source markdown spacing issue.
**Checklist:**
[skip ci]
> docs: fix markdown code block formatting issue

- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/controller/predicate.go
- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/health.go
- pkg/operator/ceph/object/s3-handlers.go
- pkg/operator/ceph/object/spec.go
- tests/integration/ceph_base_object_test.go
We must move the endpoint creation after the service monitor otherwise,
the service monitor will override the endpoint values.
**Checklist:**
[test ceph]
> ceph: do not use label selector on external svc

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
If the dashboard module is not enabled we don't need to run the
"dashboard-server-addr" init container.
Resolves #
**Checklist:**
> ceph: only enable init container if dash is enabled

- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/remove.go
If an OSD is down and needs to be removed from the cluster,
a job can be run that will remove the OSD deployment
and purge the OSD from ceph. If the OSD is still up,
the purge will be rejected.
To purge multiple OSDs at the same time, the OSD IDs can be
specified as a comma-separated list.
Signed-off-by: Servesha Dudhgaonkar <sdudhgao@redhat.com>
Resolves #
**Checklist:**
> ceph: purge a down osd with a job

- Documentation/ceph-common-issues.md
The problem of OSD on LV-backed PVC can be mitigated with disabling `lvmetad`.
Nothing
**Checklist:** …
> ceph: update the note of OSD on LV-backed PVC

- Jenkinsfile
The PRs only test against amd64 and have no need for the arm64 builds. This will save several minutes of build time. This is split out of #5847 so we can get this improvement before the full solution for storage provider builds.
**Checklist:**
[test nfs]
> ci: Only build amd64 for PRs

- pkg/daemon/ceph/osd/remove.go
Call logger.Infof() instead of Debugf() in remove.go file.
Signed-off-by: Servesha Dudhgaonkar <sdudhgao@redhat.com>
Resolves #
**Checklist:**
> ceph: update remove.go

- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/node_test.go
- pkg/operator/ceph/cluster/mon/service.go
- pkg/operator/ceph/cluster/mon/spec.go
If the mon failover fails and the mon is backed by a pvc, the pvc could remain orphaned. This is likely to happen if there is not a node available for scheduling the mon. Therefore, the operator will ensure after a failover that any orphaned mon pvc is cleaned up.
On a related change, the pvc_name label was not being set as expected on canary deployments. Now the label will always be set on both the canary and the daemon pods.  
This replaces #6199.
**Checklist:**
> ceph: Cleanup mon canary pvc if the failover failed

- tests/integration/ceph_base_deploy_test.go
In K8s 1.19 the integration tests are not running in PRs since no test suites were assigned to 1.19. Similarly, the flex suite was not being run since 1.14 was removed from the test matrix in master.
**Checklist:**
> ceph: Run integration tests on k8s 1.19 for PRs

- pkg/operator/ceph/csi/spec.go
currently, we are setting the rook operator as the owner on the csidriver objects, as csidriver is cluster the scoped object we should not set a namespaced object as the owner on cluster scoped object.
Resolves #
**Checklist:**
[test ceph]
> ceph: dont set ownerRef when creating csidriver object

- pkg/operator/ceph/object/bucket/provisioner_test.go
- pkg/operator/ceph/object/controller_test.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/rgw_test.go
- pkg/operator/ceph/object/status_test.go
By addding ".svc" to the endpoint of the object store,
will fix the custom DNS suffix cluster.
Resolves #6209
**Checklist:**
> ceph: fixed DNS suffix breaks in custom DNS suffix clusters

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
this commit will add a new flag to the osd pods
which will be named according to the name of the
storageClassDeviceSet. This will help in differentiate
pods immediately.
Resolves #6146
**Checklist:**
> ceph: add storageClassDeviceSet label to osd pods

- pkg/operator/ceph/csi/spec.go
currently, we are setting the rook operator as the owner on the csidriver objects, as csidriver is cluster the scoped object we should not set a namespaced object as owner on cluster scoped object.
(cherry picked from commit b88373f9f3905ca044cb3d8621e31347cb737b61)
Resolves #
**Checklist:**
[skip ci]
> ceph: dont set ownerRef when creating csidriver object (bp #6232)

- tests/framework/installer/ceph_installer.go
- tests/scripts/localPathPV.sh
The name of the disk in the CI changed from xvdc to nvme0n1
**Checklist:**
// need to get the fix in asap
[skip ci]
> ci: Change name of the disk used in the build

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Enables the 'create-external-cluster-resources.py' script to check a given TLS (https) enabled rgw-endpoint.
Resolves #
**Checklist:**
[skip ci]
> ceph: fix to support TLS enabled rgw-endpoint

- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/spec_test.go
We don't fail anymore if the cluster is external and user wants to
bootstrap rgw gateways in Kubernertes.
Closes: https://github.com/rook/rook/issues/6217
Resolves https://github.com/rook/rook/issues/6217
**Checklist:**
> ceph: allow running rgw in rook with external mode

- pkg/operator/ceph/cluster/mon/spec.go
The selector labels used for mons cannot change during upgrade or else the upgrade will hang when the cluster is checking for mon status immediately after the upgrade begins.
This is a regression in the cluster-on-pvc upgrade scenario caused by #6224 where the pvc_name label was added. 
Until the v1.4.4 release is out, the workaround for upgrading to v1.4.3 is to add the following label to each respective mon deployment either before the upgrade or after the upgrade had hit the blocking issue. If the upgrade doesn't immediately start, you may need to restart the operator:
```
pvc_name=rook-ceph-mon-a
```
**Checklist:**
> ceph: Upgrade to v1.4.3 for cluster-on-pvc example hangs due to changing label selectors on the mons

- cmd/rook/ceph/osd.go
Drive Groups will fail to deploy due to a message: `failed to parse
device list (""): failed to JSON unmarshal configured devices (""):
unexpected end of JSON input`
This is due to trying to JSON unmarshal an empty string which does not
contain any devices to provision when Drive Groups are specified. Fix so
that an empty string represents no non-Drive Group devices.
Resolves #
**Checklist:**
> ceph: fix drive group deployment failure

- pkg/operator/ceph/cluster/mgr/mgr_test.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
ROOK_CEPH_CLUSTER_CRD_NAME is incorrectly set to cluster namespace value
Signed-off-by: Varsha <varao@redhat.com>
Resolves #
**Checklist:**
> ceph: set ROOK_CEPH_CLUSTER_CRD_NAME with cluster name

- pkg/operator/ceph/cluster/cluster_external.go
We only need to read the ceph cluster version if the cluster external
has external monitoring enabled.
This avoids any issue during upgrades from 1.3 to 1.4 when monitoring is
enabled and ceph caps have not been updated.
Resolves #
**Checklist:**
> ceph: only run version check for monitoring

- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/k8sutil/deployment.go
If the pod spec changed, we expect an upgrade to proceed for that daemon. If the check for a changed pod spec fails, we were skipping the update of that daemon. Instead of skipping the update, we now assume the pod spec changed if we fail to detect the change so that we can ensure the upgrade even if we check for upgrades too often.
The case of failure in #6268 appears to be from env vars being duplicated in the osd pod spec. Now we avoid that duplication so we won't hit diff detection failure at least in that case.
Resolves #6268 
**Checklist:**
> ceph: If spec diff checking fails during upgrade, assume it changed

- tests/README.md
- tests/framework/installer/cassandra_installer.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/cockroachdb_installer.go
- tests/framework/installer/edgefs_installer.go
- tests/framework/installer/environment.go
- tests/framework/installer/installer.go
- tests/framework/installer/nfs_installer.go
- tests/framework/installer/provisioners.go
- tests/framework/installer/yugabytedb_installer.go
- tests/framework/utils/env.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_smoke_test.go
This commit enables the rook integration
testing capability on OpenShift. currently,
this commit enables CephSmokeSuite testing
only.
Current result 
```
go test -v -timeout 1800s -run CephSmokeSuite github.com/rook/rook/tests/integration
FAIL: TestCephSmokeSuite (1348.94s)
--- PASS: TestCephSmokeSuite/TestARookClusterInstallation_SmokeTest (28.94s)
--- PASS: TestCephSmokeSuite/TestBlockStorage_SmokeTest (254.16s)
--- PASS: TestCephSmokeSuite/TestCreateClient (25.71s)
--- PASS: TestCephSmokeSuite/TestCreateRBDMirrorClient (30.92s)
--- PASS: TestCephSmokeSuite/TestFileStorage_SmokeTest (138.12s)
--- PASS: TestCephSmokeSuite/TestMonFailover (25.40s)
--- FAIL: TestCephSmokeSuite/TestObjectStorage_SmokeTest (126.95s)
--- PASS: TestCephSmokeSuite/TestPoolResize (32.58s)
FAIL
FAIL …
```
> ceph: integration test on openshift

- cluster/examples/kubernetes/ceph/cluster.yaml
'rook' module is not enabled by default. So update the wrong comment about it.
[skip ci]
Resolves #
**Checklist:**
> ceph: update about 'rook' module  in cluster.yaml

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- pkg/operator/ceph/csi/spec.go
- tests/framework/installer/ceph_manifests.go
currently, we are setting the rook  operator as the owner on the csidriver objects,  as csidriver is cluster
the scoped object we should not set a namespaced object as owner on cluster scoped object.
Resolves #6162
**Checklist:**
> ceph: remove owner reference set by rook on csidriver

- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/config/config.go
- pkg/daemon/ceph/config/config_test.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/cluster/mon/env.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/osd/spec.go
Some parameter like bluestore_min_alloc_size, bluestore_min_alloc_size_hdd need to be set during the bootstrap of the
ceph cluster in order to have bluestore created accordingly.
To do so rook users rely on the rook-config-override configmap.
Sadly the rook-ceph-osd-prepare job does not take in account this configmap to generate its ceph config.
Changing the behaviour to merge the config from rook-config-override configmap to the default ceph config
(cherry picked from commit de7ca0193005c26b2c830df776fb1950cf76b64f)
In order to backport this commit to 1.3 branch I had to duplicate fake cluster creation and ConfigOverrideName var to avoid circular dependency issues on tests
I want to discuss this with you …
> ceph: merge rook-config-override to the default global config file

- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/deviceset_test.go
The pvc template name has either been require to be empty, or one of the expected values such as data and metadata. Those who upgrade from 1.1 may find that if they changed it to something else, their upgrade will fail when not one of these values. If there is only a single template, always treat it as the data template.
This is related to #5639 where names started being enforced in the templates.
**Checklist:**
> ceph: allow osd pvc template name set to any value

- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/deviceset_test.go
The pvc template name has either been require to be empty, or one of the expected values such as data and metadata. Those who upgrade from 1.1 may find that if they changed it to something else, their upgrade will fail when not one of these values. If there is only a single template, always treat it as the data template.
**Checklist:**
> ceph: Allow osd pvc template name set to any value (bp #6307)

- README.md
This PR updates the readme with the community meeting zoom link to now have a password. Zoom is now requiring this as of this weekend: https://support.zoom.us/hc/en-us/articles/360045009111
**Checklist:**
[skip ci]
> readme: update community meeting zoom link with password (required by zoom now)

- cluster/examples/kubernetes/ceph/import-external-cluster.sh
We do not support providing both ROOK_EXTERNAL_USER_SECRET and
ROOK_EXTERNAL_ADMIN_SECRET. When both are provided in the mon secret,
the operator code will use the client.admin user for all its operations.
This will break some of the logic when creating OBC since if
client.admin is detected we assume the cluster is converged and thus
pass args like this:
```
--rgw-realm=external-store --rgw-zonegroup=external-store --rgw-zone=external-store
```
To the radosgw-admin command, which won't work since Rook has no idea
what the external realm/zonegroup/zone are, if any are configured.
This fix should be sufficient for now, but moving forward we should
probably enhance clusterInfo with an "isExternal" property to make
things easier. Also supporting external …
> ceph: only support one external cluster secret

- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/user.go
User unlink is performed just before deleting OBC resources.
Since user is internal to OBC and next to remove to delete user,
unlinking user is not necessary.
Resolves: #6300
**Checklist:**
> ceph: remove user unlink while deleting OBC

- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/osd.go
The OSDs on PVCs were being reconciled inefficiently one by one with a label selector. This proves to be slow in large clusters. Instead, we now make this more efficient by querying for all existing PVCs and deployments and looking them up in memory with a map. This will save several minutes for the reconcile in a cluster with 100 OSDs.
**Checklist:**
> ceph: Detect OSDs on PVCs in batches instead of with label selectors individually

- pkg/operator/ceph/nfs/config.go
- pkg/operator/ceph/nfs/controller_test.go
- pkg/operator/ceph/nfs/nfs.go
- pkg/operator/ceph/nfs/spec.go
Ganesha daemons don't need to acess ceph cluster with admin capabilities.
Instead new user with restricted caps can be used.
Resolves #
**Checklist:**
> ceph: create user for each ganesha daemon

- pkg/operator/ceph/cluster/osd/spec.go
On LUKS2 format, the resize operation requires the KEK to be passed. To
maintain a single simple init container for resize, we now open the
encrypted block with  "--disable-keyring" so that further operations
won't require the keyring.
Resolves #
**Checklist:**
> ceph: disable keyring after opening encrypted block

- pkg/operator/ceph/object/bucket/provisioner.go
During the 1.3 cycle, we had implemented support for OBC external mode
through an Endpoint in the StorageClass parameter. In 1.4, this is not
the case anymore as we directly use the CephObjectStore external mode.
However, we must maintain backward compatibility with the cluster using the
Endpoint and not fail the upgrade.
Thus checking for a CephObjectStore is invalid and should not always be
assumed, now if we detect an Endpoint we return a simple context which
fixes the upgrade.
**Checklist:**
> ceph: fix obc upgrade from 1.3 to 1.4 external cluster

- tests/integration/ceph_smoke_test.go
The smoke suite relies on the csi driver for all the file and block tests. In the release branch on k8s 1.11 we only need to run the flex suite and can skip the smoke suite.
**Checklist:**
> ceph: Skip smoke suite on k8s 1.11

- Documentation/ceph-object-multisite-crd.md
- Documentation/ceph-object-multisite.md
* fix typo `zoneGroup` in ['Object Multisite CRDs' docs](https://rook.io/docs/rook/v1.4/ceph-object-multisite-crd.html#ceph-object-zone-crd)
* fix cleanup instruction in ['Object Multisite' docs](https://rook.io/docs/rook/v1.4/ceph-object-multisite.html)
N/A
**Checklist:**
[skip ci]
> docs: fix typo in ObjectMultisite docs

- tests/integration/ceph_base_file_test.go
- tests/integration/ceph_flex_test.go
this commit will add error not found condition
check before assert delete on PVC and
statefulset due to whch flex test was failing.
Resolves #6361
**Checklist:**
[test full]
> ceph: flex test failing in CI

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- pkg/apis/rook.io/v1/types.go
- pkg/operator/ceph/cluster/osd/config.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
On Azure, all SSDs are reporting as a rotational disk.
This commit will add `tuneFastDeviceClass` flag which will
tune for an SSD even if the cloud provider is reporting
rotational.
Resolves #6153 
**Checklist:**
> ceph: tune fast device class for OSD on PVC in the Azure

- pkg/operator/ceph/cluster/controller.go
Once we close the channel for the monitoring daemons, we update the
monitoring status so as to not call them again.
This is to prevent "close of closed channel" panic.
Co-authored-by: Nitin Goyal <nigoyal@redhat.com>>
Signed-off-by: Raghavendra Talur <raghavendra.talur@gmail.com>
Once we close the channel for the monitoring daemons, we update the
monitoring status so as to not call them again.
This is to prevent "close of closed channel" panic.
Resolves #
**Checklist:**
> ceph: prevent closing of channel more than once

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/controller/spec.go
- pkg/operator/ceph/controller/spec_test.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/object/spec.go
- Add `--ms-bind-ipv6 true` args to following daemons
- mon, osd, mgr, object, mds, rbd
Pending: 
Resolves #3850
Initial testing on local multi-node IPv6 cluster:
1. OSD on devices:
```
NAME                                                    READY   STATUS      RESTARTS   AGE     IP                      NODE         
csi-cephfsplugin-j8p2h                                  3/3     Running     0          35m     fd00:f00d::102          k86-worker2   
csi-cephfsplugin-provisioner-559f57dff6-4sknq           6/6     Running     0          35m     fd00:f00d::103:0:0:7    k86-worker3 
csi-cephfsplugin-provisioner-559f57dff6-pkz2w           6/6     Running     0 …
```
> ceph: support IPv6 single-stack

- Documentation/edgefs-nfs-crd.md
Add a note that NFS service names created by efscli need to comply with
k8 DNS naming restrictions. Failure to do so will result in an invalid NFS
object manifest name.
Signed-off-by: Benjamin Deuson <benjamindeuson@gmail.com>
[skip ci]
Resolves #
**Checklist:**
> edgefs: docs: note nfs service name restrictions

- pkg/operator/ceph/cluster/osd/spec.go
this commit remove _ssd  suffix from
tuneFastDeviceClass setting as with _ssd
won't affect disk.
Resolves #
**Checklist:**
> ceph: remove suffix _sdd for tuneFastDeviceClass

- tests/integration/ceph_base_file_test.go
Sometimes CephFlexSuite fails with the following backtrace.
```
--- FAIL: TestCephFlexSuite (584.14s)
--- PASS: TestCephFlexSuite/TestBlockStorageMountUnMountForDifferentAccessModes (163.66s)
--- PASS: TestCephFlexSuite/TestBlockStorageMountUnMountForStatefulSets (83.21s)
--- FAIL: TestCephFlexSuite/TestFileSystem (119.51s)
ceph_base_file_test.go:487:
Error Trace:    ceph_base_file_test.go:487
ceph_base_file_test.go:265
ceph_flex_test.go:113
Error:          Expected nil, but got: &errors.errorString{s:"kubectl exec command bash failed on pod rook-ceph-tools in namespace flex-ns. Failed to run: kubectl [exec -n flex-ns rook-ceph-tools -- bash -c mount -t ceph -o mds_namespace=smoke-test-fs,name=admin,secret=$(grep key /etc/ceph/keyring | awk '{print $3}') …
```
> ci: fix an intermittent failure of ceph flex suite

- Documentation/ceph-pool-crd.md
The rbdMirrorBootstrapPeerSecretName always starts with pool-peer-token- when we pool is created with mirroring enabled.
Resolves #
**Checklist:**
[skip ci]
> ceph: fix example rbdMirrorBootstrapPeerSecretName in mirror doc

- Documentation/ceph-nfs-crd.md
- pkg/operator/ceph/nfs/config.go
- pkg/operator/ceph/nfs/nfs.go
In cephadm and volume/nfs module, all ganesha daemons within a cluster watch
single config object. Each ganesha daemon in rook watches it's own config
object. These patches updates the ganesha config object name to maintain
uniformity.
Resolves #
**Checklist:**
> ceph: update nfs ganesha rados config object

- pkg/operator/ceph/object/s3-handlers.go
When rgw is not responding the aws-sdk retries using exponential
backoff. Having 20 retries means we would wait for a while (hours) to
eventually fail. This is a problem as we cannot reflect the status of
the bucket properly.
Now we use 5 max retries which means around 8 seconds.
Resolves #
**Checklist:**
> ceph: reduce s3 max retry

- pkg/util/exec/exec.go
In order to properly debug errors, we need to merge stderr inside the
`err` reported so that we don't only see the stdout.
We were doing this when executing without file output, doing the same
for the output file.
Resolves #
**Checklist:**
[test full]
> ceph: log stderr in error when exec with output file

- go.mod
- pkg/operator/ceph/cluster/osd/envs.go
- pkg/operator/ceph/cluster/osd/envs_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
We can now tune the value of TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES by
setting an annotation on the CephCluster CRD like so:
```
annotation:
osd:
TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES: "134217728"
```
Alternatively, if nothing is specified Rook will read the value of the
file `/etc/sysconfig/ceph`.
Closes: https://github.com/rook/rook/issues/6134
Resolves #
**Checklist:**
> ceph: tune osd tcmalloc thread cache bytes

- pkg/operator/ceph/cluster/watcher.go
When a node is not tolerable, also output the node name so it's clear
which not it is which is not tolerable.
Signed-off-by: Thomas Bechtold <tbechtold@suse.com>
Resolves #
**Checklist:**
> ceph: Improve watcher debug message when node is not tolerable

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- pkg/apis/ceph.rook.io/v1/validate_clusters.go
- pkg/apis/ceph.rook.io/v1/validate_clusters_test.go
- pkg/operator/ceph/cluster/cluster.go
The ceph mons should never be started with an even number in quorum. The desired state should always be an odd number of mons to ensure a healthy majority quorum. The operator now rejects a request for an even number of mons.
If there is not a sufficient number of nodes for mons to be on a unique host, the operator also returns an early error instead of getting stuck waiting for a pending mon. This is not foolproof since there might in reality be fewer available nodes for the mons due to placement, but at least it is a quick check for the common case.
**Checklist:**
> ceph: Require an odd number of mons and sufficient nodes for mons

- Jenkinsfile
- tests/framework/installer/environment.go
- tests/scripts/helm.sh
Download the pre-defined helm by default to make the integration test simpler. As a result, we can make PATH/TEST_HELM_PATH environment variable optional. In addition, the default helm path can be simplified that doesn't include arch and os.
Nothing
**Checklist:**
[test ceph]
> ci: fix helm path

- Documentation/ceph-common-issues.md
- Documentation/ceph-upgrade.md
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
Use raw mode OSD instead of lvm mode even if LV-backed PVC.
Resolves #5939 
**Checklist:**
[test full]
> ceph: raw mode OSD on LV-backed PVC

- tests/framework/installer/ceph_installer.go
- tests/framework/installer/environment.go
Fix the following minor bugs.
- The wrong description of TEST_BASE_DIR environment variable.
- baseTestDir() don't handle error properly
Nothing
**Checklist:**
[test ceph]
> ci: cleanup base directory code

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- pkg/operator/ceph/csi/spec.go
The default number of provisioner pods are 2. When there is only one node, for example, the CI environment, one of these becomes Pending state. Although it's harmless, it's better to reduce this value to 1.
Resolves #6294 
**Checklist:** …
> ceph: reduce the number of provisioner pods in small K8s cluster

- tests/README.md
- tests/scripts/dind-cluster.sh
We can't use vm-drivers other than "docker" or "none" in minikube scripts. It's because there is no device for OSD.
Nothing
**Checklist:**
- [o] Reviewed the …
> ci: clarify the supported vm-driver of minikube scripts

- tests/scripts/helm.sh
The reason why I start this pull request is that when I use 'make -j4' to build rook, if I don't delete arg 'z' in 'tar -zxvf',  compile process while return compilation fails in centos7. And this is my solution to fix it.
Signed-off-by: ZhenLiu94 <zhenliu94@163.com>
Resolves #
**Checklist:**
> build: fix error when building rook in centos7

- build/makelib/helm.mk
- tests/scripts/helm.sh
To be able to switch to helm v3, helm itself needs to be downloaded from
get.helm.sh. The old location from googleapis.com will only contain
helm v2 binaries. See [1].
[1] https://helm.sh/blog/get-helm-sh/
Signed-off-by: Thomas Bechtold <tbechtold@suse.com>
> helm: use get.helm.sh instead of storage.googleapis.com

- tests/scripts/helm.sh
Remove a workaround code of old-Jenkins-file-is-used-in-CI problem.
Nothing
**Checklist:** …
> ci: remove an unnecessary code

- pkg/operator/ceph/webhook.go
The number of admission controller pods is 2. When there is only one node as the CI environment, one of these becomes Pending state. Although it's harmless, it's better to reduce this value to 1.
Nothing
**Checklist:** …
> ceph: reduce the number of admission controller pods in small cluster

- pkg/operator/ceph/disruption/clusterdisruption/mon.go
- pkg/operator/ceph/disruption/clusterdisruption/mon_test.go
- pkg/operator/ceph/disruption/clusterdisruption/static_pdb.go
updated mon pdb reconcile to delete mon pdb and create a new one when mon count changes in the cluster spec
Tests:
- 3 Mons
```
Every 2.0s: oc get pdb                                                       localhost.localdomain: Wed Oct 21 13:45:00 2020
NAME                MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
rook-ceph-mon-pdb   2               N/A               1                     3m58s
```
- Updated mon count from 3 to 5
```
Every 2.0s: oc get pdb                                                       localhost.localdomain: Wed Oct 21 13:48:37 2020
NAME                MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
rook-ceph-mon-pdb   3               N/A               2                     2m47s
```
- updated mon count from 5 to 3
```
Every 2.0s: oc …
```
> ceph: fix mon pdb reconcile

- .github/workflows/golangci-lint.yaml
golangci linter sometimes failing due to
the timeout. So, increasing it to 6m from 4m.
Resolves #
**Checklist:**
> ci: increase golangci linter timeout

- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/controller_test.go
- pkg/operator/ceph/object/zone/controller.go
Add unit tests for when the "Zone" is configured
in an object store so that the object store joins
the CephObjectZone and the zone's corresponding
multisite configuration.
Resolves #6387
**Checklist:**
> ceph: Add unit tests for object store controller with multisite

- Documentation/ceph-monitoring.md
This updates the Ceph docs regarding the Grafana dashboards new version
requirement.
Resolves #6430
**Checklist:**
[skip ci]
> docs: update ceph monitoring examples

- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/mon.go
The mon resources may be orphaned if there is a mon failover that was cancelled, for example a mon pvc may remain if the original mon comes up and the operator was restarted before the mon failover completed. The cleaning up of mon resources was only happening was each successful mon failover, now we perform the check with every reconcile since the resources were not being cleaned up predictably enough.
**Checklist:**
> ceph: Check for orphaned mon resources with every reconcile

- PendingReleaseNotes.md
this commit update PendingReleaseNotes.md with
PR #6475 i.e export the storage capacity of
the ceph cluster.
Resolves #
**Checklist:**
> docs: update PendingReleaseNotes.md

- Documentation/ceph-disaster-recovery.md
Adds guidelines for performing disaster recovery for rook-ceph in kubernetes clusters with PVCs. The existing guide contains many unnecessary steps for this case - it can be handled using only regular kubernetes resources.
Resolves https://github.com/rook/rook/issues/6442
**Checklist:**
> disaster recovery guide for PVCs

- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/object/rgw.go
this commit removes unnecessary allNodes option
from rgw as it's already been removed.
Resolves #
**Checklist:**
> ceph: remove allNode option for rgw

- pkg/util/exec/exec.go
- pkg/util/exec/exec_test.go
We don't always get an error of the type "*exec.ExitError" so we must
validate the type before printing it otherwise the interface conversion
will fail.
Resolves https://github.com/rook/rook/pull/5483#discussion_r506942433
**Checklist:**
> ceph: assert error type before using it

- Documentation/ceph-common-issues.md
- Documentation/ceph-quickstart.md
- Documentation/k8s-pre-reqs.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster-with-drive-groups.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/nfs.yaml
- cluster/examples/kubernetes/ceph/pre-k8s-1.16/crd.yaml
- design/common/object-bucket.md
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.2.go
the apiextensions.k8s.io/v1beta1 version of CustomResourceDefinition
is deprecated in Kubernetes v1.16 and will no longer be supported from
v1.22. For now, we changing only for ceph and it's related documented.
co-authored-by: travisn <tnielsen@redhat.com>
Resolves #5552 
**Checklist:**
[test full]
> ceph: update deprecated CRD apiextensions.k8s.io/v1beta1 to v1

- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/controller/controller_utils_test.go
This allows the catch-22 situation where the filesystem cannot be
reconciled because there is no MDS but there is no MDS because the
operator has not reconciled the filesystem and brought up the MDS pods.
Closes #5967, #5846
Signed-off-by: Lalit Maganti <lalitm@google.com>
This allows the catch-22 situation where the filesystem cannot be
reconciled because there is no MDS but there is no MDS because the
operator has not reconciled the filesystem and brought up the MDS pods.
Resolves #5967, #5846
**Checklist:**
> ceph: ignore MDS_ALL_DOWN during reconciliation

- pkg/apis/rook.io/v1/annotations.go
- pkg/apis/rook.io/v1/labels.go
- pkg/apis/rook.io/v1/labels_test.go
- pkg/operator/ceph/cluster/mon/spec.go
[test ceph]
#6084 enables users to add custom labels to rook-managed pods. It, however, does not propagate them to mon pods.
This PR fixes that and also improves comments and tests for `ApplyToObjectMeta` to mitigate my confusion while making this PR.
Resolves #
**Checklist:**
> ceph: Label mon pods

- Documentation/ceph-filesystem-crd.md
- Documentation/ceph-filesystem.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/filesystem-ec.yaml
- cluster/examples/kubernetes/ceph/filesystem-test.yaml
- cluster/examples/kubernetes/ceph/filesystem.yaml
- cluster/examples/kubernetes/ceph/pre-k8s-1.16/crd.yaml
- cluster/examples/kubernetes/ceph/upgrade-from-v1.3-crds.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/filesystem.go
- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_base_file_test.go
- tests/integration/ceph_flex_test.go
- tests/integration/ceph_smoke_test.go
Due to #6492, preservePoolsOnDelete is not useful at all for CephFS;
after the filesystem is deleted, the leftover pools cannot be
reassocaited with a newly created filesystem without wiping all
metadata. The only way we can actually preserve data is keeping around
the entire filesystem.
This commit implements a `preserveFsOnDelete` option which works similar
to the existing pool preservation option but instead keeps the whole
CephFS while taking it down and removing all MDSes.
This commit also changes all documentation to refer to this new option
with the intent of essentially deprecating `preservePoolsOnDelete`. IMO,
keeping around `preservePoolsOnDelete` is actively harmful because it
lulls users into thinking their data will be safe but, in reality, …
> ceph: add option to preserve filesystem on CRD deletion

- pkg/daemon/ceph/osd/kms/envs_test.go
Golang maps order is not always guaranteed to be identical, which makes
the table-driven test to fail. Because of the nature of the maps, it is
hard to predict the exact position of an element on the map. This
makes the table-driven test flappy.
Reworked the unit test using a contains statement which achieves the
same validation.
Closes: https://github.com/rook/rook/issues/6522
Resolves https://github.com/rook/rook/issues/6522
**Checklist:**
> ceph: rework unit test

- tests/framework/installer/ceph_installer.go
The ceph v14.2.13 release has breaking changes for the ceph-volume batch scenario that is preventing non-pvc OSDs from being created. In the short term we will pin the tests to v14.2.12 and separately we will need to address the changes needed and/or wait for a fix from ceph.
Resolves #6532 
**Checklist:**
> ceph: Tests need to use v14.2.12 due to broken osds in v14.2.13

- pkg/operator/ceph/cluster/osd/spec.go
We now support VAULT_TLS_SERVER_NAME which represents the name to use as
the SNI host when connecting via TLS.
This is typically needed when a single host has multiple certificates,
same as virtual hosts but for SSL certificates.
**Checklist:**
> ceph: add support for VAULT_TLS_SERVER_NAME

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Currently, Rook does not support a prometheus exporter port different
than 9283 so let's fail and force the user to set it to the default.
Resolves #
**Checklist:**
[skip ci]
> ceph: fail if mgr prometheus is not default

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/pre-k8s-1.16/crd.yaml
helm test for k8s 1.15 failing showing errors
CRDs not found, after some latest changes to CRDS.
Resolves #6531 
**Checklist:**
[test full]
> ceph: helm test for k8s 1.15 failing

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- tests/framework/installer/ceph_manifests.go
this commit add the missing `deviceClass` field
in filesystem CRD with replication of pool spec.
Resolves #6548 
**Checklist:**
> ceph: some fields in FS CRD are missing

- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/version.go
- pkg/operator/ceph/version/version.go
- pkg/operator/ceph/version/version_test.go
We now use the recommended flag '--no-auto' when calling batch mode.
More details in https://tracker.ceph.com/issues/48106.
Resolves #6532
**Checklist:**
> ceph: add unit test for ceph-volume batch mode and warn about unsupported ceph version

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- Jenkinsfile
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/pre-k8s-1.16/crd.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_base_deploy_test.go
- tests/integration/nfs_test.go
- The CI in the release branch should run back to k8s v1.11 until we officially remove support for that version.
- Set the manifest version to v1.5.0-beta.0
**Checklist:**
> Set the manifest version to v1.5.0-beta.0 and enable release-1.5 tests back to K8s 1.11

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
cephfs csi driver still uses the ceph CLI for all the ceph fs operations, when cephcsi gets a request from the kubernetes it will internally start threads for each call. in cephcsi we are setting the pids limit to max, to set this value the container has
to be running as the privileged one. if we go with the default PID limit we will face a core dump due to a resource crunch.
without privileged access, we will see Failed to set new
```
PID limit to -1: open /sys/fs/cgroup/pids/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod1029ed37_bebc_466d_9e53_79e7323a67ed.slice/crio-9ef6768d027916f414bf30b54ef13eebad8efd0aa4741d97618affa838d7b4c0.scope/pids.max: permission denied
```
**Which issue is …
> ceph: add privileged securityContext to cephfs deployment

- Documentation/ceph-examples.md
- Documentation/ceph-quickstart.md
Signed-off-by: Gerhard Seidel <gseidel@xq-web.de>
When following the quick start, it may not work, because the user don't know that he need three nodes. And three nodes may also not be correct, because the control plane is also a node. So we should precise what the user need to run his cluster correctly.
Resolves #6540 
**Checklist:**
[skip ci]
> docs: precise three nodes

- tests/integration/ceph_base_block_test.go
- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_base_file_test.go
**Description of your changes:** 
The csi tests require 1.14 or newer, so we need to enable the flex test suite to run on 1.13 instead of the smoke suite.
**Checklist:**
> ceph: Disable smoke suite on k8s 1.13

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/pre-k8s-1.16/crd.yaml
- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_base_block_test.go
- tests/integration/ceph_base_file_test.go
- tests/integration/nfs_test.go
A few fixes that were needed to get tests passing in the release-1.5 branch yesterday that we will want to preserve in master:
- The csi tests require 1.14 or newer to run so disable the smoke suite on 1.13
- Remove nullable attribute from pre-1.16 schema
- NFS: skip running tests on older than k8s 1.14
**Checklist:**
> Integration test fixes for release branch to preserve in master

- Documentation/ceph-toolbox.md
Adjusts the kubectl commands for working with Ceph toolbox to make them more readable and fixes a warning with `kubectl exec` (specifying command-line arguments without the `--` separator is deprecated).
Resolves none
**Checklist:**
[skip ci]
> docs: better Ceph toolbox kubectl commands

- Documentation/ceph-quickstart.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cmd/rook/ceph/operator.go
- tests/framework/installer/ceph_manifests.go
The discovery daemon is not needed in most scenarios, therefore we disable it by default. More and more clusters are moving to the cluster-on-pvc scenario which certainly does not need the local discovery. Even where clusters are not running on PVCs, the discovery is not needed since the device discovery is again performed in the osd prepare job.
**Checklist:**
> ceph: Disable the discovery daemon by default

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster.yaml
The description of cleanupPolicy is a bit ambiguous. First, we should clarify that both skipping orchestration and data cleanup will happen iff "yes-really-destroy-data" is set to `confirmation`. Second, We should also describe wiping devices will happen even if user don't specify `sanitizeDisks` explicitly.
Nothing
**Checklist:**
- [o] …
> docs: clarify the meaning of cleanup policy of ceph cluster crd

- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/upgrade-from-v1.4-crds.yaml
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.4.go
- tests/integration/ceph_upgrade_test.go
Since Rook no longer supports legacy filestore devices, there is
no need to keep testing upgrades from v1.2 all the way to master.
We can now just test v1.4 to master.
Resolves #
**Checklist:**
// for better coverage before merge
[test full]
> ceph: upgrade test Rook only from v1.4 to master

- pkg/operator/ceph/object/controller.go
The RGW deployment's ceph-version label should now display the same
version as the image it is using.
It previously displayed an empty version: 0.0.0-0.
Resolves #6609
**Checklist:**
> ceph: fill in rgw deployment version

- pkg/daemon/ceph/client/filesystem.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/filesystem_test.go
When new pools are added to an already existing filesystem, we would
create them but not actually associate them to the filesystem. Ensure
that we do this.
Also, while we're here, we refactor the CreateFilesystem test: before,
we were not properly testing creating the filesystem from scratch
because we would return valid JSON for *every* ceph command. Change this
by making the first run return an error so that we get some better
coverage.
After this, we also add a check for the correctness of adding new pools
to the CreateFilesystem unittest.
Fixes #5876
Resolves #
**Checklist:**
[test ceph]
> ceph: associate newly created pools to existing filesystem

- Documentation/ceph-csi-snapshot.md
Due to upstream code motion, the current link to the upstream
ceph-csi-snapshot documentation no longer points to the correct
location of their CRDs. Fix this by just using the master branch.
Signed-off-by: Mike Latimer <mlatimer@suse.com>
Resolves #
**Checklist:**
[skip ci]
> docs: link to master branch for ceph-csi-snapshot

- Documentation/ceph-nfs-crd.md
- pkg/operator/ceph/nfs/config.go
- pkg/operator/ceph/nfs/controller_test.go
- pkg/operator/ceph/nfs/nfs.go
The expected nfs-ganesha config object name by mgr/volumes/nfs[1] plugin is
"conf-nfs.ganesha-\<clustername\>".
[1] https://github.com/ceph/ceph/blob/master/src/pybind/mgr/volumes/fs/nfs.py#L648-L655
Resolves #
**Checklist:**
> ceph: Add 'ganesha-' to nfs-ganesha config object name

- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/nfs/nfs.go
The NFS reconciler was not updating NFS daemons that already existed.
The controller would fail to update daemons if the number of active
daemons did not increase or decrease.
Resolves #6611
**Checklist:**
> ceph: fix nfs daemons not updating

- Documentation/ceph-filesystem-crd.md
- pkg/operator/ceph/file/controller.go
Allow filesystems with preservePoolsOnDelete to be used without errors.
A deprecation warning will still appear in the operator logs, but
existing cephfilesystem resources with preservePoolsOnDelete will still
be updated, and Rook will assume the new, preferred
preserveFilesystemOnDelete is set.
Resolves #
**Checklist:**
> ceph: allow deprecated fs  preservePoolsOnDelete

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/coreos/after-reboot-daemonset.yaml
- cluster/examples/coreos/before-reboot-daemonset.yaml
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
For the minor release we set the documentation and manifests
to use the v1.5.0 tag.
**Checklist:**
> build: Set manifest versions to v1.5.0

- tests/framework/utils/snapshot.go
in the integration test we still use
snapshotteVersion v2.1.0 but it's expected to
use v3.0.0.
Resolves #6640 
**Checklist:**
> ceph: update snapshotterVersion to v3.0.0

- Documentation/ceph-quickstart.md
crds were factored out from the common.yaml file and helm chart. This PR updates the quick start guide to use crds.yaml file.
Resolves #
**Checklist:**
[skip ci]
> ceph: update ceph quick start doc to use new crds.yaml file

- images/ceph/Dockerfile
- images/ceph/Makefile
We now ship the Rook container image with our external cluster scripts.
Closes: https://github.com/rook/rook/issues/6644
Resolves https://github.com/rook/rook/issues/6644
**Checklist:**
> ceph: add external script to the container image

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/common.yaml
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/config/network.go
- pkg/operator/ceph/config/network_test.go
- pkg/operator/ceph/csi/csi.go
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/csi/spec_test.go
- pkg/operator/ceph/operator.go
Support ceph cluster and CSI on multus deployed in diffrent namespace.
Previously csi was looking for multus config from the cluster deployed
in the namespace in which rook-ceph-operator/csi was deployed.
Now it will look for multus configuration from ceph clusters from all
the namespaces.
Resolves #
**Checklist:**
> ceph: support ceph cluster and CSI on multus in different namespace

- design/ceph/ceph-cluster-cleanup.md
Cleanup Policy design doc is not up to date to with respect to latest implementation. This PR updates the design doc.
updated `ceph-cluster-cleanup.md `  design doc
Resolves #
**Checklist:**
[skip ci]
> ceph: update cleanupPolicy design doc

- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/service.go
- pkg/operator/ceph/cluster/mon/service_test.go
In a disaster recovery scenario, the mon service may have been accidentally deleted, while the expected mon endpoint is still found in the mon endpoints configmap. In this case, we create the mon service with the same endpoint as previously.
**Checklist:**
> ceph: Restore mon clusterIP if the service is missing

- Jenkinsfile
we now run our ceph test or ceph suite
using GitHub actions, we can skip
Jenkins test for the same.
Resolves #
**Checklist:**
> ceph: update Jenkins to skip Ceph tests

- Documentation/ceph-cluster-crd.md
- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/crash/add.go
- pkg/operator/ceph/cluster/crash/crash.go
- pkg/operator/ceph/cluster/crash/keyring.go
- pkg/operator/ceph/cluster/crash/keyring_test.go
- pkg/operator/ceph/cluster/crash/reconcile.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/utils/k8s_helper.go
- tests/integration/ceph_multi_cluster_test.go
Signed-off-by: Renan Campos <rcampos@redhat.com>
Rook's crashcollector pod posts entries to the ceph cluster when a crash occurs. 
Over time the number cluster may hold crash entries needlessly. 
To clean up old crash entries, this PR adds a field to the ceph cluster CR for the user to specify the number of days a crash entry should be kept for. 
Providing a value for the field keepXDays creates a cronjob that runs every day at midnight, calling "ceph crash prune <keepXDays>". 
Resolves #6332 
**Checklist:**
[test full]
> ceph: periodically prune crash entries older than user-provided days

- cmd/rook/rook/rook.go
- go.mod
- go.sum
- pkg/clusterd/context.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/cluster_external.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/predicate.go
- pkg/operator/ceph/cluster/utils.go
- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/controller/predicate.go
- pkg/operator/ceph/controller/predicate_test.go
- pkg/operator/ceph/pool/controller_test.go
We can now prioritize orchestrations on certain event. Today only two
events will cancel on-going orchestrations (if any):
* request for cluster deletion
* request for cluster upgrade
If one of the two are caught by the watcher we will cancel the on-going
orchestration.
For that we implemented a simple approach based on check points, where
we will check for a cancellation request in certain part of the
orchestration. Mainly before each mons/mgr/osds orchestration loops.
This solution is not perfect, but we are waiting for the
controller-runtime to release its 0.7 version which will embed context
support. With that we will be able to cancel reconciles more precisely
and rapidly.
Operator log example:
```
2020-11-25 12:59:12.986264 I | …
```
> ceph: ability to abort orchestration

- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
The code was assuming that devices were passed by the user as
"/dev/sda", this is bad! We all know people should be using paths like
/dev/disk/by-id so we must support them.
Closes: https://github.com/rook/rook/issues/6685
Resolves https://github.com/rook/rook/issues/6685
**Checklist:**
> ceph: fix metadata device passed by-id

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
This fixes the pod labels variable usage in the Ceph CSI templates.
Added backport to 1.5 label.
Resolves #
**Checklist:**
> ceph: fix pod labels set on csi components

- cluster/charts/rook-ceph/templates/role.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- tests/framework/installer/ceph_manifests.go
The rook-ceph-system service account was lacking delete permission and
the operator was complaining.
Closes: https://github.com/rook/rook/issues/6708
Resolves https://github.com/rook/rook/issues/6708
**Checklist:**
> ceph: fix RBAC for cron cash pruner

- pkg/operator/ceph/cluster/cleanup.go
Before cleaning up the cluster, we wait for all the daemon pods to be cleaned up. This fails when
a daemon is in pending state and has no `spec.NodeName`. This PR ignores all daemon pods that are not scheduled on any node.
If `status.Phase` of a  ceph daemon pod is not `Running`, then ignore this pod when identifying the Nodes that are running ceph daemons.
Tests:
https://asciinema.org/a/uWYRubmE7Az31leuBfOKuqP3R
Resolves #
**Checklist:**
> ceph: cleanup should ignore ceph daemon pods that are not scheduled on any node.

- pkg/apis/rook.io/v1/labels.go
This makes it so the label merging function returns a new Labels object
with the merged content instead of modifying the existing one, which
would cause previously merged labels to be returned for a different set
of input labels.
Resolves #
**Checklist:**
> core: fix label merge

- pkg/operator/ceph/object/spec.go
If the selector changes on the rgw service, during upgrade the clients will briefly not be able to connect to the rgw pods. After all the pods are updated with any new labels, the connections would be restored, but we want to avoid that temporary outage.
Resolves #6718 
**Checklist:**
> ceph: RGW service selector should not change during upgrade

- tests/framework/installer/environment.go
testCephHelmSuite is failing in pre-k8s v1.16
due to invalid schema. v1beta1 doesn't support
the null value so returning quotes instead of an empty
string.
Resolves #6755 
**Checklist:**
> ci: helm integration test is failing on pre-k8s-1.16

- Documentation/ceph-cluster-crd.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster-external.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/cluster_external.go
- pkg/operator/ceph/cluster/cluster_external_test.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/spec.go
- tests/framework/installer/ceph_manifests.go
When the cluster is external we want to expose manager service port
along with the endpoints.
This allows us to connect but Rook will keep on using 9283 as a facing
port for Prometheus and more.
Resolves #
**Checklist:**
> ceph: ability to set external services ports

- pkg/daemon/ceph/client/crush.go
When a new node got added rook checks if there is already an OSD running on that host via `ceph osd crush ls`
As this is a new node `ceph` returns with the error `ENOENT`. Rook handles this wrongly as a fatal error and aborts the addition of nodes.
The fix checks in case of an error if `ENOENT` is the reason and simply proceeds.
> ceph: fix #6214 New node is not provisioned when useAllNodes: true

- pkg/apis/rook.io/v1/placement.go
- pkg/apis/rook.io/v1/placement_test.go
- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/k8sutil/node.go
Stretch clusters require certain node affinity for the mons and must also be merged with the required node affinity in the placement of the cluster CR. All conditions, both requested and generated must be met, rather than one overriding the other.
**Checklist:**
> ceph: Merge placement node affinity for stretch clusters

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
This commit updates the OSD capacity thresholds to match the cluster capacity alert thresholds.
Also updated device_class info to provide info about which type of storage needs to be added.
Resolves #
**Checklist:**
[skip ci]
> ceph: Updated thresholds of OSD capacity alerts and added the device_class info

- pkg/operator/ceph/csi/secrets.go
- pkg/operator/ceph/csi/secrets_test.go
If the kernel doesn't support mapping of the rbd image with the deep-flatten feature,cephcsi needs to flatten the rbd image first and then map the image on the node.
cephcsi first tries to add a task to flatten the rbd image if it receives any permission error it will try to call the rbd CLI command which is a blocking call. This commit adds mgr caps to the csi-rbd-node user so that cephcsi will add flatten task and return
immediate error to the kubelet, let kubelet retry again, If we go with blocking rbd CLI call we may end up having stale maps on the node in corner cases.
Resolves #
**Checklist:**
> ceph: add mgr caps for csi-rbd-node client

- .github/workflows/canary-integration-test.yml
this commit add yaml validation check
by adding `--dry-run` and add path
'.github/workflows/**' to Canary integration
tests.
Resolves #
**Checklist:**
> ci: add yaml validation check

- tests/scripts/validate_cluster.sh
canary test failing because the validate script
not updating the argument command passed.
Resolves #
**Checklist:**
> ci: minor update to validate cluster script

- pkg/operator/ceph/cluster/osd/spec.go
The OSD configuration on local devices was being skipped if a storageClassDeviceSet was specified. Both types of OSDs should be allowed in the same cluster, which allows a cluster in the cloud to also take advantage of local devices with different perf properties.
**Checklist:**
> ceph: Allow OSDs on both PVCs and devices

- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
The deviceClass property was being ignored when creating the non-pvc OSDs. Now the deviceClass will be specified as a property for individual devices, all devices on a node, or all OSDs in the cluster, depending on the level where the config is applied in the cluster CR.
Resolves #6814 
**Checklist:**
> ceph: Apply deviceClass properly to new osds

- Jenkinsfile
- tests/framework/installer/cassandra_installer.go
- tests/framework/installer/cockroachdb_installer.go
- tests/framework/installer/nfs_installer.go
- tests/framework/installer/provisioners.go
- tests/framework/installer/yugabytedb_installer.go
The integration tests need to run on all the supported version of K8s. With the release of 1.20.0, we now enable the tests there. To keep the tests running in master on 5 versions, we drop 1.17 and keep 1.15 so we can keep testing against v1beta1 extensions in master.
**Checklist:**
> ci: Enable K8s 1.20.0 to run the integration tests

- tests/framework/utils/k8s_helper.go
- tests/framework/utils/snapshot.go
The snapshot controller is specifying to use the canary image instead of the expected version. Update the tests to set the correct version.
Resolves #6837 
**Checklist:**
[test full]
> ceph: use the correct snapshot controller version in the tests

- pkg/daemon/ceph/client/crush.go
This reverts commit a6ee5657aeeee505964fe263b21b974426921891.
The operator reconcile of the cephcluster was staying in an endless loop in clusters that did not have OSDs configured on all nodes. Now we revert this change for the patch release and will follow up with a more complete fix in #6813.
Resolves #6796
**Checklist:**
> ceph: Revert new node is not provisioned when useAllNodes is true

- pkg/daemon/ceph/client/crush_rule.go
- pkg/daemon/ceph/client/pool_test.go
Pass 'device-class' when adding two-steps crush-rule from template
Resolves #
**Checklist:**
> ceph: Two step crush rule with device class

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- pkg/operator/ceph/test/containers.go
- pkg/operator/k8sutil/pod.go
Currently, mgr deployment has two overlapping environment variables, ROOK_POD_IP.
Like below
```
...
- name: ROOK_POD_IP
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: status.podIP
- name: ROOK_OPERATOR_NAMESPACE
value: flex-ns-system
- name: ROOK_CEPH_CLUSTER_CRD_VERSION
value: v1
- name: ROOK_CEPH_CLUSTER_CRD_NAME
value: test-cluster
- name: ROOK_POD_IP
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: status.podIP
...
```
This causes kube-apiserver to create error logs like below
```
E1209 06:06:50.382252       1 fieldmanager.go:159] [SHOULD NOT HAPPEN] failed to update managedFields for /, Kind=: failed to convert new object (apps/v1, Kind=Deployment) to smd typed: errors:
.spec.template.spec.initContainers[name="init-set-dashboard-server-addr"].env: …
```
> ceph: remove overlapping env values

- .github/workflows/canary-integration-test.yml
- Documentation/ceph-cluster-crd.md
- Documentation/ceph-upgrade.md
- Jenkinsfile
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-with-drive-groups.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/ceph/ceph-cluster-cleanup.md
- images/ceph/Makefile
- pkg/apis/ceph.rook.io/v1/types.go
- tests/framework/installer/ceph_installer.go
- tests/integration/ceph_base_object_test.go
- tests/integration/ceph_flex_test.go
- tests/integration/ceph_helm_test.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_smoke_test.go
- tests/integration/ceph_upgrade_test.go
The latest octopus release is now out with v15.2.8. We update the operator base image and the examples to run with this version.
The latest ceph-volume does not support creating OSDs on partitions (see #6849). The github actions only have a partition available, so we will run the github tests on v14.2.12 and v15.2.7 that still support partitions, while the Jenkins environment has a raw device available where we can run the latest versions of Ceph in the tests.
**Checklist:**
> ceph: Update examples and operator to Ceph v15.2.8 and fix integration tests on partitions

- .github/workflows/canary-integration-test.yml
- Documentation/ceph-cluster-crd.md
- Documentation/ceph-upgrade.md
- Jenkinsfile
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-with-drive-groups.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/ceph/ceph-cluster-cleanup.md
- images/ceph/Makefile
- pkg/apis/ceph.rook.io/v1/types.go
- tests/framework/installer/ceph_installer.go
- tests/integration/ceph_base_object_test.go
- tests/integration/ceph_flex_test.go
- tests/integration/ceph_helm_test.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_smoke_test.go
- tests/integration/ceph_upgrade_test.go
Backport the fix for integration tests and ceph v15.2.8 to release-1.5 since mergify missed it...
**Checklist:**
> ceph: Update examples and operator to Ceph v15.2.8 and fix integration tests on partitions (bp #6847)

- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
14.2.15 lvm batch command prepare report changes
output format. This commit skips md check if ceph version
is greater than 14.2.13.
In 14.2.15, `lvm batch --prepare --report` breaks report format which causes
creating osd failed.
Resolves #
**Checklist:**
[test full]
> ceph: Allow using lvm batch for ceph 14.2.15

- Documentation/ceph-nfs-crd.md
- pkg/operator/ceph/nfs/config.go
- pkg/operator/ceph/nfs/controller_test.go
PR[1] in volume nfs plugin will remove it too. Since it can cause
inconsistencies.
This change will not affect exports created using dashboard. As it looks for
ganesha config object just by 'conf-' [2].  Exports cannot be created by using
volume/nfs plugin in Octopus version. Because the ceph rook module is broken.
[1] ceph/ceph#38510
[2] https://github.com/ceph/ceph/blob/octopus/src/pybind/mgr/dashboard/services/ganesha.py#L1111
Resolves #
**Checklist:**
> ceph: remove 'ganesha-' from nfs-ganesha config object name

- pkg/operator/ceph/cluster/operator_watchers.go
- pkg/operator/ceph/operator.go
The operator namespace is not used in the StartOperatorSettingsWatch() method. Instead, the method looks up the namespace from the POD_NAMESPACE env var.
**Checklist:**
> ceph: Remove unused operator namespace parameter

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test.yaml
Upgrade `manusa/actions-setup-minikube` to use the latest version.
GitHub is rolling out Ubuntu 20.04 as the default environment. GitHub actions workflows using `ubuntu-latest` will [soon ](https://github.com/actions/virtual-environments/issues/1816) start an Ubuntu 20,04 instance instead of 18.04.
Prior versions of `manusa/actions-setup-minikube` have a check which won't allow the workflow job to run. Starting on `2.2.0`, Ubuntu 20.04 is supported too (https://github.com/manusa/actions-setup-minikube/issues/26).
Resolves n/a
**Checklist:**
> ci: Upgrade actions-setup-minikube to v2.2.0

- Documentation/ceph-csi-snapshot.md
updated few resource names in CSI snapshot documentation.
Resolves https://github.com/rook/rook/pull/6292
**Checklist:**
[skip ci]
> ceph: fix typo in resource name in the snapshot instructions

- pkg/operator/ceph/disruption/clusterdisruption/add.go
- pkg/operator/ceph/disruption/clusterdisruption/osd.go
Currently the reconcile of the clusterDisruption controller was triggered mainly due to the
ceph status update in the cephCluster CR. This PR reconciles the cluster more proactively.
Current reconcile strategies:
1. Reconcile when the cluster is created. (This will trigger the first reconcile)
2. Reconcile only when the clusterSpec is updated. (This will avoid reconciles when cluster status is updated) 
3. Reconcile for events on cephblockpool, cephfilesystem and cephObjectStore.  
4. Reconcile for events on Main PDB and when `DisruptionsAllowed` is 0. (that is, when one of the OSD goes down).
5. Reconcile after 30 seconds when there is an active drain going on, that is, pdbStateMap has …
> ceph: requeue clusterDisruption controller more proactively

- tests/scripts/validate_cluster.sh
this commit removes the leftover line
from PR #6800.
Resolves #
**Checklist:**
> ceph: remove leftover line

- Documentation/ceph-filesystem.md
The [CephFS documentation page'](https://rook.io/docs/rook/master/ceph-filesystem.html)s kube-registry.yaml PVC definition was missing the namespace property.
The YAML shown in the docs now reflects the file in cluster/examples/kubernetes/ceph/csi/cephfs/kube-registry.yaml
Signed-off-by: Léo Schoukroun <leopaul36@yahoo.fr>
Resolves #
**Checklist:**
> docs: added kube-system namespace to the registry sample's pvc in cephfs

- Documentation/ceph-object.md
This fixes an issue when running the AWS credential export commands to be more explicit. The yaml files also contain a second config key prefixed with an `f:` e.g.: the ceph-bucket secret contains a `BUCKET_HOST` key and a `f:BUCKET_HOST` key. This confuses awk and breaks the whole export since a `{}` is suffixed to the end of all values. The latter two commands even fail since the base64 command apparently doesn't like the trailing `{}`.
Resolves #6087
**Checklist:**
Signed-off-by: Daniel Schneider <daniel.schneider@eramux.com>
> docs: fix RGW AWS credential export commands

- tests/scripts/webhook-config.yaml
Currently, ValidatingWebhookConfiguration has two same named webhooks like `rook-ceph-admission-controller.flex-ns-system.svc`
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
creationTimestamp: "2020-12-14T05:12:35Z"
generation: 1
name: rook-ceph-webhook
resourceVersion: "597"
selfLink: /apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/rook-ceph-webhook
uid: 475d6f29-de26-4364-9c3d-3a2388bde54d
webhooks:
- admissionReviewVersions:
- v1beta1
clientConfig:
caBundle: 
...
service:
name: rook-ceph-admission-controller
namespace: flex-ns-system
path: /validate-ceph-rook-io-v1-cephcluster
port: 443
failurePolicy: Ignore
matchPolicy: Exact
name: rook-ceph-admission-controller.flex-ns-system.svc …
```
> ceph: rename webhooks

- Documentation/ceph-object.md
add namespace note in object storage StorageClass documentation
Add little note about namespace in provisioner when creating StorageClass required for creating ObjectBucketClaim
N/A
**Checklist:**
[skip ci]
> ceph: add namespace note in storageclass documentation

- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/objectstore_test.go
- pkg/operator/ceph/object/rgw.go
The object store is nearly always timing out in the smoke suite of the Jenkins integration tests when the object store is being deleted. The object store controller is not responding to the delete request because it is still busy with the object store creation reconcile loop for several minutes. 
In local tests and in the github actions, the same test succeeds with no issues.
For now, logging is simply added to help track down the issue in Jenkins.
**Checklist:**
> ceph: Setting rgw dashboard api key is frequently hanging in the integration tests since v15.2.8

- pkg/apis/ceph.rook.io/v1/object.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
Following #6217, allow rgw to created for external cluster
Signed-off-by: Julien Girardin <jugirardin@free.fr>
Took me some time to test #6226, but this was not still working, operator claiming: 
```
ceph-object-controller: failed to reconcile failed to create object store deployments: failed to reconcile external endpoint: failed to create or update object store "arch-cloud" endpoint: failed to create endpoint "rook-ceph-rgw-arch-cloud". Endpoints "rook-ceph-rgw-arch-cloud" is invalid: subsets[0]: Required value: must specify `addresses` or `notReadyAddresses`
```
Change external rgw detection, not relying on cluster. Now there is multiple posibilities:
- internal cluster and internal rgw pods: "normal case"
- external cluster and internal rgw pods: <= now working with the PR
- external …
> ceph: change external rgw detection, not relying on cluster

- tests/README.md
1800s is too short to complete all suites. Let's make it the same value as CI.
**Checklist:** …
> docs: extend timeout in readme

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
`.spec.resources.osd ` resources and `placement: all:` placements
parameters for the OSD pod did not reflect the value like
it has for other pods mon, mgr.
this commit will allow setting above parameters for the OSD pod also.
Resolves #6789
**Checklist:**
> ceph: apply OSD resources and placement for device sets

- pkg/daemon/ceph/client/mgr.go
- pkg/daemon/ceph/client/mgr_test.go
- pkg/operator/ceph/version/version.go
When the version is detected it will print the name of the release
Pacific correctly where previously it was showing <unknown version>".
As of Pacific the balancer is now on by default in upmap mode.
In earlier versions, the balancer was included in the `always_on_modules` list, but needed to be
turned on explicitly using the ``ceph balancer on command.
Resolves #
**Checklist:**
> ceph: add pacific release name support and do no turn on the balancer since it is only on

- tests/framework/clients/bucket.go
- tests/framework/utils/k8s_helper.go
- tests/framework/utils/retry.go
- tests/integration/ceph_base_object_test.go
- tests/integration/ceph_upgrade_test.go
When verifying OBC creation, validating that secret and configmap exist
is good, but the definitive validation is to check that the OBC's phase
is "Bound".
Add object bucket claim to Ceph upgrade test.
Resolves #
**Checklist:**
> ceph: update smoke & upgrade tests to verify obc is bound

- pkg/apis/ceph.rook.io/v1/keys.go
- pkg/apis/ceph.rook.io/v1/livenessprobe.go
- pkg/operator/ceph/config/livenessprobe.go
- pkg/operator/ceph/config/livenessprobe_test.go
- pkg/operator/ceph/file/mds/spec.go
Allow to disable liveness probes for mds pod
Allow to disable liveness probes for mds pod
**Checklist:**
> ceph: allow disable liveness check for mds daemonset

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- tests/framework/installer/ceph_manifests.go
With the 1.5 schema added to the CRDs, the devices at the root level of the storage element were missed. Now the ability to specify devices at the root storage level to apply to all nodes is restored.
**Checklist:**
> ceph: Add devices to schema at overall storage level

- .github/workflows/canary-integration-test.yml
- tests/scripts/validate_cluster.sh
this commit adds an option to download artifacts in
canary integration test for better debug.
Resolves #
**Checklist:**
> ci: add option to download artifacts in canary test

- cluster/examples/kubernetes/ceph/common-external.yaml
Fix accidental malformations in common-external.yaml manifest.
Find-replace operations seemingly replaced `namespace` with `name` in
some instances. Fix this.
This seems to have happened in https://github.com/rook/rook/pull/6809
Backport this to v1.5 since 6809's changes also were backported to v1.5.
**Checklist:**
> ceph: fix malformations in common-external.yaml

- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/dashboard_test.go
If ssl was not enabled, the dashboard was being restarted with every reconcile. Instead, the dashboard should only be restarted when the settings have changed in order to reduce the frequency that the dashboard is restarted.
Resolves #6527 
**Checklist:**
> ceph: Only restart ceph dashboard module if settings changed

- cluster/charts/rook-ceph/templates/resources.yaml
With the v1 schema added to the CRDs, the devices at the root level of the storage element were missed. Now the ability to specify devices at the root storage level to apply to all nodes is restored. This is a minimal backport of #6938.
**Checklist:**
> ceph: Add devices to schema at overall storage level (bp #6938)

- cluster/examples/kubernetes/ceph/pre-k8s-1.16/crds.yaml
- tests/framework/installer/ceph_manifests.go
Clean up an unexpected array type in the schema for pre-k8s-1.16 clusters. The tests were failing in pre-1.16 for the past couple days due to a related regression in #6938.
The error in the CI was:
```
[2021-01-13T17:27:13.774Z] Could Not create resource in args : [apply -f -] -- 
Failed to run stdin: kubectl [apply -f -] : error: error parsing STDIN: error converting YAML to JSON: yaml: line 130: did not find expected key
```
**Checklist:**
> ceph: Remove unexpected array type in v1beta1 crd schema

- tests/framework/installer/ceph_installer.go
The integration tests check after every test suite that the cluster is either ready or connected. Sometimes the operator is in progressing state because the reconcile may be triggered by some event that is unpredictable at the end of the test. For test stability we allow the progressing status.
**Checklist:**
> ceph: Allow progressing status during integration test cleanup

- Documentation/ceph-osd-mgmt.md
- cluster/examples/kubernetes/ceph/osd-purge.yaml
Describe `rook-ceph-purge-osd` job in the document of OSD management to ease day2 operations.
**Checklist:** …
> docs: describe osd purge job in the document of OSD management

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-mon-health.md
- Documentation/ceph-storage.md
The mon design and handling of failover is a topic that frequently needs to be understood by rook users, thus moving this design doc to the documentation and making some updates based on the latest behavior.
**Checklist:**
> ceph: Add mon design to the official docs

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
expose upgrade progress to the CephCluster status
Resolves #
**Checklist:**
> ceph: exposing which node/osd is processing

- build/makelib/helm.mk
- build/release/Makefile
fix build after migration to new s3 buckets
Resolves #
**Checklist:**
[skip ci]
> switch to new aws buckets

- pkg/operator/ceph/operator.go
- pkg/operator/discover/discover.go
discovery-daemon still exists even if it's disabled.
Resolves #6936
**Checklist:** …
> ceph: delete discovery daemon if it is disabled

- Documentation/nfs.md
The nfs quickstart docs have references to nfs-provisioner which no longer exist and the storage class example uses the wrong provisioner value. The changes remove the lines the nfs-provisioner references that seem to no longer exist and updates the storage class to use the provisioner specified in the example [here](https://github.com/rook/rook/blob/4e151a7e78ce8246851df6b3add64594fbf964ef/cluster/examples/kubernetes/nfs/sc.yaml#L11)
**Checklist:**
[skip ci]
> docs: updating nfs quickstart docs

- build/makelib/golang.mk
- The build currently requires golang 1.15 and will fail if an older version is used.
- Print the golang version during the build if invalid
Resolves #
**Checklist:**
[skip ci]
> build: Enforce golang 1.15 in the build

- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/volumes.go
- pkg/operator/ceph/cluster/osd/volumes_test.go
Multiple OSD pods for the same OSD might run simultaneously becasue OSD pod is managed by Deployment resource. However, OSD locking mechanism doens't work because the lock file (fsid file) exist for each OSD pod. It resutls in OSD corruption.
Resolves #6530
**Checklist:**
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a …
> ceph: avoid potential osd corruption due to wrong file-lock

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/object/spec.go
By setting the working directory of a Ceph daemon to the log direcor
(which is bindmounted to the host), we can ensure that the coredumps
will be available.
On CentOS 7 **only**, the kernel is configured with:
```
cat /proc/sys/kernel/core_pattern
core
```
which means that the coredumps will end up in the process working
directory and will be named "core".
On CentOS 8, everything is different and this won't work but still
CentOS will be able to consume this and changing the working directory
is harmless.
Resolves #
**Checklist:**
> ceph: set process working dir to /var/log/ceph

- .github/workflows/canary-integration-test.yml
After each non-pvc and pvc scenario we run the
kubectl-check-ownerreferences tool to analyze potential incorrect owner
references. We had issues in the past with incorrect owner ref so this
tool might help us ensure we are doing things right.
Resolves #
**Checklist:**
> ceph: add kubectl-check-ownerreferences in ci

- pkg/operator/ceph/version/version.go
- pkg/operator/ceph/version/version_test.go
Quincy just started https://github.com/ceph/ceph/pull/38996 so let's add
it to our version code.
Resolves #
**Checklist:**
> ceph: add quincy version

- design/ceph/admission-controller.md
- tests/framework/installer/ceph_installer.go
- tests/scripts/webhook-config.yaml
- tests/scripts/webhook-create-signed-cert.sh
this commits update admission controller to v1 from
v1beta1. v1beta1 is deprecated in v1.16+ and unavailable
in v1.22+.
Resolves #6937 
**Checklist:**
> ceph: update admission controller to v1 from v1beta1

- pkg/operator/ceph/cluster/cluster.go
The rbd-mirror was left being when the CephCluster was upgraded.
Resolves #
**Checklist:**
> ceph: update rbd-mirror when cluster is upgraded

- Documentation/helm-operator.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/charts/rook-ceph/values.yaml
This will give us the ability to configure the environment variable ROOK_ALLOW_MULTIPLE_FILESYSTEM, as that configuration cannot currently be set using the existing rook-operator helm chart.
Resolves #7007
**Checklist:**
> #7007 Ability to configure ROOK_ALLOW_MULTIPLE_FILESYSTEMS environment to rook operator pod in helm chart

- .github/workflows/canary-integration-test.yml
- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- pkg/daemon/ceph/osd/kms/volumes.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/object/spec.go
- tests/manifests/test-kms-vault-spec.yaml
- tests/scripts/deploy-validate-vault.sh
The first patch to configure vault for ceph object store. If the `security.kms` configured in
`clusterSpec` CRD, RGW will be configured with vault kms settings to handle SSE request from s3 clients.
TODO : 
- configuring tls authentication between vault and rgw, dependency on [patch](https://github.com/ceph/ceph/pull/37730)
Resolves #
**Checklist:**
> ceph: vault kms configuration for ceph object store

- cluster/examples/kubernetes/ceph/config-admission-controller.sh
- tests/framework/installer/ceph_installer.go
v1 version of `admissionregistration.k8s.io/v1` require minimum v1.16.0
of k8s. So, this commits disable admission controller when
k8s version older than v1.16.0.
Resolves #7047
**Checklist:**
> ceph: disable admission controller for k8s older than v1.16.0

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/rbd/controller.go
- pkg/operator/ceph/controller/predicate.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/object/controller.go
If the CephCluster CR spec is updated to activate the logCollector, we
must reflect that change onto child CRDs, like the mds and rgw since
their configurationn would be impacted too.
Now we watch for the CephCluster object changes from the object/file
controllers and react upon the appropriate event.
Closes: https://github.com/rook/rook/issues/7022
Resolves #
**Checklist:**
> ceph: update rgw and mds deployment for logCollector

- pkg/operator/ceph/config/conditions.go
Fix ProgressingCompleted CephCluster status condition to have type cephv1.ConditionProgressing
Resolves #7055 
**Checklist:**
> ceph: fix ProgressingCompleted CephCluster status condition type

- Documentation/ceph-osd-mgmt.md
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cmd/rook/ceph/osd.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/deviceset_test.go
OSDs on PVCs previously were always replaced with PVCs of a given name. For on-prem scenarios where the OSDs might need to be removed instead of replaced, the operator now allows holes to exist in the PVC index names as long as there are a sufficient number of PVCs to meet the criteria for the deviceSet.count.
At the same time, we use predictable PVC names for the ODSs such as rook-ceph-osd-set1-data-3 as there is no need for a generated pvc suffix name
Resolves #6287 #6948 
**Checklist:**
> ceph: Allow removal of arbitrary osds on pvcs and simplify pvc names

- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
The settings for tuneDeviceClass and tuneFastDeviceClass were stored as a map[string]string. When iterating over the map to append the args, the args were being appended in an unpredictable order. The order could change every reconcile, resulting in an unnecessary OSD restart potentially every reconcile. Now we iterate over a slice that will be ordered predictably and ensure OSDs will not be restarted when not needed.
Instead of translating the settings, also just specify settings that don't need to be translated.
**Checklist:**
> ceph: Consistently order the osd args to avoid restarts

- pkg/operator/ceph/cluster/mon/mon.go
When the node is not found for mon assignment with host networking enabled, the operator may crash. This change ensures the node is not nil and returns an error instead of crashing.
The error was found based on the 1.4 release, as seen on [line 563 of mon.go](https://github.com/rook/rook/blob/release-1.4/pkg/operator/ceph/cluster/mon/mon.go#L563) where `node` must be nil:
```
2021-01-15T06:29:08.081677455Z 2021-01-15 06:29:08.081608 I | op-mon: targeting the mon count 3
2021-01-15T06:29:09.654766574Z 2021-01-15 06:29:09.654706 I | op-mon: checking for basic quorum with existing mons
2021-01-15T06:29:09.654766574Z 2021-01-15 06:29:09.654743 I | op-mon: setting mon endpoints for hostnetwork mode
2021-01-15T06:29:09.654943096Z E0115 06:29:09.654900       7 …
```
> ceph: Prevent operator crash with host networking and node not found

- pkg/operator/ceph/cluster/mon/mon.go
Small fix since all the ceph codebase is using the errors package.
Resolves #
**Checklist:**
> ceph: use errors package instead of fmt

- pkg/operator/ceph/file/mds/spec.go
Previous patchset does not work, because
`ConfigureLivenessProbe` does not directly modifies
input variable.
Signed-off-by:  jshen28<yshxxsjt715@gmail.com>
Resolves #
**Checklist:**
> ceph: fix mds liveness probe

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/examples/kubernetes/ceph/pre-k8s-1.16/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/daemon/ceph/client/info.go
- pkg/daemon/ceph/client/upgrade.go
- pkg/daemon/ceph/client/upgrade_test.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/k8sutil/deployment.go
added WaitTimeoutForHealthyOSDUpgrade in the cluster crd that defines the time (in minutes) the operator would wait before an OSD can be stopped for
upgrade. It also defines the time the rook will wait for PGs to become active+clean after an OSD daemon is upgraded. The default value is 5 minutes.
Resolves #5790
Tested on multi-node local minikube cluster by upgrading from ceph 15.2.7 to 15.2.8
```Every 2.0s: kubectl -n rook-ceph get deployments -l rook_cluster=ro...  localhost.localdomain: Wed Jan 27 11:41:26 2021
rook-ceph-crashcollector-minikube-m02   req/upd/avl: 1/1/1      ceph-version=15.2.7-0
rook-ceph-crashcollector-minikube-m03   req/upd/avl: 1/1/1 …
```
> ceph: configure health check timeout for OSDs when upgrading

- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-stretched.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- cluster/examples/kubernetes/ceph/cluster-with-drive-groups.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- tests/framework/installer/ceph_manifests.go
The PDBs have been stabilizing for a good length of time now since they were created in v1.1, and later redesigned in v1.5. The time has come to enable the feature by default so everyone can enjoy the stable Rook storage even while draining K8s nodes. This change will be in the v1.6 release, rather than backport to 1.5.
@sp98 Any reason not to enable the PDBs by default now? 
**Checklist:**
> ceph: Enable pod disruption budgets by default

- pkg/operator/ceph/cluster/mon/config.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
The maxMonId should only track the mons that have been committed to starting. Currently the maxMonId was tracking all mon scheduling. If the reconcile was aborted or failed, or the operator restarted in a reconcile, the maxMonId was being reset by analyzing the mon deployments that existed. This does not work for scenarios where mon quroum is lost and being reset to a single mon. Now the maxMonId will only be incremented when a mon daemon is started, and will never be decremented after that to ensure that new mons will be incremented to the next id.
**Checklist:**
> ceph: Only commit the maxmonid after starting a mon daemon

- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/file/mds/spec_test.go
add `--public-addr=podIP` args to ceph mds command when host network is not enabled.
Resolves #5938
**Checklist:**
> ceph: add --public-addr args to ceph mds command

- pkg/operator/ceph/cluster/cephstatus.go
- pkg/operator/ceph/cluster/cephstatus_test.go
- pkg/operator/k8sutil/node.go
- pkg/operator/k8sutil/node_test.go
Clean up all the Rook and CSI pods that are stuck in terminating
state on a failed node.
Added code to check if there are `NotReady` nodes when Ceph status is not `HEALTH_OK` and force delete the pods that are stuck in `Terminating` on the `NotReady` node.
Resolves #
**Checklist:**
> ceph: clean pods stuck in terminating state on a failed node

- .github/workflows/canary-integration-test.yml
this commit update canary-integration-test
to remove `object-openshift.yaml` file from
`dry-run`.
Resolves #
**Checklist:**
> ci: update canary-integration-test

- pkg/operator/ceph/disruption/clusterdisruption/mon.go
If there is a single mon, we don't expect the PDBs to be created and neither do we need to log that it is an error condition.
Also the operator fails the CephCluster CR if there is an even number of mons, so we no longer need that check in the pdb reconciler.
**Checklist:**
> ceph: Skip logging error for mon pdbs if single mon

- pkg/daemon/ceph/client/command.go
- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/controller_test.go
- pkg/operator/ceph/object/objectstore_test.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/user/controller_test.go
- pkg/operator/ceph/object/zone/controller_test.go
- pkg/operator/ceph/object/zonegroup/controller_test.go
When creating object store, `radosgw-admin realm get ..` command is stuck forever when required number of OSDs are not available. Because of this the uninstall of object store is also stuck. User has to manually remove the finalizer to delete the object store.
This PR uses `ExecuteCommandWithTimeout` for running `radosgw-admin` command. Timeout during installation will be reconciled. Cleanup will be treated as best effort and timeout during unisntall will be ignored.
Resolves #
**Checklist:**
> ceph: timeout `radosgw-admin` cli commands

- pkg/operator/ceph/cluster/osd/spec.go
If HostIPC is enabled, this means the Ceph version is older than Octopus
and we are still running OSD with HostIPC due to an internal
inter-process check.
If the log collector is enabled we need to enable ShareProcessNamespace
**only** if HostIPC is disabled.
Resolves #
**Checklist:**
> ceph: do not enable ShareProcessNamespace if HostIPC

- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
If HostPID is enabled, this means the Ceph version is older than Octopus
and we are still running OSD with HostPID due to an internal
inter-process check.
If the log collector is enabled we need to enable ShareProcessNamespace
**only** if HostIPC is disabled.
Both HostPID and ShareProcessNamespace cannot be enabled.
Resolves #
**Checklist:**
> ceph: do not enable ShareProcessNamespace if HostPID

- pkg/operator/k8sutil/prometheus_test.go
- pkg/util/file.go
- pkg/util/retry.go
- pkg/util/set.go
- pkg/util/set_test.go
Do not force unit tests to be run while the rook repo is in the GOPATH.
Now that Rook uses go modules, this is no longer necessary. Allow this
by creating a helper function that unit tests can use that return the
on-host path to the `rook` project root.
Resolves #
**Checklist:**
> ceph: do not force go path in unit tests

- build/makelib/common.mk
shasum is not always available and sha256sum seems to exist more often
since it's part of coreutils where sha256sum comes with perl.
Resolves #
**Checklist:**
> build: try sha256sum if shasum is not present

- Documentation/ceph-nfs-crd.md
- cluster/examples/kubernetes/ceph/nfs.yaml
Add following don'ts note for storing ganesha recovery object:
* Don't use fs pool, it can cause this dashboard issue https://tracker.ceph.com/issues/46176
* Don't use erasure coded pool, it will not work due to ganesha's omap requirements
[skip ci]
> ceph: update nfs ganesha pool recommendation

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- tests/framework/installer/ceph_manifests.go
The deviceClass was missing from the object store CRD schema, disallowing the device class from being specified on the object store pools.
**Checklist:**
> ceph: Add deviceClass to the object store schema

- pkg/operator/ceph/controller/spec.go
The log-collector container name was exceeding the 63-char limit if the parent CR name was too long. The container name just needs to be unique to the pod spec, so we simplify it to remove the parent name and avoid hitting the limit in the pod spec.
For example:
```
2021-02-02 19:07:49.641184 E | ceph-object-controller: failed to reconcile failed to create object store deployments: 
failed to create object store "ocs-storagecluster-cephobjectstore": failed to start rgw pods: failed to create rgw deployment: 
Deployment.apps "rook-ceph-rgw-ocs-storagecluster-cephobjectstore-a" is invalid: spec.template.spec.containers[1].name:   
Invalid value: "rgwceph-client-rook-ceph-rgw-ocs-storagecluster-cephobjectstore-a-log-collector": must be no more than 63 …
```
> ceph: Simplify the log-collector container name

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- tests/framework/installer/ceph_manifests.go
This PR adds a new cmd line argument for the csi-provisioner sidecar to pass the pvc and namespace name to the cephcsi driver. and cephcsi needs to access the configmaps created in different namespaces updated RBAC to provide same access.
Resolves #
**Checklist:**
> ceph: Add new cmd argument and RBAC for csi rbd provisioner

- pkg/daemon/ceph/client/upgrade.go
- pkg/operator/ceph/client/controller.go
- pkg/operator/ceph/cluster/cephstatus.go
- pkg/operator/ceph/cluster/rbd/controller.go
- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/disruption/clusterdisruption/osd.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/object/controller.go
- pkg/util/exec/error.go
- pkg/util/exec/error_test.go
- pkg/util/exec/exec.go
See individual commits, but overall one the operator restarts this silences harmless errors.
**Checklist:**
> ceph: silence harmless errors when the operator is not initialized

- pkg/operator/ceph/disruption/clusterdisruption/add.go
This PR makes create and delete events on pdb a no-op. Update event only triggers reconcile if its the main OSD pdb and allowed disruptions is 0.
This prevents controller to reconcile on pdb events namespaces outside rook ceph.
(cherry picked from commit b780e5b5c052bac61d8b6498c4e68c1d103d202e)
Resolves #
**Checklist:**
> ceph: skip pdb reconcile on create and delete events

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/status.go
completeOSDsForAllNodes() method waits for 20 minutes for all the OSDs to start on all the nodes. This PR checks if
cluster deletion request was sent while waiting for OSDs to start. If yes, then completeOSDsForAllNodes() method will returnwithout waiting for 20 minutes.
Resolves #
**Checklist:**
> ceph: check for orchestration cancellation while waiting for all OSDs  to start.

- pkg/operator/ceph/cluster/mgr/spec.go
Binding the dashboard and prometheus to all interfaces instead of the pod ip will ensure that they are listening properly. Binding to the pod ip was only a short term solution that was intended to be removed when deploying Nautilus, which is already Rook's min supported version.
This PR will ensure the new binding is applied for all upgrade clusters to the latest v1.5. #7152 is the follow-up PR for v1.6 to remove the init containers completely.
See the analysis [here](https://github.com/rook/rook/issues/2526#issuecomment-764976286) for more background.
Resolves #2526 
**Checklist:**
> ceph: Bind mgr modules to all interfaces instead of pod ip

- Documentation/ceph-dashboard.md
ceph dashboard doc url in the doc is of older version. This patch updates it
with the latest doc url.
#skip-ci
> ceph: update dashboard doc url to latest

- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
The pod IP address is no longer needed for port binding for the dashboard and prometheus endpoints in the mgr modules. The default binding to localhost will be sufficient. This will allow the endpoints to be more reliable in some environments where today the podIP is not working.
This is the follow-up PR to #7151 that should stay in master to be included in v1.6. Let's merge #7151 before this one...
See the analysis [here](https://github.com/rook/rook/issues/2526#issuecomment-764976286) for why this change is needed.
Resolves #2526  
**Checklist:**
> ceph: Remove obsolete init containers from mgr that were used to init the binding addresses

- Documentation/helm-operator.md
- cluster/charts/rook-ceph/templates/resources.yaml
This special annotation will prevent Helm from uninstalling resources (in this case the CRDs) on `helm unistall ...`
Resolves #6617
**Checklist:**
> ceph: add helm resource-policy keep annotation for CRDs in helm chart

- Documentation/ceph-nfs-crd.md
- pkg/operator/ceph/nfs/nfs.go
nfs server requires valid pool for storing nfs-ganesha recovery objects. Only
when filesystem exports are created, filesystem should be configured first.
> ceph: filesystem is not required for nfs server deployment

- pkg/operator/ceph/cluster/crash/reconcile.go
If Ceph pods were evicted onto other nodes, there is no reason for the
crash collector to remain on those nodes. So let's remove it.
Resolves #
**Checklist:**
TODO: this needs more testing
> ceph: remove crash collector if ceph pod moved

- pkg/operator/ceph/cluster/osd/spec.go
When the blkdevmapper init container initializes we must override any
existing special block. This will prevent re-using a different disk on
the OSD on PVC scenario.
Adding "--remove-destination" to the cp line will remove each existing
destination file before attempting to open it.
We **MUST** do this otherwise in an environment where PVCs are dynamic, restarting the deployment will cause conflicts
When restarting the OSD, the PVC block might end up with a different Kernel disk allocation
For instance, prior to restart, the block was mapped to 8:32 and when re-attached it was on 8:16
The previous "block" is still 8:32 so if we don't override it we will try to initialize on a disk that is not an OSD or worse another OSD
This is mainly because in …
> ceph: always override existing block for blkdevmapper

- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/osd/envs.go
With 5f57b6fd3abbab60b2992171e042598b3fdbf333, we introduced a
regression in the validation code.
If the OSD PV comes from another cluster, GetCephVolumeRawOSDs must
return an error.
The prepare job will crash loop but at least with a useful and
comprehensive message.
Resolves #
**Checklist:**
> ceph: return an error if PVC is not clean

- pkg/operator/ceph/cluster/rbd/mirror.go
- pkg/operator/ceph/cluster/rbd/mirror_test.go
- pkg/operator/ceph/cluster/rbd/spec.go
We now rely on the "replica" setting in the Deployment spec when the
desired instance count is higher than 1 instead of creating another
deployment.
So now, we don't need to the number of deployments anymore and let
kubernetes handles the number of pods.
Resolves #
**Checklist:**
> ceph: use deployment replicas instead of more deployments for rbd-mirror

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/pre-k8s-1.16/crds.yaml
- tests/framework/installer/ceph_manifests.go
Add the cephfilesystemmirrors definition for CI runs where the
Kubernetes version is 1.15 and extension v1 extensions are not
supported.
Closes: https://github.com/rook/rook/issues/7168
Resolves https://github.com/rook/rook/issues/7168
**Checklist:**
> ceph: add cephfilesystemmirrors CRD to 1.15

- pkg/operator/ceph/cluster/osd/spec.go
If the Vault server returns an error, we must report it in the init
container. With this we can properly debug a failing init container.
Resulting container log:
```
oc logs rook-ceph-osd-0-dc6d4d4d-445dg -c encryption-kms-get-kek                                                                                                                                                                                                        
['error performing token check: Vault is sealed']%
```
Resolves #
**Checklist:**
> ceph: expose vault curl errors

- pkg/operator/ceph/cluster/version.go
The ceph version during an upgrade was incorrectly being formatted in the log message:
```
2021-02-10 22:51:48.499487 I | ceph-cluster-controller: upgrading ceph cluster to %q15.2.8-0 octopus
```
**Checklist:**
> ceph: Correct formatting of ceph version detected

- pkg/clusterd/disk.go
- pkg/daemon/ceph/osd/daemon.go
When printing pointers of struct (regardless if it is also a slice or
not) we must implement a stringer interface so they can be displayed
properly, this is especially useful when looking at the prepare job
logs.
Before this patch:
```
2021-02-10 06:39:06.783508 D | inventory: discovered disks are [0xc00029c240 0xc00024a000 0xc00086c480 0xc00024a480]
```
After this patch:
```
2021-02-11 13:05:15.730500 D | inventory: discovered disks are:
2021-02-11 13:05:15.730636 D | inventory: &{Name:dm-0 Parent: HasChildren:false DevLinks:/dev/disk/by-id/dm-uuid-LVM-aIFRq5P3hwE2YhukbOmsEZoLY61HxvX62A1xxb6ajTymVE0N8S4Ga0KWlHSgpvNw /dev/disk/by-id/dm-name-ceph--e29bf82e--86f1--4c8e--8412--c468def5a844-osd--block--2044a1ea--6e5e--4423--88cf--8947bf6957d1 Size:32208060416 …
```
> ceph: do not print pointer memory address

- Documentation/ceph-common-issues.md
- Documentation/ceph-csi-troubleshooting.md
this commit add docs for CSI Troubleshooting when
hit with the issue in Provisioning the CephFS/RBD PVC
or Mounting the CephFS/RBD PVC to application pods.
co-authored-by: Madhu-1 <madhupr007@gmail.com>
Resolves #5752
**Checklist:**
> docs: help topic for CSI troubleshooting

- Documentation/ceph-cluster-crd.md
- pkg/operator/ceph/config/livenessprobe.go
- pkg/operator/ceph/config/livenessprobe_test.go
- pkg/operator/ceph/object/spec.go
this commit set default values of liveness probe
fields if that individual field is 0.
Resolves #6980
**Checklist:**
> ceph: set default values of liveness probe

- pkg/operator/ceph/object/user/controller.go
Currently endpoint is filled from `Status.Info["endpoint"]` string map for cephobjectstore user's secret and
have two issues:
1.) endpoint is nil and only secureendpoint is available
2.) Chance of small race window in which endpoint is not filled before this ceph object user is handling.
Resolves #
**Checklist:**
> ceph: fill up endpoint for cephobjectstore user

- cluster/charts/rook-ceph/templates/deployment.yaml
The multiple filesystems parameter needed to be quoted for kubernetes to accept the parameter, without quotes the environment variable is rejected.
The value needs to be quoted to take effect.
Resolves #7223
**Checklist:**
> ceph: minor bugfix with multiple filesystems

- .github/workflows/canary-integration-test.yml
Although OSD on LV-backed PVC is supported, its test is missing. Let's add it.
Nothing
**Checklist:** …
> ceph: add osd on lv backed pvc test

- Documentation/ceph-teardown.md
This fixes the documentation to remove the CRD finalizer of the CRD and not the CR (CephCluster, CephBlockPool, etc.)
https://rook-io.slack.com/archives/CK9CF5H2R/p1613164145487300
**Checklist:**
[skip ci]
> docs: fix crd finalizer instructions

- pkg/apis/rook.io/v1/placement.go
- pkg/apis/rook.io/v1/placement_test.go
- pkg/operator/ceph/cluster/cleanup.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/cluster/version.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/file/mirror/spec.go
- pkg/operator/ceph/nfs/spec.go
- pkg/operator/k8sutil/pod.go
we don't want to merge the node affinity if specified in both
storageClassDeviceSet and placement. 
Now, we are passing new
a boolean argument in `ApplyToPodSpec` which will be false in 
case of osd and prepare pods only because we don't want to overlap 
placement of osd on PVC's and non-PVC's.
Resolves #7176 
**Checklist:**
> ceph: do not merge nodeAffinity

- pkg/daemon/ceph/osd/daemon.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_pvc_test.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/status.go
- pkg/operator/test/client.go
Add a new OSD provisioner status (reported by provisioner configmap)
that denotes that an OSD is preexisting and that OSD prepare does not
need to be run for the OSD. This only applies to OSDs on PVC currently
where existence of a deployment for the OSD indicates no further
provisioning needs to occur. New status is "preexisting".
Allow creating new OSDs on PVCs before updating existing ones by
allowing deferring OSDs during processing of OSD provisioning status
ConfigMaps. Deferral is identified by new "preexisting" status.
**manual tests**
- single node
- multi node
Resolves #6716
**Checklist:**
> ceph: create new OSDs on PVC before updating existing ones

- pkg/apis/ceph.rook.io/v1/placement.go
- pkg/operator/ceph/cluster/cleanup.go
- pkg/operator/ceph/cluster/cleanup_test.go
The cleanup job will need to run wherever the ceph daemons were running. The scheduling is done by rook on the specific nodes where the daemons were running, so there is no need for other placement such as node or pod affinity.
**Checklist:**
> ceph: Add tolerations for all daemons to the cleanup job

- cluster/charts/rook-ceph/values.yaml
this commit removes the casing error in helm.
`enableCephFSSnapshotter` in `values.yaml` does not
match the casing `enableCephfsSnapshotter` in `deployment.yaml`.
Resolves #7236 
**Checklist:**
> ceph: helm update variable enableCephFSSnapshotter

- pkg/operator/ceph/cluster/osd/spec.go
this commit update `osdProps.placement` instead
of `osdProps.getPreparePlacement()` in the osd.go
this was the copy paste issues coming from other pr.
Resolves #
**Checklist:**
> ceph: update placement in osd with osdProps.placement

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
This reverts commit 1ed307cb0991dfd716bce471c8f88e6a11b7def0. In
8aaff235bbdf2264949145fad6804dea3865d873 we have introduced the ability
to set a specific monitoring port so the block that fails if the port is
not the default 9283 is not needed anymore.
Resolves #
**Checklist:**
> ceph: revert fail if mgr prometheus is not default

- Documentation/ceph-object-bucket-claim.md
`phase` field name is not capitalized and its values are capitalized. Here is an example.
```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
...
status:
phase: Pending
```
**Checklist:**
- [o] …
> ceph: fix typos in ob doc

- pkg/operator/ceph/nfs/nfs.go
There is no need to validate rados pool namespace, it is optional[1]. And if in
case rados namespace is not specified, it is appropriately handled.
[1] https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/doc/man/ganesha-core-config.rst
> ceph: rados pool namespace is optional for nfs deployments

- pkg/daemon/ceph/client/crash.go
- pkg/daemon/ceph/client/crash_test.go
- pkg/daemon/ceph/osd/remove.go
Add ceph archive cmd in osd removal for
silencing the warning when osd is removed.
Signed-off-by: crombus <pkundra@redhat.com>
Resolves #
**Checklist:**
> ceph: Add ceph archive cmd in osd removal

- cluster/examples/kubernetes/ceph/filesystem.yaml
Some MDS fields such as placement, resource belong to mirroring currently.
It corrects the fields location to below metadataServer as it meant
Signed-off-by: Taeuk Kim <taeuk_kim@tmax.co.kr>
Resolves #
**Checklist:**
> ceph: correct fs yaml fields

- Documentation/ceph-filesystem.md
- cluster/examples/kubernetes/ceph/csi/cephfs/storageclass.yaml
The pre-provisioned volume or static-PV support in cephfs-csi has changed.
Delete 'rootPath' field which is no longer used
related with #4064
> docs: Delete 'rootPath' in cephfs storageclass yaml

- Documentation/ceph-pool-crd.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/examples/kubernetes/ceph/pool.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/daemon/ceph/client/pool.go
- tests/framework/installer/ceph_manifests.go
This will allow setting ceph pool quotas in bytes and/or objects.
Ceph documentation: https://docs.ceph.com/en/latest/rados/operations/pools/#set-pool-quotas
Signed-off-by: Frank Ritchie <12985912+fritchie@users.noreply.github.com>
Resolves #
**Checklist:**
> ceph: add ability to set pool quotas

- pkg/operator/ceph/object/health.go
We shouldn't use `user.userID` if `GetUser()` failed.
Resolves #7278 
**Checklist:** …
> ceph: fix SIGSEGV when failing to get object store user

- pkg/daemon/ceph/client/pool.go
- pkg/daemon/ceph/client/pool_test.go
- pkg/operator/ceph/pool/validate.go
- pkg/operator/ceph/pool/validate_test.go
Both cannot be identical otherwise this will create placement issues.
Resolves #
**Checklist:**
> ceph: fail if subfailure domains are identical

- pkg/operator/ceph/cluster/osd/spec.go
The --silent option will remove the progress bar of the curl but also
silence any errors of stderr, so adding --show-error will display the
error even if --silent is used.
Resolves #
**Checklist:**
> ceph: show error even in silent curl

- pkg/operator/ceph/cluster/osd/spec.go
cURL's ca-cert and Golang TLS config for ca-certs have a different
meaning, it seems that the Golang implementation will always lookup the
local certs first and then proceeds with the specificed cert, if the
system's certs works it will never go to the specificied certificate.
cURL however, does the opposite by strictly checking the specified cert.
If the certificate is signed we don't need to force a specific
certificate, thus by using capath instead we let cURL determine what's
best to validate against.
Resolves #
**Checklist:**
> ceph: do not use curl ca-cert for signed certificates

- pkg/operator/ceph/cluster/osd/config.go
- pkg/operator/ceph/cluster/osd/osd.go
keyring for osd.x is generated by `ceph volume` command, thus it is
not necessary to try to create it in operator.
Resolves #7279 [Updated by Blaine]
**Checklist:**
> ceph: remove unnecessary generate key for osd

- pkg/operator/ceph/cluster/cephstatus.go
- pkg/operator/ceph/cluster/cephstatus_test.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/osd/health.go
- pkg/operator/ceph/cluster/osd/health_test.go
With https://github.com/rook/rook/pull/6999 merged, we no longer need individual code paths to remove stuck osds and mons so removed the extra code.
removed condition check for "Health_Ok" before calling `forceDeleteStuckRookPodsOnNotReadyNodes()`, now we directly call the `forceDeleteStuckRookPodsOnNotReadyNodes()` as the function only advances if there are NotReady nodes.
Added some additional labels for pod filtering.
Resolves #
**Checklist:**
> ceph: removed individual force delete pod code for mons and osds

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-with-drive-groups.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/ceph/ceph-cluster-cleanup.md
- images/ceph/Makefile
- pkg/apis/ceph.rook.io/v1/types.go
There are still references to v15.2.7 in integration tests to allow
testing OSDs on partitions.
The newest dated Ceph image is ceph/ceph:v15.2.9-20210224
Resolves #
**Checklist:**
[test full]
> ceph: update build and examples to use v15.2.9

- pkg/operator/ceph/cluster/osd/osd_pvc_test.go
- pkg/operator/test/client.go
Change the TestOSDsOnPVC unit test to use t.Log()/t.Logf() to avoid
having a special infof() function that was unnecessary since our unit
tests run with `go test -v` where the `-v` flag interleaves t.Log()
output.
Resolves #
**Checklist:**
> ceph: change osd on pvc unit test to use t.Log()

- pkg/operator/k8sutil/prometheus.go
- Do not reconcile ServiceMonitor/PrometheusRule on label updates.
This allows users to add custom labels which can be used by
custom Prometheus instances for monitoring.
- Update call for PrometheusRule was missing. Added it back.
Resolves #
**Checklist:**
> ceph: unmanage labels of monitoring resources

- Documentation/ceph-common-issues.md
- images/ceph/Dockerfile
- images/ceph/Makefile
- images/ceph/set-ceph-debug-level
- images/ceph/toolbox.sh
By running the toolbox and injecting a single env variable to it we will
propagate the desired log level to all ceph daemons running on the
cluster:
```
kubectl -n rook-ceph set env deploy/rook-ceph-tools CEPH_DEBUG_LEVEL=1
```
Resolves #
**Checklist:**
> ceph: ability to set cluster wide log level

- .github/workflows/build.yml
- .github/workflows/canary-integration-test.yml
- .github/workflows/codegen.yml
- .github/workflows/codespell.yaml
- .github/workflows/commitlint.yml
- .github/workflows/golangci-lint.yaml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/mod-check.yml
- .github/workflows/stale.yaml
- .github/workflows/unit-test.yml
Github just switched to use Ubuntu 20.04 for the ubuntu-latest and it is
breaking some of our scenarios so far. Especially scenario creating
partitions.
Closes: https://github.com/rook/rook/issues/7327
Resolves https://github.com/rook/rook/issues/7327
**Checklist:**
> ceph: stick with ubuntu-18.04 on the CI

- .github/workflows/canary-integration-test.yml
- .github/workflows/codegen.yml
- .github/workflows/commitlint.yml
- .github/workflows/golangci-lint.yaml
- .github/workflows/mod-check.yml
- .github/workflows/unit-test.yml
Github just switched to use Ubuntu 20.04 for the ubuntu-latest and it is
breaking some of our scenarios so far. Especially scenario creating
partitions.
Closes: https://github.com/rook/rook/issues/7327
(cherry picked from commit 0adf7624d95c5aab4a1dcb9fc9a732c31880f8a6)
**Backport of #7328**
[skip ci]
> ceph: stick with ubuntu-18.04 on the CI (bp 7328)

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- pkg/daemon/ceph/osd/kms/vault.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/object/spec.go
- tests/manifests/test-kms-vault-spec.yaml
The vault env variable VAULT_BACKEND is read by the secret library so we
must not change it. This is reverting
ee6a03dfb85cd17d608773ca22abaedbe55868c2 with a few extra fixes for the
rgw code.
Resolves #
**Checklist:**
> ceph: revert kms VAULT_KV_VERS to VAULT_BACKEND

- pkg/operator/ceph/cluster/osd/spec.go
If there is a warning coming from the Vault server we must catch it and
exit immediately to reflect it if no key was retrieved.
**Needs https://github.com/rook/rook/pull/7336/ first**
> ceph: expose vault warnings better

- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
The livenessprobe for swift/health always check with RGW internal port if host network disabled,
but won't work if only secure port is configured
Resolves #
**Checklist:**
> ceph: handle ssl cases for RGW's livenessprobe

- Documentation/ceph-filesystem.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/daemon/ceph/client/filesystem.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/filesystem_test.go
The upcoming Rook release 1.6 will support Ceph Pacific which introduces
stable support for multiple Ceph Filesystems in the same cluster. So we
now allow the creation of multiple Filesystem if the release is Pacific.
Also, we remove the Operator config flag which was not necessary.
Here I have 2 filesystems:
```
[root@rook-ceph-tools-6b4889fdfd-vncck /]# ceph fs ls
name: myfs, metadata pool: myfs-metadata, data pools: [myfs-data0 ]
name: myfs2, metadata pool: myfs2-metadata, data pools: [myfs2-data0 ]
```
```
cluster:
id:     cc747950-589a-4862-bad2-ff7de1217b1a
health: HEALTH_WARN
mons a,b,c are low on available space
6 pool(s) have no replicas configured
services:
mon: 3 daemons, quorum a,b,c (age 2d)
mgr: a(active, since 2d)
mds: myfs:1 myfs2:1 …
```
> ceph: rework multiple filesystem support

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Ceph_daemon label includes references to a replaced OSD that cause a prometheus
ruleset to fail due many-to-many match error. The changes to this PR filters the
extra matching ceph_daemon time-series.
Resolves #
**Checklist:**
[skip ci]
> ceph: fixed prometheus query to avoid many-to-many match error

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/examples/kubernetes/ceph/pre-k8s-1.16/crds.yaml
- tests/framework/installer/ceph_manifests.go
Even though CRs for bucket health check was added, CRDs were missing from
crds.yaml file. So the health check always enabled for RGW.
Resolves #
**Checklist:**
> ceph: update CRDs for healthcheck in crds.yaml

- .github/workflows/canary-integration-test.yml
- Jenkinsfile
- PendingReleaseNotes.md
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- tests/framework/installer/ceph_installer.go
- tests/integration/ceph_flex_test.go
- tests/integration/ceph_helm_test.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_smoke_test.go
- tests/integration/ceph_upgrade_test.go
If the user doesn't want:
* an encrypted osd
* an osd with a backing device
* multiple osd on the same block device
Then the OSD will be prepared using the ceph-volume raw mode which does
not use LVM.
Closes: https://github.com/rook/rook/issues/4768
Resolves https://github.com/rook/rook/issues/4768
**Checklist:**
Blocked by https://github.com/ceph/ceph/pull/33371
> ceph: add raw mode for non-pvc osd

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
This PR adds an alert that notifies the users if an OSD restarts
for 5 times under 5 minutes. Each restart corresponds to 2 changes
in the value of ceph_osd_up metric.
Resolves #
**Checklist:**
[skip ci]
> ceph: add osd flapping alert

- pkg/apis/ceph.rook.io/v1/object.go
- pkg/apis/ceph.rook.io/v1/object_test.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/server.go
- tests/scripts/webhook-config.yaml
this commit adds new crd to admission webhooks to check
if one of the port or securePort are set to non-zero
value in objectstore crd.
If both are set to 0 in crd we'll see error like
```
Error from server (invalid create: either of port or securePort
fields should be not be zero): error when creating "object-test.yaml":
admission webhook
"cephobjectstore-wh-rook-ceph-admission-controller-rook-ceph.rook.io"
denied the request: invalid create: either of port or securePort fields
should be not be zero.
```
Resolves #
**Checklist:**
> ceph: webhook check if one of port or securePort are non-zero

- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
When c-v runs after the end of the prepare sequence, it will look for
lvm and raw-based OSDs. The raw mode detects LVM OSDs so we must trim
the list of OSD, only to report the LVM ones if their ID exists.
Closes: https://github.com/rook/rook/issues/7359
Resolves https://github.com/rook/rook/issues/7359
**Checklist:**
> ceph: do not duplicate osd info

- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
We will now use raw mode on non-pvc for pacific and onward.
> ceph: use raw mode for pacific on non-pvc

- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/admin_test.go
- pkg/operator/ceph/object/bucket.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/objectstore_test.go
- pkg/operator/ceph/object/realm/controller.go
- pkg/operator/ceph/object/realm/controller_test.go
- pkg/operator/ceph/object/user.go
- pkg/operator/ceph/object/zone/controller.go
- pkg/operator/ceph/object/zone/controller_test.go
- pkg/operator/ceph/object/zonegroup/controller.go
- pkg/operator/ceph/object/zonegroup/zonegroup.go
Sometimes radosgw-admin succeed after showing error message.
Here is an example.
```
2021-02-26 04:10:44.190418 I | op-bucket-prov: creating Ceph user "ceph-user-aSzNqgE7"
E0226 04:11:37.901310       8 controller.go:199] error syncing 'logging/loki-bucket': error provisioning bucket: Provision: can't create ceph user: error creating ceph user "ceph-user-aSzNqgE7": failed to unmarshal json. 2021-02-26T04:11:21.425+0000 7f6714be4980  1 robust_notify: If at first you don't succeed: (110) Connection timed out
2021-02-26T04:11:21.426+0000 7f6714be4980  0 ERROR: failed to distribute cache for ceph-hdd-object-store.rgw.meta:users.uid:ceph-user-aSzNqgE7
2021-02-26T04:11:32.168+0000 7f6714be4980  1 robust_notify: If at first you don't succeed: (110) Connection …
```
> ceph: fix improper json parsing

- .github/workflows/golangci-lint.yaml
- pkg/daemon/ceph/client/pool.go
- pkg/operator/k8sutil/pod_test.go
- pkg/operator/test/client.go
- tests/framework/installer/ceph_manifests_v1.5.go
Suppress the following complaints.
```
$ golangci-lint run -E gosec
pkg/operator/test/client.go:244:13: G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)
randIdx := rand.Intn(len(nodes.Items))
^
tests/framework/installer/ceph_manifests_v1.5.go:44:19: G107: Potential HTTP request made with variable url (gosec)
response, err := http.Get(url)
^
pkg/daemon/ceph/client/pool.go:182:6: ineffectual assignment to stats (ineffassign)
var stats = new(PoolStatistics)
^
pkg/operator/k8sutil/pod_test.go:34:2: ineffectual assignment to container (ineffassign)
container, err := GetMatchingContainer([]v1.Container{}, expectedName)
^
```
**Checklist:**
- [o] **Commit Message Formatting**: Commit titles and messages follow guidelines in the …
> ceph: suppress golanglint-ci complaints

- pkg/operator/ceph/config/defaults.go
As a recommendation from the core team we should turn on PG auto repair
when running on Bluestore OSDs. The Quincy release will enable this by
default but in the meantime let's enable it here.
Resolves #
**Checklist:**
> ceph: enable pg auto repair

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
Fix an apt-get update issue by bumping to the latest (fixed) version of
manusa/actions-setup-minikube (v2.3.1).
Resolves #
**Checklist:**
> ci: update minikube github action to fix apt-get

- Documentation/ceph-pool-crd.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/examples/kubernetes/ceph/pool.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
- pkg/daemon/ceph/client/pool.go
- tests/framework/installer/ceph_manifests.go
This is a follow up to:
https://github.com/rook/rook/pull/7264
which added pool quotas. It was stated that it would be nice to
be able to set pool max_bytes quotas using standard k8s quantity
formats rather than an integer representing the number of bytes.
I was too busy at the time to make the changes. This PR adds the
functionality.
Signed-off-by: Frank Ritchie <12985912+fritchie@users.noreply.github.com>
Resolves #
**Checklist:**
> ceph: set pool quota with k8s quantity format

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/charts/rook-ceph/templates/role.yaml
- tests/framework/installer/ceph_manifests.go
The rbac required for multus was present in role which makes only the network-attachment-definitions present in the rook cluster's namespace accessible to the operator. 
Moved it to clusterrole for cluster-wide access to NADs.
Resolves #6945 
**Checklist:**
> ceph: updated rbac for multus in helm charts

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
This commit adds an alert that notifies the users about OSD
requests taking too long to process.
Needs to be backported to release 1.5
Resolves #
**Checklist:**
[skip ci]
> ceph: add osd slow ops alert

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/examples/kubernetes/ceph/pool.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/daemon/ceph/client/pool.go
This is a follow up to:
https://github.com/rook/rook/pull/7397
Looks like I forgot to mark maxSize as optional.
Additionally, I updated an error message.
Signed-off-by: Frank Ritchie <12985912+fritchie@users.noreply.github.com>
Resolves #
**Checklist:**
> ceph: mark maxSize as optional

- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
this commit enables gh action to run
Flex test on only 'v1.15.12',
Smoke and Helm tests on both 'v1.15.12','v1.20.2',
Mgr, Multicluster and upgrade tests on only 'v1.20.2'
Resolves #
**Checklist:**
> ci: run gh action on multiple k8s version

- pkg/operator/k8sutil/resources.go
Small regression introduced in https://github.com/rook/rook/commit/26c8fd9bd14178d74dcc28f009e5c2f658224436
which was overriding the BlockOwnerDeletion from the ownerref.
Now, if set we don't modify it.
This fixes deployments on OCP.
Resolves #
**Checklist:**
> ceph: fix csi blocker owner deletion

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Script's tests were failing randomly because of an unclosed file
exceptions.
Resolves https://github.com/rook/rook/issues/7433
**Checklist:**
> ceph: fix for the random script failures because of open file issue

- pkg/apis/rook.io/v1/placement.go
- pkg/apis/rook.io/v1/placement_test.go
- pkg/operator/ceph/cluster/cleanup.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/cluster/version.go
- pkg/operator/ceph/file/mds/spec.go
- pkg/operator/ceph/file/mirror/spec.go
- pkg/operator/ceph/nfs/spec.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/k8sutil/pod_test.go
In the case of PVC,
We'll first apply `placement.All()` and then we'll
apply `devicSet Placement`. If both are specified 
`placement.All` and `devicSet Placement` then we merging
both at least the `nodeAffinity`.
In case of non-PVC,
we apply `spec.placement`.
co-authored-by: Travis Nielsen <tnielsen@redhat.com>
Resolves #7176 
**Checklist:**
> ceph: placement in case of both PVC and non-PVC's 

- cluster/examples/kubernetes/ceph/monitoring/service-monitor.yaml
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
Other resources such as the service monitor need to match the labels on the services to the active mgr, thus the active mgr name is now set on the labels for the metrics service and dashboard service. This only affects master since adding support for multiple mgrs.
**Checklist:**
> ceph: Set active mgr label on mgr services

- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
When running encrypted OSDs on multipath the expand container was
failing to find the underlying device of the encrypted block. This was
because the underlying block was located in /dev/mapper and this path
wasn't mounted in the init container "expand-encrypted-bluefs".
Resolves #
**Checklist:**
> ceph: fix init container "expand-encrypted-bluefs" multipath

- Documentation/ceph-disaster-recovery.md
- Documentation/ceph-teardown.md
[skip ci]
Two commits to improve the documentation.
* During Ceph teradown these files also need to be removed as well.
This is a continuation of the closed PR #7395.
* docs: fix disaster recovery mon patch command
This removes the curly brackets from the json patch used to remove the
livenessProbe of the mon pod. At least in 1.18+ otherwise the patch
fails with a "cryptic" error.
Resolves #7460
Resolves #
**Checklist:**
> docs: remove left overs in /dev/mapper/ceph--*

- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/health.go
isExternal was not used anymore so let's remove it.
Resolves #
**Checklist:**
> ceph: remove unsed type field

- Documentation/ceph-cluster-crd.md
Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>
If we don't export RGW_POOL_PREFIX firstly, RGW_POOL_PREFIX will be set to default value, which is "default". Add a warning in document to give user instructions.
**Checklist:**
[skip ci]
> docs: add a warning before running create-external-cluster-resources.sh

- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- pkg/daemon/ceph/client/command.go
- pkg/daemon/ceph/client/command_test.go
- pkg/daemon/ceph/client/mon_test.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- tests/framework/installer/ceph_installer.go
Let's try to create a 'ceph' user with the uid 167 and add it to the
'disk' group so that if the permissions on the disk change then the OSD
should be able to access the disk.
Closes: https://github.com/rook/rook/issues/7405
Resolves https://github.com/rook/rook/issues/7405
**Checklist:**
> ci: fix disk issue with crashing osd

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.sh
- cluster/examples/kubernetes/ceph/import-external-cluster.sh
The secret type was missing earlier and must be set
to "kubernetes.io/rook" so that the operator does not complain.
Closes: https://github.com/rook/rook/issues/5732
Resolves #
**Checklist:**
> ceph: set secret type on external cluster script

- pkg/operator/ceph/config/network.go
- pkg/operator/ceph/config/network_test.go
- pkg/operator/k8sutil/network.go
We now support reading Network Attachment Definitions with a "static"
IPAM.
Also added more unit tests.
Resolves #
**Checklist:**
> ceph: add static IPAM support for CNI

- tests/integration/ceph_base_object_test.go
Sometimes the ci fails to find the object store user, this could be
because the user is created before the object store. So first it fails
since there is no object store and stay in a retry back-off.
Then the object store is created and always need a bit of time, at the
same time the object-user is still waiting and the next retry is longer.
Creating the object store first and then the user hopefully will help
resolve that so we don't have to increase the retry for the object-user
presence.
The error:
```
2021-03-26T08:39:34.7283769Z 2021-03-26 08:39:34.727946 I | testutil: All 2 pod(s) with label rook_object_store=teststore are running
2021-03-26T08:39:34.7284744Z 2021-03-26 08:39:34.727972 I | testutil: Running kubectl [apply -f -]
2021-03-26T08:39:35.1110681Z …
```
> ci: try to mitigate object user error

- pkg/operator/ceph/cluster/osd/spec.go
When no VAULT_BACKEND_PATH is specified we default to the API one which
is set to "secret/", we could use a different variable but we don't want
to break the library support. Bonus point this will also fix issue with
users passing a slash at the end of the path.
Resolves #
**Checklist:**
> ceph: remove extra slash in curl

- pkg/daemon/ceph/osd/kms/envs.go
- pkg/daemon/ceph/osd/kms/envs_test.go
When the cluster is growing, the operator always processes all OSDs and
re-generate their Deployment spec. The generated environment variables
for encryption are coming from a map, which by design is unordered. So
once generated the deployment will see their spec change since the
environment variable position will change.
See from the following diff:
```
env:							        env:
- name: KMS_SERVICE_NAME			      <
value: vault					      <
- name: VAULT_NAMESPACE				      <
value: ocsns					      <
- name: VAULT_TLS_SERVER_NAME			      <
- name: VAULT_BACKEND_PATH			      <
value: n_ocs					      <
- name: VAULT_ADDR					        - name: VAULT_ADDR
value: https://vault.qe.rh-ocs.com:8200		          value: https://vault.qe.rh-ocs.com:8200
>	        - name: VAULT_BACKEND_PATH
>	          value: …
```
> ceph: avoid restarting all encrypted osd on cluster growth

- Makefile
The crds-gen make target was recently renamed to crds. This broke the
ceph-csv target since it still depends on the old name.
Resolves #
**Checklist:**
> build: fix ceph-csv dependency

- pkg/operator/nfs/quota.go
At setProject function, the parameter block is not used, i removed it .
Closes: https://github.com/rook/rook/issues/7501
Signed-off-by: Steve <persistence201306@gmail.com>
Resolves #7501 
**Checklist:**
> nfs: remove unused parameter

- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/csi/spec.go
Ceph-CSI v3.2.1 fixes "cephcsi create too many process" https://github.com/ceph/ceph-csi/issues/1722
This PR also upgrades the necessary sidecars of ceph-csi.
We should try to stay in sync with the used ceph-csi version.
> ceph: Upgrade ceph-csi to v3.2.1

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/controller/spec.go
- pkg/operator/ceph/controller/spec_test.go
With Pacific comes the support for dualstack where ceph daemons can
listen on both ipv4 and ipv6 stacks.
A new field in the network spec has been added: `dualStack`
Resolves #
**Checklist:**
> ceph: add dualstack support on pacific

- pkg/operator/nfs/controller.go
- pkg/operator/nfs/controller_test.go
- pkg/operator/nfs/spec.go
Give the user the ability to specify the image that the operator will use
to spin up new NFS server.
After this change, I am going to use it in the `newStatefulSetForNFSServer`
function and use the current image as the default value so the change will not affect current users.
Resolves #7174
> nfs: Add Image to the NFSServerSpec

- pkg/operator/ceph/cluster/osd/config/config.go
OSD directories were removed in v1.2, this is some more cleanup of dir configuration that is no longer needed.
**Checklist:**
> ceph: Remove obsolete osd dirs config

- .github/workflows/crds-gen.yml
- Makefile
- build/crds/build-crds.sh
- images/ceph/Makefile
The CSV file size cannot be bigger than 1MB so let's remove all the
description fields make it lighter.
With that change the CRDs size went from 692K to 372K so the size was
reduced by almost 50%.
Resolves #
**Checklist:**
> ceph: strip crd description for csv generation

- Makefile
- build/crds/build-crds.sh
- images/ceph/Makefile
We don't want to include those CRDs anymore, as they get imported from
another operator.
This trims further down the size of our CSV generation.
Additionally, we always clean the csv directory before proceeding.
Resolves #
**Checklist:**
@jarrpa FYI.
> ceph: do not include ob/obc/volumes crds in csv

- Documentation/ceph-openshift.md
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/scc.yaml
The security context constraints need to grant access to the new default service account that is applied to the mons previous using the built-in default service account. This is related to #7406. If only we had CI on openshift to catch issues like this...
**Checklist:**
> ceph: Set default service account in the SCC 

- pkg/operator/ceph/cluster/cephstatus.go
- pkg/operator/ceph/cluster/cephstatus_test.go
Renamed appLabels to rookAppLabels in getRookPodsOnNode and added the
missing rgw app label
Resolves #
**Checklist:**
> ceph: added rgw app label to rookAppLabels for deleting stuck rook pods

- cluster/examples/kubernetes/ceph/common.yaml
The csv was not generating the rook-ceph-default service account because the comment delimiting it had a typo.
**Checklist:**
> ceph: Tag default service account for CSV generation

- cluster/examples/kubernetes/ceph/object.yaml
The crd schema requires the ssl cert to either be set or not be specified. Now the example comments out the setting to avoid the error at creation.
**Checklist:**
> ceph: SSL cert property cannot be empty

- cluster/examples/kubernetes/ceph/cluster-stretched.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- images/ceph/Makefile
- pkg/operator/ceph/cluster/version_test.go
- pkg/operator/ceph/version/version.go
- tests/framework/installer/ceph_installer.go
- tests/integration/ceph_smoke_test.go
- tests/integration/ceph_upgrade_test.go
- tests/scripts/validate_cluster.sh
With the Ceph Pacific release coming this week we add support in Rook for Pacific with the Rook v1.6 release coming soon. The integration tests will now run across nautilus, octopus, and pacific to cover all supported Ceph versions. The default examples still specify Octopus until there is more bake time for Pacific.
**Checklist:**
> ceph: Enable Ceph Pacific as a supported version

- pkg/daemon/ceph/osd/remove.go
`ceph osd purge` should remove the OSD auth, but many users have issues
where they are unable to create new OSDs after removing old ones due to
the old OSD auth still being present. Therefore, run `ceph auth del` for
the OSD after purging to fix this.
Resolves #
**Checklist:**
> ceph: remove auth in osd-purge job

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
Allow empty ("") compressionMode in CRDs' 'pool' spec.
Resolves #
**Checklist:**
> ceph: allow empty compressionMode in CRD pools

- Documentation/ceph-mon-health.md
- PendingReleaseNotes.md
- pkg/operator/ceph/cluster/mon/health.go
If the health spec of the CephCluster CRD has a timeout set to 0 like
so:
```
healthCheck:
daemonHealth:
mon:
disabled: false
interval: 45s
timeout: 0
```
And the mon goes out of quorum then Rook will not fail over the mon.
This is interesting when doing maintenance on a monitor and we don't
want to create a new one.
Resolves #
**Checklist:**
> ceph: allow monitor maintenance mode

- Documentation/ceph-osd-mgmt.md
- pkg/daemon/ceph/osd/remove.go
Revert "ceph: remove auth in osd-purge job" and replace with doc update.
Upate osd purge docs to inform users they need to stop the operator before purging OSDs when using node-based OSDs.
Resolves #
**Checklist:**
> ceph: update osd purge docs

- tests/framework/installer/ceph_manifests.go
The integration tests in the CI seem to be picking up the rook/ceph:master tag that is published instead of using the local build. This was observed in #7558 where the helm and upgrade suites failed to run in the backport PR because the rook-ceph-default service account was not created. However, the mon canary pod was still started by the operator as if it was running code from the published master tag. After the master tag was pushed from merging #7556 and the tests were rerun, then they did pass. Therefore, it appears the CI is not testing what is built locally.
This PR is only a draft while simulating a failure to investigate the issue...
**Checklist:**
> ceph: Tests are picking up release tag instead of local build

- tests/framework/installer/ceph_manifests.go
The integration tests pick up the manifests directly from the examples folder, including with the release tag. In the release branch the Jenkins build still uses the master build when building locally before tagging it with the release tag. So the tests need to use the master tag.
Cherry-picked from release-1.6 since it needed to be tested there first.
**Checklist:**
> ceph: Integration tests use master tag even in release branch

- .mergify.yml
Previously forgot to add mergify rule to auto merge backports to
release-1.6. Backport PRs would still be created but not merged.
// skip jenkins
[skip ci]
Resolves #
**Checklist:**
> bot: auto merge backports to release-1.6

- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/filesystem_test.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/file/mds/spec_test.go
This fixes code and tests in `pkg/operator/ceph/file` and its subpackages that were importing the same libraries multiple times.
**Checklist:**
- [ X ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ X ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
> ceph: `pkg/operator/ceph/file`: multiple imports

- cluster/examples/kubernetes/ceph/object-openshift.yaml
comment` sslCertificateRef` as it can't be
null.
closes #7578 
Resolves #7578 
**Checklist:**
> ceph: sslCertificateRef can't be null

- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
We have seen the CI failing to run the minikube action, reaching the API
limit. By using authenticated requests, we can overcome this limitation.
Follow-up of https://github.com/rook/rook/pull/7503/commits/1504fb869b5ed5b8f7df362bc9df3b45dd8ac9ea
Resolves #
**Checklist:**
> ci: use authenticated requests for minikube action on suite

- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/object/user/controller_test.go
This fixes libraries that were being imported multiple times in
pkg/operator/ceph/object and its subpackages.
Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
**Checklist:**
> ceph: fix multiple imports

- pkg/operator/ceph/cluster/mon/mon.go
If the cluster is deleted and the mon canaries cannot be scheduled for
any reasons, let's not wait and return.
Resolves #
**Checklist:**
> ceph: cancel canary retry if necessary

- Documentation/ceph-monitoring.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- pkg/apis/ceph.rook.io/v1/keys.go
- pkg/apis/ceph.rook.io/v1/labels.go
- pkg/operator/ceph/cluster/mgr/mgr.go
Labels field in MonitoringSpec is used define labels which
needs to be injected into the monitoring resources created
by Rook operator.
Resolves #
**Checklist:**
> ceph: add labels to monitoring spec

- Makefile
- build/makelib/common.mk
- build/makelib/golang.mk
- cluster/olm/ceph/generate-rook-csv-templates.sh
- cluster/olm/ceph/generate-rook-csv.sh
- images/ceph/Makefile
CSV generation now requires versions of yq and operator-sdk that are
downloaded by the makefiles. Previously Ceph image creation used
makefile versions but `make csv-ceph` used versions present on the
system.
`sed -i 's///g' $FILE` doesn't work on Unix/Mac.
`sed -i'' -e 's///g' $FILE` is portable.
Resolves #
// skip jenkins; all tests should fail if build is failing
[skip ci]
**Checklist:**
> build: allow CSV gen on mac

- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .mergify.yml
- Jenkinsfile
With the release of K8s 1.21.0 we now run the integration tests on v1.21.0. To keep consistent with running master builds on five recent releases, we keep master builds back to v1.15 and skip other less changed versions such as v1.16 and 1.19.
**Checklist:**
> ci: Run integration tests on k8s 1.21

- .github/workflows/build.yml
- .github/workflows/canary-integration-test.yml
- .github/workflows/codegen.yml
- .github/workflows/crds-gen.yml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/mod-check.yml
- build/makelib/golang.mk
- go.sum
- images/cross/Dockerfile
With the release of go 1.16, we update the tools. The -i flag is now deprecated, no longer necessary for building in a private directory. The go modules are cleaned up at the same time.
Due to the changes in the go.mod that is generated differently than 1.15, we will need to require 1.16 when we move to it. We may want to wait a bit on merging this change since 1.16 was just released, but at least we can start testing with it now.
Resolves #7364 
**Checklist:**
> build: Update the build to use go 1.16 while still supporting 1.15

- .github/workflows/build.yml
- .github/workflows/canary-integration-test.yml
- .github/workflows/codegen.yml
- .github/workflows/crds-gen.yml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/mod-check.yml
- build/makelib/golang.mk
- go.sum
- images/cross/Dockerfile
With the release of go 1.16, we update the tools. The -i flag is now deprecated, no longer necessary for building in a private directory. The go modules are cleaned up at the same time.
This is a manual backport since mergify doesn't backport the workflows.
**Checklist:**
> build: Update the build to use go 1.16 (bp #7371)

- pkg/daemon/ceph/osd/daemon.go
getAvailableDevices() should continue if something wrong happens in a device than returning immediately with error.
Resolves #7543
**Checklist:**
- [o] …
> ceph: continue to get available devices if failed to get a device info

- pkg/operator/ceph/object/admin.go
- pkg/util/exec/exec.go
- tests/integration/ceph_base_object_test.go
- tests/integration/ceph_upgrade_test.go
Work around issue https://github.com/rook/rook/issues/7573
and make sure integration tests check for regressions.
Eventually we should use the RADOS Gateway admin REST API, but for now
we need to work around an issue where the built version of
'radosgw-admin' has incompatibilities with the RADOS Gateway version
running in the Ceph cluster.
Of note, Rook built on the Ceph Pacific image will not support
some 'radosgw-admin' commands to Ceph Nautilus (v14) or Octopus (v15)
clusters.
Further complicating matters, the flag used for the workaround changes
between Ceph v16.2.0 and v16.2.1 (both Pacific).
This bug needs to be treated a little differently than most of the ways
Rook handles different commands for different Ceph versions because this
is based on the Ceph version that is installed in …
> ceph: work around object user create/update incompatibilities between Rook v1.6 and Ceph pre-Pacific

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
Additionally to skip ci tag in the commit message from https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
We can now skip integration tests by applying the "skip-ci" label at the
**creation time** of the PR. Obviously adding later works but will still
trigger the test in the initial opening of the PR. Subsequent pushes
will skip integration tests.
Resolves #
**Checklist:**
> ci: ability to skip ci with a label

- Documentation/ceph-filesystem.md
Update Kubernetes link to version 1.9.X which includes registry addon.
Ref:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.10.md
https://github.com/kubernetes/kubernetes/pull/58564
Signed-off-by: chienfuchen32 <chienfuchen32@gmail.com>
Resolves #
**Checklist:**
> ceph: update Kubernetes registry link in CephFS document

- build/crds/build-crds.sh
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/operator/ceph/cluster/osd/deviceSet.go
The schema generation was not generating the metadata properties under the VolumeClaimTemplate type, resulting in the properties being ignored by the api server. The preserve unknown fields tag was not working recursively on the volumeClaimTemplates since the subtypes were defined. Now we post-process the schema so we can preserve the unknown fields for the volume claim templates metadata.
Also we add check for the metadata to ensure we don't end up with duplicate crushDeviceClasses.
Resolves #7629 
**Checklist:**
> ceph: Preserve volume claim template metadata in schema

- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/spec.go
Since Pacific, we can deploy multiple object gateway using the same
keying and they will appear in the service map separetly. So from now on
and on upgrades to Pacific Rook will remove all extra deployments to
only keep 1. In this single deployment the number of replica will be set
the desired `instances` count from the CRD spec.
You will now see gateways like this on Pacific:
```
rgw: 3 daemons active (1 hosts, 1 zones)
```
See an upgrade operator logs from Octopus to Pacific:
```
2021-04-14 10:05:16.883145 I | ceph-object-controller: setting multisite settings for object store "my-store"
2021-04-14 10:05:17.006492 I | ceph-object-controller: Multisite for object-store: realm=my-store, zonegroup=my-store, zone=my-store
2021-04-14 10:05:17.006516 I | ceph-object-controller: multisite …
```
> ceph: use replicaset instead of deployments for rgw instances

- pkg/operator/ceph/controller/predicate.go
- pkg/operator/ceph/controller/predicate_test.go
To avoid logging sensitive information, do not output diffs from secrets
when reconciling resources.
Resolves #7624 
**Checklist:**
> ceph: redact secret info from reconcile diffs

- .github/workflows/integration-test-cassandra-suite.yaml
- Jenkinsfile
- tests/framework/installer/cassandra_manifests.go
- tests/integration/z_cassandra_test.go
Create a github action to run the Cassandra test since the Jenkins test machine is constantly failing on the newer ubuntu release.
Resolves #7569 in release-1.5 branch
**Checklist:**
> cassandra: Get working Cassandra test in a github action (bp #7601)

- Jenkinsfile
- build/makelib/golang.mk
CI fails on builds of release branches when Jenkins runs unit tests with the warning below:
[2021-04-15T14:15:28.461Z] go: inconsistent vendoring in /home/rook/go/src/github.com/rook/rook:
[2021-04-15T14:15:28.461Z] 	github.com/jstemmer/go-junit-report@v0.9.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
Fix this by running `go mod vendor` before each build.
Resolves #
**Checklist:**
[skip ci]
> build: run 'go mod vendor' on each build

- .github/workflows/unit-test.yml
- build/makelib/golang.mk
Dependencies for `make go.test` have to run in order, so call them
explicitly from the target rather than allowing them to be done in
parallel if `make -j` flag is used.
// skip jenkins; issue only affects github actions
[skip ci]
Resolves #
**Checklist:**
> test: do not allow go.test parallel dependencies

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
In v1.6 EC pools are being disallowed by the schema since the minimum is set to 1 on the replicated.size. We expect the replicated.size to be 0 if an EC pool is being created.
Resolves #7661 
**Checklist:**
> ceph: Allow pool replica min size 0 for EC pools

- .github/workflows/unit-test.yml
- build/makelib/golang.mk
Dependencies for `make go.test` have to run in order, so call them
explicitly from the target rather than allowing them to be done in
parallel if `make -j` flag is used.
(cherry picked from commit a818a01a13c04cff5dc89c3ce92fa2cbc4217ce3)
// skip jenkins
[skip ci]
Resolves #
**Checklist:**
> test: do not allow go.test parallel dependencies (bp #7664)

- pkg/operator/ceph/file/filesystem_test.go
- pkg/operator/ceph/file/mds/mds.go
- pkg/operator/ceph/object/rgw.go
We now always set the config flags on reconcile. Previously we were
looking for non-existing rgw or mds which means that on upgrade we would
never set those flags. However, we want to set those flags on "old"
cluster that got upgraded.
Resolves #
**Checklist:**
> ceph: always apply config flags for mds and rgw

- PendingReleaseNotes.md
Since the v1.6 release is completed, reset the pending release notes
for v1.7.
Resolves #
**Checklist:**
[skip ci]
> docs: reset the pending release notes

- .mergify.yml
In the release-1.6 branch, the k8s versions are different, we run
v1.20.2 where the master branch runs v1.21.0
Resolves #
**Checklist:**
[skip ci]
> bot: set the correct k8s version for mergify auto-merge on 1.6

- tests/framework/installer/ceph_installer.go
- tests/integration/ceph_upgrade_test.go
Since Rook 1.6 is using raw mode for simple OSD scenarios we can use v14
again without having issue with ceph-volume.
Closes: https://github.com/rook/rook/issues/7669
Resolves #
**Checklist:**
> ceph: use v14 image again for integration tests

- pkg/operator/ceph/cluster/rbd/config.go
- pkg/operator/ceph/cluster/rbd/spec.go
- pkg/operator/ceph/cluster/rbd/spec_test.go
After the peer is imported via a token, ceph internally stores the
information of the remote cluster. So the rbd-mirror daemon does not
need to have files (key and config) for the remote site.
This means lighter code for us, as well no more restarts for the
rbd-mirror daemon once a peer is added to the configuration.
Resolves #
**Checklist:**
On-top of https://github.com/rook/rook/pull/7623, will rebase once merged.
> ceph: remove rbd-mirror ceph config/key

- .github/workflows/canary-integration-test.yml
- tests/scripts/validate_modified_files.sh
currently, the build action is not failing if there
is/are any modified files after the build. this commit
will validate build with `git status` after `make build`
command will fail if any changed file found.
Resolves #7657 
**Checklist:**
> ci: make build not failing

- .github/workflows/canary-integration-test.yml
- .github/workflows/macos-build.yml
- Makefile
- build/crds/build-crds.sh
- build/makelib/golang.mk
- images/ceph/Makefile
Introducing a small action on MacOS to help us catch errors with various
'make' command on OSX, most notably 'sed' versus 'gnu-sed'.
Resolves #
**Checklist:**
[skip ci]
> ci: build and run various make commands on MacOS

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cmd/rook/ceph/osd.go
- pkg/apis/rook.io/v1/types.go
- pkg/daemon/ceph/osd/device.go
- pkg/operator/ceph/cluster/osd/config/config.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/deviceset_test.go
- pkg/operator/ceph/cluster/osd/envs.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
Ceph support the option '--osd-crush-initial-weight' upon OSD start,
which sets an explicit weight (in TiB units) to specific OSD. Allow
passing this option all the way from the user (similar to
'DeviceClass'), for the special case where end users wants it cluster
to have non-even balance over specific OSDs (e.g., one of the OSDs is
placed over a partition alongside OS-partition).
ROOK issue: https://github.com/rook/rook/issues/7448
Signed-off-by: Shachar Sharon <ssharon@redhat.com>
Allow set OSD initial-weight, similar to device-class.
Resolves #7448
**Checklist:**
> ceph: allow passing 'osd-crush-initial-weight'

- pkg/daemon/ceph/osd/volume.go
This fixes cases where raw provisioning mode still cannot be used for
Rook v1.6 and Ceph Pacific clusters where json.Unmarshal fails to read
the ceph-volume output after OSD provisioning.
Resolves #7670 
Resolves #
**Checklist:**
> ceph: use ceph-volume v2 report format for Pacific

- .github/workflows/integration-tests-on-release.yaml
We resolved disk flapping problem (#7405) with #7467. However, this fix was not applied to integration test in master.
**Checklist:** …
> ceph: prevent disk flapping problem in master

- .github/workflows/integration-tests-on-release.yaml
If some jobs from master/release branches fail then we keep the runner
alive so we can debug it.
By default, runners will naturally timeout after 6 hours. See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
Resolves #
**Checklist:**
[skip ci]
> ci: let master/release runners alive on failure

- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-tests-on-release.yaml
- cluster/examples/kubernetes/ceph/cluster-test.yaml
- pkg/daemon/ceph/osd/volume.go
- tests/framework/installer/ceph_installer.go
ci: increase the number of lock retries
We have seen new cases where retrying to lock the device 3 times is not
enough. It's the same race we had experienced where Ceph tries to
acquire a lock on the device but systemd-udevd does the same too.
Retrying 20 times every 0.1sec seems to mitigate that issue in the CI.
ci: wait a bit longer for the mirroring to happen
30sec was not enough see:
```
timeout 30 sh -c 'until [ "$(kubectl exec -n rook-ceph-secondary deploy/rook-ceph-tools -t -- rbd -p replicapool ls|grep -c test)" -eq 1 ]; do echo "waiting for image to be mirrored" && sleep 1; done'
shell: /bin/bash -e {0}
env:
GOROOT: /opt/hostedtoolcache/go/1.16.3/x64
MINIKUBE_HOME: /home/runner/work/_temp
unable to get monitor info from DNS SRV with service name: ceph-mon
rbd: couldn't connect to …
```
> ci: mitigate block locking issues and flapping mirroring test

- pkg/daemon/ceph/client/crush.go
- pkg/operator/ceph/cluster/watcher.go
- pkg/operator/ceph/cluster/watcher_test.go
OSDs not automatically started when adding nodes to existing cluster.
Call the helper NormalizeCrushName(name) to make sure the node name can match the name in the crush map before querying for the node in the crush map, and reconcile when new nodes get added.
Closes: https://github.com/rook/rook/issues/7462 https://github.com/rook/rook/issues/7534
Resolves:  https://github.com/rook/rook/issues/7462 https://github.com/rook/rook/issues/7534
**Checklist:**
> ceph: update OSDs reconcile

- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/spec.go
- pkg/operator/ceph/cluster/osd/deviceSet.go
- pkg/operator/ceph/cluster/osd/deviceset_test.go
- pkg/operator/k8sutil/pvc.go
- pkg/operator/k8sutil/pvc_test.go
Expand Mon Pvc's if storage request has increased for the Mons in the
cephcluster crd.
rook will now expand the mon PVC's if the size of mon storage has changed/increased in the cephcluster CRD
rook will do nothing if size in the cephcluster CRD is less than actual size of PVC or equal to the actual size of PVC.
**Checklist:**
> ceph: Expand Mon Pvc's

- pkg/daemon/ceph/client/command.go
- pkg/daemon/ceph/client/command_test.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/mgr/orchestrator.go
- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/objectstore.go
There is no strong reason to have different timeout values.
**Checklist:**
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a- …
> ceph: unity timeout values of commands

- Documentation/ceph-upgrade.md
When upgrading Rook clusters created before v1.5,
`kubectl apply -f crds.yaml` fails due to the existence of
the usupported `spec.preserveUnknownFields`. Add text documenting how to
work around this issue in the Ceph upgrade docs.
Resolves #7659 
**Checklist:**
> docs: workaround preserveUnknownFields upgrade

- Documentation/ceph-cluster-crd.md
moved multus support out of experimental.
Resolves #6748
**Checklist:**
[skip ci]
> ceph: moved multus support out of experimental

- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/osd_test.go
The nodeAffinity for portable OSDs is needed to ensure the OSDs are tied to the same zone or other failure domain where the OSD was prepared and where it is expected to run. During upgrade the topology affinity was not being detected since the osd prepare job is skipped in that case. Now the topology will be detected from the running OSD daemon pod's node.
**Checklist:**
> ceph: Detect the osd topology affinity during upgrade

- Makefile
- build/crds/build-crds.sh
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/rook.io/v1/types.go
Allow metadata on VolumeClaimTemplates in StorageClassDeviceSets to be
persisted.
This effectively reverts https://github.com/rook/rook/pull/7683 (notably the `yq` formatting changes) and makes it totally unnecessary to inject `x-kubernetes-preserve-unknown-fields` into the CRDs where we use embedded k8s objects.
This new PR I made to controller-tools https://github.com/kubernetes-sigs/controller-tools/pull/557 finalizes some work someone else had done upstream to allow generating the embedded objectmeta. We can use it by specifying the commit hash for the `CONTROLLER_GEN_VERSION`
Resolves #
**Checklist:**
> api: persist VolumeClaimTemplate metadtata

- Documentation/ceph-dashboard.md
[skip ci]
remove unrelated text in the documentation  "this is long video b" in the output of `kubectl -n rook-ceph get service` command
Resolves #
**Checklist:**
> docs: remove unrelated text "this is long video b"

- .github/workflows/canary-integration-test.yml
- Documentation/ceph-cluster-crd.md
- Documentation/ceph-object-store-crd.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
- pkg/daemon/ceph/osd/kms/kms.go
- pkg/daemon/ceph/osd/kms/kms_test.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
- tests/manifests/test-kms-vault-spec.yaml
- tests/manifests/test-object.yaml
- tests/scripts/deploy-validate-vault.sh
The "https://docs.ceph.com/en/latest/radosgw/vault/" says RGW supports only version v2 of
kv engine, so disable encryption if the admin didn't provide "VAULT_BACKEND" in security.kms.ConnectionDetails
Resolves #
**Checklist:**
> ceph: check for kv engine version for SSE RGW

- pkg/operator/ceph/cluster/version.go
The ceph upgrade blocks if the ceph heatlh is HEALTH_ERR. If the user wants to force the upgrade despite the health error, they will need to set skipUpgradeChecks: true in the cephcluster CR. This message will hopefully make that setting more discoverable.
**Checklist:**
> ceph: Clarify log message to continue with upgrade if needed

- pkg/operator/ceph/object/user/controller.go
when store.Status was not initialized it caused
crashes when assigning store.Status.Info["endpoint"]
to objContext.Endpoint.
This commits makes sure store.Status is not Nil
before setting objContext.Endpoint and
objContext.SecureEndpoint in the ObjectStoreUser
controller.
Closes: https://github.com/rook/rook/issues/6916
Resolves #6916
**Checklist:**
> ceph: ensure object store endpoint is initialized for user

- .github/workflows/canary-integration-test.yml
So we can get https://github.com/ceph/ceph/pull/40985 and have a more
stable CI. Once v16.2.2 is released we can revert this.
Resolves https://github.com/rook/rook/issues/7727
**Checklist:**
[skip ci]
> ci: use latest pacific for mirroring test

- Documentation/ceph-filesystem-crd.md
- cluster/examples/kubernetes/ceph/csi/cephfs/storageclass-ec.yaml
docs: Add dedicated storageclass-ec.yaml
Add dedicated documentation for cephfs-storageclass using erasure-coding.
Closes: https://github.com/rook/rook/issues/7319
Signed-off-by: davralin <git@davralin.work>
Resolves #7319
**Checklist:**
> cephfs-documentation: Add dedicated storageclass-ec.yaml

- .github/workflows/canary-integration-test.yml
So we can get https://github.com/ceph/ceph/pull/40985 and have a more
stable CI. Once v16.2.2 is released we can revert this.
(cherry picked from commit 6a97721576e03f4ae361e3bac867002b3e344da5)
Resolves #
**Checklist:**
> ci: use latest pacific for mirroring test  (backport #7735)

- .github/workflows/canary-integration-test.yml
- Documentation/ceph-cluster-crd.md
- Documentation/ceph-object-store-crd.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
- pkg/daemon/ceph/osd/kms/kms.go
- pkg/daemon/ceph/osd/kms/kms_test.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
- tests/manifests/test-kms-vault-spec.yaml
- tests/manifests/test-object.yaml
- tests/scripts/deploy-validate-vault.sh
The "https://docs.ceph.com/en/latest/radosgw/vault/" says RGW supports only version v2 of
kv engine, so disable encryption if the admin didn't provide "VAULT_BACKEND" in security.kms.ConnectionDetails
Since there is a conflict between secret engine used by `osd` encryption and `rgw` encryption, the `SecuritySpec` moved to `CephObjectStore` CRD
Resolves #
**Checklist:**
> ceph: check for kv engine version for SSE RGW  (backport #7385)

- tests/scripts/github-action-helper.sh
Try to mitigate the following error from the CI:
```
+ sudo vgcreate test-rook-vg /dev/sdb
Can't open /dev/sdb exclusively.  Mounted filesystem?
Error: Process completed with exit code 5.
```
Now we retry up to 3 times to create the volume group.
Closes: https://github.com/rook/rook/issues/7487
Resolves #
**Checklist:**
> ci: retry vgcreate on failure

- Documentation/ceph-upgrade.md
The ceph-common-issues doc link in ceph-upgrade document was broken
Fixed the link by changing the directory path
Closes: https://github.com/rook/rook/issues/7794
Resolves #
**Checklist:**
[skip ci]
> docs: common-issues link updated in ceph-upgrade doc

- pkg/apis/ceph.rook.io/v1/object.go
- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/health.go
- pkg/operator/ceph/object/s3-handlers.go
- tests/integration/ceph_base_object_test.go
In case ssl enabled for RGW, bucket healthcheck won't work since access is denied from the server.
Resolves #
**Checklist:**
> ceph: fix healthcheck in case ssl enabled for rgw (backport #7331) 

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/cluster_external.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
Because of the recent CRD changes made, the mon count had a minimum of
1, making the configuration of the external cluster impossible. The
operator would fail to add the finalizer:
```
2021-04-29 16:57:38.429451 E | ceph-cluster-controller: failed to reconcile. failed to add finalizer: failed to add finalizer "cephcluster.ceph.rook.io" on "test-external": CephCluster.ceph.rook.io "test-external" is invalid: spec.mon.count: Invalid value: 0: spec.mon.count in body should be greater than or equal to 1
```
We now fixed the CRD as well as adding the CR status.
Resolves #
**Checklist:**
> ceph: fix external cluster mode

- .github/workflows/canary-integration-test.yml
- Documentation/cassandra.md
- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- Documentation/cockroachdb.md
- Documentation/edgefs-csi.md
- Documentation/edgefs-monitoring.md
- Documentation/edgefs-quickstart.md
- Documentation/nfs.md
- cluster/examples/kubernetes/cassandra/operator.yaml
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- cluster/examples/kubernetes/cockroachdb/operator.yaml
- cluster/examples/kubernetes/edgefs/operator.yaml
- cluster/examples/kubernetes/nfs/operator.yaml
- cluster/examples/kubernetes/nfs/webhook.yaml
- cluster/examples/kubernetes/yugabytedb/operator.yaml
The patch release version is now set to v1.5.11 for example manifests and documentation
**Checklist:**
[skip ci]
> build: Set release version to v1.5.11

- cmd/rook/ceph/osd.go
- images/ceph/set-ceph-debug-level
- pkg/daemon/ceph/osd/volume.go
Filestore support has been long gone with only bluestore currently supported.
**Checklist:**
> ceph: Remove obsolete references to filestore

- Documentation/ceph-mon-health.md
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/k8sutil/pod.go
- pkg/operator/k8sutil/pod_test.go
Events like node drain can take more than 10-15 minutes. If the node is not up before the default monTimeOut of 10 minutes, then rook will attempt to fail over the mon. This failover won't work as the node is still down.
This PR retries once before the mon failover if the mon pod is not scheduled
Resolves #7776
**Checklist:**
> ceph: retry once before mon failover if mon pod is unscheduled

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster-stretched.yaml
- images/ceph/Makefile
Ceph v16.2.2 is released with dated tag v16.2.2-20210505. Update Ceph
images to match with or without date as appropriate.
Resolves #
**Checklist:**
> ceph: update images to v16.2.2

- pkg/daemon/ceph/client/erasure-code-profile.go
- pkg/daemon/ceph/client/erasure-code-profile_test.go
currently, recreating erasure codedpPool with
different Settings show error and creation
failed.
Adding `--force` to the erasure coded profile
command works file with above condition.
Resolves #2016 
**Checklist:**
> ceph: update erasure coded profile command

- build/crds/build-crds.sh
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
The upgrade of the csv is failing to the latest schema when the crushDeviceClass is specified and when the volumeClaimTemplate annotations do not preserve the unknown fields. To fix the upgrade, we preserve the fields even though it should not be necessary from the strict schema.
The csv upgrade was working prior to the merge of #7631 downstream, and this error just appeared in the next upgrade test after that merge.
**Checklist:**
> ceph: Preserve volume claim template annotations during upgrade

- pkg/operator/ceph/cluster/crash/reconcile.go
- pkg/operator/ceph/cluster/predicate.go
- pkg/operator/ceph/config/store.go
- pkg/operator/ceph/controller/predicate.go
When DEBUG logging is enabled in the operator, there are a number of overwhelming messages in the log that are very overwhelming and don't seem useful, which makes debug mode difficult to use
Updated/Cutted down the messages that are not useful in debug mode.
Closes: https://github.com/rook/rook/issues/7499
Resolves #
**Checklist:**
> core: enhancement in debug logs

- .github/workflows/push-build.yaml
For the github action to publish the build to aws, we also need to include the aws-region setting in the action settings. The master builds are not currently being published due to this issue.
**Checklist:**
> build: Include aws region when publishing build

- Jenkinsfile
- tests/framework/installer/ceph_installer.go
- tests/integration/ceph_multi_cluster_test.go
The multicluster test was never removing the finalizer of the external cluster since the core cluster was being removed first. Now we remove the external cluster first to ensure the finalizer will be removed properly instead of forcefully by the test.
This is needed for the 1.6 patch release since the github tests are not currently being triggered for the release branch.
Resolves #7824 
**Checklist:**
> ceph: Multicluster test cleanup of external cluster first

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
In some clusters, the schema validation is failing for the default object.yaml example that the value must be of a type string null. While the null value shouldnt be strictly needed, we need working examples by default.
```
The CephObjectStore XXX is invalid:
* spec.gateway.sslCertificateRef: Invalid value: "null": spec.gateway.sslCertificateRef in body must be of type string: "null"
* spec.gateway.securePort: Invalid value: "null": spec.gateway.securePort in body must be of type integer: "null"
```
Resolves #7803 
**Checklist:**
> ceph: Add nullable to object gateway settings

- design/ceph/ceph-managed-disruptionbudgets.md
- pkg/operator/ceph/disruption/clusterdisruption/osd.go
- pkg/operator/ceph/disruption/clusterdisruption/osd_test.go
- pkg/operator/ceph/disruption/clusterdisruption/reconcile.go
- Detect node drains more reliably. When OSD is down and OSD pod is not scheduled to any node or if the scheduled node is not ready, then assume that node is draining.
- Don't set no-out flag on the failure domain if the OSD is down due to reasons other than node drain (say disk failure)
- update unit tests
- update design doc to reflect above changes
Resolves #
**Checklist:**
> ceph: update podDisruptionBudget controller for OSD

- pkg/operator/ceph/csi/spec.go
This commit removes redundant `RBDProvisionerSTSTemplatePath` and
`CephFSProvisionerSTSTemplatePath` variables which were forgetten to
be removed in https://github.com/rook/rook/pull/5982 when csi support
for k8s 1.13 was removed.
**Checklist:**
> ceph: remove redundant csi statefulset template path vars

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/create-external-cluster-resources.sh
- pkg/operator/ceph/cluster/cluster_external.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/controller/spec.go
- pkg/operator/ceph/controller/spec_test.go
If the cluster is external we want to periodically rehydrate the mgr
endpoint. This handles the scenarion where the active manager changes,
so we need to update the endpoint with the new IP address.
The create-external-cluster-resources.py script now requires an extra
permission to query the manager service so Rook can discover the active
one and its IP.
Testing:
```
[leseb@tarox~/go/src/github.com/rook/rook][external-active-mgr-change] minikube kubectl -- exec -n rook-ceph deploy/rook-ceph-tools -ti -- ceph mgr stat
{
"epoch": 37,
"available": true,
"active_name": "b",
"num_standby": 1
}
[leseb@tarox~/go/src/github.com/rook/rook][external-active-mgr-change] kubectl -n rook-ceph-external get ep
NAME                     ENDPOINTS          AGE
rook-ceph-mgr-external   172.17.0.12:9283 …
```
> ceph: actively update the service endpoint for external mgr

- .github/workflows/push-build.yaml
this commit restrict push image build action to run on
fork repo.
Resolves #7871
**Checklist:**
> ci: restrict push image build action to run on fork

- pkg/operator/ceph/config/livenessprobe.go
- pkg/operator/ceph/config/livenessprobe_test.go
Changing the livenessprobe handler is not possible anymore for the
simple reason that it does not make sense. Practicly speaking we just
cannot change its value since it is propapaged to all the daemons. The
exec handler contains the socket name of the daemon, because daemons
have different names we cannot possibly make it generic since it will
apply to all.
Closes: https://github.com/rook/rook/issues/7842
Resolves #
**Checklist:**
> ceph: do not overwrite the probe handler

- .github/workflows/canary-integration-test.yml
Before running the external script test let's make sure the prometheus
exporter is loaded. We often see in the CI errors like:
```
kubectl -n rook-ceph exec $(kubectl get pod -l app=rook-ceph-tools -n rook-ceph -o jsonpath='{.items[0].metadata.name}') -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool
shell: /bin/bash -e {0}
env:
GOROOT: /opt/hostedtoolcache/go/1.16.4/x64
MINIKUBE_HOME: /home/runner/work/_temp
Execution Failed: unable to connect to endpoint: 172.17.0.10:9283
Traceback (most recent call last):
File "/etc/ceph/create-external-cluster-resources.py", line 801, in <module>
raise err
File "/etc/ceph/create-external-cluster-resources.py", line 798, in <module>
rjObj.main()
File "/etc/ceph/create-external-cluster-resources.py", line 779, in …
```
> ceph: wait for the prometheus module to be ready

- .github/workflows/canary-integration-test.yml
**BACKPORT OF https://github.com/rook/rook/pull/7891**
Before running the external script test let's make sure the prometheus
exporter is loaded. We often see in the CI errors like:
```
kubectl -n rook-ceph exec $(kubectl get pod -l app=rook-ceph-tools -n rook-ceph -o jsonpath='{.items[0].metadata.name}') -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool
shell: /bin/bash -e {0}
env:
GOROOT: /opt/hostedtoolcache/go/1.16.4/x64
MINIKUBE_HOME: /home/runner/work/_temp
Execution Failed: unable to connect to endpoint: 172.17.0.10:9283
Traceback (most recent call last):
File "/etc/ceph/create-external-cluster-resources.py", line 801, in <module>
raise err
File "/etc/ceph/create-external-cluster-resources.py", line 798, in <module>
rjObj.main()
File …
```
> ceph: wait for the prometheus module to be ready (bp #7891)

- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
After mon failover is initiated, there was a time window where if the operator was restarted, the new mon is started and has joined quorum, but the operator does not believe the mon should be in quorum after the operator restart. The operator was mistakenly removing the extra mon prematurely, sometimes causing quorum to be lost if another mon was also down at the same time. If the mon does not come back online, steps to recover quroum would need to be followed from the disaster guide. Now the expected list of mons will be updated immediately during mon failover if the operator successfully created the new mon deployment, thus removing the window where restarting the operator can cause quorum loss.
Most commonly this issue was hit during node drain where …
> ceph: Persist expected mon endpoints immediately during mon failover

- pkg/operator/ceph/cluster/osd/spec.go
A directory is created under dataDirHostPath for each OSD. In host-based cluster, its name is constructed from kernel device name like _dev_sdb though user specifies udev persistent device name. We should use unique name among all OSDs.
Resolves #7878 
**Checklist:**
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific …
> ceph: fix hostpath of osd to avoid data corruption

- cluster/olm/ceph/generate-rook-csv.sh
This commit makes it so the bundle created for OKD will actually create a operator deployment that works on OpenShift. Previously it did not set the variables in the Operator Deployment thus the operator was not working as expected after deployment by OLM.
**Checklist:**
> build: rook-ceph Operator deployment for OKD should be the same as OCP for it to work

- cluster/charts/rook-ceph/templates/deployment.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
Enabling rbac is a legacy setting from way back when the operator was creating the rbac internally, instead of declaring it explicitly in the common.yaml. There is no need for this setting now.
**Checklist:**
> ceph: Remove obsolete operator setting for enabling rbac

- pkg/operator/ceph/config/network.go
- pkg/operator/ceph/config/network_test.go
- pkg/operator/k8sutil/network.go
- pkg/operator/k8sutil/network_test.go
With this change, the Rook ceph cluster can have only a public network or
only a cluster network or both can be specified. Prior to this commit if
only a public network was specified, it was copied to the cluster network.
Also, cluster network will only be applied to Osd pods.
Resolves #7436
**Checklist:**
> ceph: support specifying only public network or only cluster network or both

- Documentation/ceph-object-store-crd.md
- Documentation/ceph-object.md
- cluster/examples/kubernetes/ceph/object-ec.yaml
- cluster/examples/kubernetes/ceph/object-multisite-pull-realm.yaml
- cluster/examples/kubernetes/ceph/object-multisite.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
- cluster/examples/kubernetes/ceph/object-test.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- design/ceph/object/store.md
- design/common/object-bucket.md
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.5.go
- tests/manifests/test-object.yaml
`CephObjectStore->gateway->type` is not used. Rook has only supported s3-like interface and hasn't had no code which handles `type` field.
In addition, this field was removed from CRD in the following commit.
ceph: auto-gen crds
31db03fece6d11c3054a6488b96d1c6ad3722b84
**Checklist:** …
> ceph: remove an missing field in crd

- .github/workflows/push-build.yaml
#7887 Disabled the private forks from running the action to push the images, but it also disabled the master branch. For now, reverting the change so we can get master builds pushed again.
**Checklist:**
> Revert restriction to push image build action to run on fork as it also disabled master pushes

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/k8sutil/events.go
- pkg/operator/k8sutil/events_test.go
PR will add functionality to generate k8s events for the cephCluster
Resolves #6042
**Checklist:**
> ceph: generate cephCluster reconcile result as events

- ROADMAP.md
With the v1.6 release completed, we now update the roadmap for v1.7.
**Checklist:**
> docs: Update roadmap for v1.7

- Documentation/ceph-teardown.md
Play safe: after zapping devices, issue a call to 'partprobe' to inform
the OS on partition table changes. This may assists users who face
voodoo partition creation, as described in those ROOK issues:
https://github.com/rook/rook/issues/7734
https://github.com/rook/rook/issues/7940
Signed-off-by: Shachar Sharon <ssharon@redhat.com>
Resolves #
**Checklist:**
> docs: call partprobe after zapping device

- pkg/daemon/ceph/client/mirror.go
- pkg/daemon/ceph/client/mirror_test.go
- pkg/operator/ceph/pool/config.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/predicate.go
- pkg/operator/ceph/pool/predicate_test.go
- pkg/operator/k8sutil/secret.go
If the monitors addresses change, we must update the peer secret with
the new addresses. For this, each time the configmap
"rook-ceph-mon-endpoints" is updated, we trigger a reconcile on the
CephBlockPool CRs, which will update the token secret.
Resolves #
**Checklist:**
> ceph: rehydrate the bootstrap peer token secret on monitor changes 

- cluster/charts/rook-ceph/templates/deployment.yaml
If you enable `allowMultipleFilesystems`, the chart will generate an invalid yaml file.
(@leseb for SA)
Resolves an error introduced in #7307
**Checklist:**
> Fix helm chart to allow multiple filesystems

- pkg/operator/ceph/controller/spec.go
If no endpoint are configured let's simply return.
Closes: https://github.com/rook/rook/issues/7963
Resolves #
**Checklist:**
> ceph: do not configure external metric endpoint is not present

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/ceph/ceph-cluster-cleanup.md
- pkg/apis/ceph.rook.io/v1/types.go
This version of Ceph notably fixes an issue where the Ceph dashboard's
urlPrefix option caused the dashboard to be inaccessible.
Resolves #
**Checklist:**
> ceph: Rook v1.6 - update Ceph version to v15.2.12 (latest)

- pkg/daemon/ceph/client/mirror.go
- pkg/daemon/ceph/client/mirror_test.go
`rbd mirror pool peer bootstrap create` will use cluster fsid by default, so specifying --site-name shouldn't be needed at all.
Resolves #
**Checklist:**
> ceph: remove '--site-name' arg when creating bootstrap peer token

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- go.mod
- go.sum
added volume replication operator release-v0.1 branch to the go.mod as we are doing enhancements to the volume replication CRDS. Once we have a release will change this to the release-v0.1 branch.
Resolves #
**Checklist:**
> ceph: pin volume replication to release-v0.1 branch

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-stretched.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/ceph/ceph-cluster-cleanup.md
- images/ceph/Makefile
- pkg/apis/ceph.rook.io/v1/types.go
- tests/scripts/k8s-vagrant-multi-node.sh
- tests/scripts/minikube.sh
Ceph v16 will be the default in Rook v1.7. Update references in the
master branch from v15 (currently v15.2.11) to v16 (currently v16.2.4).
Resolves #
**Checklist:**
> ceph: update references to v15.2.11 to v16.2.4

- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- pkg/operator/ceph/operator.go
earlier, to change the operator log level we need
to change the deployment which requires a restart
the operator pod.
Now, we are changing the log level dynamically
by reading the configmap. For, backward compatibility
we still load from env var.
Resolves #7909 
**Checklist:**
> ceph: change operator log level dynamically

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/ceph/ceph-cluster-cleanup.md
- pkg/apis/ceph.rook.io/v1/types.go
**PUSHED IN RELEASE-1.6 BRANCH**
We're happy to announce the 13th backport release in the Octopus series.
We recommend users to update to this release. For a detailed release
notes with links & changelog please refer to the official blog entry at
https://ceph.io/releases/v15-2-13-octopus-released
Notable Changes
---------------
* RADOS: Ability to dynamically adjust trimming rate in the monitor and
several other bug fixes.
Resolves #
**Checklist:**
> ceph: update ceph version to 15.2.13 - release-1.6

- pkg/operator/ceph/object/spec.go
The backend path has for transit secret engine in vault kms for RGW is changed from pacific
Resolves #
**Checklist:**
> ceph: update the backend path for transit engine

- Documentation/helm-ceph-cluster.md
- build/makelib/helm.mk
- cluster/charts/rook-ceph-cluster/.helmignore
- cluster/charts/rook-ceph-cluster/Chart.yaml
- cluster/charts/rook-ceph-cluster/README.md
- cluster/charts/rook-ceph-cluster/templates/NOTES.txt
- cluster/charts/rook-ceph-cluster/templates/_helpers.tpl
- cluster/charts/rook-ceph-cluster/templates/cephcluster.yaml
- cluster/charts/rook-ceph-cluster/templates/clusterrolebinding.yaml
- cluster/charts/rook-ceph-cluster/templates/configmap.yaml
- cluster/charts/rook-ceph-cluster/templates/deployment.yaml
- cluster/charts/rook-ceph-cluster/templates/role.yaml
- cluster/charts/rook-ceph-cluster/templates/rolebinding.yaml
- cluster/charts/rook-ceph-cluster/templates/serviceaccount.yaml
- cluster/charts/rook-ceph-cluster/values.yaml
- go.mod
- tests/framework/installer/ceph_helm_installer.go
- tests/framework/installer/ceph_installer.go
- tests/framework/utils/helm_helper.go
This manages a CephCluster CRD, and is designed to be deployed into its own namespace to manage a single Ceph cluster independent of the main Rook operator.
Additional functions:
- Ability to setup ServiceMonitor for the Prometheus operator
Signed-off-by: Henry Zhang <me@henry.dev>
Implements a CephCluster chart that deploys the necessary roles, with the option of also deploying the toolbox
pod alongside the CRD.
I saw some progress on the issue regarding moving the charts out of the Rook repository. This is probably a good idea longer term, but as that ticket had stagnated, I went ahead and implemented this chart.
This is just a thin wrapper around the `CephCluster` CRD. The `values.yaml` is almost the `cluster.yaml` example.
Example template output: …
> ceph: implement CephCluster CRD Helm Chart

- pkg/operator/k8sutil/pvc.go
- pkg/operator/k8sutil/pvc_test.go
Expand the functionality of 'ExpandPVCIfRequired' to check if
storageclass does allow expansion then only expand the PVC.
otherwise skip the expansion.
We have seen cases where expansion is not allowed by the storage class and PVC update with the new size fails because of the same reason. Handle this via checking the storage class's ability to expand PVC.
Resolves #
**Checklist:**
> ceph: expand PVC only if storageclass allow expansion

- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/admin_test.go
radosgw-admin may output logs before and after JSON when this command succeeds. We should get rid of these logs before unmarshaling output. Although the logs before JSON were treated in  PR7354, the logs after JSON weren't.
**Checklist:** …
> ceph: parse json correctly

- pkg/operator/ceph/cluster/mon/health.go
If the number of desired mons is reduced, for example from 5 down to 3, the extra mons will be removed by the next health check. Only a single mon can be removed per health check to ensure that other mons do not become unhealthy at the same time as removing an extra mon, and so the list of healthy mons can be refreshed. If multiple mons are removed in a single health check, we risk removing too many mons and losing quorum.
This also enables specific mons to be removed as described in #7999.
Resolves #7999
**Checklist:**
> ceph: remove one extra mon per health check

- pkg/operator/ceph/operator.go
When the operator configmap is edited, it is likely that some user will
simply put "debug" instead of "DEBUG", so let's always transform the
value to upper case to ease user experience.
Resolves #
**Checklist:**
> ceph: force upper case for Operator log level

- pkg/apis/ceph.rook.io/v1/security.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/encryption.go
- pkg/daemon/ceph/osd/encryption_test.go
- pkg/daemon/ceph/osd/kms/envs.go
- pkg/daemon/ceph/osd/kms/vault.go
- pkg/daemon/ceph/osd/kms/volumes.go
- pkg/daemon/ceph/osd/volume.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
- tests/manifests/test-cluster-on-pvc-encrypted.yaml
- tests/scripts/github-action-helper.sh
- tests/scripts/validate_cluster.sh
When configuring encrypted on-pvc clusters we now set the cluster fsid
in the LUKS header. If needed we can then determine if the encrypted
block is part of our cluster or not. We also attach the pvc_name in case
it might become useful.
Closes: #7991
Resolves #
**Checklist:**
> ceph: add ceph cluster fsid to LUKS header

- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/pool/controller.go
Saw this today in the logs:
```
2021-06-02 13:02:54.787838 I | ceph-block-pool-controller: deleting pool "testpool"
2021-06-02 13:02:56.178094 I | cephclient: no images/snapshosts present in pool "testpool"
2021-06-02 13:02:56.178125 I | cephclient: purging pool "testpool" (id=17)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cef49f]
goroutine 1607 [running]:
github.com/rook/rook/pkg/operator/ceph/pool.(*mirrorChecker).checkMirroringHealth(0xc001a98ba0, 0x8, 0xc000d34c60)
/home/runner/work/rook/rook/pkg/operator/ceph/pool/health.go:115 +0xdf
github.com/rook/rook/pkg/operator/ceph/pool.(*mirrorChecker).checkMirroring(0xc001a98ba0, 0xc0016fd500) …
```
> ceph: stop the monitoring before cleanup

- pkg/operator/ceph/csi/csi.go
- pkg/operator/ceph/csi/spec.go
CSI drivers failed to start if rook encountered error while reading configmap with no retry.
This commit introduces retry for starting CSI driver if there is a failure in reading configmap upto 3 times.
Fixes: #7950
**Checklist:**
> ceph: retry starting CSI drivers on failure

- .github/workflows/canary-integration-test-arm64.yml
- tests/scripts/github-action-helper.sh
Thanks to @xin3liang we now have 2 hosted runners on ARM64. So let's add
a small integration test for it.
Resolves #
**Checklist:**
[skip ci]
> ci: add arm64 runner

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
Both MonSpec.Count and CephVersionSpec.Image should be optional for the
external cluster. So marking them as so.
Resolves #
**Checklist:**
> ceph: fix external cluster upgrade

- pkg/daemon/ceph/osd/daemon.go
Unless they are encrypted disk and have markers for a ceph cluster.
Closes: https://github.com/rook/rook/issues/8046
**This is only affecting master, NO BACKPORT NEEDED**
Resolves https://github.com/rook/rook/issues/8046
**Checklist:**
> ceph: always skip disks with filesystem

- INSTALL.md
- Jenkinsfile
- The github actions are fully covering the build needs in master so we can go ahead and disable Jenkins by default. In case there is still a desired to run Jenkins for a particular PR, the `test full` text can still trigger it.
- Given the improvements with github actions and other improvements, we now clean up the build instructions for developers joining the rook project. There is no need to understand about Jenkins pipelines since we will soon be fully on github actions.
@subhamkrai @leseb Nothing left before we disable Jenkins in master, right?
**Checklist:**
> Disable the Jenkins build in master by default

- cluster/examples/kubernetes/ceph/cluster.yaml
removed the word EXPERIMENTAL from multus section in cluster.yaml
Resolves #
**Checklist:**
> ceph: removes experimental for multus in cluster.yaml

- cluster/charts/rook-ceph/values.yaml
enableCSIHostNetwork was missing in the helm charts values.yaml example. adding the same in this commit.
Resolves #
**Checklist:**
[skip ci]
> ceph: correct enableCSIHostNetwork in helm charts

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- pkg/apis/ceph.rook.io/v1/resources.go
- pkg/daemon/ceph/cleanup/disk.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/osd/create.go
- pkg/operator/ceph/cluster/osd/envs.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/util/sys/device.go
Currently it is not possible to set resource limits based on device classes
for different OSDs. Now adding an ability to use predefined keys for main
cluster spec Resource section to reflect resource limits for different OSDs
with different device classes.
Closes: https://github.com/rook/rook/issues/8007
Resolves #
**Checklist:**
> ceph: add ability to set resource limit for OSDs based on device classes

- pkg/operator/ceph/cluster/predicate.go
- pkg/operator/ceph/controller/predicate.go
I found this bug while working on the CephObjectStore dependency updates. 
Fix a bug where delete events on Rook-Ceph CRs would be detected
multiple times if deletion was blocked. Old method used pointer
comparison instead of using the (metav1.Time) Equal() method.
**Checklist:**
> ceph: fix detection of delete event reconciliation

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
- cluster/examples/kubernetes/ceph/create-external-cluster-resources.sh
- cluster/examples/kubernetes/ceph/import-external-cluster.sh
- go.mod
- go.sum
- pkg/operator/ceph/client/controller.go
- pkg/operator/ceph/cluster/rbd/controller.go
- pkg/operator/ceph/controller/controller_utils.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/mirror/controller.go
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/bucket.go
- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/bucket/provisioner_test.go
- pkg/operator/ceph/object/bucket/rgw-handlers.go
- pkg/operator/ceph/object/bucket/util.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/controller_test.go
- pkg/operator/ceph/object/health.go
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/object/rgw.go
- pkg/operator/ceph/object/rgw_test.go
- pkg/operator/ceph/object/s3-handlers.go
- pkg/operator/ceph/object/status.go
- pkg/operator/ceph/object/user.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/object/user/controller_test.go
- pkg/operator/ceph/pool/controller.go
We have been having many issues with external mode with Ceph version
mismatching. The operator would have a Ceph version different than the
external cluster. The `radosgw-admin` was used to interact with S3
users, even a small version delta would cause the command to coredump.
After checking with the rgw core team it appears Rook was misusing the
CLI and the admin ops API should be used instead.
So this patch is the first introduction of go-ceph in Rook to consume
the rgw admin ops API instead of the `radosgw-admin` CLI, **only** for
user management in this initial commit.
Later we can do more such as bucket operation, zone management etc.
Closes: https://github.com/rook/rook/issues/7924
**Which issue is …
> ceph: stop using radosgw-admin CLI for s3 user management

- go.mod
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/objectstore.go
We now create and delete pools in parallel.
Before this patch, the deletion:
```
2021-06-08 13:48:26.557328 I | cephclient: no images/snapshosts present in pool "my-store.rgw.control"
2021-06-08 13:48:26.557383 I | cephclient: purging pool "my-store.rgw.control" (id=1)
2021-06-08 13:48:27.030021 I | ceph-object-controller: done disabling the dashboard api secret key
2021-06-08 13:48:28.800661 I | cephclient: purge completed for pool "my-store.rgw.control"
2021-06-08 13:48:29.085744 I | cephclient: no images/snapshosts present in pool "my-store.rgw.meta"
2021-06-08 13:48:29.085762 I | cephclient: purging pool "my-store.rgw.meta" (id=3)
2021-06-08 13:48:30.835487 I | cephclient: purge completed for pool "my-store.rgw.meta"
2021-06-08 13:48:31.128349 I | cephclient: no images/snapshosts …
```
> ceph: operate over object store pools concurrently

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
External script should raise an exception if 'quorum-leader' mon has only `v2` type address enabled. It should make user aware that when v2 type is enabled they should enable `v1` type address as well.
Resolves #
**Checklist:**
> ceph: mons should enable v1 address type when enabling v2

- pkg/operator/ceph/cluster/version_test.go
- pkg/operator/ceph/version/version.go
- pkg/operator/ceph/version/version_test.go
.Compare Image ID while checking for upgrades. This will be useful in the case where ceph version is same but  image ID is different and also when build number has not changed for a hotfix build. 
For example:
**existing ceph version** - 
```ceph version 14.2.11-139.el8cp (b8e1f91c99491fb2e5ede748a1c0738ed158d0f5) nautilus (stable) ```
**new ceph version with hotfix** - 
```ceph version 14.2.11-139.0.hotfix.bz1959254.el8cp (5c0dc966af809fd1d429ec7bac48962a746af243) nautilus (stable)```
Resolves #7964
Commit ID Regex test: https://play.golang.org/p/S5wBQrueC_m
**Checklist:**
> ceph: compare ceph commit ID for upgrade check

- pkg/operator/ceph/csi/csi.go
This commit changes CSI_ENABLE_HOST_NETWORK default value to true
since it was observed that cephfsvolume gets blocked when csi cephfs
nodeplugin is restarted and nodeunpublish call also hangs when
cephfs nodeplugin is using pod networking.
Updates: #8085
Resolves #
**Checklist:**
> ceph: set `CSI_ENABLE_HOST_NETWORK` default value to true

- tests/integration/ceph_smoke_test.go
Prior to 1.16 we do not injec the volumereplication CRDs so the
csi-rbdplugin-provisioner will fail to fetch the CRD.
Closes: https://github.com/rook/rook/issues/8039
Resolves #
**Checklist:**
[skip ci]
> ci: only run ceph-csi volume replication on k8s >= 1.16

- pkg/daemon/ceph/client/config.go
- pkg/daemon/ceph/client/mgr.go
- pkg/operator/ceph/cluster/cephstatus.go
- pkg/operator/ceph/cluster/cephstatus_test.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_upgrade_test.go
In the latest Ceph releases starting with v16.2.1, all clients are recommended to be updated so they will have a security fix to connect with a secure global ID. A health warning will be raised if any insecure clients are connected and another health warning is raised if insecure clients are still allowed. Rook will now disable allowing the insecure clients if the health warning is not being raised to indicate that there are insecure clients still connected. This means that upgraded clusters will not have this disabled until all the daemons are updated.
If there are any clients connecting insecurely, they will be denied the next time they come online after the operator disables this setting. Therefore, perhaps we need to consider an option in the operator …
> ceph: Disable insecure global id if no insecure clients

- cmd/rook/ceph/osd.go
- cmd/rook/ceph/osd_test.go
If devices are not specified for node return empty desired devices
list and do not fail prepareOSD job.
Closes: #8097
Signed-off-by: Denis Egorenko degorenko@mirantis.com
Resolves #
**Checklist:**
> ceph: do not fail prepareOSD job if devices are not passed

- Documentation/helm-ceph-cluster.md
Adds documentation to 1.6 branch with instructions as to how to install the
chart slated for release in 1.7.
Signed-off-by: Henry Zhang <me@henry.dev>
As discussed in https://github.com/rook/rook/pull/7778, this adds a documentation section to the 1.6 release that points to the ceph-cluster Helm chart that is currently in master.
**Checklist:**
> ceph: backport installation documentation for Ceph Cluster chart

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
codespell ci was failing due to mirroring typo.
Resolves #
**Checklist:**
> ceph: correct mirroring typo

- cluster/examples/kubernetes/ceph/monitoring/rbac.yaml
When there are two mgr daemons, a sidecar of the mgr will update the service monitor depending on the active mgr daemon. When there is only a single mgr, the operator will create the service monitor. Now, we add rbac for the mgr to create these resources.
Without the rbac, the mgr will fail similar to this error:
```
2021-06-11 08:49:43.594790 E | cephcmd: failed to reconcile services. failed to enable service monitor: service monitor could not be enabled: failed to retrieve servicemonitor. servicemonitors.monitoring.coreos.com "rook-ceph-mgr" is forbidden: User "system:serviceaccount:openshift-storage:rook-ceph-mgr" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "openshift-storage"
```
**Checklist:**
> ceph: Add RBAC for mgr to create service monitor

- Documentation/ceph-cluster-crd.md
- cluster/examples/kubernetes/ceph/cluster.yaml
- pkg/apis/ceph.rook.io/v1/resources.go
- pkg/daemon/ceph/cleanup/disk.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/volume.go
- pkg/daemon/ceph/osd/volume_test.go
- pkg/operator/ceph/cluster/osd/create.go
- pkg/operator/ceph/cluster/osd/envs.go
- pkg/operator/ceph/cluster/osd/osd.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/util/sys/device.go
Currently it is not possible to set resource limits based on device classes
for different OSDs. Now adding an ability to use predefined keys for main
cluster spec Resource section to reflect resource limits for different OSDs
with different device classes.
This is an backport of pull request #8028 
Closes: https://github.com/rook/rook/issues/8007
Resolves #
**Checklist:**
> ceph: add ability to set resource limit for OSDs based on device classes (backport #8028)

- pkg/daemon/ceph/client/filesystem.go
- pkg/operator/ceph/file/filesystem.go
we should not use --force when creating filesystem(fs)
as it will recreate fs which will leads to data loss
when `preserveFilesystemOnDelete` is set to 'true'.
this commit removes --force argument when creating fs.
Resolves #
**Checklist:**
> ceph: remove --force when creating filesystem

- pkg/daemon/ceph/client/fake/osd.go
- pkg/daemon/ceph/client/osd.go
- pkg/daemon/ceph/client/osd_test.go
- pkg/operator/ceph/cluster/osd/integration_test.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/update.go
- pkg/operator/ceph/cluster/osd/update_test.go
Add ability to set device class for existing osd deployments,
based on its crush map device class.
Related-Issue: rook#8028
Resolves #
**Checklist:**
> ceph: set device class for already present osd deployments

- .github/workflows/integration-test-upgrade-suite.yaml
this commit adds one more kubernetes version 'v1.15.12'
in upgrade suite test.
Resolves #
**Checklist:**
> ci: add one more kubernetes version in upgrade suite

- Documentation/helm-ceph-cluster.md
- Documentation/helm-operator.md
- Documentation/helm.md
- cluster/charts/rook-ceph-cluster/templates/cephcluster.yaml
- cluster/charts/rook-ceph-cluster/values.yaml
- Document how the CephCluster CR for an existing cluster can be taken over by the new cluster helm chart if desired, for simpler management of the RBAC and related resources.
- The cluster CR name defaults to the namespace where the CR is created. This name may need to be overridden if the chart is taking over a cluster that had been previously created with a different name.
@henryzhangsta PTAL
**Checklist:**
> ceph: Instructions for taking over management of the cluster CR with the cluster helm chart

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-filesystem-crd.md
Move MDS related information from the Cluster to the Filesystem document.
Document how resource requests influence Ceph configuration keys.
Resolves #
**Checklist:**
> docs: clarify resource documentation

- pkg/operator/ceph/cluster/osd/spec.go
The active osd container was always using `/var/lib/rook` for the configuration of the OSD. If the `dataDirHostPath` is anything other than the default, the config would show up in the wrong place. Changing this back to the `dataDirHostPath` does not appear to affect any upgrade scenarios as the activate container will simply start extracting the config to the correct place.
**Checklist:**
> ceph: Activate osd container should use correct dataDirHostPath

- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/config.go
- pkg/operator/ceph/object/health.go
- pkg/operator/ceph/object/s3-handlers.go
- pkg/operator/ceph/object/user/controller.go
For the TLS communication in AdminOps Api, httpclient is required and
filled with TLS certs. But it is set to nil pointer in `buckethealthchecker` and 
`cephobjectstoreuser`.
Thanks @Krast76 finding the issue even proposing the fix.
Resolves #8132
**Checklist:**
> ceph: initialise httpclient for bucketchecker and objectstoreuser

- pkg/operator/ceph/cluster/osd/spec.go
We have seen issues with fullchain.pem files containing one self-signed
certificate. At the same time, the failing configuration was not
providing any client certificates or keys.
The error from curl was `"self signed certificate in the chain"`.
The openssl binary is not available so we cannot even c_rehash the
certificate directory when using `--capath`, however this worked already
with a fully signed fullchain.pem along with a client certificate and
key. So we cannot only use `--cacert` which will break that use case.
This is becoming really obscur on why using `--cacert` solves this
problem. I just can't wait to use the `vault` binary, that's all I can
say... …
> ceph: use cacert if no client cert/key are present

- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/mon_test.go
When the mons are using the dataDirHostPath and not a volumeClaimTemplate, they need to be permanently assigned to a node. The node assignment was missing in stretch clusters when the dataDirHostPath was being used. This resulted in mons that were moving to other nodes for example during a node drain, which would cause the mon to lose its backing store.
**Checklist:**
> ceph: Mons in stretch cluster should be assigned to a node when using dataDirHostPath

- pkg/operator/k8sutil/network.go
- pkg/operator/k8sutil/network_test.go
In pkg/operator/k8sutil/network.go:ApplyMultus(), sort the string
annotations before applying them so that Rook will avoid the situation
where a Deployment or Pod will need updated repeatedly even when no
Multus network configuration has changed.
Resolves #
**Checklist:**
> core: sort multus annotation strings when applying

- .github/workflows/canary-integration-test-arm64.yml
this commit restrict canary integration arm64 test
to run on rook/rook only(not on forked).
Resolves #8163 
**Checklist:**
> ci: restrict canary integration arm64 to run on forked

- pkg/operator/ceph/csi/csi.go
- pkg/operator/ceph/csi/spec.go
- pkg/operator/ceph/operator.go
This commit moves SetParams and ValidateCSIParam func
into go routine/lock, since it modifies/reads global CSIParam
variable.
Resolves #
**Checklist:**
> ceph: read and validate CSI params in Go routine

- pkg/util/exec/exec.go
In e8f9cfcb714685d93017be279d9ffdfc3847acca, the logging was replaced by
Debug which is probably a mistake given the intent of the commit to
enable debug logging on the prepare job.
However, this code is only triggered when running a ceph-osd with the
rook binary, so we must run Info and run Debug since Debug is not
activated.
Resolves #
**Checklist:**
> ceph: run CLI output with Info logging

- cluster/charts/rook-ceph/values.yaml
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
The operator has very bursty behavior while it is reconciling, then has much lower resource requirements. We increase the memory limits to 512Mi and reduce the requests to 128Mi. When not reconciling, the background health operations are much less resource demanding.
@leseb Before we merge this, even better if we can reduce the memory requirements when the object store reconcile is bursting. Any quick fixes you can think of there? All the parallel ceph pool commands cause the memory spike.
**Checklist:**
> ceph: set example memory requests and limits on the operator

- .github/workflows/build.yml
- .github/workflows/canary-integration-test.yml
- .github/workflows/integration-test-cassandra-suite.yaml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-nfs-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
this commit enable tmate session for every ci failure
with 120min timeout.
Resolves #
**Checklist:**
> ci: set tmate for 120min in case of ci failure

- pkg/operator/ceph/cluster/rbd/config.go
- pkg/operator/ceph/controller/mirror_peer.go
- pkg/operator/ceph/file/mirror/config.go
- pkg/operator/ceph/pool/config.go
- pkg/operator/ceph/pool/config_test.go
We know append additional information to the rbd-mirror bootstrap peer
token. It is useful for disaster recovery scenario where the other
cluster is reading the peer token and needs to know the pool_id as well
as the namespace.
Resolves #
**Checklist:**
> ceph: append additional info in the rbd-mirror bootstrap peer token

- pkg/operator/ceph/cluster/cleanup.go
The `break` statement is not necessary, especially since we don't want
to break out of the outerloop.
Resolves #
**Checklist:**
> ceph: fix ineffective break statement

- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
The topology spread constraint example allowed scheduling even if the TSC could not be satisfied when scheduling the osd prepare jobs. This could lead to unevenly spread OSDs especially when the cluster was not using the zone labels. Now the topology will be required for scheduling, to ensure proper spread of the OSDs.
**Checklist:**
> ceph: Update cluster-on-pvc example for proper OSD scheduling

- .github/workflows/stale.yaml
Running the stale workflow is a waste of resources.
Signed-off-by: Sebastian Wagner <sewagner@redhat.com>
See #8168 for a similar PR
Resolves #
**Checklist:**
> ci: disable stale workflow on forks

- pkg/operator/ceph/config/livenessprobe.go
When the Operator set the livenessProbe of the POD, it overwrote the contents of the shared desiredProbe.
Therefore, the wrongly configured livenessProbe was applied to other PODs, resulting in a CrashLoop.
In this PR, I created another instance to avoid overwriting the desiredProbe.
Closes: https://github.com/rook/rook/issues/8196
Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>
Resolves #8196
**Checklist:**
> ceph: fix overwriting shared livenessProbe

- .github/workflows/integration-tests-on-release.yaml
this commit downgrades minikube version
from release test for helm suite as
test are failing.
closes: https://github.com/rook/rook/issues/8202
Resolves #8202 
**Checklist:**
> ci: downgrade minikube version from helm suite

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
When the cluster is external we don't have any instances of rgw running
so let's not have this as a required field in the spec.
Resolves #
**Checklist:**
> ceph: do not require rgw 'instances' spec

- pkg/operator/ceph/cluster/predicate.go
If the CephCluster CR is updated let's cancel any on-going
orchestration. This will handle the situation where the spec is
misconfigured and OSD are crashlooping.
Prior to this patch, we would have to wait for the provisioning to
timeout, which will leave the cluster in a bad state for 10min or more.
Now the CR changes are picked up right away and the OSDs will deploy
normally.
Resolves #
**Checklist:**
> ceph: cancel on-going orchestration on any CR update

- Documentation/ceph-common-issues.md
- pkg/daemon/ceph/osd/daemon.go
- pkg/daemon/ceph/osd/daemon_test.go
- pkg/util/sys/device.go
- pkg/util/sys/device_test.go
Ceph bluestore raw disks can sometimes appear as though they have Atari
(AHDI) partitions on them. If a disk has Atari partitions, we just
ignore them as though they don't exist. This should be a safe assumption
since the hardware was last manufactured in 1992 and likely can't run
Kubernetes.
If we don't ignore the Atari partitions, Rook can create a new OSD on a
disk that is already running an OSD, corrupting the first and possibly
also the latest OSD. This can happen an arbitrary number of times per
disk.
Resolves #7940 
**Checklist:**
> ceph: ignore atari partitions when provisioning OSDs

- .github/workflows/canary-integration-test.yml
The ceph-mgr needs some time to come up so we need to wait for an IP
address to be available.
Closes: https://github.com/rook/rook/issues/8126
(cherry picked from commit ba04b3eeef90e7b8490d6fd2bf34641cfd6430d4)
Resolves #
**Checklist:**
[skip ci]
> ci: wait for the ceph-mgr IP to be available

- pkg/operator/ceph/file/mds/config.go
- pkg/operator/ceph/file/mds/spec.go
earlier, for mds, when resource limit is not defined it has
default limit of `"mds_cache_memory_limit": "4294967296"`
even if resouce.request is defined.
Now, resource request will be given preference when both
request and limit is defined and if only limit is defined
it will be applied or otherwise.
Resolves #8143 
**Checklist:**
> ceph: give resource request preference for mds_cache_memory_limit

- pkg/operator/ceph/pool/controller.go
- pkg/util/exec/exec.go
Let's not look at misleading errors if the operator is still initializing.
Resolves #
**Checklist:**
> ceph: silence harmless errors

- pkg/operator/ceph/csi/betav1csidriver.go
- pkg/operator/ceph/csi/csidriver.go
- pkg/operator/ceph/csi/spec.go
Update the CSIDriver object to v1 from betav1 as it will be
deprecated in v1.19+ and become unavailable from v1.22+
Signed-off-by: Yug <yuggupta27@gmail.com>
Resolves #7020 
**Checklist:**
> ceph: update CSIDriver object from betav1 to v1

- pkg/operator/k8sutil/k8sutil.go
The info log is rather verbose with all the filtering of the K8s version
like the following:
```
2021-07-01 21:54:36.383925 I | op-k8sutil: returning version v1.19.0 instead of v1.19.0+43983cd
```
**Checklist:**
> ceph: Debug log the k8s version instead of info

- cmd/rook/ceph/operator.go
- cmd/rook/rook/rook.go
- pkg/operator/ceph/object/objectstore.go
when operator pod resources are set(which are
default in case of helm), operator pod are
killed due to using concurrency while creating
object store.
Co-authored-by: Sébastien Han <seb@redhat.com>
this commit checks if operator resources are set
or not. if set then we'll *not* create object store
in concurrency or if not set then we'll create in
concurrency.
Resolves #8149 
**Checklist:**
> ceph: operator pod killed due to resource limit

- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/controller/controller_utils.go
If the reconcile is cancelled due to a CR update, we want to retry the next reconcile immediately rather than wait for the exponential backoff timeout if the reconcile was already failing. The wait can easily be minutes if the reconcile was in this state, which makes it appear the operator is ignoring the request to start a new reconcile.
Resolves #7872 
**Checklist:**
> ceph: Retry reconcile immediately after cancellation

- pkg/daemon/ceph/client/mirror.go
- pkg/daemon/ceph/client/mirror_test.go
- pkg/daemon/ceph/client/pool.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
- pkg/operator/ceph/pool/validate.go
- pkg/operator/ceph/pool/validate_test.go
The PR disables mirroring on a pool when PoolSpec.Mirroring.Enabled
is set to false
When `Mirroring.Mode == pool`
- remove cluster peer
- disable mirroring on the pool.
When `Mirroring.Mode == image`
-  Add warning for the user to disable mirroring manually for the images
Stop the mirroring health checker goroutine 
Reset the mirroring health check status in the CR. 
Resolves #
**Checklist:**
> ceph: ability to disable pool mirroring

- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/bucket/provisioner.go
The debug for adminOps client can be enabled by setting `Debug` flag.
In this PR, it is enabled for OBC and cephobjectstore not healthchecker.
Also add similar changes while calling `NewS3Agent` in the bucket
provisioner code path.
Resolves #
**Checklist:**
> ceph: enable debug for adminops client if the rook loglevel <= debug

- tests/integration/ceph_helm_test.go
The helm tests frequently hit an issue with the admission controller. The admission controller is also enabled in other test suites, so it seems safe enough to disable for the helm test suite.
For example in [this test](https://github.com/rook/rook/runs/2974651548?check_suite_focus=true), the helm test failed here:
```
Error: Internal error occurred: failed calling webhook "cephcluster-wh-rook-ceph-admission-controller-helm-ns.rook.io": Post "https://rook-ceph-admission-controller.helm-ns.svc:443/validate-ceph-rook-io-v1-cephcluster?timeout=5s": dial tcp 10.109.33.128:443: connect: connection refused: exit status 1
2021-07-02 18:07:29.220846 E | testutil: could not install helm chart with name : rook-ceph-cluster, namespace: helm-ns  - . coalesce.go:199: …
```
> ceph: Run helm tests without admission controller

- pkg/operator/ceph/nfs/nfs.go
When scaling down the nfs deployment gracefully, the wrong error code was checked,
resulting in a failed scaling down even though the condition was expected.
Now we check properly if the deployment was removed properly.
Resolves #8231 
**Checklist:**
> ceph: Scaling down nfs deployment was failing

- pkg/operator/ceph/object/bucket/provisioner.go
- pkg/operator/ceph/object/bucket/util.go
Currently `setObjectStorePort()` queries port from RGW service and
picks up the first port from the list, other places of the code
prefers for TLS, if it is enabled so for OBC's we end up having
`https` endpoint with non-secure port.
Fixes: #8141
**Checklist:**
> ceph: fetch rgw port from cephobjectstore crd for obc

- cluster/charts/rook-ceph-cluster/templates/deployment.yaml
adds a default empty dict for the network when deciding whether toolbox
should also be on the host network to catch the case when the entire
`network` block is empty
Resolves #8251
**Checklist:**
> ceph: network configuration should be optional in Helm chart

- pkg/operator/ceph/object/s3-handlers.go
- tests/framework/clients/object.go
- tests/framework/clients/object_user.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.5.go
- tests/integration/ceph_base_object_test.go
- tests/scripts/github-action-helper.sh
Extend the object store smoke test to include TLS configurations.
Fixes: #7695
Resolves #
**Checklist:**
> test: ci test for TLS objectstore

- cluster/charts/rook-ceph-cluster/values.yaml
ci is complaining due to empty field in
values.yaml with error
```
coalesce.go:199: warning: destination for config is a table. Ignoring non-table value <nil>
```
this commit make those field empty map/list.
Closes: https://github.com/rook/rook/issues/8239
Resolves #8239 
**Checklist:**
> ci: in helm chart field should not be empty

- pkg/daemon/ceph/client/mirror.go
- pkg/daemon/ceph/client/mirror_test.go
- pkg/daemon/ceph/client/pool.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
- pkg/operator/ceph/pool/validate.go
- pkg/operator/ceph/pool/validate_test.go
This PR is for backporting 8215 to release-1.6
The PR disables mirroring on a pool when PoolSpec.Mirroring.Enabled
is set to false
- disable mirroring on the pool for `Mirroring.Mode == pool`
- Add warning for the user to disable mirroring manually for `Mirroring.Mode == image`
- Stop the mirroring health checker goroutine
- Reset the mirroring health check status in the CR.
(cherry picked from commit 05b0ae09bbb449e1e7594998649d1ca474109280)
Resolves #
**Checklist:**
> ceph: add ability to disable mirroring

- pkg/operator/ceph/disruption/clusterdisruption/pools.go
It's better to create PDB of RGW if ObjectStore's `instances` field is 2. In the current implementation, at least three desired RGW instances are needed to create this. If `instances` is 1, we can still safely skip the creation of PDB because it's useless.
**Checklist:** …
> ceph: fix pdb of RGW instances

- pkg/operator/ceph/controller/object_operations.go
- pkg/operator/ceph/object/bucket/rgw-handlers.go
- pkg/operator/ceph/object/health.go
- pkg/operator/ceph/object/user/controller.go
Prior to that the access and secret keys were left empty if the user
already existed, which led to updating the secret with empty values when
the operator restarts.
Resolves #
**Checklist:**
> ceph: always rehydrate the access and secret keys

- pkg/operator/ceph/object/admin_test.go
- pkg/operator/ceph/object/user/controller.go
The CephClusterSpec was missing from the object context, so the check
for the network provider in RunAdminCommandNoMultisite() was not
discovering the network property correctly.
Resolves #
**Checklist:**
> ceph: add missing spec to the object context

- cluster/charts/rook-ceph-cluster/templates/serviceaccount.yaml
- cluster/charts/rook-ceph-cluster/values.yaml
Allow to specify imagePullSecrets to pull operator/ceph images from private registry
Resolves #
**Checklist:**
> rook: Add image pull secrets option on new helm cluster

- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
"/dev/" is only mounted on OSD on device. However, this directory should also be mounted on OSD on LV-backed PVC.
Resolves #8264
**Checklist:**
- [o] Reviewed …
> ceph: mount dev directory in lvm mode osd on  osd on lv-backed pvc

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-upgrade.md
- cluster/charts/rook-ceph-cluster/values.yaml
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster-external-management.yaml
- cluster/examples/kubernetes/ceph/cluster-on-local-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-stretched.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/olm/ceph/assemble/metadata-common.yaml
- design/ceph/ceph-cluster-cleanup.md
- images/ceph/Makefile
- pkg/apis/ceph.rook.io/v1/types.go
The latest pacific release is 16.2.5 so we set this as the default for Rook to deploy.
**Checklist:**
> ceph: Update default ceph image to latest v16.2.5

- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
when osd pods removed, they are not able
to add back due to missing `ceph auth`
or different `ceph auth`.
this commit mounts the secret `rook-ceph-admin-keyring`
inside the osd activate initcontainer which has
admin keyring.
Resolves #4238
**Checklist:**
> ceph: create new keyring for osd

- pkg/daemon/ceph/client/command.go
- pkg/daemon/ceph/client/command_test.go
- pkg/daemon/ceph/client/info.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/cluster/mgr/spec_test.go
- pkg/operator/ceph/object/admin.go
We now pass the networking spec to the clusterInfo so that the executor
can make the right decision on how to execute a command.
This is a small change that allows us to remove the CephBlockPool CR
since it's checking for rbd images. On a Multus deployment, the operator
does not have the network annotations, thus has no access to the OSD
network then rbd commands are hanging forever.
**Checklist:**
> ceph: proxy rbd commands when multus is enabled

- Documentation/ceph-cluster-crd.md
- PendingReleaseNotes.md
- cluster/examples/kubernetes/ceph/cluster-stretched-aws.yaml
- pkg/daemon/ceph/client/mon.go
- pkg/daemon/ceph/client/mon_test.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/mon.go
- pkg/operator/ceph/cluster/mon/spec.go
The mon daemon in a stretch cluster now can have its location set as a CLI param instead of setting it with a separate command. This enables mon failover to set the location of a mon immediately when it is joining quorum instead of having a delayed command to set the location.
**The mon is not yet joining quorum with these changes, still testing**
**Checklist:**
> ceph: Set the location on the mon daemon for stretch clusters

- cmd/rook/ceph/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr.go
- pkg/operator/ceph/cluster/mgr/mgr_test.go
- pkg/operator/ceph/cluster/mgr/spec.go
- pkg/operator/ceph/version/version_test.go
When there are multiple mgr daemons, the mgr sidecar owns reconciling the services for the active mgr. However, for efficiency the sidecar only reconciles the services if the active mgr changes. Now the operator will also reconcile the mgr services to ensure that services are re-created after being deleted, or otherwise in an incorrect state.
Resolves #8321 
**Checklist:**
> ceph: Reconcile mgr services with every reconcile

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/charts/rook-ceph/templates/clusterrolebinding.yaml
- cluster/charts/rook-ceph/templates/role.yaml
- cluster/charts/rook-ceph/templates/rolebinding.yaml
Operator can run on a namespace not named rook-ceph
The ClusterRoleBinding muste rely on .Release.Namespace helm value
Also move the ClusterRole and ClusterRoleBinding in appropriate yaml file
Resolves #
**Checklist:**
> ceph: create rook-ceph-system ClusterRoleBinding in operator namespace

- pkg/operator/ceph/object/health.go
- tests/framework/installer/ceph_manifests.go
- tests/framework/installer/ceph_manifests_v1.6.go
- tests/integration/ceph_base_file_test.go
- tests/integration/ceph_upgrade_test.go
With v1.7 approaching, the upgrade integration test will now test from v1.6.x to the latest master, which will effectively become the v1.7 release soon.
Updating the upgrade test for the next release is so much simpler these days!
**Checklist:**
> ceph: Test upgrades from v1.6 to master

- .github/workflows/integration-tests-on-release.yaml
The minimum K8s version for v1 CRDs is 1.16. Since support for v1beta1 cassandra and nfs was removed and only v1 is supported, the CI will now only run back to 1.16 for those providers.
With the merge of #8326 the release notes were already updated with the new min version supported, the master/release CI update was just missed.
**Checklist:**
> build: Min version for cassandra and nfs tests is k8s 1.16

- cluster/charts/rook-ceph-cluster/templates/role.yaml
- cluster/charts/rook-ceph-cluster/templates/rolebinding.yaml
- cluster/charts/rook-ceph-cluster/templates/serviceaccount.yaml
- cluster/charts/rook-ceph/templates/role.yaml
- cluster/charts/rook-ceph/templates/rolebinding.yaml
- cluster/charts/rook-ceph/templates/serviceaccount.yaml
- cluster/examples/kubernetes/ceph/common-second-cluster.yaml
- cluster/examples/kubernetes/ceph/common.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
Currently ceph osd purge job rely on rook-ceph-system service account which is only created on the rook operator namespace
When multiple clusters are deployed on distinct namespace the ceph osd purge failed to run as the service account is not available
Creating a specific service account rook-ceph-purge-osd with appropriate rights on each cluster namespace and operator namespace to still manage case where cluster is installed along side the operator
Resolves #
**Checklist:**
> ceph: define specific ServceAccount/RBAC for ceph osd purge job

- pkg/operator/ceph/cluster/crash/reconcile.go
- pkg/operator/ceph/cluster/mon/drain.go
- pkg/operator/ceph/cluster/mon/drain_test.go
- pkg/operator/ceph/disruption/clusterdisruption/add.go
- pkg/operator/ceph/disruption/clusterdisruption/osd.go
- pkg/operator/ceph/disruption/clusterdisruption/osd_test.go
- pkg/operator/ceph/disruption/clusterdisruption/pools.go
- pkg/operator/ceph/disruption/clusterdisruption/reconcile.go
- pkg/operator/ceph/disruption/clusterdisruption/static_pdb.go
- pkg/operator/k8sutil/k8sutil.go
This commit update the PodDisruptionBudget policy to use version v1
Updated to policy/v1 as policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+
Closes: https://github.com/rook/rook/issues/7917
Resolves #
**Checklist:**
> ceph: update PodDisruptionBudget from v1beta1 to v1

- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/deployment.yaml
- pkg/daemon/ceph/client/filesystem.go
- pkg/operator/ceph/file/filesystem.go
- pkg/operator/ceph/file/filesystem_test.go
Multiple filesystems are supported as of the Ceph Pacific release. So we
remove the flag from the operator configuration and just have a ceph
version check instead.
The Operator configuration option `ROOK_ALLOW_MULTIPLE_FILESYSTEMS`
has been removed in favor of simply verifying the Ceph version is
at least Pacific.
Multiple filesystems are stable since Ceph Pacific.
So users who had `ROOK_ALLOW_MULTIPLE_FILESYSTEMS` enabled will
need to update their Ceph version to Pacific.
Closes: #7183
**Checklist:**
> ceph: remove operator config `ROOK_ALLOW_MULTIPLE_FILESYSTEMS`

- pkg/operator/ceph/cluster/crash/reconcile.go
- tests/framework/utils/k8s_helper.go
The v1beta1 cronjob is deprecated and needs to use v1 for K8s 1.16 and newer. This is just one remaining place in the integration tests to fix since #8114. 
**Checklist:**
> ceph: Update test to watch for v1 cronjob instead of v1beta1

- go.mod
- go.sum
- pkg/operator/ceph/object/admin_mock.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/dependents.go
- pkg/operator/ceph/object/dependents_test.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/object/user/controller_test.go
Since the mock client was added to the rgw/admin package from the
go-ceph project in https://github.com/ceph/go-ceph/pull/532 we can now
mock the HTTP client and validate the entire reconcile.
Resolves #
**Checklist:**
> ceph: mock object store user create

- tests/scripts/build-release.sh
in pr 8328, function call was missing
so action for pushing the image is not
starting.
Resolves #
**Checklist:**
> ci: missing function call in script

- pkg/operator/ceph/object/dependents_test.go
This is what happens when you merge without rebasing onto master
first...
MockExecuteCommandWithOutputFile is gone in
https://github.com/rook/rook/pull/8351 but
https://github.com/rook/rook/pull/8353 was merged before and
https://github.com/rook/rook/pull/8351 should have been rebased first.
Resolves #
**Checklist:**
> ceph: remove non-existing mock

- .mergify.yml
The mergify bot now has rules for backporting to the release-1.7 branch. Backporting to 1.3 is no longer needed, so we can remove that backport rule.
While we're at it, the cassandra and ceph PRs already had the label added automatically, now the nfs PRs will also have a label added.
**Checklist:**
> build: Add release-1.7 mergify backport rule

- .github/workflows/integration-test-cassandra-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
The cassandra integration tests expect a tag of `rook/cassandra:master` instead of the version tag from the release builds.
**Checklist:**
****
> cassandra: Tests should just use master tag instead of version tag

- .github/workflows/integration-tests-on-release.yaml
The integration test actions were not running on the release branch or tags due too restrictive of a condition. 
Already merged to release-1.7 with #8374 
**Checklist:**
> build: Run integration tests on release branch and tags

- .github/workflows/push-build.yaml
- tests/scripts/build-release.sh
The tagged builds will run git checkout on the correct tag, though the publish and promote actions expect a branch name to be available due to internal build assumptions. Now the publish looks up the branch name from the tag and passes it to the publish command as expected.
Resolves #8378 
**Checklist:**
> build: Publish and promote with correct branch name

- .github/workflows/push-build.yaml
The unshallow step in the action is replaced now with the fetch-depth: 0 option on the checkout@v2 action.
**Checklist:**
> build: unshallow not needed with fetch-depth 0

- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
When changing the settings for the Rook mon health check (.spec.healthCheck.mon) in the CephCluster resource, the mon health check isn't reconfigured with the new values
Updated checkHealth goroutine so it can also updates the new patched values
Closes: https://github.com/rook/rook/issues/8363
Resolves #
**Checklist:**
> ceph: updated mon health check goroutine for reconfiguring patch values

- cluster/charts/rook-ceph/templates/clusterrole.yaml
- cluster/examples/kubernetes/ceph/common.yaml
Since we changed the Rook orchestrator module for Ceph, it now has to access Storage Classes and Persistent Volumes in the cluster to gather inventory and create OSDs so we have to make changes to the rook-ceph-mgr-cluster role so the orchestrator has permission to access these resources.
Resolves #
**Checklist:**
> ceph: update rook-ceph-mgr-cluster role rules to include PV and SC

- .github/workflows/build.yml
- .github/workflows/canary-integration-test-arm64.yml
- .github/workflows/canary-integration-test.yml
- .github/workflows/codegen.yml
- .github/workflows/codespell.yaml
- .github/workflows/crds-gen.yml
- .github/workflows/golangci-lint.yaml
- .github/workflows/integration-test-cassandra-suite.yaml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-nfs-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- .github/workflows/mod-check.yml
- .github/workflows/unit-test.yml
- .github/workflows/yaml-lint.yaml
- tests/scripts/build-release.sh
- tests/scripts/github-action-helper.sh
The build version should be detected with the git describe command, but if the VERSION var is already set, it will be used instead of being detected from git. During the official builds or even local builds, we just want to use the git version instead of 0.
Since the conversion to the github actions, this version was preventing the proper publish of the helm charts. 
**Checklist:**
> build: Detect git version instead of setting to 0

- .github/workflows/build.yml
- .github/workflows/canary-integration-test-arm64.yml
- .github/workflows/canary-integration-test.yml
- .github/workflows/codegen.yml
- .github/workflows/codespell.yaml
- .github/workflows/crds-gen.yml
- .github/workflows/golangci-lint.yaml
- .github/workflows/integration-test-cassandra-suite.yaml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-nfs-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- .github/workflows/mod-check.yml
- .github/workflows/unit-test.yml
- .github/workflows/yaml-lint.yaml
- tests/scripts/build-release.sh
- tests/scripts/github-action-helper.sh
The build version should be detected with the git describe command, but if the VERSION var is already set, it will be used instead of being detected from git. During the official builds or even local builds, we just want to let the makefile detect the git version.
The full git history is added to enable proper detection of the version. Without the full history only a hash is returned for the version, which then results in an invalid semantic version error for the helm chart.
**Checklist:**
> build: Detect git version correctly instead of setting to 0 (backport #8408)

- tests/framework/installer/ceph_installer.go
- tests/integration/ceph_mgr_test.go
**Enable again the mgr test:**
- Now is more reliable and robust the start of the test.
- Minor fixes to adapt the <service ls>  to the new name of the crash daemon
deployed by rook
- The creation of OSDs is disabled in the orchestrator, so i have removed
this test until we will have the functionality ready again in the orchestrator
part
My plan is to provide in the orchestrator two different ways to create OSDs:
- Creation of OSD using specific devices if discovery daemon is running
- Creation of OSds using PVS (if we have LSO/other LS operator running)
**Checklist:**
- [x ] Integration tests have been added, if necessary.
> ceph: enable again the Rook orchestrator mgr test

- .github/workflows/canary-integration-test.yml
- Documentation/ceph-pool-crd.md
- Documentation/ceph-rbd-mirror-crd.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/examples/kubernetes/ceph/pre-k8s-1.16/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
- pkg/daemon/ceph/client/mirror.go
- pkg/operator/ceph/cluster/rbd/config.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
- pkg/operator/ceph/pool/peers.go
Instead of having the `MirroringPeerSpec` in the RBDMirror CRD we want
to move it on the CephBlockPool CRD so that each pool can have its own peer.
This enables pool to re-use an existing peer secret if it points to the
same cluster peer.So we don't need to duplicate secret peer anymore.
Also, added a deprecation warning if user tries to import the peer tokens via
RDBMirror CRD. 
Resolves #
**Checklist:**
> ceph: add mirroring peer specification to CephBlockPool CRD

- Documentation/ceph-monitoring.md
- Documentation/ceph-upgrade.md
Add sections to docs to mention updating ancillary resources, of which
monitoring is the only one currently.
Fixes #7750
We could consider 
**Checklist:**
> docs: update ancillary resources (monitoring)

- .github/workflows/integration-tests-on-release.yaml
As long as we support back to k8s 1.11, the flex suite should run on that release. This only applies to the release-1.7 branch.
**Checklist:**
> ceph: Run flex suite on K8s 1.11

- Documentation/ceph-block.md
- Documentation/helm-ceph-cluster.md
- cluster/charts/rook-ceph-cluster/templates/_helpers.tpl
- cluster/charts/rook-ceph-cluster/templates/cephblockpool.yaml
- cluster/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
- cluster/charts/rook-ceph-cluster/templates/cephobjectstore.yaml
- cluster/charts/rook-ceph-cluster/templates/configmap.yaml
- cluster/charts/rook-ceph-cluster/templates/deployment.yaml
- cluster/charts/rook-ceph-cluster/templates/ingress.yaml
- cluster/charts/rook-ceph-cluster/values.yaml
- tests/framework/installer/ceph_helm_installer.go
- tests/framework/installer/ceph_installer.go
- tests/framework/installer/ceph_settings.go
…
Signed-off-by: Tom Hellier <me@tomhellier.com>
This commit adds an ingress resource to the rook-ceph-cluster helm chart, allowing ingress to the ceph-dashboard service. It also adds the ability to define the various storage types that
you can run on ceph inside kubernetes.
Resolves #8384 
**Checklist:**
> ceph: Add additional helm chart functionality for ingresses and defining the ceph storage crds

- .github/workflows/canary-integration-test.yml
- pkg/daemon/ceph/osd/kms/kms.go
- pkg/daemon/ceph/osd/kms/kms_test.go
- pkg/daemon/ceph/osd/kms/vault_api.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
- tests/manifests/test-kms-vault-spec.yaml
- tests/scripts/deploy-validate-vault.sh
Rook will now auto detect the kv version of the vault server. This
allows users not having to pass the VAULT_BACKEND configuration in the
CephCluster CR.
Resolves #
**Checklist:**
> ceph: auto detect vault k/v version

- .github/workflows/canary-integration-test.yml
- pkg/daemon/ceph/osd/kms/kms.go
- pkg/daemon/ceph/osd/kms/kms_test.go
- pkg/daemon/ceph/osd/kms/vault_api.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
- tests/manifests/test-kms-vault-spec.yaml
- tests/scripts/deploy-validate-vault.sh
Rook will now auto detect the kv version of the vault server. This
allows users not having to pass the VAULT_BACKEND configuration in the
CephCluster CR.
(cherry picked from commit 99e00dea1ed6dcf185246ef6ceac4e6a9b21ee84)
Resolves #
**Checklist:**
> ceph: auto detect vault k/v version (backport #8265) 

- .github/workflows/canary-integration-test.yml
- Documentation/ceph-pool-crd.md
- Documentation/ceph-rbd-mirror-crd.md
- PendingReleaseNotes.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/examples/kubernetes/ceph/pre-k8s-1.16/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
- pkg/daemon/ceph/client/mirror.go
- pkg/operator/ceph/cluster/rbd/config.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
- pkg/operator/ceph/pool/peers.go
Instead of having the RBDMirroringPeerSpec in the RBDMirror CRD we want
to move it on the CephBlockPool CRD so that each pool can have its own peer.
This enables pool to re-use an existing peer secret if it points to the
same cluster peer.So we don't need to duplicate secret peer anymore.
(cherry picked from commit 3b50f5fd007157941ab8508655269e3634ce04da)
Resolves #
**Checklist:**
> ceph: add mirroring peer specification to CephBlockPool CRD (backport #8380)

- Documentation/ceph-advanced-configuration.md
- Documentation/ceph-cluster-crd.md
- Documentation/ceph-common-issues.md
- Documentation/ceph-configuration.md
- cluster/charts/rook-ceph-cluster/values.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/filesystem.yaml
- cluster/examples/kubernetes/ceph/object-ec.yaml
- cluster/examples/kubernetes/ceph/object-openshift.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- cluster/examples/kubernetes/ceph/pool.yaml
- pkg/daemon/ceph/client/filesystem.go
- pkg/daemon/ceph/client/upgrade.go
- pkg/daemon/ceph/client/upgrade_test.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/cluster/version_test.go
- pkg/operator/ceph/version/version_test.go
References to luminous and mimic, and unnecessary references to nautilus were found in the docs that have been cleaned up and clarified. At the same time, the tests are updated to use more recent versions.
Resolves #8409 
**Checklist:**
> ceph: Remove old references to luminous and mimic versions

- Documentation/ceph-osd-mgmt.md
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/osd/remove.go
Sometimes we want to investigate a PVC for removed OSD.
**Checklist:**
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull …
> ceph: add an option to preserve pvc in osd purge job

- Makefile
- build/crds/build-crds.sh
- build/makelib/common.mk
- build/makelib/helm.mk
- build/sed-in-place
- cluster/olm/ceph/generate-rook-csv-templates.sh
- cluster/olm/ceph/generate-rook-csv.sh
- images/ceph/Makefile
- images/nfs/Makefile
If a user were to `make build` Rook, and after the Ceph CSV was
generated and before make had finished, the Rook repo would be left with
changes caused by the build modifying files temporarily in-place.
All CSV template generation in the Ceph makefile is now self-contained
and can be configured to operate outside of the main repo so that files
are not modified in-place.
In-place modification of files was also incorrect. On Mac some files
with `-e` trailing were left, and in-place backups were also present in
the form `<filename>''`. Therefore, also fix the generation to fix
in-place modifications.
Resolves #
**Checklist:**
> build: stage CSV files into tmp while building

- go.mod
- go.sum
- pkg/operator/ceph/object/admin.go
- pkg/operator/ceph/object/bucket/provisioner.go
The go-ceph library has removed the `Debug` field from the API type in
https://github.com/ceph/go-ceph/pull/543. Since the HTTP Client can be
mutated we now have our own client to dump requests and responses when
the operator log level is DEBUG.
**Checklist:**
> ceph: change the debug implementation of the admin ops API

- Documentation/ceph-upgrade.md
A few small updates to the upgrade guide:
- Update docs to point to quay for ceph images
- No need for drive groups instructions
- PreserveUnknownFields upgrade issue should not be there anymore
**Checklist:**
> docs: Upgrade guide cleanup of previous release upgrade issues

- Documentation/ceph-upgrade.md
Recently, images moved from docker.io to quay.io so people using main
major tag like `v16` needs to switch to use the quay.io URL.
Resolves #
**Checklist:**
> docs: add note about new container image location 

- .github/workflows/canary-integration-test.yml
- pkg/daemon/ceph/client/filesystem_mirror.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/mirror/config.go
- pkg/util/retry.go
Trying to disable mirroring on a cluster where mirroring is not enabled
results in an error during upgrades. Let's catch this error and ignore
it.
Funny enough the exec error resembles to:
```
Error ENOTSUP: Module 'mirroring' is not enabled (required by command 'fs snapshot mirror disable'): use `ceph mgr module enable mirroring` to enable it: exit status 95
```
So we get ENOTSUP which is 45 but exit status 95...
Closes: #8438
Resolves #8438
**Checklist:**
> ceph: ignore errors when mirroring is not enabled on the filesystem

- Documentation/ceph-cluster-crd.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster-on-local-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
earlier, we had the issue for osd placement regarding
whether we should merge the placements or not.
Now, we have option `skipApplyAllPlacement` to
enable/disable osd placement. By default it is false
which means it will merge both placement.All() and
storageClassDeviceSets.Placement, when true
it will only apply storageClassDeviceSets.Placement.
Also, adding unit test.
Closes: https://github.com/rook/rook/issues/8135
Resolves #8135 
**Checklist:**
> ceph: add an option to enable/disable merge all placement

- .github/workflows/integration-tests-on-release.yaml
K8s 1.11 cannot run on the github action because it is so old and unsupported. K8s 1.11 has been validated with Jenkins for the v1.7 release with #8481 and does not have a need to run it regularly in every release as it is deprecated. The flex suite still runs on 1.15 and newer so the risk of regression is very small.
**Checklist:**
> build: Remove 1.11 from flex suite test action

- pkg/daemon/ceph/client/mirror.go
- pkg/daemon/ceph/client/mirror_test.go
Do not point to a made-up file in /tmp
Use ioutil.TempFile() for creating a token file
Closes: https://github.com/rook/rook/issues/8446
Resolves #
**Checklist:**
> ceph: use mktemp file in ImportRBDMirrorBootstrapPeer

- build/makelib/golang.mk
till now we were using older go fmt version(1.11).
From now, go fmt version will be same as golang version
Resolves #
**Checklist:**
> build: update go fmt version

- tests/scripts/gen_release_notes.sh
this commit include script which will help
the person who is creating release note
to get all the pr number with title and owner
in required order. In the past, it was manual
step.
Resolves #
**Checklist:**
> ceph: Get PR title and user info for release notes

- cluster/examples/kubernetes/ceph/cluster-on-local-pvc.yaml
`cluster-on-local-pvc.yaml` doesn't work due to missing topologyKey. In addition, it's better to add the example of `topologySpreadConstraints` for K8s >= 1.18 users.
Resolves #8478 
**Checklist:** …
> ceph: fix example of cluster on local pvc

- Documentation/ceph-cluster-crd.md
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster-on-local-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/rook.io/v1/types.go
- pkg/operator/ceph/cluster/osd/osd_test.go
- pkg/operator/ceph/cluster/osd/provision_spec.go
- pkg/operator/ceph/cluster/osd/spec.go
- pkg/operator/ceph/cluster/osd/spec_test.go
earlier, we had the issue for osd placement regarding
whether we should merge the placements or not.
Now, we have option `skipApplyAllPlacement` to
enable/disable osd placement. By default it is false
which means it will merge both placement.All() and
storageClassDeviceSets.Placement, when true
it will only apply storageClassDeviceSets.Placement.
Also, adding unit test.
Closes: https://github.com/rook/rook/issues/8135
(cherry picked from commit 98383133989b41dfd4b998dfaa5ce64fcde81b8c)
Resolves #
**Checklist:**
> ceph: add an option to enable/disable merge all placement (backport #8381) 

- Documentation/helm-ceph-cluster.md
- Documentation/helm.md
With the v1.7 release and the Cluster helm chart, this clarifies that the helm charts are still completely optional, but are intended only to simplify deployment for those who choose to use them.
**Checklist:**
> docs: Clarify that helm charts are optional

- cmd/rook/ceph/operator.go
- pkg/operator/ceph/cluster/mon/health.go
- pkg/operator/ceph/cluster/mon/health_test.go
I don't know why these flags are there but it's not like we run the
operator with them and with a different value.
So removing for clarity.
Resolves #
**Checklist:**
> ceph: Remove unused mon timeout cli flags

- pkg/operator/ceph/client/controller.go
- pkg/operator/ceph/cluster/controller.go
- pkg/operator/ceph/cluster/rbd/controller.go
- pkg/operator/ceph/cr_manager.go
- pkg/operator/ceph/disruption/clusterdisruption/add.go
- pkg/operator/ceph/disruption/machinedisruption/add.go
- pkg/operator/ceph/disruption/machinelabel/add.go
- pkg/operator/ceph/file/controller.go
- pkg/operator/ceph/file/mirror/controller.go
- pkg/operator/ceph/nfs/controller.go
- pkg/operator/ceph/object/controller.go
- pkg/operator/ceph/object/realm/controller.go
- pkg/operator/ceph/object/user/controller.go
- pkg/operator/ceph/object/zone/controller.go
- pkg/operator/ceph/object/zonegroup/controller.go
- pkg/operator/ceph/pool/controller.go
Let's initialize the schemes in a single place instead of doing it
when each controller initializes.
Resolves #
**Checklist:**
> ceph: move scheme initialization to the same place

- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
Kubernetes 1.22 version didn't support
certificates.k8s.io v1beta1 version
reverting the k8s 1.22 version to 1.21
till the certificates.k8s.io #[8364](https://github.com/rook/rook/pull/8364) Pr
didn't get completed
so the CI can run successfully
Resolves #
**Checklist:**
> ci: CephSmokeSuite test run on kubernetes 1.21

- tests/framework/installer/ceph_manifests.go
- tests/integration/ceph_base_object_test.go
Integration test CephSmokeSuite fails frequently
A quick fix for it by reordering storeName, running tlsteststore before teststore
Closes: https://github.com/rook/rook/issues/8309
Resolves #
**Checklist:**
> ci: fix for CephObjectStores flakiness

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/examples/kubernetes/ceph/object.yaml
- design/ceph/object/store.md
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/object/config.go
- pkg/operator/ceph/object/spec.go
- pkg/operator/ceph/object/spec_test.go
Specify ca Bundle for RGW spec and mount inside pods.
Related-Issue: https://github.com/rook/rook/issues/8490
Resolves #
**Checklist:**
> ceph: add ability to specify ca bundle for rgw

- .github/workflows/canary-integration-test.yml
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- cluster/examples/kubernetes/ceph/object-multisite-pull-realm-test.yaml
- cluster/examples/kubernetes/ceph/object-multisite-pull-realm.yaml
- cluster/examples/kubernetes/ceph/object-multisite-test.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- tests/scripts/github-action-helper.sh
This test:
- starts up 2 minikube clusters
- create 2 ceph clusters
- creates object multisite CRDs on each cluster and
syncs the clusters
- writes an object to cluster 1 and reads it on
cluster 2
This commit also adds new functions in
github-action-helper.sh that aid in the multisite
test and the multi cluster mirroring test.
Resolves #
**Checklist:**
> ceph: RGW multisite integration testing

- .github/workflows/create-tag.yaml
we need to validate create tag action
so that only authorized users can trigger
that action.
[skip-ci]
Resolves #
**Checklist:**
> ci: validate user before creating tag

- build/makelib/golang.mk
Print the Go version when running any Go build target. This can be
helpful in making sure that we are building with the Go version we want
and expect.
Resolves #
**Checklist:**
> build: print go version when building

- images/cross/Dockerfile
Rook CephObjectStore S3 connections may be affected by CVE-2021-34558.
This is fixed in Go v1.16.6, so we update to the latest Go version
available to ensure this is fixed in future builds.
Resolves #
**Checklist:**
> build: use latest golang v1.16.7 (Go CVE-2021-34558)

- images/nfs/Dockerfile
Signed-off-by: Oleksii Kravchenko <kamikaze.ua@gmail.com>
We start to use NFS rook operator a few weeks ago and were faced with the issue when NFS server was killed by OOM under the heavy load. Adding more memory didn't help. So I checked nfs-ganesha changelog for OOM fixes and found issue related to our problem https://github.com/nfs-ganesha/nfs-ganesha/issues/116. It was merged in the recent version. Upgrade nfs-ganesha to 3.5 version completely resolves high memory consumption.
Resolves #
**Checklist:**
> nfs: upgrade nfs-ganesha to 3.5 version

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
Resolves #8550 
**Checklist:**
> ceph: make storage device config nullable

- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
Since core->v1 (https://pkg.go.dev/k8s.io/api/core/v1),  serviceAccountName is the correct key in the pod spec. 
Ref# https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
https://docs.openshift.com/container-platform/3.11/rest_api/core/podtemplate-core-v1.html
Resolves #
**Checklist:**
> ceph: use serviceAccountName as the key in ceph csi templates

- .github/workflows/build.yml
- .github/workflows/integration-test-cassandra-suite.yaml
- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-nfs-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
reduce tmate timeout to 60 for the pull_request event.
Resolves #
**Checklist:**
> ci: reduce tmate timeout to 60

- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-tests-on-release.yaml
- design/ceph/admission-controller.md
- tests/scripts/deploy-validate-vault.sh
- tests/scripts/generate-tls-config.sh
- tests/scripts/github-action-helper.sh
This commit update the certificates.k8s.io to use version v1
Updated to v1 as v1beta1 certificates.k8s.io is deprecated in v1.19+
Closes: https://github.com/rook/rook/issues/8308
Resolves #
**Checklist:**
> ceph: update CSR from v1beta1 to v1

- build/crds/build-crds.sh
- cluster/charts/rook-ceph/templates/resources.yaml
to use prerelease of kubernetes it requires
to have `-0` added in kubernetes version check
ex:
```{{- if semverCompare ">=1.16.0-0" .Capabilities.KubeVersion.GitVersion }}```
ref: https://github.com/helm/helm/issues/3810
Closes: https://github.com/rook/rook/issues/8548
Resolves #8548 
**Checklist:**
> ceph: add `-0` for helm k8s version check

- pkg/operator/ceph/csi/betav1csidriver.go
- pkg/operator/ceph/csi/csidriver.go
- pkg/operator/ceph/csi/spec.go
This PR fixes the below items
* fix panic in reCreateCSIDriverInfo
Initialize the client and the csidriver object before calling the reCreateCSIDriverInfo function.
* Reuse defined csiDriver object
reuse already defined csiDriver object instead of referring to the method receiver
* fix logging of csidriver
log the successful message about starting CSIDriver after creating the daemonset and deployment objects.
Note: the issue was reported at slack https://rook-io.slack.com/archives/CK9CF5H2R/p1629776387282600
Resolves #
**Checklist:**
> ceph: fix panic when recreating the csidriver object

- pkg/daemon/ceph/client/config.go
- pkg/operator/ceph/cluster/cephstatus.go
- pkg/operator/ceph/cluster/cephstatus_test.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/config/monstore.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
The mon config had two different implementations that have evolved over the lifetime of the project. This is a simple refactor to remove the SetConfig() option and stick with the MonStore as a single implementation for updating the mon store.
Resolves #8107 
**Checklist:**
> ceph: Consolidate the calls to set mon config

- pkg/daemon/ceph/client/upgrade.go
- pkg/daemon/ceph/client/upgrade_test.go
This handles the scenario where the OSDs have been created but not yet
started due to a wrong CR configuration.
For instance, when OSDs are encrypted and Vault is used to store
encryption keys, if the KV version is incorrect during the cluster
initialization the OSDs will fail to start and stay in CLBO until the
CR is updated again with the correct KV version so that it can start.
For this scenario, if the CRUSH map has no host registered yet it's fair
to assume the initialization broke and we need to fix it. So when don't
need to call ok-to-stop since it will always fail and eventually force
pass but let's not wait for nothing.
Resolves #
**Checklist:**
> ceph: do not check ok-to-stop when OSDs are in CLBO

- pkg/operator/ceph/file/controller.go
When mirroring is enabled on the filesystem, the status was not being set on the filesystem. Now the reconcile will ensure the status is updated on the CR whether or not mirroring is enabled.
**Checklist:**
> ceph: Set the filesystem status when mirroring not enabled

- .github/workflows/canary-integration-test.yml
- pkg/daemon/ceph/client/pool.go
- pkg/operator/ceph/cluster/mgr/dashboard.go
- pkg/operator/ceph/csi/peermap/config.go
- pkg/operator/ceph/csi/peermap/config_test.go
- pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
- pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
- pkg/operator/ceph/object/objectstore.go
- pkg/operator/ceph/operator.go
- pkg/operator/ceph/pool/controller.go
- pkg/operator/ceph/pool/controller_test.go
- pkg/operator/k8sutil/deployment.go
- pkg/util/file.go
During disaster recovery/migration of a cluster, as part of the failover, the
kubernetes artifacts like deployment, PVC, PV, etc will be restored to a new
cluster by the admin. Even if the kubernetes objects are restored the
corresponding RBD/CephFS subvolume cannot be retrieved during CSI operations as
the clusterID and poolID are not the same in both clusters
See ceph-csi [design](https://github.com/ceph/ceph-csi/blob/devel/docs/design/proposals/clusterid-mapping.md) for more details.
This PR creates a mapping between Cluster ID and RBD Pool ID between
local cluster and peer cluster.
TODO
Resolves #
**Checklist:**
> ceph: add ClusterID and PoolID mappings between local and peer cluster

- cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
As `exec` is an internal builtin function for python2 there were some errors thrown while running the script with python2.
Changed the variable name to `execErr`.
Resolves #
**Checklist:**
> Making script backward compatible with python2

- pkg/apis/rook.io/v1/placement.go
- pkg/apis/rook.io/v1/placement_test.go
- pkg/operator/ceph/cluster/osd/spec.go
earlier, `ApplyToPodSpec()` was only taking one toleration and ignoring
tolerations from `placement.ALL()`.
this commit merge toleration for Mgr,Mon,Osd pod
example, for osd it will merge
spec.placement.all and
storageDeviceClassSets.Placement(in case of pvc) or
spec.placement.osd(in case of non-pvc's).
(cherry picked from commit e1f232eeb7ac716e53ec27912ac0556062085a83)
Resolves #
**Checklist:**
> ceph: merge toleration for osd/prepareOSD pod if specified both places

- pkg/operator/k8sutil/resources.go
- pkg/operator/k8sutil/resources_test.go
If we call OwnerInfo.SetOwnerReference for an object multiple times, it results in OwnerReference duplication.
**Checklist:**
> ceph: avoid duplicate ownerReferences

- Documentation/ceph-advanced-configuration.md
- tests/scripts/auto-grow-storage.sh
When an OSDs reach OSD_NEARFULL state, we have to manually either increase the volume claim for provisioning more storage or add more OSDs to the cluster to keep the cluster Healthy.
1) If you need to automatically increase the provisioned volume(scale OSDs vertically).
Added a script auto-grow-storage.sh which will automatically increase claim volume, depending on the percent growth rate mentioned.
2)  If you need to automatically increase the number of OSDs(scale OSDs Horizontally).
Added a script auto-grow-storage.sh which will automatically increase the OSDs of a device set, depending on the Count you mentioned. 
Closes: https://github.com/rook/rook/issues/6101
Tested on different scenarios:
For scaling vertically:
i) When the increment …
> ceph: auto grow OSDs size on PVCs

- build/run
removing unused var which was making push build
action to fail due set -u which was added recently.
Closes: https://github.com/rook/rook/issues/8616
Resolves #8616 
**Checklist:**
> ci: build failed due unbound var

- images/cross/run.sh
Fixes issues with the `build/run` tooling, notably for publishing images
where `build/run make <args>` would only result in `make` being called
without args.
Resolves #
**Checklist:**
> build: fix cross build run script

- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/watcher.go
See commits.
Resolves #
**Checklist:**
> ceph: avoid multiple reconciles of ceph cluster

- cmd/rook/ceph/osd.go
- pkg/daemon/ceph/osd/daemon.go
- pkg/operator/ceph/cluster/osd/status.go
- pkg/operator/ceph/cluster/osd/status_test.go
The error message in UpdateNodeStatus regards the second argument
as node name. However, it is a PVC name in OSD on PVC.
**Checklist:**
> ceph: fix error message in UpdateNodeStatus

- Documentation/ceph-cluster-crd.md
- Documentation/ceph-mon-health.md
- cluster/charts/rook-ceph-cluster/values.yaml
- cluster/charts/rook-ceph/templates/resources.yaml
- cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
- cluster/examples/kubernetes/ceph/cluster.yaml
- cluster/examples/kubernetes/ceph/crds.yaml
- pkg/apis/ceph.rook.io/v1/cluster.go
- pkg/apis/ceph.rook.io/v1/cluster_test.go
- pkg/apis/ceph.rook.io/v1/types.go
- pkg/operator/ceph/cluster/cluster.go
- pkg/operator/ceph/cluster/cluster_test.go
- pkg/operator/ceph/cluster/mon/health.go
While an even number of mons can cause lower availability of mon quorum, it also can provide higher durability for the cluster. Mon quorum can be restored from a single mon according to the disaster recovery guide, so there may be scenarios where an even number of mons may be preferable.
Reverts the check for an even number of mons added in #6420.
**Checklist:**
> ceph: Allow an even number of mons

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
The updated query will work for single mon deployment and will work better for deployments with five or more mons.
Resolves #8156
**Checklist:**
[skip ci]
> ceph: fix CephMonQuorumAtRisk Alert Query

- .github/workflows/integration-test-flex-suite.yaml
- .github/workflows/integration-test-helm-suite.yaml
- .github/workflows/integration-test-mgr-suite.yaml
- .github/workflows/integration-test-multi-cluster-suite.yaml
- .github/workflows/integration-test-smoke-suite.yaml
- .github/workflows/integration-test-upgrade-suite.yaml
With the -failfast flag the tests will not continue when one of them
fails. This allows us to log in the runner and observe the exact state
of any failure.
The flag can be activated via a label "ci-fail-fast" in the PR.
Resolves #
**Checklist:**
> ci: add failfast go flag to stop tests sooner (optional)

- pkg/operator/ceph/pool/controller.go
The ceph-block-pool controller was missing the network spec from the
cephcluster that contains all the details about networking.
Resolves #
**Checklist:**
> ceph: fix pool deletion when running on multus

- pkg/util/sys/device.go
Sometimes the error does not tell much, so as `exit status 1` and
printing the output along returning the error is useful.
For instance, I saw a job failing with no osd and the prepare job had
those lines:
```
exec: Running command: lsblk /dev/sdb1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
inventory: skipping device "sdb1". exit status 1
```
We need to understand more about the lsblk issue.
Resolves #
**Checklist:**
> ceph: print the output on errors

- pkg/operator/ceph/cluster/mon/spec.go
correct typo in logging, it was showing `ok-to-stop`
instead of `ok-to-continue` when 'continueUpgradeAfterChecksEvenIfNotHealthy' is true
Co-Authored-by: Zeaone <zeaone@ZeaonedeMacBook-Pro.local>
Resolves #
**Checklist:**
> ceph: modify the log info when ok to continue fails

- cluster/charts/rook-ceph-cluster/templates/ingress.yaml
Kubernetes cluster versions 1.22+ must use the v1 Ingress version.
Signed-off-by: Bryton Hall <email@bryton.io>
Resolves #
**Checklist:**
> ceph: add networking.k8s.io/v1 Ingress chart compatability

- cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Add hostname to CephOSDCriticallyFull and CephOSDNearFull rules's expr
When the alarm is triggered, the hostname field does not appear in the notification message 
Resolves #
**Checklist:**
> ceph: fix CephOSDCriticallyFulla and CephOSDNearFull Alert Query

- .github/workflows/canary-integration-test.yml
- Documentation/ceph-common-issues.md
- Documentation/ceph-upgrade.md
- tests/scripts/github-action-helper.sh
- tests/scripts/validate_cluster.sh
We should not use .items[0].metadata.name if the array length is 0. This
is the case when nothing has been initialized yet. Instead, we should
use .items[*].metadata.name, the wildcard ensures to always return 0
even if nothing is present yet.
Fixes: https://github.com/rook/rook/issues/8676
Resolves #
**Checklist:**
> ci: fix pod list

- Documentation/ceph-cluster-crd.md
- design/ceph/storage-class-device-set.md
fixed the incorrect indentation for topologyKey
in ceph-cluster-crd doc and storage-class-device-set doc
Co-authored-by: Fabio Nitto
Refer: https://github.com/rook/rook/pull/8123
Resolves #
**Checklist:**
> docs: correct indentation for topologyKey

- cluster/examples/kubernetes/ceph/images.txt
- images/ceph/Makefile
create file tests/scripts/rook-ceph-image.txt which
will have list of images required for offline installation.
Closes: https://github.com/rook/rook/issues/6406
Resolves #6406 
**Checklist:**
> ci: image list for offline installation

- Documentation/ceph-monitoring.md
- Documentation/ceph-quickstart.md
- Documentation/ceph-toolbox.md
- Documentation/ceph-upgrade.md
- cluster/examples/kubernetes/ceph/direct-mount.yaml
- cluster/examples/kubernetes/ceph/images.txt
- cluster/examples/kubernetes/ceph/operator-openshift.yaml
- cluster/examples/kubernetes/ceph/operator.yaml
- cluster/examples/kubernetes/ceph/osd-purge.yaml
- cluster/examples/kubernetes/ceph/toolbox-job.yaml
- cluster/examples/kubernetes/ceph/toolbox.yaml
- tests/scripts/github-action-helper.sh
With the Ceph patch release we set the example manifests versions to v1.7.3
Resolves #
**Checklist:**
> build: Update the release version to v1.7.3

- Documentation/development-flow.md
Emphasize unit tests in the development guide, and provide guidelines to
help contributors create good unit tests.
Also clarify that Rook's CI will run integration tests and that users
aren't expected to run integration tests locally.
Resolves #
**Checklist:**
> docs: emphasize unit tests in development guide

- .commitlintrc.json
- Documentation/development-flow.md
With the storage providers moved to their own repo, we add more possible prefixes for commits to the ceph operator, including the ceph daemons and csi driver.
**Checklist:**
> bot: Add more ceph commit prefixes

- cluster/examples/kubernetes/ceph/images.txt
- images/ceph/Makefile
it has happened more than once that the manifests do not
reflect the images so now reading from `pkg/operator/ceph/csi/spec.go`
as this what code uses.
Closes: https://github.com/rook/rook/issues/8687
Resolves #
**Checklist:**
> build: use pkg/operator/ceph/csi/spec.go for csi images

- Documentation/ceph-pool-crd.md
- Documentation/ceph-rbd-mirror-crd.md
- Documentation/ceph-upgrade.md
Add a section to the upgrade doc instructing users to (and how to)
migrate `CephRBDMirror` `peers` spec to individual `CephBlockPools`.
Adjust the pending release notes to refer to the upgrade section now,
and clean up a few references in related docs to make sure users don't
miss important documentation.
Resolves #
**Checklist:**
> docs: ceph: add peer spec migration to upgrade doc

- pkg/operator/ceph/disruption/clusterdisruption/osd.go
- pkg/operator/ceph/disruption/clusterdisruption/osd_test.go
Rook checks for down OSDs by checking the `ReadyReplicas` count
in the OSD deployement. When an OSD pod goes into CBLO due to
disk failure, there is a delay before this `ReadyReplicas` count
becomes 0. The deplay is very small but may result in rook missing
OSD down event. As a result no blocking PDBs will be created and
only default PDB with `AllowedDisruptions` count as 0 is available.
This PR tries to solve this. The OSD pdb reconciler will be
reconciled again if `AllowedDisruptions` count in the main
PDB is 0.
Resolves #
**Checklist:**
> ceph: reconcile osd pdb if allowed disruption is 0

- Documentation/ceph-fs-mirror-crd.md
The steps to configure the peers are detailed in the CephFilesystem
section. Only the CephFilesystem is holding the peer configuration, not
the CephFilesystemMirror which only controls the bootstrap of the
daemon.
Resolves #
**Checklist:**
> doc: fix cephfs-mirror documentation

- cluster/examples/kubernetes/ceph/cluster-test.yaml
- tests/framework/installer/ceph_installer.go
Let's force v16.2.5 since the CI is broken with 16.2.6. This gives us
time to continue to merge work and work on fixing deployments with
16.2.6 in parallel.
Resolves #
**Checklist:**
> ci: force a particular ceph version

- tests/integration/ceph_base_deploy_test.go
- tests/integration/ceph_flex_test.go
- tests/integration/ceph_helm_test.go
- tests/integration/ceph_mgr_test.go
- tests/integration/ceph_multi_cluster_test.go
- tests/integration/ceph_object_test.go
- tests/integration/ceph_smoke_test.go
- tests/integration/ceph_upgrade_test.go
The `*SuiteMinimalTestVersion` vars in
`tests/integration/ceph_base_deploy_test.go` are no longer needed with
Jenkins no longer being used. Remove them.
Resolves #
**Checklist:**
> test: remove unused minimal test versions
