rook/rook

tests/integration/ceph_mgr_test.go

Explicitly set the length of the string parameter in json.Unmarshal method
fixes: https://github.com/rook/rook/issues/8669

ceph: fix probable cause of intermittent fails in the manager test

---

pkg/operator/ceph/object/admin.go
pkg/operator/ceph/object/controller.go
pkg/operator/ceph/object/controller_test.go
pkg/operator/ceph/object/rgw.go

If the CephObjectStore health checker fails to be created, return a
reconcile failure so that the reconcile will be run again and Rook will
retry creating the health checker. This also means that Rook will not
list the CephObjectStore as ready if the health checker can't be
started.
Resolves #
**Checklist:**

ceph: retry object health check if creation fails

---

pkg/operator/ceph/cluster/mgr/spec.go

When private/public network have been defined in the Ceph rook cluster it is not
possible to configure properly the ip address of the liveness probe
for the manager.
Changes in the manager in Pacific introduced this regression.
This change replaces the http probe by a command probe, avoiding thus to
determine what is going to be the ip address of the manager before launching
the pod.
Resolves: https://github.com/rook/rook/issues/8510

ceph: do not use http for mgr liveness probe

---

pkg/operator/ceph/object/admin.go
pkg/operator/ceph/object/objectstore.go
pkg/operator/ceph/object/user.go
tests/scripts/github-action-helper.sh

If the cluster where the rgw is started is secondary and not primary,
trying to create the admin ops user will fail with:
```
Please run the command on master zone.
Performing this operation on non-master zone
leads to inconsistent metadata between zones
```
So we need to force the creation regardless, it is fine the creation will
return UserAlreadyExist and then we just read the current user.
Closes: https://github.com/rook/rook/issues/8671
Resolves #
**Checklist:**

rgw: do not create the rgw ops user on the secondary cluster

---

.github/workflows/canary-integration-test.yml
Documentation/ceph-cluster-crd.md
Documentation/ceph-upgrade.md
cluster/charts/rook-ceph-cluster/values.yaml
cluster/examples/kubernetes/ceph/cluster-external-management.yaml
cluster/examples/kubernetes/ceph/cluster-on-local-pvc.yaml
cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
cluster/examples/kubernetes/ceph/cluster-stretched.yaml
cluster/examples/kubernetes/ceph/cluster-test.yaml
cluster/examples/kubernetes/ceph/cluster.yaml
cluster/examples/kubernetes/ceph/images.txt
cluster/olm/ceph/assemble/metadata-common.yaml
design/ceph/ceph-cluster-cleanup.md
images/ceph/Makefile
pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/file/filesystem.go
pkg/operator/ceph/file/filesystem_test.go
pkg/operator/ceph/file/mds/mds.go
pkg/operator/ceph/file/mds/spec_test.go
pkg/operator/ceph/object/user.go
tests/framework/installer/ceph_installer.go
tests/integration/ceph_base_file_test.go

This is a backport of https://github.com/rook/rook/pull/8743.
Resolves #
**Checklist:**

ceph: use next ceph v16.2.6 pacific version (backport #8743)

---

pkg/operator/ceph/object/admin.go
pkg/operator/ceph/object/controller.go
pkg/operator/ceph/object/controller_test.go
pkg/operator/ceph/object/rgw.go

If the CephObjectStore health checker fails to be created, return a
reconcile failure so that the reconcile will be run again and Rook will
retry creating the health checker. This also means that Rook will not
list the CephObjectStore as ready if the health checker can't be
started.
Resolved backport conflicts in the below files:
pkg/operator/ceph/object/controller.go
- revert monitoring routine struct change from 1.7 to master
pkg/operator/ceph/object/controller_test.go
- use master branch's rearchitected test harness
(cherry picked from commit 5383ba2df2c159619bcb925880c2c7ff01fb28ca)
backport of #8708
Resolves #
**Checklist:**

ceph: retry object health check if creation fails (backport #8708)

---

Documentation/ceph-csi-drivers.md
pkg/operator/ceph/csi/spec.go
pkg/operator/ceph/csi/version.go
pkg/operator/ceph/csi/version_test.go

With the release of Ceph CSI 3.4.0, Ceph CSI project came up
with a new support policy where we support only versions >= 3.3.0
The supported window of Ceph CSI versions is known as "N.(x-1)":
(N (Latest major release) . (x (Latest minor release) - 1)).
For example, if Ceph CSI latest major version is 3.4.0 today,
support is provided for the versions above 3.3.0.
If users are running an unsupported Ceph CSI version, they will be
asked to upgrade when requesting support for the cluster.
This PR lift the minimum supported version of Ceph CSI to 3.3.0
in this repo.
Fix https://github.com/rook/rook/issues/8709
Ref #
https://github.com/ceph/ceph-csi/releases/tag/v3.4.0
https://github.com/ceph/ceph-csi/#known-to-work-co-platforms
NOTE:  Kept `minimum` and `releasev330` vars eventhough both …

ceph: lift minimum supported version of ceph csi to v3.3.0

---

pkg/operator/ceph/object/status.go

There was a log line that informed that the object store status would
not be updated because the status was deleting erroneously. Move the
line to the correct position.
Resolves #
**Checklist:**

rgw: fix misleading log line in rgw health checker

---

pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml

Like RBD, the CephFS provisioner pod need not run as privileged. as it's not doing any operation like plugin pods which does mounting and unmounting removing the permissions for the same.
Resolves #
**Checklist:**

ceph: modify CephFS provisioner permission

---

tests/scripts/github-action-helper.sh

We just need to wait a little for the object to be replicated to the
other gateway. A simple retry solves this.
Closes: https://github.com/rook/rook/issues/8671
Resolves https://github.com/rook/rook/issues/8671
**Checklist:**

ci: fix multisite test

---

tests/framework/installer/ceph_helm_installer.go
tests/framework/installer/ceph_installer.go
tests/framework/installer/ceph_manifests.go
tests/framework/installer/installer.go
tests/framework/installer/settings.go
tests/integration/ceph_flex_test.go
tests/integration/ceph_helm_test.go
tests/integration/ceph_mgr_test.go
tests/integration/ceph_multi_cluster_test.go
tests/integration/ceph_object_test.go
tests/integration/ceph_smoke_test.go
tests/integration/ceph_upgrade_test.go
tests/scripts/github-action-helper.sh

The integration tests must always be run against the local build of rook, and an image should never be pulled from dockerhub. To prevent pulling a release or master tag, the local build will use a tag specific to the build and not ever published elsewhere.
This was first merged to release-1.7 with #8780 so it could be tested where we were seeing the issue with tests not matching the build. Now we cherry-pick to master.
**Checklist:**

test: Run all integration tests against the local build

---

cluster/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
cluster/charts/rook-ceph-cluster/values.yaml

Added the configuration for the default filesystem storageclass in the helm chart.
This is a backport of #8771 since the bot didn't pick it up.
**Checklist:**

ceph: Add default field to filesystem-sc helm chart (backport #8771)

---

pkg/operator/ceph/object/bucket/provisioner.go
pkg/operator/ceph/object/health.go
pkg/operator/ceph/object/s3-handlers.go
tests/integration/ceph_object_test.go

If the region is specified in the storage class of OBC, use that in the
newS3agent() than using constant "us-east-1".
Resolves #
**Checklist:**

ceph: pass region to newS3agent()

---

pkg/util/exec/exec.go
pkg/util/exec/exec_test.go

In ExtractExitCode, there is one error type that can be valid as a
pointer or not-as-a-pointer. Add a case to the type check for the
non-pointer condition.
Resolves #8280
Resolves #
**Checklist:**

core: add missing error type check to exec

---

Documentation/ceph-upgrade.md
cluster/examples/kubernetes/ceph/cluster.yaml
images/ceph/Makefile

The previous base image in use by rook `v16.2.6-20210916` disappeared from quay.io. The CI started failing in the past hour due to the previous image disappearing.
**Checklist:**

ceph: Pick up latest ceph base image 16.2.6-20210918

---

cluster/charts/rook-ceph-cluster/values.yaml
cluster/examples/kubernetes/ceph/cluster.yaml

Cephcluster have wrong indentation for examples yaml and helm
Updated the specs indentation the way it is present in types.go
Closes: https://github.com/rook/rook/issues/8800
Resolves #https://github.com/rook/rook/issues/8800
**Checklist:**

docs: updated correct indentation for Storage spec in Cephcluster

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules-external.yaml
cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

Due to the latest jsonnet and jsonnetfmt, v0.17.0, we have the
`description` and `message` lines format changed.
Resolves #
**Checklist:**

ceph: prometheus rules format changes

---

tests/scripts/validate_cluster.sh

Sometimes the CI needs more time...
Closes: https://github.com/rook/rook/issues/8825
Resolves #
**Checklist:**

ci: wait longer for csi to be available

---

PendingReleaseNotes.md
cluster/charts/rook-ceph-cluster/templates/deployment.yaml
cluster/examples/kubernetes/ceph/toolbox.yaml
cmd/rook/util/cmdreporter.go
cmd/rook/util/copybins.go
images/ceph/Dockerfile
pkg/daemon/util/cmdreporter.go
pkg/daemon/util/cmdreporter_test.go
pkg/daemon/util/copybins.go
pkg/daemon/util/copybins_test.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/cluster/osd/integration_test.go
pkg/operator/ceph/cluster/osd/provision_spec.go
pkg/operator/ceph/cluster/osd/spec.go
pkg/operator/ceph/cluster/osd/spec_test.go
pkg/operator/ceph/operator.go
pkg/operator/k8sutil/cmdreporter/cmdreporter.go
pkg/operator/k8sutil/volume.go

We don't need to use tini.
We don't have anything in the rook operator that would
either create zombie processes (no threads) or use
exec (to fork). The Go binary has a really good
signal handling mechanism.
Closes: https://github.com/rook/rook/issues/8794
Resolves #
**Checklist:**

ceph: stop using tini

---

Documentation/ceph-common-issues.md

The ceph common issue had a bad link to the advanced doc topic.
Resolves #8840
**Checklist:**

docs: Fix link to advanced documentation

---

.github/workflows/canary-integration-test.yml
.github/workflows/integration-test-helm-suite.yaml
.github/workflows/integration-test-mgr-suite.yaml
.github/workflows/integration-test-multi-cluster-suite.yaml
.github/workflows/integration-test-object-suite.yaml
.github/workflows/integration-test-smoke-suite.yaml
.github/workflows/integration-test-upgrade-suite.yaml
.github/workflows/integration-tests-on-release.yaml

run tmate only for `pull_request` event and
remove for other events. As during release
when tests fail it takes extra 30 min to fail the
test or someone manually has to end the test
which is painfully especially during release time.
Resolves #
**Checklist:**

ci: run tmate session only on PR

---

pkg/operator/ceph/controller/spec.go

The log collector was not responding to SIGINT or SIGTERM correctly
since the parent bash process did not have the job control functionality
enabled. Now any signal received on bash will exit the container
immediately.
Resolves #
**Checklist:**

ceph: add signal handling for log collector

---

cluster/examples/kubernetes/ceph/cluster-on-local-pvc.yaml

PV for mon must be a filesystem volume.
Resolves #8818
**Checklist:** …

docs: fix the example of local PVC based cluster

---

cluster/charts/rook-ceph-cluster/templates/role.yaml
cluster/charts/rook-ceph/templates/role.yaml
cluster/examples/kubernetes/ceph/common-second-cluster.yaml
cluster/examples/kubernetes/ceph/common.yaml

The purge osd job need to read and update persistentvolumeclaims
While the job doesn't failed with osd and deployments well deleted, the associated pvc is not deleted by the job as it failed to read it
**Checklist:**

ceph: add missing rights rook-ceph-purge-osd account

---

tests/integration/ceph_base_object_test.go
tests/integration/ceph_helm_test.go
tests/integration/ceph_object_test.go
tests/integration/ceph_smoke_test.go
tests/integration/ceph_upgrade_test.go

In general, make the output from the object store test easier to follow
and debug.
- Make sure assertions are associated with the appropriate subtest.
- Remove `t.Helper()` from complex helpers.
- Add info to log messages.
- Move long parts of (sub-)test names to log messages.
- Move some reused functions back to ceph_base_object_test.go
- Refactor runObjectE2ETestLite() to be suitable for use as the second
store created in the "run a second object store" test.
Resolves #
**Checklist:**

test: clean up object store tests

---

tests/integration/ceph_mgr_test.go

The `mgr host ls` looks like:
`"addr": "10.1.0.27/fv-az244-362", "hostname": "fv-az244-362"`
Previously, we were picking `addr` which contains both IP and hostname
where the k8snode has the hostname only. So let's use the Hostname from
the mgr command output instead.
Resolves #
**Checklist:**

ci: fix mgr test for host

---

.github/workflows/integration-tests-on-release.yaml

Since we were pointing at CephUpgradeSuite test only this was running
all the tests and thus some resources were created by other tests.
Let's just run the test we need.
Closes: https://github.com/rook/rook/issues/8843
Resolves #
**Checklist:**

ci: fix the test name for upgrade suite

---

pkg/operator/ceph/object/bucket/provisioner.go
pkg/operator/ceph/object/health.go
pkg/operator/ceph/object/rgw.go
pkg/operator/ceph/object/s3-handlers.go
pkg/operator/ceph/object/s3-handlers_test.go
tests/integration/ceph_base_object_test.go
tests/integration/ceph_object_test.go

We have seen cases where the signed certificate used for the RGW does not
contain the internal DNS endpoint, resulting in the health check to fail
since the certificate is not valid for this domain.
People consuming the gateways by external clients and for specific
domains do not necessarily have the internal DNS configured in the
certificate.
So let's be a bit more flexible and simply ensure a connectivity check
and bypass the certificate validation.
Closes: https://github.com/rook/rook/issues/8663
Resolves #
**Checklist:**

rgw: use insecure TLS for bucket health check

---

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py

If we call the script with --monitoring-endpoint
10.1.8.29,10.1.8.36,10.1.8.25, we need to parse each comma-separated
address and not the entire block.
Now each address is tested properly.
Resolves #
**Checklist:**

ceph: fix external script when passing monitoring list

---

pkg/daemon/ceph/client/command.go
pkg/daemon/ceph/client/command_test.go

When proxying commands to the cmd-proxy container we don't need to build
the command line with the same flags as the operator. The cmd-proxy
container does not use any ceph config file and just relies on the
CEPH_ARGS environment variable in the container. So passing the same
args as the operator causes to fail since we don't have a ceph config
file in `/var/lib/rook/openshift-storage/openshift-storage.config` thus
the remote exec fails with:
```
global_init: unable to open config file from search list ...
```
Resolves #
**Checklist:**

multus: do not build all the args to remote exec cmd

---

cluster/examples/kubernetes/ceph/images.txt
images/ceph/Makefile

While build.all we have race condition where
images.txt file was update with duplicate entries.
So, removing `-a` from 1st tee and also add `uniq` command
to confirm no duplicate entry is in the file.
Resolves #
**Checklist:**

build: update command to generate image list

---

pkg/daemon/ceph/osd/kms/vault.go
pkg/daemon/ceph/osd/kms/vault_test.go

Prior, we were returning a nil map and thus the assignment for forced
deletion was not working since we were trying to assign on a nil map.
Resolves #
**Checklist:**

ceph: do not fail on keys deletion

---

pkg/operator/ceph/object/objectstore.go
pkg/operator/ceph/object/objectstore_test.go
pkg/util/exec/exec_test.go
pkg/util/exec/test/mockexec.go

Rook should update the RGW object store's period if the period doesn't
yet exist. This protects us from the case where the
'radosgw-admin period update --commit` command fails and the
CephObjectStore controller reconciles again.
Resolves #
**Checklist:**

rgw: update period if period does not exist

---

cluster/charts/rook-ceph/templates/clusterrole.yaml
cluster/charts/rook-ceph/templates/clusterrolebinding.yaml
cluster/examples/kubernetes/ceph/common.yaml

Reduce the RBAC scope for the lib-bucket-provisioner to the minimum
necessary for Rook to operate with lib-bucket-provisioner. Comment the
RBAC so that users can make informed decisions about whether or not they
can remove the permissions for their uses.
Resolves #
**Checklist:**

rgw: reduce RBAC for lib-bucket-provisioner

---

pkg/operator/ceph/object/objectstore.go

Log as a debug message when the RGW period will be updated because it
does not exist.
Resolves #
**Checklist:**

rgw: add period does not exist debug message

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

Instead of using 'absent' query, we are trying to use 'up' which should
provide us with the needed 'namespace' field in the resultant metrics
Signed-off-by: aruniiird <amohan@redhat.com>
Resolves #
**Checklist:**

ceph: change CephAbsentMgr to use 'up' query

---

.github/workflows/build.yml
images/ceph/Makefile

Reading from a file, processing the file in a pipe, and outputting the
piped content to the same file can have undefined results, often leading
to an empty file. Use an intermediate temp file for generating the
offline image list.
I only observed the issue on MacOS, but it could effect linux as well if my understanding of the root cause is correct.
Resolves #
**Checklist:**

build: use intermediate tmp for offline image gen

---

.github/workflows/build.yml
.github/workflows/rbac-gen.yaml
Makefile
build/rbac/get-helm-rbac.sh
build/rbac/keep-rbac-yaml.py
build/rbac/rbac.yaml
tests/scripts/validate_modified_files.sh

This is a starting step to be able to generate common.yaml from Helm
charts. For right now, we merely want to be able to determine when the
rendered output of the Helm chart changes.
Resolves #
**Checklist:**

build: start tracking rbac generated from helm chart

---

.github/workflows/integration-test-mgr-suite.yaml

Let's run the test every day at midnight since the code is moving
fast and tends to fail. This gives us some time to fix the issues.
It can be triggered on PR too if the "run-mgr-suite" label is set.
Resolves #
**Checklist:**

ci: run the orch ceph manager test daily

---

Makefile

build: fix double include of build/makelib/helm.mk

---

.github/workflows/canary-integration-test.yml
tests/scripts/github-action-helper.sh

The canary tests were still picking up the tag from operator.yaml and toolbox.yaml instead of the new test local-build tag.
This is a follow-up from #8812 that already merged this fix to the release-1.7 branch to unblock those tests.
**Checklist:**

build: Run canary tests against the local-build tag

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

Adding the `namespace` field to other ceph alerts
Resolves #
**Checklist:**

ceph: adding 'namespace' field to the needed ceph queries

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

The following alerts,
CephMonHighNumberOfLeaderChanges
CephOSDDiskNotResponding
CephClusterWarningState
, which are resolved automatically, in most cases,
are causing unnecessary admin events. So we are increasing the
alert delay time to '15m'.
Resolves #
**Checklist:**

ceph: increasing the auto-resolvable alerts' delay to 15m

---

tests/integration/ceph_mgr_test.go

Sometimes the orch command fails with a timeout ... with this modification these commands are going to be retried.
This PR addresses the changes suggested in https://github.com/rook/rook/pull/8788
fixes: https://github.com/rook/rook/issues/8759

ceph: retry <ceph orch> commands when they fail

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

As 'CephMonHighNumberOfLeaderChanges' means there is a
multiple monitor election and indicate some communication
issue between the monitors. Increasing interval timing for
this alert is not considered as safe. So reverting this
change back to 5m
Resolves #
**Checklist:**

ceph: reverting the time delay of 'CephMonHighNumberOfLeaderChanges'

---

Documentation/ceph-csi-troubleshooting.md

this commit adds the doc which has the manual
steps to recover from the specific scenario
like
`on the node lost, the new pod can't mount the
same volume`.
Closes: https://github.com/rook/rook/issues/1507
Resolves #1507
**Checklist:**

docs: add doc to recover from pod from lost node

---

pkg/daemon/discover/discover.go

Closing stdoutPipe that could possibly
leaks memory due to unclosed resources.
Closes: https://github.com/rook/rook/issues/8914
Resolves #8914 
**Checklist:**

core:  close stdoutPipe for the discovery daemon

---

Documentation/ceph-upgrade.md

The cephfs csi volume plugin if restarted when host networking is not enabled will cause the volumes to hang. In Rook v1.6.0 - v1.6.4 host networking was not enabled by default, causing all cephfs volumes to hang during upgrade from those releases. A note is added to the upgrade guide [as requested](https://github.com/rook/rook/issues/8085#issuecomment-933440203) to help make this issue more visible.
Related to: #8085 
**Checklist:**

docs: Add node restart requirement for csi upgrade issue

---

cluster/charts/rook-ceph/values.yaml
cluster/examples/kubernetes/ceph/operator-openshift.yaml
cluster/examples/kubernetes/ceph/operator.yaml
cmd/rook/rook/rook.go
pkg/clusterd/context.go
pkg/daemon/ceph/client/config_test.go
pkg/operator/ceph/controller.go
pkg/operator/ceph/object/admin.go
pkg/util/logging.go
pkg/util/logging_test.go

Create a new log level for Rook that is hidden from users. This is the
most verbose log level, and it is the level developers would like to use
to get debug logs that are important for debugging but that could leak
senstivie information like credentials in production use.
If a user sets their debug level to "TRACE", they will merely get
"DEBUG" level logs. Only if they set "TRACE_INSECURE" will they get
trace logs, and those are likely to include insecure information. Rook
tries very hard not to leak sensitive information in logs even with
verbose "DEBUG" logs.
Resolves #8778
Resolves #
**Checklist:**

core: create TRACE_INSECURE log level

---

cluster/charts/rook-ceph/templates/resources.yaml
cluster/examples/kubernetes/ceph/crds.yaml
cluster/examples/kubernetes/ceph/object-ec.yaml
cluster/examples/kubernetes/ceph/object-openshift.yaml
cluster/examples/kubernetes/ceph/object.yaml
pkg/apis/ceph.rook.io/v1/types.go
pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
pkg/operator/ceph/config/livenessprobe.go
pkg/operator/ceph/config/livenessprobe_test.go
pkg/operator/ceph/object/spec.go
pkg/operator/ceph/object/spec_test.go
tests/integration/ceph_base_object_test.go

rgw doesn't respond `livenessProbe` if the number of connection reaches its limit (by default, 1000). Then rgw is out of service but still live. Hense the current `livenessProbe` logic is suitiable for `readinessProbe`. `tcpSocket` is enough for `livenessProbe`.
Remove rgw-multisite-test related code because this test doesn't exist in release-1.7 branch.
**Checklist:**
- [o] **Skip …

rgw: change the way to livenessProbe and introduce readinessProbe

---

pkg/daemon/ceph/client/mirror.go

The monitor list was not sorted, so each time we were reconciling, the
peer secret token will see its content updated with randomized
monitors. This would enter our predicate and trigger a reconcile.
Potentially an endless one, if the randomized list is already different.
Closes: https://github.com/rook/rook/issues/9076
Resolves https://github.com/rook/rook/issues/9076
**Checklist:**

rbd-mirror: use a sorted list for peer token content

---

pkg/operator/ceph/cluster/version.go
pkg/operator/ceph/cluster/version_test.go

In the event a ceph image is specified that is lower than the current running version of the daemons, the downgrade is allowed, even if not technically supported. All of the core daemons (mon,mgr,osd) were being downgraded, but the daemons for other controllers (rgw,mds,rbdmirror) were not being downgraded, resulting in an inconsistent cluster. Now we log that the downgrade is not supported and all all of the daemons to be downgraded.
Resolves #9097 
**Checklist:**

core: Allow downgrade of all daemons consistently

---

.github/workflows/create-tag.yaml

Add the workflow that allows us to create release tags to the
release-1.7 branch.
Resolves #
**Checklist:**

build: add create-tag workflow

---

tests/scripts/gen_release_notes.sh

Backport the tests/scripts/gen_release_notes.sh script to release-1.7
that is needed by the create-tag workflow.
Resolves #
**Checklist:**

build: backport gen_release_notes.sh script

---

.github/workflows/push-build.yaml

This reverts commit c53304c3b4f762488d8129cecc65282eaa612acc.
After experimenting with this release, we have found that the
`workflow_run` action source doesn't work for branches. The
documentation was updated with this PR and has more detail.
https://github.com/github/docs/pull/531
For now, we will revert back to using on.push.tags = ["v*"]
Resolves #
**Checklist:**

Revert "ci: trigger push build action after tag creation"

---

Documentation/ceph-kms.md
cmd/rook/secret.go
pkg/daemon/ceph/osd/kms/envs.go
pkg/daemon/ceph/osd/kms/envs_test.go
pkg/daemon/ceph/osd/kms/vault.go
tests/manifests/test-kms-vault-spec-k8s-auth.yaml
tests/scripts/deploy-validate-vault.sh

We can pass bound_service_account_names with a comma separated list of
service accounts. Let's do this instead of remapping new values.
Earlier, we thought a single service account could be added per Vault
role and we were using other variables like
`VAULT_AUTH_KUBERNETES_ROOK_OPERATOR_ROLE` that we were remapping to
`VAULT_AUTH_KUBERNETES_ROLE` internal for the API calls to Vault.
Resolves #
**Checklist:**

osd: use multiple service account for vault role

---

cluster/charts/rook-ceph/templates/resources.yaml
cluster/examples/kubernetes/ceph/crds.yaml
pkg/apis/ceph.rook.io/v1/types.go

The schema has a limit of nine data and nine coding chunks in an EC pool. More data chunks may be desired, even if not typically recommended due to the higher recovery cost. To allow for the higher chunks sizes if desired, we increase the limit.
Resolves #9106
**Checklist:**

pool: Allow more data chunks in an ec pool

---

Makefile
build/makelib/common.mk
build/makelib/golang.mk
build/makelib/helm.mk
build/release/Makefile
images/ceph/Makefile

We now build rook to build only for linux platforms and not darwin nor
windows anymore.
Resolves #
**Checklist:**

build: only produce binary for linux

---

.github/workflows/canary-integration-test.yml
PendingReleaseNotes.md
cluster/charts/rook-ceph/templates/deployment.yaml
cluster/examples/kubernetes/ceph/operator-openshift.yaml
cluster/examples/kubernetes/ceph/operator.yaml
cluster/examples/kubernetes/ceph/toolbox.yaml
images/ceph/Dockerfile
pkg/daemon/ceph/osd/kms/volumes.go
pkg/daemon/ceph/osd/kms/volumes_test.go
pkg/operator/ceph/webhook.go

The rook operator as well as the toolbox pod run with the "rook" user
with UID 2016. The UID was chosen based on the year of the initial
commit in the rook/rook repository.
No more root user running.
Closes: https://github.com/rook/rook/issues/8734
Resolves https://github.com/rook/rook/issues/8734
**Checklist:**

ceph: run operator with rook user

---

pkg/daemon/ceph/osd/remove.go
pkg/operator/ceph/cluster/osd/create.go
pkg/operator/k8sutil/job.go

When a reconcile is started for OSDs, the prepare jobs are first deleted from a previous reconcile. The timeout for the osd prepare job deletion was only 40s. After that timeout, the reconcile attempts to continue waiting for the pod, but of course will never complete since the OSD prepare was not running in the first place, causing the reconcile to wait indefinitely. In the reported issue, the osd prepare jobs were actually deleted successfully, the timeout just wasn't long enough. Pods need at least a minute to be forcefully deleted, so we increase the timeout to 90s to give it some extra buffer.
At the same time, if the osd prepare job deletion fails, we should treat it as a reconcile error instead of ignoring it.
As described in #8558, the operator log …

osd: Increase wait timeout for osd prepare cleanup

---

pkg/daemon/ceph/client/config.go

If the operator fails to create the operator's configuration directory
then we should fail the Operator.
Resolves #
**Checklist:**

core: fail if config dir creation fails

---

.github/workflows/daily-nightly-jobs.yml

They are no arm64 packages for ceph-nfs so we must skip this validation
for the nightly arm64 CI job.
Resolves #
**Checklist:**

ci: fix arm64 job

---

.github/workflows/canary-integration-test.yml
tests/scripts/deploy-validate-vault.sh

When requesting issuer, we run a local kubectl proxy command which spawn
a proxy server. However, we must wait for the proxy to be ready before
we actually start making requests to it.
Now the CI waits up to 10sec to retrieve the issuer.
Closes: #9090
Resolves https://github.com/rook/rook/issues/9090
**Checklist:**

ci: wait for kubeproxy to be ready

---

pkg/apis/ceph.rook.io/v1/scc.go

- Adds `AllowHostDirVolumePlugin` to the `go` representation of the rook-ceph SCC for using the hostPath. Also making it consistent with the yaml representation. 
- Removes unused import.
From Openshift [Docs](https://docs.openshift.com/container-platform/4.9/authentication/managing-security-context-constraints.html):
``` 
For backwards compatibility, the usage of allowHostDirVolumePlugin overrides settings in the volumes field. For example, if allowHostDirVolumePlugin is set to false but allowed in the volumes field, then the hostPath value will be removed from volumes.
```
Resolves #
**Checklist:**

core: add `AllowHostDirVolumePlugin: true` to SCC and remove unused imports

---

Documentation/ceph-object.md
PendingReleaseNotes.md
images/ceph/Dockerfile
images/ceph/Makefile
images/cross/Makefile

The toolbox can now interact with S3 gateways using the `s5cmd` tool.
The binary is only 12M so this does not add up too much to the operator
image size.
Closes: https://github.com/rook/rook/issues/4968
Resolves https://github.com/rook/rook/issues/4968
**Checklist:**

core: add s5cmd binary to operator image

---

cluster/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
cluster/charts/rook-ceph-cluster/values.yaml

The cluster helm chart missed adding the default setting for the volume expansion, so now we enable it by default.
Resolves #9120 
**Checklist:**

helm: Enable cephfs volume expansion by default

---

pkg/operator/ceph/object/rgw.go

The generation of the rgw deployment spec was swallowing errors if any issues are raised such as the tls cert not being found as expected in some configurations. We need to fail the reconcile so the error will be logged and the admin can identify the issue.
Resolves #9134 
**Checklist:**

rgw: Raise errors when rgw daemon fails to be created

---

Documentation/ceph-csi-drivers.md

Fixed the ephemeral link for the rbd pod. 
Fixes https://github.com/rook/rook/commit/dcf522c37d2148d973c3d52edf93ea3f473cf754#r60100703
**Checklist:**

doc: fix ephemeral link for rbd pod

---

Documentation/branch.liquid

With the recent rename of master docs to the latest docs, the links from the docs back to github need to be generated with the latest url instead of master.
**Checklist:**

docs: Fix the links from docs to github examples in master branch

---

pkg/daemon/ceph/osd/remove.go
pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/cluster/mgr/mgr_test.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/cluster/mon/spec.go
pkg/operator/ceph/cluster/osd/create.go
pkg/operator/ceph/cluster/osd/health.go
pkg/operator/ceph/cluster/osd/update.go
pkg/operator/ceph/cluster/osd/update_test.go
pkg/operator/ceph/csi/controller.go
pkg/operator/ceph/csi/peermap/config.go
pkg/operator/ceph/csi/peermap/config_test.go
pkg/operator/ceph/csi/spec.go
pkg/operator/ceph/file/mds/mds.go
pkg/operator/ceph/file/mds/spec.go
pkg/operator/ceph/object/rgw.go
pkg/operator/ceph/pool/controller.go
pkg/operator/k8sutil/deployment.go
pkg/operator/k8sutil/deployment_test.go
tests/integration/ceph_upgrade_test.go

This commit adds context parameter to k8sutil deployment functions. By
this, we can handle cancellation during API call of deployment resource.
Part of https://github.com/rook/rook/issues/8700
**Checklist:**

core: add context parameter to k8sutil deployment

---

cmd/rook/ceph/operator.go
cmd/rook/rook/rook.go
pkg/daemon/discover/discover.go
pkg/operator/ceph/cluster/cephstatus.go
pkg/operator/ceph/cluster/cephstatus_test.go
pkg/operator/ceph/cluster/mon/health.go
pkg/operator/ceph/cluster/mon/health_test.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/discover/discover.go
pkg/operator/k8sutil/pod.go
pkg/operator/k8sutil/pod_test.go
tests/integration/ceph_mgr_test.go

This commit adds context parameter to k8sutil pod functions. By this, we
can handle cancellation during API call of pod resource.
Part of https://github.com/rook/rook/issues/8700
**Checklist:**

core: add context parameter to k8sutil pod

---

cmd/rook/ceph/operator.go
pkg/util/flags/flags.go

rook command doesn't interpret `logtostderr` option. It's OK to just remove this option because `capnslog` outputs all logs to stdout by default. It's better to keep `AddGoFlagSet()` call because some libraries might define their own flags with Go's `flag` package.
**Checklist:** …

core: remove unnecessary option

---

pkg/operator/ceph/csi/spec.go
pkg/operator/k8sutil/daemonset.go

This commit adds context parameter to k8sutil daemonset functions. By
this, we can handle cancellation during API call of daemonset resource.
Part of https://github.com/rook/rook/issues/8700
**Checklist:**

core: add context parameter to k8sutil daemonset

---

pkg/operator/ceph/cluster/osd/spec.go

The OSD blkdevmapper init container relies on the MKNOD capability, which it does not actually request.
As a result, deployments fail on Kubernetes clusters that do not happen to assign this capability to all containers by default.
This PR introduces a function that constructs a securityContext tailored to the `blkdevmapper` use-case instead of relying on the controller.PodSecurityContext function.  
This change also implies `blkdevmapper` will no longer become privileged when `ROOK_HOSTPATH_REQUIRES_PRIVILEGED` is true but as far as I can tell this should never be happening/needed for the `blkdevmapper` use-case anyway. (unless I missed something?)
Resolves #9156 
**Checklist:**

osd: set blkdevmapper capabilities

---

cmd/rook/ceph/osd.go
pkg/operator/ceph/cluster/cephstatus.go
pkg/operator/ceph/cluster/cleanup.go
pkg/operator/ceph/cluster/osd/create.go
pkg/operator/ceph/cluster/osd/osd.go
pkg/operator/discover/discover.go
pkg/operator/discover/discover_test.go
pkg/operator/k8sutil/node.go
pkg/operator/k8sutil/node_test.go
tests/integration/ceph_mgr_test.go

This commit adds context parameter to k8sutil node functions. By this,
we can handle cancellation during API call of node resource.
Part of https://github.com/rook/rook/issues/8700
**Checklist:**

core: add context parameter to k8sutil node

---

images/ceph/Makefile

On mac, the docker build was failing due to an unspecified S5CMD_ARCH. Now we default to build amd64 always and override it if the arch is arm64. 
Though not sure why the official mac build was running and my local build hit this issue...
```
=== Generated CSV templates can be found at /var/folders/fw/dvkm8bzd60n8j0j40y55ngvw0000gn/T/tmp.Ux4igYyI/cluster/olm/ceph/templates
if [ -z "" ]; then\
docker build -q \
--build-arg S5CMD_VERSION=1.4.0 \
--build-arg S5CMD_ARCH= \
-t build-a63aad4e/ceph-amd64 \
/var/folders/fw/dvkm8bzd60n8j0j40y55ngvw0000gn/T/tmp.Ux4igYyI;\
fi
Sending build context to Docker daemon  50.67MB
Step 1/12 : FROM quay.io/ceph/ceph-amd64:v16.2.6-20210918
---> fd4c47aacbc9
Step 2/12 : ARG S5CMD_VERSION
---> Using cache
---> a35e2fd1136a
Step …
```

build: Default to amd64 arch for the the s5cmd tool

---

pkg/operator/ceph/cluster/mon/mon.go

the mons re-initialize its ClusterInfo which results in missing
CR name on the ClusterInfo
Set the CR name to the mons cluster ClusterInfo
Closes: https://github.com/rook/rook/issues/9159
Resolves #https://github.com/rook/rook/issues/9159
**Checklist:**

mon: update mons Cluster ClusterInfo with CR name

---

Documentation/branch.liquid

The latest docs should link to the master examples on github. Only the docs were renamed to latest, but not the github branch. This change was missed with #9155. 
**Checklist:**

docs: generate correct doc links to master github branch

---

cluster/charts/rook-ceph-cluster/templates/ingress.yaml
cluster/charts/rook-ceph-cluster/values.yaml

In the helm chart, the ingress for the dashbard was always referring to the http-dashboard port on the dashboard service. If ssl is enabled the https-dashboard port must be specified, or else the dashboard will not be available through the ingress.
The default is also changed from http to https when the dashboard is installed through the cluster helm chart.
Resolves #9152 
**Checklist:**

helm: Set correct ingress endpoint protocol

---

pkg/operator/ceph/cluster/osd/spec.go
pkg/operator/ceph/controller/spec.go

The blockdevmapper securityContext was changed to request a minimal set of required capabilities for its operation and drop running as privileged.  
While the base change works and is valid in terms of the container's copy operation, it turns out that OpenShift may require some additional configuration not currently covered by the limited securityContext and the capabilities granted.  
To not break those OpenShift deployments, make the blkdevmapper securityContext listen to the ROOK_HOSTPATH_REQUIRES_PRIVILEGED flag again to set privileged mode.  
This flag is true on OpenShift deployments and running as privileged works around the (missing) configuration problem for now.  
To properly drop privileged completely some additional investigation needs to be …

osd: add privileged support (back) to blkdevmapper securityContext (work-around)

---

Documentation/development-flow.md

Removing `ceph` component from doc as component
`ceph` was removed from commitlint bot earlier.
Resolves #
**Checklist:**

docs: remove old commitlint component `ceph` from doc

---

cluster/charts/rook-ceph/templates/clusterrolebinding.yaml
cluster/charts/rook-ceph/templates/psp.yaml

Move the rbd-csi-nodeplugin ClusterRoleBinding from the chart PSP
resources to its proper place with the rest of the operator-wide
ClusterRoleBindings.
Resolves #
**Checklist:**

helm: move rbd-csi-nodeplugin from PSP resources

---

pkg/operator/ceph/cluster/cluster.go

the mon cluster clusterInfo is intiated seprately,
and misses out to set the cluster name and use default name as testing
from AdminClusterInfo.
Part-of: https://github.com/rook/rook/issues/9159
Resolves #
**Checklist:**

mon: set cluster name to mon cluster

---

.github/workflows/canary-integration-test.yml
Documentation/ceph-object-store-crd.md
pkg/daemon/ceph/osd/kms/envs.go
pkg/daemon/ceph/osd/kms/volumes.go
pkg/daemon/ceph/osd/kms/volumes_test.go
pkg/operator/ceph/cluster/osd/provision_spec.go
pkg/operator/ceph/cluster/osd/spec.go
pkg/operator/ceph/object/config.go
pkg/operator/ceph/object/spec.go
pkg/operator/ceph/object/spec_test.go
tests/scripts/deploy-validate-vault.sh

From ceph v16.2.6 onwards the vault TLS suppport in RGW was added,
include similar changes for RGW.
Resolves #
**Checklist:**

ceph: add support in RGW to communicate vault with TLS

---

Documentation/ceph-upgrade.md

Ceph has recently reported that it may be unsafe to upgrade clusters
from Nautilus/Octopus to Pacific v16.2.0 through v16.2.6. We are
tracking this in Rook issue https://github.com/rook/rook/issues/9185.
Add a warning to the upgrade doc about this.
Resolves #
**Checklist:**

docs: add OMAP quick fix warning to upgrade guide

---

pkg/operator/ceph/file/controller.go
pkg/operator/ceph/object/controller.go
pkg/operator/ceph/pool/controller.go

Clean up the code used to stop health checkers for all controllers
(pool, file, object). Health checkers should now be stopped when
removing the finalizer for a forced deletion when the CephCluster does
not exist. This prevents leaking a running health checker for a resource
that is going to be imminently removed.
Also tidy the health checker stopping code so that it is similar for all
3 controllers. Of note, the object controller now uses namespace and
name for the object health checker, which would create a problem for
users who create a CephObjectStore with the same name in different
namespaces.
Any leaks would likely come into play more often in the real world for test clusters where a user is installing clusters with various …

pool: file: object: clean up health checkers for both types of deletion

---

pkg/apis/ceph.rook.io/v1/labels.go
pkg/apis/ceph.rook.io/v1/labels_test.go
pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/k8sutil/prometheus_test.go

The templates for the mgr-generated ServiceMonitor and PrometheusRule objects included the labels prometheus and team, making it impossible to override them as user.
This removes these labels from the templates and sets them in code, if not already set by the user.
Resolves #8502
**Checklist:**

#8502: Make monitoring object labels overridable

---

Documentation/ceph-monitoring.md
cluster/examples/kubernetes/ceph/monitoring/keda-rgw.yaml
tests/scripts/github-action-helper.sh

By default HPA can use details about memory or CPU consumption for
autoscaling, but also it can use custom metrics as well. There are alot
provides supports HPA via customer and one of them is KEDA project. Here
it is done with help of Prometheus Scaler
Resolves #
**Checklist:**

docs: add details about HPA via KEDA

---

.github/workflows/integration-test-setup/action.yaml
.github/workflows/setup-cluster-resources/action.yaml
Documentation/helm-ceph-cluster.md
cluster/charts/rook-ceph-cluster/templates/_helpers.tpl
cluster/charts/rook-ceph-cluster/templates/ingress.yaml
cluster/charts/rook-ceph-cluster/values.yaml
tests/framework/installer/ceph_helm_installer.go
tests/integration/ceph_base_deploy_test.go
tests/integration/ceph_helm_test.go

The ingress api version changed when it went to v1, and this has caused a lot of problems on how this is handled across the helm ecosystem.
This PR uses the standard introduced by bitnami to deal with overriding the ingress version.
As discussed in the issue, the helm chart cannot deploy to clusters older than 1.18.
Resolves #9174
**Checklist:**

helm: Allow further configurability of the ingress version

---

cluster/charts/rook-ceph/values.yaml

Change the default image in value.yaml to match [spec.go](https://github.com/rook/rook/blob/ba54567e8f51874080658420b1b221ebfe5318a0/pkg/operator/ceph/csi/spec.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L100-L105)
Signed-off-by: zhangwei <zhangwei24@apache.org>
Resolves #
**Checklist:**

helm: update comments to match the default image in the code

---

pkg/daemon/ceph/client/pool.go
pkg/operator/ceph/nfs/controller.go
pkg/operator/ceph/nfs/controller_test.go
pkg/operator/ceph/nfs/nfs.go

For CRD not using the new nfs spec that includes the pool settings,
applying the "size" property won't work since it is set to 0. The pool
still gets created but returns an error. The loop is re-queued but on
the second run the pool is detected so no further configuration is done.
Previously, if the pool was present we would not run the pool creation
again. This is a problem if the pool spec changes, the new settings will
never be applied.
Closes: https://github.com/rook/rook/issues/9205
Resolves #9205
**Checklist:**

nfs: only set the pool size when it exists and always run default pool creation

---

pkg/operator/k8sutil/prometheus.go

Updating the promethes resources (PrometheusRule and ServiceMonitor) is
done by fetching the current resource from the server and updating the
spec on it. This commit makes it also apply the labels, so users can
update them via rook CRDs.
Resolves #9241
**Checklist:**

monitoring: update label on prometheus resources

---

cluster/examples/kubernetes/ceph/operator-openshift.yaml
pkg/apis/ceph.rook.io/v1/scc.go

The MKNOD capability was missing and due to recent addition some pod now
only require this cap as well as privileged.
The cap must be explicitly exposed so it can be requested by a pod.
Closes: https://github.com/rook/rook/issues/9234
Resolves https://github.com/rook/rook/issues/9234
**Checklist:**

core: fix openshift security context

---

pkg/apis/rook.io/labels.go
pkg/apis/rook.io/labels_test.go
pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/k8sutil/prometheus_test.go

This is a backport of #9180 into v1.7 branch, also making sure the tests for `pkg/apis/rook.io.Labels` are run by renaming `labels_spec.go` back to `labels_test.go`.
Resolves #8502 (in v1.7)
**Checklist:**

monitoring: allow overriding monitoring labels

---

.github/workflows/canary-integration-test.yml
.github/workflows/daily-nightly-jobs.yml
.github/workflows/rgw-multisite-test/action.yml
tests/scripts/github-action-helper.sh

In the nightly job, run the test with the latest Ceph version so we can
detect if there are RGW changes in Ceph that might break multisite. Use
a reusable GitHub action workflow to duplicate as little code as
possible.
Resolves #
**Checklist:**

test: test rgw multisite nightly

---

.github/workflows/canary-integration-test.yml
cluster/examples/kubernetes/ceph/osd-purge.yaml
cmd/rook/ceph/osd.go
pkg/daemon/ceph/client/crash.go
pkg/daemon/ceph/client/osd.go
pkg/daemon/ceph/osd/remove.go
tests/scripts/collect-logs.sh

If multiple removal jobs are fired in parallel, there is a risk of
losing data since we will forcefully remove the OSD. So now, we check
if the OSD is ok-to-stop first and then proceed. The code waits forever
and retries every minute.
Resolves #
**Checklist:**

osd: check if osd is safe-to-destroy before removal

---

images/cross/Dockerfile

This reverts commit ceec0bc48c7f3b1d8c50c2f56d9520986e20baec. The build
is failing to push images to master. This is not a critical update so
let's remove.
Example error: https://github.com/rook/rook/actions/runs/1503761177
Resolves #
**Checklist:**

build: revert "build: images/cross/Dockerfile to reduce vulnerabilities"

---

pkg/operator/ceph/object/config.go
pkg/operator/ceph/object/rgw.go

use Zone and ZoneGroup instead of storename for rgw_zone and rgw_zonegroup flags
Signed-off-by: Olivier Bouffet <olivier.bouffet@infomaniak.com>
Resolves #9248
**Checklist:**

object: fix rgw ceph config

---

.mergify.yml

Normally, only the mergify bot should send out PR to the release
branches. All contributions should generally go in master first then be
backported. Let's warn to avoid merging PR send against a release
branch.
Resolves #
**Checklist:**

bot: add bot message when pushing on a release branch

---

pkg/operator/ceph/nfs/nfs.go
pkg/operator/ceph/nfs/nfs_test.go
pkg/operator/ceph/nfs/spec.go
pkg/operator/ceph/nfs/spec_test.go

When the configuration configmap is updated for a CephNFS server, the
NFS application should restart to ensure it is running with the latest
config.
Fixes #9028
Resolves #
**Checklist:**

nfs: restart nfs servers when configmap is updated

---

Documentation/helm-ceph-cluster.md
cluster/charts/rook-ceph-cluster/templates/_helpers.tpl
cluster/charts/rook-ceph-cluster/templates/ingress.yaml
cluster/charts/rook-ceph-cluster/values.yaml

The ingress api version changed when it went to v1, and this has caused some upheaval
throughout the kubernetes ecosystem. This commit uses a common method of deciding which
ingress api to use, and allows the optional override of the kubernetes version
presented to helm using the helm build-in capabilities.
also add an ingress into the helm integration tests so any regressions to how ingresses
are handled in the future are caught easier.
Closes rook#9174
Signed-off-by: Tom Hellier <me@tomhellier.com>
(cherry picked from commit ba4460247710124d00d8768614f7dd2dcd8c8758)
Resolves #9232

helm: allow further configurability of ingress version (manual backport)

---

pkg/daemon/ceph/client/command.go
pkg/daemon/ceph/client/filesystem_mirror.go

cephfs-mirror: try to mitigate peer import error
Some users have reported issues while adding the token, this is not
always reproducible so perhaps it's a typo when importing the token and
adding trailing spaces.
core: add the ability to execute ceph commands with a combined output
Sometimes Ceph uses a different standard output to return errors or
merges standard error to standard out. So let's allow some commands to
return both in the output.
cephfs-mirror: use the combined output to possibly catch peer import error
By adding combined output to the executor we might be able to fetch more
error messages.
Resolves #9151
**Checklist:**

cephfs-mirror: various fixes for random bootstrap peer import errors

---

pkg/operator/ceph/object/objectstore.go

avoid failed reconcile when multiple multisite objectstore are configured
Signed-off-by: Olivier Bouffet <olivier.bouffet@infomaniak.com>
Sorry this time a PR against master , previous bad PR #9143
Resolves #9100 
**Checklist:**

object: fix search user in objectstore

---

cluster/examples/kubernetes/ceph/pv-migrator/migrator.yaml
images/ceph/Dockerfile

-  Adding  add pv-migrator binary to rook image directly
in 1.7.x branch as discussed.
- Adding migrator.yaml file which will required
to run migrator pod.
Resolves #
**Checklist:**

build: add pv-migrator binary to rook image in 1.7.x branch

---

Documentation/helm-ceph-cluster.md
deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml
deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
deploy/charts/rook-ceph-cluster/values.yaml

It should be possible to configure the storage classs mount options, this follows
the helm code used by the ceph-csi project for their ceph-csi-rbd and ceph-csi-cephfs
helm charts.
Signed-off-by: Tom Hellier <me@tomhellier.com>
Adds the ability to use the storageClass mount options provided by the csi storage class
Resolves #9286 
**Checklist:**

helm: addition of mountOptions into storage class configuration

---

pkg/operator/ceph/cluster/osd/update.go

Skipping upgrade checks was not being honored for OSDs. Now the flag will be checked and allow the OSDs to be upgraded without checking for the ok-to-stop condition.
**Checklist:**

osd: Honor skipUpgradeChecks for OSDs

---

cluster/charts/rook-ceph-cluster/templates/ingress.yaml

This is a manual backport as there are merge conflicts, so mergify cannot do it for us.

helm: Use a more explicit value for ingress (backport #9280)

---

.mergify.yml

With the creation of the release-1.8 branch we enable the mergify bot to open the backport PRs automatically based on the backport-release-1.8 label.
**Checklist:**

bot: Enable backports to release-1.8

---

build/rbac/common.yaml.header
deploy/examples/common.yaml

In anticipation of generating common.yaml from the Helm charts, sort
common.yaml using the same script used to sort the output from Helm
charts.
This was done using the flow below, then editing some comments out of the result.
```
cat build/rbac/common.yaml.header > new-common.yaml
cat deploy/examples/common.yaml | build/rbac/keep-rbac-yaml.sh >> new-common.yaml
mv new-common.yaml deploy/examples/common.yaml
```
Resolves #
**Checklist:**

docs: sort common.yaml

---

.github/workflows/push-build.yaml
tests/scripts/build-release.sh

Do not use the cross build container when building, publishing, and
promoting rook/ceph images. It is no longer needed, and its complexity
can add flakiness.
Resolves #
**Checklist:**

build: do not use cross build container for ceph

---

pkg/daemon/ceph/client/mon.go
pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/mon/health.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/cluster/mon/mon_test.go

The failover of the arbiter mon in a stretch cluster was sometimes failing due to the new tiebreaker not being set in ceph. Rook would repeatedly try to remove the old tiebreaker mon and keep failing because the new tiebreaker had not been set. Now we make setting the tiebreaker idempotent in case the operator restarts in the middle of the operation or some other corner case causes the expected tiebreaker to be set. In that case, the next reconcile will also ensure the tiebreaker mon is set as expected.
**Checklist:**

mon: Set stretch tiebreaker reliably during failover

---

deploy/olm/generate-rook-csv.sh

The command needs to be run outside the OLM_CATALOG_DIR as it already
contains that directory in its paths.
Signed-off-by: Boris Ranto <branto@redhat.com>
Resolves #9318
**Checklist:**

build: run mv outside the OLM_CATALOG_DIR

---

.mergify.yml

The strict merge option was not being used and anyway has been depcrecated by the mergify bot.
This is currently resulting in the following CI failure:
```
Summary Failing after 3s — The Mergify configuration is invalid
```
The details of the failure show:
The configuration uses the deprecated strict mode of the merge action.
A brownout is planned for the whole December 6th, 2021 day.
This option will be removed on January 10th, 2022.
For more information: https://blog.mergify.com/strict-mode-deprecation/
**Checklist:**

bot: Mergify deprected the strict merge option

---

deploy/olm/generate-rook-csv.sh

The command needs to be run outside the OLM_CATALOG_DIR as it already
contains that directory in its paths.
Signed-off-by: Boris Ranto <branto@redhat.com>
(cherry picked from commit 4cb8bb3bec57a95f46f7a2936a63261bf1f23348)
Resolves #
**Checklist:**

build: Run mv outside the OLM_CATALOG_DIR (backport #9319)

---

pkg/operator/ceph/cluster/cleanup.go
pkg/operator/ceph/cluster/osd/provision_spec.go
pkg/operator/k8sutil/k8sutil.go
pkg/operator/k8sutil/k8sutil_test.go
tests/framework/installer/ceph_installer.go
tests/framework/installer/ceph_settings.go
tests/integration/ceph_helm_test.go
tests/integration/ceph_smoke_test.go

- In K8s 1.22 there is a bug in the job name generation that the job name is truncated an additional 10 characters. This can cause an issue in the generated pod name if it then ends in a non-alphanumeric character. In that case, we more aggressively generate a hashed job name.
- The generation of a long node name in the integration tests was being done based on the k8s version. In the past, older K8s versions did not support the changing name. Now it's more maintainable if we generate the long name depending on the test suite.
Resolves #9294 
**Checklist:**

Truncate job name of the osd prepare job further to avoid pod generation failure on K8s 1.22

---

build/rbac/keep-rbac-yaml.sh

Currently there was an issue related to sorting
files in Rbac generation in different platforms
Updated the locale to LC_ALL=C so rbac generation
can done correctly
Closes: https://github.com/rook/rook/issues/9331
Co-authored-by: Blaine Gardner blaine.gardner@redhat.com
Resolves #
**Checklist:**

build: updated locale for rbac generation

---

Makefile
build/rbac/gen-common.sh
deploy/charts/library/templates/_cluster-role.tpl
deploy/charts/library/templates/_cluster-serviceaccount.tpl
deploy/charts/library/templates/_imagepullsecret.tpl
deploy/charts/rook-ceph/templates/clusterrole.yaml
deploy/charts/rook-ceph/templates/clusterrolebinding.yaml
deploy/charts/rook-ceph/templates/role.yaml
deploy/examples/common.yaml

Generate deploy/examples/common.yaml from Helm charts. There were still
a few differences between common.yaml and the Helm charts. Where there
were differences we assume common.yaml was the most up-to-date.
Resolves #
**Checklist:**

build: generate common.yaml from helm charts

---

Documentation/ceph-filesystem-crd.md
deploy/examples/csi/cephfs/storageclass-ec.yaml
deploy/examples/filesystem-ec.yaml

when creating ec fs, create replicated pool as primary
pool and ec pool as secondary pool, creating ec pool
as primary is not encouraged and it will lead to failure.
Closes: https://github.com/rook/rook/issues/8210
Resolves #8210 
**Checklist:**

mds: create EC pool as secondary pool

---

tests/integration/ceph_upgrade_test.go

The toolbox spec changed from 1.7 to 1.8 due to the removal of tini from the image. The upgrade test was failing on k8s 1.18 due to this issue.
**Checklist:**

test: Upgrade test to update the toolbox spec

---

Documentation/ceph-advanced-configuration.md
Documentation/ceph-pool-crd.md
PendingReleaseNotes.md
pkg/daemon/ceph/client/crush_rule.go
pkg/daemon/ceph/client/pool.go
pkg/daemon/ceph/client/pool_test.go

The failure domain is baked into the crush rule that is created for a pool. To allow for an updated failure domain on the pool, create a new crush rule specific for that failure domain and update the pool with the new rule.
Previously the advanced docs indicated how to update the failure domain. Now the failure domain can simply be updated on the pool CR. 
**Checklist:**

pool: Update the desired failure domain when changed

---

Documentation/ceph-nfs-crd.md
Documentation/ceph-upgrade.md
deploy/examples/nfs-test.yaml
deploy/examples/nfs.yaml

NFS docs need to be updated to reflect changes between Octopus and
Pacific, how users are affected, how NFS is configured differently
between the Ceph versions, and how to upgrade from one Ceph version to
the other.
Resolves #
**Checklist:**

docs: update NFS docs

---

.github/workflows/rgw-multisite-test/action.yml
Documentation/ceph-cluster-crd.md
Documentation/ceph-upgrade.md
deploy/charts/rook-ceph-cluster/values.yaml
deploy/examples/cluster-external-management.yaml
deploy/examples/cluster-on-local-pvc.yaml
deploy/examples/cluster-on-pvc.yaml
deploy/examples/cluster-stretched-aws.yaml
deploy/examples/cluster-stretched.yaml
deploy/examples/cluster-test.yaml
deploy/examples/cluster.yaml
deploy/examples/images.txt
deploy/olm/assemble/metadata-common.yaml
design/ceph/ceph-cluster-cleanup.md
images/ceph/Makefile
tests/framework/installer/ceph_installer.go

ceph 16.2.7 is out so let's use it in our manifests.
Resolves #
**Checklist:**

core: bump to ceph 16.2.7

---

pkg/operator/ceph/controller/predicate.go
pkg/operator/ceph/object/bucket/provisioner.go
pkg/operator/ceph/object/bucket/util.go
pkg/operator/ceph/object/notification/controller.go
pkg/operator/ceph/object/notification/controller_test.go
pkg/operator/ceph/object/notification/obc_label_controller.go
pkg/operator/ceph/object/notification/obc_label_controller_test.go
pkg/operator/ceph/object/notification/provisioner.go
pkg/operator/ceph/object/notification/s3ext.go
pkg/operator/ceph/object/rgw.go
pkg/operator/ceph/object/topic/controller.go
pkg/operator/ceph/object/topic/controller_test.go
pkg/operator/ceph/object/topic/provisioner.go

This PR is addressing followup work from: https://github.com/rook/rook/pull/8426
Following tasks will be broken off to their own PRs:
- add OBC list in notification status
- fetch the list of notifications from the RGW and do the diff with the labels instead of deleting all notifications on any label change
- More integration tests: https://github.com/rook/rook/pull/9169

ceph: bucket notifications refactoring work

---

deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/crds.yaml
pkg/apis/ceph.rook.io/v1/types.go

Fix the CephNFS spec.rados API specifiation to be clear that spec.rados
is optional for all Ceph v16 versions, including that
spec.rados.namespace is optional.
Resolves #
**Checklist:**

nfs: make rados.namespace optional

---

.github/workflows/canary-integration-test.yml
pkg/daemon/ceph/client/filesystem_mirror.go
pkg/daemon/ceph/client/filesystem_mirror_test.go

If cephVersion>= 16.2.7, we run
ceph fs snapshot mirror daemon status
otherwise we run
ceph fs snapshot mirror daemon status <fs_name>
Updating the cmd so both the ceph version can run successfully
Closes: https://github.com/rook/rook/issues/8458
Resolves #
**Checklist:**

ceph: removing fs_name arg from daemon status cmd

---

deploy/charts/rook-ceph/templates/deployment.yaml

The 1.8 (beta) relies on a volume when using the admission controller, which is missing from the Helm chart.  
This change sets up the volume so the operators starts properly when set up to run the admission controller.
Resolves #9349 
**Checklist:**

helm: rook-ceph chart: Set up webhook cert volume

---

tests/framework/clients/bucket.go
tests/framework/clients/notification.go
tests/framework/utils/k8s_helper.go
tests/integration/ceph_bucket_notification_test.go

Added following test cases for bucket notification integration test
suite:
* different order: OBC - Topic - Notification
* different order: OBC - Notification - Topic
* adding a label to an existing OBC
* deleting a label from an existing OBC
Resolves #
**Checklist:**

test: add more test cases for bucket notfication

---

Documentation/ceph-upgrade.md

In 1.8, the admission controller has merged with the operator and the
operator needs an emptyDir and a volume mount to store the webhook
certificates.
Co-authored-by: Blaine Gardner <blaine.gardner@redhat.com>
Co-authored-by: Sébastien Han <seb@redhat.com>
Resolves #
**Checklist:**

docs: add instructions to upgrade admission controller

---

pkg/operator/ceph/cluster/cleanup.go

We need to use the root UID to run the cleanup job since ceph-volume
does not support running as non-root in all the versions. We have this
ceph tracker to allow this https://tracker.ceph.com/issues/53511 but
it's not in all ceph's versions. Implementing a version check is tricky
since at this stage the cluster is being deleted and it's hard to catch
it.
Closes: https://github.com/rook/rook/issues/9375
Resolves #
**Checklist:**

osd: cleanup cluster using the root UID

---

pkg/operator/ceph/controller/mirror_peer.go
pkg/operator/k8sutil/replicaset.go
pkg/operator/k8sutil/secret.go

This commit adds context parameter to k8sutil replicaset and secret
functions. By this, we can handle cancellation during API call of
replicaset and secret resource.
Part of #8700
**Checklist:**

core: add context to k8sutil replicaset and secret

---

pkg/operator/ceph/cluster/cluster_external.go
pkg/operator/ceph/cluster/mgr/dashboard.go
pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/cluster/mon/service.go
pkg/operator/ceph/cr_manager.go
pkg/operator/ceph/csi/spec.go
pkg/operator/ceph/object/spec.go
pkg/operator/ceph/webhook.go
pkg/operator/k8sutil/service.go

This commit adds context parameter to k8sutil service functions. By
this, we can handle cancellation during API call of service resource.
Part of #8700
**Checklist:**

core: add context parameter to k8sutil service

---

pkg/operator/ceph/controller/spec.go
pkg/operator/ceph/object/spec.go
pkg/operator/k8sutil/endpoint.go

This commit adds context parameter to k8sutil endpoint functions. By
this, we can handle cancellation during API call of endpoint resource.
Part of #8700
**Checklist:**

core: add context parameter to k8sutil endpoint

---

pkg/operator/k8sutil/cmdreporter/cmdreporter.go
pkg/operator/k8sutil/configmap.go
pkg/operator/k8sutil/configmap_test.go

This commit adds context parameter to k8sutil configMap functions. By
this, we can handle cancellation during API call of configMap resource.
Part of #8700
**Checklist:**

core: add context parameter to k8sutil configMap

---

pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/k8sutil/prometheus.go

This commit adds context parameter to k8sutil prometheus functions. By
this, we can handle cancellation during API call of prometheus resource.
Part of #8700 
**Checklist:**

core: add context parameter to k8sutil prometheus

---

pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/cluster/osd/deviceSet.go
pkg/operator/k8sutil/pvc.go
pkg/operator/k8sutil/pvc_test.go

This commit adds context parameter to k8sutil pvc functions. By this, we
can handle cancellation during API call of pvc resource.
Part of #8700 
**Checklist:**

core: add context parameter to k8sutil pvc

---

cmd/rook/ceph/osd.go
pkg/daemon/ceph/osd/daemon.go
pkg/operator/ceph/cluster/osd/status.go
pkg/operator/ceph/cluster/osd/status_test.go
pkg/operator/ceph/object/mime.go
pkg/operator/k8sutil/kvstore.go
pkg/operator/k8sutil/kvstore_test.go

This commit adds context parameter to k8sutil kvstore functions. By
this, we can handle cancellation during API call of kvstore resource.
Part of #8700 
**Checklist:**

core: add context parameter to k8sutil kvstore

---

deploy/examples/create-external-cluster-resources.py

The create-external-cluster-resources.py with
--create-external-cluster-resources set to true
sets a wrong osd application tag. It should use
the fs name and not the fs pools.
Resolves #9227
Signed-off-by: Lennart Hagemann <lennart.hagemann@continum.net>
**Checklist:**

security: use correct osd tags for restricted caps with external cluster script

---

pkg/operator/ceph/file/controller.go
pkg/operator/ceph/object/controller.go
pkg/operator/ceph/pool/controller.go

When CephBlockPool, CephFilesystem, or CephObjectStore resources are
deleted after removing their finalizer, the code path to stop monitoring
was not stopping monitoring since a non-present resource does not have a
name and namespace attached. When the object is deleted, ensure the
internal representation used to stop monitoring has a name and namespace
to fix the issue.
Resolves #
**Checklist:**

pool: file: object: clean up health checkers for force deletion

---

.github/workflows/daily-nightly-jobs.yml
.github/workflows/integration-test-helm-suite.yaml
.github/workflows/integration-test-mgr-suite.yaml
.github/workflows/integration-test-multi-cluster-suite.yaml
.github/workflows/integration-test-object-suite.yaml
.github/workflows/integration-test-smoke-suite.yaml
.github/workflows/integration-test-upgrade-suite.yaml
.github/workflows/integration-tests-on-release.yaml
.github/workflows/setup-cluster-resources/action.yaml

With the release of k8s 1.23 we update the CI to run PRs against K8s 1.16 and K8s 1.23, the oldest and latest releases that are supported. The master branch will run against the latest v1.16, 1.18, 1.21, and 1.23.
Resolves #9374 
**Checklist:**

build: Add K8s 1.23 to the CI tests

---

.github/workflows/canary-integration-test.yml
deploy/examples/create-external-cluster-resources.py
deploy/examples/pool-ec.yaml
tests/scripts/github-action-helper.sh

Adding cli agrument `--rbd-metadata-ec-pool-name` to read
rbd ec pool name to support ec pool in external cluster
and also updating the json blob.
Resolves #
**Checklist:**

pool: add rbd ec pool support in external cluster

---

deploy/examples/direct-mount.yaml

the tini have been removed but was still present at direct mount
used the bin/bash shell in place of tini
Closes: https://github.com/rook/rook/issues/9382
Resolves #
**Checklist:**

build: updating tini init command in direct mount toolbox

---

Documentation/ceph-upgrade.md
Documentation/helm-operator.md
deploy/charts/library/templates/_cluster-monitoring.tpl
deploy/charts/rook-ceph/templates/cluster-rbac.yaml
deploy/charts/rook-ceph/values.yaml

An older version of the Helm chart always installed RBAC permissions for
enabling monitoring. In an effort to reduce the privileges Rook uses by
default, they were removed. We need to still include the monitoring RBAC
optionally since the change could break some users.
Co-authored-by: Mathieu Parent <mathieu.parent@insee.fr>
Co-authored-by: Blaine Gardner <blaine.gardner@redhat.com>
Resolves #9398 (with the caveat that values `monitoring.enabled` should be set to `true`)
**Checklist:**

helm: add optional monitoring RBAC to operator chart

---

pkg/operator/ceph/file/controller.go
pkg/operator/ceph/object/controller.go
pkg/operator/ceph/pool/controller.go

Clean up the code used to stop health checkers for all controllers
(pool, file, object). Health checkers should now be stopped when
removing the finalizer for a forced deletion when the CephCluster does
not exist. This prevents leaking a running health checker for a resource
that is going to be imminently removed.
Also tidy the health checker stopping code so that it is similar for all
3 controllers. Of note, the object controller now uses namespace and
name for the object health checker, which would create a problem for
users who create a CephObjectStore with the same name in different
namespaces.
(cherry picked from commit 03ba7dec640dc3f1c944c57f28ff0852c5f19c5b)
> Resolved conflicts:
>	pkg/operator/ceph/file/controller.go
> …

pool: file: object: clean up health checkers for both types of deletion (backport #9094)

---

cmd/rook/ceph/mgr.go
pkg/operator/ceph/cluster/cleanup.go
pkg/operator/ceph/cluster/mgr/spec.go
pkg/operator/ceph/cluster/osd/config.go
pkg/operator/ceph/cluster/osd/spec.go
pkg/operator/ceph/controller/spec.go

We don't need to use /var/lib/rook for the ceph config and keyring, so
let's use /etc/ceph which has the right permissions too. Also, we need
to run with the ceph user since the rook image defaults to the "rook"
user.
Resolves #9385
**Checklist:**

mgr: run the watch side car config on /etc/ceph

---

pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/cluster_test.go

The mons need to be configured to skip the mds sanity check during upgrade to 16.2.7 or the mons may crash during that upgrade.
Resolves #9373 
**Checklist:**

mds: Skip sanity check during upgrades to 16.2.7

---

build/rbac/rbac.yaml
deploy/charts/rook-ceph/templates/psp.yaml
deploy/examples/common.yaml

This commit adds CAP_MKNOD to PodSecurityPolicy to allow OSD-prepare job
creating pods on PSP-enabled Kubernetes cluster.
Follow-up of https://github.com/rook/rook/pull/9158
Signed-off-by: Yuichiro Ueno <ueno@preferred.jp>
Resolves https://github.com/rook/rook/issues/9438
**Checklist:**

osd: add CAP_MKNOD to PSP

---

.github/workflows/canary-integration-test.yml
deploy/examples/create-external-cluster-resources.py

Adding dry run mode for external cluster script.
This will add cli argument `--dry-run`. By default
`dry-run` option will be `False`
which means it will only print something like below.
```
Execute: 'ceph fs ls'
Execute: 'ceph fsid'
Execute: 'ceph quorum_status'
Execute: 'ceph auth get-or-create client.healthchecker mon allow r, allow command quorum_status, allow command version mgr allow command config osd allow rwx pool=default.rgw.meta, allow r pool=.rgw.root, allow rw pool=default.rgw.control, allow rx pool=default.rgw.log, allow x pool=default.rgw.buckets.index'
Execute: 'ceph mgr services'
Execute: 'ceph auth get-or-create client.csi-rbd-node mon profile rbd osd profile rbd'
Execute: 'ceph auth get-or-create client.csi-rbd-provisioner mon profile rbd mgr allow rw osd profile rbd' …
```

security: add dry run mode for external cluster script

---

Documentation/ceph-common-issues.md

Resolves #9320
Resolves #
**Checklist:**

docs: add jumbo frames note to common issues

---

deploy/charts/rook-ceph/templates/clusterrole.yaml
deploy/examples/common.yaml

See https://sdk.operatorframework.io/docs/faqs/ for further reference
Signed-off-by: Daniel Ruiz Capilla <crd1985@gmail.com>
This PR adds a missing role to allow the object controller update the finalizers section in OBC and OB. Otherwise, an error like `secrets \"my-bucket\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on:` is thrown in the operator log.
This error raises when the plugin OwnerReferencesPermissionEnforcement  is enabled (OKD 4.8 in bare metal in my use case).
See <https://sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-why-do-i-see-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on-> for …

ceph: fix blockOwnerDeletion error

---

Documentation/ceph-pool-crd.md

Hybrid pools suffer from lower availability when a node goes down, so we recommend primary affinity instead of hybrid pools.
Resolves #9298 
**Checklist:**

docs: Recommend primary affinity over hybrid pools

---

deploy/examples/osd-purge.yaml

The label was on the job, but not on the pod template, so querying for the pod logs was not working as simply as if we added the label.
Resolves #9429 
**Checklist:**

osd: Add label to osd purge job

---

Documentation/rbd-mirroring.md

Fixed typo from VolmeReplication  to VolumeReplication on the documentation page of RBD-mirroring.
Signed-off-by: Vivek Shinde vivek.j.shinde1@gmail.com
docs: Fixed typo from VolmeReplication  to VolumeReplication
Resolves # 
**Checklist:**

docs: fixed typo on rbd mirroring documentation

---

pkg/operator/ceph/cluster/controller.go
pkg/operator/ceph/cluster/predicate.go
pkg/operator/ceph/controller/predicate.go
pkg/operator/ceph/controller/predicate_test.go
pkg/operator/ceph/csi/controller.go
pkg/operator/ceph/csi/predicate.go
pkg/operator/ceph/disruption/clusterdisruption/add.go
pkg/operator/ceph/object/bucket/controller.go
pkg/operator/ceph/object/bucket/predicate.go

Rook does not support running multiple clusters in the same namespace,
so the operator should not reconcile if a new cluster is added.
The scenario where a cluster is added while the operator is down is also
handled. CR updates are also handled.
When the operator detects more than one cluster it will refuse to
reconcile the CephCluster, and child CRDs will block too until the
operator is ready.
The user must remove one of the clusters before can continue to perform
any reconcile.
Closes: #9452
Resolves  #9452
**Checklist:**

core: disallow multiple clusters in the same namespace

---

images/cross/Dockerfile

A Go net/http bug documented here
https://github.com/golang/go/issues/50058 could potentially affect users
who enable Rook's webhook.
This PR is made direct to release-1.7 because master and release-1.8 don't use the cross container to build release images. This fix isn't needed elsewhere.
Resolves #
**Checklist:**

build: update build to go v1.16.12

---

.github/workflows/canary-integration-test.yml
pkg/clusterd/disk.go
pkg/daemon/ceph/osd/daemon.go
pkg/daemon/ceph/osd/encryption.go
pkg/daemon/ceph/osd/volume.go
pkg/operator/ceph/cluster/osd/create.go
pkg/util/sys/device.go
tests/scripts/github-action-helper.sh

This is handling a tricky scenario where the OSD deployment is manually
removed and the OSD never reconvers. This is unlikely to happen, but
still OSD should be able to run after that action. Essentially after a
manual deletion, we need to run the prepare job again to re-hydrate the
OSD information so that the OSD deployment can be deployed.
On encryption, it is a little bit tricky since ceph-volume list again
the main block won't return anything, so we need to target the encrypted
block to list.
There is another case this PR does not handle, which is the removal of
the OSD deployment and then the node is restarted. This means that the
encrypted container is not opened anymore. However, opening it requires
more work like writing the key on the filesystem (if not coming from the
Kubernete …

osd: handle removal of encrypted osd deployment

---

pkg/operator/ceph/object/notification/controller.go
pkg/operator/ceph/object/notification/controller_test.go
pkg/operator/ceph/object/notification/obc_label_controller.go
pkg/operator/ceph/object/notification/obc_label_controller_test.go
pkg/operator/ceph/object/notification/provisioner.go
pkg/operator/ceph/object/notification/s3ext.go

Current approach is to delete all the existing notifcations from bucket
and re-add the notification from the labels.
Resolves #
**Checklist:**

object: fix handling for notifications for OBC

---

INSTALL.md

If helm is not install, `make` fails with the following log.
```console
./build/rbac/get-helm-rbac.sh: line 25: helm: command not found
```
**Checklist:**
- [o] Reviewed the developer guide on [Submitting a …

build: add missing helm

---

pkg/operator/discover/discover.go
pkg/operator/discover/discover_test.go

So that the tool inside the container has the permission to run
correctly, e.g: sgdisk.
Clsoes: https://github.com/rook/rook/issues/9493
Resolves  https://github.com/rook/rook/issues/9493
**Checklist:**

core: run discover daemonset as root uid

---

Documentation/ceph-cluster-crd.md
Documentation/ceph-object-store-crd.md
deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/cluster.yaml
deploy/examples/crds.yaml
deploy/examples/object.yaml
pkg/apis/ceph.rook.io/v1/probe.go
pkg/apis/ceph.rook.io/v1/types.go
pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
pkg/operator/ceph/cluster/mgr/spec.go
pkg/operator/ceph/cluster/mon/spec.go
pkg/operator/ceph/cluster/osd/spec.go
pkg/operator/ceph/config/livenessprobe.go
pkg/operator/ceph/config/livenessprobe_test.go
pkg/operator/ceph/controller/spec.go
pkg/operator/ceph/controller/spec_test.go
pkg/operator/ceph/file/mds/spec.go
pkg/operator/ceph/object/spec.go

Allow specifying daemon startup probes where we also allow configuring
liveness probes. Startup probes allow Rook to tolerate when Ceph daemons
occasionally take a long time to start up while not also making
Kubernetes liveness probes slower to detect runtime failures of daemons.
Startup probes are beta in Kubernetes 1.18, so we should not enable
probes by default for earlier Kubernetes versions.
TODO:
**Note:** turns out, tests on k8s 1.16 don't fail if resources contain startup probes. I think k8s must silently ignore the config there. Good news for us. We don't have to check the k8s version after all.
Resolves #9401
**Checklist:**

core: rgw: allow specifying daemon startup probes

---

pkg/apis/ceph.rook.io/v1/types.go
pkg/operator/ceph/object/notification/controller.go
pkg/operator/ceph/object/notification/controller_test.go
pkg/operator/ceph/object/notification/obc_label_controller.go
pkg/operator/ceph/object/notification/obc_label_controller_test.go

the events are used to mark the start/finish of the reconciliation
and also to log the bucket names on which the CephbucketNotification is
created
Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>
**Checklist:**

rgw: add events to CephBucketNotification CR

---

Documentation/ceph-cluster-crd.md

Adding section `disruptionManagement` which was removed unintentionally
in #8381.
Resolves #
**Checklist:**

docs: add section for `disruptionManagement`

---

pkg/operator/ceph/object/spec.go
pkg/operator/ceph/object/spec_test.go

It's better to set the same handler to startupProbe as livenessProbe. Otherwise, we might hit the following problem.
https://github.com/rook/rook/issues/6304
**Checklist:**

rgw: fix startup probe

---

.github/workflows/canary-integration-test.yml
Documentation/ceph-monitoring.md
Documentation/ceph-upgrade.md
Documentation/quickstart.md
deploy/examples/direct-mount.yaml
deploy/examples/images.txt
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml
deploy/examples/osd-purge.yaml
deploy/examples/toolbox-job.yaml
deploy/examples/toolbox.yaml

With the patch release the examples and docs are updated to v1.8.2
**Checklist:**

build: Update release version to v1.8.2

---

.github/workflows/canary-integration-test.yml

The local build tag replacement in the CI should work the same whether in master or release branches, so we use a regex to match any rook/ceph tag to be renamed to the local-build tag.
**Checklist:**

build: Replace local build tag with regex

---

deploy/charts/rook-ceph/templates/clusterrole.yaml
deploy/examples/common.yaml

Rook needs to be able to watch all `ceph.rook.io` resources to reconcile
them; however, it does not need blanket verb privileges. Reduce the
privileges as much as possible.
Ideally, Rook would only have update permissions to status and
finalizers of resources; however, finalizers are not a full-fledged
subresource at this time, and "update" permissions must be maintained
for `ceph.rook.io` resources.
What should we do about the `rook-ceph-mgr` `Role` permissions (copied below)?
These are only needed if the user intends to use the rook mgr orchestrator module to control Rook. And I'm not sure if these permissions are fully up to date either (@jmolmo might have a fuller idea of that). Should we move these permissions to another file, …

core: limit use of wildcards in cluster-scoped rbac

---

.github/workflows/canary-integration-test.yml
deploy/examples/create-external-cluster-resources.py

Added a clusterName, poolName , filesystemName, radosNamespace
as a suffix on ceph auth principals for external cluster so
every csi authentication would be unique if
restricted_auth_permission flag is specified.
Closes: https://github.com/rook/rook/issues/9192
Resolves #
**Checklist:**

security: update auth permissions for external cluster

---

cmd/rook/secret.go

Previously we were using the namespace, it's a mistake, even though most
clusters use the same name as the namespace.
Let's be precise and use the cluster name when looking for it.
Resolves #
**Checklist:**

osd: use cluster name when fetching the cephcluster

---

deploy/charts/library/templates/_cluster-monitoring.tpl

right now the RoleBinding for monitoring is created with the cluster namespace as the subject
This causes the operator to loop on reconcile due to it not having permissions to create `ServiceMonitor`s
in the other namespace
moving the subject to the operator namespace fixes this
Resolves #9553
**Checklist:**

helm: use operatorNamespace if exists for monitoring RBAC

---

build/crds/build-crds.sh
build/rbac/keep-rbac-yaml.sh

Linux doesn't guarantee file ordering, so when dealing with files in
order, we can use 'sort' to make sure the order is deterministic. For
yq's usage of files, we need to keep file names in an intermediate
variable, and this should be an array to support file paths with spaces.
'readarray' is not available on MacOS's built-in bash, so a longer
'while read' loop is needed for the array creation.
Resolves #9563 
**Checklist:**

build: make crd/rbac generation order deterministic

---

Documentation/ceph-cluster-crd.md
pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/cluster/mgr/mgr_test.go

When the active mgr changes, there may be user-created services that also need to have their selector updated to point to the new active mgr. Now the operator will update any service in the rook operator namespace that has the label app=rook-ceph-mgr to point to the active mgr.
Resolves #7988 
**Checklist:**

mgr: Update services when active mgr changes

---

Makefile
build/crds/build-crds.sh
build/rbac/keep-rbac-yaml.sh

Simply applying `LC_ALL=C` will work for the current shell only. For all
the shells and sub-shell to use it, we must set it globally.
Making it the first thing in the Make entrypoint now so the CRD and RBAC
sorting works on all the platforms.
Resolves #
**Checklist:**

build: set LC_ALL on the make target

---

Documentation/ceph-monitoring.md
deploy/examples/monitoring/keda-rgw.yaml

Even though mention about keda 2.x version, the scaledObject.yaml or
rgw-keda.yaml referring to older keda CRs
Resolves #
**Checklist:**

docs: update scaledobject.yaml for applicable with keda v2.5

---

.github/workflows/canary-integration-test.yml
deploy/examples/create-external-cluster-resources.py

The CSI users created by the external script(both for rbd and cephfs)
need the blocklist capability so the CSI pods can execute the
`osd blocklist` commands for metro DR
update the mon caps of csi users with `profile simple-rados-client-with-blocklist`
so they have privileges to run osd blocklist cmds
Closes: https://issues.redhat.com/browse/RHSTOR-2451
Resolves #https://issues.redhat.com/browse/RHSTOR-2451
**Checklist:**

csi: Add osd blocklist capabilities to the external cephcluster

---

build/rbac/rbac.yaml
deploy/charts/rook-ceph/templates/psp.yaml
deploy/examples/common.yaml

This commit restrict csiaddons to open only 1 port
as per the requirement which is required for security.
Fixes: #9604
Signed-off-by: yati1998 <ypadia@redhat.com>

csi: restrict csiaddons to use only 1 port

---

deploy/charts/rook-ceph-cluster/templates/volumesnapshotclass.yaml
deploy/charts/rook-ceph-cluster/values.yaml

add support for helm charts to create default volumesnapshotclass for cephfs and rbd.
Resolves #9566
**Checklist:**

csi: add support to create volumesnapshotclass

---

Documentation/ceph-cluster-crd.md
deploy/charts/rook-ceph-cluster/values.yaml
deploy/examples/cluster.yaml
pkg/apis/ceph.rook.io/v1/priorityclasses.go
pkg/apis/ceph.rook.io/v1/priorityclasses_test.go
pkg/operator/ceph/cluster/crash/crash.go
pkg/operator/ceph/cluster/crash/crash_test.go

Support priorityClass to crashcollectos as mons, mgrs, and osds.
https://rook.io/docs/rook/v1.8/ceph-cluster-crd.html#priority-class-names-configuration-settings
The main use case is applying the high priority to crashcollectors to preempt normal pods under heavy load. Without this feature, we might lose crash information.
Closes: https://github.com/rook/rook/issues/9500
Signed-off-by: Satoru Takeuchi <satoru.takeuchi@gmail.com>
Resolves #9500
**Checklist:**

core: support priority class for crashcollector

---

design/ceph/object/swift-and-keystone-integration.md

**Description of your changes:** This adds draft of a design document for adding support for the Ceph RGW Keystone and Swift integration.
This is a first step towards resolving #9088
**Checklist:**

rgw: Design document for the Keystone and Swift integration

---

pkg/operator/ceph/controller/predicate.go
pkg/operator/ceph/csi/controller.go
pkg/operator/ceph/csi/predicate.go
pkg/operator/ceph/csi/predicate_test.go

Previously, we were ignoring configuration changes coming from the
operator's pod env variables. We were assuming most users were using the
operator configmap "rook-ceph-operator-config" but most Helm users
don't. Now we will reconcile if a cephcluster is found during a CREATE
event (can be an operator restart or a cephcluster creation) AND no
"rook-ceph-operator-config" is found which means the operator's pod env
var are used.
Also, unit tests have been added (long due) for the predicate!
Closes: #9602, #9487, #9579
Resolves #9602, #9487, #9579
**Checklist:**

core: reconcile operator configuration with env var

---

pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/cluster_external.go
pkg/operator/ceph/cluster/controller.go
pkg/operator/ceph/cluster/mon/drain_test.go
pkg/operator/ceph/cluster/mon/health_test.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/cluster/mon/mon_test.go
pkg/operator/ceph/cluster/mon/node_test.go
pkg/operator/ceph/cluster/mon/service_test.go
pkg/operator/ceph/cluster/mon/spec_test.go
pkg/operator/ceph/csi/cluster_config.go
pkg/operator/ceph/csi/cluster_config_test.go
pkg/operator/ceph/csi/predicate.go
pkg/operator/ceph/file/subvolumegroup/controller.go
pkg/operator/ceph/file/subvolumegroup/controller_test.go
pkg/operator/ceph/nfs/nfs.go

The rook-ceph-csi-config config map now includes CephFS subvolumegroups
when a subvolumegroup CR is created. It is useful for ceph-csi to
understand which subvolumegroup to use for a given cluster.
Resolves #
**Checklist:**

csi: change rook-ceph-csi-config to expose clusterID for subvolume

---

.github/workflows/canary-integration-test.yml
.github/workflows/daily-nightly-jobs.yml
.github/workflows/encryption-pvc-kms-ibm-kp/action.yml
Documentation/ceph-kms.md
pkg/apis/ceph.rook.io/v1/security.go
pkg/daemon/ceph/osd/kms/envs_test.go
pkg/daemon/ceph/osd/kms/ibm_key_protect.go
pkg/daemon/ceph/osd/kms/ibm_key_protect_test.go
pkg/daemon/ceph/osd/kms/kms.go
pkg/daemon/ceph/osd/kms/kms_test.go
tests/manifests/test-kms-ibm-kp-spec.in

For better consistency with IBM_KP_SERVICE_API_KEY and use
"ibmkeyprotect" as a provider name for more clarity.
Resolves #
**Checklist:**

osd: rename a few configuration flags

---

pkg/operator/ceph/object/bucket/rgw-handlers.go
pkg/operator/ceph/object/bucket/rgw-handlers_test.go

ceph might return NoSuchKey than NoSuchBucket when the target bucket does not exist.
then we can use GetBucketInfo() to judge the existence of the bucket.
see: https://github.com/ceph/ceph/pull/44413
Resolves #9494
**Checklist:**

rgw: handle the non-existence of the bucket correctly when removing bucket

---

pkg/daemon/ceph/client/config_test.go
pkg/daemon/ceph/osd/device_test.go
pkg/daemon/ceph/osd/volume_test.go
pkg/daemon/util/copybins_test.go
pkg/operator/ceph/cluster/mgr/mgr_test.go
pkg/operator/ceph/cluster/mon/health_test.go
pkg/operator/ceph/cluster/mon/mon_test.go
pkg/operator/ceph/file/filesystem_test.go
pkg/operator/ceph/object/rgw_test.go
tests/integration/ceph_base_object_test.go

We can write less code by using the `T.TempDir` function from the `testing` package to create temporary test directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
N/A
**Checklist:**

test: use `T.TempDir` to create temporary test directory

---

pkg/operator/ceph/object/notification/provisioner.go
pkg/operator/ceph/object/topic/provisioner.go
tests/framework/clients/bucket.go
tests/integration/ceph_bucket_notification_test.go
tests/integration/ceph_object_test.go

The certs for accessing TLS enabled RGW is saved as secrets and inject
them if controllers for notification and topics if the request is sent to
TLS enabled RGW endpoint.
Resolves #
**Checklist:**

rgw: inject tls certs for bucket notification and topic operations

---

deploy/charts/library/templates/_cluster-psp.tpl
deploy/charts/library/templates/_cluster-rolebinding.tpl
deploy/charts/library/templates/_recommended-labels.tpl
deploy/charts/library/templates/_suffix-cluster-namespace.tpl
deploy/charts/rook-ceph-cluster/templates/_helpers.tpl
deploy/charts/rook-ceph-cluster/templates/rbac.yaml
deploy/charts/rook-ceph/templates/cluster-rbac.yaml
deploy/charts/rook-ceph/templates/clusterrole.yaml
deploy/charts/rook-ceph/templates/clusterrolebinding.yaml
deploy/charts/rook-ceph/templates/psp.yaml
deploy/charts/rook-ceph/templates/rolebinding.yaml
tests/scripts/helm.sh

- The CI was building with helm 3.6.2, now updating to the latest v3.8.0
- Recent versions of helm are failing the linter on the end tag if the tag is `{{- end -}}`. Instead, the correct end tag is `{{- end }}`.
Resolves #9639 
**Checklist:**

helm: Update CI to the latest helm and fix the linter

---

pkg/daemon/ceph/client/pool.go
pkg/daemon/ceph/client/pool_test.go
pkg/operator/ceph/pool/controller_test.go

If the pool application is already set, skip setting it again to avoid a warning message being logged that it is already set.
**Checklist:**

pool: Check for application already being set

---

pkg/daemon/ceph/client/config.go
pkg/daemon/ceph/client/upgrade.go

See individual commits.
Resolves #
**Checklist:**

core: fix some nits 

---

deploy/examples/osd-env-override.yaml
pkg/operator/ceph/cluster/osd/envs.go
pkg/operator/ceph/cluster/osd/provision_spec.go
pkg/operator/ceph/cluster/osd/spec.go

This is a reworked, implemented in a very different way version of the PR https://github.com/rook/rook/pull/9516.
**Checklist:**

osd: allow for injecting extra env. variables via ConfigMap

---

pkg/operator/k8sutil/resources.go
pkg/operator/k8sutil/resources_test.go

The merging of OSD resource limits and requests assumed that only the cpu and memory resources needed to be merged. It is also possible to set custom resource properties such as intel.com/sriov_net_in: '1' for use with multus, so the merging needs to be more general.
Resolves #9653 
**Checklist:**

osd: Merge all osd resources including custom

---

pkg/operator/ceph/cluster/mon/predicate.go
pkg/operator/ceph/cluster/osd/health.go
pkg/operator/ceph/cluster/rbd/controller.go
pkg/operator/ceph/controller/spec.go
pkg/operator/ceph/file/controller.go
pkg/operator/ceph/file/mirror/controller.go
pkg/operator/ceph/nfs/controller.go
pkg/operator/ceph/object/controller.go
pkg/operator/ceph/object/controller_test.go

Prior to this, we were comparing a pointer (the memory address) with a
struct. This was obviously always failing and returned false. We must
dereference the pointer to access the data contained at that memory
location.
Closes: https://github.com/rook/rook/issues/9544
Resolves https://github.com/rook/rook/issues/9544
**Checklist:**

core: dereference pointer before trying to compare with deepequal

---

tests/framework/utils/snapshot.go

In kubernetes 1.18 we are seeing CRD validation errors when installing with kubectl, adding `validate=false` to skip the validation and to make tests works with kubernetes 1.18
Resolves #9670
**Checklist:**

csi: skip validation when installing snapshotter

---

pkg/daemon/ceph/osd/volume.go
pkg/util/exec/exec.go

In volume.go, remove if condition in `callCephVolume`
method where we always pass false.
In exec.go, removing `ExecuteCommandWithFile*` methods
which was not used anywhere.
Resolves #
**Checklist:**

core: remove obsolete ceph-volume executor code

---

tests/framework/utils/snapshot.go
tests/integration/ceph_base_block_test.go
tests/integration/ceph_base_file_test.go

Currently, we sleep only if the snapshot is not ready and try again, this covers only the happy path. the checks might fail to get the snapshot object or the `.status.readyToUse` might not be set yet. First sleep and then try to check snapshot is ready or not, if we do this we cover all the cases when checking the snapshot ready status. Changed sleep internal to do incremental sleep to give more time for tests.
cleanup the CRD and controller in defer to make sure the CRD and controller are removed as filesystem/block test also install CRD and controller separately.
Resolves #
**Checklist:**

csi: fix snapshot tests

---

pkg/daemon/ceph/client/subvolumegroup.go
pkg/operator/ceph/file/subvolumegroup/controller.go
pkg/operator/ceph/file/subvolumegroup/controller_test.go

If the cluster is external, users might still want to take advantage of
the ceph-csi configmap configuration for ceph filesystem subvolume
group. This configuration is handled by the controller whenever a
cephFilesystemSubVolumeGroup CR is created or deleted.
If the present cluster CephCluster is external, the controller
(cephFilesystemSubVolumeGroup) won't handle creation nor deletion of sub volume groups.
It just assumes that the given name is correct and the controller goes ahead with the
ceph-csi configuration.
Closes: https://github.com/rook/rook/issues/9551
Resolves https://github.com/rook/rook/issues/9551
**Checklist:**

subvolumegroup: handle external mode

---

Documentation/ceph-monitoring.md
Documentation/ceph-upgrade.md
Documentation/quickstart.md
deploy/examples/direct-mount.yaml
deploy/examples/images.txt
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml
deploy/examples/osd-purge.yaml
deploy/examples/toolbox-job.yaml
deploy/examples/toolbox.yaml
tests/framework/installer/ceph_manifests_previous.go

With the patch release we update the example manifests to v1.8.4. At the same time the upgrade tests are updated to use the latest v1.7.11.
**Checklist:**

build: Set release version to v1.8.4

---

pkg/daemon/ceph/osd/volume.go
pkg/daemon/ceph/osd/volume_test.go
pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/cluster/mgr/mgr_test.go
pkg/operator/ceph/version/version.go
pkg/operator/ceph/version/version_test.go

We can eliminate the OSD creation code for Ceph < v15.2.0 because Nautilus(v14.2.z) is no longer supported. In other words, we can now expect that all newly-created OSDs on PVC are raw mode.
Please note that the existing lvm mode OSDs on PVCs still be supported after this change.
**Checklist:**

core: eliminate unnecessary code

---

Documentation/ceph-cluster-crd.md
design/ceph/multus-network.md

Add a section detailing a design to handle the volume-operations-blocked
on CSI restart issue when running with Multus.
See: https://github.com/rook/rook/issues/8085
Resolves #
**Checklist:**

docs: add CSI section to Multus design doc

---

.github/workflows/canary-integration-test.yml
deploy/examples/create-external-cluster-resources.py

Currently if we run external-script and user already exit,
it fails to create/run same user again if the caps are upgraded,
so we need to check first if user is already present.
And for upgrading user we can do upgrade after this
PR: https://github.com/rook/rook/pull/9609 will get merged.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2048458
Resolves #
**Checklist:**

csi: make create and get process separate for csi users

---

pkg/daemon/ceph/client/pool.go
pkg/daemon/ceph/client/pool_test.go
pkg/operator/ceph/file/filesystem.go
pkg/operator/ceph/file/filesystem_test.go
pkg/operator/ceph/object/controller_test.go
pkg/operator/ceph/object/objectstore.go
pkg/operator/ceph/pool/controller.go

The reconcile was skipping updating most pool properties for object stores. The implementation of pools between the file, object, and pool controllers had some duplicate code, so this change also factors out the common code for better reuse in a single place. Anytime a pool is created or updated, it will now consistently update all the pool properties that are expected to be modifiable.
Resolves #9443 
**Checklist:**

object: Update object pool properties during reconcile

---

pkg/operator/ceph/object/controller.go
pkg/operator/ceph/object/controller_test.go

We need to explicitly assign the ceph version within each scope since
one function returns a pointer and one is not.
Previously, the `desiredCephVersion` was recreated in the scope of the
`else` and thus a new variable `desiredCephVersion` was initialized (see
the `:=`).
Now, each scope creates and assign to clusterInfo a `desiredCephVersion`
value.
Resolves #
**Checklist:**

rgw: fix variable assignment

---

deploy/examples/csi/rbd/storageclass.yaml

adding comment after namespace to identify if
it cluster namespace or operator namespace.
Resolves #
**Checklist:**

csi: add comment after namespace

---

pkg/operator/ceph/csi/controller.go
pkg/operator/ceph/csi/csi.go
pkg/operator/ceph/csi/predicate.go
pkg/operator/ceph/csi/spec.go

This commit modifies ceph-csi controller to be able to cleanup
ceph-csi deployment,daemonset,services & csidriver objects
when no cephcluster exists.
It makes the following changes:
- redundant check for tp.DriverNamePrefix is removed.
- retry to start drivers within reconcile loop is removed,
controller will retry in case of error now.
- stopDrivers() will now return error in case of failure.
- predicate delete func will now respond to cephcluster deletion.
- CSI resources will be cleaned up when cephcluster does not exist.
Fixes: #9697
**Checklist:**

csi: cleanup csi driver resources when zero cephclusters exist

---

tests/framework/clients/notification.go
tests/framework/clients/topic.go
tests/framework/installer/ceph_manifests.go
tests/integration/ceph_bucket_notification_test.go
tests/scripts/pythonwebserver/Dockerfile
tests/scripts/pythonwebserver/server.py

Add test cases to check notification is received by http server. For
this a sample HTTP server in https://github.com/thotz/pythonwebserver
used.
Resolves #
**Checklist:**

test: update bucket notification integration test with http server

---

pkg/operator/ceph/cluster/watcher.go
pkg/operator/k8sutil/node.go
pkg/operator/k8sutil/node_test.go

When a node is being skipped for creation of OSDs, log a message that indicates whether it was from the node being unschedulable, the node is not ready, or the node does not meet the placement criteria specified in the cluster CR.
Resolves #9716 
**Checklist:**

osd: Write log message when node is being skipped

---

.github/workflows/canary-integration-test.yml
deploy/examples/create-external-cluster-resources.py

The upgrade function doesn't seem to be that smart
for now so it can update the new auth caps listed
with the existing one, it only compares the value of
the current cap with the MIN_USER_CAP_PERMISSIONS,
Modified the upgrade flag functionality so we can use
this while upgrading the cluster clients
Closes: https://github.com/rook/rook/issues/9589
Resolves #
**Checklist:**

csi: modify upgrade flag in external cluster

---

Documentation/ceph-cluster-crd.md

Add doc to explain why some daemons are not listening to the NAD.
Closes: https://github.com/rook/rook/issues/9488
Resolves https://github.com/rook/rook/issues/9488
**Checklist:**

docs: add multus known limitations

---

pkg/operator/ceph/config/config.go
pkg/operator/ceph/config/defaults.go

Instead of setting the default values in the Rook, we should use the defaults provided by the ceph itself. This configuration is causing a problem for the rbd image creation, this is not allowing the rbd images to have default image features that come with librbd.
* Without this Fix, the rbd images are created with layering features as Rook is setting its own default
```
sh-4.4# rbd create replicapool/test1 --size=1G -m=10.104.250.35:6789 --user=csi-rbd-provisioner --key=AQBnnwRi82AkBRAAzJAGOjbwxppY9KQeYrD6dA==
sh-4.4# 
sh-4.4# rbd info replicapool/test1  -m=10.104.250.35:6789 --user=csi-rbd-provisioner --key=AQBnnwRi82AkBRAAzJAGOjbwxppY9KQeYrD6dA==
rbd image 'test1':
size 1 GiB in 256 objects
order 22 (4 …
```

ceph: remove rbd_default_features setting

---

pkg/daemon/ceph/osd/volume.go
pkg/daemon/ceph/osd/volume_test.go

The OSD prepare job was succeeding even if the OSDs failed to be listed by ceph-volume. These errors should be returned and fail the job, resulting in a retry to retrieve the OSDs. Otherwise, the failure is masked and the admin needs to dig through logs to find why the OSDs were not configured on that node.
This issue was seen in the following osd prepare log:
```
2022-01-26 23:10:36.953577 D | cephosd: desiredDevices are [{Name:/mnt/default-1-data-0f8266 OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: InitialWeight: IsFilter:false IsDevicePathFilter:false}]
2022-01-26 23:10:36.953580 D | cephosd: context.Devices are:
2022-01-26 23:10:36.953596 D | cephosd: &{Name:/mnt/default-1-data-0f8266 Parent: HasChildren:false …
```

osd: Return error if fail to list osds in prepare job

---

.github/workflows/daily-nightly-jobs.yml

PR #9546 missed updating the daily-nightly CI jobs, and logs are no
longer properly collected from the upgrade jobs there.
Of note the [upgrade-from-pacific-stable-to-pacific-devel](https://github.com/rook/rook/runs/5170432545?check_suite_focus=true#logs) test seems flaky, and I wasn't able to debug it since the logs were missing.
Resolves #
**Checklist:**

test: fix upgrade test namespace in daily-nightly CI

---

pkg/daemon/ceph/osd/volume.go
pkg/daemon/ceph/osd/volume_test.go

We can re-enable raw mode OSD on disk if Ceph version is at least v16.2.6.
Resolves #9659
**Checklist:**
- [o] Reviewed the developer guide on [Submitting a …

osd: re-enable raw mode on disk

---

build/rbac/get-helm-rbac.sh
deploy/charts/rook-ceph/templates/role.yaml
deploy/charts/rook-ceph/templates/rolebinding.yaml

We should use csiAddons.enabled to check whether csiAddons is used.
**Checklist:**

helm: fix csiAddons enabled flag

---

pkg/operator/ceph/object/objectstore.go

currently if multisite is not configured Rook sets values for
zone/zonegroup/realm as object store name which is only valid for
internal ceph object store. This may not exists for rgw running in
external cluster.
Resolves #
**Checklist:**

object: set default zone/zonegroup/realm values for external rgw

---

.github/workflows/integration-test-upgrade-suite.yaml
tests/scripts/collect-logs.sh

A few of the nightly tests are failing often, and we were missing logs for many things that would be helpful. Rewrite the log collector to collect all pod logs from cluster and system namespaces, to describe all common k8s resources, and to describe all CRs in those namespaces.
Resolves #
**Checklist:**

test: collect fuller logs for CI tests

---

deploy/charts/rook-ceph-cluster/templates/deployment.yaml
deploy/charts/rook-ceph-cluster/values.yaml
deploy/charts/rook-ceph/templates/deployment.yaml
deploy/charts/rook-ceph/values.yaml

The operator and toolbox pods were not configurable for their priority class in the helm chart. Now the settings are exposed in the values.yaml.
Resolves #9620 
**Checklist:**

helm: Allow setting priority class on operator and toolbox

---

.github/workflows/canary-integration-test.yml
pkg/daemon/ceph/osd/remove.go

The osd destroy command leaves the osd id in use instead of fully purging the osd id. If the osd id is not also removed, it gives the impression that there is still something that needs to be cleaned up from the old osd.
With the osd destroy, the osd id remains as seen here:
```
[rook@rook-ceph-tools-d6d7c985c-gc2p8 /]$ ceph osd tree
ID  CLASS  WEIGHT   TYPE NAME          STATUS     REWEIGHT  PRI-AFF
-1         0.11728  root default                                   
-3         0.11728      host minikube                              
0    hdd  0.03909          osd.0             up   1.00000  1.00000
1    hdd  0.03909          osd.1      destroyed         0  1.00000
2    hdd  0.03909          osd.2             up   1.00000  1.00000
```
Keeping the destroy …

osd: Remove osd with purge instead of destroy

---

deploy/charts/library/templates/_cluster-role.tpl
deploy/examples/common-second-cluster.yaml
deploy/examples/common.yaml
pkg/daemon/ceph/osd/remove.go
pkg/daemon/ceph/osd/remove_test.go
pkg/operator/ceph/cluster/osd/deviceSet.go

The purge job is intended to clean up all the resources related to an OSD that is to be removed. An OSD with a metadata, wal, and data PVC was only cleaning up the data PVC. Now the metadata and wal PVCs will also be cleaned up.
**Checklist:**

osd: Purge job will remove all pvcs for the osd

---

Documentation/ceph-upgrade.md
deploy/examples/cluster.yaml
images/ceph/Makefile

The latest ceph image should be used for the base of the rook image to pick up the latest security releases.
**Checklist:**

build: Update ceph base image to v16.2.7-20220216

---

Documentation/ceph-common-issues.md

Signed-off-by: Junyoung, Sung <wnsdud1861@gmail.com>
**Description of your changes:** 
Looks like markdown link is not valid for `ceph-toolbox.md`, can cause 404 page. 
Resolves #
**Checklist:**

docs: correct ceph toolbox path

---

Documentation/ceph-cluster-crd.md
PendingReleaseNotes.md
deploy/charts/rook-ceph-cluster/values.yaml
deploy/examples/cluster.yaml
tests/framework/installer/ceph_manifests.go

To ensure the mgr is not the single point of failure, the mgr daemon count is now set to 2 by default in the cluster examples.
**Checklist:**

mgr: Set the default count of mgr daemons to 2

---

pkg/operator/ceph/disruption/clusterdisruption/osd.go

The controller for disruption budgets is verbose at cluster creation when the cluster is not yet created, which generates a lot of noise in the log that makes the cluster look unhealthy. This is an expected condition, so we can change this logging to debug level.
For example, lots of these messages:
```
2022-03-03 20:29:42.206920 E | clusterdisruption-controller: failed to check cluster health: failed to get status. . unable to get monitor info from DNS SRV with service name: ceph-mon
[errno 2] RADOS object not found (error connecting to the cluster): exit status 1
```
**Checklist:**

core: Disruption controller log ceph errors in debug level

---

Documentation/helm-ceph-cluster.md
deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
deploy/charts/rook-ceph-cluster/values.yaml

CephFileSystem StorageClass created by helm chart should use the specified pool
in values.yaml rather than hardcode 'data0'
Signed-off-by: mtt0 <retmain@foxmail.com>
Resolves #9826
**Checklist:**

helm: add cephFileSystems storageClass.pool

---

pkg/daemon/ceph/osd/volume.go
pkg/daemon/ceph/osd/volume_test.go

If a specific disk is configured to have more than one OSD per device,
or if it has a metadata device specified, exclude it from raw mode on an
individual basis.
**manual tests run:**
Resolves #9822 
**Checklist:**

osd: disable raw mode for specific disk configs

---

Documentation/helm-operator.md
deploy/charts/rook-ceph/values.yaml

The multiple filesystem support was added in Pacific and no need for a setting that allows the support. The setting was already removed other places from rook in a previous change #8350, these settings were just left behind in the helm chart to be removed now.
**Checklist:**

helm: Remove obsolete setting for enabling multiple filesystems

---

deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml
deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
deploy/charts/rook-ceph-cluster/templates/cephobjectstore.yaml

Fix rook-ceph-cluster helm chart with passing no parameter on CephObjectStore storageclass
Before pull-request:
```
cephObjectStores:
- name: ceph-objectstore
[...]
storageClass:
parameters: {}
```
gives
```
$ helm template . -f values.yaml --debug
Error: YAML parse error on rook-ceph-cluster/templates/cephobjectstore.yaml: error converting YAML to JSON: yaml: line 9: did not find expected key
[...]                                                               
---                                     
apiVersion: storage.k8s.io/v1           
kind: StorageClass                      
metadata:                               
name: s3                              
provisioner: default.ceph.rook.io/bucket
reclaimPolicy: Delete                   
parameters: …
```

helm: fix rook-ceph-cluster helm chart for cephobjectstore storageclass without/empty parameters

---

pkg/operator/ceph/nfs/controller.go
pkg/operator/ceph/nfs/controller_test.go
pkg/operator/ceph/nfs/nfs.go
pkg/operator/ceph/nfs/spec.go

When downscaling CephNFS clusters, be sure to remove secrets and
configmaps. Also be sure to only downscale for the currently-reconciling
CephNFS cluster.
**NOTE:** actually a fairly small PR except the massively expanded unit test
Resolves #
**Checklist:**

nfs: remove secret, configmap when downscaling CephNFS

---

deploy/charts/rook-ceph/values.yaml

helm: `.Values.image.prefix` is not referenced anywhere
Signed-off-by: kahirokunn <okinakahiro@gmail.com>
I looked up what `image.prefix` was and it wasn't used from anywhere.
Values that are not used anywhere should be removed as they invite unnecessary questions.
Resolves #
**Checklist:**

helm: .Values.image.prefix is not referenced anywhere

---

Documentation/helm-ceph-cluster.md
deploy/charts/rook-ceph-cluster/templates/deployment.yaml
deploy/charts/rook-ceph-cluster/values.yaml

The rook-ceph-tools pod doesn't allow the ability to set a resource requests/limits. This commit allows the ability to set those values.
Closes: #9855
Signed-off-by: Tom Hellier <me@tomhellier.com>
Resolves #
**Checklist:**

helm: add resources to rook-ceph-tools pod

---

pkg/operator/ceph/csi/util.go
pkg/operator/ceph/csi/util_test.go

This function was always using an empty string, instead of the extracted resources
Closes: #9867
There is a bug where the configuration items:
* csi.csiCephFSProvisionerResource
* csi.csiCephFSPluginResource
* csi.csiRBDPluginResource
* csi.csiRBDProvisionerResource
Didn't take effect due to using an empty string instead of the serialised resources passed in via configuration
Resolves #9867 
**Checklist:**
- [] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.

core: fix empty string bug

---

pkg/daemon/ceph/osd/kms/vault_api.go

When kube authentication is used, let's clarify the error message and
hopefully lead to a better understanding on where to look for.
It could be misleading to print "token auth" when using kube auth,
although internally a token is used (the JWT from the Service
Account).
Resolves #
**Checklist:**

osd: clarify vault auth error message

---

pkg/operator/ceph/cluster/mon/mon.go

The canary pods are very short-lived pods and are not running ceph in any form. The startup probe was mistakenly enabled for the canary pod, which could cause the pod to fail unexpectedly if the startup probe was triggered after the delay timeout.
Resolves #9843 
**Checklist:**

mon: Disable startup probe on canary pods

---

pkg/operator/ceph/csi/cluster_config.go

If the csi driver was enabled at a later time, the mon endpoints would not be populated. The populate the csi config, either a new cluster reconcile or restarting the operator would be necessary. It is simpler just to update the csi configmap with every reconcile even if the csi driver is not enabled.
This was confusing to hit in my own testing, thus the fix.
**Checklist:**

csi: Populate mon endpoints even if driver not enabled

---

pkg/operator/ceph/cluster/controller.go
pkg/operator/ceph/object/controller.go
pkg/operator/ceph/object/notification/controller.go
pkg/operator/ceph/object/notification/obc_label_controller.go
pkg/operator/ceph/reporting/reporting.go
pkg/operator/ceph/reporting/reporting_test.go

ReportReconcileResult should never be given an object that is nil. It is
impossible to force compile-time checking for this because the object's
type is an interface. We can't force this, but we can rework the
function definition to handle more cases where the object may not be
returned fully-complete, and we can rework callers to return structs
(not pointers-to-structs) so it is less likely a caller will pass nil
to the function.
Resolves #
**Checklist:**

core: rework usage of ReportReconcileResult

---

deploy/examples/create-external-cluster-resources.py

fix incorrect join command
Signed-off-by: vavuthu <vavuthu@redhat.com>
correcting the join command and assign ACCESS_KEY and SECRET_KEY only in case 
of actual run
Resolves #
**Checklist:**

core: fix incorrect join command

---

pkg/operator/ceph/client/controller.go
pkg/operator/ceph/client/controller_test.go
pkg/operator/ceph/cluster/rbd/controller.go
pkg/operator/ceph/cluster/rbd/controller_test.go
pkg/operator/ceph/file/mirror/controller.go
pkg/operator/ceph/file/mirror/controller_test.go
pkg/operator/ceph/nfs/controller.go
pkg/operator/ceph/nfs/controller_test.go
pkg/operator/ceph/object/realm/controller.go
pkg/operator/ceph/object/realm/controller_test.go
pkg/operator/ceph/object/user/controller.go
pkg/operator/ceph/object/user/controller_test.go
pkg/operator/ceph/object/zone/controller.go
pkg/operator/ceph/object/zone/controller_test.go
pkg/operator/ceph/pool/controller.go
pkg/operator/ceph/pool/controller_test.go

adding k8s event in blockpool reconciler when
1. when blockpool reconciler starts
2. when blockpool deletion reconcile triggered.
Closes: https://github.com/rook/rook/issues/9462
Resolves #9462 
**Checklist:**

core: add k8s events in blockpool reconciler

---

.github/workflows/daily-nightly-jobs.yml
deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/cluster-test.yaml
deploy/examples/crds.yaml
pkg/apis/ceph.rook.io/v1/types.go
pkg/operator/ceph/cluster/version_test.go
pkg/operator/ceph/pool/controller.go
pkg/operator/ceph/pool/controller_test.go
pkg/operator/ceph/version/version.go
tests/framework/installer/ceph_installer.go
tests/framework/installer/ceph_manifests.go
tests/framework/installer/ceph_manifests_previous.go
tests/integration/ceph_helm_test.go
tests/integration/ceph_multi_cluster_test.go
tests/integration/ceph_upgrade_test.go

With the Ceph Quincy release coming up at the end of March and the Rook v1.9 release early April:
1. Update the integration tests to add Quincy to the matrix. 
2. Test upgrades from Rook v1.8 to master (instead of v1.7 to master)
3. Add support for the new built-in `.mgr` pool name, which was renamed from `device_health_metrics`.
**Checklist:**

test: Support Ceph Quincy v17 and Rook v1.9 with updated integration tests

---

tests/scripts/github-action-helper.sh
tests/scripts/multi-node/build-rook.sh

Data inconsistency might happen if the disk is accessed just after disk zapping because direct I/O is not synchronous by itself.
**Checklist:**
- [o] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [o] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [o] Documentation …

test: avoid potential data inconsistency on zapping disk

---

pkg/operator/ceph/cluster/mon/health_test.go
pkg/operator/ceph/cluster/mon/mon.go

Older kernels still fail to connect for rbd/cephfs with the msgr2 port due to a difference in http protocol expected. For now, we keep the default port as msgr1 for the csi driver and other client connections, unless msgr2 is strictly required for encryption or compression.
Setting the msgr2 port by default for all new mons had been done in #9118, which was too optimistic.
**Checklist:**

mon: Set the msgr1 port by default for csi driver

---

deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/crds.yaml
pkg/apis/ceph.rook.io/v1/types.go

this commit adding `Phase` in `additionalPrinterColumns` for
all the CRs.
this is how it looks now, example:
```
$ kc get cephfilesystem
NAME   ACTIVEMDS   AGE     PHASE
myfs   1           4m57s   Ready
srai@ ~
$ kc get cephblockpool
NAME                    PHASE
device-health-metrics   Ready
replicapool             Progressing
srai@ ~
$ kc get cephclient
NAME     PHASE
cinder   Ready
glance   Ready
```
Closes: https://github.com/rook/rook/issues/9883
Resolves #9883 
**Checklist:**

core: add `Phase` in `additionalPrinterColumns` for all CRs

---

deploy/charts/rook-ceph-cluster/values.yaml

This commit fixes the missing indentation for nodeAffinity configuration
example in the comment. If users try to use the example configuration by
copy and paste, an error will occur.
Resolves #
**Checklist:**

helm: fix the invalid nodeAffinity configuration in the comment

---

pkg/apis/ceph.rook.io/v1/resources.go

Signed-off-by: Yuval Manor <yuvalman958@gmail.com>
Fix  GetLogCollectorResources function to use the log collector key instead of the crash collector key, for getting the right resources.
Resolves #9897
**Checklist:**

core: fix GetLogCollectorResources to get the right resources

---

deploy/examples/create-external-cluster-resources.py

Corrected CSI_RBD_NODE_SECRET name so it should be
output correctely when called script with
bash format output
Resolves #
**Checklist:**

csi: rbd node secret was misspelled

---

pkg/operator/ceph/csi/spec.go
pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml

This oidc-token is used to authenticate with OpenID Connect (OIDC)
Provider. Ceph-CSI may use it to assume role with amazon STS
to get access to aws kms for encryption.
Refer: https://github.com/ceph/ceph-csi/blob/devel/docs/deploy-rbd.md#configuring-amazon-kms-with-amazon-sts
**Checklist:**

csi: mount serviceaccount oidc-token into csi-driver

---

pkg/daemon/ceph/osd/nsenter.go

Basically nothing else, but `/usr/bin/env` exists on the NixOS-based systems and "installed" binaries reside in `/run/current-system/sw/bin` and `/run/current-system/sw/sbin`
I got a suggestion on [Slack](https://rook-io.slack.com/archives/CK9CF5H2R/p1648820974211349?thread_ts=1648820683.395979&cid=CK9CF5H2R) to simply add those NixOS specific paths
None, didn't create it.
**Checklist:**

osd: add NixOS specific PATHs

---

Documentation/ceph-object.md

Couple of modification to existing example for s3 client regarding how
to access the ceph object store. Added details to fetch the
`BUCKET_NAME`, updated the `AWS_ENDPOINT` and `AWS_HOST` details.
Resolves #
**Checklist:**

docs: update the s3 client example for accesing RGW

---

deploy/examples/object-openshift.yaml

In the `object-openshift.yaml` details about exposing `Routes` for RGW
service, currently, it exposes both ports if they are available. This is
very difficult to manage via the same route like adding a termination policy
etc.
Resolves #
**Checklist:**

object: add details about route for rgw's https endpoint

---

Documentation/development-flow.md

In the development section some
links where not working so fixed them
Closes: https://github.com/rook/rook/issues/10007
Resolves #
**Checklist:**

docs: fix design doc link

---

deploy/examples/cluster-test.yaml

The default replica count for test clusters should be 1. This was causing the rgw-multisite integration test to fail because the PGs were attempting to use the default replication instead of the replication of 1 expected for test clusters. This is being reverted from #9997. 
Resolves #10021 
**Checklist:**

test: Default pool replica size for test cluster is 1

---

deploy/charts/rook-ceph/templates/clusterrole.yaml
deploy/examples/common.yaml

The CSI driver pods dont need to update the node objects for
its operations. This commit remove the unwanted access to node
object update in the RBAC of CSI pods.
Resolves #
**Checklist:**

csi: remove node object update rbac for csi deamonset pods

---

Documentation/flex-to-csi-migration.md

update migraton doc to mentions that
destination storageclass pool name should be
same as one pvc which is going to migrate.
Closes: https://github.com/rook/rook/issues/9986
Resolves #
**Checklist:**

docs: update migraton doc

---

pkg/operator/ceph/cluster/mgr/mgr.go

The ownerref of the prometheus rules should not be set if in a different namespace than the cluster CR.
Resolves #10022 
**Checklist:**

monitoring: Only set prometheus rules ownerref in same namespace

---

deploy/charts/rook-ceph-cluster/templates/prometheusrules.yaml

When the prometheus rules are created, if external settings were not specified, the helm chart would fail due to a nil ref in the external settings. Now we check both for the existence of external settings and whether the external settings are enabled.
There was also an indentation issue with the local rules.
**Checklist:**

helm: Correctly check external cluster for prometheus rules

---

.github/workflows/canary-integration-test.yml
.github/workflows/setup-cluster-resources/action.yaml
deploy/examples/cluster-multus-test.yaml
tests/scripts/github-action-helper.sh
tests/scripts/validate_cluster.sh

This new integration test will deploy a cluster with multus enabled. It
will be comprised of two network interfaces for ceph public and cluster
communications.
For now, it only deploys a Ceph cluster up to the OSDs.
Closes: https://github.com/rook/rook/issues/9784
Resolves #
**Checklist:**

ci: add multus integration test

---

deploy/examples/operator.yaml
go.mod
pkg/operator/k8sutil/node.go
pkg/operator/k8sutil/node_test.go

Fixes: #9711
Adds support for valid arbitrary NodeAffinity JSON input by the user while
maintaining backward compatibility with the older parsing code.
Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>
Resolves #
**Checklist:**

core: support arbitrary node affinity inputs

---

pkg/apis/ceph.rook.io/v1/pool.go
pkg/operator/ceph/pool/validate.go
pkg/operator/ceph/pool/validate_test.go

Built in Ceph pools (device_health_metrics, .mgr, .nfs) must be
replicated and not erasure coded.
Resolves #
**Checklist:**

pool: built-in pools must be replicated

---

deploy/examples/nfs-test.yaml
deploy/examples/nfs.yaml
pkg/operator/ceph/nfs/controller_test.go
pkg/operator/ceph/nfs/nfs.go

Create the ".nfs" config pool by default so that users aren't required
to create it via CephBlockPool.
Is built on top of #10053
Resolves #
**Checklist:**

nfs: create config pool automatically

---

.mergify.yml

The ibm test is not expected to run in PRs, so we can remove it from the list of required backports for the release-1.9 branch.
**Checklist:**

build: Remove requirement for ibm test in backports

---

deploy/examples/operator-openshift.yaml

Fix a small permission (RBAC) issue with the operator-on-openshift.yaml
example's SecurityContextConstraint. A ServiceAccount reference for the
Ceph CSI NFS provisioner was missing.
Resolves #
**Checklist:**

docs: fix nfs permission on openshift example

---

Documentation/ceph-nfs-crd.md

Add some information to NFS docs about how LoadBalancer Service endpoint
and PersistentVolume share field can be used when mounting NFS exports
manually.
Resolves #
**Checklist:**

docs: add info about mounting NFS exports externally

---

deploy/olm/generate-rook-csv.sh

This commit enables csi.nfs during rbac generation
for csv, so that it can used when deployed with olm.
Refer: https://github.com/rook/rook/pull/10058
**Checklist:**

csi: enable csi nfs to generate nfs rbac for csv

---

pkg/operator/ceph/cluster/osd/osd.go

After all OSDs are updated to each major release of Ceph, the require-osd-release version is set to that release so all the latest functionality for osds can be enabled by Ceph. In Quincy there is a warning if all osds are on Quincy and this flag is not set, so this will resolve the health warning.
Resolves #10084 
**Checklist:**

osd: Enable quincy osd release version

---

deploy/charts/rook-ceph-cluster/templates/ingress.yaml
deploy/charts/rook-ceph-cluster/values.yaml

With deprecation of `kubernetes.io/ingress.class annotation`, helm chart should add support for `.spec.ingressClassName`.
Resolves #
**Checklist:**

helm: add ingressClassName field

---

pkg/apis/ceph.rook.io/v1/pool.go
pkg/apis/ceph.rook.io/v1/pool_test.go

Currently, we are allowing users to change the name of the pool to be created in the BlockPool CR. with this we have a bug of leaving stale resources in the cluster. With new changes, we are blocking the update of the pool name in the BlockPool CR.
Resolves #
**Checklist:**

block: validate updating names in BlockPool CR

---

deploy/charts/rook-ceph/values.yaml
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml

Signed-off-by: Yuval Manor <yuvalman958@gmail.com>
1. Add csi-snapshotter resources for csiCephFSProvisioner
2. Add csi-omap-generator resources for csiRBDProvisioner (only if omap generator is enabled)
Resolves #10083
**Checklist:**

helm: fix missing default resources in rook components

---

deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml
deploy/examples/monitoring/localrules.yaml

The new alerts picked up for Rook v1.9 directly from the ceph repo were not all rook-compliant. The alert for the prometheus job not running is not needed since Rook and K8s go to great lengths to keep the mgr pod running already.
The alert for the cluster filling up soon is also disabled until we find how to get the formula working in rook clusters.
@pcuzner Let's discuss the right approach for these alerts in the long term, if there is something better than disabling them.
Resolves #10070 
**Checklist:**

monitoring: Disable new alerts that are not applicable to rook

---

Documentation/ceph-cluster-crd.md
deploy/charts/rook-ceph-cluster/values.yaml
deploy/charts/rook-ceph/values.yaml
deploy/examples/cluster-on-local-pvc.yaml
deploy/examples/cluster-on-pvc.yaml
deploy/examples/cluster-stretched-aws.yaml
deploy/examples/cluster-stretched.yaml
deploy/examples/cluster-test.yaml
deploy/examples/cluster.yaml
deploy/examples/filesystem.yaml
deploy/examples/object.yaml
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml
tests/framework/installer/ceph_helm_installer.go
tests/framework/installer/ceph_manifests.go
tests/framework/installer/ceph_settings.go
tests/framework/utils/k8s_helper.go
tests/integration/ceph_base_deploy_test.go

By default, we should set the priority class to one of the built-in priority class names to ensure that pods critical to the storage will be able to remain running when resources are low. Otherwise, critical rook pods could be evicted and affect many other pods that rely on the storage to continue functioning. 
The options have been available in the CRs, but until now we have just not set the defaults in the examples. Critical rook components are now set to the priority class system-node-critical if they are generally pinned to a node, and system-cluster-critical if they are critical to the storage. Some pods such as the operator and crash collector do not have a default priority class set in the examples since they don't affect the data path.
**Which …

core: Examples set default priority class names

---

deploy/charts/library/templates/_cluster-role.tpl
deploy/charts/library/templates/_cluster-rolebinding.tpl
deploy/examples/common.yaml

The csv will not properly include the rook-ceph-rgw service account unless there is a role and binding that references the service account. No roles are needed yet for the rgw daemon, so this will add a placeholder only for the purposes of csv generation.
**Checklist:**

build: Add a placeholder rgw role for csv generation

---

tests/framework/installer/ceph_manifests.go
tests/integration/ceph_smoke_test.go

The mon failover test was failing if the cluster reconcile was being triggered in the middle of the failover and if the ordering of the mons happened to attempt to start the mons that were not failed over. The other mons couldn't be updated due to the upgrade checks, so the test would timeout waiting for the mons that would never update in time.
**Checklist:**

test: Improve reliability of mon failover test

---

.github/workflows/build.yml
build/makelib/golang.mk

adding support for go 1.18 but rook master still
build on 1.17.
Resolves #
**Checklist:**

build: add support for go 1.18

---

deploy/charts/library/templates/_cluster-role.tpl
deploy/examples/common.yaml

With https://github.com/rook/rook/pull/10108 a placeholder role and role binding were added for the rgw service account so the csv generation would generate the service account. That workaround also requires a rule to be added to the role or else the generation is invalid. Now a rule is added to avoid that issue. In the future we need to remove this role and binding when the operator sdk is updated as explained in https://github.com/rook/rook/issues/10141
Related to #10141
**Checklist:**

build: Add a placeholder rule to the RGW RBAC

---

pkg/operator/ceph/cluster/cluster_external.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/csi/cluster_config.go
pkg/operator/ceph/csi/cluster_config_test.go
pkg/operator/ceph/file/subvolumegroup/controller.go
pkg/operator/ceph/pool/radosnamespace/controller.go

If a mon is added or removed in a ceph cluster all the CSI clusterID belonging to the ceph cluster should also get updated.
Added a new cluster identifier to the csi configmap, i.e ceph cluster namespace which helps to identify the clusterID belongs to that ceph cluster.
Note:- To support the upgraded clusters,we can ask users to update the mon IPs for the problamatic clusterID as it won't be updated by the operator.
Resolves #10126 
**Checklist:**
@travisn this is the other approach as discussed. PTAL

csi: add/remove mon IP from csi config

---

deploy/charts/rook-ceph-cluster/templates/ingress.yaml

ingressClassName can't be set on clusters 1.20+ since it uses networking.k8s.io/v1
Resolves #
**Checklist:**

helm: ingressClassName should be available for networking.k8s.io/v1

---

pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/cluster_test.go
pkg/operator/ceph/cluster/controller_test.go
pkg/operator/ceph/cluster/crash/crash_test.go
pkg/operator/ceph/cluster/mgr/spec_test.go
pkg/operator/ceph/cluster/mon/spec.go
pkg/operator/ceph/cluster/osd/integration_test.go
pkg/operator/ceph/cluster/osd/osd.go
pkg/operator/ceph/cluster/osd/spec_test.go
pkg/operator/ceph/controller/spec_test.go
pkg/operator/ceph/controller/version.go
pkg/operator/ceph/file/mds/spec.go
pkg/operator/ceph/object/bucket/provisioner.go
pkg/operator/ceph/object/controller_test.go
pkg/operator/ceph/object/objectstore.go
pkg/operator/ceph/object/spec.go
pkg/operator/ceph/pool/controller_test.go
pkg/operator/ceph/pool/validate.go
pkg/operator/test/client.go
tests/integration/ceph_base_file_test.go

This removes double package imports. Example:
```
"github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
cephv1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
```
Only one is now being used as shown in [go-staticcheck
ST1019](https://staticcheck.io/docs/checks#ST1019).
**Checklist:**

core: remove double imported packages

---

.github/workflows/golangci-lint.yaml
Makefile
go.mod
go.sum
pkg/operator/ceph/object/user/controller.go
pkg/operator/ceph/object/user/controller_test.go

updating go ceph version to 0.15.0 will no longer require
`ceph_preview` during build. Also if added in VsCode workspace
we can remove that now.
Resolves #
**Checklist:**

build: update go-ceph version and remove ceph_preview

---

tests/scripts/generate-tls-config.sh

sometimes, it take few seconds to fill certificate
after certificate approval. So, let's wait for few seconds.
Closes: https://github.com/rook/rook/issues/10158
Resolves #10158 
**Checklist:**

ci: wait for cert while deploying vault

---

pkg/operator/ceph/object/admin.go
pkg/operator/ceph/object/controller.go
pkg/operator/ceph/object/controller_test.go
pkg/operator/ceph/object/objectstore.go
pkg/operator/ceph/object/objectstore_test.go
pkg/operator/ceph/object/rgw.go
pkg/operator/ceph/object/user.go
tests/integration/ceph_base_object_test.go
tests/integration/ceph_helm_test.go
tests/integration/ceph_object_test.go
tests/integration/ceph_smoke_test.go
tests/integration/ceph_upgrade_test.go

Check the radosgw-admin realm user list per object store instead of relying
on the ceph dashboard get-rgw-api- command.
Resolves #9099
**Checklist:**

rgw: fix dashboard admin creation for multiple object stores

---

deploy/charts/rook-ceph/values.yaml

The operator is very bursty and when starting up may need more memory to reconcile all the CRs initially before it calms down. The default of 256Mi was not sufficient for many clusters, so now we bump up the limit to 512Mi.
Resolves #10192 
**Checklist:**

helm: Increase memory limit of operator

---

.github/workflows/canary-integration-test.yml
pkg/daemon/ceph/cleanup/disk.go
pkg/daemon/ceph/osd/encryption.go
pkg/daemon/ceph/osd/encryption_test.go
pkg/daemon/ceph/osd/volume.go
pkg/operator/ceph/cluster/osd/osd.go
tests/scripts/github-action-helper.sh

Once we are done cleaning up the content of the encrypted osd, let's
close the main LUKS device.
This avoids having dm devices on the system after the cleanup.
Closes: https://github.com/rook/rook/issues/10181
Resolves https://github.com/rook/rook/issues/10181
**Checklist:**

osd: close the encrypted disk after cleanup is done

---

deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml

The operator is very bursty and when starting up may need more memory to reconcile all the CRs initially before it calms down. The default of 256Mi was not sufficient for many clusters, so now we bump up the limit to 512Mi.
This is a follow-up from the same change to the helm chart in https://github.com/rook/rook/pull/10195.
**Checklist:**

operator: Increase memory limit of operator

---

.commitlintrc.json
deploy/charts/rook-ceph-cluster/values.yaml

Two small changes to address the following:
* [helm: update rook-ceph-cluster dashboard values comments](https://github.com/rook/rook/commit/8b6e5e8ba149582965e6f78016b42aa95bfff46c)
* [ci: fix indentation in .commitlintrc.json](https://github.com/rook/rook/commit/f657cb7861dab8963567770aea856200a80b76d5)
**Checklist:**

tweak rook-ceph-cluster dashboard values comments and fix indentation in commitlintrc config

---

pkg/operator/ceph/version/version.go
pkg/operator/ceph/version/version_test.go

Since Quincy is released, Ceph master builds will soon be tagged with the reef v18 version. This adds the capability for rook to check for the reef version of Ceph.
Needed for #10208.
**Checklist:**

core: Add reef version info

---

pkg/clusterd/disk.go
pkg/daemon/discover/discover.go
pkg/util/sys/device.go

- disk UUID should only be got for "disk" type device.
- It's not necessary to fail prepare job when failing to get disk UUID
- We should consider that `sgdisk` reports UUID even if there is no GPT.
Resolves #9948
**Checklist:**

osd: fix disk uuid management

---

pkg/clusterd/disk.go
pkg/daemon/ceph/osd/daemon.go
pkg/util/sys/device.go

hen detecting the device property the filesystem was not passed but
used later to validate if the device should be taken or not. Now we read
the filesystem info from "lsblk" and populate it in the device type.
Resolves #9470
**Checklist:**

core: append filesystem property on disk

---

.github/workflows/canary-integration-test.yml

THe radosnamespace CRD is already added by
https://github.com/rook/rook/pull/9733,
Checking the external script with the namespace created by
the CRD
Resolves #
**Checklist:**

namespace: adding radosnamespace in canary CI

---

.commitlintrc.json
pkg/apis/ceph.rook.io/v1/cluster.go
pkg/apis/ceph.rook.io/v1/cluster_test.go

we should iterate older clusters spec instead of
new cluster spec since in case of new storageClassdeviceset
added in spec. The total count of the new clusters and older
spec cluster is will not be the same and we'll get panic.
Closes: https://github.com/rook/rook/issues/10222
Resolves #10222 
**Checklist:**

webhook: update the check-in cluster spec validation

---

deploy/charts/library/templates/_cluster-psp.tpl
deploy/examples/common.yaml

This commit adds psp RoleBindings to rook-ceph-rgw role and
rook-ceph-purge-osd role. Without this commit, I cannot perform
rook-ceph-purge-osd job on PSP-enabled cluster.
Signed-off-by: Yuichiro Ueno <ueno@preferred.jp>
Resolves #10243 
**Checklist:**

build: add psp for missing roles

---

pkg/operator/ceph/controller/spec.go

The startup probe for the OSD has been too aggressive to kill the OSD in case the OSD is taking some time to start. The OSD may be self-optimizing, scrubbing, or some other internal operation before it is ready to start. Rather than disable the startup probe completely, the default is now to retry for two hours in case the OSD is performing those operations.
Resolves #10196 
**Checklist:**

osd: Allow the osd to take a long time to start

---

deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml

In the `deploy/examples/operator.yaml` file, the correct name for the control plane toleration key is `node-role.kubernetes.io/control-plane` instead of `node-role.kubernetes.io/controlplane`.
Resolves #
**Checklist:**

docs: update tolerations name from controlplane to control-plane

---

pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/config/monstore.go

Beginning with a Draft PR, I'd like to solicit some feedback from the Ceph community members most involved with telemetry to ensure that:
1. This does not risk the anonymity of Ceph clusters, AND
2. That this field will actually allow telemetry to identify Rook clusters
-----
Ceph upstream telemetry (which Rook users could optionally enable via
Ceph CLI or Dashboard) does not easily identify if a cluster is managed
by Rook. Identifying Rook clusters is possible only if users also enable
the rook mgr module, which is optional and not often used.
To get better upstream insights into Ceph clusters managed by Rook, set
a new 'rook-version' field in Ceph's generic k/v store. This field can
be used to determine if a cluster is managed by Rook by its presence.
It additionally provides …

operator: set 'rook-version' in mon k/v store

---

pkg/operator/ceph/cluster/osd/spec.go

We don't need to run any `cp` command since a destination path already
exists. Using `--no-clobber` is not needed and it results in a noop
anyways.
Instead, let's print the reason why we exit the container.
Resolves #
**Checklist:**

osd: exit immediately if pvc block has not changed

---

deploy/examples/create-external-cluster-resources-tests.py
deploy/examples/create-external-cluster-resources.py

Now rgw can be pass by FQDN too,
to avoid problems where it is required
The format should be similar to
Ip(<IP>:<PORT> format), <FQDN>:<PORT> format
Resolves #
**Checklist:**

rgw: support FQDN for RGW endpoint

---

.github/workflows/canary-integration-test.yml
deploy/examples/create-external-cluster-resources-tests.py
deploy/examples/create-external-cluster-resources.py
images/ceph/Makefile

The ceph-external-cluster-details-exporter.py
generates the json output even with
rgw-endpoint IP from different cluster
Added a check validate_rgw_endpoint which will validate
the above rgw_endpoint Ip by matching the cluster fsid
Resolves #
**Checklist:**

rgw: validate rgw endpoint ip

---

deploy/charts/rook-ceph-cluster/templates/cephcluster.yaml
deploy/charts/rook-ceph-cluster/templates/prometheusrules.yaml
deploy/charts/rook-ceph-cluster/values.yaml

The cephcluster CR monitoring schema should be honored. The helm chart was creating extra values that didn't match the schema by copying the values such as createPrometheusRules that are only used for template evaluation. Now only the monitoring values from the schema will be added to the template.
Resolves #10267 
**Checklist:**

helm: Only copy relevant monitoring settings

---

pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/telemetry/telemetry.go

The Rook and Ceph teams settled on using slashes to separate Rook
telemetry items into a hierarchy in https://github.com/rook/rook/pull/10254.
Rename the config-key used to `rook/version`, and create a `telemetry`
package to define the telemetry key constants.
Note: was originally added here: #10161
Resolves #
**Checklist:**

operator: rename telemetry rook-version to rook/version

---

.docs/overrides/main.html
build/release/Makefile

This should fix the banner url when on the `latest` or old doc versions, to correctly point to the latest release ("alias").
Resolves #
**Checklist:**

docs: use absolute path for latest-release

---

pkg/operator/ceph/cluster/osd/spec.go

During the tini's binary removal you overlooked that scenario and
introduced a bug in the OSD startup line.
We were passing the binary path as an argument, which is obviously wrong
and makes the OSD crash at boot.
Resolves #
**Checklist:**

osd: remove broken argument

---

.github/workflows/push-build.yaml

The push image build CI action is mistakenly running on arm64 instead of amd64, which is failing the build since it only expects amd64. The ubuntu 20.04 runner always seems to use arm instead of amd with 18.04, so let's try reverting to 18.04 for now.
This partially reverts #10289.
Resolves #10282 
**Checklist:**

build: Correct architecture for the release build

---

.github/workflows/push-build.yaml

The setup tools package is required on ubuntu 18.04 in order to install the mkdocs framework and publish the docs.
Resolves #10282 
**Checklist:**

build: Add setup tools package for docs publish

---

build/release/Makefile

With the full rework of the docs framework, we cannot support automated updating of docs from branches where the doc framework has not been backported. We are largely done with the 1.8 releases, so we can just disable publishing the docs for the 1.8 branch. If further updates are required in the docs, we can update the legacy docs directly in the rook.github.io repo.
Resolves #10282 
**Checklist:**

build: disable docs build in 1.8 branch

---

deploy/examples/create-external-cluster-resources.py

Currently cephfs caps are data=filesystemname,
which only have write access, but not the read access
changing it to *=filesystemname so we can read data also
Resolves #
**Checklist:**

csi: update cephfs osd caps

---

.github/workflows/rgw-multisite-test/action.yml
Documentation/CRDs/ceph-cluster-crd.md
Documentation/Upgrade/ceph-upgrade.md
deploy/charts/rook-ceph-cluster/values.yaml
deploy/examples/cluster-external-management.yaml
deploy/examples/cluster-on-local-pvc.yaml
deploy/examples/cluster-on-pvc.yaml
deploy/examples/cluster-stretched-aws.yaml
deploy/examples/cluster-stretched.yaml
deploy/examples/cluster.yaml
deploy/examples/images.txt
deploy/olm/assemble/metadata-common.yaml
design/ceph/ceph-cluster-cleanup.md
images/ceph/Makefile

In release 1.9, the operator base image has been changed to
ceph v16.2.9
Resolves #
**Checklist:**

build: update examples and base image to use ceph v16.2.9

---

pkg/operator/ceph/file/filesystem.go

The path resolved the problem that the variable pool is the same as the package name. (bug #9275)
Signed-off-by: fengjiankui <fengjiankui@github.com>
Resolves #9275 
**Checklist:**

mds: pool changed to cephpool

---

pkg/daemon/ceph/client/pool.go
pkg/operator/ceph/nfs/nfs.go

Ceph added a check recently that prevents creation of the built-in pools that start with a dot, such as .nfs, .mgr, and .rgw.root. These pools require a --yes-i-really-mean-it flag to be passed to force the creation now.
This has been causing the daily tests to fail on the latest master builds.
The change in ceph requiring the flag to force creation for built-in pools is seen here: https://github.com/ceph/ceph/pull/44911
Resolves #10013 
**Checklist:**

pool: Built-in pools require flag to force creation

---

pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml

This argument in csi-provisioner and csi-snapshotter sidecar allows us
to receive additional metadata in the CreateVolume and CreateSnapshot()
request.
For ex:
as part of CreateVolume request:
csi.storage.k8s.io/pvc/name
csi.storage.k8s.io/pvc/namespace
csi.storage.k8s.io/pv/name
and
as part of CreateSnapshot request:
csi.storage.k8s.io/volumesnapshot/name
csi.storage.k8s.io/volumesnapshot/namespace
csi.storage.k8s.io/volumesnapshotcontent/name
This is useful information that can be used depending on the use case we have
at our csi driver level. The features like adding metadata to CephFS subvolume,
RBD image or snapshot can consume this based on the need.
Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>
**Checklist:**

csi: add --extra-create-metadata arg to csi sidecars

---

deploy/charts/rook-ceph/templates/clusterrole.yaml
deploy/examples/common.yaml

rbd node plugin needs volumeattachment RBAC to remount, the volume in case of the nbd driver is used to mount the volume.
```
E0531 04:50:56.553128     589 rbd_healer.go:141] list volumeAttachments failed, err: volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-rbd-plugin-sa" cannot list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope
E0531 04:50:56.553147     589 driver.go:198] healer had failures, err volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-rbd-plugin-sa" cannot list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope
```
Found this in CI run …

csi: add volumeattachment list rbac

---

deploy/charts/rook-ceph-cluster/values.yaml

Signed-off-by: Denis O <denis.o@linux.com>
During preparation for deployment of rook noticed that links from helm values point to invalid locations which is quite annoying for learning supported configurations
**Checklist:**

docs: updated links to CRD objects in helm chart 

---

.github/workflows/build.yml
.github/workflows/canary-integration-test.yml
.github/workflows/codegen.yml
.github/workflows/codespell.yaml
.github/workflows/commitlint.yml
.github/workflows/crds-gen.yml
.github/workflows/golangci-lint.yaml
.github/workflows/helm-lint.yaml
.github/workflows/integration-test-helm-suite.yaml
.github/workflows/integration-test-mgr-suite.yaml
.github/workflows/integration-test-multi-cluster-suite.yaml
.github/workflows/integration-test-object-suite.yaml
.github/workflows/integration-test-smoke-suite.yaml
.github/workflows/integration-test-upgrade-suite.yaml
.github/workflows/linters.yaml
.github/workflows/mod-check.yml
.github/workflows/rbac-gen.yaml
.github/workflows/shellcheck.yaml
.github/workflows/unit-test.yml

stop the in-progress jobs when a PR is updated
Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run
Resolves #
**Checklist:**

ci: stop inprogress jobs when pr is updated

---

pkg/apis/ceph.rook.io/v1/pool.go
pkg/apis/ceph.rook.io/v1/pool_test.go
pkg/operator/ceph/pool/controller.go
pkg/operator/ceph/pool/controller_test.go
pkg/operator/ceph/pool/validate.go

During deletion of a CephBlockPool CR, the underlying ceph pool was not being deleted. During the deletion sequence this is due to the spec being refreshed upon a call to check for dependents in ReportDeletionNotBlockedDueToDependents(). The pool name was then coming up blank during the deletion request and rook of course then wasn't finding the pool to delete.
Now Rook properly sets the pool name in the named spec every time it is converted internally from a CephBlockPool type to a NamedPoolSpec.
This does not repro in v1.8.9, it seems to be a regression in v1.9.
Resolves #10360 
**Checklist:**

pool: Delete ceph pool when blockpool cr is deleted

---

deploy/examples/create-external-cluster-resources.py

During the recent additions of rgw validation
changes there are too many places where we use
rgw endpoint, so making fqdn to ip conversion globally
Resolves #
**Checklist:**

rgw: make fqdn rgw converted to ip everywhere

---

.github/workflows/setup-cluster-resources/action.yaml

The minikube node is staying in NotReady state and preventing the operator from even starting in the canary and other suites that use the setup-cluster-resources action.
The failing tests are all waiting for the osd prepare pods to start, but the cluster doesn't get near that far since the operator is stuck pending for the node to get to Ready state.
**Checklist:**

build: Flannel flag to minikube is causing test failures

---

.github/workflows/setup-cluster-resources/action.yaml

adding cni flag in minikube start command
since it is required for multus ci.
Resolves #
**Checklist:**

ci: add new cni flag in minikube start

---

pkg/operator/ceph/cluster/osd/topology.go
pkg/operator/ceph/cluster/osd/topology_test.go

Ceph requires all topology label being unique. And it is quite common to
have topology.kubernetes.io/region and topology.kubernetes.io/zone being set
to the same value. In this case, let's just ignore the region label.
See https://github.com/rook/rook/issues/9419#issuecomment-1144311818
**Checklist:**

osd: ignore the region label when it is the same as zone label in topology

---

pkg/daemon/ceph/osd/kms/kms_test.go
pkg/daemon/ceph/osd/kms/vault.go
pkg/operator/ceph/object/spec_test.go

Return the error instead of hiding it, err could be non-nil for a lot of
reasons, eg: a canceled context or a non-existing object.
Resolves #
**Checklist:**

osd: do not hide the error

---

.github/workflows/rgw-multisite-test/action.yml
Documentation/CRDs/ceph-cluster-crd.md
Documentation/Upgrade/ceph-upgrade.md
deploy/charts/rook-ceph-cluster/values.yaml
deploy/examples/cluster-external-management.yaml
deploy/examples/cluster-on-local-pvc.yaml
deploy/examples/cluster-on-pvc.yaml
deploy/examples/cluster-stretched-aws.yaml
deploy/examples/cluster-stretched.yaml
deploy/examples/cluster.yaml
deploy/examples/images.txt
deploy/olm/assemble/metadata-common.yaml
design/ceph/ceph-cluster-cleanup.md
images/ceph/Makefile

The operator base image has been changed to
ceph v17.2.0 quincy release version `quay.io/ceph/ceph:v17.2.0`
Closes: https://github.com/rook/rook/issues/10140
Resolves #
**Checklist:**

build: Update examples and base image to use Ceph v17.2.0 Quincy version

---

deploy/examples/create-external-cluster-resources-tests.py
deploy/examples/create-external-cluster-resources.py

`black` is python formatter tool which
automatically formats python files without
manual changing. just run `black <python-file>`
and done.
Resolves #
**Checklist:**

external: format python files using tool black

---

.github/workflows/canary-integration-test.yml
pkg/operator/ceph/csi/controller.go
pkg/operator/ceph/csi/spec.go
pkg/operator/ceph/csi/spec_test.go
pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml
pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml
pkg/operator/ceph/csi/version.go
pkg/operator/ceph/csi/version_test.go
tests/scripts/github-action-helper.sh
tests/scripts/validate_cluster.sh

If csi is configured not the use the hostnetworking, deploy the holder pod for executing the commands with nsenter.
The implementation is the same as multus.
Resolves #
**Checklist:**
Note:
```
Added DNM label as testing is still pending
```

ceph: Add holder pod if csi host networking is disabled

---

pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/cluster_test.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/cluster/telemetry/telemetry.go
pkg/operator/ceph/csi/spec.go

For the ceph telemetry report the csi version, k8s version, and metrics from the desired state in the cephcluster CR such as mon count, stretch cluster, number of device sets, and so on.
This is the next round of rook telemetry reported as defined in the [telemetry design doc](https://github.com/rook/rook/blob/master/design/ceph/ceph-telemetry.md).
**Checklist:**

core: Report basic cluster and version telemetry

---

.github/workflows/canary-integration-test.yml
Documentation/Getting-Started/Prerequisites/prerequisites.md
pkg/operator/ceph/cluster/osd/spec.go
tests/scripts/github-action-helper.sh

- encrypted OSD on device don't startup a if Ceph applied [this change](https://github.com/ceph/ceph/commit/25655e5a8829e001adf467511a6bde8142b0a575).
- It's better to test the creation of encrypted devices in host-based clusters. This test will reduce the potential risks of regression
when modifying the osd-creation code.
Resolves: #10375
**Checklist:**

test: Fix encrypted OSDs on latest Ceph releases and add canary test for encrypted osd in host-based cluster

---

deploy/examples/cluster-stretched-aws.yaml
deploy/examples/cluster-stretched.yaml

From kube v1.24 onwards, Kubeadm applies a "node-role" label to its
control plane Nodes.Currently this label key is node-role.kubernetes.io/master
and it will be renamed to node-role.kubernetes.io/control-plane. Kubeadm
also uses the same "node-role" as key for a taint it applies on control
plane Nodes. This taint key should also be renamed to
"node-role.kubernetes.io/control-plane".
Resolves #https://github.com/rook/rook/issues/10398
**Checklist:**

mon: update node labels as per new key value

---

.github/workflows/canary-integration-test.yml

A seprate version test was introduce for rgw-endpoint
but from now as we are using quincy in master so
we can remove it and update the current canary test.
Resolves #
**Checklist:**

ci: remove the seprate quincy test

---

.github/workflows/canary-integration-test.yml
Documentation/CRDs/ceph-cluster-crd.md
deploy/examples/create-external-cluster-resources.py
deploy/examples/import-external-cluster.sh

For using restricted auth users we need to update the
restricted users in the Storage class, so updating
it in the json output for external cluster
(cherry picked from commit b7c165b41103b3d98731f6c31f5ad4dde1b9054d)
Original PR: https://github.com/rook/rook/pull/10278
Resolves #
**Checklist:**

csi: make storage class updated with csi-users in external cluster (backport #10278)

---

Documentation/CRDs/ceph-cluster-crd.md

With the new holder pod that was implemented for the csi driver to maintain a consistent network endpoint across csi plugin restarts, there is no longer a limitation that needs to be documented.
**Checklist:**

docs: Remove obsolete limitation from multus docs

---

pkg/daemon/ceph/osd/daemon.go
pkg/operator/ceph/cluster/osd/spec.go

Ancient OSDs based on LVM and activated by the Rook binary are still in
production. They fail on the deactivation of the VolumeGroup due to
incorrect filter. Setting the OSD as LVM adjusts the filter and make the
deactivate call working.
Repro without and with the correct filter:
```
[root@ca862389706c /]# vgchange -an -vv ceph-a8ae9f01-a440-4a0e-8e4d-592d3bce3a9d
global/use_lvmpolld not found in config: defaulting to 1
devices/sysfs_scan not found in config: defaulting to 1
devices/scan_lvs not found in config: defaulting to 0
devices/multipath_component_detection not found in config: defaulting to 1
devices/md_component_detection not found in config: defaulting to 1
devices/fw_raid_component_detection not found in config: defaulting to 0 …
```

osd: add lvm flag for lvm osd activate

---

deploy/charts/rook-ceph/templates/clusterrole.yaml
deploy/examples/common.yaml

This rbac is required to fetch serviceaccount
token for vault tenant sa encryption type on k8s 1.24+.
refer: https://github.com/ceph/ceph-csi/pull/3174
Resolves #
**Checklist:**

csi: add token create rbac for rbd csi clusterrole

---

pkg/operator/ceph/controller/spec.go
pkg/operator/ceph/controller/spec_test.go

we have noticed multiple failures because of the probe
failing, most of the time it's due to fewer resources.
But increasing timeout fixes that, so increasing the
probe timeout to 2s from default 1s so that it will
give more time to probe before failing.
Resolves #
**Checklist:**

core: increase liveness probe timeout to 2s

---

pkg/operator/discover/discover.go

regulate the variable names to unite standard
Signed-off-by: xakdwch <xakdwch@163.com>
Resolves #
**Checklist:**

operator: discovery parameters use camelCase instead of snake_case

---

pkg/daemon/ceph/client/filesystem.go
pkg/daemon/ceph/client/filesystem_test.go
pkg/operator/ceph/file/controller.go
pkg/operator/ceph/file/controller_test.go
pkg/operator/ceph/file/dependent.go
pkg/operator/ceph/file/dependent_test.go
pkg/operator/ceph/file/filesystem.go
tests/framework/clients/filesystem.go
tests/framework/installer/ceph_manifests.go
tests/framework/installer/ceph_manifests_previous.go
tests/framework/utils/k8s_helper.go
tests/integration/ceph_base_file_test.go

Block deletion of CephFilesystems when there are any raw Ceph
subvolumegroups present that have subvolumes in them. Empty
subvolumegroups will not block deletion.
One important subvolume group is "csi" which is the default location
where CSI subvolumes are kept. If this group is empty, it means that
there are no PVCs created based on the CephFilesystem in question. This
also holds true if there are external consumers of the filesystem in
external cluster mode.
Similarly, if there are any subvolumegroups (for example "_nogroup",
which includes subvolumes in the filesystem root) that contain
manually-created subvolumes, Rook will also see this and block deletion.
This comes into play currently with manually-created NFS exports.
A work-in progress aims to create a Ceph-CSI NFS export …

file: block deletion on more dependents

---

Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md

This commit updates doc to point the k8s-csi-addons
controller links to release v0.4.0.
Refer: https://github.com/csi-addons/kubernetes-csi-addons/releases/tag/v0.4.0
Resolves #
**Checklist:**

doc: update k8s-csi-addons controller links to v0.4.0

---

deploy/charts/rook-ceph-cluster/values.yaml

in helm charts default value of osd prepare pods
limit was less so increased it to 400Mi
Resolves # closes: https://github.com/rook/rook/issues/10477
**Checklist:**

osd: increase memory of osd prepare pods

---

pkg/operator/ceph/cluster/crash/crash.go
pkg/operator/ceph/cluster/crash/reconcile.go

earlier we're deleting v1beta1 always before creating
v1 job. Now, we delete only when k8s version is
latest(which supports v1  job) and v1 job is not created
which means this is the first time and this is the only time we'll
delete v1beta1.
Resolves #
**Checklist:**

core: delete v1beta1 cronjob only when v1 not found

---

pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml

Kubernetes 1.24 and newer use a different path for staging the volume.
That means the CSI-driver is requested to mount the volume at an other
location, compared to previous versions of Kubernetes.
The backward compatibility should be taken care by the CSI driver.
See-also: kubernetes/kubernetes#107065
Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

csi: fix stagingpath

---

pkg/operator/ceph/cluster/cephstatus.go
pkg/operator/ceph/cluster/cephstatus_test.go
pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/config/config.go
pkg/operator/ceph/config/config_test.go

In new deployments we always want to disable the insecure global id in versions of ceph where it is supported. If the mgr deployment is newly created, we know it's a new cluster and the mons are in quorum, so we can go ahead and disable the insecure global IDs.
**Checklist:**

mon: Disable insecure global ids for new deployments

---

.github/workflows/build.yml
.github/workflows/canary-integration-test.yml
.github/workflows/integration-test-helm-suite.yaml
.github/workflows/integration-test-mgr-suite.yaml
.github/workflows/integration-test-multi-cluster-suite.yaml
.github/workflows/integration-test-object-suite.yaml
.github/workflows/integration-test-smoke-suite.yaml
.github/workflows/integration-test-upgrade-suite.yaml
.github/workflows/push-build.yaml

Be selective about when to offer tmate
* Unconditionally offer it when running from the rook org
* Offer it if the current repository has a `USE_TMATE` secret
* Offer it if the workflow is being re-run
w/o this change, tmate is run on all forks when builds fail.
Resolves #
**Checklist:**

ci: be selective about when to offer tmate

---

build/release/Makefile

The `mkdocs build` needs to be run in the root of the repo to work.
Resolves #
**Checklist:**

build: fix working dir for docs building

---

.github/workflows/canary-integration-test.yml
Documentation/CRDs/Cluster/ceph-cluster-crd.md
Documentation/CRDs/Cluster/external-cluster.md
deploy/examples/create-external-cluster-resources.py
deploy/examples/import-external-cluster.sh

Using subvolume group and rados namespace for external deployment
was complicated and not documented,
Automating the process for the users, so they just need to pass
the respective names by cli flag for creation
Closes: https://github.com/rook/rook/issues/10427
Resolves #
**Checklist:**

external: add support for subvolumegroup and rados namespace

---

.commitlintrc.json
PendingReleaseNotes.md
deploy/examples/toolbox.yaml

The toolbox is really only used for ceph commands. The main reason the rook image was being used in the toolbox pod was for the script that generates the ceph.conf and updates it whenever the mons are updated during mon failover.
Now the ceph image can be specified directly by moving the script inline with the container definition instead of being requiredin the image.
The rook image will still contain the script for backward compatibility and for scenarios where the rook binary may still be needed
@yuvalif Does this toolbox spec work for you with a custom ceph image?
Resolves #10513
**Checklist:**

manifest: Inline toolbox script for direct use of ceph image

---

.github/workflows/canary-test-config/action.yaml
.github/workflows/daily-nightly-jobs.yml
.github/workflows/integration-test-config/action.yaml
.github/workflows/integration-test-helm-suite.yaml
.github/workflows/integration-test-mgr-suite.yaml
.github/workflows/integration-test-multi-cluster-suite.yaml
.github/workflows/integration-test-object-suite.yaml
.github/workflows/integration-test-smoke-suite.yaml
.github/workflows/integration-test-upgrade-suite.yaml
.github/workflows/integration-tests-on-release.yaml

Since K8s 1.24.0 was released we need to run rook CI against the latest Kubernetes. At the same time, we update minikube in the CI to 1.25.2.
**Checklist:**

ci: Run tests against k8s 1.24

---

tests/integration/ceph_upgrade_test.go

The uninstall after the upgrade test was attempting to read the crds from github, instead of the local repo as expected. Now the correct manifests interface is updated during the upgrade so it will be used during the uninstall.
Resolves #10516
**Checklist:**

test: Upgrade test to use correct manifests for uninstall

---

tests/framework/utils/k8s_helper.go
tests/integration/ceph_base_file_test.go
tests/integration/ceph_smoke_test.go

Skip nfs e2e until https://github.com/rook/rook/issues/10518
is resolved to avoid flakiness.
Resolves #
**Checklist:**

ci: skip nfs e2e to avoid flaky e2e

---

deploy/charts/rook-ceph/templates/deployment.yaml
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml

Use `Recreate` strategy instead of `RollingUpdate` for
rook-ceph-operator deployement upgrade
Resolves #10237 
Testing:
- Strategy: RollingUpdate
Operator deployment replica is still 1 and new operator pod is started. 
```
oc get pods -n rook-ceph 
NAME                                                 READY   STATUS              RESTARTS      AGE
csi-cephfsplugin-provisioner-84b87c9778-49glw        6/6     Running             0             11m
csi-cephfsplugin-zjx5p                               3/3     Running             0             11m
csi-rbdplugin-provisioner-74c78559f6-szwt5           6/6     Running             2 (11m ago)   11m
csi-rbdplugin-vpq6r …
```

manifest: use `Recreate` strategy for operator upgrade

---

Documentation/CRDs/Cluster/external-cluster.md
design/README.md

Multiple links are broken in docs
Fixes: #10482
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>
**Checklist:**

docs: Correct multiple 404 page not found error

---

.github/workflows/canary-integration-test.yml
Documentation/CRDs/Cluster/external-cluster.md
deploy/examples/create-external-cluster-resources.py
deploy/examples/import-external-cluster.sh

Using subvolume group and rados namespace for external deployment
was complicated and not documented,
Automating the process for the users, so they just need to pass
the respective names by cli flag for creation
Closes: rook#10427
(cherry picked from commit c9a864ccdb683f45e231e10250e2b72eef44a654)
Resolves #
**Checklist:**

external: add support for subvolumegroup and rados namespace (backport #10459)

---

deploy/charts/library/templates/_recommended-labels.tpl

This changes the `app.kubernetes.io/managed-by` label to use the helm
`{{ .Release.Service }}` for it's value.
This is recommended by the Helm labels and annotations standard labels
doc page, see https://helm.sh/docs/chart_best_practices/labels/#standard-labels
Resolves #10473 
**Checklist:**

helm: use recommended value for helm managed-by label

---

deploy/charts/rook-ceph/templates/deployment.yaml

adding port which was missing from helm rook-ceph chart
which is used by webhook due to which it was failing with
```
failed to run operator: gave up to run the operator manager: failed to
run the controller-runtime manager: listen tcp :9443: bind: address
already in use
```
Resolves #10541 
**Checklist:**

helm: add missing port for webhook in helm

---

.github/workflows/canary-integration-test.yml
Documentation/CRDs/Cluster/ceph-cluster-crd.md
pkg/daemon/ceph/osd/daemon.go
pkg/daemon/ceph/osd/daemon_test.go
pkg/util/sys/device.go
tests/scripts/github-action-helper.sh

Rook supports raw mode OSD in host-based cluster. So we can also support OSD on logical volume in this kind of cluster.
Logical volumes aren't picked by filters (i.e. `useAllDevices: true` and `device{Path,}Filter` to avoid unwanted LV consumption on upgrade.
Resolves #2047 
**Checklist:**

osd: support OSD on logical volume in host-based cluster

---

pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml

CSI pods use leader election and they were using
default values but seems like the default values of the leader
elections are not working for some specific clusters.
Resolves #
**Checklist:**

csi: default values of leader election not enough

---

tests/scripts/github-action-helper.sh

The whereabouts manifests in the master branch have moved around, so until the new approach is investigated we pin to the latest release version v0.5.3
**Checklist:**

ci: Pin the whereabouts version to v0.5.3

---

deploy/examples/import-external-cluster.sh

The secrets in import-external-cluster.sh are being created with "rook-" prefix, but used without when creating the Storage Clasees
Resolves #
**Checklist:**

examples: fix secrets naming import-external-cluster.sh script

---

.github/workflows/auto-assign.yaml
Documentation/Contributing/development-flow.md

ci: add ci bot for auto assign issue
Now users can auto-assign issues by commenting
/assign on the issue topic
Closes: https://github.com/rook/rook/issues/10492
Resolves #
**Checklist:**

ci: add ci bot for auto assign issue

---

Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/crds.yaml
pkg/apis/ceph.rook.io/v1/object.go
pkg/apis/ceph.rook.io/v1/types.go
pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
pkg/operator/ceph/object/config.go
pkg/operator/ceph/object/spec.go
pkg/operator/ceph/object/spec_test.go

Network mode can be set separately for cephcluster and rgw
Resolves #10451 
**Checklist:**

object: network mode can be set separately for cephcluster and rgw

---

Documentation/Getting-Started/quickstart.md

To start collecting telemetry on upstream clusters, we add a new section to the quickstart guide that requests users to enable the telemetry.
**Checklist:**

docs: Add telemetry section to quickstart guide

---

pkg/daemon/ceph/osd/kms/envs_test.go
pkg/daemon/ceph/osd/kms/vault_test.go
pkg/daemon/ceph/osd/volume_test.go
pkg/daemon/util/copybins_test.go
pkg/operator/ceph/cluster/mon/health_test.go
pkg/operator/ceph/cluster/osd/integration_test.go
pkg/operator/ceph/cluster/osd/osd_test.go
pkg/operator/ceph/controller_test.go
pkg/operator/ceph/csi/controller_test.go
pkg/operator/ceph/csi/peermap/config_test.go
pkg/operator/ceph/csi/spec_test.go
pkg/operator/ceph/csi/util_test.go
pkg/operator/ceph/file/subvolumegroup/controller_test.go
pkg/operator/ceph/object/objectstore_test.go
pkg/operator/ceph/pool/controller_test.go
pkg/operator/ceph/pool/radosnamespace/controller_test.go
pkg/operator/discover/discover_test.go
pkg/operator/k8sutil/configmap_test.go
pkg/operator/k8sutil/pod_test.go

This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
This saves us at least 2 lines (error check, and unsetting the env var) on every instance.
Reference: https://pkg.go.dev/testing#T.Setenv
N/A
**Checklist:**

test: use `T.Setenv` to set env vars in tests

---

pkg/daemon/ceph/client/config_test.go
pkg/daemon/ceph/client/info.go
pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/cluster_external.go
pkg/operator/ceph/cluster/controller.go
pkg/operator/ceph/cluster/mon/health.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/cluster/mon/mon_test.go
pkg/operator/ceph/cluster/osd/status.go
pkg/operator/ceph/cluster/version.go
pkg/operator/ceph/disruption/clusterdisruption/osd.go

Some context canceled were missed and not reported correctly. We had
multiple reconcilers running in //. Since they all run in goroutine then
will continue to run until they timeout (if the timeout is available,
otherwise would run forever until the op is restarted).
Resolves #
**Checklist:**

core: fix stuck reconciler (more checkpoints for cancelled context)

---

deploy/examples/cluster-multus-test.yaml
deploy/examples/cluster-test.yaml
tests/framework/installer/ceph_installer.go

there could be something breaking with latest ceph.
So, let's stick to v17.2.1.
Resolves #
**Checklist:**

ci: use ceph v17.2.1 instead of latest v17

---

Documentation/Helm-Charts/ceph-cluster-chart.md
deploy/charts/rook-ceph-cluster/templates/prometheusrules.yaml
deploy/charts/rook-ceph-cluster/values.yaml

To install rook-ceph using ArgoCD while Prometheus is not yet installed, I need to add the [following annotation](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types): 
```yaml
metadata:
annotations:
argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
```
Resolves #
**Checklist:**

helm: add labels and annotations to PrometheusRule

---

images/image.mk

The OSBASE and OSBASEIMAGE are obsolete from an older version of rook where Ceph was not the base image. Now that Ceph provides the base image, there is no need for these vars in the makefile.
**Checklist:**

build: Remove obsolete OSBASE image var

---

Documentation/Contributing/development-flow.md

In linux environment, when go is installed using
`dnf/yum/apt` or other pacakge installer. In this case we
get error when we do `make build` because of GOPROXY.
So, we need to update the GOPROXY with `export GOPROXY=https://proxy.golang.org,direct`
in `.bashrc` file
Resolves #
**Checklist:**

docs: add section to update GOPROXY

---

pkg/operator/ceph/object/objectstore.go
pkg/operator/ceph/object/rgw.go
pkg/operator/ceph/object/user/controller.go

In object package code, external rgw server checks whether ceph cluster
is external instead of rgw. Correcting such scenarios in the code base.
Resolves #
**Checklist:**

object: add the external rgw server check properly

---

deploy/examples/cluster-multus-test.yaml
deploy/examples/cluster-test.yaml
tests/framework/installer/ceph_installer.go

This reverts commit 3279cb91870e59eccabb9b5eff903d71beb31594.
Resolves #
**Checklist:**

Revert "ci: use ceph v17.2.1 instead of latest v17"

---

tests/integration/ceph_base_file_test.go

The file deletion status has been intermittently failing for several months. Investigation shows that the timeout is just missing by a few seconds. Now we increase the timeout from 15 to 45 seconds to stabilize the test. Better to have a longer timeout than to have an intermittently failing test.
In [this test](https://github.com/rook/rook/runs/7637658897?check_suite_focus=true), the test failed after 15 seconds waiting:
```
=== RUN   TestCephSmokeSuite/TestFileStorage_SmokeTest/delete_CephFilesystem_should_be_blocked_by_csi_volumes_and_CephFilesystemSubVolumeGroup
2022-08-02 18:23:30.185996 I | integrationTest: waiting for CephFilesystem "smoke-test-fs" in namespace "smoke-ns" to have condition "DeletionIsBlocked"
2022-08-02 18:23:30.188786 I | …
```

test: Increase timeout waiting for file deletion status

---

deploy/examples/import-external-cluster.sh

Cluster_ID variable that we export from python script was different
from what we going to use in import script so changed it
Resolves #
**Checklist:**

external: fix cluster id naming in import-external-cluster script

---

pkg/apis/ceph.rook.io/v1/labels.go
pkg/operator/ceph/cluster/mon/health.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/cluster/osd/osd.go
pkg/operator/ceph/cluster/osd/update.go
pkg/operator/ceph/cluster/osd/update_test.go
pkg/operator/ceph/disruption/clusterdisruption/osd.go

During certain maintenance tasks the admin will own running operations on the ceph mons and osds, and the operator should not interfere with those operations. If the operator sees any mon in debug mode, every reconcile and mon health check will be skipped. Thus, mons will not be updated while any one of them is in maintenance. During OSD reconcile, individual OSD deployment updates will only be skipped for OSDs that are actively being debugged.
The debug mode for osd and mon deployments is signaled by creating the `ceph.rook.io/debug: "true"` label.
edit: The label is now `ceph.rook.io/do-not-reconcile: "true"`
But... Why not just scale down the operator if we expect the operator to suspect reconcile operations? This change would allow the operator to …

core: Operator to skip reconcile of mons and osds in debug mode

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md
Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
Documentation/Contributing/ci-configuration.md
Documentation/Contributing/development-flow.md
Documentation/Storage-Configuration/Advanced/ceph-configuration.md
Documentation/Storage-Configuration/Advanced/configuration.md
Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
Documentation/Troubleshooting/ceph-common-issues.md
Documentation/Upgrade/health-verification.md
Documentation/Upgrade/rook-upgrade.md
deploy/examples/import-external-cluster.sh

Rename Rook-Ceph to Rook Ceph and add some more inline code "blocks" for highlighting flags in the Ceph Cluster CRD external script docs.
**Checklist:**

docs: rename Rook-Ceph to Rook Ceph

---

pkg/operator/ceph/cluster/rbd/controller.go
pkg/operator/ceph/file/controller.go
pkg/operator/ceph/file/mirror/controller.go
pkg/operator/ceph/nfs/controller.go
pkg/operator/ceph/object/controller.go

skip ceph upgrade check in external cluster
This is the new solution for PR #10696.
Comment: https://github.com/rook/rook/pull/10696#pullrequestreview-1068407695
Resolves #10688
**Checklist:**

core: skip ceph upgrade check in external cluster

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md
Documentation/CRDs/Cluster/external-cluster.md
Documentation/CRDs/Cluster/host-cluster.md
Documentation/CRDs/Cluster/pvc-cluster.md
Documentation/CRDs/Cluster/stretch-cluster.md
Documentation/Upgrade/ceph-upgrade.md
deploy/charts/rook-ceph-cluster/values.yaml
deploy/examples/cluster-external-management.yaml
deploy/examples/cluster-on-local-pvc.yaml
deploy/examples/cluster-on-pvc.yaml
deploy/examples/cluster-stretched-aws.yaml
deploy/examples/cluster-stretched.yaml
deploy/examples/cluster.yaml
deploy/examples/images.txt
deploy/examples/toolbox.yaml
deploy/olm/assemble/metadata-common.yaml
design/ceph/ceph-cluster-cleanup.md
images/ceph/Makefile

For the Rook v1.10 release we want the latest version of Quincy to be the default deployment and the base for the operator image. Updating to v17.2.3 with the latest patch release.
**Checklist:**

manifest: Update default version of ceph to v17.2.3

---

pkg/operator/ceph/cluster/crash/reconcile.go

we are already deleting v1beta1 cronJob while creating v1 cronJob,
so no need to delete v1beta while v1 cronJob deltion.
Resolves #
**Checklist:**

core: no need to delete v1beta cronJob during v1 deletion

---

tests/framework/utils/k8s_helper.go

When a test has a slash in it's name the log collection can fail due to
the "directory" not existing, this makes sure the full path exists.
In our fork, in which we have enabled all CI workflows, when a test, e.g., CephUpgradeSuite/TestUpgradeHelm, failed the log collection wants to write the logs to a file placed _output/tests/TestCephUpgradeSuite/TestUpgradeHelm_localhost_upgrade-system_rook-ceph-operator-67c5cbc94c-drf7g_1660327489.log but only the directories up to _output/tests is created in the k8s_helper.go logic (around line 1378). I haven't checked rook's failed CI logs but this should also be an issue that can occur here.
Resolves # …

test: fix test pod log collector

---

.github/workflows/codespell.yaml
pkg/operator/ceph/object/objectstore_test.go

Codespell had its first release in a year yesterday and added some
dictionary rules that are now being flagged in our code. None of the
issues require changes to our code, so modify the codespell config to
allow the words we want to allow.
Resolves #
**Checklist:**

ci: update codespell config

---

.mergify.yml

- Configure the mergify bot to open backport PRs for the 1.10 release branch if PRs are labeled as such.
- Remove configuration for the bot to backport to release-1.6 since we haven't backported to that release for so long.
**Checklist:**

build: Update mergify for the release-1.10 branch and remove 1.6 automatic backports

---

deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/crds.yaml
pkg/apis/ceph.rook.io/v1/object.go
pkg/apis/ceph.rook.io/v1/types.go
pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
pkg/operator/ceph/object/spec_test.go

hostNetwork setting should be under spec.gateway instead of spec in the ObjectStore CRD
Resolves #10649 
**Checklist:**

object: hostNetwork setting should be under spec.gateway instead of spec in the ObjectStore CRD

---

deploy/charts/rook-ceph/values.yaml
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml
pkg/operator/ceph/csi/betav1csidriver.go

At present the CephFS CSI driver works with default mode ie,
`ReadWriteOncewithFsType`. However `File` type is more apt for
the CephFS CSI driver and this commit bring that change. The
similar change is also introduced in ceph csi driver here:
https://github.com/ceph/ceph-csi/pull/3204
considering the `File` mode has been GAd in 1.23 kubernetes version
and also we are lifting one of the problematic code path in this
area via Ceph CSI driver changes, it is good to move the
fsgrouppolicy to `File`.
Resolves #
**Checklist:**

csi: change the fsgrouppolicy for CephFS driver to "File" mode

---

deploy/examples/operator.yaml
pkg/operator/ceph/csi/version.go
pkg/operator/ceph/csi/version_test.go

Setting the min version to 3.7 will make the upgrade difficult. If someone is using a different/custom version, they won't be able to upgrade to rook v1.10 unless they also update their csi image simultaneously. If we set the min version to 3.6, it will give some time buffer to allow them to change the csi driver later.
ref: https://github.com/rook/rook/pull/10759#discussion_r953014295
Resolves #
**Checklist:**

csi: make cephcsi 3.6.0 as minimum supported version

---

pkg/operator/ceph/cluster/mon/health.go
pkg/operator/ceph/cluster/mon/health_test.go
pkg/operator/ceph/cluster/mon/mon.go

Mon failover reliability is improved in two scenarios with these changes. 
1. If the failover is aborted because of failing to start the new mon and wait for it to join quorum, the new mon will be fully removed and the failover rolled back. Previously, the operator would leave the new mon pod running even if it never joined quorum. Now the timeout for the failover is increased to wait longer for the new mon, but if it times out, there are no leftovers from the cancelled failover.
2. If the operator is failed in the middle of a failover before the old mon is removed, the operator needs to remove an extra
mon. The operator was only selecting a random mon for removal instead of honoring the stretch cluster topology or looking for mons on the same node that …

mon: Improve mon failover reliability to better handle failure and topology

---

.github/ISSUE_TEMPLATE/bug_report.md
Documentation/Troubleshooting/.pages
Documentation/Troubleshooting/ceph-toolbox.md
Documentation/Troubleshooting/krew-plugin.md

It's been a while we have the krew plugin capability for
troubleshooting that makes it easier but not added to rook
docs.
So adding it to rook docs and bug template
Closes: https://github.com/rook/rook/issues/10765
Resolves #
**Checklist:**

docs: add krew plugin to the troubleshooting docs

---

Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md

Nested list items need to be intended 3 spaces in order for markdown to
consistently handle nested lists.
Signed-off-by: Joshua Hoblitt <josh@hoblitt.com>

docs: fix html rendering of nested list items -- "because markdown"

---

tests/framework/installer/ceph_settings.go
tests/scripts/collect-logs.sh
tests/scripts/github-action-helper.sh

in case of secrets we need to get `-oyaml` instead
of `describe` since in describe it will be hidden.
Resolves #
**Checklist:**

test: update logcollector to get secrets -oyaml

---

build/rbac/gen-common.sh
deploy/examples/common.yaml

Due to an oversight, PSP resources were left in generation of
common.yaml from #10797. Resolve that by setting
pspEnable=false when generating common.yaml.
Resolves #
**Checklist:**

build: remove psp from common.yaml generation

---

.github/workflows/daily-nightly-jobs.yml
.github/workflows/integration-test-helm-suite.yaml
.github/workflows/integration-test-mgr-suite.yaml
.github/workflows/integration-test-multi-cluster-suite.yaml
.github/workflows/integration-test-object-suite.yaml
.github/workflows/integration-test-smoke-suite.yaml
.github/workflows/integration-test-upgrade-suite.yaml
.github/workflows/integration-tests-on-release.yaml
tests/framework/installer/ceph_manifests.go
tests/framework/installer/ceph_manifests_previous.go

integration test now run on the latest k8s v1.25.0.
Resolves #
**Checklist:**

ci: upgrade to latest k8s version v1.25.0 for ci test

---

Documentation/Storage-Configuration/ceph-teardown.md

otherwise it will fail with the following message:
```
The CephCluster "rook-ceph" is invalid:
* metadata.finalizers: Invalid value: "": name part must be non-empty
* metadata.finalizers: Invalid value: "": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
* metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{""}
```

docs: change [null] to []

---

Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
deploy/charts/rook-ceph/values.yaml
deploy/examples/images.txt
deploy/examples/operator-openshift.yaml
pkg/operator/ceph/csi/spec.go

at present, the csi sidecars are older versions and not in parity
with the latest ceph csi release v3.7.0. This commit update the
same to make it.
Resolves #
**Checklist:**

csi: use the latest sidecars for ceph csi driver

---

pkg/operator/ceph/object/spec.go

Signed-off-by: zhucan <zhucan.k8s@gmail.com>
If hostNetwork is enabled to cluster and disabled to store, the contianer port is 8080, and service port is 80.
Resolves #10743 
**Checklist:**

object: gateway.port partially ignored when hostNetwork disabled

---

.github/workflows/canary-integration-test.yml
.github/workflows/integration-tests-on-release.yaml

The ibm test has been failing since the move to ubuntu 20 was merged a couple days ago. Reverting back to 18 for now.
**Checklist:**

ci: Revert ibm canary test to ubuntu 18

---

Documentation/Storage-Configuration/Advanced/ceph-configuration.md
Documentation/Storage-Configuration/Advanced/configuration.md

- adds description on how to configure default pg_num and pgp_num
parameters on per pool basis while deploying rook based ceph cluster.
- advices user to declare them during initial startup.
uptil now, docs only covered cli way of configuring them.
Resolves # https://github.com/rook/rook/issues/10361
**Checklist:**

docs/storage-config: add yaml way of configuring pg_num and pgp_num

---

pkg/daemon/ceph/osd/daemon.go

OSD on logical volume is raw mode. This mode can'set metadata device. We should not mark a logical volume as available in this case.
Resolves #10747
**Checklist:**

osd: disallow to create osd on lv with metadata device

---

Documentation/CRDs/ceph-nfs-crd.md

Initial commit of NFS CRD docs missed two params, causing some users to
experience problems setting it up.
Resolves #
**Checklist:**

docs: add missed sssdConfigFile params for NFS CRD

---

pkg/operator/ceph/csi/spec.go
pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml
pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml

Currently daemonset template.metadata.name is empty, and the way we are setting it is not correct use the daemonset name as the template.metadata.name
Add missing serviceAccountName to the holder pod.
Resolves #
**Checklist:**

csi: fix holder pod creation in openshift multus cluster

---

deploy/charts/rook-ceph/values.yaml
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml
pkg/operator/ceph/csi/spec.go

This commit change the default fsgroup policy for csi driver object
to "File" type which is the better/correct setting for the CSI volumes
as it works regardless of fstype or access mode
We have been using default value which is "ReadWriteOnceWithFSType"
With this change backward compatibility should be preserved.
Resolves #
**Checklist:**

csi: change the default fsgroup policy for CSI driver object

---

.mergify.yml

The success of all the CI actions must exactly match the list for the mergify config. The config was missing a paren, so the merges were not happening automatically.
**Checklist:**

bot: Fix automerge for 1.10 backports

---

build/crds/build-crds.sh
deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/crds.yaml

Using the kpt [render-helm-chart](https://catalog.kpt.dev/render-helm-chart/v0.2/) function to generate YAML results in `failed to parse input bytes: yaml: line 583: found unexpected end of stream` when encountering `---` in the hostPath description of the `cephnfses.ceph.rook.io` CRD. :confused:
This is take two. I prematurely closed #10891 when @subhamkrai noted that the descriptions were auto-generated from content upstream, but then soon discovered that there is some agency over post-rendering via `yq` in the `build-crds.sh` script.
Resolves #
**Checklist:**

manifest: fix unexpected end of stream

---

deploy/charts/rook-ceph-cluster/templates/cephobjectstore.yaml

OBC storageclasses should have their names based on the cluster
namespace and not the operator namespace. Fix the chart to reflect this.
Resolves #10894 
**Checklist:**

helm: set OBC storageclass name to right namespace

---

tests/scripts/github-action-helper.sh

The build process sometimes fails with intermittent problems. Some of them are known problems and then we retry the build process. However, there still are unknown problems. In this case, it's hard to find the reason because the build process exits immediately.
ref.
https://github.com/rook/rook/runs/8225144002?check_suite_focus=true#step:3:926
```
+ case "$o" in
+ exit 1
Error: Process completed with exit code 1.
```
To make debugging easier, let's print the output of `make`. This log won't be too long since `make` prints most messages to stderr.
Resolves #
**Checklist:**

ci: improve the log on intermittent build failure

---

pkg/operator/ceph/controller/spec.go
pkg/operator/ceph/controller/spec_test.go

This commit implements more diagnostic error for unsccessful
Liveness- and Readiness-Probe of Pods.
Added codes are expected to catch failures of
`ceph status` and `ceph mon_status`, and report it.
Resolves #9846,  #9852
**Checklist:**

operator: improve ProbeHandler error message

---

Documentation/Upgrade/rook-upgrade.md

The helm chart is blocked from upgrading to newer versions of Rook if v1.9.10 is not installed before upgrading to K8s 1.25. The helm chart is confused by the PSPs that still exist in the installed chart and fails to upgrade to the new chart.
Related to #10826
**Checklist:**

helm: Warn to upgrade to 1.9.10 before k8s 1.25

---

Documentation/Getting-Started/Prerequisites/prerequisites.md
Documentation/Getting-Started/quickstart.md

The quickstart guide prerequisites have diverged from the storage requirements on the [prereqs doc](https://rook.io/docs/rook/latest/Getting-Started/Prerequisites/prerequisites/#ceph-prerequisites) page, now they are in sync again.
@satoru-takeuchi After this is merged, want to add another line to the storage options for LVs?
**Checklist:**

docs: Clarify storage prereqs in quickstart guide

---

deploy/examples/create-external-cluster-resources.py

The rgw ip validation feature was needing to update the rgw user cap to add info=read permission, but this permission is only backported till ceph pacific, so we added a check that only add this cap when ceph version support it,
But this cap was also adding with the other caps, so removed it from there Now it will only add this cap if ceph version support it
Resolves #
**Checklist:**

external: do not add info=read cap if ceph version doesn't support it

---

build/rbac/get-helm-rbac.sh

this is for the diagnosis of flaky github test, to know what is wrong and failing in tests like :
https://github.com/rook/rook/runs/8236140354?check_suite_focus=true
it would be helpful to have this debug option in ci setup.
Signed-off-by: Deepika Upadhyay <deepika@koor.tech>
Resolves #
**Checklist:**

ci: add debug flag to identify any failing yaml origin

---

pkg/operator/ceph/pool/controller.go

`rbd pool init` cmd initializes pool for rbd images. This commit makes modification to init only
rbd application pools, since it is not required
by other pools like ".nfs",".mgr" & "mgr_devicehealth".
refer: https://github.com/rook/rook/pull/8923#discussion_r723117689
This maybe the reason cephnfs with multus is failing too.
@parth-gr ^
@idryomov can you please take a look too.
**Checklist:**

pool: initialize only rbd application pools

---

deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml
deploy/examples/monitoring/localrules.yaml

Predict linear will continue to predict on exporter data from old pods.
We can take the max value for every hour in the 2 day window before we
linearly predict to get the most conservative estimate. This will only
affect the hour in which a new mgr pod is started.
Fixes #10691
Signed-off-by: Jamison Lofthouse <jamison.lofthouse@gmail.com>
Resolves #10691 
**Checklist:**

monitoring: fix pool growth warning grouping

---

pkg/daemon/ceph/osd/daemon.go

Disallow the creation of the following un-supported configurations.
- encrypted osd on lv
- osd on lv with metadata device
Resolves #10782
**Checklist:**

ci:  disallow to create encrypted osd on lv and osd on lv with metadata device

---

build/rbac/keep-rbac-yaml.sh

The rbac generation prints a lot of info that is not necessary unless troubleshooting the rbac build, so we can comment it out by default.
@BlaineEXE Per our discussion, ok to comment this out, right?
**Checklist:**

build: Stop printing verbose rbac generation details

---

pkg/daemon/ceph/osd/daemon.go

Rook doesn't support encrypted osd on partition. So we should skip partitions as candidates of the new encrypted osds.
Resolves #10911
**Checklist:**

osd: disallow to create encrypted osd on partition

---

.github/workflows/daily-nightly-jobs.yml

The self-hosted arm64 machine has a new label ubuntu-20.04-arm64 to avoid the conflict with other ubuntu-20.04 labels from general github actions. We only want the daily arm job to use the self-hosted runner.
@satoru-takeuchi Thanks for recognizing this issue!
Resolves #10964
**Checklist:**

ci: Update arm host to pick up correct self-hosted machine

---

CODE-OWNERS

The storage providers have long since been split to their own repo, so there is no need to define the code owners for different storage providers in this repo. The owners for cassandra and nfs are therefore removed, and the list simplified.
@jbw976 Requesting steering committee approval.
**Checklist:**

docs: Simplify code owners for ceph provider

---

Documentation/CRDs/Cluster/external-cluster.md
deploy/examples/create-external-cluster-resources.py

Currently for external clustr multitenancy is only applicable for new deployments, but adding doc change so multi-tenancy can be achieved for upgraded cluster also
Closes: https://github.com/rook/rook/issues/10678
Multi-tenancy will look like this for the upgraded cluster:
provider ceph cluster
|                            |                                |
consumer cluster1      consumer cluster 2     consumer cluster 3
If consumer cluster1 is already present.
Consumer cluster2 and cluster3 can still be added with restricted caps in the system and isolated from cluster1.
In this scenario, cluster2 and cluster3 will be having restricted caps so they can only make use of their storage pools,
But cluster1 may have …

docs: add upgrade steps for multi-tenant custer

---

Documentation/Getting-Started/Prerequisites/prerequisites.md
Documentation/Getting-Started/quickstart.md

Rook supports osd on logical volume in host-based clusters. Let's add it to the list of valid device types.
**Checklist:**

docs: add logical volume to storage options

---

pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/cluster_test.go

this commit uses the ceph feature assimilate-conf to set multiple configurations for ceph global/pods at one file
and use that in command to set the required configuration in one line command.
for example:
`ceph config assimilate-conf -i <input file> -o <output file>`
Resolves #10531 
**Checklist:**

core: use assimilate-conf command to run commands

---

deploy/examples/cluster-test.yaml

ceph cluster on ci mostly have health error
mon disk low on size,
so overriding the min aval capacity to 0 from 30% default so this error can be removed
Closes: https://github.com/rook/rook/issues/10971
Resolves #
**Checklist:**

ci: add mon_data_avail_warn to canary ci test

---

build/crds/build-crds.sh

The crds generation for the helm crds is intermittently hitting a build error due to multiple builds generating the crds at the same time. We avoid this race condition by first writing the crds to a temp file then move the file to the helm crd resources file.
@ideepika hopefully this will fix the intermittent issue we were discussing recently, I finally had some time to take a look.
Related to #10948 
**Checklist:**

build: Fix intermittent gen-rbac failure

---

Documentation/Helm-Charts/operator-chart.md
deploy/charts/rook-ceph/templates/configmap.yaml
deploy/charts/rook-ceph/values.yaml
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml
pkg/operator/ceph/csi/spec.go
pkg/operator/ceph/csi/util.go
pkg/operator/ceph/csi/util_test.go
pkg/operator/k8sutil/volume.go

This option open-up volumes and volumemounts for user customization of the rbd,cephfs,nfs plugin daemonset.
Resolves #10932
**Checklist:**

csi: customize plugin volumes and volumemounts

---

pkg/operator/ceph/cluster/predicate.go

I guesstimate that around 50% of the operator log volume when set to log level `DEBUG` are messages about cm's which aren't relevant to rook.
E.g.:
```
2022-09-16 23:03:05.430839 D | ceph-cluster-controller: hot-plug cm watcher: only reconcile on hot plug cm changes, this "ingress-controller-leader" cm is handled by another watcher
2022-09-16 23:03:05.643255 D | ceph-cluster-controller: hot-plug cm watcher: only reconcile on hot plug cm changes, this "fleet-agent-lock" cm is handled by another watcher
2022-09-16 23:03:05.799526 D | ceph-cluster-controller: hot-plug cm watcher: only reconcile on hot plug cm changes, this "cattle-controllers" cm is handled by another watcher
```
Yes, it is `DEBUG` and noise is expected. However, there is no message about checking the status of the cm's rook …

operator: silence 'cm is handled by another watcher' DEBUG messages

---

Documentation/CRDs/Cluster/pvc-cluster.md

Copy pasting current code block results in an YAML parsing error and this change fixing that error by adding a space where its needed
Resolves #
**Checklist:**

docs: fix indentation in CephCluster on PVC example yaml

---

build/release/Makefile
build/release/latest_release_branch.sh

This makes a script determine what the latest release branch is. This enables us to not need to update an additional variable during every release to make the docs point to the actual currently released release branch.
Resolves #
**Checklist:**

build: use script to reliably determine latest released release branch

---

pkg/operator/ceph/csi/csi.go

On removing or setting params to false in the operator config map, make sure to set CSIParam to their appropriate defaults, since we are not restarting the operator we cannot just assume these params/variables/flags default, everytime we need to makesure some defaults are specified.
This is what happens without these changes:
* Set CSI_ENABLE_METADATA to true, this will tune CSIParam.CSIEnableMetadata to true from false
* Create a PVC and check the metadata is added to the rbd/cephfs volumes
* Now Set CSI_ENABLE_METADATA to false, we assume CSIParam.CSIEnableMetadata will be set to false, but that is not happening because the earlier value of `CSIParam.CSIEnableMetadata = true` still persist. (we are not restarting operator to assume value of …

csi: make sure we reset CSIParam booleans to default

---

.github/workflows/canary-integration-test.yml
tests/scripts/github-action-helper.sh

github-hosted runner ubuntu-18.04 will be removed by Dec. 1st, 2022.
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
So, let's change the all runnners to ubuntu-20.04.
We need to uninstall `snapd` because `snapd` prevents kernel from unmounting `/mnt` completely.
**Checklist:**

ci: move to ubuntu 20.04 runner completely

---

pkg/clusterd/disk.go
pkg/daemon/discover/discover.go
pkg/daemon/discover/discover_test.go

Signed-off-by: dkeven <dkvvven@gmail.com>
Remove the filter in `rook-discover` that skips partitions when reporting availabel devices to the operator.
Remove the logic in `GetDeviceEmpty` which checks whether the target device has a parent.
Resolves https://github.com/rook/rook/issues/11038
**Checklist:**

osd: allow raw partitions to be picked up by discover daemon

---

deploy/examples/pool-ec.yaml
deploy/examples/pool.yaml

With Kubernetes 1.25 it seems that applying the yaml files that have a CephBlockPool with spec.annotations fail with errors like this:
CephBlockPool in version "v1" cannot be handled as a CephBlockPool:
strict decoding error: unknown field "spec.annotations"
Updates: ceph/ceph-csi#3362
**Checklist:**

examples: CephBlockPool does not have spec.annotations

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md
pkg/daemon/ceph/osd/daemon.go

LVM logical volumes are not picked by `deviceFilter`, `devicePathFilter`, and `useAllDevices`. It's to prevent old version's users from creating lv-backed osd during upgrading rook by accident.
It's better to clarify lvs are not picked by filters" in docs and suggest users to use exact device name instead.
Resolves #11032
**Checklist:**

osd: clarify lv is not picked by filters

---

pkg/daemon/ceph/osd/kms/kmip.go

This commit changes cryptographic length for keys created for kmip kms to 256 from 128, since it is more secure.
**Checklist:**

osd: use 256 as cryptographicLength for keys using kmip kms

---

pkg/operator/ceph/object/bucket/provisioner.go

OBC provisioner ignores insecure skip flag even if it is declared for TLS auth, hence bucket creation was failing
Resolves #10910 
**Checklist:**

rgw: handle insecure flag skip for obc in the tls config

---

Documentation/Getting-Started/Prerequisites/prerequisites.md

Explain the fix for https://github.com/rook/rook/issues/10932 to let NixOS users set up Rook more easily.
Resolves https://github.com/rook/rook/pull/10942#discussion_r971577389
**Checklist:**
@moduon MT-1248

docs: explain specific nixos configurations

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md
deploy/charts/rook-ceph-cluster/values.yaml

The OSD creation may need to burst during OSD provisioning depending on the size of the OSD or similar factors. If the OSD prepare job is OOM killed it will cause OSD provisioning to fail and have various side effects that are difficult to troubleshoot to get the OSD to succeed. So we increase the recommendation significantly to avoid the OOM kill.
Resolves #10219 
**Checklist:**

osd: Prepare job needs significant more memory for provisioning

---

pkg/operator/ceph/cluster/mgr/config.go
pkg/operator/ceph/cluster/mgr/dashboard.go
pkg/operator/ceph/cluster/mgr/dashboard_test.go
pkg/operator/ceph/cluster/mgr/spec.go

If the port is greater than 1024, for backward compatibility the port and targetPort should be the same value. If the port is less than 1024, the internal port must use a higher port number. In that case, the internal port will be the default port numbers and only the public port will be the desired port in the cluster CR.
Resolves #11092
**Checklist:**

mgr: Set the public dashboard port differently from the target port

---

.github/workflows/canary-integration-test.yml
pkg/daemon/ceph/client/command.go
pkg/daemon/ceph/client/command_test.go
pkg/operator/ceph/nfs/controller_test.go
pkg/operator/ceph/nfs/nfs.go
tests/scripts/github-action-helper.sh

Run the ganesha-rados-grace command in a remote pod when multus networking is enabled.
Resolves #11039
**Checklist:**

nfs: fix nfs grace period when multus is enabled

---

tests/framework/clients/nfs.go
tests/framework/installer/ceph_manifests.go
tests/framework/utils/k8s_helper.go
tests/integration/ceph_base_file_test.go
tests/integration/ceph_base_nfs_test.go
tests/integration/ceph_smoke_test.go

This commit anabled nfs csi ci and
add fixes/improvements to it like the
following:
- verify deletion of cephnfs and .nfs pool before proceeding
- verify pv deletion
- do not enable rook module
- reduce activeCount to 1 to save resources
- run cephnfs ci before cephfs ci since it cephfs
ci is more resource intensive.
Resolves #
**Checklist:**

ci: enable and fixes for nfs ci

---

deploy/examples/cluster-test.yaml

I see the mon_data_avail_warn is set to 500M
but acording to ceph doc this should be in percentage
And by default this percentage is 30%,
So re assigned to 10% for the CI
Closes: https://github.com/rook/rook/issues/11130
Resolves #
**Checklist:**

ci: update mon_data_avail_warn percentage 

---

.github/workflows/canary-integration-test.yml

As a part of the improvements the following steps have been added:
1. Create a subvolume of same name in both the primary and secondary cluster.
2. Creating multiple snapshots on the subvolume on the cluster.
3. Verifying from the count on the primary and comparing it with the count on the snapshot directory mounted for the CephFS volume mounted in the direct-mount pod.
This helps in confirming that mirroring is working properly and the snapshots have been mirrored for a desired subvolume on the secondary cluster.
Resolves #
**Checklist:**

tests: improved filesystem snapshot mirroring integration tests

---

Documentation/Storage-Configuration/Monitoring/ceph-dashboard.md

New point to explain when is available this information in the Ceph dashboard
Note: Linked with the functionality recovered in Rook orchestrator. Bug [48384](https://github.com/ceph/ceph/pull/48384)
- [ x ] Documentation has been updated, if necessary.

docs: add point about physical disks visualization in dashboard

---

pkg/operator/ceph/controller/spec.go

stability issues have been observed with 1s.
socket latency is expected whenever CPUs are
under minor pressure. Increasing value to
5s should cover most small-medium scale envs.
Resolves BZ: 2126566
Signed-off-by: Randy J. Martinez <randy@cephtips.com>
Resolves #
**Checklist:**

core: increase liveness probe timeout to 5s

---

pkg/daemon/ceph/osd/remove.go

currently, osdSafeToDestroy check is done before
marking osd out which prevents ceph from rebalancing. With these changes, we are moving check for
osdSafeToDestroy after osd is marked out.
Resolves # https://bugzilla.redhat.com/show_bug.cgi?id=2128966
**Checklist:**

osd: osdSafeToDestroy check should be after osd out

---

pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml

The omap generator sidecar is the one who sets the pvc name and clustername in the metadata if the pv is re-attached to a new pvc or if the clustername changes, for that reason we need to set these flags on the omap generator sidecar
also.
Resolves #
**Checklist:**

csi: add setmetadata and clustername flag to omap

---

deploy/examples/create-external-cluster-resources.py

the validate rgw endpoint tls cert returns the certificate instead of returning whether it exist or not,
So updatd the flow how to use it
Closes: https://github.com/rook/rook/issues/11060
Resolves #
**Checklist:**

external: fix endpoint_dial check for rgw endpoint

---

pkg/daemon/ceph/osd/remove.go

When the osd is purged, properly log the host name that is being purged and whether the host was removed from the crush map.
This should help troubleshoot the hang in the krew plugin CI defined here: https://github.com/rook/kubectl-rook-ceph/issues/59
**Checklist:**

osd: Improve logging during osd purge

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md
deploy/charts/rook-ceph-cluster/values.yaml
deploy/examples/cluster-on-pvc.yaml
deploy/examples/cluster.yaml
tests/framework/installer/ceph_manifests.go

To enable log collector by default for getting coredump for troubleshooting in case of segfaults.
Resolves #10788 #11151 
**Checklist:**

core: enabling logCollector by default for coredump collection

---

deploy/charts/rook-ceph/templates/deployment.yaml
deploy/charts/rook-ceph/values.yaml
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml

The flex driver was deprecated and fully purged long ago, and now finally we are purging the related properties from the operator deployment that are no longer applied anywhere.
**Checklist:**

operator: Remove obsolete flex driver properties

---

Documentation/Contributing/development-flow.md
INSTALL.md
design/ceph/ceph-config-updates.md
design/ceph/interacting-with-rook-resources.md

The `Note` label is updated in several places in the docs for improved rendering.
Multiple markdown files have been updated.
Closes: https://github.com/rook/rook/issues/10458
Signed-off-by: Yashasvi Chaurasia <yashasvi12977@gmail.com>

docs: updated syntax in markdown files

---

Documentation/Troubleshooting/disaster-recovery.md

**Description of your changes:** These changes make substantial improvements on the Troubleshooting -> Restoring CRDs After Deletion document. The currently published docs are incomplete. This updates them to include instructions surrounding the `ValidatingWebhookConfiguration`, and replaces interactive steps with commands. Additionally, some whitespace issues affecting the markdown parsing of the numbered lists have been fixed.
**Which issue is resolved by this Pull Request:** NA
**Checklist:**

Docs: Improve troubleshooting docs on restoring CRDs after deletion

---

pkg/operator/ceph/cluster/controller.go

Removing the finalizers from cluster resources can intermittently fail in the CI if other updates are made at similar times. Now we retry the finalizer removal to improve the reliability of the finalizer removal.
The finalizer removal error was seen in the daily CI, but then the removal never retried so the test timed out waiting.
```
2022-10-18 00:49:14.337813 E | ceph-cluster-controller: failed to reconcile CephCluster "object-ns/object-cluster". 
failed to remove finalizers: failed to remove finalizer for the secret "rook-ceph-mon": failed to remove finalizer "ceph.rook.io/disaster-protection": 
failed to remove finalizer "ceph.rook.io/disaster-protection" on "rook-ceph-mon": 
Operation cannot be fulfilled on secrets "rook-ceph-mon": the object has been …
```

core: Retry when removing finalizers from cluster resources

---

pkg/operator/ceph/cluster/osd/spec.go

The osd arguments had a few duplicate lines that could be factored out and thus simplified for code maintainability. Just a small change I stumbled on while investigating another osd issue.
**Checklist:**

osd: Reduce duplication of arguments

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md
pkg/apis/ceph.rook.io/v1/cluster.go
pkg/apis/ceph.rook.io/v1/cluster_test.go
pkg/operator/ceph/cluster/mon/health.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/cluster/mon/node_test.go
pkg/operator/ceph/cluster/mon/spec.go

If the host network setting is changed in the cluster CR, the existing mons must continue using the same network settings or else the operator would update their pod specs with the incorrect settings and cause mon quorum to go down. Now the network setting is preserved so the admin could switch between host and non-host network configuration without reinstalling.
Resolves #11121 
**Checklist:**

mon: The mon daemons maintain host network settings to allow change in config

---

images/ceph/Makefile

update "s5cmd" to "v2.0.0" as "1.4.0" was built using go v1.16 and has many vulnerabilities
Resolves #11176
**Checklist:**
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

security: update "s5cmd" to "v2.0.0"

---

pkg/operator/ceph/cluster/crash/crash.go
pkg/operator/ceph/cluster/crash/crash_test.go
pkg/operator/ceph/controller/spec.go

The crash collector does not have the command line arguments to run as ceph user id 167, so we set the security context to run as the ceph user in the main crash collector container.
**Checklist:**

security: Run the crash collector as ceph user

---

Documentation/Troubleshooting/disaster-recovery.md

Since we moved to cert-manager for the webhook a long time back, 
we just need to disable the webhook instead of backing the whole webhook. 
And, after crs are restored we need to enable the webhook and all the resources will be created by the operator.
Resolves #
**Checklist:**

docs: update disaster recovery guide for webhook

---

pkg/operator/ceph/cluster/osd/labels.go
pkg/operator/ceph/cluster/osd/osd.go

Closes:https://github.com/rook/rook/issues/11059
Resolves #
**Checklist:**

osd: add deviceType label to an OSD

---

pkg/apis/ceph.rook.io/v1/object.go

Resolves #https://github.com/rook/rook/issues/11212
**Checklist:**

core: validate crd name size from admission controller 

---

pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/config/config.go
pkg/operator/ceph/config/defaults.go
pkg/operator/ceph/config/monstore.go
pkg/operator/ceph/config/monstore_test.go
pkg/operator/ceph/config/network.go
pkg/operator/ceph/config/network_test.go

The monstore has a `SetAll()` method for applying multiple settings that was applying them individually. Now we use the assimilate config option to make this more efficient.
**Checklist:**

mon: Apply mon store settings more efficiently with the assimilate conf

---

Documentation/Getting-Started/Prerequisites/prerequisites.md
deploy/charts/rook-ceph/templates/configmap.yaml
deploy/charts/rook-ceph/values.yaml

85b079105b62752c10edaf3ccdaf637f9ca39d02 (from https://github.com/rook/rook/issues/10932) introduced some bugs that here I'm fixing.
1. Docs missing `csi.` prefix.
2. Chart was using `cis.csiRBDPluginVolumes` instead of `csi.csiCephFSPluginVolume`.
3. Values had to be a scalar value, not a raw string. Otherwise, the operator can't parse it.
4. Link to `/run/booted-system` instead of `/run/current-system`. In the former, the kernel modules will always match the current kernel; in the latter, it could happen that after a new `nixos-rebuild switch`, plugin containers can't find the kernel modules for the booted kernel version.
5. Values included in the `values.yaml` template were plural. These are not supported, they must all be singular.
About that 3rd point, this was the error being …

fix: bugs following docs for NixOS deployment

---

deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/crds.yaml
pkg/apis/ceph.rook.io/v1/types.go
tests/framework/utils/k8s_helper.go

For the upgrade case, Rook can fail to set status information on CephObjectStores after CRDs are updated but before the operator is updated. To fix this, merely allow the slices to be null in the CephObjectStore's status.endpoints.
This PR seems to be aggravating the helm filesystem upgrade test. Allow 30 more seconds for CRDs to be done before bailing. In debugging, the filesystem often needed only an extra 3 seconds to succeed.
**I will add this to backport #11279 manually once this is merged since it is needed for that PR to pass tests**
Resolves #
**Checklist:**

object: allow status endpoints to be null

---

pkg/operator/ceph/client/controller.go
pkg/operator/ceph/client/controller_test.go

Signed-off-by: Avan Thakkar <athakkar@redhat.com>
Adding two new entries(userID/userKey) in the cephClient secret, so that the csi driver can easily consume
Resolves #10810
**Checklist:**

core: include userID/userKey to secret generated from CephClient

---

pkg/daemon/ceph/client/config.go
pkg/daemon/ceph/client/info.go
pkg/operator/ceph/cluster/mon/health.go
pkg/operator/ceph/cluster/mon/health_test.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/controller/cluster_info.go

The mons that are out of quorum may cause ceph commands to timeout or fail unnecessarily trying to connect to a mon that is no longer online. Now the mon health check will update the mon endpoints configmap when a mon is detected out of quorum. This also means that if the operator is restarted during a mon failover, the failed mon will no longer remain in the ceph.conf, thus allowing the quorum to be more likely to respond to the mons that are still in quorum.
The update for mons out of quorum only applies if other mons are in quorum. If quorum is down, the configmap will not keep track of the offline mons since too many are offline.
Resolves #10650
**Checklist:**

mon: Remove out of quorum mons from ceph.conf

---

Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md
Documentation/CRDs/Block-Storage/ceph-block-pool-rados-namespace-crd.md
Documentation/CRDs/Block-Storage/ceph-rbd-mirror-crd.md
Documentation/CRDs/Cluster/ceph-cluster-crd.md
Documentation/CRDs/Object-Storage/.pages
Documentation/CRDs/Object-Storage/ceph-object-realm-crd.md
Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
Documentation/CRDs/Object-Storage/ceph-object-store-user-crd.md
Documentation/CRDs/Object-Storage/ceph-object-zone-crd.md
Documentation/CRDs/Object-Storage/ceph-object-zonegroup-crd.md
Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md
Documentation/CRDs/Shared-Filesystem/ceph-fs-mirror-crd.md
Documentation/CRDs/Shared-Filesystem/ceph-fs-subvolumegroup-crd.md
Documentation/CRDs/ceph-client-crd.md
Documentation/CRDs/ceph-nfs-crd.md
Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md

The name of the CRD is more clear for finding the CRD specs instead of a modified form of the name that was intended to be more human readable. When someone is looking for the CRD settings, they more naturally expect the CRD name in the title.
@galexrt How do we increase the width of the TOC on the left column of the docs? With this change, the last three letters of `CephBlockPoolRadosNamespace` is cut off in that pane.
**Checklist:**

docs: Set CRD page titles to the CRD name

---

Documentation/CRDs/Cluster/external-cluster.md
Documentation/Getting-Started/Prerequisites/prerequisites.md
Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
deploy/charts/rook-ceph-cluster/values.yaml
deploy/examples/csi/rbd/storageclass-ec.yaml
deploy/examples/csi/rbd/storageclass.yaml
deploy/examples/import-external-cluster.sh
design/ceph/ceph-config-updates.md

Various files are outdated in that they limit RBD features to only `layering`.  `fast-diff` and `object-map` are beneficial on the Ceph back end for accelerating commands including `rbd du`.  Also add `exclusive-lock` and `deep-flatten` to fill out the conventional set of features.  Added note about this set being equivalent to the OR'd bitfield value 63, and that KRBD in the Linux kernel supports these additional features as of 5.4.
Signed-off-by: Anthony D'Atri <anthonyeleven@users.noreply.github.com>
Resolves #
**Checklist:**

docs: add additional RBD image features to docs and YAML files

---

deploy/charts/rook-ceph/templates/deployment.yaml

While #4211 added support for the udev blacklist and also added it to the values file, it omitted actually passing the value as environment variable.
Does this minor fix need a release notes entry?
Resolves #
**Checklist:**

helm: set DISCOVER_DAEMON_UDEV_BLACKLIST

---

Documentation/Troubleshooting/ceph-csi-common-issues.md

The already exists error message is perhaps the most common issue with the csi driver. The csi troubleshooting guide is now clarified to make that error message easier to find.
**Checklist:**

docs: Clarify csi already exists error in docs

---

pkg/operator/ceph/csi/peermap/config.go
pkg/operator/ceph/csi/peermap/config_test.go

When mirror logs are enabled, `ceph osd pool get <poolname> all` command returns peer pool info along with the debug logs. This causes error while parsing the logs for json data. Using --out-file flag saves the json data in the file which can be parsed easily while logging will still be written to stdout/stderr.
Resolves #
**Checklist:**

core: parse peer pool output with --out-file flag

---

pkg/daemon/ceph/osd/daemon.go

We can use LVM logical volumes and loop devices as OSD iff we specify them in the `devices` field. If we use filters like `deviceFilter`, these devices are not picked with a log message which let users specify the exact device name. It's better to mention which field users should use in this case.
Resolves #11353
**Checklist:**

osd: improve log on specifying lv and loop device as osd

---

pkg/daemon/ceph/osd/encryption.go
pkg/daemon/ceph/osd/volume.go
pkg/operator/ceph/cluster/osd/config.go
pkg/operator/ceph/cluster/osd/config_test.go
pkg/operator/ceph/cluster/osd/spec.go
pkg/util/exec/exec.go
pkg/util/exec/exec_test.go
pkg/util/exec/test/mockexec.go
pkg/util/exec/translate_exec.go

This commit implements this corner case during osd-prepare job.
```
The encrypted block is not opened, this is an extreme corner case
The OSD deployment has been removed manually AND the node rebooted
So we need to re-open the block to re-hydrate the OSDInfo.
Handling this case would mean, writing the encryption key on a
temporary file, then call luksOpen to open the encrypted block and
then call ceph-volume to list against the opened encrypted block.
We don't implement this, yet and return an error.
```
When underlying PVC for osd are CSI provisioned, the encrypted device is closed when PVC is unmounted due to osd pod being deleted. Therefore, this is no longer a corner case and needs to be handled. This commit implements the fix for the same. …

osd: re-open encrypted disk during osd-prepare-job if closed

---

pkg/operator/ceph/test/containers.go
pkg/operator/k8sutil/pod.go

Ceph will use a random nonce for the msgr daemons as long as they are running as PID 1 or have the environment variable CEPH_USE_RANDOM_NONCE set to indicate running in a containerized environment. While the Ceph daemons in Rook are expected to run in PID 1, there are some environments where the container runtime may choose to run something else such as /usr/bin/pod as PID 1. The side effect then is that ceph uses the pid as the nonce and causes problems when the daemons restart with the same PID.
The environment observed with the ceph daemons running not as pid 1 is in Openshift 4.10, although it's not clear if it's the Openshift version or something else in the downstream environment. Running in minikube I do see them running as pid 1.
Related to …

core: Set env var for ceph msgr to always use random nonce

---

design/ceph/ceph-exporter.md

Add a design doc for introducing ceph-exporter daemon in Rook.
Signed-off-by: Avan Thakkar <athakkar@redhat.com>
Resolves #
**Checklist:**

docs: add ceph-exporter design doc

---

cmd/rook/ceph/osd.go
pkg/operator/ceph/cluster/mgr/spec.go
pkg/operator/ceph/cluster/mon/env.go
pkg/operator/ceph/cluster/osd/envs.go
pkg/operator/ceph/cluster/osd/provision_spec.go
pkg/operator/ceph/cluster/osd/spec.go

The fsid, username, and user secrets were from legacy and no longer needed on the osd daemon or mon pods. This removes the unnecessary/legacy env vars from the pod specs.
**Checklist:**

core: Remove unnecessary env vars from pod specs

---

pkg/daemon/ceph/osd/encryption.go
pkg/daemon/ceph/osd/volume.go

During osd-prepare-job,
The encrypted device is found to be closed in some cases when the OSD deployment has been removed manually accompanied by any of following cases:
- node reboot
- csi managed PVC being unmounted etc
while re-opening the block to re-hydrate the OSDInfo,
the dm device `<pvc-name>-block-dmcrypt` clashes with
the one used by OSD pod which is stale by now.
This commit adds cmd to remove this stale dm device.
Error with output "No such device" is ignored.
---
refer: #11338
The error is 
```
2022-12-06 07:34:16.804076 D | exec: Running command: cryptsetup luksOpen --verbose --allow-discards /mnt/ocs-deviceset-gp3-csi-0-data-0qsvjg ocs-deviceset-gp3-csi-0-data-0qsvjg-block-dmcrypt
2022-12-06 …
```

osd: remove stale dm device during osd-prepare-job 

---

pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/cluster_external.go
pkg/operator/ceph/cluster/nodedaemon/add.go
pkg/operator/ceph/cluster/nodedaemon/add_test.go
pkg/operator/ceph/cluster/nodedaemon/crash.go
pkg/operator/ceph/cluster/nodedaemon/crash_test.go
pkg/operator/ceph/cluster/nodedaemon/keyring.go
pkg/operator/ceph/cluster/nodedaemon/keyring_test.go
pkg/operator/ceph/cluster/nodedaemon/pruner.go
pkg/operator/ceph/cluster/nodedaemon/pruner_test.go
pkg/operator/ceph/cluster/nodedaemon/reconcile.go
pkg/operator/ceph/controller/predicate.go
pkg/operator/ceph/cr_manager.go
tests/framework/utils/k8s_helper.go

The crash collector controller is designed for watching nodes where ceph daemons are running, and ensuring a special daemon is running on that node to provide additional support for ceph on that node. The crash collector is the first example of a daemon that should be running on all the ceph daemon nodes. The next example of such a node daemon will be the ceph exporter that will listen for the ceph metrics as described in the design doc and in #10687.
https://github.com/rook/rook/blob/master/design/ceph/ceph-exporter.md
Now the crash collector controller is renamed to the node daemon controller so the ceph exporter daemon can also be managed by the same controller. This PR really just moved around the code and made it simpler to add the ceph exporter to …

core: Refactor crash collector for more node daemons

---

pkg/daemon/ceph/client/config.go
pkg/daemon/ceph/osd/remove.go

The ceph.conf was being written with 0x444 permissions, which means the file could not be updated if it already exists. Specifically, when an osd is purged, if the operation is retried multiple times, only the first operation was succeeding. The subsequent requests to purge an osd were failing due to the config already existing. If we make the config writeable with 0x644 then the operator can always write the file.
A small typo is also fixed in the osd purge message.
**Checklist:**

core: Allow ceph.conf to be updated if already exists

---

pkg/operator/ceph/cluster/osd/deviceSet.go
pkg/operator/ceph/cluster/osd/deviceset_test.go

The volume names of a pod must follow a schema that does not allow periods in the name. Since the device set name is used as the pvc name and then the volume name to attach to the osd prepare job, we must sanitize the device set name for the invalid character and replace it.
edit: Here is the error found in the volume of the osd prepare job when attempting to create the volume with the dot. When the storageClassDeviceName is set to `name.with.dots`, we see this error:
```
2022-12-12 15:08:01.120368 E | op-osd: failed to run osd provisioning job for PVC "name.with.dots-data-02rnf7": 
Job.batch "rook-ceph-osd-prepare-name.with.dots-data-02rnf7" is invalid: [spec.template.spec.volumes[7].name: Invalid value: "name.with.dots-data-02rnf7": 
a lowercase RFC 1123 …
```

osd: Replace dot with dash in storageClassDeviceSet names since used as volume names

---

.github/workflows/canary-integration-test.yml
.github/workflows/canary-test-config/action.yaml
.github/workflows/integration-test-config-latest-k8s/action.yaml

upgrading minikube action to latest version which has the fix of crictl, currently CI is failing due to this.
Resolves #
**Checklist:**

ci: upgrade minikube action to latest version

---

Documentation/CRDs/Cluster/external-cluster.md

If there is a external k8s cluster which need to use rook-ceph as a storageclass backend then user can do the following steps to import it to the running rook-ceph cluster
Closes:https://github.com/rook/rook/issues/11404
Resolves #
**Checklist:**

docs: import external K8s cluster on existing cluster

---

tests/framework/installer/ceph_installer.go
tests/framework/utils/k8s_helper.go

will check if the podrestartcount is greater than 1,
If it is we will alert it and fail the CI
It is important to understand intermittent failures
to avoid too many false positives
Resolves #https://github.com/rook/rook/issues/11380
**Checklist:**

ci: watch for pods that restart unexpectedly

---

deploy/examples/operator-openshift.yaml
pkg/operator/ceph/controller.go
pkg/operator/ceph/webhook-config.go
pkg/operator/ceph/webhook.go

disable webhook in the downstream cluster.
Resolves #
**Checklist:**

operator: disable webhook by default

---

pkg/daemon/ceph/osd/volume.go
pkg/daemon/ceph/osd/volume_test.go

The kubernetes job `rook-ceph-osd-prepare-<server-name>` is not able to complete correctly when trying to create a OSD whose device is created by a LVM and has an alias starting by `/dev/mapper`. The job fails trying to create a `ceph-volume`
Resolves #11297
**Checklist:**

OSD prepare job cannot create vols with /dev/mapper alias on PVCs

---

cmd/rook/ceph/ceph.go
cmd/rook/ceph/mgr.go
cmd/rook/ceph/osd.go
cmd/rook/ceph/osd_test.go
deploy/charts/rook-ceph-cluster/templates/deployment.yaml
deploy/examples/direct-mount.yaml
deploy/examples/osd-purge.yaml
deploy/examples/toolbox-job.yaml
deploy/examples/toolbox.yaml
images/ceph/toolbox.sh
pkg/operator/ceph/cluster/mgr/spec.go
pkg/operator/ceph/cluster/mon/config.go
pkg/operator/ceph/cluster/mon/env.go
pkg/operator/ceph/cluster/osd/envs.go
pkg/operator/ceph/cluster/osd/provision_spec.go

Environment variables are not recommended for secrets in pods since they can be easily leaked if the environemnt variables are logged. By mounting the mon secret as a file, the mgr and osd prepare pods can read the mon secret from a file for better security.
This in addition to #11331 should mean rook is compliant with not using the secrets.
The one exception to this is that the CSI driver and many of the Ceph pods mount the `rook-ceph-config` secret, but it does not contain confidential information. The secret only contains the mon endpoints, which is necessary to save as a secret for the csi driver.
```
$ kubectl -n rook-ceph get secret rook-ceph-config -o yaml
apiVersion: v1
data:
mon_host: W3YyOjEwLjEwNi4zMC4yMTQ6MzMwMCx2MToxMC4xMDYuMzAuMjE0OjY3ODld …
```

core: Read mon secret from file instead of env var

---

pkg/operator/ceph/webhook-config.go

operator: adding logs for debugging

---

.github/workflows/canary-integration-test.yml
.github/workflows/canary-test-config/action.yaml
.github/workflows/crds-gen.yml
.github/workflows/daily-nightly-jobs.yml
.github/workflows/docs-check.yml
.github/workflows/integration-test-config-latest-k8s/action.yaml
.github/workflows/mod-check.yml
.github/workflows/push-build.yaml
.github/workflows/rbac-gen.yaml
.github/workflows/unit-test.yml

Go 1.18.5 and other Go 1.18 version patches provided many vulnerability fixes
but as go.mod doesn't support minor version i.e why moving to next go release
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
Resolves #11176 
**Checklist:**

build: move to Go 1.19 as default version for building services

---

Documentation/Storage-Configuration/Block-Storage-RBD/rbd-mirroring.md

A note in the rbd mirroring topic was missing a link to the failover and failback doc.
Resolves #10741 
**Checklist:**

docs: Add link to failover and failback topic

---

Documentation/Helm-Charts/ceph-cluster-chart.gotmpl.md
Documentation/Helm-Charts/ceph-cluster-chart.md
deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml
deploy/charts/rook-ceph-cluster/values.yaml

- allow to specify **allowedTopologies** for **storageClass** defined in here https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies
**Checklist:**

helm: allow to specify allowed topologies for storage class

---

.github/workflows/canary-integration-test.yml

Waiting for pools to be configured in the multi cluster test is taking too long and timing out. Increase the timeout of the wait so the pool creation can succeed.
**Checklist:**

ci: Multi cluster test failing consistently in master

---

build/crds/build-crds.sh
deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/crds.yaml

Using the kpt [render-helm-chart](https://catalog.kpt.dev/render-helm-chart/v0.2/) function to generate YAML results in `failed to parse input bytes: yaml: line 549: found unexpected end of stream` when encountering `---` in the hostPath description of the `cephnfses.ceph.rook.io` CRD.
This was addressed previously in #10899, but this time the fix applies recursively to any matching paths, which presently includes two instances under the `kerberos` object (introduced in #10950) and a second instance under the `sssd` object (introduced in #11042).
Resolves #
**Checklist:**

manifest: revert fix unexpected end of stream

---

pkg/operator/ceph/cluster/osd/spec.go
pkg/operator/ceph/cluster/osd/spec_test.go

OSD is not resized in host-based clusters even though expanding
the backing block device. It's due to the lack of bluefs-bdev-expand
init container.
Resolves #10930
**Checklist:**

osd: add expand-bluefs init container for host-based cluster

---

Documentation/Helm-Charts/ceph-cluster-chart.md
deploy/charts/rook-ceph-cluster/templates/deployment.yaml
deploy/charts/rook-ceph-cluster/values.yaml
tests/framework/installer/ceph_helm_installer.go

This integrates the [toolbox spec from the examples](https://github.com/rook/rook/blob/master/deploy/examples/toolbox.yaml) into the chart `rook-ceph-cluster`, in order to simplify the setup of the toolbox: just flip `toolbox.enabled` to `true`.
Resolves #11126 
**Checklist:**

helm: fix toolbox command, default to cluster image

---

Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md

Fixes the Grafana dashboard links dur to changes on the Grafana website.
Signed-off-by: Tim Jones <timniverse@gmail.com>
Resolves #
**Checklist:**

docs: fix grafana dashboard links

---

deploy/charts/rook-ceph-cluster/values.yaml

Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>
Expand a comment that recommends no `limit` for the `prepareosd` pod to note a conflict with an external `limitRange`.  Also wrap lines to a traditional length.
Resolves #11511
**Checklist:**

docs: add limitRange comment to deploy/charts/rook-ceph-cluster/values.yaml

---

Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-notifications.md
PendingReleaseNotes.md

Bucket notifications and topics have been implemented since v1.8 and have been stable. Therefore, with v1.11 we move the feature to stable.
Related to #11484
**Checklist:**

object: Move bucket notifications to stable

---

pkg/operator/ceph/cluster/cluster.go
tests/framework/installer/ceph_manifests.go

Set rbd_default_map_options to secure when encryption is enabled.
Resolves #11522 
**Checklist:**

ceph: set rbd_default_map_options for encryption

---

Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md
Documentation/CRDs/Cluster/ceph-cluster-crd.md
Documentation/CRDs/Object-Storage/ceph-object-realm-crd.md
Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
Documentation/CRDs/Object-Storage/ceph-object-store-user-crd.md
Documentation/CRDs/Object-Storage/ceph-object-zone-crd.md
Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md
Documentation/CRDs/Shared-Filesystem/ceph-fs-mirror-crd.md
Documentation/CRDs/Shared-Filesystem/ceph-fs-subvolumegroup-crd.md
Documentation/CRDs/ceph-client-crd.md
Documentation/CRDs/ceph-nfs-crd.md

Seems that the CRD pages lists got broken some time ago because of the markdown list indentations.
Now:
Fixed:
I'm still looking through the other CRD pages locally to fix these issues for the other CRD pages.
**Checklist:**

docs: fix ceph cluster crd list indentation issue

---

deploy/examples/object-external.yaml

The health checker options are no longer applicable to external rgw servers, so remove those info.
Resolves #
**Checklist:**

docs: remove health checker related option in object-external.yaml

---

pkg/operator/ceph/object/spec_test.go

The test is getting time out while checking backend version for kv engines in RGW KMS unit tests.
Resolves #11210
**Checklist:**

test: update kv version for rgw-kms tests

---

pkg/operator/ceph/csi/spec.go

we need to set the variable in the template instead of the global variable for the template rendering.
Resolves #11555 
**Checklist:**

csi: fix custom ceph.conf for csi pods

---

pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/cluster_test.go

Unset encryption configuration and default rbd map option when the encryption is not enabled or it is disabled after some time.
Unset the compression option also when the compression is disabled.
Resolves #11541 
**Checklist:**

core: unset messenger2 configuration

---

deploy/charts/library/templates/_cluster-role.tpl
deploy/examples/common.yaml

ceph orch command uses patch method to update cephcluster. Adding patch to verbs list of rook-ceph-mgr(Role) to make it work. It was allright with deploy/charts/rook-ceph-cluster/charts/library/templates/_cluster-role.tpl to justify the changes quite a bit.
Signed-off-by: Ben Gao <bengao168@msn.com>
Resolves #11537 
**Checklist:**

mgr: role rook-ceph-mgr is lack of patch verb to compete ceph request(fix 11537)

---

Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
pkg/operator/ceph/csi/csi.go
pkg/operator/ceph/csi/util.go
pkg/operator/ceph/csi/util_test.go

Rook will now append internal default versions to custom csi image variables passed down if version is missing in them.
This will enable users using their private registries to just pass different image names while rook takes care of adding default versions to them.
Resolves: #10529
**Checklist:**

csi: add default version to images if it is missing

---

pkg/operator/ceph/file/controller.go
pkg/operator/ceph/file/status.go

CephFS object fails to do a initial status update.
Operator shows the following error message in logs,
'Error while updation: Operation cannot be fulfilled on
cephfilesystems.ceph.rook.io "myfs": the object has been
modified; please apply your changes to the latest version
and try again'
Function 'updateStatus' now returns the new/updated
CephFilesystem object if successfully updated or nil.
Resolves issue https://github.com/rook/rook/issues/10767
**Checklist:**

Fix CephFS Status updates

---

design/ceph/multi-cluster-service.md

Design doc on adding Submariner-globalnet support to enable mirroring across multiple clusters having overlapping CIDRs
Resolves #
**Checklist:**

docs: design document for multi-cluster service support

---

Documentation/Storage-Configuration/NFS/nfs-csi-driver.md

Add an example of getting the export path for an NFS PVC to the NFS CSI docs.
Resolves #
**Checklist:**

docs: add export path example for NFS CSI

---

.docs/macros/includes/main.py

The latest python black stable release started flagging a newline between a function `def` and the function body. Remove said newline.
Resolves #
**Checklist:**

docs: fix lint error in doc generating python code

---

Documentation/Helm-Charts/ceph-cluster-chart.gotmpl.md
Documentation/Helm-Charts/ceph-cluster-chart.md
deploy/charts/rook-ceph-cluster/values.yaml

currently helm has only the config of cephclusterSpec
for a converged cluster, document installing pvc based,
strech based , external based cluster
Closes: https://github.com/rook/rook/issues/11480
Resolves #
**Checklist:**

helm: document installing different types of CephClusters

---

Documentation/Storage-Configuration/Monitoring/ceph-dashboard.md

Fix some formatting issues and the kubectl apply command `-f` flag missing.
**Checklist:**

docs: fix formatting issues

---

Documentation/Contributing/development-flow.md

Adding instructions to fetch the tags as they are used during the build process. The current instructions only require the user to clone the project which results in build errors later on.
Closes: https://github.com/rook/rook/issues/11619
Signed-off-by: Redouane Kachach <rkachach@redhat.com>
Resolves #
**Checklist:**

docs: fixing build instructions

---

tests/framework/installer/ceph_manifests.go
tests/framework/installer/ceph_manifests_previous.go
tests/integration/ceph_upgrade_test.go

With the v1.11 release approaching, the upgrade tests in master are not updated to upgrade starting from v1.10 instead of from v1.9.
**Checklist:**

test: Upgrade tests to update from v1.10

---

pkg/operator/ceph/file/mds/spec.go

to support mds with multus, we don't need
to add `--public-adr`, if multus is selected as
the network in cephCluster CR.
Resolves #
**Checklist:**

mds: support mds with multus

---

tests/manifests/test-cluster-on-pvc-encrypted.yaml

This is to fix the following CI failure.
ci: Canary tests on PVCs are failing when creating OSDs #11600
We set the version of Ceph used for OSD on PVC to v16. It's the moving target and was recently changed the target version. The new version has a regression which fails `ceph-volume raw prepare`. Although this will be fixed in Ceph by the following PR, it's not been backported to Quincy yet.
ceph-volume: fix a bug in lsblk_all()
https://github.com/ceph/ceph/pull/49171
Let's change the version to v17.2.3, the latest version without the above-mentioned regression of Ceph.
**Checklist:**

test: change ceph version of osd on pvc canary test to avoid failures

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md
Documentation/Helm-Charts/operator-chart.md
deploy/charts/rook-ceph/templates/configmap.yaml
deploy/charts/rook-ceph/values.yaml
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml
pkg/operator/ceph/csi/csi.go
pkg/operator/ceph/csi/spec.go
pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml

Exposing CSI configuration for the user to set the cephfs kernel mount options.
Resolves #11624
**Checklist:**

csi: provide way to set cephfs kernel mount options

---

pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/cluster_external.go
pkg/operator/ceph/cluster/utils.go
pkg/operator/ceph/cluster/utils_test.go

The default configmap does not have any labels or annotations applied. If the helm chart is later updated to configure the ceph config overrides, the configmap will fail to be created by the chart since it doesn't have the needed label and helm annotations so helm will know it can take over the resource management.
@holmesb This should cover the issue.
Resolves #11302 
**Checklist:**

helm: Add labels and annotations to config overrides configmap

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md
PendingReleaseNotes.md
deploy/charts/rook-ceph-cluster/values.yaml
deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/cluster.yaml
deploy/examples/crds.yaml
pkg/apis/ceph.rook.io/v1/cluster.go
pkg/apis/ceph.rook.io/v1/types.go
pkg/daemon/ceph/client/config.go
pkg/daemon/ceph/client/info.go
pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/cluster/mon/service.go
pkg/operator/ceph/cluster/mon/spec.go
pkg/operator/ceph/config/store_test.go
tests/framework/installer/ceph_manifests.go
tests/framework/installer/ceph_settings.go
tests/integration/ceph_multi_cluster_test.go

Enabling msgr v2 and disabling msgr v1 currently requires enabling either encryption on the wire or compression on the wire. As more clients are running on the latest kernel, allow the clients to run on v2 even when encryption and compression are not enabled. Clusters that are fully running on v2 will more easily be able to change configuration between enabling or disabling msgr v2 features.
**Checklist:**

core: Option to require msgrv2 even without encryption

---

pkg/operator/ceph/controller/spec.go
pkg/operator/ceph/controller/spec_test.go

increasing the rotation from default 7 to 28 as
in case of rbdmirror logs seems not enough in some cases
with maxLogSize 500 so it's better to increase the rotation
for rbdmirror specific.
Resolves #
**Checklist:**

rbdmirror: set log rotation from 7 to 4x i.e 28

---

tests/framework/installer/ceph_manifests_previous.go

The requireMsgr2 setting is not available in 1.10, therefore the setting must be removed from the cephcluster CR when the 1.10 cluster is created before the upgrade.
Resolves #11672 
**Checklist:**

test: Fix upgrade test for msgr2 setting

---

.github/workflows/canary-test-config/action.yaml
.github/workflows/integration-test-config-latest-k8s/action.yaml
.github/workflows/integration-test-helm-suite.yaml
.github/workflows/integration-test-mgr-suite.yaml
.github/workflows/integration-test-multi-cluster-suite.yaml
.github/workflows/integration-test-object-suite.yaml
.github/workflows/integration-test-smoke-suite.yaml
.github/workflows/integration-test-upgrade-suite.yaml
.github/workflows/integration-tests-on-release.yaml
Documentation/Getting-Started/Prerequisites/prerequisites.md
Documentation/Getting-Started/quickstart.md
tests/scripts/github-action-helper.sh

this commit bump minmum k8s version to 1.21.14 and max k8s version to latest 1.26.0. Keeping support for most recent 6 versions.
Resolves #
**Checklist:**

ci: Update min K8s support to 1.21 and add 1.26 support

---

pkg/operator/ceph/cluster/mgr/spec.go
pkg/operator/ceph/controller/spec.go
pkg/operator/ceph/controller/spec_test.go

The idea behind this change is to use the readiness probe to implement the mgr HA mechanism. In the current ceph mgr implementation only the active instance offers the command 'mgr_status' through the admin socket. We use this command combined with a Readiness Exec Probe to detect which manager is active. Kubernetes will automatically mark it as ready and redirect any service traffic to the active instance.
Closes: https://github.com/rook/rook/issues/11640
Closes: https://github.com/rook/rook/issues/11638
Signed-off-by: Redouane Kachach <rkachach@redhat.com>
Resolves #11640
Resolves https://github.com/rook/rook/issues/11638
============== Manual Testing ===========
Starting from a clean environment, pull …

mgr: use k8s readiness probe to implement mgr HA

---

pkg/operator/ceph/object/objectstore.go
pkg/operator/ceph/object/objectstore_test.go

The removal of the rgw_rados_pool_pg_num_min property was completed in v16.2.11 for Pacific. The previous fix in #11024 only assumed the fix was in Quincy v17.2.2 or newer. Now we account for v16.2.11 as well.
Resolves #11671 
**Checklist:**

object: RGW metadata pg count reduction on 16.2.11

---

pkg/operator/ceph/cluster/osd/osd_test.go
pkg/operator/ceph/cluster/osd/spec.go
pkg/operator/k8sutil/k8sutil.go

The rook-version tag must not be set on the pod spec labels since it will result in the ceph daemons being restarted every time there is a rook version update, even if the ceph version or pod spec was not otherwise updated.
The rook-version tag was being added to the OSD pod spec due to a shared pointer to the labels. The code intended to only add the version label to the deployment labels, but since the pod labels shared the map variable, the pod unintentionally also had the version label added.
Now the OSD pod will only be updated and restart if there is a ceph version change, or some other pod spec change on the OSD. 
Surprisingly, this does not appear to be a regression, at least not any time recently.  …

osd: Ensure rook version label is not set on pod

---

Documentation/Helm-Charts/operator-chart.md
Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
PendingReleaseNotes.md
deploy/charts/rook-ceph/templates/configmap.yaml
deploy/charts/rook-ceph/values.yaml
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml
pkg/operator/ceph/cluster/osd/osd.go
pkg/operator/ceph/cluster/osd/topology/topology.go
pkg/operator/ceph/cluster/osd/topology/topology_test.go
pkg/operator/ceph/csi/csi.go
pkg/operator/ceph/csi/spec.go
pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
pkg/operator/ceph/disruption/clusterdisruption/pools.go

- csi: add option to enable read affinity for rbd volumes
This commit adds code to supply variables required
to enable read affinity for rbd volumes.
It leverages `read_from_replica=localize,crush_locations=key:value`
krbd map option from ceph to serve reads from the most local OSD.
refer:
https://docs.ceph.com/en/latest/man/8/rbd/#kernel-rbd-krbd-options
- docs: add documentation about rbd read affinity
This commit documents steps to enable read affinity
for rbd volumes.
- helm: add option for rbd read affinity
This commit documents and adds helm options
to enable read affinity for rbd volumes.
refer: https://github.com/ceph/ceph-csi/pull/3639
Resolves #8935
PTAL …

csi: add support for enabling read affinity for rbd volumes.

---

pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/cluster/mgr/mgr_test.go
pkg/operator/ceph/controller/spec.go
pkg/operator/k8sutil/deployment.go

This fixes the the MultiClusterDeploySuite CI failure. The operator is timing out waiting for the mgr deployments to be ready, according to the WaitForDeploymentToStart() method. After the reconcile times out after about five minutes, the next reconcile succeeds since the wait is only done for new mgr deployments.
Closes: https://github.com/rook/rook/issues/11685
Resolves #
**Checklist:**

ci: fix MultiClusterDeploySuite CI

---

.github/workflows/build.yml
Makefile
build/csv/csv-gen.sh
deploy/charts/rook-ceph/templates/clusterrolebinding.yaml
deploy/examples/common.yaml
deploy/olm/assemble/metadata-common.yaml
images/ceph/Makefile

removing unnecessary rbac and also updating
csv-gen script.
ci: install kubectl binary in mac for csv gen
installing kubectl in mac build for csv generation
as without that it is failing with
```
./../build/csv/csv-gen.sh: line 26: kubectl: command not found
```
Closes: https://github.com/rook/rook/issues/10141
Resolves #
**Checklist:**

build: clean rbac which are not required

---

deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml
deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
deploy/charts/rook-ceph-cluster/templates/cephobjectstore.yaml
deploy/charts/rook-ceph-cluster/values.yaml

Added the ability to configure the `volumeBindingMode` for the block, file, and object StoageClass resources in the rook-ceph-cluster helm chart.
Resolves #11011
**Checklist:**

helm: support setting storageclass volumeBindingMode in rook-ceph-cluster helm chart

---

pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/cluster/mgr/mgr_test.go
pkg/operator/k8sutil/deployment.go
pkg/operator/k8sutil/pod.go

After an update, the mgr pod will be restarted. Since the readiness probe will indicate the standby mgr pod is never ready, we need to check simply for the running mgr pod and not whether or not it is ready.
Resolves #11702
**Checklist:**

mgr: Wait for the mgr pod to be running after an update

---

Makefile

we need to export variable in different lines
to work in Makefile, exporting in single doesn't
work.
Resolves #
**Checklist:**

build: fix csv generation during make build

---

Documentation/Helm-Charts/operator-chart.md
Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
Documentation/Storage-Configuration/NFS/nfs-csi-driver.md
Documentation/Upgrade/rook-upgrade.md
deploy/charts/rook-ceph/values.yaml
deploy/examples/images.txt
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml
pkg/operator/ceph/csi/spec.go
pkg/operator/ceph/csi/util_test.go
pkg/operator/ceph/csi/version.go
pkg/operator/ceph/csi/version_test.go

Update the cephcsi image to the v3.8.0 release and remove support for 3.6.0, as it's deprecated and not supported anymore.
More details at
https://github.com/ceph/ceph-csi/releases/tag/v3.8.0 and https://github.com/ceph/ceph-csi/tree/release-v3.8#ceph-csi-container-images-and-release-compatibility
Resolves #11688
**Checklist:**

csi: update cephcsi to v3.8.0

---

.github/workflows/canary-integration-test.yml
.mergify.yml
tests/scripts/collect-logs.sh
tests/scripts/validate_cluster.sh

The test scripts were only waiting for a timeout of three seconds for ceph commands, which was causing intermittent failures in the CI. Now the timeout is increased to ten seconds.
Resolves #11741
**Checklist:**

test: Increase timeout waiting for ceph commands

---

pkg/operator/ceph/cluster/osd/spec.go

If a kernel device name change happens and a block device file in the OSD directory becomes dangling link, this OSD fails to start continuously. This problem can be resolved by confirming the validity of the device file and recreating it if necessary.
Resolves #10860 
**Checklist:**

osd: handle device name change and device removel correctly

---

Documentation/Upgrade/rook-upgrade.md

'kubectl apply --server-side' still doesn't always update CRDs correctly if a CRD is too big to have its last applied annotation. Use 'kubectl replace' instead.
Resolves #
**Checklist:**

doc: use kubectl replace instead of apply for crd updates

---

.github/workflows/synk.yaml

The snyk check is failing because the -buildvcs flag is defaulting to true. Let's disable this flag to
get the check passing.
```
go: downloading github.com/josharian/intern v1.0.0
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
**Checklist:**

ci: Enable snyk flag not to build vcs

---

pkg/operator/ceph/cluster/nodedaemon/crash.go
pkg/operator/ceph/cluster/nodedaemon/crash_test.go

ceph crash pod gets rook version label added unintentionally, which is only for deployment label.
This fix along with pr 11674 is to stop ceph daemons pod restarting unnecessarily after upgrading rook operator.
Resolves #11657 
**Checklist:**

core: on crash pod ensure rook version label is not set

---

pkg/operator/ceph/cluster/osd/spec.go

Add container ports for OSD container only when multi cluster service is enabled in the cluster spec.
Resolves #11792
**Checklist:**

ceph: add osd container ports only if mcs is enabled

---

.docs/overrides/main.html

Change the "old version" hint on the docs.
Resolves https://github.com/rook/rook.github.io/issues/144
**Checklist:**

docs: change old version hint in docs

---

.github/workflows/canary-integration-test.yml
Documentation/CRDs/Cluster/external-cluster.md
deploy/examples/create-external-cluster-resources.py
pkg/operator/ceph/object/objectstore.go

if a cluster won't use the deafult realm and try to execute the python script it will fail to vaildate rgw as the rgw-admin-user would be created on default realm So creating user in specific realm if the realm name is passed
Resolves #
**Checklist:**

external: add realm support for external cluster

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md

It seems that this `deviceFilter` list item is indented too far.
This PR de-indents it one level.
**Checklist:**

Fix documentation indentation

---

deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml
deploy/examples/monitoring/localrules.yaml

When the alerts were updated from the ceph repo, the cephadm alerts were removed, now we also remove two other alerts that don't apply to rook clusters. The pool growth warning alert and prometheus job missing alerts need to be removed as also seen in #10109.
Resolves #11785 
**Checklist:**

monitoring: Remove alerts that don't apply to rook

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md
cmd/rook/ceph/ceph.go
cmd/rook/ceph/mgr.go
deploy/charts/rook-ceph-cluster/values.yaml
deploy/examples/cluster.yaml
deploy/examples/monitoring/service-monitor.yaml
pkg/apis/ceph.rook.io/v1/resources.go
pkg/operator/ceph/cluster/cluster_external.go
pkg/operator/ceph/cluster/mgr/dashboard.go
pkg/operator/ceph/cluster/mgr/dashboard_test.go
pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/cluster/mgr/mgr_test.go
pkg/operator/ceph/cluster/mgr/spec.go
pkg/operator/ceph/cluster/mgr/spec_test.go
pkg/operator/ceph/controller/spec.go
pkg/operator/ceph/controller/spec_test.go
pkg/operator/k8sutil/deployment.go
pkg/operator/k8sutil/pod.go

Revert all the commits related to the readiness probe
Resolves #11791
Closes: https://github.com/rook/rook/issues/11791
**Checklist:**

mgr: revert readiness probe and go back to the original sidecar HA implementation

---

pkg/operator/ceph/cluster/nodedaemon/exporter.go
pkg/operator/ceph/cluster/nodedaemon/exporter_test.go

The exporter requires the mon config and keyring. Use the CEPH_ARGS env var to specify the config instead of expecting a ceph.conf to be generated by another component on the host path.
Resolves: #11817 
**Checklist:**

core: Add env var to exporter for ceph config

---

.github/workflows/canary-integration-test.yml
Documentation/Storage-Configuration/Advanced/key-management-system.md
cmd/rook/secret.go
deploy/charts/library/templates/_cluster-role.tpl
deploy/charts/rook-ceph/templates/clusterrole.yaml
deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/cluster-on-pvc.yaml
deploy/examples/common-second-cluster.yaml
deploy/examples/common.yaml
deploy/examples/crds.yaml
pkg/apis/ceph.rook.io/v1/annotations.go
pkg/apis/ceph.rook.io/v1/keys.go
pkg/apis/ceph.rook.io/v1/labels.go
pkg/apis/ceph.rook.io/v1/types.go
pkg/daemon/ceph/osd/encryption.go
pkg/daemon/ceph/osd/encryption_test.go
pkg/daemon/ceph/osd/key_rotation.go
pkg/daemon/ceph/osd/kms/k8s.go
pkg/daemon/ceph/osd/kms/kms.go
pkg/operator/ceph/cluster/osd/config.go
pkg/operator/ceph/cluster/osd/create.go
pkg/operator/ceph/cluster/osd/key_rotation.go
pkg/operator/ceph/cluster/osd/key_rotation_test.go
pkg/operator/ceph/cluster/osd/osd.go
pkg/operator/k8sutil/deployment.go
tests/scripts/github-action-helper.sh

This pr implements the following:
- [core: add KeyRotationSpec to cephcluster CR](https://github.com/rook/rook/commit/5dc8f5a688c72fb95dc032d001b8b7ed47e78cae) 
- [osd: add util functions to support encryption key rotation](https://github.com/rook/rook/commit/e3d9a3a13a507842ea252d1c9a7af40fb287c1e9) 
- [ceph: add support for updating secret for default KMS](https://github.com/rook/rook/commit/9f1ea407fb4a384b63e89bcb747f7d19a89428d1) 
- [osd: add rotate-key functionality to rook's key-management cmd](https://github.com/rook/rook/commit/8abba1bbd362ded53ab16446738b3c662e1efef7) 
- [ceph: add util function to create key rotation cron job](https://github.com/rook/rook/commit/20e7b5e453822f6bafb770612e08e763392ec1ec) 
- [ceph: add capability to reconcile key …

Implement OSD encryption key rotation 

---

pkg/operator/ceph/cluster/nodedaemon/exporter.go

Missing `rook_cluster` & `ceph_daemon_id` labels on rook-ceph-exporter deployments
Resolves #11855
**Checklist:**

core: add missing labels in exporter deployment

---

tests/framework/installer/ceph_installer.go

The wait for external cluster to be ready does not seem to be sufficient.
Therefore doubling it. 
Resolves #11865 
**Checklist:**

ci: increase wait time for external cluster to be ready

---

pkg/operator/ceph/cluster/cluster_external.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/csi/cluster_config.go
pkg/operator/ceph/csi/cluster_config_test.go
pkg/operator/ceph/csi/spec.go
pkg/operator/ceph/file/subvolumegroup/controller.go
pkg/operator/ceph/pool/radosnamespace/controller.go
tests/integration/ceph_upgrade_test.go

When msgr2 is required, ensure the mon endpoints passed to the csi configmap are on port 3300. The mons will still be listening on both 6789 and 3300 if they were created before msgr2 was required. Existing volumes can continue using port 6789 while new volumes will use port 3300.
**Checklist:**

csi: Update port to 3300 if msgr2 is required

---

Documentation/CRDs/ceph-nfs-crd.md
deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/crds.yaml
pkg/apis/ceph.rook.io/v1/nfs.go
pkg/apis/ceph.rook.io/v1/types.go
pkg/operator/ceph/nfs/spec.go

Based heavily on #10491, Network mode can be set separately for cephcluster and nfs and for the same reasons.
Without this fix it is not possible to use the recommended host network configuration for ceph without also using it for any NFS servers -- and each node can only have one NFS server running on it, including if NFS is enabled on the node itself outside of kubernetes.
Resolves #10749
**Checklist:**

nfs: network mode can be set separately for cephcluster and nfs

---

.github/workflows/auto-assign.yaml

This Pr updates the behaviour of the token used by the bot
https://github.com/bdougie/take-action/commit/dae661e9a0abfafa2be0c170be1156302f4149e8
Closes: https://github.com/rook/rook/issues/11863
Resolves #
**Checklist:**

ci: update github token in auto-assign bot

---

pkg/operator/ceph/cluster/osd/osd_test.go
pkg/operator/ceph/cluster/osd/topology/topology.go
pkg/operator/ceph/cluster/osd/topology/topology_test.go

remove the duplicate topology added to the node,
and the priority to keep duplicate would be give to the one who is lowest in the hierarchy
Closes: https://github.com/rook/rook/issues/11800
Resolves #
**Checklist:**

osd: validate and remove duplicate topology

---

tests/scripts/multus-test.sh

Add a script to help evaluate environments for running multus.
Sample output
```
❯ ./deploy/tools/multus-test.sh                                                                                                     
daemonset.apps/multus-validator-1 created
daemonset.apps/multus-validator-2 created
daemonset.apps/multus-validator-3 created
daemonset.apps/multus-validator-4 created
daemonset.apps/multus-validator-5 created
daemonset.apps/multus-validator-6 created
daemonset.apps/multus-validator-7 created
daemonset.apps/multus-validator-8 created
daemonset.apps/multus-validator-9 created
daemonset.apps/multus-validator-10 created
daemonset.apps/multus-validator-11 created
daemonset.apps/multus-validator-12 created
daemonset.apps/multus-validator-13 created
daemonset.apps/multus-validator-14 …
```

docs: add script to help evaluate environments for multus

---

deploy/examples/create-external-cluster-resources.py
deploy/examples/import-external-cluster.sh

Pool and Metadata Pool Appear to be reversed causing PVC creation to fail
It seems the data-pool and EC pool on an external cluster are set the wrong way round in the example code for configuring external clusters
dataPool: needs to contain the EC Data pool
pool: needs to contain the Metadata Pool
Resolves 
https://github.com/rook/rook/issues/11918

external: pool and metadata ec pools were reversed in scripts

---

deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/crds.yaml
pkg/apis/ceph.rook.io/v1/object.go
pkg/apis/ceph.rook.io/v1/types.go
pkg/operator/ceph/object/rgw.go

make rgw dashboard configurable by custom when create objectstore
Resolves #
[11884](https://github.com/rook/rook/discussions/11884)
**Checklist:**

rgw: enableRGWDashboard can be configured by custom

---

pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/cluster_test.go
pkg/operator/ceph/config/monstore.go

The operator will now correctly use the messenger v2 protocol if compression is enabled.
Resolves #11795
**Checklist:**

operator: use msgr2 if compression is enabled

---

deploy/examples/create-external-cluster-resources-tests.py
deploy/examples/create-external-cluster-resources.py

Replace the old formatting method with the f-string and fix few pylint errors
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>
(cherry picked from commit (6dbbc9d)
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>
Resolves #
**Checklist:**

external: use f-strings for formatting

---

pkg/daemon/ceph/osd/daemon.go
pkg/daemon/ceph/osd/device.go
pkg/daemon/ceph/osd/device_test.go
pkg/util/sys/device_test.go

Rook uses global or node-local device class configuration if device-level configuratios doesn't exist. However, after introducing device-class level resource configuration, rook set the default value of device class. So global or node-level device class configuration has never been used after that.
Resolves #11826 #11871
**Checklist:**

osd: handle global or node-local device class configuration correctly

---

pkg/daemon/ceph/client/config.go

This should correct formatting of IPv6 `mon_hosts` in the config file when `requireMsgr2: true` is set on cluster creation.
Resolves #11977
**Checklist:**

core: fix config format for msgr2 ipv6 monitors

---

.github/workflows/canary-integration-test.yml
deploy/examples/create-external-cluster-resources.py

if the rgw endpoint is not reachable don't block the creation of rbd and cephfs sc, just print the error instead of raising an exception
Resolves #
**Checklist:**

external: make rgw call separate from cephfs and rbd

---

pkg/operator/ceph/object/notification/controller_test.go
pkg/operator/ceph/object/notification/obc_label_controller.go
pkg/operator/ceph/object/notification/obc_label_controller_test.go

obc-label-controller needs to check only the obc provisioned by the Rook operator.
Check other OBCs result in errors from the controller and keep on reconcilling
Resolves #
**Checklist:**

object: check obc provisioner for bucket notification

---

.github/workflows/canary-integration-test.yml
deploy/examples/cluster-test.yaml
tests/scripts/github-action-helper.sh

The canary test is waiting for the prometheus module, which is now disabled by default. Instead, wait for the dashboard module to respond. This test has been failing since #11980 was merged. 
**Checklist:**

ci: Canary test should enable prometheus module for the external cluster test

---

pkg/operator/ceph/nfs/spec.go

NFS-Ganesha (as of V5-dev.2 [1]) supports Prometheus monitoring from within the NFS server itself. It provides metrics for both connected clients and active exports, via TCP port 9587. Expose those metrics via standard K8S service.
[1] https://github.com/nfs-ganesha/nfs-ganesha/commit/b6c59df5a0b8a3ae5b2a87446f8906cb321ee026
Resolves #
**Checklist:**

nfs: add support for nfs-ganesha metrics monitoring

---

.vscode/extensions.json
build/makelib/common.mk
build/release/Makefile
images/image.mk
tests/scripts/build-release.sh

This helps forks build custom rook releases more easily by allowing
certain Makefile vars to be overwriten using a `.env` file.
In addition this introduces the `DOCKERCMD` var to the
`build/release/Makefile`.
Resolved #11701
**Checklist:**

build: allow overriding variables from a dot env file

---

tests/scripts/build-release.sh

The `DOCS_GIT_REPO` var needs to be exported when not set through a `.env` file, as otherwise it is not propagated to commands run in the `build-release.sh` script.
Based on my current investigation this should solve the issue for the `master` release issue introduced by the #11968.
I couldn't test it yet, because the tmate CI debug step doesn't have the CI secrets attached to it. I can do a test run by modifying the CI file to include the secrets but I don't want to accidentally expose any of the secrets.
**Checklist:**

build: fix publish docs step

---

deploy/examples/create-external-cluster-resources.py

external: name correction of validate_rgw_metadata_ec_pool_name function
The function is used for rbd so it should be name to validate_rbd_metadata_ec_pool_name
Resolves #
**Checklist:**

external: name correction of validate_rgw_metadata_ec_pool_name function

---

pkg/operator/ceph/cluster/mgr/dashboard.go
pkg/operator/ceph/cluster/mgr/dashboard_test.go

Firstly we use the port 443 or 6443 to mgr dashboard, but it was used by other daemon; The dashboard will start failed and the status of the ceph will be HEALTH_ERR; then we update the port to a unused port，the operator can not deal with it. after this change,  dashboard can start normally and the status of ceph will be HEALTH_OK.
Resolves #11931 
**Checklist:**

mgr: failed to update the port of dashboard

---

deploy/examples/import-external-cluster.sh

there might be a user who only wants to use rbd, so don't enforce them
to to create all the pools and pass the flags
Closes: https://github.com/rook/rook/issues/11846
Resolves #
**Checklist:**

external: do not enforce rbd, cephfs and rgw flags for the external cluster

---

.github/workflows/canary-integration-test.yml
tests/scripts/validate_cluster.sh

For the RGW daemon validation please check whether pod is Running than the existing checks
Resolves #11743
**Checklist:**

test: check rgw pod is running for canary github workflow

---

Documentation/Helm-Charts/operator-chart.md
deploy/charts/rook-ceph/templates/deployment.yaml
deploy/charts/rook-ceph/values.yaml

Some administrative actions require the user to scale down the rook operator to zero replicas to stop any potential conflicts where the operator is attempting to do something contrary to the current goals of the administrator.
Addresses #11927
**Checklist:**

helm: add option to scale down rook operator

---

deploy/charts/rook-ceph-cluster/templates/volumesnapshotclass.yaml
deploy/examples/csi/cephfs/snapshot.yaml
deploy/examples/csi/cephfs/snapshotclass.yaml
deploy/examples/csi/rbd/snapshot.yaml
deploy/examples/csi/rbd/snapshotclass.yaml

drop snapshot.storage.k8s.io/v1beta1, v1 exists since k8s v1.20.
Resolves #
**Checklist:**

helm: drop snapshot.storage.k8s.io/v1beta1

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md
Documentation/CRDs/Cluster/external-cluster.md
Documentation/CRDs/Cluster/host-cluster.md
Documentation/CRDs/Cluster/pvc-cluster.md
Documentation/CRDs/Cluster/stretch-cluster.md
Documentation/Upgrade/ceph-upgrade.md
deploy/charts/rook-ceph-cluster/values.yaml
deploy/examples/cluster-external-management.yaml
deploy/examples/cluster-on-local-pvc.yaml
deploy/examples/cluster-on-pvc.yaml
deploy/examples/cluster-stretched-aws.yaml
deploy/examples/cluster-stretched.yaml
deploy/examples/cluster.yaml
deploy/examples/images.txt
deploy/examples/toolbox.yaml
deploy/olm/assemble/metadata-common.yaml
design/ceph/ceph-cluster-cleanup.md
images/ceph/Makefile
pkg/operator/ceph/object/spec_test.go
tests/manifests/test-cluster-on-pvc-encrypted.yaml

With the release of ceph v17.2.6, the examples and the base image for the operator are updated to pick up the latest and greatest.
Resolves: #11656 
**Checklist:**

core: Update default image to Ceph v17.2.6

---

Documentation/CRDs/Cluster/external-cluster.md
deploy/examples/create-external-cluster-resources.py

if restricted permission was on the . was appended to k8s secret and failed to create the secret so added a alias name is user wan't to suuport pool with . in name
Resolves #
**Checklist:**

external: add alias rbd pool name to support . pools name

---

pkg/operator/ceph/cluster/nodedaemon/exporter.go
pkg/operator/ceph/cluster/nodedaemon/exporter_test.go

The expected ceph version for exporter is changed temporarily because some regression was detected in Ceph version 17.2.6 which is summarised here https://github.com/ceph/ceph/pull/50718#issuecomment-1505608312. Thus, disabling ceph-exporter for now until all the regression are fixed.
Resolves #
**Checklist:**

core: disable exporter  for Ceph v17.2.6

---

.github/workflows/canary-integration-test.yml
Documentation/CRDs/Cluster/external-cluster.md
deploy/examples/create-external-cluster-resources-tests.py
deploy/examples/create-external-cluster-resources.py

Add --skip-monitoring-endpoint to create-external-cluster-resources.py to allow the script to work with Ceph clusters without an enabled prometheus module.
Did not create an issue as this should be a straightforward change, similar to https://github.com/rook/rook/commit/e734911532802451755356b58df9f27b761f477b
**Checklist:**

external: do not enforce need for monitoring endpoint

---

.github/workflows/canary-integration-test.yml
Documentation/CRDs/Cluster/external-cluster.md
deploy/examples/create-external-cluster-resources.py

Add support for realm, zone and zonegroup
Resolves # https://github.com/rook/rook/issues/11806
**Checklist:**

external: add support for multisite in external cluster script

---

pkg/operator/ceph/nfs/security.go
pkg/operator/ceph/nfs/spec.go

While testing kerberos mounting of CephNFS resources, I came across a few problems which prevent the use of the CephNFS share being used with kerberos authentication. This  set of changes fix a part of the problems we see with mounting cephNFS shares using kerberos.
https://github.com/rook/rook/issues/11870
https://github.com/rook/rook/issues/11925
**Checklist:**
- [*] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [*] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [*] Reviewed the developer guide on [Submitting a Pull …

CephNFS: Some fixes for mounting CephNFS using Kerberos auth

---

Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md

During reconciliation of cephobjectstore, Rook operator resets the value
of replica count by the HPA and HPA brings back it up when it notices
the desired count for replica change.
Resolves #
**Checklist:**

docs: mention about reconciliation issue in hpa docs

---

pkg/operator/ceph/cluster/nodedaemon/exporter.go
pkg/operator/ceph/cluster/nodedaemon/reconcile.go

The exporter service should only be created if exporter pods are created. Recently the creation was disabled temporarily due to some regression detected in Ceph v17.2.6 https://github.com/rook/rook/pull/12077
Create the exporter service only if exporter pods are created.
Resolves #
**Checklist:**

core: temporary disable exporter service

---

pkg/operator/ceph/object/bucket/controller.go
pkg/operator/ceph/object/controller.go
pkg/operator/ceph/object/notification/controller.go

Skip running Object Bucket controllers when the env ROOK_DISABLE_OBJECT_BUCKET_CLAIM is true
Resolves #
**Checklist:**
Tested on single node minikube cluster. Didn't deploy any objectbucket.io group crds.
NAME                                         CREATED AT
cephblockpoolradosnamespaces.ceph.rook.io    2023-04-19T03:52:00Z
cephblockpools.ceph.rook.io                  2023-04-19T03:52:00Z
cephbucketnotifications.ceph.rook.io         2023-04-19T03:52:00Z
cephbuckettopics.ceph.rook.io                2023-04-19T03:52:00Z
cephclients.ceph.rook.io                     2023-04-19T03:52:00Z
cephclusters.ceph.rook.io                    2023-04-19T03:52:00Z
cephfilesystemmirrors.ceph.rook.io …

core: Skip OBC controllers based on env variable

---

deploy/charts/rook-ceph-cluster/values.yaml
deploy/examples/cluster.yaml
pkg/apis/ceph.rook.io/v1/spec_test.go
pkg/operator/ceph/cluster/osd/config/config.go
tests/framework/installer/ceph_manifests.go

The journal size was only applicable to the filestore OSD format which has not been supported by rook since v1.2. Remove the remaining obsolete setting from the examples and code.
Resolves #12126
**Checklist:**

core: Remove obsolete journal size config value

---

deploy/examples/create-external-cluster-resources.py

While adding the support for dot and special rbd pools the check for pool and cluster name check was removed, Adding it back as it is needed
https://github.com/rook/rook/pull/12056
Resolves #
**Checklist:**

external: check for pool and cluster name is provided

---

pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/cluster/mgr/spec.go

The active and standby labels are updated on the mgr pods by the mgr sidecar. In the case of a single mgr, there is not sidecar, so the dashboard and other mgr services were not available when there was a single mgr. Now the mgr pod will default to the active mgr status label so that the single mgr case will succeed. In the case of two mgrs, the sidecar will immediately update the standby mgr to remove the active status label.
This issue was only affecting test deployments from master since #11845 hasn't yet been backported.
**Checklist:**

mgr: Default to active mgr label

---

.github/PULL_REQUEST_TEMPLATE.md

- The pr template has an extra parenthesis that is now removed.
- Make the developer guide URL more discoverable since the comment is not rendered as markdown.
**Checklist:**

docs: Update the PR template for a typo and more easily discoverable dev guide link

---

cmd/rook/rook/rook.go
cmd/rook/userfacing/multus/validation/validation.go

Use contents of KUBECONFIG var for creating Kubernetes client interface if its present. This allows running rook CLI commands locally for quicker development iteration.
Resolves #
**Checklist:**

operator: use KUBECONFIG context for cli if present

---

pkg/operator/ceph/cr_manager.go

As we are not using the controller runtime metrics we dont even need to start the server as it just uses extra resources and its not much useful.
* Before disabling the metrics port
```bash
sh-4.4# netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp6       0      0 :::8080                 :::*                    LISTEN      1/rook              
sh-4.4# 
```
* After Disabling the metrics port
```bash
sh-4.4# netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
sh-4.4# 
```
Resolves # …

core: disable controller runtime metrics server

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md
Documentation/CRDs/specification.md
deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/cluster.yaml
deploy/examples/crds.yaml
design/ceph/ceph-exporter.md
pkg/apis/ceph.rook.io/v1/types.go
pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/cluster/mgr/mgr_test.go
pkg/operator/ceph/cluster/nodedaemon/exporter.go
pkg/operator/ceph/cluster/nodedaemon/reconcile.go

The prometheus mgr module and ceph exporter can now be optionally disabled by the monitoring.metricsDisabled setting in the CephCluster CR. These will not be disabled by default, rather than the mgr module being disabled by default from v1.11.4.
@avanthakkar This means that if we have a ceph version that supports the exporter, the exporter will be enabled by default, so we will need to fix #11831 before enabling the exporter again.
Resolves #12097 
**Checklist:**

monitoring: Configurable option to disable prometheus metrics

---

Documentation/Helm-Charts/operator-chart.md
deploy/charts/rook-ceph/templates/servicemonitor.yaml
deploy/charts/rook-ceph/values.yaml

implement https://github.com/rook/rook/blob/master/deploy/examples/monitoring/csi-metrics-service-monitor.yaml in the helm chart
Resolves #
**Checklist:**

servicemonitor for rook-ceph csi drivers

---

.github/workflows/build_dependabot_bundler_pr.yml
.github/workflows/update_dependabot_bundler_pr.yml

Golang module sync on dependabot PR, should force-sync Golang module data from root to API.
This is roughly based on https://github.com/dependabot/dependabot-actions-workflow/blob/main/.github/workflows/update_dependabot_bundler_pr.yml

build: run Golang module sync on dependabot PR

---

pkg/operator/ceph/cluster/nodedaemon/exporter.go

Shorten the termination time for exporter pod before it gets deleted to avoid crashing of pod.
Add termination grace period for exporter pods to avoid crash.
Resolves #11831
**Checklist:**

core: add termination grace period for exporter pods

---

pkg/operator/ceph/cluster/nodedaemon/reconcile.go

The exporter is enabled by default, but the service monitor can only be enabled if prometheus CRDs are available. The `monitoring.enabled` must be set to true as the flag that prometheus is available and the service monitor should be created.
This is a follow-up to a regression caused by #12193 that I found when testing other exporter changes.
**Checklist:**

monitoring: Skip creating the service monitor for the exporter if monitoring is not enabled

---

pkg/operator/ceph/cluster/rbd/controller.go

The rbd mirror reconcile was not re-queuing the reconcile if the cephcluster was not initialized. All other controllers waiting for the initialization are requeuing the event, just not the rbd mirror controller.
**Checklist:**

rbdmirror: Retry reconcile if cluster not initialized

---

cmd/rook/userfacing/multus/validation/validation.go
pkg/daemon/multus/client-daemonset.yaml
pkg/daemon/multus/image-pull-daemonset.yaml
pkg/daemon/multus/nginx-pod.yaml
pkg/daemon/multus/resources.go
pkg/daemon/multus/templates.go
pkg/daemon/multus/validation.go

Before starting multus validation test clients, pull the client image to all nodes. This will ensure that variations in client readiness timing will not be affected by variations in the time nodes take to pull the image. This is intended to reduce the number of false reports of flaky multus networks.
Resolves #
**Checklist:**

operator: pull multus validation test images before test

---

deploy/examples/monitoring/service-monitor.yaml

The service monitor selectors need to match the mgr service labels. Since the mgr service labels don't use the mgr_role (only the mgr service selectors use the mgr_role), the mgr_role should be removed from the service monitor.
Related to #12249 
**Checklist:**

monitoring: Service monitor should not use mgr_role label

---

cmd/rook/userfacing/multus/validation/validation.go
pkg/daemon/multus/client-daemonset.yaml
pkg/daemon/multus/image-pull-daemonset.yaml
pkg/daemon/multus/nginx-pod.yaml
pkg/daemon/multus/templates.go
pkg/daemon/multus/validation.go

- allow overriding the nginx server image for multus-validation-test-web-server from CLI using `--nginx-image` flag
- default image will be **nginxinc/nginx-unprivileged:stable-alpine**
Resolves #12175 
CC @BlaineEXE 
**Checklist:**

test: allow specifying custom nginx image for multus validation

---

tests/scripts/tmate-pod.yaml

Add a tmate manifest that can be added to CI tests to allow manually debugging them in real-time while the test is ongoing.
I found this method to be working for another repo I was trying to debug. I quickly added the manifest and usage here with the intent that we can decide when and how often to use it at a later point. And we can always enable it manually and temporarily for any PR we are struggling with.
Resolves #
**Checklist:**

test: add tmate pod manifest

---

pkg/operator/ceph/object/admin.go
pkg/operator/ceph/object/admin_test.go
pkg/operator/ceph/object/bucket/provisioner.go
pkg/operator/ceph/object/bucket/util.go
pkg/operator/ceph/object/controller.go
pkg/operator/ceph/object/notification/provisioner.go
pkg/operator/ceph/object/topic/provisioner.go
pkg/operator/ceph/object/user/controller.go

The ceph cluster spec need to set on object context for executing radosgw-admin commands if multus is enabled.
The radosgw-admin command uses the network spec from ceph cluster spec
in object context but it is not filled properly in the object package.
But with PR 10898, network spec is available in clusterinfo which can
be used directly. Also removed cluserspec from object context.
Resolves #
**Checklist:**

object: add missing cephcluster spec addition in object controller

---

pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/cluster/nodedaemon/exporter.go
pkg/operator/k8sutil/prometheus.go
pkg/operator/k8sutil/prometheus_test.go

When deploying a cluster with Helm Chart, if the namespace is not the default value `rook-ceph`, and if the monitoring feature is enabled, then the generated ServiceMonitor's `rook_cluster` selector now follows the namespace, not the hard-coded value `rook-ceph`.
1. Deploy a rook-ceph cluster (rook-ceph, rook-ceph-cluster) with Helm Chart.
- With modifying the namespace to `my-rook-ceph`
- With enabling the feature `monitoring`
1. Command `kubectl -n csi-rook-ceph get servicemonitor rook-ceph-mgr -o jsonpath --template '{.spec.selector.matchLabels.rook_cluster}'`
1. Before patch, the command output should be `rook-ceph`.
- After patch, it should be `my-rook-ceph`.
Resolves #
**Checklist:**

mgr: update default rook_cluster of ServiceMonitor

---

.github/workflows/canary-integration-test.yml
.github/workflows/integration-test-helm-suite.yaml
.github/workflows/integration-test-mgr-suite.yaml
.github/workflows/integration-test-multi-cluster-suite.yaml
.github/workflows/integration-test-object-suite.yaml
.github/workflows/integration-test-smoke-suite.yaml
.github/workflows/integration-test-upgrade-suite.yaml

Updating GitHub Actions Workflows so it ignores the documentations changes.
Resolves #12287 
**Checklist:**

ci: adding path ignore to documentations
